### ISSUE TITLE
@nuxt/webpack uses outdated cssnano version

### ISSUE THREAD

**Issue by martynaskre** [nuxt/nuxt#10587]
### Versions

- nuxt: v2.15.7
- node: v16.16.0

`@nuxt/webpack` uses outdated `cssnano` version which causes bugs if using it with `tailwind:^3.0.0`. Required fixes were made in `cssnano` [repo](https://github.com/cssnano/cssnano/issues/1350#event-6219603890).

Adding `cssnano:^5.1.12` to [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) causes build step to fail with:

```
ERROR  this.options.cssProcessor.process is not a function           21:41:37

  at OptimizeCssAssetsWebpackPlugin.processCss (node_modules/optimize-css-assets-webpack-plugin/src/index.js:73:21)
  at Object.processor (node_modules/optimize-css-assets-webpack-plugin/src/index.js:13:18)
  at node_modules/last-call-webpack-plugin/src/index.js:150:10
  at arrayEach (node_modules/lodash/_arrayEach.js:15:9)
  at forEach (node_modules/lodash/forEach.js:38:10)
  at OptimizeCssAssetsWebpackPlugin.process (node_modules/last-call-webpack-plugin/src/index.js:147:5)
  at node_modules/last-call-webpack-plugin/src/index.js:178:28
  at _next0 (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:17)
  at eval (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ```

**Comment by EPuluikis** [comment]
Same here. Project can't be launched because of this issue.

**Comment by danielroe** [comment]
This is now resolved.
