### ISSUE TITLE
RROR Cannot set property del of #<LRUCache> which has only a getter

### ISSUE THREAD

**Issue by AlexeyNaum** [nuxt/nuxt#10737]
Hi there! I've got the magic bug:

ERROR Cannot set property del of #<LRUCache> which has only a getter 15:09:29

at node_modules/axios-extensions/lib/index.js:22:25
at Object.<anonymous> (node_modules/axios-extensions/lib/index.js:26:2)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:101:18)
at node_modules/vue-server-renderer/[build.prod](http://build.prod/).js:1:76519
at Object.<anonymous> (webpack:/external "axios-extensions":1:0)

How can i fix it?? Everything worked well, but today I caught such a trouble. The problem only applies to the PRODUCT

**Comment by tukao89** [comment]
@AlexeyNaum , Try to downgrade version of package: axios-extensions to 3.1.3
