### ISSUE TITLE
使用npm run generate打包动态页面时出现错误

### ISSUE THREAD

**Issue by luhao514** [nuxt/nuxt#10826]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
运行npm run generate

### What is actually happening?
以下为控制台部分报错
....................
HTML minification failed. Make sure the route generates valid HTML. Failed HTML:
....................
Request failed with status code 503                                                                                                                                                                                      
  at createError (node_modules\axios\lib\core\createError.js:16:15)
  at settle (node_modules\axios\lib\core\settle.js:17:12)
  at Unzip.handleStreamEnd (node_modules\axios\lib\adapters\http.js:269:11)
  at Unzip.emit (node:events:513:28)
  at endReadableNT (node:internal/streams/readable:1358:12)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by manniL** [comment]
Seems like an API call fails with 503 while generating the pages.

Closing here as stale but if you can provide more info, please do so and I'll reopen it 👍🏻
