### ISSUE TITLE
Nuxt2 SCSS compilation issue

### ISSUE THREAD

**Issue by gkurl** [nuxt/nuxt#10860]
### Versions

- nuxt: 2.15.8
- node: 16.18.1

### Reproduction

Repo: https://gitlab.com/gkurl/vapedcrusader

### Steps to reproduce

I'm running `yarn run build` and receive compilation error:

```
ERROR in ./components/AppNavigation.vue?vue&type=style&index=0&id=c72ea0a0&prod&lang=scss& (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./components/AppNavigation.vue?vue&type=style&index=0&id=c72ea0a0&prod&lang=scss&)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 23
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/components/AppNavigation.vue:1:198660
    at Parser.error (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-values-parser/lib/parser.js:162:20)
    at Parser.parseTokens (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-custom-properties/index.cjs.js:333:24
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:194:18
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:139:18
    at Rule.each (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:105:16)
    at Rule.walk (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:135:17)
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:152:24
    at Root.each (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:105:16)
    at Root.walk (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:135:17)
    at Root.walkDecls (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:192:19)
    at transformProperties (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-custom-properties/index.cjs.js:330:8)
    at Object.syncTransform [as plugin] (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-custom-properties/index.cjs.js:522:5)
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-preset-env/index.js:459:97
 @ ./components/AppNavigation.vue?vue&type=style&index=0&id=c72ea0a0&prod&lang=scss& (./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./components/AppNavigation.vue?vue&type=style&index=0&id=c72ea0a0&prod&lang=scss&) 4:14-450
 @ ./components/AppNavigation.vue?vue&type=style&index=0&id=c72ea0a0&prod&lang=scss&
 @ ./components/AppNavigation.vue
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

 FATAL  Nuxt build error                                                                                                                                                12:55:50

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:110:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)
```

I'm using `lang=scss` and `scss` files throughout - I've ensured I have `sass-loader@10` and `sass` installed. Anyone should be able to clone to repo down and try to reproduce. Running `yarn run dev` works fine and the site is up and running.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. This is advance warning that I'm going to close this issue then, as it's currently marked as a Nuxt 2 related bug.

If it's a critical or security issue, please do comment and let me know, in case it is possible to address it before the EOL date.

If it's a an issue you think is relevant for Nuxt 3, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏

Thank you for your understanding and for your contribution to Nuxt. ❤️

**Comment by danielroe** [comment]
It's the day, at last. Nuxt 2 is now [marked end-of-life](https://nuxt.com/blog/nuxt2-eol).

My apologies we never got round to resolving this bug in the 2.x branch, but we do have to draw a line somewhere. Again, if you think this is still relevant for Nuxt going forward, please feel free to open a fresh issue (or just comment here so I can update labels, etc.). 🙏
