### ISSUE TITLE
incompatible with paths with `'` in the filename

### ISSUE THREAD

**Issue by jaguarsiva** [nuxt/nuxt#12909]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27296423.f3082ca`
- Package Manager:  `npm@6.14.15`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I haven't wrote even a single line of code. I just installed nuxt3 using `npx nuxi init nuxt3-app`, changed directory and installed the dependencies using `npm install`. Without even touching a single file, I ran `npm run dev` and it doesn't even show the `<NuxtWelcome />` page to me in the browser. The loading page keeps on spinning.

### Describe the bug

The loading page keeps on spinning in the browser. I could see vite build it successfully and then a error message and a few warnings thrown into the terminal [ attached below ].

### Logs

```shell
[SSR] Error transforming virtual:<Mypath here>/.nuxt/plugins/server.mjs: Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.


 WARN  [SSR] Error transforming[SSR] Error transforming virtual:<Mypath here>/.nuxt/plugins/server.mjs: Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.


 WARN  [SSR] Error transforming virtual:<Mypath here>/.nuxt/root-component.mjs: Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.


 WARN  [SSR] Error transforming virtual:<Mypath here>/.nuxt/app-component.mjs: Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

√ Vite server built in 1133ms                                                   11:58:41  
√ Nitro built in 328 ms                                                         11:58:42  

 ERROR  [worker] Unexpected identifier                                          11:58:42  

  at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
  at async link (internal/modules/esm/module_job.js:67:21)


 WARN  [worker] Unexpected identifier                                           11:58:42  

  at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
  at async link (internal/modules/esm/module_job.js:67:21)/.nuxt/root-component.mjs: Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.


 WARN  [SSR] Error transforming virtual:C:/Siva's Web Dev Files/Projects/Portfolio Revamp/nuxt3-app/.nuxt/app-component.mjs: Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

√ Vite server built in 1133ms                                                   11:58:41  
√ Nitro built in 328 ms                                                         11:58:42  

 ERROR  [worker] Unexpected identifier                                          11:58:42  

  at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
  at async link (internal/modules/esm/module_job.js:67:21)


 WARN  [worker] Unexpected identifier                                           11:58:42  

  at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
  at async link (internal/modules/esm/module_job.js:67:21)
```

**Comment by madebyfabian** [comment]
Filenames with `'` are not common and will cause issues anywhere. Upstream closed. Would suggest to close this.
