### ISSUE TITLE
inconsistent behavior of route middlewares 

### ISSUE THREAD

**Issue by mercs600** [nuxt/nuxt#14473]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

this is module, please run `yarn dev:prepare` before `yarn dev`
https://codesandbox.io/s/ancient-sea-noh9rh?file=/README.md

https://stackblitz.com/edit/node-89wpqd?file=playground%2Fnuxt.config.ts

https://github.com/mercs600/nuxt3-middleware-issue.git

### Describe the bug

✋
I have noticed weird behavior when I work with route middlewares attached by module. 
I reproduced repository when you can check route middleware attached by file in middleware directory and also the same middleware but attached by plugin. 

https://github.com/mercs600/nuxt3-middleware-issue/blob/main/playground/middleware/example.global.ts 

https://github.com/mercs600/nuxt3-middleware-issue/blob/main/src/runtime/plugin.ts 

These middlewares do the same work - resolve async function and set some state. 

When I use middleware from plugin I get `500 error: nuxt instance unavailable`
When I use middleware from `playground/middleware` directory it works. 

Should we expect some different behavior between middlewares from application and attach by modules ? 

In the reproduce app you can enable middleware in plugin by nuxt.config (by default it use middleware from directory)
```js
export default defineNuxtConfig({
  modules: [MyModule],
  myModule: {
    addPlugin: true,
  },
});
```

### Logs

```shell
[h3] [unhandled] H3Error: nuxt instance unavailable
    at createError (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/node_modules/h3/dist/index.mjs:196:15)
    at Server.nodeHandler (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/node_modules/h3/dist/index.mjs:386:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] nuxt instance unavailable
  at createError (./node_modules/h3/dist/index.mjs:196:15)
  at Server.nodeHandler (./node_modules/h3/dist/index.mjs:386:21)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
[Vue Router warn]: uncaught error during route navigation:
Error: nuxt instance unavailable
    at Module.useNuxtApp (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/playground/.nuxt/dist/server/server.mjs:411:13)
    at Module.useState (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/playground/.nuxt/dist/server/server.mjs:837:38)
    at Module.useExampleState2 (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/playground/.nuxt/dist/server/server.mjs:2923:46)
    at __vite_ssr_import_0__.addRouteMiddleware.global (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/playground/.nuxt/dist/server/server.mjs:2960:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.callAsync (file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/node_modules/unctx/dist/index.mjs:45:16)
    at async file:///Users/merc/Projects/Poligon/nuxt-module-middlwares/modules/mymodule/playground/.nuxt/dist/server/server.mjs:2533:22
```

**Comment by dargmuesli** [comment]
Actually, it now works for me to use `defineNuxtRouteMiddleware` in `definePageMeta`'s `middleware: []`

**Comment by danielroe** [comment]
(It is now implemented upstream, via https://github.com/unjs/unctx/pull/69.)
