### ISSUE TITLE
@vitejs/plugin-legacy does not build

### ISSUE THREAD

**Issue by andresespinosapc** [nuxt/nuxt#14634]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-qzrpnn?file=nuxt.config.ts

### Describe the bug

When adding the Vite plugin `@vitejs/plugin-legacy` and trying to build using `nuxt build` I get an error.

The error does not happen when using a clean Vite project, so I guess it is related to Nuxt.

### Logs

```shell
ERROR  [vite:terser] _require2 is not defined                                                            11:12:21


 ERROR  [vite:legacy-generate-polyfill-chunk] _require2 is not defined                                    11:12:21


 ERROR  _require2 is not defined                                                                          11:12:21

  at doWork (eval at __global_eval__ (https://github-qzrpnn.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:8:32190), <anonymous>:5:20)
  at _0x51acfb.eval (eval at __global_eval__ (https://github-qzrpnn.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:8:32190), <anonymous>:12:21)
  at [nodejs.internal.kHybridDispatch] (https://github-qzrpnn.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:353083)
  at t.emitMessage (https://github-qzrpnn.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:1031392)
  at _started.<computed>._source.<computed> (https://github-qzrpnn.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:103757)
```

**Comment by uovol** [comment]
I have the same problem

**Comment by fahmifitu** [comment]
After testing, this issue doesn't replicate in latest nuxt (3.2.2). The project can be built and ran successfully with @vitejs/plugin-legacy. I can see the legacy scripts included in the browser

<img width="748" alt="Screenshot 2023-02-28 at 1 32 03 PM" src="https://user-images.githubusercontent.com/24812043/221841606-5c4193c2-62c8-4f33-811d-f27af4f2eceb.png">

Raising this error in the console 

<img width="606" alt="Screenshot 2023-02-28 at 1 32 33 PM" src="https://user-images.githubusercontent.com/24812043/221841695-19412518-b043-405b-9eb3-a882cb3ac6d4.png">

here's reproduction: https://stackblitz.com/edit/github-8lcbw5?file=nuxt.config.ts

npm run build && node .output/server/index.mjs

**Comment by danielroe** [comment]
Great. Closing in favour of https://github.com/nuxt/nuxt/issues/15464.
