### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in statusMessage

### ISSUE THREAD

**Issue by melrefaie** [nuxt/nuxt#14688]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.5`
- Builder:          `vite`
- User Config:      `css`, `vite`, `modules`, `buildModules`, `runtimeConfig`, `publicRuntimeConfig`
- Runtime Modules:  `nuxt-graphql-client@0.1.12`, `@vueuse/nuxt@9.1.0`, `nuxt-icons@2.0.1`
- Build Modules:    `@pinia/nuxt@0.4.1`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-d75xgh?file=app.vue

### Describe the bug

When createError with arabic status message i got this error
```
throw createError({ statusCode: 404, statusMessage: 'الصفحة غير موجودة' });
```
------------------------------
Works fine if statusMessage english

------------------------------

### Logs

```shell
[Vue warn]: Unhandled error during execution of setup function 
  at <App>
[nitro] [dev] [unhandledRejection] H3Error: الصفحة غير موجودة
    at Module.createError (file:///home/projects/github-d75xgh/node_modules/h3/dist/index.mjs:317:15)
    at Module.createError (file:///home/projects/github-d75xgh/.nuxt/dist/server/server.mjs:954:38)
    at setup (file:///home/projects/github-d75xgh/.nuxt/dist/server/server.mjs:3390:33)
    at _sfc_main.setup (file:///home/projects/github-d75xgh/.nuxt/dist/server/server.mjs:3412:23)
    at callWithErrorHandling (/home/projects/github-d75xgh/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at setupStatefulComponent (/home/projects/github-d75xgh/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7084:29)
    at setupComponent (/home/projects/github-d75xgh/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7039:11)
    at renderComponentVNode (/home/projects/github-d75xgh/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)
    at Module.ssrRenderComponent (/home/projects/github-d75xgh/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at default (file:///home/projects/github-d75xgh/.nuxt/dist/server/server.mjs:2828:37) {
  statusCode: 404,
  fatal: false,
  unhandled: false,
  statusMessage: 'الصفحة غير موجودة',
  __nuxt_error: true
}
[nitro] [dev] [unhandledRejection] TypeError [ERR_INVALID_CHAR]: Invalid character in statusMessage
    at TypeError.get (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:292488)
    at getStackString (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:103713)
    at https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:99367
    at https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:101164
    at formatValue (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:103550)
    at inspect (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:92243)
    at formatWithOptionsInternal (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:115079)
    at formatWithOptions (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:116334)
    at console.value (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:1056556)
    at console.warn (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:1056650)
    at console.consoleCall (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:15:372509)
    at process.eval (file:///home/projects/github-d75xgh/.nuxt/dev/index.mjs:449:53)
    at EventEmitter.emit (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:155574)
    at emit (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:1073017)
    at processPromiseRejections (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:1075519)
    at processTicksAndRejections (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:6:797464)
    at _0x4041a5 (https://github-d75xgh.w.staticblitz.com/blitz.df64f655701fde45529fa8e152b3842072335b47.js:8:258812) {
  code: 'ERR_INVALID_CHAR'
```
```

**Comment by siavcom** [comment]
remove  all characters 13 and characters 10 (return, line feed) from statusMessage
