### ISSUE TITLE
fix: template uses lang html for template, however it is not installed

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/nuxt#14815]
### Environment

- Operating System: `Linux`
- Node Version:     `v14.19.3`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `telemetry`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://codesandbox.io/s/template-lang-html-dzr7f2?file=/pages/index.vue

### Describe the bug

Setting `lang="html"` on a template tag yields the following error in `@vitejs/plugin-vue`:
```
 ERROR  Component /.../pages/index.vue uses lang html for template, however it is not installed.         19:16:56

  at error (node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at throwPluginError (node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:21764:12)
  at Object.error (node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:22486:20)
  at Object.error (node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:21941:42)
  at node_modules/.pnpm/@vitejs+plugin-vue@3.1.0_vite@3.0.9+vue@3.2.38/node_modules/@vitejs/plugin-vue/dist/index.mjs:161:32
  at Array.forEach (<anonymous>)
  at compile (node_modules/.pnpm/@vitejs+plugin-vue@3.1.0_vite@3.0.9+vue@3.2.38/node_modules/@vitejs/plugin-vue/dist/index.mjs:160:19)
  at transformTemplateAsModule (node_modules/.pnpm/@vitejs+plugin-vue@3.1.0_vite@3.0.9+vue@3.2.38/node_modules/@vitejs/plugin-vue/dist/index.mjs:130:18)
  at Object.transform (node_modules/.pnpm/@vitejs+plugin-vue@3.1.0_vite@3.0.9+vue@3.2.38/node_modules/@vitejs/plugin-vue/dist/index.mjs:2653:18)
  at node_modules/.pnpm/rollup@2.77.3/node_modules/rollup/dist/es/shared/rollup.js:22695:37
```

### Additional context

I'm not sure if that's an upstream issue. What do you think?

There was a similar issue, which was closed with a workaround: https://github.com/vuejs/rollup-plugin-vue/issues/256

**Comment by dargmuesli** [comment]
This issue is now resolved upstream :)
https://codesandbox.io/p/sandbox/template-lang-html-updated-w9g6xg?welcome=true
