### ISSUE TITLE
Fail to import .scss async

### ISSUE THREAD

**Issue by ilyary** [nuxt/nuxt#14961]
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.19.3`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `app`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

```
"devDependencies": {
    "firebase-tools": "^11.9.0",
    "nuxt": "^3.0.0-rc.10",
    "sass": "^1.54.8",
    "sass-loader": "^13.0.2"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^6.2.0",
    "bootstrap": "^5.2.0"
  }
```

### Reproduction

https://github.com/ilyary/hyve-gtm

### Describe the bug

Fails to import like this: import("@/styles/async.scss");

```
<template>
  <NuxtPage />
</template>

<script>
import "bootstrap/scss/bootstrap.scss";

//import "@/styles/async.scss"; // That works

import("@/styles/xxx.js"); // That works

import("@/styles/async.scss"); // Not working
/*
>npm run generate
...

ℹ Initializing prerenderer

ERROR  Rollup error: Could not resolve './_nuxt/async.744a712b.js' from .nuxt/dist/server/server.mjs                                         nitro 09:45:18


ERROR  Could not resolve './_nuxt/async.744a712b.js' from .nuxt/dist/server/server.mjs                                                             09:45:18

 at error (node_modules/rollup/dist/es/shared/rollup.js:1858:30)
 at ModuleLoader.handleResolveId (node_modules/rollup/dist/es/shared/rollup.js:22357:24)
 at ModuleLoader.resolveDynamicImport (node_modules/rollup/dist/es/shared/rollup.js:22411:120)
 at async node_modules/rollup/dist/es/shared/rollup.js:22306:32
 */
</script>
```

**Comment by danielroe** [comment]
This works if called within `<script setup>`.

```vue
<script lang="ts">
import("~/assets/async.css");
</script>
```
