### ISSUE TITLE
Getting "Multiple conflicting contents for sourcemap source" when trying to build app with rc.10

### ISSUE THREAD

**Issue by Bodokh** [nuxt/nuxt#14981]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.19.3`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `alias`, `app`, `env`, `server`, `build`, `css`, `modules`, `ignore`, `publicRuntimeConfig`, `runtimeConfig`, `vite`, `storybook`
- Runtime Modules:  `@pinia/nuxt@0.4.2`, `@vueuse/nuxt@9.2.0`, `@nuxtjs/tailwindcss@5.3.3`, `./modules/fonts/index.ts`
- Build Modules:    `-`
------------------------------

### Reproduction

I am unable to reproduce this, I only hope you might know how this sort of error can arrise. The error happens in multiple versions of node, i checked versions: 14, 16, 18

#### EDIT: 
I can confirm the issue does not happen on rc.9.

### Describe the bug

I have a project that works when using yarn dev, but when i try to build i get the following error:
Multiple conflicting contents for sourcemap source /somepath/pages/vue-page.vue          

I tried deleting the page and building but it just threw the same error for another page and so on for all pages.

The build was working when I was using rc.6 beforehand.

### Logs

```shell
ERROR  Multiple conflicting contents for sourcemap source /path/pages/user/profile.vue                                                                                                                 16:06:31


 ERROR  Multiple conflicting contents for sourcemap source /path/pages/user/profile.vue                                                                                                                 16:06:31

  at error (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Link.traceMappings (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:13934:32)
  at collapseSourcemaps (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:14027:63)
  at Chunk.render (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:14896:19)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:16006:40
  at async Promise.all (index 109)
  at async Bundle.addFinalizedChunksToBundle (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:16004:9)
  at async Bundle.generate (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:15984:13)
  at async node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23754:27
```

### Another Log
```shell
  at error (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Link.traceMappings (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:13934:32)
  at collapseSourcemaps (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:14027:63)
  at Chunk.render (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:14896:19)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:16006:40
  at async Promise.all (index 116)
  at async Bundle.addFinalizedChunksToBundle (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:16004:9)
  at async Bundle.generate (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:15984:13)
  at async node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23754:27
  at async catchUnfinishedHookActions (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23088:20)
  at async doBuild (node_modules/vite/dist/node/chunks/dep-557f29e6.js:45822:20)
  at async Module.build (node_modules/vite/dist/node/chunks/dep-557f29e6.js:45653:16)
  at async buildServer (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.cbd4a916.mjs:589:5)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.cbd4a916.mjs:825:3)
  at async build (node_modules/nuxt/dist/index.mjs:1992:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:46:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by paperplane110** [comment]
> It's definitely a weird one. Is anyone else with this issue using windicss or something similar?

Meet the same issue here. I use `nuxt: "^3.0.0-rc.14"` and `"nuxt-windicss": "^2.5.5".`
The yarn generate command will failed when I try to add some screen variants , such as `<md`, to my `ProseCode` component. Once I remove the `<md`, build is successful

**Error Log**
```
rendering chunks (82)...Multiple conflicting contents for sourcemap source /Users/tyyuan/Desktop/code/resume-nuxt/components/content/ProseCode.vue

 ERROR  Multiple conflicting contents for sourcemap source /Users/tyyuan/Desktop/code/resume-nuxt/components/content/ProseCode.vue

  at error (node_modules/rollup/dist/es/shared/rollup.js:2088:30)
  at Link.traceMappings (node_modules/rollup/dist/es/shared/rollup.js:16469:32)
  at collapseSourcemaps (node_modules/rollup/dist/es/shared/rollup.js:16553:63)
  at transformChunk (node_modules/rollup/dist/es/shared/rollup.js:16648:15)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async node_modules/rollup/dist/es/shared/rollup.js:16681:17
  at async Promise.all (index 37)
  at async transformChunksAndGenerateContentHashes (node_modules/rollup/dist/es/shared/rollup.js:16677:5)
  at async renderChunks (node_modules/rollup/dist/es/shared/rollup.js:16598:109)
  at async Bundle.generate (node_modules/rollup/dist/es/shared/rollup.js:16807:13)
  at async node_modules/rollup/dist/es/shared/rollup.js:25030:27
  at async catchUnfinishedHookActions (node_modules/rollup/dist/es/shared/rollup.js:24133:20)
  at async doBuild (node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44518:22)
  at async Module.build (node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44347:16)
  at async buildServer (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.a80ec7fc.mjs:630:5)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.a80ec7fc.mjs:904:3)
  at async build (node_modules/nuxt/dist/index.mjs:2466:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:56:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:51:20)

error Command failed with exit code 1.
```

**Comment by baronkoko** [comment]
@danielroe in Nuxt v3.3.2 this problem is gone on my end, thanks

**Comment by MichaelNussbaumerGOWEST** [comment]
On my end it fails with nuxt v3.3.3 if I use `ssr: true`

**Comment by danielroe** [comment]
@MichaelNussbaumerGOWEST Could you provide a reproduction? 🙏

**Comment by Soya-xy** [comment]
@danielroe  when i run pnpm run build/generate  Nuxt 3.4.3 also not work 
reproduction: https://github.com/Soya-xy/nuxt3-editor 
<img width="938" alt="image" src="https://github.com/nuxt/nuxt/assets/56671014/1f226ab8-2a92-4f00-8884-abd02c6e4f1b">

**Comment by ShaggyTech** [comment]
I revisted my reproduction I posted in an earlier comment.  Repo for my  project is at [https://github.com/ShaggyTech/dubsquared](https://github.com/ShaggyTech/dubsquared).

I'm now on Nuxt v3.4.3 with Nitro v2.3.3.  I still receive the sourcemap error when trying to build the app via `nuxt build`.

I can make the error go away now by turning off server sourcemap in the nuxt config like so:

```typescript
sourcemap: {
  server: false,
},
```

Previously I was also disabling client sourcemaps but the problem now seems isolated to only the server build, it does not error until the server build happens, client build is successful in any case.

The following is the error and trace I'm getting:

```
 ERROR  Multiple conflicting contents for sourcemap source /home/shaggy/git-repos/nuxt3/dubsquared/components/Layout/Page/Footer/CardGroup.vue 

  at error (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
  at Link.traceMappings (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17163:32)
  at collapseSourcemaps (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17247:63)
  at transformChunk (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17342:15)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17386:17
  at async Promise.all (index 50)
  at async transformChunksAndGenerateContentHashes (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17382:5)
  at async renderChunks (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17292:109)
  at async Bundle.generate (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17510:13)
  at async node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:25802:27
  at async catchUnfinishedHookActions (node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24889:20)
  at async Module.build (node_modules/vite/dist/node/chunks/dep-a178814b.js:46426:22)
  at async buildServer (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.1d3e962a.mjs:845:5)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.1d3e962a.mjs:1155:3)
  at async build (node_modules/nuxt/dist/index.mjs:3175:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:55:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)
```

**Comment by danielroe** [comment]
@ShaggyTech Checking this again, the issue seems to stem from windicss, which is generating invalid sourcemaps:

https://github.com/windicss/vite-plugin-windicss/blob/main/packages/vite-plugin-windicss/src/index.ts#L168-L173

When this is addressed the issue goes away. Would you open an issue in their repo? 🙏 

@Soya-xy I couldn't reproduce the issue with your repo. Possibly you might have resolved it upstream.

I'm closing this issue as it doesn't seem to be an issue in Nuxt.

**Comment by karladler** [comment]
Having this issue without any windi css. But only running build in husky pre-push hook. Normal build works just fine.

**Comment by felixdenoix** [comment]
Posting here to give resolution clues for humans encountering the same issue as of 2026
For me The problem appeared while migrating from nuxt@2 to nuxt@3 to nuxt@4
The error happened with components that were using the **vue options API** and that i tried to migrate to **typescript**.
I managed to mitigate the issue from happening on my side by __either__:
- disabling the sourcemaps
- removing the typescript typings and the `lang="ts"` from the component appearing in the error log.

**Comment by danielroe** [comment]
if you provide a reproduction, I'll happily look into it. the previous issue was caused by a plugin that emitted invalid sourcemaps.
