### ISSUE TITLE
support http proxy when using `nuxi init`

### ISSUE THREAD

**Issue by ikexing-cn** [nuxt/nuxt#15101]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `0.0.0`
- Nitro Version:    `-`
- Package Manager:  `unknown`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Not exist

### Describe the bug

```
 ERROR  Failed to download template from registry: request to https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json failed, reason: connect ECON3

  at /Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:13269:11
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async downloadTemplate (/Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:13268:20)
  at async Object.invoke (/Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/chunks/init.mjs:13336:15)
  at async _main (/Users/xdclass/.npm/_npx/a95e0f536cf9a537/node_modules/nuxi/dist/cli.mjs:50:20)
```

### Additional context

` curl https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json`
```JSON
{
  "name": "v3",
  "defaultDir": "nuxt-app",
  "url": "https://v3.nuxtjs.org",
  "tar": "https://codeload.github.com/nuxt/starter/tar.gz/refs/heads/v3"
}
```

Everything works fine when I request the URL directly, I think this might be a bug in nuxt.

**Comment by kingyue737** [comment]
Not work for me. Already set proxy with clash
```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOENT raw.githubusercontent.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'raw.githubusercontent.com'
}
```

**Comment by kingyue737** [comment]
Not work for me. Already set proxy with clash
```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOENT raw.githubusercontent.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'raw.githubusercontent.com'
}
```

**Comment by rabbitxl** [comment]
get ip of raw.githubusercontent.com from a web.
and set these into **hosts** file (windows: C:\Windows\System32\drivers\etc)
185.199.111.133 raw.githubusercontent.com
rerun 'npx nuxi init nut3-app', and it works

**Comment by pi0** [comment]
Reopening to investigate more.

**Comment by ikexing-cn** [comment]
In fact, this is entirely due to China's network issues. @rabbitxl method of operation is to switch to an IP that has not been blocked, and the proxy works well (:

I think if we want to solve this problem for real, the first step is to directly abandon GitHub as a resource handling platform.

**Comment by pi0** [comment]
I totally understand your situation and it is not great or fair for Nuxt being hard to use in some countries. We should find a better way to overcome this issue (I'm thinking to either an easier global proxy config or one for custom end-pont).

**Comment by so1ve** [comment]
we may create a new package to automatically set http(s)_proxy by detecting the system proxy. I found a package luckyyyyy/node-system-proxy, which can set / remove the system api through napi. is it possible to form this library and add an api to get the current proxy?

**Comment by so1ve** [comment]
another package: @cypress/get-windows-proxy

**Comment by javix64** [comment]
same issue here.
It's seems that the problem also is from ipv6. i disabled ipv6 and it works :)

```bash
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/nuxi failed, reason: connect ETIMEDOUT 2606:4700::6810:1323:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/x535/.npm/_logs/2023-03-15T15_33_57_098Z-debug-0.log
```

**Comment by Kavya200114** [comment]
how to solve if this issue arise
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by blkcor** [comment]
environment:macos
solution: edit your file named /etc/hosts and add a mapping like this <185.199.108.133 raw.githubusercontent.com>
the ip you could find in https://ipaddress.com/website/raw.githubusercontent.com

**Comment by so1ve** [comment]
> environment:macos solution: edit your file named /etc/hosts and add a mapping like this <185.199.108.133 raw.githubusercontent.com> the ip you could find in https://ipaddress.com/website/raw.githubusercontent.com

This is not actually a solution. Now we are finding a way to let giget use the system proxy, not how to connect to github in China.

**Comment by blkcor** [comment]
But I can't run the example mentioned at https://github.com/unjs/giget/issues/23

**Comment by so1ve** [comment]
> But I can't run the example mentioned at [unjs/giget#23](https://github.com/unjs/giget/issues/23)

Have you set the `http(s)_proxy` environment variable?

**Comment by blkcor** [comment]
> 

yes , I put my clash proxy address in .env file

**Comment by so1ve** [comment]
> > > But I can't run the example mentioned at [unjs/giget#23](https://github.com/unjs/giget/issues/23)
> > 
> > 
> > Have you set the `http(s)_proxy` environment variable?
> 
> yes , I put my clash proxy address in .env file

It won't work because nuxi in it does not use dozens and the environment variables in .env files are injected. You should set them in your shell (terminal).

**Comment by shylockWu** [comment]
> 114.114.114.114

Really good!!!

**Comment by so1ve** [comment]
> > 114.114.114.114
> 
> Really good!!!

哎 就不能看一下issue标题吗？？？这个issue讨论的是如何让nuxi走代理的问题而不是怎么访问GitHub

Please read the title. This issue is discussing how to let nuxi use the proxy.

**Comment by shylockWu** [comment]
> > > 114.114.114.114
> > 
> > 
> > Really good!!!
> 
> 哎 就不能看一下issue标题吗？？？这个issue讨论的是如何让nuxi走代理的问题而不是怎么访问GitHub
> 
> Please read the title. This issue is discussing how to let nuxi use the proxy.

修改DNS能够正确初始化项目，而使用代理不可以，仅限个人情况

**Comment by coderwyd** [comment]
That's too bad.  Can you tell me what I should do to create a project?

**Comment by ikexing-cn** [comment]
> That's too bad. Can you tell me what I should do to create a project?

If you want to start a new project,  you can simply clone this GitHub repository: https://github.com/nuxt/starter/tree/v3.

**Comment by so1ve** [comment]
> > That's too bad. Can you tell me what I should do to create a project?
> 
> If you want to start a new project, you can simply clone this GitHub repository: https://github.com/nuxt/starter/tree/v3.

And delete the .git folder :)

**Comment by coderwyd** [comment]
> > > That's too bad. Can you tell me what I should do to create a project?
> > 
> > 
> > If you want to start a new project, you can simply clone this GitHub repository: https://github.com/nuxt/starter/tree/v3.
> 
> And delete the .git folder :)

Thank you. That's a great idea.

**Comment by 442283045** [comment]
> get ip of raw.githubusercontent.com from a web. and set these into **hosts** file (windows: C:\Windows\System32\drivers\etc) 185.199.111.133 raw.githubusercontent.com rerun 'npx nuxi init nut3-app', and it works

it works

**Comment by daiwanxing** [comment]
> 

Thanks! It's work for me

**Comment by ikxin** [comment]
Browser proxy is invalid for it. Try setting up a terminal proxy.

```bash
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890
```

**Comment by C1oudust** [comment]
I have the same problem and solved it, if you are using clash, you can turn on tun mode to ensure that nuxi init use the proxy :P

**Comment by dragon-fish** [comment]
> I have the same problem and solved it, if you are using clash, you can turn on tun mode to ensure that nuxi init use the proxy :P

it worked for me

**Comment by crick77** [comment]
Hello, nuxi init does not work under proxy (Windows 11). My proxy is also password-protected (http://user:pass@proyhost:port/). Nuxi gives me error:

Error: Failed to download template from registry: fetch failed

I have proxy configured (both http and htttps) under npm and environment variables and it works fine. I've also tried Angular CLI and works as well.

Thank you

**Comment by danielroe** [comment]
Are you still investigating this @pi0?

**Comment by cuishunbiao** [comment]
> Report content

Thank you.
I'm in China.
In my Mac, i add DNS command in "/etc/hosts" file. I have already solved this problem.

185.199.111.133 raw.githubusercontent.com
