### ISSUE TITLE
Server: different route params on same route are not possible

### ISSUE THREAD

**Issue by bastian-friedrich** [nuxt/nuxt#15140]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I reproduced the error here: https://github.com/bastian-friedrich/nuxt3-nitro-api-route-params

Check out the api routes in this folder: https://github.com/bastian-friedrich/nuxt3-nitro-api-route-params/tree/main/server/api/hello

As a counter reproduction, I also added a working route here (single route param file in one folder): https://github.com/bastian-friedrich/nuxt3-nitro-api-route-params/tree/main/server/api/foo

To reproduce:
1. Create server api route with param in any folder under /server/api, f.e. /server/api/hello/[name].get.ts
2. Try it, this will work as expected
3. Create a second server api route with a DIFFERENTLY named param AND different method in the same folder, f.e.: /server/api/hello/[id].put.ts
4. In this case, the first route (get) will not work anymore but the put route will work as expected.

### Describe the bug

If there are multiple server routes with different params on the same level, nuxt cannot handle the requests anymore for at least one of them.

If you look at the output of .nuxt/dev/index.mjs the routes are there and looking fine.

I figured out that nuxt can still handle the route with the param that comes alphabetically first. No matter what method you are using.
Example:
/server/api/hello/[page].get.ts -> works
/server/api/hello/[quark].put.ts -> not working

If you are using the same param and different methods, it works:
/server/api/hello/[page].get.ts -> works
/server/api/hello/[page].put.ts -> works

### Logs

```shell
{
    "url": "/api/hello/asd",
    "statusCode": 405,
    "statusMessage": "Method get is not allowed on this route.",
    "message": "Method get is not allowed on this route.",
    "stack": "<pre><span class=\"stack internal\">at createError (./node_modules/h3/dist/index.mjs:23:15)</span>\n<span class=\"stack internal\">at Object.handler (./node_modules/h3/dist/index.mjs:675:13)</span>\n<span class=\"stack internal\">at ./node_modules/h3/dist/index.mjs:592:31</span>\n<span class=\"stack internal\">at processTicksAndRejections (node:internal/process/task_queues:96:5)</span>\n<span class=\"stack internal\">at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:538:7)</span></pre>"
}
```

**Comment by OrbisK** [comment]
I looks like this is already solved by nitro. I cant reproduce the error with latest nuxt.
