### ISSUE TITLE
After build not all library files are copied to .output dir

### ISSUE THREAD

**Issue by Demivan** [nuxt/nuxt#15215]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `pnpm@7.13.4`
- Builder:          `vite`
- User Config:      `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-28bn6b?file=README.md

### Describe the bug

If `production` conditional export is specified for a library after build `.output/server/node_modules` will only contain production files for that library.

This means that you cannot run server with `node .output/server/index.mjs` command.

You need to specify production condition: `node -C=production .output/server/index.mjs`

### Logs

```shell
[nuxt] [request error] [unhandled] [500] Cannot find module '/home/projects/github-28bn6b/.output/server/node_modules/fluent-vue/dist/index.mjs' imported from /home/projects/github-28bn6b/.output/server/chunks/app/server.mjs
  at get (https://github-28bn6b.w-corp.staticblitz.com/blitz.421e70ed35311a61ea4321fec3fad6b3e279633a.js:6:292489)  
  at get (./.output/server/node_modules/h3/dist/index.mjs:120:9)  
  at normalizeError (./.output/server/chunks/nitro/node-server.mjs:381:18)  
  at errorhandler (./.output/server/chunks/nitro/node-server.mjs:400:71)  
  at toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:719:27)  
  at <anonymous> (<anonymous>)
[nuxt] [request error] [unhandled] [500] Cannot find module '/home/projects/github-28bn6b/.output/server/node_modules/fluent-vue/dist/index.mjs' imported from /home/projects/github-28bn6b/.output/server/chunks/app/server.mjs
  at get (https://github-28bn6b.w-corp.staticblitz.com/blitz.421e70ed35311a61ea4321fec3fad6b3e279633a.js:6:292489)  
  at get (./.output/server/node_modules/h3/dist/index.mjs:120:9)  
  at normalizeError (./.output/server/chunks/nitro/node-server.mjs:381:18)  
  at errorhandler (./.output/server/chunks/nitro/node-server.mjs:400:71)  
  at toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:719:27)  
  at <anonymous> (<anonymous>)
[nuxt] [request error] [unhandled] [500] Cannot find module '/home/projects/github-28bn6b/.output/server/node_modules/fluent-vue/dist/index.mjs' imported from /home/projects/github-28bn6b/.output/server/chunks/app/server.mjs
  at get (https://github-28bn6b.w-corp.staticblitz.com/blitz.421e70ed35311a61ea4321fec3fad6b3e279633a.js:6:292489)  
  at get (./.output/server/node_modules/h3/dist/index.mjs:120:9)  
  at normalizeError (./.output/server/chunks/nitro/node-server.mjs:381:18)  
  at errorhandler (./.output/server/chunks/nitro/node-server.mjs:400:71)  
  at toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:719:27)  
  at <anonymous> (<anonymous>)
```

**Comment by danielroe** [comment]
resolved in https://github.com/unjs/nitro/issues/844
