### ISSUE TITLE
installModule doesn't work with nuxt 2 modules

### ISSUE THREAD

**Issue by junholee14** [nuxt/nuxt#15507]
### Environment

Operating System: Windows
Node Version: v14.17.1
Nuxt Version: 2.15.8
Nitro Version: -
Package Manager: npm@6.14.13
Builder: nxut2(webpack )
User Config: -
Runtime Modules: -
Build Modules: -

### Reproduction

The latest version of @nuxt/kit has a problem with @nuxtjs/tailwindcss
problem version : 3.0.0-rc.14

and seems like versions below 3.0.0-rc.14 work properly 

### Describe the bug

npm run dev doesn't work properly 

### Logs

```shell
npm run dev doesn't work properly as following below 

i Using default Tailwind CSS file from runtime/tailwind.css                                                                                                                        nuxt:tailwindcss 17:04:00

 FATAL  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                                                                                            17:04:00  

  at postcss8Module (node_modules\@nuxt\postcss8\dist\index.js:15:10)
  at installModule (/C:/Users/jun/Desktop/projects/nuxtjs2/node_modules/@nuxtjs/tailwindcss/node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async setup (/C:/Users/jun/Desktop/projects/nuxtjs2/node_modules/@nuxtjs/tailwindcss/dist/module.mjs:196:7)
  at async ModuleContainer.normalizedModule (/C:/Users/jun/Desktop/projects/nuxtjs2/node_modules/@nuxtjs/tailwindcss/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:239:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:51:7)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:478:5)
```

**Comment by anime-shed** [comment]
> For me, I removed tailwindcss from the project then it work.
> 
> 1/ npm uninstall @nuxtjs/tailwindcss 
> 2/ find nuxt.config.js then remove import value: @nuxtjs/tailwindcss 
> 3/ run again, it works for me.

Have tried these but now I am getting the following error:
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                     friendly-errors 12:39:36  

This dependency was not found:                                                                                                                                                                              friendly-errors 12:39:36
                                                                                                                                                                                                            friendly-errors 12:39:36  
* nuxt_plugin_signalR_63479a74 in ./.nuxt/index.js                                                                                                                                                          friendly-errors 12:39:36  
                                                                                                                                                                                                            friendly-errors 12:39:36  
To install it, you can run: npm install --save nuxt_plugin_signalR_63479a74                                                                                                                                 friendly-errors 12:39:36  
i Waiting for file changes                                                                                                                                                                                                  12:39:36
i Memory usage: 674 MB (RSS: 938 MB)                                                                                                                                                                                        12:39:36  
i Listening on: http://localhost:10023/                                                                                                                                                                                     12:39:36  

                                                                                                                                                                                    12:39:36
TS2339: Property 'isAxiosError' does not exist on type 'AxiosStatic'.
    140 |       } catch (e: any) {
    141 |         console.error(e)
  > 142 |         if (axios.isAxiosError(e)) {
        |                   ^^^^^^^^^^^^
    143 |           this.error = getAxiosError(e)
    144 |           if (this.error == 'Session expired. Please Login again!') {
    145 |             window.open(`${this.baseUrl}?logout=true`, '_self')



 WARN  Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'                         
```
