### ISSUE TITLE
`server/api` being a file gives error

### ISSUE THREAD

**Issue by nopeless** [nuxt/nuxt#15752]
### Environment

❯ nuxi info
Nuxi 3.0.0                                                                                                        17:10:38
                                                                                                                  17:10:40
RootDir: /home/projects/nuxt-starter-3rghgt                                                                       17:10:40
Nuxt project info:                                                                                                17:10:40

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-3rghgt?file=server%2Fapi

### Describe the bug

When server/api is a file it errors without giving helpful information

### Additional context

Accidentally discovered it.

Very low priority bug

**Comment by andreygmc** [comment]
Hello. I tried to reproduce and it seems to me that this log is quite helpful to understand the problem:

```
 ERROR  [unhandledRejection] ENOTDIR: not a directory, stat '/Users/andrey/nuxt-proj/server/api/**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}'                                           22:17:36

    at async Object.stat (node:internal/fs/promises:1036:18)
    at async isType (node_modules/path-type/index.js:10:17)
    at async node_modules/globby/index.js:39:4
    at async Promise.all (index 0)
    at async directoryToGlob (node_modules/globby/index.js:38:16)
    at async Promise.all (index 0)
    at async node_modules/globby/index.js:192:8
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async node_modules/globby/index.js:224:6

ℹ Restarting Nuxt due to error: Error: ENOTDIR: not a directory, stat '/Users/andrey/nuxt-proj/server/api/**/*.{js,mjs,cjs,ts,mts,cts,tsx,jsx}'
```
