### ISSUE TITLE
Using router in middleware throws Nuxt Instance unavailable.

### ISSUE THREAD

**Issue by ziadomalik** [nuxt/nuxt#18423]
### Environment

```
RootDir: D:/Projects/insightq                                                            
Nuxt project info:                                                      

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`
------------------------------
```

### Reproduction

Here is my simple middleware:

```
import { Auth, onAuthStateChanged } from "firebase/auth";

export default defineNuxtRouteMiddleware((to, from) => {
    const { auth } = useFirebase();

    onAuthStateChanged(auth as Auth, async user => {
        if (!user) {
            return navigateTo({ path: "/login" });
        }
    })
});
```

### Describe the bug

Throws the following error when adding a router middleware:

```
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable                                                        16:45:55
    at Module.useNuxtApp (D:\Projects\insightq\node_modules\nuxt\dist\app\nuxt.mjs:165:13)
    at useRouter (D:\Projects\insightq\node_modules\nuxt\dist\app\composables\router.mjs:14:32)
    at Module.navigateTo (D:\Projects\insightq\node_modules\nuxt\dist\app\composables\router.mjs:75:18)
```

### Additional context

I have also gotten this error when using `useRouter` in a Pinia action. I am using `@pinia/nuxt`.

### Logs

```shell-script
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable                                                        16:45:55
    at Module.useNuxtApp (D:\Projects\insightq\node_modules\nuxt\dist\app\nuxt.mjs:165:13)
    at useRouter (D:\Projects\insightq\node_modules\nuxt\dist\app\composables\router.mjs:14:32)
    at Module.navigateTo (D:\Projects\insightq\node_modules\nuxt\dist\app\composables\router.mjs:75:18)
```
```

**Comment by danielroe** [comment]
The problem here is that you are calling `navigateTo` outside the direct context of the middleware, and on server side there's no way to know what request to attach that response to. Instead you will need to reconsider your implementation (should you be listening for auth state change on server-side?), or get the nuxtApp instance directly within the middleware, and then use `callWithNuxt` ensure it has the correct nuxt instance.

See https://github.com/nuxt/nuxt/issues/14723 and linked issues for more.

**Comment by ziadomalik** [comment]
Thanks Daniel ❤️
