### ISSUE TITLE
Using jest with `@nuxt/test-utils` results in `Returning a Promise from "describe" is not supported`

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt#18436]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-5c4p72?file=test/default.test.ts

### Describe the bug

`@nuxt/test-utils` doesn't work with `jest` if one is to set it up in a way that Nuxt 3 documentation recommends (https://nuxt.com/docs/getting-started/testing#setup):

```
  ● Test suite failed to run

    Returning a Promise from "describe" is not supported. Tests must be defined synchronously.

      1 | import { setup } from '@nuxt/test-utils';
      2 |
    > 3 | describe('Smoke test (default)', async () => {
        |         ^
      4 |   await setup({});
      5 |
      6 |   test('it goes well', async () => {

      at ErrorWithStack (node_modules/jest-util/build/ErrorWithStack.js:23:13)
      at Object.<anonymous> (test/default.test.ts:3:9)
          at [object Object]
```

**Comment by manniL** [comment]
Indeed, because jest is not supporting async `describe` 🙁
