### ISSUE TITLE
nuxt.config's `ignore` and `ignore-prefix` not working

### ISSUE THREAD

**Issue by miclgael** [nuxt/nuxt#18439]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.22.0`
- Builder:          `vite`
- User Config:      `telemetry`, `test`, `srcDir`, `css`, `ignore`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Reproduction

https://stackblitz.com/edit/github-ywawgt?file=.nuxt/components.d.ts

### Describe the bug

When using components organized within folders, Nuxt is adding non-component files to the global components list. 

### Additional context

1. I have tested using the default `ignore` options
2. I have tested by setting explicit `ignore` options
3. I have tested using the `-` prepend method

None seem to work for me currently.

> Also FYI these files being present seem to prevent the `build` command from working on my machine. Could not reproduce this on Stackblitz, but provided my logs below.

### Logs

```shell-script
➜ pnpm run build

> @ build /Users/REDACTED
> nuxt build

Nuxi 3.0.0                                                            08:02:07
Nuxt 3.0.0 with Nitro 1.0.0                                           08:02:07

 ERROR  'promises' is not exported by __vite-browser-external, imported by ../chia/node_modules/.pnpm/local-pkg@0.4.3/node_modules/local-pkg/dist/shared.mjs
file: /Users/REDACTED/node_modules/.pnpm/local-pkg@0.4.3/node_modules/local-pkg/dist/shared.mjs:61:13
59: import process2 from "process";
60: import path from "path";
61: import fs, { promises as fsPromises } from "fs";
                 ^
62: import { fileURLToPath } from "url";


 ERROR  'promises' is not exported by __vite-browser-external, imported by ../chia/node_modules/.pnpm/local-pkg@0.4.3/node_modules/local-pkg/dist/shared.mjs

  at error (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
  at Module.traceVariable (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
  at ModuleScope.findVariable (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
  at FunctionScope.findVariable (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
  at ChildScope.findVariable (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
  at MemberExpression.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:8601:49)
  at ConditionalExpression.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
  at VariableDeclarator.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
  at VariableDeclaration.bind (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5265:73)

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by danielroe** [comment]
I believe this has just been fixed in https://github.com/nuxt/nuxt/pull/15884, and should be usable in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Comment by miclgael** [comment]
Are you... are you mind reading now? 

Thanks, will let you know 🙏

**Comment by miclgael** [comment]
Just noting its working as expected on `3.0.1-rc.0-27906778.5ede291`
