### ISSUE TITLE
bug: rollup failed to parsed css/scss/sass

### ISSUE THREAD

**Issue by HigherOrderLogic** [nuxt/nuxt#18490]
### Environment

Stackblitz

### Reproduction

https://stackblitz.com/edit/github-3ppsfz

### Describe the bug

When bundling Nitro server, rollup failed to parse css file.

### Additional context

`nuxi dev` runs fine but error out when build for production.

The first part of the error log is caused by this part of code (https://github.com/unjs/nitro/blob/main/src/rollup/config.ts#L400). A solution to fixed this is to modify the code to `rollupConfig.plugins.push(inject({ exclude: "**/*.(scss|sass|css)", ...env.inject }));`.

### Logs

```shell-script
rollup-plugin-inject: failed to parse /home/projects/github-3ppsfz/node_modules/element-plus/theme-chalk/src/badge.scss. Consider restricting the plugin to particular files via options.include
rollup-plugin-inject: failed to parse /home/projects/github-3ppsfz/node_modules/element-plus/theme-chalk/src/base.scss. Consider restricting the plugin to particular files via options.include

 ERROR  RollupError: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)


1: @use 'sass:math';
   ^
2: @use 'sass:map';


 ERROR  Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)             02:06:41

  at error (file://node_modules/rollup/dist/es/shared/rollup.js:2066:30)
  at Module.error (file://node_modules/rollup/dist/es/shared/rollup.js:13087:16)
  at Module.tryParse (file://node_modules/rollup/dist/es/shared/rollup.js:13762:25)
  at Module.setSource (file://node_modules/rollup/dist/es/shared/rollup.js:13372:39)
  at ModuleLoader.addModuleSource (file://node_modules/rollup/dist/es/shared/rollup.js:22954:20)
```

**Comment by danielroe** [comment]
At some point this is because a CSS file is being imported by some file in that component library. The solution is to transpile the library.

```diff
  // https://nuxt.com/docs/api/configuration/nuxt-config
  export default defineNuxtConfig({
+   build: {
+     transpile: [/element-plus/]
+   },
    modules: ["@element-plus/nuxt"],
    elementPlus: {
      importStyle: "scss",
      themes: ["dark"],
    }
  })
```
