### ISSUE TITLE
Cannot destructure property 'createComponentInstance' of 'Vue.ssrUtils' as it is undefined

### ISSUE THREAD

**Issue by Asxer** [nuxt/nuxt#18717]
### Environment

Everything is in reproduce repositoryreproducing

### Reproduction

https://github.com/Asxer/pinia-persistedstate-reproduce

### Describe the bug

I wanted to create a minimal reproducing project about a bug for the pinia-persisatedstate plugin and copy-pasted project from a real project but this project can not even start. I'm getting this error and can not do anything with that. I've tried all solutions from the StackOverflow and nothing happened.

```
pinia-plugin-persistedstate-reproduce-frontend |  ERROR  Cannot set properties of undefined (setting 'id')
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend |  ERROR  Cannot set properties of undefined (setting 'id')
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend |  ERROR  Cannot set properties of undefined (setting 'id')
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend |  ERROR  Cannot set properties of undefined (setting 'id')
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend |  ERROR  Cannot set properties of undefined (setting 'id')
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend | ℹ Vite client warmed up in 1645ms
pinia-plugin-persistedstate-reproduce-frontend | ✔ Nitro built in 649 ms
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend |  ERROR  [worker reload] [worker init] Cannot destructure property 'createComponentInstance' of 'Vue.ssrUtils' as it is undefined.
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend |   at Object.<anonymous> (node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:594:9)
pinia-plugin-persistedstate-reproduce-frontend |   at Module._compile (node:internal/modules/cjs/loader:1159:14)
pinia-plugin-persistedstate-reproduce-frontend |   at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
pinia-plugin-persistedstate-reproduce-frontend |   at Module.load (node:internal/modules/cjs/loader:1037:32)
pinia-plugin-persistedstate-reproduce-frontend |   at Module._load (node:internal/modules/cjs/loader:878:12)
pinia-plugin-persistedstate-reproduce-frontend |   at Module.require (node:internal/modules/cjs/loader:1061:19)
pinia-plugin-persistedstate-reproduce-frontend |   at require (node:internal/modules/cjs/helpers:103:18)
pinia-plugin-persistedstate-reproduce-frontend |   at Object.<anonymous> (node_modules/@vue/server-renderer/index.js:6:20)
pinia-plugin-persistedstate-reproduce-frontend |   at Module._compile (node:internal/modules/cjs/loader:1159:14)
pinia-plugin-persistedstate-reproduce-frontend |   at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
pinia-plugin-persistedstate-reproduce-frontend | 
```

 There also was a cypress and there was a problem with it

```
pinia-plugin-persistedstate-reproduce-frontend | npm notice 
pinia-plugin-persistedstate-reproduce-frontend | npm notice New major version of npm available! 8.19.2 -> 9.4.1
pinia-plugin-persistedstate-reproduce-frontend | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.4.1>
pinia-plugin-persistedstate-reproduce-frontend | npm notice Run `npm install -g npm@9.4.1` to update!
pinia-plugin-persistedstate-reproduce-frontend | npm notice 
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! code 1
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! path /app/node_modules/cypress
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! command failed
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! command sh -c -- node index.js --exec install
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! Cypress cannot write to the cache directory due to file permissions
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! 
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! See discussion and possible solutions at
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! https://github.com/cypress-io/cypress/issues/1281
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! 
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! ----------
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! 
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! Failed to access /root/.cache/Cypress:
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! 
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! EACCES: permission denied, mkdir '/root/.cache/Cypress'
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! 
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! ----------
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! 
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! Platform: linux-x64 (Debian - 11.5)
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! Cypress Version: 10.11.0
pinia-plugin-persistedstate-reproduce-frontend | 
pinia-plugin-persistedstate-reproduce-frontend | npm ERR! A complete log of this run can be found in:
pinia-plugin-persistedstate-reproduce-frontend | npm ERR!     /root/.npm/_logs/2023-02-02T15_21_45_449Z-debug-0.log
```

But I think it isn't related to the main issue but I mentioned it just in case

**Comment by Baroshem** [comment]
I think this problem could be related to the pinia module itself. Have you tried contacting the kodule author about his bug?

**Comment by Asxer** [comment]
No, I've got a problem with starting Nuxt and that's why I started from Nuxt. I don't see mentioning Pinia here. 
Thank you I will create the same issue for Pinia too

**Comment by shaobeichen** [comment]
I encountered the same error, but I just followed the instructions of nuxt website to perform pnpm dev - o. And I have reported an error since I did not install pinia.
