### ISSUE TITLE
Cannot read properties of undefined (reading 'modules') after upgrading to 3.1.2

### ISSUE THREAD

**Issue by fathi91** [nuxt/nuxt#18781]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `modules`, `typescript`, `serverHandlers`, `app`, `css`, `runtimeConfig`, `nitro`
- Runtime Modules:  `@vueuse/nuxt@9.5.0`
- Build Modules:    `-`
------------------------------

### Reproduction

Cannot read properties of undefined (reading 'modules') after upgrading to 3.1.2

### Describe the bug

Good day,
after upgrading to Nuxt 3.1.2 I couldn't run my app in dev mode 
when i run it and try to access the index page i get `Cannot read properties of undefined (reading 'modules')` 
so i tried to roll back to 3.1.1 and everything works fine the error is gone,
but building and running in production mode using v3.1.2 works fine i don't get the same error
i just get:
`Export "useNitroApp" of module "node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/nuxt/dist/core/runtime/nitro/renderer.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.`

### Logs

```shell-script
Nuxi 3.1.2                                                                                                                                                             16:01:51
Nuxt 3.1.2 with Nitro 2.1.1                                                                                                                                            16:01:51
                                                                                                                                                                       16:01:53  
  > Local:    http://localhost:3000/
  > Network:  http://192.168.0.105:3000/

i Vite client warmed up in 4367ms                                                                                                                                      16:02:03
√ Nitro built in 3631 ms                                                                                                                                         nitro 16:02:06
√ Vite server hmr 24 files in 1500.756ms                                                                                                                               16:02:44
[Vue warn]: inject() can only be used inside setup() or functional components.                                                                                         16:02:44
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.                                           16:02:44
[Vue warn]: Unhandled error during execution of setup function                                                                                                         16:02:44
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')                                                                       16:02:44
  at _sfc_main.setup (C:\Users\xx\Desktop\nuxtapp\node_modules\nuxt\dist\app\components\nuxt-root.vue:76:16)
  at callWithErrorHandling (C:\Users\xx\Desktop\nuxtapp\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:171:22)
  at setupStatefulComponent (C:\Users\xx\Desktop\nuxtapp\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7194:29)
  at setupComponent (C:\Users\xx\Desktop\nuxtapp\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7149:11)
  at renderComponentVNode (C:\Users\xx\Desktop\nuxtapp\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:628:17)
  at renderToString (C:\Users\xx\Desktop\nuxtapp\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:906:26)
  at Object.renderToString$1 [as renderToString] (/C:/Users/xx/Desktop/nuxtapp/.nuxt/dev/index.mjs:19903:24)
  at Object.renderToString (/C:/Users/xx/Desktop/nuxtapp/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)
  at async /C:/Users/xx/Desktop/nuxtapp/.nuxt/dev/index.mjs:19967:21
  at async /C:/Users/xx/Desktop/nuxtapp/.nuxt/dev/index.mjs:107:22
[Vue warn]: inject() can only be used inside setup() or functional components.                                                                                         16:02:44
[Vue warn]: Unhandled error during execution of setup function                                                                                                         16:02:44  
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')                                                                       16:02:44  
  at _sfc_main.setup (C:\Users\xx\Desktop\nuxtapp\node_modules\nuxt\dist\app\components\nuxt-root.vue:76:16)
  at callWithErrorHandling (C:\Users\xx\Desktop\nuxtapp\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:171:22)
  at setupStatefulComponent (C:\Users\xx\Desktop\nuxtapp\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7194:29)
  at setupComponent (C:\Users\xx\Desktop\nuxtapp\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7149:11)
  at renderComponentVNode (C:\Users\xx\Desktop\nuxtapp\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:628:17)
  at renderToString (C:\Users\xx\Desktop\nuxtapp\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:906:26)
  at Object.renderToString$1 [as renderToString] (/C:/Users/xx/Desktop/nuxtapp/.nuxt/dev/index.mjs:19903:24)
  at Object.renderToString (/C:/Users/xx/Desktop/nuxtapp/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)
  at async /C:/Users/xx/Desktop/nuxtapp/.nuxt/dev/index.mjs:19967:21
  at async /C:/Users/xx/Desktop/nuxtapp/.nuxt/dev/index.mjs:107:22
```

**Comment by fathi91** [comment]
track in https://github.com/nuxt/nuxt/issues/18563.
