### ISSUE TITLE
in version 3.1.2, require is not defined in ES module scope, you can use import instead. This problem does not appear in version 3.1.1, how can I modify it

### ISSUE THREAD

**Issue by Morii120** [nuxt/nuxt#18847]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.11.1`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `app`, `css`, `build`, `typescript`, `modules`, `nitro`, `components`, `vueuse`, `vite`
- Runtime Modules:  `@vueuse/nuxt@9.12.0`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

https://github.com/Morii120/nuxt_bug

### Describe the bug

Now running npm run dev will cause this problem and not be able to develop

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] require is not defined in ES module scope, you can use import instead
  at $id_jliaSA3QKS (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:275:3)
  at __instantiateModule__ (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116069:9)
  at __ssrLoadModule__ (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116007:25)
  at ssrImport (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116032:13)
  at $id_w4M3WWtjnW (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:257:37)
  at __instantiateModule__ (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116069:9)
  at __ssrLoadModule__ (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116007:25)
  at ssrImport (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116032:13)
  at $id_Vp6XaZwVXS (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:17:37)
  at __instantiateModule__ (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116069:9)
[nuxt] [request error] [unhandled] [500] require is not defined in ES module scope, you can use import instead
  at $id_jliaSA3QKS (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:275:3)
  at __instantiateModule__ (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116069:9)
  at __ssrLoadModule__ (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116007:25)
  at ssrImport (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116032:13)
  at $id_w4M3WWtjnW (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:257:37)
  at __instantiateModule__ (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116069:9)
  at __ssrLoadModule__ (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116007:25)
  at ssrImport (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116032:13)
  at $id_Vp6XaZwVXS (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:17:37)
  at __instantiateModule__ (/E:/education/roncoo-education-web/.nuxt/dist/server/server.mjs:116069:9)
```

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by Morii120** [comment]
You try to download this project at   https://github.com/Morii120/nuxt_bug

**Comment by Morii120** [comment]
> Hey! Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

You try to download this project at https://github.com/Morii120/nuxt_bug

**Comment by manniL** [comment]
> > Hey! Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> @manniL manniLYou try to download this project at [Morii120/nuxt_bug](https://github.com/Morii120/nuxt_bug)

Instead of a whole project, please try to create a *minimal* version of it so the problem can be analyzed without going through all the files ☺️

**Comment by Morii120** [comment]
> > > 嘿！你能提供一个[复制品](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)吗？🙏
> > 
> > 
> > @manniLmanniL你尝试在[Morii120/nuxt_bug下载这个项目](https://github.com/Morii120/nuxt_bug)
> 
> 请尝试创建它的_最小_版本，而不是整个项目，这样就可以在不检查所有文件的情况下分析问题☺️
There were a lot of empty folders just configuration files and a server middleware

**Comment by manniL** [comment]
> There were a lot of empty folders just configuration files and a server middleware

That's a good start but please remove everything that is unrelated (e.g. all libraries that do not have impact on the bug, and so on). Also, I get some errors right now when starting the project because files that do not exist anymore are requested.

**Comment by Morii120** [comment]
> > There were a lot of empty folders just configuration files and a server middleware
> 
> That's a good start but please remove everything that is unrelated (e.g. all libraries that do not have impact on the bug, and so on). Also, I get some errors right now when starting the project because files that do not exist anymore are requested.

Sorry, I have deleted the relevant code and updated it. Please have a look

**Comment by itzaks** [comment]
I can only confirm I'm also seeing this error, and downgrading to 5.1.1 resolves it. I don't have time for a repro, sorry. But I'm also only seeing it when running yarn build.

**Comment by ekrausso** [comment]
I just spin a nuxt 3 app with `npx nuxi init` and I'm getting this error after `yarn dev`:

`[nitro] [dev] [uncaughtException] ReferenceError: require is not defined in ES module scope, you can use import instead ... at file /.nuxt/dev/index.mjs:594:20`

**Comment by manniL** [comment]
> I just spin a nuxt 3 app with `npx nuxi init` and I'm getting this error after `yarn dev`:
> 
> `[nitro] [dev] [uncaughtException] ReferenceError: require is not defined in ES module scope, you can use import instead ... at file /.nuxt/dev/index.mjs:594:20`

Can you provide a reproduction for that?

**Comment by manniL** [comment]
Yes, right now the stacktrace points to the auto-generated file for errors. From there you can infer where the same position in your code is (usually 🙈)

**Comment by Nemure231** [comment]
I have the same problem, mine already solve by removing. devBundler: "legacy", from your nuxt.config.ts.
