### ISSUE TITLE
Getting an error when setting up a client side plugin 

### ISSUE THREAD

**Issue by naveensky** [nuxt/nuxt#18891]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.13.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `typescript`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I have setup a basic codebase to reproduce the error at https://stackblitz.com/edit/github-c6xmxw

### Describe the bug

I am trying to use a library https://github.com/ownego/polaris-vue with a nuxt 3 project. Its a client-side library and I am hoping to use it with the nuxt

I am getting following error when I setup the library with a fresh nuxt 3 project. I am loading the plugin on client side only so I am not sure what could be breaking on server side

I have reproduced the error at https://stackblitz.com/edit/github-c6xmxw

```
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_2__.createMemoryHistory is not a function          18:07:50
  at eval (./node_modules/nuxt/dist/pages/runtime/plugins/router.mjs:38:256)  
  at fn (./node_modules/nuxt/dist/app/nuxt.mjs:151:27)  
  at Object.callAsync (file://./node_modules/unctx/dist/index.mjs:68:19)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.mjs:153:23)  
  at applyPlugin (./node_modules/nuxt/dist/app/nuxt.mjs:97:29)  
  at Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.mjs:107:11)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.mjs:29:7)  
  at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (file://./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:42:18)  
  at async Object.renderToString (file://./node_modules/vue-bundle-renderer/dist/runtime.mjs:198:19)  
  at async eval (file://./.nuxt/dev/index.mjs:700:21)
```the 

### Additional context

_No response_

### Logs

_No response_

**Comment by danielroe** [comment]
That library you linked wrongly has a dependency on the Vue 2 version of `vue-router`: https://unpkg.com/browse/@ownego/polaris-vue@1.3.0/package.json. They should update their package dependency to `vue-router` v4.
