### ISSUE TITLE
Filter API response

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/nuxt#18940]
Hello,

Is there a way to filter the API response with Nuxt 3? I would like to return only some properties from my JSON response but I have the following error with this code :

`server/api/imgkit.ts`
```ts
export default defineEventHandler(async () => {
  const config = useRuntimeConfig()
  const response = await $fetch('https://api.imagekit.io/v1/files', {
    method: 'GET',
    headers: {
      Authorization: `Basic ${config.IMAGEKIT_B64_API}`,
    },
  }) as Response
  const data = await response.json() as ImageKit[] // error here
  return data.map(item => ({ name: item.name, filePath: item.filePath, tags: item.tags, url: item.url }))
})
```

`nuxt.config.ts`
```ts
export default defineNuxtConfig({
  nitro: {
    routeRules: {
      '/api/**': { cors: true, headers: { 'access-control-allowed-methods': 'GET' } },
    },
  }
})
```

`error`:
```shell
[nuxt] [request error] [unhandled] [500] response.json is not a function
  at /Users/user/Documents/Visual%20Studio%20Code/portfolio/.output/server/chunks/imgkit.mjs:14:31  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.handler (/Users/user/Documents/Visual%20Studio%20Code/portfolio/.output/server/node_modules/h3/dist/index.mjs:990:19)  
  at async toNodeHandle (/Users/user/Documents/Visual%20Studio%20Code/portfolio/.output/server/node_modules/h3/dist/index.mjs:1065:7)  
  at async ufetch (/Users/user/Documents/Visual%20Studio%20Code/portfolio/.output/server/node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async $fetchRaw2 (/Users/user/Documents/Visual%20Studio%20Code/portfolio/.output/server/node_modules/ofetch/dist/shared/ofetch.5c
```

FYI (`types/imgkit.d.ts`):
```ts
export {}
declare global {
  export interface ImageKit {
    aiTags: null
    createdAt: Date
    customCoordinates: null
    customMetadata: CustomMetadata
    embeddedMetadata: EmbeddedMetadata
    fileID: string
    filePath: string
    fileType: FileType
    hasAlpha: boolean
    height: number
    isPrivateFile: boolean
    mime: MIME
    name: string
    size: number
    tags: Tag[] | null
    thumbnail: string
    type: Type
    updatedAt: Date
    url: string
    versionInfo: VersionInfo
    width: number
  }

  export interface CustomMetadata {}

  export interface EmbeddedMetadata {
    imageHeight?: number
    imageSize?: ImageSize
    imageWidth?: number
    megapixels?: number
    colorSpace?: string
    dateCreated?: Date
    dateTimeCreated?: Date
    exifVersion?: string
    resolutionUnit?: string
    xResolution?: number
    yResolution?: number
  }

  export enum ImageSize {
    The1036X1554 = '1036x1554',
    The1273X849 = '1273x849',
    The1500X1500 = '1500x1500',
    The1554X1036 = '1554x1036',
    The600X750 = '600x750',
    The910X1365 = '910x1365'
  }

  export enum FileType {
    Image = 'image'
  }

  export enum MIME {
    ImageJPEG = 'image/jpeg',
    ImageWebp = 'image/webp'
  }

  export enum Tag {
    Architecture = 'architecture',
    Astrophotographie = 'astrophotographie',
    Empty = '*',
    Mariage = 'mariage',
    Nature = 'nature',
    Paysage = 'paysage',
    Portrait = 'portrait'
  }

  export enum Type {
    File = 'file'
  }

  export interface VersionInfo {
    id: string
    name: Name
  }

  export enum Name {
    Version1 = 'Version 1'
  }
}
```

**Comment by manniL** [comment]
The problem in your code seems more that you don't need to call `response.json()` when using `$fetch`.

**Comment by BenjaminOddou** [comment]
@manniL, super clear, thank you very much, really appreciate it 😃
