### ISSUE TITLE
Building a Nuxt 3 app inside Docker

### ISSUE THREAD

**Issue by gloriousky** [nuxt/nuxt#18974]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `modules`, `imports`, `vite`, `typescript`, `plugins`, `nitro`, `build`, `app`, `routeRules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@vueuse/nuxt@9.8.2`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

Inside docker building container:
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `ssr`, `css`, `modules`, `imports`, `vite`, `typescript`, `plugins`, `nitro`, `build`, `app`, `routeRules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.2.0`, `@vueuse/nuxt@9.8.2`, `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

1.create a new Nuxt 3 project:
`npx nuxi init .`

install this project dependencies
`yarn install`

(at this stage it is working on the host machine without docker)

Create a file Dockerfile containing the following content:
``` Dockerfile 
FROM node:16-alpine as builder
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
COPY nuxt.config.ts ./
RUN yarn set version 1.22.18
RUN yarn install
COPY . .
RUN yarn build

FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
COPY --from=builder /app/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```
4.Create a .gitignore file containing:
```
node_modules
.nuxt
.output
node_modules
Dockerfile
README.md
```

5.start building the image
docker build . -t nuxt-web:latest

get an error (see logs below)

### Describe the bug

When building a Nuxt 3 app using a Dockerfile the build fails because it can't load some plugins (see logs below).
I don't know if I'm doing something wrong because something drastically changed since Nuxt 2 or if it is a bug.

### Additional context

the build command work on the host machine just fine and create the .output folder.

### Logs

```shell-script
[+] Building 187.5s (15/20)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/nginx:stable-alpine                                             3.7s
 => [internal] load metadata for docker.io/library/node:16-alpine                                                  3.7s
 => CACHED [stage-1 1/5] FROM docker.io/library/nginx:stable-alpine@sha256:cc61d734c3045fa64f3d50173e5025e35e0074  0.0s
 => [builder  1/10] FROM docker.io/library/node:16-alpine@sha256:1621ddffc775ccf10dc8710660e70d5bfb8e4ee349b926f1  0.0s
 => [internal] load build context                                                                                  7.6s
 => => transferring context: 75.79MB                                                                               6.9s
 => CACHED [builder  2/10] WORKDIR /app                                                                            0.0s
 => CACHED [builder  3/10] COPY package.json ./                                                                    0.0s
 => CACHED [builder  4/10] COPY yarn.lock ./                                                                       0.0s
 => [builder  5/10] COPY nuxt.config.ts ./                                                                         0.6s
 => [builder  6/10] RUN yarn set version 1.22.18                                                                   3.9s
 => [builder  7/10] RUN yarn install                                                                             149.9s
 => [builder  8/10] COPY . .                                                                                      13.1s
 => ERROR [builder  9/10] RUN yarn build                                                                           8.6s
------
 > [builder  9/10] RUN yarn build:
#15 1.278 yarn run v1.22.18
#15 1.366 $ nuxt build
#15 1.533 Nuxi 3.0.0
#15 1.554 Nuxt 3.0.0 with Nitro 1.0.0
#15 3.415 ℹ Using default Tailwind CSS file from runtime/tailwind.css
#15 8.432
#15 8.432  ERROR  [vite]: Rollup failed to resolve import "Swiper" from "plugins/swiper.js".
#15 8.432 This is most likely unintended because it can break your application at runtime.
#15 8.432 If you do want to externalize this module explicitly add it to
#15 8.432 `build.rollupOptions.external`
#15 8.432
#15 8.436
#15 8.436  ERROR  [vite]: Rollup failed to resolve import "Swiper" from "plugins/swiper.js".
#15 8.436 This is most likely unintended because it can break your application at runtime.
#15 8.436 If you do want to externalize this module explicitly add it to
#15 8.436 `build.rollupOptions.external`
#15 8.436
#15 8.436   This is most likely unintended because it can break your application at runtime.
#15 8.436   If you do want to externalize this module explicitly add it to
#15 8.436   `build.rollupOptions.external`
#15 8.436   at onRollupWarning (node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45832:19)
#15 8.436   at onwarn (node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45603:13)
#15 8.436   at Object.onwarn (node_modules/rollup/dist/es/shared/rollup.js:23263:13)
#15 8.436   at ModuleLoader.handleResolveId (node_modules/rollup/dist/es/shared/rollup.js:22158:26)
#15 8.436   at node_modules/rollup/dist/es/shared/rollup.js:22119:26
#15 8.436
#15 8.474 error Command failed with exit code 1.
#15 8.475 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build]: exit code: 1
```

**Comment by danielroe** [comment]
I can't reproduce, either with 3.0.0 or with the latest Nuxt version (3.2.0). Also, I assume you have `node-modules` in your Dockerignore?

**Comment by gloriousky** [comment]
Here is [reproduction](https://github.com/gloriousky/Nuxt3-issue-example) with the latest Nuxt version.
I didn't add Dockerignore in my project.
