### ISSUE TITLE
Behavior between npm run dev and npm run build differs

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt/nuxt#18991]
Hello, I remarked that the following syntax is working fine on `npm run dev` instance, using `SSR` :

```vue
<script setup lang="ts">
import gsap from 'gsap'
const tl = gsap.timeline()
const isHover = () => tl.restart()
const isNotHover = () => tl.reverse()
onMounted(() => {
  //tl.to()...
})
</script>

<template>
<div 
    @mouseenter="isHover"
    @mouseleave="isNotHover"
>
</div>
</template>
```

However this is not a valid syntax  as `gsap.timeline()` should be defined under `onMounted` hook. Here is the full error message after `npm run build`
```shell
TypeError: gsap$3.timeline is not a function
    at setup (file:///Users/user/Documents/Visual%20Studio%20Code/portfolio/.output/server/chunks/app/server.mjs:7978:12)
    at _sfc_main$8.setup (file:///Users/user/Documents/Visual%20Studio%20Code/portfolio/.output/server/chunks/app/server.mjs:7992:25)
    at callWithErrorHandling (/Users/user/Documents/Visual Studio Code/portfolio/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:21:22)
    at setupStatefulComponent (/Users/user/Documents/Visual Studio Code/portfolio/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5771:29)
    at setupComponent (/Users/user/Documents/Visual Studio Code/portfolio/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5752:11)
    at renderComponentVNode (/Users/user/Documents/Visual Studio Code/portfolio/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:365:17)
    at renderVNode (/Users/user/Documents/Visual Studio Code/portfolio/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:492:22)
    at renderVNodeChildren (/Users/user/Documents/Visual Studio Code/portfolio/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:507:9)
    at renderElementVNode (/Users/user/Documents/Visual Studio Code/portfolio/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:558:17)
    at renderVNode (/Users/user/Documents/Visual Studio Code/portfolio/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:489:17)
```

Correct syntax :
```vue
<script setup lang="ts">
import gsap from 'gsap'
let tl: gsap.core.Timeline
const isHover = () => tl.restart()
const isNotHover = () => tl.reverse()
onMounted(() => {
  tl = gsap.timeline()
  //tl.to()...
})
</script>

<template>
<div 
    @mouseenter="isHover"
    @mouseleave="isNotHover"
>
</div>
</template>
```

The first piece of code causes no problem at all after `npm run dev` command which is quite confusing. Maybe there is something to improve in order to warn the user?

**Comment by madebyfabian** [comment]
Hi, Since this is a 3rd party library, there could be many reasons why it works on the dev server. But this is something the gsap library would have to detect (if it ran inside a onMounted) or not. And since it works when using it with the correct syntax, I currently don't see an issue. What would your improvements you've suggested imply?

**Comment by BenjaminOddou** [comment]
Hey @madebyfabian, thanks for the message. My point is that I would have expected the same behavior between dev and build. I was trying to understand why it was working on dev but maybe that's something inside GSAP that needs to be changed. My guess was that GSAP was loaded differently between dev and build which then leads to different behaviors. 🤔

**Comment by madebyfabian** [comment]
Yeah they're different environments, there for sure is a lot difference between the build and the devserver. But for my understanding, that's not something nuxt can actively change/fix. Maybe this would better fit as as discussion and not an issue.

**Comment by PumpkinPeasant** [comment]
> Yeah they're different environments, there for sure is a lot difference between the build and the devserver. But for my understanding, that's not something nuxt can actively change/fix. Maybe this would better fit as as discussion and not an issue.

Hi. Did you find the solution to this?

**Comment by sthompson232** [comment]
You will need to transpile gsap when you build. In `nuxt.config.js`:

```
  build: {
    transpile: ['gsap'],
  },
```
