### ISSUE TITLE
rollup parse problem after upgrade to Nuxt 3.2.0

### ISSUE THREAD

**Issue by misaon** [nuxt/nuxt#19017]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v19.6.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `pnpm@7.27.0`
- Builder:          `vite`
- User Config:      `modules`, `oxyshopNuxt`, `i18n`, `experimental`, `build`
- Runtime Modules:  `normalizedModule()`, `normalizedModule()`
- Build Modules:    `-`
------------------------------

### Reproduction

I can't provide

### Describe the bug

After upgrading to Nuxt 3.2.0 on projects using my Nuxt module, I started getting the following error. I don't really know what to do, I tried disabling experimental client-only treeshake and transpiling the library, without success.

```
 WARN  rollup-plugin-inject: failed to parse /app/node_modules/.pnpm/....my-plugin..../src/runtime/middleware/ipKiller.ts. Consider restricting the plugin to particular files via options.include


 ERROR  RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
```

**Comment by manniL** [comment]
Hey! Could you kindly provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by misaon** [comment]
@manniL reproduction added to the description. It is important to say that this is a monorepo and the test-module works in it. However, if you install the test-module as a dependency in another project, you will get this error. For now, I'm sticking with Nuxt 3.1.2

```
 WARN  rollup-plugin-inject: failed to parse /app/node_modules/.pnpm/@oxyshop+nuxt@1.16.16/node_modules/@oxyshop/nuxt/src/runtime/middleware/ipKiller.ts. Consider restricting the plugin to particular files via options.include


 ERROR  RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)


2: import { defineEventHandler, createError } from 'h3'
3: 
4: function isAwsHostValid(host: string | undefined) {
                               ^
5:   if (!host) {
6:     return false

✔ Nitro built in 7955 ms
```

**Comment by AloisSeckar** [comment]
There is definitely something wrong with Rollup in Nuxt 3.2.0

I was forced to remove manual chunking for DevExtreme UI, because I started getting

```
Entry module "devextreme-vue/button" cannot be external.

 ERROR  Entry module "devextreme-vue/button" cannot be external.                                                                       14:03:59

  at error (file://node_modules/rollup/dist/es/shared/rollup.js:2116:30)
  at ModuleLoader.loadEntryModule (file://node_modules/rollup/dist/es/shared/rollup.js:23385:20)
  at async Promise.all (index 0)
  at async Promise.all (index 0)
```

during production build, after I updated to 3.2.0 yesterday.

Reproduction: https://stackblitz.com/edit/github-tzag3d?file=plugins%2Fdx.client.ts,nuxt.config.ts 
(try running `npm run build`)

After commenting out `manualChunks` in `nuxt.config.ts` build works again - only the chunk for DevExtreme is now 2,3 MB. It was working since like september, when I established the project, with newest Nuxt it is broken.

**Comment by danielroe** [comment]
@AloisSeckar I think your issue is that on the server those will be externalised (which is a positive change upstream with nitro) which is causing this confusing error. Try this to create manual chunks only on the client build:

```js
import { defu } from 'defu';
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  hooks: {
    'vite:extendConfig'(config, { isClient }) {
      if (!isClient) return;
      config.build = defu(config.build, {
        chunkSizeWarningLimit: 1750,
        rollupOptions: {
          output: {
            manualChunks: {
              dxButton: ['devextreme-vue/button'], // ~0.4 MB
              dxDataGrid: ['devextreme-vue/data-grid'], // ~1.6 MB
            },
          },
        },
      });
    },
  },
});
```

> https://stackblitz.com/edit/github-tzag3d-vqseph?file=plugins%2Fdx.client.ts,nuxt.config.ts

**Comment by AloisSeckar** [comment]
Thank you, @danielroe, this works great.

I just realized one think I don't quite understand the build process. File in `node_modules` for `devextreme-vue/data-grid` has 90 KB. What happens during production build, that the result `dxDataGrid.614dfac9.js` chunk has 1,6 MB? It is bundling it together with all its internal dependencies into one independent file? Can I do something to optimize final outcome or is it inevitably that big? Can you point me to some docs/article, where I can read more about what's going on?

**Comment by danielroe** [comment]
Yes, it's tricky to configure rollup chunks. It won't include duplicate code, but it might add _more_ code to that chunk than you are expecting.

**Comment by sPaCeMoNk3yIam** [comment]
I also ran into this, when `import`ing a ts file directly that is part of an (internal) node package:
```
import { someFunction } from "@internal/package/lib/config";
```

```
RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
rollup-plugin-inject: failed to parse /Users/user/Projects/some-project/node_modulesinternal/package/lib/config.ts. Consider restricting the plugin to particular files via options.include
```

Before upgrading, it worked.

**Comment by misaon** [comment]
@sPaCeMoNk3yIam Thats true.

@danielroe If you import any raw .ts file from an external package in node_modules, you will get the following rollup error.
Do you have any ideas?

**Comment by danielroe** [comment]
Would you try adding any libraries that are not transpiled to `build.transpile`?

**Comment by japboy** [comment]
I have same issue with `@rollup/plugin-graphql@2.0.3` & `nuxt@3.2.2`/`nuxt@3.1.0`/`nuxt@3.0.0`. Any idea why?

```
 WARN  rollup-plugin-inject: failed to parse /path/to/schema.graphql. Consider restricting the plugin to particular files via options.include


 ERROR  RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)                                                                                                     nitro 09:15:01


1: type Query {
        ^
2:   hello: String
3: }
```

`nuxt.config.ts`

```ts
import graphql from '@rollup/plugin-graphql';
import { defineNuxtConfig } from "nuxt/config";

export default defineNuxtConfig({
  // This doesn't change the result
  // build: {
  //   transpile: ["@rollup/plugin-graphql"],
  // },
  vite: {
    plugins: [
      // @see https://vite-rollup-plugins.patak.dev/#graphql
      graphql(),
    ],
  },
});
```

`server/routes/graphql.ts`

```ts
// import { gql } from '@urql/vue'
import { createSchema, createYoga } from 'graphql-yoga'

import type { Query } from 'typing'

// FXIME: rollup-plugin-inject: failed to parse path/to/schema.graphql. Consider restricting the plugin to particular files via options.include
import schema from './schema.graphql'
/*
const schema = gql`
type Query {
  hello: String
}
`
*/

const yoga = createYoga({
  schema:  createSchema<Query>({
    typeDefs: schema,
    resolvers: {
      Query: {
        hello: () => 'Hello world!',
      },
    },
  }),
})

export default defineEventHandler((event) => {
  const { req, res } = event.node
  return yoga(req, res)
})
```

**Comment by misaon** [comment]
> Would you try adding any libraries that are not transpiled to `build.transpile`?

Yes, I tried, it didn't help.

**Comment by eminoda** [comment]
nitro: {
    rollupConfig: {
      external: ['ali-oss'], //this config maybe helpful, but i dont know why made this error
    },
  },

**Comment by eminoda** [comment]
When I use "ali-oss", nuxt build error cost many days to fix them:
- Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
- "Cannot find module" when main file not index.js
- rollup-plugin-inject: failed to parse *.ts. Consider restricting the plugin to particular files via options.include
- ...

I try to setting nitro.rollupConfig.plugins which become better,but not fix all:
````js
// nuxt.config.ts
  nitro: {
    rollupConfig: {
      // external: ['ali-oss'],
      plugins: [
        nodeResolve({
          exportConditions: ['node'],
          extensions: ['.mjs', '.node'],
        }),
      ],
    },
    node: true,
````

see "node_modules\nitropack\dist\shared\nitro.908171be.mjs", you can find there code:
```js
  rollupConfig.plugins.push(
    nodeResolve({
      // extensions,
      extensions: [  '.mjs', '.js', '.json', '.node','.ts'  ], // change this line
      preferBuiltins: !!nitro.options.node,
      rootDir: nitro.options.rootDir,
      modulePaths: nitro.options.nodeModulesDirs,
      // 'module' is intentionally not supported because of externals
      mainFields: ["main"],
      exportConditions: [
        "default",
        nitro.options.dev ? "development" : "production",
        "module",
        "node",
        "import"
      ]
    })
  );
```

So you can rewrite  nitro.rollupConfig.plugins setting which can fix this problem.

**Comment by hoangquochung95** [comment]
I face the problem @rollup of vite when run build 
`
 ERROR  "extname" is not exported by "__vite-browser-external", imported by "node_modules/@rollup/pluginutils/dist/es/index.js".`

**Comment by premiermatt** [comment]
> I face the problem @rollup of vite when run build ` ERROR "extname" is not exported by "__vite-browser-external", imported by "node_modules/@rollup/pluginutils/dist/es/index.js".`

I have this exact issue - can't find any fixes. Upgraded to Nuxt 3.4.1 with Nitro 2.3.3. Error is still present.

**Comment by jamieowen** [comment]
Same/Similar problem with scss files imported from module inside node_modules. On the Nitro server build.

**Comment by Jamiewarb** [comment]
> I have same issue with `@rollup/plugin-graphql@2.0.3` & `nuxt@3.2.2`/`nuxt@3.1.0`/`nuxt@3.0.0`. Any idea why?

@japboy you've only given the `graphql plugin to `vite`'s Rollup config, but you're also using them in your Nitro server.

To fix your issue, you need to also pass graphql plugin to nitro's rollup config:

```
// nuxt.config.ts
export default defineNuxtConfig({
  vite: {
    plugins: [graphql()], // Allow usage of .gql/.graphql files
  },

  nitro: {
    rollupConfig: {
      // @ts-expect-error "Type instantiation is excessively big" - I don't know what to do about that
      plugins: [
        graphql(),
      ], // Allow usage of .gql/.graphql files
    },
  },
});
```

**Comment by Som-comite** [comment]
ERROR  "devRootDir" is not exported by "virtual:nuxt://.nuxt/nuxt.config.mjs"

**Comment by martinszeltins** [comment]
I am experiencing this same problem with Nuxt `3.6.5`

**Comment by danielroe** [comment]
Closing as this is basically about ensuring that modules that use TypeScript or otherwise need to be transpiled, are added to `build.transpile`, rather than an issue with Nuxt.

**Comment by martinszeltins** [comment]
> Closing as this is basically about ensuring that modules that use TypeScript or otherwise need to be transpiled, are added to `build.transpile`, rather than an issue with Nuxt.

I think it would be very helpful if there was a better error message saying that the module needs to be added to the `build.transpile`, otherwise it's a lot of wasted time trying to figure out why it is not working.

**Comment by lmq352489099** [comment]
> 
me too ,how to do this question ,
```
ℹ ✓ built in 13.04s                                                                                                       17:34:27
✔ Server built in 13060ms                                                                                                 17:34:27
✔ Generated public .output/public                                                                                   nitro 17:34:27
ℹ Building Nitro Server (preset: node-server)                                                                       nitro 17:34:27
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/client/getReqUrl.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/createRequest.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/encoder.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/setSTSToken.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/isFunction.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/retry.ts. Consider restricting the plugin to particular files via options.include
(esbuild plugin) [esbuild] (.nuxt/dist/server/_nuxt/writer-5235dab7.js:1563:10) This assignment will throw because "cur_notebook" is
a constant
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/isBuffer.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/obj2xml.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/checkBucketName.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/deepCopy.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/setRegion.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/checkConfigValid.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/getBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/completeBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/deleteBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/putBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/abortBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/initiateBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/extendBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/listBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/getBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/object/postAsyncFetch.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/object/getAsyncFetch.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/checkBucketTag.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/formatObjKey.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/policy2Str.ts. Consider restricting the plugin to particular files via options.include

 ERROR  RollupError: Unexpected keyword 'this' (Note that you need plugins to import files that are not JavaScript)  nitro 17:35:31


 7: import { checkConfigValid } from '../utils/checkConfigValid';
 8:
 9: export function getReqUrl(this: any, params) {
                              ^
10:   const ep: any = {};
11:   const isCname = this.options.cname;

 ERROR  Unexpected keyword 'this' (Note that you need plugins to import files that are not JavaScript)  
```

**Comment by lmq352489099** [comment]
> When I use "ali-oss", nuxt build error cost many days to fix them:
> 
> * Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
> * "Cannot find module" when main file not index.js
> * rollup-plugin-inject: failed to parse *.ts. Consider restricting the plugin to particular files via options.include
> * ...
> 
> I try to setting nitro.rollupConfig.plugins which become better,but not fix all:
> 
> ```js
> // nuxt.config.ts
>   nitro: {
>     rollupConfig: {
>       // external: ['ali-oss'],
>       plugins: [
>         nodeResolve({
>           exportConditions: ['node'],
>           extensions: ['.mjs', '.node'],
>         }),
>       ],
>     },
>     node: true,
> ```
> 
> see "node_modules\nitropack\dist\shared\nitro.908171be.mjs", you can find there code:
> 
> ```js
>   rollupConfig.plugins.push(
>     nodeResolve({
>       // extensions,
>       extensions: [  '.mjs', '.js', '.json', '.node','.ts'  ], // change this line
>       preferBuiltins: !!nitro.options.node,
>       rootDir: nitro.options.rootDir,
>       modulePaths: nitro.options.nodeModulesDirs,
>       // 'module' is intentionally not supported because of externals
>       mainFields: ["main"],
>       exportConditions: [
>         "default",
>         nitro.options.dev ? "development" : "production",
>         "module",
>         "node",
>         "import"
>       ]
>     })
>   );
> ```
> 
> So you can rewrite nitro.rollupConfig.plugins setting which can fix this problem.

me too ,how to do this question ,
```

ℹ ✓ built in 13.04s                                                                                                       17:34:27
✔ Server built in 13060ms                                                                                                 17:34:27
✔ Generated public .output/public                                                                                   nitro 17:34:27
ℹ Building Nitro Server (preset: node-server)                                                                       nitro 17:34:27
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/client/getReqUrl.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/createRequest.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/encoder.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/setSTSToken.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/isFunction.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/retry.ts. Consider restricting the plugin to particular files via options.include
(esbuild plugin) [esbuild] (.nuxt/dist/server/_nuxt/writer-5235dab7.js:1563:10) This assignment will throw because "cur_notebook" is
a constant
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/isBuffer.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/obj2xml.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/checkBucketName.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/deepCopy.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/setRegion.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/checkConfigValid.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/getBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/completeBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/deleteBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/putBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/abortBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/initiateBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/extendBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/listBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/getBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/object/postAsyncFetch.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/object/getAsyncFetch.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/checkBucketTag.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/formatObjKey.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/policy2Str.ts. Consider restricting the plugin to particular files via options.include

 ERROR  RollupError: Unexpected keyword 'this' (Note that you need plugins to import files that are not JavaScript)  nitro 17:35:31


 7: import { checkConfigValid } from '../utils/checkConfigValid';
 8:
 9: export function getReqUrl(this: any, params) {
                              ^
10:   const ep: any = {};
11:   const isCname = this.options.cname;

 ERROR  Unexpected keyword 'this' (Note that you need plugins to import files that are not JavaScript)  
```

**Comment by lmq352489099** [comment]
> 当我使用“ali-oss”时，nuxt构建错误需要很多天才能修复它们：
> 
> * 错误：意外的令牌（请注意，您需要插件来导入非 JavaScript 的文件）
> * 当主文件不是index.js时“找不到模块”
> * rollup-plugin-inject：无法解析 *.ts。考虑通过 options.include 将插件限制为特定文件
> * ...
> 
> 我尝试设置 nitro.rollupConfig.plugins 变得更好，但不能修复所有问题：
> 
> ```js
> // nuxt.config.ts
>   nitro: {
>     rollupConfig: {
>       // external: ['ali-oss'],
>       plugins: [
>         nodeResolve({
>           exportConditions: ['node'],
>           extensions: ['.mjs', '.node'],
>         }),
>       ],
>     },
>     node: true,
> ```
> 
> 参见“node_modules\硝基包\dist\shared\硝基.908171be.mjs”，你可以找到那里的代码：
> 
> ```js
>   rollupConfig.plugins.push(
>     nodeResolve({
>       // extensions,
>       extensions: [  '.mjs', '.js', '.json', '.node','.ts'  ], // change this line
>       preferBuiltins: !!nitro.options.node,
>       rootDir: nitro.options.rootDir,
>       modulePaths: nitro.options.nodeModulesDirs,
>       // 'module' is intentionally not supported because of externals
>       mainFields: ["main"],
>       exportConditions: [
>         "default",
>         nitro.options.dev ? "development" : "production",
>         "module",
>         "node",
>         "import"
>       ]
>     })
>   );
> ```
> 
> 所以你可以重写 ninto.rollupConfig.plugins 设置来解决这个问题。

ℹ ✓ built in 13.04s                                                                                                       17:34:27
✔ Server built in 13060ms                                                                                                 17:34:27
✔ Generated public .output/public                                                                                   nitro 17:34:27
ℹ Building Nitro Server (preset: node-server)                                                                       nitro 17:34:27
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/client/getReqUrl.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/createRequest.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/encoder.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/setSTSToken.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/isFunction.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/retry.ts. Consider restricting the plugin to particular files via options.include
(esbuild plugin) [esbuild] (.nuxt/dist/server/_nuxt/writer-5235dab7.js:1563:10) This assignment will throw because "cur_notebook" is
a constant
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/isBuffer.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/obj2xml.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/checkBucketName.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/deepCopy.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/setRegion.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/checkConfigValid.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/getBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/completeBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/deleteBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/putBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/abortBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/initiateBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/extendBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/listBucketInventory.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/bucket/getBucketWorm.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/object/postAsyncFetch.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/object/getAsyncFetch.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/checkBucketTag.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/formatObjKey.ts. Consider restricting the plugin to particular files via options.include
(inject plugin) rollup-plugin-inject: failed to parse F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/ali-oss/lib/common/utils/policy2Str.ts. Consider restricting the plugin to particular files via options.include

 ERROR  RollupError: Unexpected keyword 'this' (Note that you need plugins to import files that are not JavaScript)  nitro 17:35:31


 7: import { checkConfigValid } from '../utils/checkConfigValid';
 8:
 9: export function getReqUrl(this: any, params) {
                              ^
10:   const ep: any = {};
11:   const isCname = this.options.cname;

 ERROR  Unexpected keyword 'this' (Note that you need plugins to import files that are not JavaScript)

**Comment by ifredom** [comment]
> transpile
How to solve it? I also used the ali-oss package and encountered the same error when packaging.
![image](https://github.com/nuxt/nuxt/assets/13759936/8ed274f4-3ec7-4c87-9512-c379c513e22a)
