### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#19113]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.2`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`
- Runtime Modules:  `@pinia/nuxt@0.4.6`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-u9cwfg

### Describe the bug

If you load this urls first time:
https://nuxtstarteru9cwfg-ptc5--3000.local-credentialless.webcontainer.io/393

Loads OK!, but if you refresh this urls throws an error:

`Converting circular structure to JSON --> starting at object with constructor 'Object' | property '_context' -> object with constructor 'Object' --- property 'app' closes the circle

at JSON.stringify ()
at Object.toDisplayString (./node_modules/@vue/shared/dist/shared.cjs.js:448:24)
at Module.ssrInterpolate (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:181:37)
at _sfc_ssrRender (./src/pages/[postId].js:32:220)
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:17)
at eval (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:641:29)
at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:865:24)
at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:871:24)
at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:871:24)
at async unrollBuffer$1 (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:871:24)`

**Comment by danielroe** [comment]
You should access `album.state` and not `album` in your template.
