### ISSUE TITLE
Nitro proxy settings are not taking effect.

### ISSUE THREAD

**Issue by cpt-n3mo** [nuxt/nuxt#19325]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v19.6.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `nitro`, `css`, `postcss`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

export default defineNuxtConfig({
  nitro: {
    devProxy: {
      '/proxy/rust': {
        target: 'http:127.0.0.1:8000',
        prependPath: true,
        changeOrigin: true,
      },
    }
  }
})

### Describe the bug

nitro proxy is not using settings described in nuxt.config.ts

### Additional context

rust backand is running on 127.0.0.1:8000
nuxt running on 127.0.0.1:3000

### Logs

```shell-script
http://127.0.0.1:3000/proxy/rust/some_route
[HTTP/1.1 500 internal server error]

```
```

**Comment by pi0** [comment]
Hi. `devProxy` is not supported through direct fetch. You can either fetch with full URL (`http://localhost:3000/proxy/...`) or better use new runtime proxy via route rules https://nitro.unjs.io/config#routerules

**Comment by cpt-n3mo** [comment]
nice this seems to work thx..!
one thing though the docs are going all over the place..
first it was vite proxy then nitro proxy then routeRules, this makes things mighty confusing..
it would be nice if docs could be updated..

**Comment by pi0** [comment]
Happy it is working for you now. Indeed we need to unify docs little bit more. For context, vite proxy is also only dev only and inherits more limitations. devProxy is more powerful and using Node.js HTTP module but only works in development environment and not supporting direct fetch. New runtime proxy via route rules (you can directly use `sendProxy` in server routes too) is powered by native fetch and streaming support. Probably best option for universal usage.

**Comment by ekrausso** [comment]
@piO I'm having an issue with nitro routeRules proxy... basically it 'fails to fetch' when sending a form-data body... I have another POST call with JSON body and it goes through without issues... 
I've confirmed its nitro since I tried setting up an nginx to proxy requests and everything works fine.

**Comment by pi0** [comment]
Is it happening for dev environment too @ekrausso? Any chance you can make a small reproduction ?

**Comment by ekrausso** [comment]
@pi0 yes both in production and dev... I'll see if I can make a small repro and get back to you

**Comment by freddy-daniel** [comment]
It's still not working.

**Comment by seijikohara** [comment]
I am also having the same problem, I have no problem with the GET and POST methods, but DELETE gives me an error.

- Error log when executing DELETE http://127.0.0.1:3000/api/v2/users/sign_out

```
[nuxt] [request error] [unhandled] [500] fetch failed (http://127.0.0.1:3000/api/v2/users/sign_out)                                            10:50:06 PM
  at async sendProxy (./node_modules/h3/dist/index.mjs:506:20)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1247:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)
```

- My environment is as follows

```
- Operating System: Darwin
- Node Version:     v18.12.1
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, devServer, app, modules, css, vite, runtimeConfig, pinia, build, nitro, typescript
- Runtime Modules:  @bootstrap-vue-next/nuxt@0.0.5, @pinia/nuxt@0.4.8
- Build Modules:    -
```

**Comment by freddy-daniel** [comment]
> It's still not working. "nuxt": "^3.3.2",

Got it work. Found i've mis-configured base url

**Comment by jonkri** [comment]
I may have missed something, but I don't think the documentation (for neither Nuxt or Nitro) mentions that `proxy.to` can be used, like in @pi0's example:

> ```ts
> defineNuxtConfig({
>   routeRules: {
>     '/proxy/rust/**': { proxy: { to: 'http://127.0.0.1:8000/**' } }
>   }
> })
> ```

**Comment by vushe** [comment]
Even though proxy is working, I can't get headers working like so (I expect following should inject headers into proxy request).
@pi0, could you kindly clarify it?

```
nitro: {
    routeRules: {
        '/proxy/**': {
            proxy: `https://some-host.com/api/**`,
            headers: {
                'x-api-key': '12345',
            },
            cors: true,
        },
    },
},
```

Also doesn't work:
```
nitro: {
    routeRules: {
        '/proxy/**': {
            proxy: {
               to: `https://some-host.com/api/**`,
               headers: {
                   'x-api-key': '12345',
               },
           },
            cors: true,
        },
    },
},
```

**Comment by Aaron-AnHe** [comment]
ohh，thanks，this problem has bothered me for a long time，my problem is : devProxy does not proxy when refreshing the page.....

**Comment by shenyanshu** [comment]
> 
"Me too. Have you found a solution?"

**Comment by tghsjtmk** [comment]
> Hi. `devProxy` is not supported through direct fetch. You can either fetch with full URL (`http://localhost:3000/proxy/...`) or better use new runtime proxy via route rules https://nitro.unjs.io/config#routerules
> 
> ```ts
> defineNuxtConfig({
>   routeRules: {
>     '/proxy/rust/**': { proxy: { to: 'http://127.0.0.1:8000/**' } }
>   }
> })
> ```

I can use proxy in this way. however it fails when doing useFetch with multipart data.

"nuxt": "^3.5.1",
``` 
  routeRules: {
    "/arjuna/**": {
      proxy: {
        to: `${API_URL}/**`,
      },
    },
  },
```

**Comment by harish2704** [comment]
I saw similar issue reported under different titles in Nuxt3. 
Since I was not able to find a proper fix for this solution, I fixed it by
1. Removed entry from  `routeRuels` in `nuxt.config.js`
     ```
    -            "/api/**": {
    -                proxy: "http://localhost:3001/api/**"
    -            }
    ```
2. Created a server route ( server/api/[...].js) as show below
    ```
    ├── nuxt.config.js
    ├── pages
    ├── public
    ├── server
    │   └── api
    │       └── [...].js
    ```
3. Added following content to server route handler
    ```javascript
    // server/api/[...].js
    import { proxyRequest, getRequestURL } from "h3";
    
    export default defineEventHandler((event) => {
      const reqUrl = getRequestURL(event);
      return proxyRequest(event, "http://localhost:3001" + reqUrl.pathname + reqUrl.search );
    });
    ```

This minimal route handler was working fine for my use case

**Comment by pi0** [comment]
Do you mind to report this to [nitro repo](https://github.com/unjs/nitro/issues/new/choose) with a [minimal reproduction](https://stackblitz.com/github/unjs/nitro/tree/starter)? 🙏🏼

**Comment by nhan-ho-saltovn** [comment]
> I saw similar issue reported under different titles in Nuxt3. Since I was not able to find a proper fix for this solution, I fixed it by
> 
> 1. Removed entry from  `routeRuels` in `nuxt.config.js`
>    ```
>    -            "/api/**": {
>    -                proxy: "http://localhost:3001/api/**"
>    -            }
>    ```
> 2. Created a server route ( server/api/[...].js) as show below
>    ```
>    ├── nuxt.config.js
>    ├── pages
>    ├── public
>    ├── server
>    │   └── api
>    │       └── [...].js
>    ```
> 3. Added following content to server route handler
>    ```js
>    // server/api/[...].js
>    import { proxyRequest, getRequestURL } from "h3";
>    
>    export default defineEventHandler((event) => {
>      const reqUrl = getRequestURL(event);
>      return proxyRequest(event, "http://localhost:3001" + reqUrl.pathname + reqUrl.search );
>    });
>    ```
> 
> This minimal route handler was working fine for my use case

I tried this solution, but it doesn't work :( Having the same trouble when post body with type mutipart/form-data

**Comment by harish2704** [comment]
@nhan-ho-saltovn : it is possible.  ` mutipart/form-data` may need special handling .  
Your may need to refer `readMultipartFormData`  from https://github.com/unjs/h3

**Comment by sei-aderr** [comment]
@seijikohara Did you ever find a solution to that issue? I am running into the same issue where HTTP GET and POST work, but as soon as I change it to a DELETE, my API does not receive the request even though the JS console reports an internal server error. Then I get the same error logs in my nuxt console.

It only seems to happen on a route using the route rules though, as when I go to a test endpoint on a public server, the HTTP delete works as expected.

**Comment by TM-SunnyDay** [comment]
@seijikohara @sei-aderr 
I found the same issue unjs/h3#375 where someone gave a solution.

> Found a fix from [unjs/nitro#1137](https://github.com/unjs/nitro/issues/1137)
> 
> `export NODE_OPTIONS='--no-experimental-fetch'`
> 
> It seems the experimental fetch doesn't like `content-length: 0` for deletes.

**Comment by seijikohara** [comment]
@sei-aderr @TM-SunnyDay 
I resolved this issue by replacing it with the nuxt-proxy module.

**Comment by hadimajidi** [comment]
> ```ts
> routeRules: {
>     '/proxy/rust/**': { proxy: { to: 'http://127.0.0.1:8000/**' } }
>   }
> ```

Dear pi0
I checked that out with tow different ways like this

  nitro: {
    routeRules: {
      "/api/xxx": {
        proxy: "http://127.0.0.1:8000/api/xxx",
      },
    },
    devProxy: {
      "/api/login": {
        target: "http://127.0.0.1:8000/api/xxx",
        changeOrigin: true,
      },
    }
  },

in both way dev and build the respose of the server are the same while dev mode Nuxt accept the answer. But in build mode the request in connction is keep-alive and dev mode connection is close. 
afterward i tried to do like this
  nitro: {
    routeRules: {
      "/api/xxx": {
        proxy: "http://127.0.0.1:8000/api/xxx",
        headers: {
          'Connection': 'close',
        },
      },
but it was the same as connection: "keep-alive". because the source of the error comes from tcp connection i think the problem source is the connection. Do you? 
Woman life freedom

**Comment by mrzdevcore** [comment]
This works perfectly for me

```ts
export default defineNuxtConfig({
 ....
  routeRules: {
    '/proxy/**': {
      proxy: 'https://my-api.com/**'
    }
  },
...
}
```

**Comment by danielroe** [comment]
I think we can close this as this should now be resolved in nitro. If anyone is still experiencing an issue, please see if you can reproduce with pure nitro and raise an issue at https://github.com/unjs/nitro. :pray:

**Comment by jorismak** [comment]
Complete new nuxt 3.9 project scaffolded with `bunx nuxi@latest create`, and the routeRules seem to do nothing.

How can I figure out if this is in the nuxt part or the nitro part? Do I need to update nitro or enable experimental things somewhere?

**Comment by jorismak** [comment]
💡  I think I realised it (untested yet).
But nitro is only used when building the production server. So everything related to routeRules and devProxy that are nitro settings, isn't working until you are building for production.

In the devserver, I'm using (we are using) Vite of course, so any kind of proxy settings have to be Vite settings, not Nitro.
Little d'oh moment :).

**Comment by pi0** [comment]
@jorismak Nitro is the same server engine used for development too. `routeRules` are effective and `devProxy` is _only_ for development time. When running Nuxt in development, we also add a vite (or webpack) dev middleware that enabled full stack development.

If `routeRules` is not working as expected, feel free to make a new issue with reproduction or part of your config 🙏🏼

**Comment by jorismak** [comment]
I'm about to ask 'are you sure' but seeing your name and involvement I think you'll know a from b here:).

Routerules directly in nuxt.config I couldn't get it to work. (Proxy that is). Trying to get everything that starts with /api to end up at a different go or php backend that's running. Kept getting 500 no such route errors.

Tried the same with devProxy in a nitro block in nuxt.config, but nothing. The same 500 errors. Sometimes a tiny bit of jaon saying 500, sometimes a full blown html 500 error page from nuxt.

Setting the proxy in a server block in a vite block in nuxt.config worked instantly (well, after fixing some SSL related issues ). 

Am I having the wrong expectations from devproxy or proxy rules in routeRules? Or is something not working as it should?

**Comment by pi0** [comment]
`routeRules` with `proxy` rule should work universally and it is the recommended method of defining proxy, unless you really need advanced dynamics or custom behavior (/cc @manniL you know I mentioned you this before, but again)

**Comment by jorismak** [comment]
Of course... now it's working all of sudden. **flabbergasted**.

I _**think**_ that the problem les in the fact that I try to proxy to an internal https host, that requires a custom CA to work without errors / warnings.

Setting up Vite's devserver-proxy, showed me an error message in the console running `bun run dev` showing a SSL client error. That made me disable strict SSL checking, and then Vite worked.

Now trying again with routeRules, and it works. I guess the real reason it didn't work before was a SSL client error buried deep in the stacktrace somewhere. But Nuxt was still responding with 'no such route', but that might be because the proxy failed.

Did a quick test with removing the NODE_EXTRA_CA_CERTS environment var, then I get this:
```
[nuxt] [request error] [unhandled] [500] fetch failed
  at Object.fetch (node:internal/deps/undici/undici:11730:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async sendProxy (./node_modules/h3/dist/index.mjs:1080:20)
  at async Object.handler (./node_modules/h3/dist/index.mjs:1676:19)
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1886:7)
```

While the Vite devserver proxy gives me this:
```
 ERROR  http proxy error at /api/test:                                                                      1:24:22 PM
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at ssl.onhandshakedone (node:_tls_wrap:871:12)
```

Which gave me the proper hint that it was a SSL client error.

With the NODE_EXTRA_CA_CERTS env var both work fine.

Now that I think about this, I'm tested the proxy (now) with a local curl command. In the dev-server I get 'fetch failed', which now seems obvious that Nitro is failing its fetch to reach the proxy.

But first I was testing from nuxt, so I was trying to access the proxied URL with `useFetch()`. if I then see a 500 error from nuxt with 'fetch failed', I don't think it could be an error in the nitro-proxy trying to reach its target, I'm thinking useFetch() failed. The error sent me in the wrong direction.

And a lot of lessons learned here for me, but yay it's working :).
