### ISSUE TITLE
After creating new Nuxt 3 project, it gives me a Write EPIPE error

### ISSUE THREAD

**Issue by eyopa21** [nuxt/nuxt#19457]
### Environment

_I have updated version of node and nuxi_

- Windows 11
- Node 18.14.2
- Nuxi 9.5.0

to create the error, 
`npx nuxi init test`
`cd test`
`yarn` 
`yarn dev`
** ERROR  [unhandledRejection] The service was stopped: write EPIPE                                                          10:42:14

  at node_modules\vite\node_modules\esbuild\lib\main.js:1145:25
  at responseCallbacks.<computed> (node_modules\vite\node_modules\esbuild\lib\main.js:701:9)
  at afterClose (node_modules\vite\node_modules\esbuild\lib\main.js:691:28)
  at node_modules\vite\node_modules\esbuild\lib\main.js:2097:11
  at onwriteError (node:internal/streams/writable:418:3)
  at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

 ERROR  (node:16056) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)        10:42:14
(Use `node --trace-warnings ...` to show where the warning was created)**

### Reproduction

https://github.com/eyopa21/salehu

### Describe the bug

the bug blocks the HMR and I can't also execute the script block

### Logs

```shell-script
ERROR [unhandledRejection] The service was stopped: write EPIPE 10:42:14

at node_modules\vite\node_modules\esbuild\lib\main.js:1145:25
at responseCallbacks. (node_modules\vite\node_modules\esbuild\lib\main.js:701:9)
at afterClose (node_modules\vite\node_modules\esbuild\lib\main.js:691:28)
at node_modules\vite\node_modules\esbuild\lib\main.js:2097:11
at onwriteError (node:internal/streams/writable:418:3)
at process.processTicksAndRejections (node:internal/process/task_queues:84:21)

ERROR (node:16056) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3) 10:42:14
(Use node --trace-warnings ... to show where the warning was created)
```

**Comment by Baroshem** [comment]
Hey,

could you please create a reproduction link in Stackblitz? It will be easier for testing :)
