### ISSUE TITLE
Redis driver requires either a host, url or cluster option

### ISSUE THREAD

**Issue by minkoonim** [nuxt/nuxt#19499]
### Environment

node lts
nuxt latest

### Reproduction

just use redis with nuxt

### Describe the bug

Please have a look from
https://github.com/unjs/unstorage/issues/172

### Additional context

![image](https://user-images.githubusercontent.com/38183949/223380228-986cd061-a421-40b6-b236-11a74e4acfa1.png)

### Logs

```shell-script
ERROR  Redis driver requires either a host, url or cluster option                                                                                      17:25:17

  at getRedisClient (node_modules/unstorage/drivers/redis.mjs:10:13)
  at dispose (node_modules/unstorage/drivers/redis.mjs:57:14)
  at asyncCall (node_modules/unstorage/dist/shared/unstorage.c2211058.mjs:9:26)
  at dispose (node_modules/unstorage/dist/index.mjs:346:11)
  at node_modules/unstorage/dist/index.mjs:252:55
  at Array.map (<anonymous>)
  at Object.dispose (node_modules/unstorage/dist/index.mjs:252:39)
  at node_modules/nitropack/dist/shared/nitro.908171be.mjs:3635:25
  at node_modules/hookable/dist/index.mjs:39:82
```

**Comment by pi0** [comment]
Please see https://github.com/unjs/unstorage/issues/172#issuecomment-1458099561
