### ISSUE TITLE
Dynamic assets image fails

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#19498]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `tailwindcss`, `vite`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.5.0`, `@nuxtjs/tailwindcss@6.4.1`, `formidable@2.1.1`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.13.0`, `@nuxtjs/i18n-edge@8.0.0-beta.9-27948515.3db6367`, `nuxt-schema-org@1.1.0-beta.6`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`

### Reproduction

we want to use dinamic urls like this... but throws an error
` <img class="w-70 h-70 mx-auto" :src="'~/assets/img/'+link.icon+'.svg'" alt="contact header" />`

[nuxt] error caught during app initialization Error: Page not found: /~/assets/img/chat.svg
    at Module.createError (/home/foticos/var/www/wanapix_next/node_modules/h3/dist/index.mjs:128:15)
    at /home/foticos/var/www/wanapix_next/node_modules/nuxt/dist/pages/runtime/plugins/router.mjs:141:113
    at triggerAfterEach (/home/foticos/var/www/wanapix_next/node_modules/vue-router/dist/vue-router.mjs:3306:13)
    at /home/foticos/var/www/wanapix_next/node_modules/vue-router/dist/vue-router.mjs:3209:13
    at process.processTicksAndRejections (/home/foticos/var/www/wanapix_next/lib/internal/process/task_queues.js:95:5)
    at async /home/foticos/var/www/wanapix_next/node_modules/nuxt/dist/pages/runtime/plugins/router.mjs:157:7
    at async createNuxtAppServer (/home/foticos/var/www/wanapix_next/node_modules/nuxt/dist/app/entry.mjs:30:7)
    at async default (/home/foticos/var/www/wanapix_next/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
    at async Object.renderToString (/home/foticos/var/www/wanapix_next/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
    at async file:///home/foticos/var/www/wanapix_next/.nuxt/dev/index.mjs:2945:21 {statusCode: 404, fatal: false, unhandled: false, statusMessage: 'Page not found: /~/assets/img/chat.svg', __nuxt_error: true, …}

If i use 
`<img class="w-70 h-70 mx-auto" :src="'_nuxt/assets/img/'+link.icon+'.svg'" alt="contact header" />`

Runs Ok

### Describe the bug

we want to use dinamic urls like this... but throws an error
 `<img class="w-70 h-70 mx-auto" :src="'~/assets/img/'+link.icon+'.svg'" alt="contact header" />`

[nuxt] error caught during app initialization Error: Page not found: /~/assets/img/chat.svg
    at Module.createError (/home/foticos/var/www/wanapix_next/node_modules/h3/dist/index.mjs:128:15)
    at /home/foticos/var/www/wanapix_next/node_modules/nuxt/dist/pages/runtime/plugins/router.mjs:141:113
    at triggerAfterEach (/home/foticos/var/www/wanapix_next/node_modules/vue-router/dist/vue-router.mjs:3306:13)
    at /home/foticos/var/www/wanapix_next/node_modules/vue-router/dist/vue-router.mjs:3209:13
    at process.processTicksAndRejections (/home/foticos/var/www/wanapix_next/lib/internal/process/task_queues.js:95:5)
    at async /home/foticos/var/www/wanapix_next/node_modules/nuxt/dist/pages/runtime/plugins/router.mjs:157:7
    at async createNuxtAppServer (/home/foticos/var/www/wanapix_next/node_modules/nuxt/dist/app/entry.mjs:30:7)
    at async default (/home/foticos/var/www/wanapix_next/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
    at async Object.renderToString (/home/foticos/var/www/wanapix_next/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
    at async file:///home/foticos/var/www/wanapix_next/.nuxt/dev/index.mjs:2945:21 {statusCode: 404, fatal: false, unhandled: false, statusMessage: 'Page not found: /~/assets/img/chat.svg', __nuxt_error: true, …}

If i use 
`<img class="w-70 h-70 mx-auto" :src="'_nuxt/assets/img/'+link.icon+'.svg'" alt="contact header" />`

Runs Ok

**Comment by raphaelbernhart** [comment]
This is not a bug. This is due to how vite works.

Here you can see solutions to your problem.
https://stackoverflow.com/questions/66419471/vue-3-vite-dynamic-image-src

**Comment by manniL** [comment]
Consolidating in https://github.com/nuxt/nuxt/issues/14766
