### ISSUE TITLE
500 Error - useNestedBar is not defined when viewing auto-import sandbox examples

### ISSUE THREAD

**Issue by mxttwoods** [nuxt/nuxt#19520]
### Environment

https://nuxt.com/docs/examples/auto-imports/composables

Seems to be in both the code sandbox and stack blitz viewers.

### Reproduction

https://codesandbox.io/s/github/nuxt/nuxt/tree/main/examples/auto-imports/composables?from-embed

### Describe the bug

Seems that the constant useNestedBar is not defined in `use-foo.ts` (https://github.com/nuxt/nuxt/blob/main/examples/auto-imports/composables/composables/use-foo.ts#L22) 

### Additional context

Was just browsing the docs and came across this issue. 

### Logs

```shell-script
> Sandbox Container: Starting sandbox ex59j3...
> Sandbox Container: Sandbox ex59j3 started
[Vue warn]: Unhandled error during execution of setup function        04:55:47
  at <App>
[Vue warn]: Unhandled error during execution of setup function        04:56:10
  at <App>
[nitro] [dev] [unhandledRejection] ReferenceError: useNestedBar is not defined
    at setup (/sandbox/app.vue:17:13)
    at _sfc_main.setup (/sandbox/app.vue:119:23)
    at callWithErrorHandling (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at setupStatefulComponent (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7176:29)
    at setupComponent (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7131:11)
    at renderComponentVNode (/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)
    at Module.ssrRenderComponent (/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:624:12)
    at default (/sandbox/node_modules/nuxt/dist/app/components/nuxt-root.vue:54:37)
    at Module.ssrRenderSuspense (/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:966:9)
    at _sfc_ssrRender (/sandbox/node_modules/nuxt/dist/app/components/nuxt-root.vue:49:25)
[Vue warn]: Unhandled error during execution of setup function        04:56:12
  at <App>
[nitro] [dev] [unhandledRejection] ReferenceError: useNestedBar is not defined
    at setup (/sandbox/app.vue:17:13)
    at _sfc_main.setup (/sandbox/app.vue:119:23)
    at callWithErrorHandling (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
    at setupStatefulComponent (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7176:29)
    at setupComponent (/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7131:11)
    at renderComponentVNode (/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)
    at Module.ssrRenderComponent (/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:624:12)
    at default (/sandbox/node_modules/nuxt/dist/app/components/nuxt-root.vue:54:37)
    at Module.ssrRenderSuspense (/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:966:9)
    at _sfc_ssrRender (/sandbox/node_modules/nuxt/dist/app/components/nuxt-root.vue:49:25)
```

**Comment by mxttwoods** [comment]
Would enjoy fixing this if someone can give some direction on requirements or desired behavior.

**Comment by mxttwoods** [comment]
I think the issue was created w this commit `43eb93fe7b6160e5a5b6e8ee391db9fe12c134db`

maybe we should add `examples/auto-imports/composables/composables/nested/bar.ts` ?

https://github.com/nuxt/nuxt/pull/19249/commits/43eb93fe7b6160e5a5b6e8ee391db9fe12c134db

**Comment by danielroe** [comment]
My guess is that the lockfile in the sandboxes needs to be updated to include the latest version of `unimport`, where this feature landed.

**Comment by mxttwoods** [comment]
Will read the docs and get started on pr. thanks!

**Comment by mxttwoods** [comment]
@danielroe I think this corrects the issue. Let me know what you think.
