### ISSUE TITLE
Completely broken with pnpm

### ISSUE THREAD

**Issue by brawaru** [nuxt/nuxt#19588]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.2.3`
- Package Manager:  `pnpm@7.13.6`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Bootstrap your project using `pnpx nuxi@latest init my-app`
2. Go to `my-app`, remove `node_modules` and npm lock file — `package-lock.json`
3. Create `.npmrc`:
    ```ini
   shamefully-hoist=true
   strict-peer-dependencies=false
    ```
4. Install dependencies via `pnpm i`
5. Wait until it installs all dependencies runs `postinstall`

**StackBlitz**: https://stackblitz.com/edit/github-xiqyev?file=README.md

### Describe the bug

Nuxt won't launch:

```
> @ postinstall /home/projects/github-xiqyev
> nuxt prepare

Nuxi 3.2.3

 ERROR  First argument must be a non-empty string.

  at serialTaskCaller (file://node_modules/.pnpm/hookable@5.5.0/node_modules/hookable/dist/index.mjs:65:16)
  at Hookable.callHookWith (file://node_modules/.pnpm/hookable@5.5.0/node_modules/hookable/dist/index.mjs:214:20)
  at Hookable.callHook (file://node_modules/.pnpm/hookable@5.5.0/node_modules/hookable/dist/index.mjs:204:17)
  at initNuxt (file://node_modules/.pnpm/nuxt@3.2.3/node_modules/nuxt/dist/index.mjs:2211:14)
  at Object.ready (file://node_modules/.pnpm/nuxt@3.2.3/node_modules/nuxt/dist/index.mjs:2150:18)
  at loadNuxt (file://node_modules/.pnpm/nuxt@3.2.3/node_modules/nuxt/dist/index.mjs:2306:16)
  at async loadNuxt (file://node_modules/.pnpm/@nuxt+kit@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:596:19)
  at async Object.invoke (file://node_modules/.pnpm/nuxi@3.2.3/node_modules/nuxi/dist/chunks/prepare.mjs:45:18)
  at async _main (file://node_modules/.pnpm/nuxi@3.2.3/node_modules/nuxi/dist/cli.mjs:65:20)

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by plcdnl** [comment]
#19585

**Comment by danielroe** [comment]
let's track there
