### ISSUE TITLE
Could not load E:/\u79C1\u5355/xxx/pages/car/screening/index.vue?macro=true&vue&type=script&setup=true&lang.ts (imported by pages/car/screening/index.vue?macro=true): ENOENT: no such file or directory, open 'E:/\u79C1\u5355/xxx/pages/car/screening/index.vue'

### ISSUE THREAD

**Issue by evanlong0926** [nuxt/nuxt#19678]
[vite:vue] Could not load E:/\u79C1\u5355/rvtimes_nuxt3_h5/pages/car/screening/index.vue?macro=true&vue&type=script&setup=true&lang.ts (imported by pages/car/screening/index.vue?macro=true): ENOENT: no such file or directory, open 'E:/\u79C1\u5355/rvtimes_nuxt3_h5/pages/car/screening/index.vue'

 ERROR  Could not load E:/\u79C1\u5355/rvtimes_nuxt3_h5/pages/car/screening/index.vue?macro=true&vue&type=script&setup=true&lang.ts (imported by pages/car/screening/index.vue?macro=true): ENOENT: no such file or directory, open 'E:/\u79C1\u5355/rvtimes_nuxt3_h5/pages/car/screening/index.vue'

  at Object.openSync (node:fs:594:3)
  at Object.readFileSync (node:fs:462:35)
  at getDescriptor (/E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/@vitejs+plugin-vue@4.0.0_vite@4.1.4+vue@3.2.47/node_modules/@vitejs/plugin-vue/dist/index.mjs:86:10)
  at Object.load (/E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/@vitejs+plugin-vue@4.0.0_vite@4.1.4+vue@3.2.47/node_modules/@vitejs/plugin-vue/dist/index.mjs:2663:28)
  at /E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:24343:40
  at async PluginDriver.hookFirstAndGetPlugin (/E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:24243:28)
  at async /E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:23531:75
  at async Queue.work (/E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:24453:32)

**Comment by TracyG7** [comment]
i have this problem too . Did you solve it?
