### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by evanlong0926** [nuxt/nuxt#19679]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.2.3`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.19.0`
- Builder:          `vite`
- User Config:      `experimental`, `app`, `nitro`, `build`, `css`, `modules`, `runtimeConfig`, `typescript`, `vite`, `imports`, `sourcemap`, `postcss`
- Runtime Modules:  `@vueuse/nuxt@9.13.0`, `nuxt-windicss@2.6.0`, `@pinia/nuxt@0.4.7`, `@vant/nuxt@1.0.0-beta.0`
- Build Modules:    `-`

### Reproduction

Error every time `pnpm build` is executed, But I don't know what the problem is, I hope to get your tips, please ~

### Describe the bug

ENOENT: no such file or directory

### Logs

```shell-script
[vite:vue] Could not load E:/\u79C1\u5355/rvtimes_nuxt3_h5/pages/car/screening/index.vue?macro=true&vue&type=script&setup=true&lang.ts (imported by pages/car/screening/index.vue?macro=true): ENOENT: no such file or directory, open 'E:/\u79C1\u5355/rvtimes_nuxt3_h5/pages/car/screening/index.vue'

 ERROR  Could not load E:/\u79C1\u5355/rvtimes_nuxt3_h5/pages/car/screening/index.vue?macro=true&vue&type=script&setup=true&lang.ts (imported by pages/car/screening/index.vue?macro=true): ENOENT: no such file or directory, open 'E:/\u79C1\u5355/rvtimes_nuxt3_h5/pages/car/screening/index.vue'

  at Object.openSync (node:fs:594:3)
  at Object.readFileSync (node:fs:462:35)
  at getDescriptor (/E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/@vitejs+plugin-vue@4.0.0_vite@4.1.4+vue@3.2.47/node_modules/@vitejs/plugin-vue/dist/index.mjs:86:10)
  at Object.load (/E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/@vitejs+plugin-vue@4.0.0_vite@4.1.4+vue@3.2.47/node_modules/@vitejs/plugin-vue/dist/index.mjs:2663:28)
  at /E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:24343:40
  at async PluginDriver.hookFirstAndGetPlugin (/E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:24243:28)
  at async /E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:23531:75
  at async Queue.work (/E:/%E7%A7%81%E5%8D%95/rvtimes_nuxt3_h5/node_modules/.pnpm/rollup@3.19.1/node_modules/rollup/dist/es/shared/node-entry.js:24453:32)
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by evanlong0926** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

It works fine in my development environment, but when I execute `pnpm build` it tells me `ENOENT: no such file or directory`, so I can't find the root cause of the problem, so I can't provide it.😢

**Comment by danielroe** [comment]
Can you create a minimal project that has the same issue and then upload it to GitHub? What is your directory path? For what it's worth, it looks like the issue here is coming from vite or possibly rollup rather than Nuxt.

**Comment by danielroe** [comment]
Thanks! If you could comment as well then I will check again when you update.

**Comment by ExEr7um** [comment]
I think it's because non-ascii characters and `script setup lang="ts"` in pages file.

Here is the same issue with reproduction: #15113.

**Comment by evanlong0926** [comment]
> I think it's because non-ascii characters and `script setup lang="ts"` in pages file.
> 
> Here is the same issue with reproduction: #15113.

Yes, I did. This is the problem. Because my path contains Chinese, I was prompted that I could not find the file during packaging. Thank you very much for reminding me 😊

**Comment by icai** [comment]
I also found this issue

filename: server/core/pay/alipay.ts
```
const __filename = fileURLToPath(import.meta.url)


const __dirname = path.dirname(__filename);



const config = {
  privateKey: fs.readFileSync(path.join(__dirname, '../../', 'server/config/payment/alipay/private-key.pem'), 'ascii'),
  alipayPublicKey: fs.readFileSync(path.join(__dirname, '../../', 'server/config/payment/alipay/public-key.pem'), 'ascii'),
}

export const alipaySdk = new AlipaySdk({
  appId: '2016102300745867',
  // privateKey: fs.readFileSync(path.join(__dirname, '../../', 'config/payment/alipay/private-key.pem'), 'ascii'),
  // alipayPublicKey: fs.readFileSync(path.join(__dirname, '../../', 'config/payment/alipay/public-key.pem'), 'ascii'),
  gateway: 'https://openapi.alipaydev.com/gateway.do',
  ...config
})
```

filename: nuxt.config.ts

```
export default defineNuxtConfig({
  rootDir: __dirname,
  srcDir: "client",
  serverDir: "server",
})
```


build output:

filename: .output/server/chunks/nitro/node-server.mjs

```
var alipayExports = alipay.exports;
const AlipaySdk = /*@__PURE__*/getDefaultExportFromCjs(alipayExports);

const __filename = fileURLToPath$1(globalThis._importMeta_.url);
const __dirname$1 = path$1.dirname(__filename);
const config = {
  privateKey: fs__default.readFileSync(path$1.join(__dirname$1, "../../", "config/payment/alipay/private-key.pem"), "ascii"),
  alipayPublicKey: fs__default.readFileSync(path$1.join(__dirname$1, "../../", "config/payment/alipay/public-key.pem"), "ascii")
};
const alipaySdk = new AlipaySdk({
  appId: "2016102300745867",
  // privateKey: fs.readFileSync(path.join(__dirname, '../../', 'config/payment/alipay/private-key.pem'), 'ascii'),
  // alipayPublicKey: fs.readFileSync(path.join(__dirname, '../../', 'config/payment/alipay/public-key.pem'), 'ascii'),
  gateway: "https://openapi.alipaydev.com/gateway.do",
  ...config
});
```

@danielroe

**Comment by danielroe** [comment]
@icai Would you open a new issue with a reproduction? 🙏

**Comment by icai** [comment]
@danielroe  just like this issue https://github.com/nuxt/nuxt/issues/14884

**Comment by danielroe** [comment]
I think that's a problem with your code. Instead you can use `useStorage` and nitro bundled storage to access the fs in a reliable way.

**Comment by icai** [comment]
@danielroe 
 demo for https://www.npmjs.com/package/alipay-sdk
```

import AlipaySdk from 'alipay-sdk';

const alipaySdk = new AlipaySdk({
  appId: '2016123456789012',
  // keyType: 'PKCS1', 
  privateKey: fs.readFileSync('private-key.pem', 'ascii'),
  alipayPublicKey: fs.readFileSync('alipay-public-key.pem', 'ascii'),
});
```

the shortening issue, just for ```fs.readFileSync('private-key.pem', 'ascii')```

the question to be how to use ```fs.readFileSync```

**Comment by icai** [comment]
some stackoverflow questions about this issue 

https://stackoverflow.com/questions/76453100/how-to-read-txt-file-in-nuxt-3-in-a-folder
https://stackoverflow.com/questions/75874301/how-to-store-and-access-user-uploaded-files-inside-a-nuxt-3-app
@danielroe

**Comment by mofyart** [comment]
Hello everyone, I have problem with set date for post. Can you help me, please

''
error while updating dependencies:
Error: ENOENT: no such file or directory, open '/home/adduser/socialmedia/node_modules/.pnpm/@tanstack+react-query@4.36.1_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@tanstack/react-query/build/lib/index.mjs'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async extractExportsData (file:///home/adduser/socialmedia/node_modules/.pnpm/vite@6.0.11_@types+node@22.10.7_sass@1.83.4_yaml@2.7.0/node_modules/vite/dist/node/chunks/dep-M1IYMR16.js:19213:24)
    at async file:///home/adduser/socialmedia/node_modules/.pnpm/vite@6.0.11_@types+node@22.10.7_sass@1.83.4_yaml@2.7.0/node_modules/vite/dist/node/chunks/dep-M1IYMR16.js:18959:27
    at async Promise.all (index 4)
    at async prepareEsbuildOptimizerRun [(file:///home/adduser/socialmedia/node_modules/.pnpm/vite@6.0.11_@types+node@22.10.7_sass@1.83.4_yaml@2.7.0/node_modules/vite/dist/node/chunks/dep-M1IYMR16.js:18956:3)]()

''
