### ISSUE TITLE
ERROR  Nuxt module should be a function: [object Object]

### ISSUE THREAD

**Issue by videmann** [nuxt/nuxt#19681]
### Environment

> postinstall
> nuxt prepare

Nuxi 3.3.1                                                                                                                                                                                                18:05:19

 ERROR  Nuxt module should be a function: [object Object]                                                                                                                                                 18:05:22

  at normalizeModule (/C:/Users/videmanso/projects/lrp-front/node_modules/@nuxt/kit/dist/index.mjs:478:11)
  at installModule (/C:/Users/videmanso/projects/lrp-front/node_modules/@nuxt/kit/dist/index.mjs:450:47)
  at initNuxt (/C:/Users/videmanso/projects/lrp-front/node_modules/nuxt/dist/index.mjs:2469:13)
  at async loadNuxt (/C:/Users/videmanso/projects/lrp-front/node_modules/nuxt/dist/index.mjs:2523:5)
  at async loadNuxt (/C:/Users/videmanso/projects/lrp-front/node_modules/@nuxt/kit/dist/index.mjs:539:19)
  at async Object.invoke (/C:/Users/videmanso/projects/lrp-front/node_modules/nuxi/dist/chunks/prepare.mjs:37:18)
  at async _main (/C:/Users/videmanso/projects/lrp-front/node_modules/nuxi/dist/cli.mjs:49:20)

npm ERR! code 1
npm ERR! path C:\Users\videmanso\projects\lrp-front
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c nuxt prepare

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\videmanso\AppData\Local\npm-cache\_logs\2023-03-14T15_04_14_785Z-debug-0.log

### Reproduction

no

### Describe the bug

app crashed after update to nuxt 3.3.1

### Logs

```shell-script
6453 timing command:i Completed in 68137ms
6454 verbose stack Error: command failed
6454 verbose stack     at ChildProcess.<anonymous> (C:\Users\videmanso\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
6454 verbose stack     at ChildProcess.emit (node:events:520:28)
6454 verbose stack     at maybeClose (node:internal/child_process:1092:16)
6454 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
6455 verbose cwd C:\Users\videmanso\projects\lrp-front
6456 verbose Windows_NT 10.0.19044
6457 verbose node v16.14.0
6458 verbose npm  v9.4.2
6459 error code 1
6460 error path C:\Users\videmanso\projects\lrp-front
6461 error command failed
6462 error command C:\Windows\system32\cmd.exe /d /s /c nuxt prepare
6463 verbose exit 1
6464 timing npm Completed in 68170ms
6465 verbose code 1
6466 error A complete log of this run can be found in:
6466 error     C:\Users\videmanso\AppData\Local\npm-cache\_logs\2023-03-14T15_04_14_785Z-debug-0.log
```

**Comment by danielroe** [comment]
I would guess you have a file in your `~/modules` directory that does not export a Nuxt module. This was a new feature in v3.3 (auto-scanning). You can change the auto-scanned folder with `dir.modules`.

**Comment by videmann** [comment]
> I would guess you have a file in your `~/modules` directory that does not export a Nuxt module. This was a new feature in v3.3 (auto-scanning). You can change the auto-scanned folder with `dir.modules`.

Thanks a lot!!!
