### ISSUE TITLE
nuxtApp._useHead is not a function

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#19693]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.14.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.3.1`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `tailwindcss`, `vite`, `nitro`, `schemaOrg`, `telemetry`, `algolia`, `head`, `auth`, `viewport`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/algolia@1.5.0`, `@nuxtjs/tailwindcss@6.6.0`, `formidable@2.1.1`, `nuxt-viewport@2.0.3`, `@nuxtjs/partytown@1.3.0`, `@vueuse/nuxt@9.13.0`, `nuxt-schema-org@1.1.0-beta.6`, `nuxt-icon@0.1.8`, `@pinia/nuxt@0.4.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`

### Reproduction

I upgrade Nuxt to version 3.3.1 and when i start the app, throws an error

![image](https://user-images.githubusercontent.com/77386602/225254306-3a9cddab-dd08-4715-9247-e59279f865ab.png)

### Describe the bug

I upgrade Nuxt to version 3.3.1 and when i start the app, throws an error

![image](https://user-images.githubusercontent.com/77386602/225254306-3a9cddab-dd08-4715-9247-e59279f865ab.png)

[nuxt] [request error] [unhandled] [500] nuxtApp._useHead is not a function
  at Object.updateHead (./node_modules/nuxt-schema-org/dist/runtime/plugin.mjs:15:15)  
  at Object.setupDOM (./node_modules/@vueuse/schema-org/dist/index.mjs:69:22)  
  at Object.forceRefresh (./node_modules/@vueuse/schema-org/dist/index.mjs:60:20)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./node_modules/nuxt-schema-org/dist/runtime/plugin.mjs:49:90  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:53:16)  
  at async applyPlugin (./node_modules/nuxt/dist/app/nuxt.js:113:23)  
  at async Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.js:123:5)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.js:29:7)  
  at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] nuxtApp._useHead is not a function
  at Object.updateHead (./node_modules/nuxt-schema-org/dist/runtime/plugin.mjs:15:15)  
  at Object.setupDOM (./node_modules/@vueuse/schema-org/dist/index.mjs:69:22)  
  at Object.forceRefresh (./node_modules/@vueuse/schema-org/dist/index.mjs:60:20)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./node_modules/nuxt-schema-org/dist/runtime/plugin.mjs:49:90  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:53:16)  
  at async applyPlugin (./node_modules/nuxt/dist/app/nuxt.js:113:23)  
  at async Module.applyPlugins (./node_modules/nuxt/dist/app/nuxt.js:123:5)  
  at async createNuxtAppServer (./node_modules/nuxt/dist/app/entry.js:29:7)  
  at async default (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
```

**Comment by agracia-foticos** [comment]
![image](https://user-images.githubusercontent.com/77386602/225269707-52bc9be8-95a4-41a0-bc6f-3b63eefa37da.png)

I upgrade nuxt-schema-org and runs
