### ISSUE TITLE
Unable to build a project with TailwindCSS

### ISSUE THREAD

**Issue by k3z** [nuxt/nuxt#19761]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `pnpm@7.29.1`
- Builder:          `vite`
- User Config:      `app`, `runtimeConfig`, `modules`, `fontLoader`, `css`, `postcss`, `build`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `nuxt-icon@0.2.11`, `@vueuse/motion/nuxt@2.0.0-beta.25`
- Build Modules:    `-`
------------------------------

### Reproduction

 pnpm run build

### Describe the bug

Build ends with error

### Additional context

Source code that seems to cause the error. But if I remove the line. Another similar error occurs.

```<span
            :class="[
              'lg:text-2xl',
              'font-medium',
              'group-hover:before:scale-x-100',
              'group-hover:before:origin-left',
              'relative',
              'before:transition-transform',
              'before:duration-300',
              'before:scale-x-0',
              uderlineEffect,
              {
                uderlineEffect:
                  item.to.length > 1 && $route.path.startsWith(item.to) == true,
                'before:scale-x-100':
                  item.to.length > 1 && $route.path.startsWith(item.to) == true,
              },
            ]"
          >
            {{ item.label }}
          </span>
          ```

### Logs

```shell-script
> @ build /Users/olivierk3z/projects/blast/extranet-next
> nuxt build

Nuxi 3.3.1                                                                                                                                                                              09:59:40
Nuxt 3.3.1 with Nitro 2.3.1                                                                                                                                                             09:59:40
ℹ Building client...                                                                                                                                                                    09:59:41
ℹ vite v4.1.4 building for production...                                                                                                                                                09:59:41
ℹ ✓ 221 modules transformed.                                                                                                                                                            09:59:42
rendering chunks (13)...
 ERROR  [vite:css-post] [esbuild css minify] Transform failed with 1 error:                                                                                                             09:59:42
<stdin>:1:23179: ERROR: Unterminated string token

✘ [ERROR] Unterminated string token

    <stdin>:1:23179:
      1 │ ...padding-top:1rem}.lg\:text-2xl{font-size:1.5rem;line-height:2rem}}
        ╵                                                                      ^




 ERROR  [esbuild css minify] Transform failed with 1 error:                                                                                                                             09:59:42
<stdin>:1:23179: ERROR: Unterminated string token

  <stdin>:1:23179: ERROR: Unterminated string token
  at failureErrorWithLog (node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:1604:15)
  at node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:837:29
  at responseCallbacks.<computed> (node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:701:9)
  at handleIncomingPacket (node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:756:9)
  at Socket.readFromStdout (node_modules/.pnpm/esbuild@0.16.17/node_modules/esbuild/lib/main.js:677:7)
  at Socket.emit (node:events:513:28)
  at Socket.emit (node:domain:489:12)
  at addChunk (node:internal/streams/readable:324:12)
  at readableAddChunk (node:internal/streams/readable:297:9)
  at Readable.push (node:internal/streams/readable:234:10)

 ELIFECYCLE  Command failed with exit code 1.
(base) ➜  extranet-next git:(develop) ✗
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by k3z** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

OK, not simple. I experience this bug in all my recents big projets created with my own scaffolding, this is most certainly the problem. I try with a more atomic nuxt projet.

**Comment by k3z** [comment]
It was a typo in the fontFamily tailwind config section
Missing semicolon for a font name.
Sorry for the inconvenience.
My Issue is irrelevant and has nothing to do with Nuxt.

It's a real pleasure to code frontends, backends with Nuxt3. Thanks to all team members and contributors.
