### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'postcss') at Processor.normalize

### ISSUE THREAD

**Issue by gkatsanos** [nuxt/nuxt#19771]
### Environment

``` 

  System:
    OS: macOS 12.6.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 126.39 MB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.2
  npmPackages:
    @nuxt/image: ^0.7.1 => 0.7.1 
    nuxt: ^2.16.1 => 2.16.2 
```

### Reproduction

I apologise for not providing a minimal reproduction... Issue depends on two private repos.
I created a tailwindcss plugin that I import in my nuxt app as an npm dependency.
The issue seems to be related to a webpack postcss-loader configuration. 

### Describe the bug

```
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js): TypeError: Cannot read properties of undefined (reading 'postcss') at Processor.normalize (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/postcss/lib/processor.js:35:13) at new Processor (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/postcss/lib/processor.js:11:25) at postcss (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/postcss/lib/postcss.js:26:10) at Object.module.exports [as sync] (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/postcss-js/sync.js:7:19) at /Users/gkatsanos/repos/visable/explore-frontend/node_modules/@visable-dev/ui-components/src/index.js:7:32 at registerPlugins (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:777:61) at createContext (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1160:5) at getContext (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1217:20) at /Users/gkatsanos/repos/visable/explore-frontend/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:115:81 at /Users/gkatsanos/repos/visable/explore-frontend/node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11 at plugins (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/tailwindcss/lib/plugin.js:38:63) at LazyResult.runOnRoot (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:339:16) at LazyResult.runAsync (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:393:26) at async Object.loader (/Users/gkatsanos/repos/visable/explore-frontend/node_modules/postcss-loader/dist/index.js:95:14)
```

### Additional context

Here are the dependencies of the tailwind plugin I am trying to import:
```
 "devDependencies": {
    "@types/css-selector-tokenizer": "^0.7.1",
    "husky": "^8.0.3",
    "postcss": "^8.1.6",
    "postcss-cli": "8.3.0",
    "postcss-import": "13.0.0",
    "postcss-nested": "5.0.1",
    "prejss-cli": "0.3.3",
    "prettier": "^2.7.1",
    "pretty-quick": "^3.1.3",
    "vite": "^4.1.4"
  },
  "dependencies": {
    "@visable-dev/wlw-tailwindcss-config": "^3.0.5",
    "autoprefixer": "^10.4.14",
    "css-selector-tokenizer": "^0.8.0",
    "postcss-js": "^4.0.0",
    "tailwindcss": "^3"
  },
```
And its' post css config:
```js
module.exports = {
  plugins: {
    "tailwindcss/nesting": {},
    tailwindcss: {},
    autoprefixer: {},
  },
};
```

Here are the deps of the nuxt application:
```js
"dependencies": {
    "@koumoul/nuxt-config-inject": "^0.4.10",
    "@nuxt/image": "^0.7.1",
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/device": "^2.1.0",
    "@nuxtjs/proxy": "^2.1.0",
    "@nuxtjs/robots": "^2.5.0",
    "@nuxtjs/router": "^1.6.1",
    "@nuxtjs/style-resources": "^1.2.0",
    "@nuxtjs/svg": "^0.4.0",
    "@nuxtjs/tailwindcss": "^6.0.0",
    "@tailwindcss/line-clamp": "^0.4.2",
    "@visable-dev/ab-testing": "^4.0.4",
    "@visable-dev/favourites": "^1.9.3",
    "@visable-dev/fontsources": "^0.5.0",
    "@visable-dev/quick-connect": "^1.1.4",
    "@visable-dev/routing": "^7.0.0",
    "@visable-dev/styleguide": "^35.13.1",
    "@visable-dev/tracking": "^3.0.0",
    "@visable-dev/ui-components": "^0.5.1",
    "@visable-dev/vue": "14.7.2-alpha.0",
    "@visable-dev/wlw-tailwindcss-config": "^3.0.5",
    "await-to-js": "^3.0.0",
    "consola": "^2.15.3",
    "cookie-universal-nuxt": "^2.1.5",
    "core-js": "^3.25.5",
    "css-loader": "^6.7.1",
    "dd-trace": "^2.18.0",
    "imgix.js": "^3.6.1",
    "insane": "^2.6.2",
    "nuxt": "^2.16.1",
    "nuxt-breakpoints": "^1.1.9",
    "nuxt-user-agent": "^1.2.2",
    "portal-vue": "^2.1.7",
    "sass": "1.32.4",
    "sass-loader": "~10.1.1",
    "v-tooltip": "^2.1.3",
    "vee-validate": "^3.4.13",
    "vue-clipboard2": "^0.3.3",
    "vue-i18n": "~8.27.1",
    "vue-lazy-hydration": "^2.0.0-beta.4",
    "vue-popperjs": "^2.3.0",
    "vue-slick-carousel": "^1.0.6",
    "vuejs-paginate": "^2.1.0",
    "weighted-random": "^0.1.0"
  },
  "devDependencies": {
    "@applitools/eyes-cypress": "^3.27.2",
    "@babel/core": "^7.19.3",
    "@babel/eslint-parser": "^7.19.1",
    "@babel/preset-env": "^7.19.3",
    "@babel/runtime-corejs3": "^7.19.4",
    "@cypress/vue": "^4.2.1",
    "@size-limit/preset-app": "^8.1.0",
    "@size-limit/webpack": "^8.1.0",
    "@size-limit/webpack-why": "^8.1.0",
    "@vue/cli-plugin-eslint": "~5.0.8",
    "@vue/cli-service": "~4.5.19",
    "@vue/eslint-config-airbnb": "~5.3.0",
    "@vue/test-utils": "^1.3.0",
    "@vue/vue2-jest": "^28.0.1",
    "babel-jest": "^28.1.3",
    "cypress": "^10.9.0",
    "eslint": "~8.22.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-html": "^7.1.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-vue": "^8.7.1",
    "git-branch-is": "^4.0.0",
    "husky": "^8.0.1",
    "jest": "^28.1.3",
    "jest-environment-jsdom": "^28.1.3",
    "jest-jasmine2": "^28.1.3",
    "jest-serializer-vue": "^2.0.2",
    "jest-transform-stub": "^2.0.0",
    "jsdom": "^20.0.1",
    "prettier": "^2.7.1",
    "pretty-quick": "^3.1.3",
    "size-limit": "^8.1.0",
    "vuex-mock-store": "^0.0.8"
  },
```

**Comment by danielroe** [comment]
Would you try using `nuxt-edge`? We just landed a feature that I hope might resolve this.

**Comment by gkatsanos** [comment]
How do I get to nuxt-edge on 2.x ?

**Comment by gkatsanos** [comment]
@danielroe same issue with     "nuxt-edge": "^2.16.3-27983541.093e1b1",
as the library is mine/under my control, could you advise on which dependency I can downgrade as a workaround? this is an internal CSS UI library project, dont think we need all the latest bells and whistles from postcss

**Comment by gkatsanos** [comment]
what's weird is my tailwind plugin is just serving pre-compiled css so I'm not sure why postcss is needed at all for nuxt

**Comment by danielroe** [comment]
Does this reproduce without your library?

**Comment by gkatsanos** [comment]
And I was able to fix it as well (with the help of the reproduction..) unfortunately the poor documentation of https://github.com/postcss/postcss-js#syncplugins-function confused me, one needs to pass an empty array even when there's no plugins.. (****y API)

**Comment by danielroe** [comment]
Great work!
