### ISSUE TITLE
Cannot find module 'node-fetch-native' from '/app'

### ISSUE THREAD

**Issue by buglavecz** [nuxt/nuxt#19820]
### Environment

 System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 3.15 GB / 15.87 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.44)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    nuxt: ^2 => 2.16.3

### Reproduction

After I builded the project as production mode with `--standalone` flag. 

### Describe the bug

I got this error on first page loading:

```
 ERROR  Cannot find module 'node-fetch-native' from '/app'                                                                                                                                                                                                      12:29:25

  at Function.resolveSync [as sync] (node_modules/resolve/lib/sync.js:111:15)
  at node_modules/vue-server-renderer/build.prod.js:1:76676
  at Object.<anonymous> (webpack:/external "node-fetch-native":1:0)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Module.<anonymous> (server.js:37850:35)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at Object.<anonymous> (server.js:31314:18)
  at __webpack_require__ (webpack/bootstrap:25:0)
  at server.js:118:18
  at Object.<anonymous> (server.js:121:10)
  at o (node_modules/vue-server-renderer/build.prod.js:1:76584)
  at node_modules/vue-server-renderer/build.prod.js:1:77223
  at new Promise (<anonymous>)
  at node_modules/vue-server-renderer/build.prod.js:1:77136
  at Object.renderToString (node_modules/vue-server-renderer/build.prod.js:1:80334)
  at SSRRenderer.render (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:353:38)
```

**Comment by buglavecz** [comment]
I added in my docker file manually `node-fetch-native`.
```
RUN yarn add nuxt-start@2.15.8 @nuxtjs/sentry@^6.0.1 node-fetch-native
```

Working fine.
