### ISSUE TITLE
RollupError in vite 4 (nuxt 3.2.3+) and vuetify

### ISSUE THREAD

**Issue by rekryt** [nuxt/nuxt#19850]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `typescript`, `app`, `css`, `modules`, `build`, `vite`
- Runtime Modules:  `@pinia/nuxt@0.4.7`, `@kevinmarrec/nuxt-pwa@0.11.1`
- Build Modules:    `-`
------------------------------

### Reproduction

[Reproduction](https://codesandbox.io/p/github/nuxt/starter/csb-2twsl5/draft/zen-bartik?file=%2Fnuxt.config.ts&selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A6%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl7rh39as0003lngt67wg399j%2522%252C%2522openFiles%2522%253A%255B%2522%252Fpackage.json%2522%252C%2522%252Fnuxt.config.ts%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfisk5p6027j356kiw6gw1b7%2522%253A%257B%2522devtools%2522%253A%255B%255D%252C%2522key%2522%253A%2522clfisk5p6027j356kiw6gw1b7%2522%252C%2522name%2522%253A%2522Terminal%2522%257D%252C%2522clfit1u9m0613356kmdtimru8%2522%253A%257B%2522key%2522%253A%2522clfit1u9m0613356kmdtimru8%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clfit6mdz00su356kcdkz3wit%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clfit6k2z00nk356k3n2ofyg6%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%252C%2522name%2522%253A%2522build%2522%257D%257D%252C%2522currentSpace%2522%253A%2522clfit1u9m0613356kmdtimru8%2522%252C%2522spacesOrder%2522%253A%255B%2522clfisk5p6027j356kiw6gw1b7%2522%252C%2522clfit1u9m0613356kmdtimru8%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

nuxt.config.ts
```
export default defineNuxtConfig({
  css: ["vuetify/lib/styles/main.sass"],
  build: {
    transpile: ["vuetify"],
  },
});
```

plugins/vuetify.ts
```
import { createVuetify } from 'vuetify';
import * as components from 'vuetify/components';
import * as directives from 'vuetify/directives';

import { VDataTable } from 'vuetify/labs/VDataTable';

export default defineNuxtPlugin((nuxtApp) => {
    const cookieTheme = useCookieTheme();

    const vuetify = createVuetify({
        components: {
            ...components,
            VDataTable,
        },
        directives,
        theme: {
            defaultTheme: cookieTheme.value && cookieTheme.value !== 'system' ? cookieTheme.value : 'light',
            themes: {
                light: {
                    dark: false,
                    colors: {
                        primary: '#4caf50',
                        secondary: '#4caf50',
                        background: '#FFFFFF',
                        surface: '#FFFFFF',
                        'primary-darken-1': '#3700B3',
                        'secondary-darken-1': '#018786',
                        error: '#f55a4e',
                        info: '#00d3ee',
                        success: '#5cb860',
                        warning: '#ffa21a',
                    },
                },
            },
        },
    });

    nuxtApp.vueApp.use(vuetify);
});
```

### Describe the bug

Vuetify ^3.1 + Nuxt 3.2.3, 3.3.1 build failed

![image](https://user-images.githubusercontent.com/181338/226754237-77a5b48b-3b60-444a-88e5-fef84b03078c.png)

### Additional context

This temporary fix this issue (not works with nuxt@3.3.1)
```
npm i -D nuxt@3.2.3 @nuxt/kit@3.0.0 @nuxt/vite-builder@3.0.0
```

### Logs

```shell-script
√ Server built in 11703ms                                                                                                                                                                                00:39:13  
√ Generated public .output/public                                                                                                                                                                  nitro 00:39:13  
i Building Nitro Server (preset: node-server)                                                                                                                                                      nitro 00:39:13  

 ERROR  RollupError: Could not resolve "./_nuxt/VContainer-styles.a03b508f.mjs" from ".nuxt/dist/server/styles.mjs"                                                                                nitro 00:39:25


undefined


 ERROR  Could not resolve "./_nuxt/VContainer-styles.a03b508f.mjs" from ".nuxt/dist/server/styles.mjs"                                                                                                   00:39:25  

  at error (/C:/Users/.../IdeaProjects/nuxt3-vuetify3-dashboard/node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
  at ModuleLoader.handleInvalidResolvedId (/C:/Users/.../IdeaProjects/nuxt3-vuetify3-dashboard/node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:23776:24)
  at ModuleLoader.resolveDynamicImport (/C:/Users/.../IdeaProjects/nuxt3-vuetify3-dashboard/node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:23834:58)
  at async /C:/Users/.../IdeaProjects/nuxt3-vuetify3-dashboard/node_modules/nitropack/node_modules/rollup/dist/es/shared/node-entry.js:23723:32
```

**Comment by danielroe** [comment]
You might also try setting `experimental.inlineSSRStyles` to `false` as a workaround.

**Comment by rekryt** [comment]
> experimental.inlineSSRStyles

this helps at 3.3.1, thx

**Comment by Rrrally** [comment]
Had the same problem since Monday afternoon. Now it works again. Thanks! Thanks! Thanks!

**Comment by piqjen-1xofFi-sikxyh** [comment]
Was this fixed

**Comment by danielroe** [comment]
The reproduction link doesn't seem to reproduce your issue, and vite is now v5.

If you're still experiencing this, please do provide a reproduction, and I'll happily look into it. 🙏
