### ISSUE TITLE
Nuxt Layers: Cannot find module '@nuxt/kit'

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#19852]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/warflash/nuxt-layers-base

https://github.com/warflash/nuxt-layers-parent

### Describe the bug

I'm trying to follow the docs here: https://nuxt.com/docs/guide/going-further/layers#relative-paths-and-aliases on how to import css in the base nuxt layer. When deploying the app that extends that layer to production it fails throwing `[error] Cannot find module '@nuxt/kit'`. 

### Additional context

I tried specifically installing nuxtkit as a dependency in both the base and parent repo but that didn't seem to help unfortunately

### Logs

```shell-script
[03:56:22.663] Running build in Washington, D.C., USA (East) – iad1
[03:56:22.715] Cloning github.com/warflash/nuxt-layers-parent (Branch: main, Commit: de720c0)
[03:56:22.917] Cloning completed: 202.097ms
[03:56:23.013] Previous build cache not available
[03:56:23.064] Running "vercel build"
[03:56:23.506] Vercel CLI 28.17.0
[03:56:24.074] Installing dependencies...
[03:56:27.455] npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[03:56:27.502] npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[03:56:31.215] 
[03:56:31.215] > postinstall
[03:56:31.215] > nuxt prepare
[03:56:31.216] 
[03:56:31.304] [log] Nuxi 3.3.1
[03:56:32.443] [error] Cannot find module '@nuxt/kit'
[03:56:32.443] Require stack:
[03:56:32.443] - /vercel/.cache/c12/github_warflash_nuxt-layers-base/nuxt.config.ts
[03:56:32.443]   Require stack:
[03:56:32.443]   - /vercel/.cache/c12/github_warflash_nuxt-layers-base/nuxt.config.ts
[03:56:32.443]   at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
[03:56:32.443]   at Function.resolve (node:internal/modules/cjs/helpers:109:19)
[03:56:32.443]   at _resolve (node_modules/jiti/dist/jiti.js:1:241025)
[03:56:32.444]   at jiti (node_modules/jiti/dist/jiti.js:1:243309)
[03:56:32.444]   at /vercel/.cache/c12/github_warflash_nuxt-layers-base/nuxt.config.ts:1:174
[03:56:32.444]   at Object.jiti (node_modules/jiti/dist/jiti.js:1:245784)
[03:56:32.444]   at resolveConfig (node_modules/c12/dist/index.mjs:271:24)
[03:56:32.444]   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[03:56:32.444]   at async extendConfig (node_modules/c12/dist/index.mjs:214:21)
[03:56:32.444]   at async loadConfig (node_modules/c12/dist/index.mjs:156:5)
[03:56:32.444]   at async loadNuxtConfig (node_modules/@nuxt/kit/dist/index.mjs:485:18)
[03:56:32.444]   at async loadNuxt (node_modules/nuxt/dist/index.mjs:2500:19)
[03:56:32.444]   at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:539:19)
[03:56:32.444]   at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:37:18)
[03:56:32.444]   at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
[03:56:32.457] npm ERR! code 1
[03:56:32.457] npm ERR! path /vercel/path0
[03:56:32.458] npm ERR! command failed
[03:56:32.458] npm ERR! command sh -c -- nuxt prepare
[03:56:32.459] 
[03:56:32.459] npm ERR! A complete log of this run can be found in:
[03:56:32.459] npm ERR!     /vercel/.npm/_logs/2023-03-22T02_56_24_342Z-debug-0.log
[03:56:32.488] Error: Command "npm install" exited with 1
[03:56:32.744] BUILD_UTILS_SPAWN_1: Command "npm install" exited with 1
```

**Comment by pi0** [comment]
I think we need to hotfix the docs until finding a better solution. kit is also not a dependency for main layer and usage (while is shorter) is technically wrongly adviced.

**Comment by danielroe** [comment]
I believe this is now resolved - I can't replicate with your provided reproduction, either locally or deploying on vercel.

Let me know if not.
