### ISSUE TITLE
Ssr fall when using navigateTo from route plugin

### ISSUE THREAD

**Issue by Venegrad** [nuxt/nuxt#19878]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `css`, `alias`, `plugins`, `modules`, `i18n`, `postcss`, `vite`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-beta.10`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/Venegrad/venegrad.com

### Describe the bug

plugins/authRoute.js:
```
export default defineNuxtPlugin(async (nuxtApp) => {
  addRouteMiddleware(async (to, from) => {
    const data  = await $fetch('/api/auth/check-login');

    if(to.meta.requiresAuth && !data.user) {
      return navigateTo('/auth')
    }
  })
})
```

server/api/check-login.js
```
import { parse } from 'cookie';
import jwt from 'jsonwebtoken';
import secret from "@/helpers/setting";

function verifyToken(token, secret) {
  try {
    const decoded = jwt.verify(token, secret);
    return decoded;
  } catch (error) {
    return false;
  }
}

export default defineEventHandler((event) => {
  const serverCookies = parse(event.req.headers.cookie || '');
  const token = serverCookies.authToken;

  return {
    user: token ? verifyToken(token, secret.secret) : false
  }
})
```

When request `const data  = await $fetch('/api/auth/check-login');` returning user = false? and reload page, ssr ruins with error 

```
[Vue Router warn]: uncaught error during route navigation:
           10:36:34
Error: nuxt instance unavailable
           10:36:34
    at Module.useNuxtApp (C:\Users\venegrad\Desktop\venegrad\node_modules\nuxt\dist\app\nuxt.js:181:13)
    at useRouter (C:\Users\venegrad\Desktop\venegrad\node_modules\nuxt\dist\app\composables\router.js:16:32)
    at Module.navigateTo (C:\Users\venegrad\Desktop\venegrad\node_modules\nuxt\dist\app\composables\router.js:83:18)
    at C:\Users\venegrad\Desktop\venegrad\plugins\authRoutes.js:8:36
    at async Object.callAsync (file:///C:/Users/venegrad/Desktop/venegrad/node_modules/unctx/dist/index.mjs:53:16)
    at async C:\Users\venegrad\Desktop\venegrad\node_modules\nuxt\dist\pages\runtime\plugins\router.js:119:22
```

### Additional context

U can login with 
login: venegrad@gmail.com 
pass: wwdu3cya

Affer you will be redirected to main page, but, if after 3 seconds u will reload page u will get an error.

**Comment by Venegrad** [comment]
i think issue here because nuxt instance is not aviable in addRouteMiddleware on ssr

**Comment by danielroe** [comment]
You can read about the reason here: https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.

I would recommend adding your middleware instead as `~/middleware/auth-route.global.ts`:

```ts
export default defineNuxtRouteMiddleware(async (to, from) => {
  // useRequestFetch will automatically proxy the headers through to your API route
  const data  = await useRequestFetch()('/api/auth/check-login');

  if(to.meta.requiresAuth && !data.user) {
    return navigateTo('/auth')
  }
})
```

Or alternatively you can do it like this:

```ts
export default defineNuxtPlugin(async (nuxtApp) => {
  // defineNuxtRouteMiddleware signals to Nuxt to preserve the Nuxt context after await
  addRouteMiddleware(defineNuxtRouteMiddleware(async (to, from) => {
    const data  = await $fetch('/api/auth/check-login');

    if(to.meta.requiresAuth && !data.user) {
      return navigateTo('/auth')
    }
  })
}))
```
