### ISSUE TITLE
Escaping strings in .env doesn't work

### ISSUE THREAD

**Issue by AregGhazaryan** [nuxt/nuxt#19904]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.2.0`
- Nitro Version:    `2.2.1`
- Package Manager:  `npm@9.5.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.6.4`
- Build Modules:    `-`
------------------------------

### Reproduction

To reproduce, simply add 
`
MY_VAR="ahbo4aui2h$"
`
in your .env

### Describe the bug

When i add an environment variable that has "$" in it, nuxt throws an error 

`Cannot start nuxt:  dotenv-expand failed to expand env vars. Maybe you need to escape $?`

Even when you still escape it like so `MY_VAR="ahbo4aui2h\$"` it still breaks, i even tried single quotes and no quotes, nothing helps.

### Logs

```shell-script
ERROR  Cannot start nuxt:  dotenv-expand failed to expand env vars. Maybe you need to escape $?                                                                                     20:20:28

  at loadEnv (/C:/Projects/my-proj/node_modules/vite/dist/node/chunks/dep-3007b26d.js:44346:19)
  at resolveConfig (/C:/Projects/my-proj/node_modules/vite/dist/node/chunks/dep-3007b26d.js:61877:9)                                                               20:20:26  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Module.createServer (/C:/Projects/my-proj/node_modules/vite/dist/node/chunks/dep-3007b26d.js:61127:20)
  at async buildClient (/C:/Projects/my-proj/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.970f93e5.mjs:367:24)
  at async bundle (/C:/Projects/my-proj/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.970f93e5.mjs:961:3)
  at async build (/C:/Projects/my-proj/node_modules/nuxt/dist/index.mjs:2584:5)
  at async Promise.all (index 1)
  at async load (/C:/Projects/my-proj/node_modules/nuxi/dist/chunks/dev.mjs:6805:9)
  at async Object.invoke (/C:/Projects/my-proj/node_modules/nuxi/dist/chunks/dev.mjs:6859:5)
```
```

**Comment by danielroe** [comment]
This seems to be an upstream issue in vite that is now resolved: https://github.com/vitejs/vite/issues/12006. You might need to refresh your lockfile and ensure you're on the latest Nuxt version.
