### ISSUE TITLE
Request error on nuxt start : Cannot find module '.../.output/', involving either pinia or pinia-orm

### ISSUE THREAD

**Issue by olinox14** [nuxt/nuxt#20128]
### Environment

This error occurred on different environments, with some variations. Concerning the project I am working on, I had this error on a docker local server and on a testing distant server, both with this configuration : 

- Operating System: `Linux`
- Node Version:     `v18.10.0`
- Nuxt Version:     `3.3.3`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `ssr`, `runtimeConfig`, `hooks`, `app`, `css`, `typescript`, `modules`, `vite`, `i18n`, `build`
- Runtime Modules:  `()`, `@pinia/nuxt@0.4.7`, `@pinia-orm/nuxt@1.6.7`, `@nuxtjs/i18n@8.0.0-beta.10`, `@nuxt/image-edge@1.0.0-28008586.381b906`, `@nuxt/devtools@0.2.5`
- Build Modules:    `-`

On this env, I've got the error described later.

A similar error occured on the stackblitz env (see later)

 

### Reproduction

You can reproduce the error on [the following stackblitz](https://stackblitz.com/edit/nuxt-starter-gnioxz?file=package.json,nuxt.config.ts,app.vue)

Interrupt the dev server in the console, then run 

    yarn install
    yarn build
    yarn  start

And refresh the preview.

### Describe the bug

I've got a Nuxt 3 project, with [pinia](https://pinia.vuejs.org/) and [pinia-orm](https://pinia-orm.codedredd.de/). SSR is on.

When I run the dev server with `nuxt dev`, **everything runs fine**. 

But **if I build and start the server** with `nuxt build` and `nuxt start`, as soon as a page is requested, the server throws an error 500 and logs the following :

    [nuxt] [request error] [unhandled] [500] Cannot find module '/home/workspace/.output/server/node_modules/pinia-orm/dist/decorators' imported from /home/workspace/.output/server/chunks/app/server.mjs
      at new NodeError (node:internal/errors:393:5)  
      at finalizeResolution (node:internal/modules/esm/resolve:323:11)  
      at moduleResolve (node:internal/modules/esm/resolve:916:10)  
      at defaultResolve (node:internal/modules/esm/resolve:1124:11)  
      at nextResolve (node:internal/modules/esm/loader:163:28)  
      at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)  
      at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)  
      at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)  
      at link (node:internal/modules/esm/module_job:75:36)

I've tried to :

- remove all caches and nuxt generated files to rebuild from scratch
- move the @pinia/nuxt and @pinia-orm/nuxt dependencies in the devDependencies in package.json, as suggested [here][1], even if documentations instruct otherwise
- install both pinia and and @pinia/nuxt, or only @pinia/nuxt as suggested here
- use npm and force install pinia with npm as proposed [here](https://github.com/vuejs/pinia/issues/1542#issuecomment-1238820465) (I use yarn in this project)
- remove the autoImports section in the nuxt.config.ts, as suggested somewhere

### Logs

```shell-script
On my local env:

[nuxt] [request error] [unhandled] [500] Cannot find module '/home/workspace/.output/server/node_modules/pinia-orm/dist/decorators' imported from /home/workspace/.output/server/chunks/app/server.mjs
  at new NodeError (node:internal/errors:393:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:323:11)  
  at moduleResolve (node:internal/modules/esm/resolve:916:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1124:11)  
  at nextResolve (node:internal/modules/esm/loader:163:28)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)  
  at link (node:internal/modules/esm/module_job:75:36)


On stackblitz :

[nuxt] [request error] [unhandled] [500] Cannot find module '/home/projects/nuxt-starter-gnioxz/.output/server/node_modules/pinia/dist/pinia.prod.cjs' imported from /home/projects/nuxt-starter-gnioxz/.output/server/node_modules/pinia-orm/dist/index.mjs
  at get (https://nuxtstartergnioxz-3aer.w-corp.staticblitz.com/blitz.b5037fed.js:35:344852)  
  at get (./server/node_modules/h3/dist/index.mjs:238:11)  
  at normalizeError (./server/chunks/nitro/node-server.mjs:423:18)  
  at errorhandler (./server/chunks/nitro/node-server.mjs:442:71)  
  at toNodeHandle (./server/node_modules/h3/dist/index.mjs:1430:27)
```

**Comment by danielroe** [comment]
For now you can add them to your `build.transpile` array:

```diff
  export default defineNuxtConfig({
    // ...
+   build: {
+     transpile: ['pinia', 'pinia-orm']
+   },
    // ...
  })
```

But this suggests there might be an upstream issue with the nitro tracer (cc: @pi0).

**Comment by olinox14** [comment]
Thanks for your reply, the bug is solved for now, seemingly. I'll test it more in a few days, but it seems all good.
Shall I contact pinia and pinia-orm teams so they update their docs?

**Comment by daniandl** [comment]
Just wanted to point out that this bug also happened to me, but at the build step, not during requests.
It doesn't happen on regular builds, only on `NITRO_PRESET=cloudflare`.

**Comment by kimbaudi** [comment]
@danielroe - the workaround of adding `pinia` to `build.transpile` in `nuxt.config.ts` does not work when I deploy to vercel. I still get 500 error (cannot find module pinia/dist/pinia.prod.cjs).

![image](https://github.com/nuxt/nuxt/assets/1864092/7389013a-6c8e-4da0-9c5e-cbb73f9717f2)


links to minimal reproducible repos:
- https://github.com/kimbaudi/vue3tslibtest
- https://github.com/kimbaudi/vue3-nuxt-demo

links to discussions in pinia:
- https://github.com/vuejs/pinia/discussions/2216
- https://github.com/vuejs/pinia/discussions/2286
