### ISSUE TITLE
Rollup failed to resolve import "@unhead/vue" for nuxt layers parent

### ISSUE THREAD

**Issue by warflash** [nuxt/nuxt#20152]
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `^3.3.3`
- Nitro Version:    `-`
- Package Manager:  `npm@7.17.0`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/warflash/nuxt-layers-useHead-parent
https://github.com/warflash/nuxt-layers-useHead-base

### Describe the bug

Rollup failed to resolve import "@unhead/vue" from "path/to/component.vue/"

Traditional workarounds like setting the alias in the parent config to the exported cjs or mjs like this:
```
alias: {
      "@unhead/vue": require.resolve("@unhead/vue/dist/index.mjs"),
},
```
do not seem to work. Or atleast I cant get them to work :/

### Logs

```shell-script
[00:56:26.036] Running build in Washington, D.C., USA (East) – iad1
[00:56:26.090] Cloning github.com/warflash/nuxt-layers-useHead-parent (Branch: main, Commit: 53d778a)
[00:56:26.361] Cloning completed: 270.639ms
[00:56:26.415] Previous build cache not available
[00:56:26.519] Running "vercel build"
[00:56:27.093] Vercel CLI 28.18.3
[00:56:27.779] Installing dependencies...
[00:56:46.017] npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[00:56:49.504] 
[00:56:49.505] > postinstall
[00:56:49.505] > nuxt prepare
[00:56:49.505] 
[00:56:49.620] [log] Nuxi 3.3.3
[00:56:51.812] [success] Types generated in .nuxt
[00:56:51.842] 
[00:56:51.842] added 607 packages in 24s
[00:56:51.842] 
[00:56:51.842] 95 packages are looking for funding
[00:56:51.842]   run `npm fund` for details
[00:56:51.879] Detected `package-lock.json` generated by npm 7+...
[00:56:51.880] Running "npm run build"
[00:56:52.296] 
[00:56:52.297] > build
[00:56:52.297] > nuxt build
[00:56:52.297] 
[00:56:52.404] [log] Nuxi 3.3.3
[00:56:52.433] [log] Nuxt 3.3.3 with Nitro 2.3.2
[00:56:53.428] [error] (node:198) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
[00:56:53.428] (Use `node --trace-deprecation ...` to show where the warning was created)
[00:56:55.086] [info] Building client...
[00:56:55.102] [info] [36mvite v4.2.1 [32mbuilding for production...[36m[39m
[00:56:55.176] [info] transforming...
[00:56:56.021] [info] [32m✓[39m 48 modules transformed.
[00:56:56.021] [info] [32m✓[39m built in 917ms
[00:56:56.022] [error] [31m[vite]: Rollup failed to resolve import "@unhead/vue" from "/vercel/.cache/c12/github_warflash_nuxt-layers-useHead-base/pages/index.vue?vue&type=script&setup=true&lang.ts".
[00:56:56.022] This is most likely unintended because it can break your application at runtime.
[00:56:56.022] If you do want to externalize this module explicitly add it to
[00:56:56.022] `build.rollupOptions.external`[39m
[00:56:56.025] [error] [vite]: Rollup failed to resolve import "@unhead/vue" from "/vercel/.cache/c12/github_warflash_nuxt-layers-useHead-base/pages/index.vue?vue&type=script&setup=true&lang.ts".
[00:56:56.025] This is most likely unintended because it can break your application at runtime.
[00:56:56.025] If you do want to externalize this module explicitly add it to
[00:56:56.025] `build.rollupOptions.external`
[00:56:56.025]   This is most likely unintended because it can break your application at runtime.
[00:56:56.025]   If you do want to externalize this module explicitly add it to
[00:56:56.025]   `build.rollupOptions.external`
[00:56:56.026]   at onRollupWarning (node_modules/vite/dist/node/chunks/dep-79892de8.js:46368:19)
[00:56:56.026]   at onwarn (node_modules/vite/dist/node/chunks/dep-79892de8.js:46138:13)
[00:56:56.026]   at Object.onwarn (node_modules/rollup/dist/es/shared/node-entry.js:25149:13)
[00:56:56.026]   at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:23784:26)
[00:56:56.026]   at node_modules/rollup/dist/es/shared/node-entry.js:23744:26
[00:56:56.026]   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[00:56:56.065] Error: Command "npm run build" exited with 1
[00:56:56.358] BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1
```

**Comment by mvdschee** [comment]
@warflash in your [parent project](https://github.com/warflash/nuxt-layers-useHead-parent) add `.npmrc` at the root with the content
```
shamefully-hoist=true
```

this will allow it to use some of the packages that would normally not link properly

**Comment by warflash** [comment]
Thanks, that's what we're using in our production repo by default but we still get the issue there. Have you verified that fixes it for you?

**Comment by mvdschee** [comment]
Yes, I just fixed one of our projects that had this issue, but I'm running `"nuxt": "3.4.1"`

**Comment by mvdschee** [comment]
True, did not consider that one yet.

I also tried the alias, but it gave me an error because the export could not be found.

This worked instead for me:
```
alias: {
      "@unhead/vue": require.resolve("@unhead/vue"),
},
```
_This was the case for `pnpm` but might be a workaround that works_

**Comment by warflash** [comment]
For most other deps the alias workaround fixes dependency issues we have with layers but not for `@unhead/vue` for some reason. Might be a side effect of pnpm that that one works for you as well? 
Not really sure tbh but it's quite frustrating as `useHead` is built in functionality and needed on basically every route

**Comment by bitmonti** [comment]
same here using npm

**Comment by jawngee** [comment]
I just ran into this upgrading to nuxt latest.  @bitmonti's top saved my bacon.  thanks!

**Comment by simonmaass** [comment]
i am having the same problem in nuxt 3.6.5

**Comment by hedongshu** [comment]
I encountered the same problem
 @bitmonti's solution let me work，但是在cloudflare page中报错
 ```
[error] Nuxt Build Error: Could not load ./node_modules/@unhead/vue (imported by node_modules/.pnpm/nuxt@3.7.4_eslint@8.39.0_typescript@5.0.4/node_modules/nuxt/dist/head/runtime/plugins/unhead.js): ENOENT: no such file or directory, open './node_modules/@unhead/vue'
```

**Comment by danielroe** [comment]
This should be resolved in the latest version of c12 with https://github.com/unjs/c12/pull/109.
