### ISSUE TITLE
Serverless Function Invocation Failed at Timeout when deploying Nuxt 3 site on Vercel

### ISSUE THREAD

**Issue by john-szetho** [nuxt/nuxt#20220]
### Environment

Hey there, I am trying to deploy a Nuxt 3 site on Vercel and have been trying to fix this error for the last couple of days.

Not sure if it's a bug or my inexperience with Nuxt (forgive me I am still learning), but I can't figure it out. The site works fine on my local development server, it just won't deploy.

I suspect it has something to do with the plugins:
— plugins/about.js
— plugins/creditCard.js
— plugins/message.js

### Reproduction

https://contentdotnet.vercel.app/

### Describe the bug

This is the error code:

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: syd1::hz7dz-1681254028180-392b059c733b

This prints in terminal:

```
[nitro] [dev] [uncaughtException] ReferenceError: document is not defined                                                         00:11:28
    at Timeout._onTimeout (/Applications/MAMP/htdocs/contentdotnet/website-1.1/plugins/about.js:6:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[nitro] [dev] [uncaughtException] ReferenceError: document is not defined                                                         00:11:28
    at Timeout._onTimeout (/Applications/MAMP/htdocs/contentdotnet/website-1.1/plugins/message.js:14:24)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[nitro] [dev] [uncaughtException] ReferenceError: document is not defined                                                         00:11:34
    at Timeout._onTimeout (/Applications/MAMP/htdocs/contentdotnet/website-1.1/plugins/creditCard.js:6:25)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

### Additional context

Here is the code:

```
// pages/index.vue
<template>
    <div>
        <div id="main">
            <PlaceholderHeader class="clickable" />
            <CreditCard />
            <PlaceholderContent class="clickable" />
            <TheFooter />
        </div>
        <About />
    </div>
</template>
```

```
// components/PlaceholderHeader.vue
<template>
    <header>
        <NuxtLink class="logo" to="/">
            <nuxt-img src="/assets/img/logo-chrome.png" alt="Content Dot Net" />
        </NuxtLink >
        <div class="counter">
            <div>0005312</div>
        </div>
    </header>
</template>
```

```
// components/About.vue
<template>
    <div id="about" class="container">
        <div v-if="data">
            <div v-for="about in data">
                <h1>{{ about.about[0].children[0].text }}</h1>
                <h2><span class="underline">{{ about.about[1].children[0].text }}</span>{{ about.about[1].children[1].text }}</h2>
                <h3><NuxtLink href="mailto:info@content.net.au">EMAIL...</NuxtLink> <NuxtLink to="https://instagram.com/content.net.au">INSTAGRAM...</NuxtLink> <NuxtLink to="https://contentnetau.bandcamp.com/">BANDCAMP...</NuxtLink></h3>
                <p>{{ about.about[3].children[0].text }}</p>
                <p>{{ about.about[4].children[0].text }}</p>
            </div>
        </div>
    </div>
</template>

<script setup>
    // sanity
    const query = groq`*[_type == 'about'] {
        about[]{
            _key,
            _type,
            children[]{
                _key,
                _type,
                text
                }
        }}`;
    const { data } = useSanityQuery(query);
</script>
```

```
// components/CreditCard.vue
<template>
    <div class="container">
        <div id="credit-card"></div>
    </div>
</template>
```

```
//components/TheFooter.vue
<template>
    <footer>
        <button id="footer-btn" class="logo">
            <nuxt-img src="/assets/img/logo-c-chrome.png" alt="C" />
        </button >
        <div class="copyright">
            <p>Content Dot Net © 2023</p>
        </div>
    </footer>
</template>
```

```
// plugins/about.js
export default defineNuxtPlugin(nuxtApp => {
    // about footer button interaction
    setTimeout(() => {
        var footerBtn = document.querySelector('#footer-btn');
        var about = document.querySelector('#about');
        var main = document.querySelector('#main');
    
        footerBtn.addEventListener('click', function() {
            about.classList.add('open')
            main.classList.add('blur')
        });
    
        about.addEventListener('click', function() {
            about.classList.remove('open')
            main.classList.remove('blur')
        });
    }, 100)
})
```

```
// plugins/creditCard.js
export default defineNuxtPlugin(nuxtApp => {
    // prompt: credit card number
    setTimeout(() => {
        const element = document.getElementById('credit-card')
        var creditCard = Number(prompt('Enter credit card number'))
        // var validation = /^(?:4[0-9]{12}(?:[0-9]{3})?)$/

        if (creditCard == 0) {
            // document.getElementById('credit-card').innerHTML = 'Invalid'
            console.log('Invalid')
        }
        else if (!Number.isNaN(creditCard)) {
            element.innerHTML = creditCard + ' 💰'
            element.classList.add('valid')
            console.log('Credit Card Number: ' + creditCard)

            element.addEventListener('click', function() {
                element.classList.add('hide')
            })
        }
        else if (Number.isNaN(creditCard)) {
            element.innerHTML = 'Invalid credit card number. Try again'
            console.log('N/A')

            element.addEventListener('click', function() {
                element.classList.add('hide')
            })
        }
    }, 6000);
  })
```

```
// plugins/message.js
export default defineNuxtPlugin(nuxtApp => {
    // alert: message
    setTimeout(function() {
        var messageIntro = 'NEW MESSAGE (1) from content.net.au: \n\n'
        var message1 = messageIntro + 'Welcome to our world! Please click the links to hear our music + watch our videos…if u do i will return the favour…also pls follow us on social media x'
        var message2 = messageIntro + 'Lets connect, send me an email info@content.net.au'
        var message3 = messageIntro + 'https://drive.google.com/drive/folders/1S3ilSaQCreXwAxNdrvYnEnQKex2NquWH?usp=share_link'

        var messageArray = [message1, message2, message3];
        var count = -1;

        var elements = document.getElementsByClassName('clickable');

        for (var i = 0, len = elements.length; i < len; i++) {
            elements[i].addEventListener("click", function() {
                alert(messageArray[++count % messageArray.length]);
            });
        }
    }, 100);
  })
```

### Logs

Log via Vercel:

```
Uncaught Exception 	{"errorType":"ReferenceError","errorMessage":"document is not defined","stack":["ReferenceError: document is not defined","    at Timeout._onTimeout (file:///var/task/chunks/app/server.mjs:875:21)","    at listOnTimeout (node:internal/timers:564:17)","    at process.processTimers (node:internal/timers:507:7)"]}
Unknown application error occurred
Runtime.Unknown
```

**Comment by warflash** [comment]
I'd be kind of surprised of that works locally tbh.
But like you mentioned and also what the error is saying the issue comes from 
```
var footerBtn = document.querySelector('#footer-btn');
var about = document.querySelector('#about');
var main = document.querySelector('#main');    
```

On the server side you dont have access to the `document` object hence it throws the error.

You might be able to do some fancy things like check for `process.client`, make the plugin client only or wrap things in a `onMounted` hook but in general accessing and calling `querySelector` in a vue app is a big red flag.

I'm not sure about your usecase but to me those plugins all look like they should just be in a component, use template interpolation and follow the general vue architecture

**Comment by john-szetho** [comment]
Thanks for the tip, I didn't realise `document` isn't available.. but makes sense.

Will have another go, thanks!

**Comment by warflash** [comment]
As daniel mentioned, this is not really something suited for github issues, the nuxt or vue discord or even discussion tab would be better suited. 

There's a ton of routes, if you really wanted to reuse the function you could built it in a way that expects a ref as a param and acts based on that. That seems overkill here though and not something I'd recommend for your case. 

Maybe try looking into how [events](https://vuejs.org/guide/components/events.html) and [props](https://vuejs.org/guide/components/props.html) work, sounds like that'd be more applicable here. You could also keep track of the current state and bind classes to your things based on that.
