### ISSUE TITLE
Can't resolve plugins on initializing nuxt 3.4.0(also after 3.3.0)

### ISSUE THREAD

**Issue by Skmt3P** [nuxt/nuxt#20248]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.0
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qsa4ck?file=app.vue

### Describe the bug

In Nuxt 3.4.0, I get the attached error when I run `nuxi prepare`. 

The contents of the .nuxt folder are hardly generated and the development environment does not start up. 

I understand that this is an incorrect usage of plugins, but since this bug did not occur in the 3.0.0 series, I would like to prevent this from occurring. 

A workaround approach is also welcome.

### Additional context

- This bug also occurs in past versions after 3.3.0.
- This bug does NOT occurs in 3.2.3 version (maybe...).
- This bug also occurs in dev and build commands.

### Logs

```shell-script
❯ npm run postinstall
$ nuxt prepare
Nuxi 3.4.0                                                                            09:32:15

[09:32:16]  ERROR  Error while requiring module /home/projects/nuxt-starter-qsa4ck/modules/test.ts: Error: Cannot find module '@/plugins/aaa'
Require stack:
- /home/projects/nuxt-starter-qsa4ck/modules/test.ts


 ERROR  Cannot find module '@/plugins/aaa'                                            09:32:16
Require stack:
- /home/projects/nuxt-starter-qsa4ck/modules/test.ts

  Require stack:
  - modules/test.ts
  at Module._resolveFilename (https://nuxtstarterqsa4ck-iylz.w-credentialless.staticblitz.com/blitz.9926f97d.js:35:242305)
  at Function.resolve (https://nuxtstarterqsa4ck-iylz.w-credentialless.staticblitz.com/blitz.9926f97d.js:35:480406)
  at _resolve (node_modules/jiti/dist/jiti.js:1:241100)
  at jiti (node_modules/jiti/dist/jiti.js:1:243384)
  at eval (modules/test.ts:1:170)
  at jiti (node_modules/jiti/dist/jiti.js:1:245859)
  at requireModule (file://node_modules/@nuxt/kit/dist/index.mjs:355:26)
  at normalizeModule (file://node_modules/@nuxt/kit/dist/index.mjs:541:77)
  at Module.installModule (file://node_modules/@nuxt/kit/dist/index.mjs:520:47)
  at initNuxt (file://node_modules/nuxt/dist/index.mjs:2633:23)
```
```

**Comment by danielroe** [comment]
Aliases are not supported in modules so this would never have worked. But before v3.3.0, they were not automatically loaded just because they are in a `modules` directory. You can:

1. update the import statement not to use aliases
2. rename your `modules` folder
3. change `dir.modules` to a different directory

**Comment by Skmt3P** [comment]
@danielroe 
OK! Thx!
