### ISSUE TITLE
devtools giving error on nuxt 3.4.1

### ISSUE THREAD

**Issue by joseehilton147** [nuxt/nuxt#20267]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      app, css, modules, pinia, imports, build, runtimeConfig, devServer, nitro, experimental
- Runtime Modules:  @pinia/nuxt@0.4.8, @unocss/nuxt@0.51.4, nuxt-icon@0.3.3, @pinia-plugin-persistedstate/nuxt@1.1.1, @nathanchase/nuxt-dayjs-module@1.0.15, nuxt-viewport@2.0.4
- Build Modules:    -

### Reproduction

for me was switching node version from 18 to 16 and then go back to 18, the code wasnt changed.

### Describe the bug

Ive updated to nuxt 3.4.1 on morning, used the project all day and switched to another project wich runs on a older node version using NVM, switched to v16, but when i come back to node v18 on nuxt project give a error with devtools with any modification on code, only node version switched.

![image](https://user-images.githubusercontent.com/53986027/231899597-215bd6c4-d3e3-4ae5-bd16-f5981c40f4e9.png)

### Logs

```shell-script
ERROR  Cannot start nuxt:  Cannot find module 'C:/Program Files/nodejs/node_modules/@nuxt/devtools/module.cjs'                       19:46:28
Require stack:
- C:\Cliqx\Repositorios\cliqx.pernambucanas.catalogo.create.frontend\index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
  at Function.resolve (node:internal/modules/cjs/helpers:116:19)
  at Function._resolve [as resolve] (node_modules\jiti\dist\jiti.js:1:241025)
  at resolveModule (/C:/Cliqx/Repositorios/cliqx.pernambucanas.catalogo.create.frontend/node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:260:29)
  at normalizeModule (/C:/Cliqx/Repositorios/cliqx.pernambucanas.catalogo.create.frontend/node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:469:18)
  at installModule (/C:/Cliqx/Repositorios/cliqx.pernambucanas.catalogo.create.frontend/node_modules/nuxt/node_modules/@nuxt/kit/dist/index.mjs:451:47)
  at initNuxt (/C:/Cliqx/Repositorios/cliqx.pernambucanas.catalogo.create.frontend/node_modules/nuxt/dist/index.mjs:2616:13)
  at async load (/C:/Cliqx/Repositorios/cliqx.pernambucanas.catalogo.create.frontend/node_modules/nuxi/dist/chunks/dev.mjs:6824:9)
  at async Object.invoke (/C:/Cliqx/Repositorios/cliqx.pernambucanas.catalogo.create.frontend/node_modules/nuxi/dist/chunks/dev.mjs:6874:5)
  at async _main (/C:/Cliqx/Repositorios/cliqx.pernambucanas.catalogo.create.frontend/node_modules/nuxi/dist/cli.mjs:47:20)
```

**Comment by danielroe** [comment]
Would you check whether you have a `.nuxtrc` file in your home folder which is enabling devtools?
