### ISSUE TITLE
Error when trying to run dev server on fresh project: `Cannot read properties of undefined (reading 'port')`

### ISSUE THREAD

**Issue by hhofner** [nuxt/nuxt#20303]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

The repo https://github.com/hhofner/my-app-test

commands I ran to encounter issue:
```
npx nuxi@latest init my-app
yarn
yarn dev
```

### Describe the bug

I tried to start a fresh new Nuxt 3 project from the command found on nuxtjs.com `npx nuxi@latest init my-app`. After installing with yarn, I tried to run dev server and I get the following error:

```
Cannot read properties of undefined (reading 'port')

  at Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6777:78)
  at async _main (node_modules/nuxi/dist/cli.mjs:47:20)
```

When adding the port manually with `yarn dev --port 3001` I get 
```
Cannot read properties of undefined (reading 'host')

  at Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6778:82)
  at async _main (node_modules/nuxi/dist/cli.mjs:47:20)
```

so somewhere in `node_modules/nuxi/dist/chunks/dev.mjs:6778:82` the options aren't being passed in
```
const listener = await listen(serverHandler, {
      showURL: false,
      clipboard: args.clipboard,
      open: args.open || args.o,
      port: args.port || args.p || process.env.NUXT_PORT || config.devServer.port,
      hostname: args.host || args.h || process.env.NUXT_HOST || config.devServer.host,
      https: args.https !== false && (args.https || config.devServer.https) ? {
        cert: args["ssl-cert"] || config.devServer.https && config.devServer.https.cert || void 0,
        key: args["ssl-key"] || config.devServer.https && config.devServer.https.key || void 0
      } : false
    });
```

Initially I thought it may be due to Nuxt version, so I naively manually changed the version to `3.0.0` in the `package.json` and ran `yarn` again, but it didn't do anything (may or may not be useful).

### Additional context

I have another random bootstrapped Nuxt project that I made some time ago (around October 3rd via the `stat` command) that works just fine: https://github.com/hhofner/working-nuxt-example

If it's on my end, I'm not sure what problem it may be (apologies if it is..)

**Comment by hhofner** [comment]
For some reason I got it to work.
