### ISSUE TITLE
use18In in utils function on click event

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#20431]
### Environment

https://stackblitz.com/edit/nuxt-starter-fytnw3?file=README.md

### Reproduction

When i puss the button, throws me:

`Uncaught SyntaxError: Must be called at the top of a `setup` function (at message-compiler.mjs?v=fe22c653:54:19)
    at createCompileError (message-compiler.mjs?v=fe22c653:54:19)
    at createI18nError (vue-i18n.mjs?v=fe22c653:92:12)
    at useI18n (vue-i18n.mjs?v=fe22c653:2243:15)
    at apiError (utils.ts:2:3)
    at loadDescription (index.vue:10:23)
    at callWithErrorHandling (chunk-LGAZO65B.js?v=fe22c653:1580:18)
    at callWithAsyncErrorHandling (chunk-LGAZO65B.js?v=fe22c653:1588:17)
    at HTMLButtonElement.invoker (chunk-LGAZO65B.js?v=fe22c653:8198:5)`

### Describe the bug

When i puss the button, throws me:

`Uncaught SyntaxError: Must be called at the top of a `setup` function (at message-compiler.mjs?v=fe22c653:54:19)
    at createCompileError (message-compiler.mjs?v=fe22c653:54:19)
    at createI18nError (vue-i18n.mjs?v=fe22c653:92:12)
    at useI18n (vue-i18n.mjs?v=fe22c653:2243:15)
    at apiError (utils.ts:2:3)
    at loadDescription (index.vue:10:23)
    at callWithErrorHandling (chunk-LGAZO65B.js?v=fe22c653:1580:18)
    at callWithAsyncErrorHandling (chunk-LGAZO65B.js?v=fe22c653:1588:17)
    at HTMLButtonElement.invoker (chunk-LGAZO65B.js?v=fe22c653:8198:5)`

**Comment by danielroe** [comment]
The error message seems pretty descriptive to me. You are calling useI18n in the wrong place, within a function rather than in a setup function.
