### ISSUE TITLE
Cannot split a chunk

### ISSUE THREAD

**Issue by kaikaibenkai** [nuxt/nuxt#20444]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      ssr, modules, devServer
- Runtime Modules:  (), ()
- Build Modules:

### Reproduction

In `plugins/1.config.ts`:
```ts
import { readConfig, writeConfig } from '~~/utils/config';
export default defineNuxtPlugin(async () => {
  await writeConfig(await readConfig());
  return {};
});
```

In `utils/config.ts`:
```ts
import { fs, path } from '@tauri-apps/api';

// file paths, it runs well
const DIR = (await path.appConfigDir()).slice(0, -1);
export const CONFIG_FILE = `${DIR}\\config.json`;

// methods
export interface Config {
   key: number;
}
let config: Config;
export async function readConfig(): Promise<Config> {
  return JSON.parse(await fs.readTextFile(CONFIG_FILE)); // read & parse config file
}
export async function writeConfig(value: Config) {
  config = value;
  await fs.writeTextFile({ // save config file
    path: CONFIG_FILE,
    contents: JSON.stringify(value),
  });
}
```

### Describe the bug

(I'm having trouble comprehending the error message, so sorry)

### Logs

```shell-script
[10:34:54]  ERROR  Internal server error: Cannot split a chunk that has already been edited (3:20 – "await writeConfig(await readConfig())")
  Plugin: unctx:transform
  File: D:/hzh/grade-analyzer/plugins/1.config.ts
      at MagicString._splitChunk (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/magic-string/dist/magic-string.es.mjs:924:10)
      at MagicString._split (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/magic-string/dist/magic-string.es.mjs:914:43)
      at MagicString.update (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/magic-string/dist/magic-string.es.mjs:697:8)                                                                                                 10:34:54  
      at MagicString.overwrite (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/magic-string/dist/magic-string.es.mjs:682:15)
      at injectForNode (file:///D:/hzh/grade-analyzer/node_modules/unctx/dist/transform.mjs:117:9)
      at Object.enter (file:///D:/hzh/grade-analyzer/node_modules/unctx/dist/transform.mjs:95:13)
      at SyncWalker.visit (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/estree-walker/src/sync.js:65:16)
      at SyncWalker.visit (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/estree-walker/src/sync.js:100:19)
      at SyncWalker.visit (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/estree-walker/src/sync.js:107:12)
      at SyncWalker.visit (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/estree-walker/src/sync.js:107:12)
      at SyncWalker.visit (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/estree-walker/src/sync.js:100:19)
      at walk (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/estree-walker/src/index.js:20:18)
      at transformFunctionBody (file:///D:/hzh/grade-analyzer/node_modules/unctx/dist/transform.mjs:90:7)
      at transformFunctionArguments (file:///D:/hzh/grade-analyzer/node_modules/unctx/dist/transform.mjs:108:9)
      at Object.enter (file:///D:/hzh/grade-analyzer/node_modules/unctx/dist/transform.mjs:39:13)
      at SyncWalker.visit (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/estree-walker/src/sync.js:65:16)
      at SyncWalker.visit (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/estree-walker/src/sync.js:107:12      at walk (file:///D:/hzh/grade-analyzer/node_modules/unctx/node_modules/estree-walker/src/index.js:20:18)
      at Object.transform (file:///D:/hzh/grade-analyzer/node_modules/unctx/dist/transform.mjs:34:5)      at TransformContext.transform (file:///D:/hzh/grade-analyzer/node_modules/nuxt/dist/index.mjs:1824:34)
      at plugin.transform (file:///D:/hzh/grade-analyzer/node_modules/unplugin/dist/index.mjs:1158:25)
      at Object.transform (file:///D:/hzh/grade-analyzer/node_modules/vite/dist/node/chunks/dep-d305c21f.js:43464:44)    
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///D:/hzh/grade-analyzer/node_modules/vite/dist/node/chunks/dep-d305c21f.js:41182:29)
```

**Comment by kaikaibenkai** [comment]
it looks like an internal error...

**Comment by kaikaibenkai** [comment]
I use this to resolve: (`plugins/1.config.ts`)
```
import { readConfig, writeConfig } from '~~/utils/config';
export default defineNuxtPlugin(() => {
  return new Promise<{ provide?: undefined; }>((resolve) => {
    readConfig().then((value) => {
      writeConfig(value).then(() => {
        resolve({});
      });
    });
  });
});
```

But... Why?

**Comment by danielroe** [comment]
Reproduction: https://stackblitz.com/edit/github-53i1w9?file=plugins/test-unctx.ts.

This is an upstream issue from `unctx` (cc: @pi0).

**Comment by danielroe** [comment]
This should be resolved in unctx v2.3.1. which you can get with `npx nuxi upgrade --force` or by refreshing your lockfile.

Let me know if not and I'll reopen.
