### ISSUE TITLE
[500] Context Conflict when using useCookie

### ISSUE THREAD

**Issue by burda-osowiecki** [nuxt/nuxt#20473]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.2`
- Nitro Version:    `2.3.3`
- Package Manager:  `npm@9.6.2`
- Builder:          `vite`
- User Config:      `devServer`, `imports`, `modules`, `srcDir`, `typescript`
- Runtime Modules:  `@pinia/nuxt@0.4.9`
- Build Modules:    `-`

### Reproduction

https://github.com/burda-osowiecki/nuxt-context-conflict

`npm install`
`npm run build`
`npm run start:debug`

`gtimeout 10 siege -c 20 http://localhost:3000/whatever`

### Describe the bug

After upgrading Nuxt from 3.2.3. to 3.4.2 some requests randomly fails with `[500] Context conflict`
Looks like using `useCookie` during server side fetch throws this error.

### Logs

```shell-script
Request: [GET] /__nuxt_error?url=/whatever&statusCode=500&statusMessage&message=Context+conflict&stack
[nuxt] [request error] [unhandled] [500] Context conflict
  at checkConflict (./.output/server/node_modules/unctx/dist/index.mjs:6:13)  
  at Object.call (./.output/server/node_modules/unctx/dist/index.mjs:50:7)  
  at contextCaller (./.output/server/chunks/app/server.mjs:83:26)  
  at Hookable.callHookWith (./.output/server/node_modules/hookable/dist/index.mjs:198:20)  
  at nuxtApp.hooks.callHook (./.output/server/chunks/app/server.mjs:86:63)  
  at ./.output/server/chunks/handlers/renderer.mjs:389:32  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./.output/server/chunks/handlers/renderer.mjs:31:22  
  at async Object.handler (./.output/server/node_modules/h3/dist/index.mjs:1247:19)  
  at async Server.toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:1322:7)
```

**Comment by FranciscoKloganB** [comment]
I personally get this error when I use the following code snipet.

```ts
export async function useMemoizedFetch<T>(url: string, headers: HeadersInit = {}) {
  const sessionCache = useSessionStorage<T>(url, null, {
    serializer: StorageSerializers.object,
  })

  if (sessionCache.value) {
    return sessionCache
  }

  const cookiesMap = useRequestHeaders(['cookie']) as Record<string, string>

  const result = await $fetch<T>(url, {
    headers: { ...cookiesMap, ...headers },
  })

  sessionCache.value = result as T

  return sessionCache
}
```

**Comment by danielroe** [comment]
linked: https://github.com/nuxt/nuxt/issues/20070
