### ISSUE TITLE
Request error unhandled 500 - missing global references

### ISSUE THREAD

**Issue by moranje** [nuxt/nuxt#20553]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.5.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `typescript`, `debug`, `css`, `modules`, `build`, `vite`, `pwa`, `googleFonts`
- Runtime Modules:  
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-kxynpm-jgrldv?file=package.json

### Describe the bug

When upgrading from nuxt `3.3.1` to `3.3.2` my app using `manaco-editor` stopped working (it crashes before loading anything sensible).

```
[nuxt] [request error] [unhandled] [500] navigator is not defined                                 22:35:36
  at eval (./node_modules/monaco-editor/esm/vs/base/browser/browser.js:112:19)  
  at async ViteNodeRunner.directRequest (file://./node_modules/vite-node/dist/client.mjs:332:5)  
  at async ViteNodeRunner.cachedRequest (file://./node_modules/vite-node/dist/client.mjs:176:14)  
  at async ViteNodeRunner.dependencyRequest (file://./node_modules/vite-node/dist/client.mjs:224:14)  
  at async eval (./node_modules/monaco-editor/esm/vs/base/browser/dom.js:5:31)  
  at async ViteNodeRunner.directRequest (file://./node_modules/vite-node/dist/client.mjs:332:5)  
  at async ViteNodeRunner.cachedRequest (file://./node_modules/vite-node/dist/client.mjs:176:14)  
  at async ViteNodeRunner.dependencyRequest (file://./node_modules/vite-node/dist/client.mjs:224:14)  
  at async eval (./monaco-editor/esm/vs/editor/standalone/browser/inspectTokens/inspectTokens.js:16:31)  
  at async ViteNodeRunner.directRequest (file://./node_modules/vite-node/dist/client.mjs:332:5)
```

I connected the node debugger to see what's happening behind the scenes but I have trouble understanding where the problem (navigator not being available) originates from. Here's a snippet of the code it breaks on. There's no window or navigator available when it breaks.

```js
const userAgent = navigator.userAgent; // because of this
export const isFirefox = (userAgent.indexOf('Firefox') >= 0);
export const isWebKit = (userAgent.indexOf('AppleWebKit') >= 0);
export const isChrome = (userAgent.indexOf('Chrome') >= 0);
export const isSafari = (!isChrome && (userAgent.indexOf('Safari') >= 0));
export const isWebkitWebView = (!isChrome && !isSafari && isWebKit);
export const isElectron = (userAgent.indexOf('Electron/') >= 0); // It breaks here
export const isAndroid = (userAgent.indexOf('Android') >= 0);
```

I am at a loss to debug this down any further. I'm guessing either vite some something to the global scope of nuxt is doing something on the server side of things.

### Additional context

In my app I have also tried surrounding the component with `<ClientOnly>` tags but that did not change anything.

**Comment by danielroe** [comment]
I think the issue is that you are importing code from monaco that relies on being run in a browser environment.  You can try this instead:

https://stackblitz.com/edit/github-kxynpm-svrafv
