### ISSUE TITLE
Nuxt build problem. Failed to publish your Function.

### ISSUE THREAD

**Issue by ReferTV** [nuxt/nuxt#20692]
### Environment

Nuxi 3.4.3                                                                                                                                18:20:33
                                                                                                                                          18:20:34
RootDir: C:/Projekty/MateuszB_portal                                                                                                      18:20:34
Nuxt project info:                                                                                                                        18:20:34

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.17.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.4
- Builder:          vite
- User Config:      ssr, modules, extends, runtimeConfig, app, experimental, vite, nitro, routeRules, sitemap
- Runtime Modules:  @nuxt/image-edge@1.0.0-28020728.5df24eb, @nuxtjs/tailwindcss@6.6.7, nuxt-icon@0.4.0, nuxt-simple-sitemap@2.4.22
- Build Modules:    -
------------------------------

### Reproduction

Deploy page with `nuxt build` on Cloudflare Pages.

### Describe the bug

Its only on cloudflare, locally its works fine for me.

When i generate static page with nuxt generate, all works.
But when i deploy page with nuxt build, I got this error:
<html>
<body>

Error: Failed to publish your Function. Got error: Uncaught ReferenceError: __dirname is not defined   at functionsWorker-0.9946994914616272.js:5989:18
--

</body>
</html>

### Additional context

I'm not sure if it's a nuxt-related bug or not, anyway, if anyone needs access to the code or something to investigate it, tell me.

### Logs

```shell-script
18:15:47.018	Cloning repository...
18:15:48.144	From https://github.com/all4coach-pl/MateuszB_portal
18:15:48.144	 * branch            66b9570ea74cb571a19ee0fedbbed0cebf649c59 -> FETCH_HEAD
18:15:48.144	
18:15:48.209	HEAD is now at 66b9570 revert server
18:15:48.210	
18:15:48.321	
18:15:48.354	Success: Finished cloning repository files
18:15:48.955	Installing dependencies
18:15:48.964	Python version set to 2.7
18:15:52.206	v18.16.0 is already installed.
18:15:53.990	Now using node v18.16.0 (npm v9.5.1)
18:15:54.164	Started restoring cached build plugins
18:15:54.177	Finished restoring cached build plugins
18:15:54.584	Attempting ruby version 2.7.1, read from environment
18:15:56.075	Using /opt/buildhome/.rvm/gems/ruby-2.7.1
18:15:57.078	Using PHP version 5.6
18:15:57.174	5.2.5 is already installed.
18:15:57.191	Using Swift version 5.2.5
18:15:57.192	Started restoring cached node modules
18:15:57.204	Finished restoring cached node modules
18:15:57.210	Started restoring cached yarn cache
18:15:57.222	Finished restoring cached yarn cache
18:15:57.244	Installing yarn at version 1.22.4
18:15:57.262	Installing Yarn!
18:15:57.262	> Downloading tarball...
18:15:57.294	
18:15:57.294	[1/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz --> /tmp/yarn.tar.gz.GXPV9wL9ea
18:15:57.295	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
18:15:57.295	                                 Dload  Upload   Total   Spent    Left  Speed
18:15:57.354	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    80  100    80    0     0   1355      0 --:--:-- --:--:-- --:--:--  1379
18:15:57.399	
100    93  100    93    0     0    894      0 --:--:-- --:--:-- --:--:--   894
18:15:57.472	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
18:15:57.618	
100 1215k  100 1215k    0     0  3763k      0 --:--:-- --:--:-- --:--:-- 3763k
18:15:57.619	
18:15:57.619	[2/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz.asc --> /tmp/yarn.tar.gz.GXPV9wL9ea.asc
18:15:57.619	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
18:15:57.620	                                 Dload  Upload   Total   Spent    Left  Speed
18:15:57.654	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    84  100    84    0     0   2470      0 --:--:-- --:--:-- --:--:--  2470
18:15:57.657	
100    96  100    96    0     0   2594      0 --:--:-- --:--:-- --:--:--  2594
18:15:57.675	
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
18:15:57.776	
100  1028  100  1028    0     0   6589      0 --:--:-- --:--:-- --:--:--  6589
100  1028  100  1028    0     0   6589      0 --:--:-- --:--:-- --:--:--     0
18:15:57.788	> Verifying integrity...
18:15:57.816	gpg: Oops: lock already held by us
18:15:57.825	gpg: Signature made Mon 09 Mar 2020 03:52:13 PM UTC
18:15:57.826	gpg:                using RSA key 6D98490C6F1ACDDD448E45954F77679369475BAA
18:15:57.828	gpg: Good signature from "Yarn Packaging <yarn@dan.cx>" [unknown]
18:15:57.831	gpg: WARNING: This key is not certified with a trusted signature!
18:15:57.831	gpg:          There is no indication that the signature belongs to the owner.
18:15:57.831	Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
18:15:57.832	     Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
18:15:57.832	> GPG signature looks good
18:15:57.832	> Extracting to ~/.yarn...
18:15:57.910	> Adding to $PATH...
18:15:57.928	> We've added the following to your /opt/buildhome/.bashrc
18:15:57.928	> If this isn't the profile of your current shell then please add the following to your correct profile:
18:15:57.928	   
18:15:57.928	export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
18:15:57.929	
18:15:58.297	> Successfully installed Yarn 1.22.4! Please open another terminal where the `yarn` command will now be available.
18:15:58.664	Installing NPM modules using Yarn version 1.22.4
18:16:00.096	yarn install v1.22.4
18:16:00.192	[1/4] Resolving packages...
18:16:00.543	[2/4] Fetching packages...
18:16:26.102	info fsevents@2.3.2: The platform "linux" is incompatible with this module.
18:16:26.102	info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.112	info @esbuild/android-arm@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.113	info "@esbuild/android-arm@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.113	info @esbuild/android-arm@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.113	info @esbuild/android-arm64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.113	info "@esbuild/android-arm64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.113	info @esbuild/android-arm64@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.113	info @esbuild/android-x64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.114	info "@esbuild/android-x64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.114	info @esbuild/darwin-arm64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.114	info "@esbuild/darwin-arm64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.114	info @esbuild/darwin-arm64@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.114	info @esbuild/darwin-x64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.114	info "@esbuild/darwin-x64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.115	info @esbuild/freebsd-arm64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.115	info "@esbuild/freebsd-arm64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.115	info @esbuild/freebsd-arm64@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.115	info @esbuild/freebsd-x64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.115	info "@esbuild/freebsd-x64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.115	info @esbuild/linux-arm@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.115	info "@esbuild/linux-arm@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.115	info @esbuild/linux-arm64@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.116	info "@esbuild/linux-arm64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.116	info @esbuild/linux-ia32@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.116	info "@esbuild/linux-ia32@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.116	info @esbuild/linux-loong64@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.116	info "@esbuild/linux-loong64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.116	info @esbuild/linux-mips64el@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.117	info "@esbuild/linux-mips64el@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.117	info @esbuild/linux-ppc64@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.117	info "@esbuild/linux-ppc64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.117	info @esbuild/linux-riscv64@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.117	info "@esbuild/linux-riscv64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.117	info @esbuild/linux-s390x@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.117	info "@esbuild/linux-s390x@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.118	info @esbuild/netbsd-x64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.118	info "@esbuild/netbsd-x64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.118	info @esbuild/openbsd-x64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.118	info "@esbuild/openbsd-x64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.118	info @esbuild/sunos-x64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.118	info "@esbuild/sunos-x64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.118	info @esbuild/win32-arm64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.119	info "@esbuild/win32-arm64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.119	info @esbuild/win32-arm64@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.119	info @esbuild/win32-ia32@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.119	info "@esbuild/win32-ia32@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.119	info @esbuild/win32-ia32@0.17.18: The CPU architecture "x64" is incompatible with this module.
18:16:26.119	info @esbuild/win32-x64@0.17.18: The platform "linux" is incompatible with this module.
18:16:26.119	info "@esbuild/win32-x64@0.17.18" is an optional dependency and failed compatibility check. Excluding it from installation.
18:16:26.120	warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
18:16:26.124	[3/4] Linking dependencies...
18:16:26.126	warning " > @headlessui/vue@1.7.13" has unmet peer dependency "vue@^3.2.0".
18:16:26.127	warning " > postcss-custom-properties@13.1.5" has unmet peer dependency "postcss@^8.4".
18:16:26.128	warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > css-loader@5.2.7" has unmet peer dependency "webpack@^4.27.0 || ^5.0.0".
18:16:26.128	warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > postcss-loader@4.3.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
18:16:26.129	warning "daisyui > postcss-js@4.0.1" has unmet peer dependency "postcss@^8.4.21".
18:16:26.129	warning " > @tinymce/tinymce-vue@5.1.0" has unmet peer dependency "vue@^3.0.0".
18:16:26.129	warning " > daisyui@2.51.6" has unmet peer dependency "autoprefixer@^10.0.2".
18:16:26.130	warning " > daisyui@2.51.6" has unmet peer dependency "postcss@^8.1.6".
18:16:26.131	warning "nuxt-icon > @iconify/vue@4.1.1" has unmet peer dependency "vue@>=3".
18:16:26.131	warning " > vue3-lottie@2.7.0" has unmet peer dependency "vue@^3.2".
18:16:26.132	warning " > nuxt@3.4.3" has unmet peer dependency "@types/node@^14.18.0 || >=16.10.0".
18:16:26.135	warning "nuxt-seo-kit > nuxt-schema-org > @unhead/schema-org-vue@0.5.0" has unmet peer dependency "@unhead/vue@>=1.1.9".
18:16:26.135	warning "nuxt-seo-kit > nuxt-unhead > @vueuse/head@1.1.26" has unmet peer dependency "vue@>=2.7 || >=3".
18:16:46.970	[4/4] Building fresh packages...
18:16:48.648	$ nuxt prepare
18:16:48.760	[log] Nuxi 3.4.3
18:16:50.684	[info] [nuxt:tailwindcss] Using default Tailwind CSS file from runtime/tailwind.css
18:16:52.389	[success] Types generated in .nuxt
18:16:52.407	Done in 52.32s.
18:16:52.462	NPM modules installed using Yarn
18:16:52.780	Installing Hugo 0.54.0
18:16:53.453	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
18:16:53.457	Started restoring cached go cache
18:16:53.471	Finished restoring cached go cache
18:16:53.560	go version go1.14.4 linux/amd64
18:16:53.574	go version go1.14.4 linux/amd64
18:16:53.580	Installing missing commands
18:16:53.580	Verify run directory
18:16:53.580	Executing user command: yarn install && yarn run build
18:16:53.827	yarn install v1.22.4
18:16:53.919	[1/4] Resolving packages...
18:16:54.277	success Already up-to-date.
18:16:54.281	$ nuxt prepare
18:16:54.405	[log] Nuxi 3.4.3
18:16:55.846	[info] [nuxt:tailwindcss] Using default Tailwind CSS file from runtime/tailwind.css
18:16:57.244	[success] Types generated in .nuxt
18:16:57.262	Done in 3.44s.
18:16:57.543	yarn run v1.22.4
18:16:57.591	$ nuxt build
18:16:57.712	[log] Nuxi 3.4.3
18:16:57.736	[log] Nuxt 3.4.3 with Nitro 2.3.3
18:16:59.133	[info] [nuxt:tailwindcss] Using default Tailwind CSS file from runtime/tailwind.css
18:17:01.822	[info] Building client...
18:17:01.843	[info] vite v4.3.4 building for production...
18:17:01.925	[info] transforming...
18:17:02.805	
18:17:02.806	🌼 daisyUI components 2.51.6  https://daisyui.com
18:17:02.930	  ✔︎ Including:  base, components, 2 themes, utilities
18:17:02.931	  ❤︎ Support daisyUI:  https://opencollective.com/daisyui 
18:17:02.931	  
18:17:06.436	Use of eval in "node_modules/lottie-web/build/player/lottie.js" is strongly discouraged as it poses security risks and may cause issues with minification.
18:17:08.084	[info] ✓ 210 modules transformed.
18:17:08.630	[info] rendering chunks...
18:17:13.778	[info] computing gzip size...
18:17:13.866	[info] .nuxt/dist/client/manifest.json                        7.53 kB │ gzip:   1.01 kB
18:17:13.866	[info] .nuxt/dist/client/_nuxt/Icon.1086b57f.css              0.07 kB │ gzip:   0.09 kB
18:17:13.867	[info] .nuxt/dist/client/_nuxt/IconCSS.05fd33c5.css           0.26 kB │ gzip:   0.17 kB
18:17:13.867	[info] .nuxt/dist/client/_nuxt/error-500.b63a96f5.css         2.02 kB │ gzip:   0.75 kB
18:17:13.869	[info] .nuxt/dist/client/_nuxt/error-404.8bdbaeb8.css         3.70 kB │ gzip:   1.13 kB
18:17:13.870	[info] .nuxt/dist/client/_nuxt/entry.76c5112b.css            80.39 kB │ gzip:  11.91 kB
18:17:13.871	[info] .nuxt/dist/client/_nuxt/config.cfa1c7c3.js             0.16 kB │ gzip:   0.15 kB
18:17:13.876	[info] .nuxt/dist/client/_nuxt/tworzenie-posta.72acecf9.js    0.17 kB │ gzip:   0.16 kB
18:17:13.876	[info] .nuxt/dist/client/_nuxt/index.91235050.js              0.59 kB │ gzip:   0.43 kB
18:17:13.877	[info] .nuxt/dist/client/_nuxt/blog.79b4620c.js               0.76 kB │ gzip:   0.47 kB
18:17:13.877	[info] .nuxt/dist/client/_nuxt/IconCSS.8d712020.js            0.89 kB │ gzip:   0.53 kB
18:17:13.877	[info] .nuxt/dist/client/_nuxt/error-component.31c7ad1e.js    1.16 kB │ gzip:   0.62 kB
18:17:13.877	[info] .nuxt/dist/client/_nuxt/wszystkie-posty.a24ebccd.js    1.46 kB │ gzip:   0.85 kB
18:17:13.877	[info] .nuxt/dist/client/_nuxt/default.debb4ee3.js            1.53 kB │ gzip:   0.96 kB
18:17:13.877	[info] .nuxt/dist/client/_nuxt/o-mnie.b2aa9198.js             1.85 kB │ gzip:   1.08 kB
18:17:13.877	[info] .nuxt/dist/client/_nuxt/error-500.bd0cbf52.js          1.88 kB │ gzip:   0.98 kB
18:17:13.878	[info] .nuxt/dist/client/_nuxt/error-404.c370ee32.js          2.26 kB │ gzip:   1.16 kB
18:17:13.878	[info] .nuxt/dist/client/_nuxt/login.ab019cfd.js              2.39 kB │ gzip:   1.21 kB
18:17:13.878	[info] .nuxt/dist/client/_nuxt/kontakt.f6adf91c.js            2.67 kB │ gzip:   1.03 kB
18:17:13.878	[info] .nuxt/dist/client/_nuxt/index.58f14034.js              3.99 kB │ gzip:   2.00 kB
18:17:13.878	[info] .nuxt/dist/client/_nuxt/_post_.03c18e21.js             4.13 kB │ gzip:   1.97 kB
18:17:13.878	[info] .nuxt/dist/client/_nuxt/LastedPosts.95e20706.js        4.27 kB │ gzip:   1.88 kB
18:17:13.879	[info] .nuxt/dist/client/_nuxt/nuxt-link.4da3e566.js          4.35 kB │ gzip:   1.81 kB
18:17:13.879	[info] .nuxt/dist/client/_nuxt/panel.2b1c7855.js              4.40 kB │ gzip:   1.85 kB
18:17:13.879	[info] .nuxt/dist/client/_nuxt/index.563aa2c2.js              5.21 kB │ gzip:   2.62 kB
18:17:13.879	[info] .nuxt/dist/client/_nuxt/NewPost.4feef0e9.js            8.68 kB │ gzip:   3.65 kB
18:17:13.879	[info] .nuxt/dist/client/_nuxt/Navbar.2e614ba9.js            10.39 kB │ gzip:   4.34 kB
18:17:13.880	[info] .nuxt/dist/client/_nuxt/Icon.270d4314.js              20.96 kB │ gzip:   7.76 kB
18:17:13.880	[info] .nuxt/dist/client/_nuxt/entry.485fc497.js            831.32 kB │ gzip: 229.80 kB
18:17:13.880	[warn] 
18:17:13.880	(!) Some chunks are larger than 200 kBs after minification. Consider:
18:17:13.880	- Using dynamic import() to code-split the application
18:17:13.880	- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
18:17:13.880	- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
18:17:13.881	[info] ✓ built in 12.04s
18:17:13.881	[success] Client built in 12059ms
18:17:13.883	[info] Building server...
18:17:13.896	[info] vite v4.3.4 building SSR bundle for production...
18:17:13.912	[info] transforming...
18:17:13.913	[info] ✓ 1 modules transformed.
18:17:14.039	[info] rendering chunks...
18:17:14.043	[info] .nuxt/dist/server/server.mjs  0.07 kB │ map: 0.22 kB
18:17:14.044	[info] ✓ built in 146ms
18:17:14.053	[success] Server built in 170ms
18:17:16.141	[success] [nitro] Generated public dist
18:17:16.142	[info] [nitro] Initializing prerenderer
18:17:17.342	[info] [nitro] Prerendering 2 initial routes with crawler
18:17:17.463	[log] [nitro]   ├─ / (118ms)
18:17:17.465	[log] [nitro]   ├─ /robots.txt (1ms)
18:17:17.541	[log] [nitro]   ├─ /__sitemap__/routes.json (0ms)
18:17:17.562	[info] [nitro] Building Nitro Server (preset: `cloudflare-pages`)
18:17:45.889	[success] [nitro] Nitro server built
18:17:46.092	  ├─ dist/__sitemap__/routes.json (107 B) (95 B gzip)
18:17:46.092	  ├─ dist/_nuxt/_post_.03c18e21.js (4.17 kB) (1.97 kB gzip)
18:17:46.093	  ├─ dist/_nuxt/_post_.03c18e21.js.br (1.76 kB) (1.78 kB gzip)
18:17:46.093	  ├─ dist/_nuxt/_post_.03c18e21.js.gz (1.97 kB) (1.99 kB gzip)
18:17:46.093	  ├─ dist/_nuxt/blog.79b4620c.js (755 B) (469 B gzip)
18:17:46.093	  ├─ dist/_nuxt/config.cfa1c7c3.js (164 B) (147 B gzip)
18:17:46.093	  ├─ dist/_nuxt/default.debb4ee3.js (1.58 kB) (957 B gzip)
18:17:46.093	  ├─ dist/_nuxt/default.debb4ee3.js.br (864 B) (887 B gzip)
18:17:46.094	  ├─ dist/_nuxt/default.debb4ee3.js.gz (957 B) (980 B gzip)
18:17:46.094	  ├─ dist/_nuxt/entry.485fc497.js (831 kB) (229 kB gzip)
18:17:46.094	  ├─ dist/_nuxt/entry.485fc497.js.br (194 kB) (194 kB gzip)
18:17:46.094	  ├─ dist/_nuxt/entry.485fc497.js.gz (229 kB) (229 kB gzip)
18:17:46.094	  ├─ dist/_nuxt/entry.76c5112b.css (80.4 kB) (11.9 kB gzip)
18:17:46.094	  ├─ dist/_nuxt/entry.76c5112b.css.br (9.63 kB) (9.55 kB gzip)
18:17:46.094	  ├─ dist/_nuxt/entry.76c5112b.css.gz (11.9 kB) (11.7 kB gzip)
18:17:46.095	  ├─ dist/_nuxt/error-404.8bdbaeb8.css (3.7 kB) (1.13 kB gzip)
18:17:46.095	  ├─ dist/_nuxt/error-404.8bdbaeb8.css.br (967 B) (990 B gzip)
18:17:46.095	  ├─ dist/_nuxt/error-404.8bdbaeb8.css.gz (1.13 kB) (1.15 kB gzip)
18:17:46.095	  ├─ dist/_nuxt/error-404.c370ee32.js (2.26 kB) (1.16 kB gzip)
18:17:46.095	  ├─ dist/_nuxt/error-404.c370ee32.js.br (994 B) (1.02 kB gzip)
18:17:46.095	  ├─ dist/_nuxt/error-404.c370ee32.js.gz (1.16 kB) (1.19 kB gzip)
18:17:46.095	  ├─ dist/_nuxt/error-500.b63a96f5.css (2.02 kB) (751 B gzip)
18:17:46.096	  ├─ dist/_nuxt/error-500.b63a96f5.css.br (644 B) (667 B gzip)
18:17:46.096	  ├─ dist/_nuxt/error-500.b63a96f5.css.gz (751 B) (774 B gzip)
18:17:46.096	  ├─ dist/_nuxt/error-500.bd0cbf52.js (1.88 kB) (984 B gzip)
18:17:46.096	  ├─ dist/_nuxt/error-500.bd0cbf52.js.br (839 B) (862 B gzip)
18:17:46.096	  ├─ dist/_nuxt/error-500.bd0cbf52.js.gz (984 B) (1.01 kB gzip)
18:17:46.096	  ├─ dist/_nuxt/error-component.31c7ad1e.js (1.16 kB) (620 B gzip)
18:17:46.097	  ├─ dist/_nuxt/error-component.31c7ad1e.js.br (527 B) (550 B gzip)
18:17:46.097	  ├─ dist/_nuxt/error-component.31c7ad1e.js.gz (620 B) (643 B gzip)
18:17:46.097	  ├─ dist/_nuxt/Icon.1086b57f.css (67 B) (87 B gzip)
18:17:46.099	  ├─ dist/_nuxt/Icon.270d4314.js (21 kB) (7.76 kB gzip)
18:17:46.099	  ├─ dist/_nuxt/Icon.270d4314.js.br (7.1 kB) (7.13 kB gzip)
18:17:46.099	  ├─ dist/_nuxt/Icon.270d4314.js.gz (7.76 kB) (7.79 kB gzip)
18:17:46.099	  ├─ dist/_nuxt/IconCSS.05fd33c5.css (258 B) (169 B gzip)
18:17:46.099	  ├─ dist/_nuxt/IconCSS.8d712020.js (890 B) (532 B gzip)
18:17:46.099	  ├─ dist/_nuxt/index.563aa2c2.js (5.27 kB) (2.62 kB gzip)
18:17:46.099	  ├─ dist/_nuxt/index.563aa2c2.js.br (2.38 kB) (2.4 kB gzip)
18:17:46.099	  ├─ dist/_nuxt/index.563aa2c2.js.gz (2.62 kB) (2.64 kB gzip)
18:17:46.100	  ├─ dist/_nuxt/index.58f14034.js (4 kB) (2 kB gzip)
18:17:46.100	  ├─ dist/_nuxt/index.58f14034.js.br (1.79 kB) (1.81 kB gzip)
18:17:46.100	  ├─ dist/_nuxt/index.58f14034.js.gz (2 kB) (2.02 kB gzip)
18:17:46.100	  ├─ dist/_nuxt/index.91235050.js (592 B) (434 B gzip)
18:17:46.100	  ├─ dist/_nuxt/kontakt.f6adf91c.js (2.69 kB) (1.03 kB gzip)
18:17:46.100	  ├─ dist/_nuxt/kontakt.f6adf91c.js.br (940 B) (963 B gzip)
18:17:46.100	  ├─ dist/_nuxt/kontakt.f6adf91c.js.gz (1.03 kB) (1.05 kB gzip)
18:17:46.100	  ├─ dist/_nuxt/LastedPosts.95e20706.js (4.27 kB) (1.88 kB gzip)
18:17:46.100	  ├─ dist/_nuxt/LastedPosts.95e20706.js.br (1.69 kB) (1.71 kB gzip)
18:17:46.101	  ├─ dist/_nuxt/LastedPosts.95e20706.js.gz (1.88 kB) (1.9 kB gzip)
18:17:46.101	  ├─ dist/_nuxt/login.ab019cfd.js (2.4 kB) (1.21 kB gzip)
18:17:46.101	  ├─ dist/_nuxt/login.ab019cfd.js.br (1.07 kB) (1.09 kB gzip)
18:17:46.101	  ├─ dist/_nuxt/login.ab019cfd.js.gz (1.21 kB) (1.23 kB gzip)
18:17:46.101	  ├─ dist/_nuxt/Navbar.2e614ba9.js (10.4 kB) (4.34 kB gzip)
18:17:46.102	  ├─ dist/_nuxt/Navbar.2e614ba9.js.br (3.82 kB) (3.84 kB gzip)
18:17:46.102	  ├─ dist/_nuxt/Navbar.2e614ba9.js.gz (4.34 kB) (4.37 kB gzip)
18:17:46.102	  ├─ dist/_nuxt/NewPost.4feef0e9.js (8.69 kB) (3.65 kB gzip)
18:17:46.102	  ├─ dist/_nuxt/NewPost.4feef0e9.js.br (3.2 kB) (3.22 kB gzip)
18:17:46.102	  ├─ dist/_nuxt/NewPost.4feef0e9.js.gz (3.65 kB) (3.67 kB gzip)
18:17:46.102	  ├─ dist/_nuxt/nuxt-link.4da3e566.js (4.35 kB) (1.81 kB gzip)
18:17:46.103	  ├─ dist/_nuxt/nuxt-link.4da3e566.js.br (1.63 kB) (1.65 kB gzip)
18:17:46.103	  ├─ dist/_nuxt/nuxt-link.4da3e566.js.gz (1.81 kB) (1.83 kB gzip)
18:17:46.103	  ├─ dist/_nuxt/o-mnie.b2aa9198.js (1.9 kB) (1.08 kB gzip)
18:17:46.103	  ├─ dist/_nuxt/o-mnie.b2aa9198.js.br (979 B) (1 kB gzip)
18:17:46.103	  ├─ dist/_nuxt/o-mnie.b2aa9198.js.gz (1.08 kB) (1.1 kB gzip)
18:17:46.103	  ├─ dist/_nuxt/panel.2b1c7855.js (4.4 kB) (1.85 kB gzip)
18:17:46.103	  ├─ dist/_nuxt/panel.2b1c7855.js.br (1.64 kB) (1.66 kB gzip)
18:17:46.103	  ├─ dist/_nuxt/panel.2b1c7855.js.gz (1.85 kB) (1.88 kB gzip)
18:17:46.103	  ├─ dist/_nuxt/tworzenie-posta.72acecf9.js (173 B) (159 B gzip)
18:17:46.104	  ├─ dist/_nuxt/wszystkie-posty.a24ebccd.js (1.46 kB) (848 B gzip)
18:17:46.104	  ├─ dist/_nuxt/wszystkie-posty.a24ebccd.js.br (747 B) (770 B gzip)
18:17:46.104	  ├─ dist/_nuxt/wszystkie-posty.a24ebccd.js.gz (848 B) (871 B gzip)
18:17:46.104	  ├─ dist/_worker.js (911 kB) (277 kB gzip)
18:17:46.104	  ├─ dist/android-chrome-192x192.png (15.7 kB) (15.7 kB gzip)
18:17:46.104	  ├─ dist/android-chrome-512x512.png (43.1 kB) (42.5 kB gzip)
18:17:46.104	  ├─ dist/apple-touch-icon.png (14.5 kB) (14.5 kB gzip)
18:17:46.104	  ├─ dist/favicon-16x16.png (945 B) (840 B gzip)
18:17:46.104	  ├─ dist/favicon-32x32.png (1.47 kB) (1.4 kB gzip)
18:17:46.105	  ├─ dist/favicon.ico (1.15 kB) (458 B gzip)
18:17:46.105	  ├─ dist/index.html (3.13 kB) (1.1 kB gzip)
18:17:46.105	  ├─ dist/index.html.br (889 B) (912 B gzip)
18:17:46.105	  ├─ dist/index.html.gz (1.1 kB) (1.12 kB gzip)
18:17:46.105	  ├─ dist/inter-latin-ext-400-normal.woff (44 kB) (43.5 kB gzip)
18:17:46.105	  ├─ dist/inter-latin-ext-700-normal.woff (47.9 kB) (47.6 kB gzip)
18:17:46.106	  ├─ dist/nitro.json (183 B) (151 B gzip)
18:17:46.106	  ├─ dist/robots.txt (56 B) (72 B gzip)
18:17:46.106	  ├─ dist/site.webmanifest (360 B) (187 B gzip)
18:17:46.106	  ├─ dist/svg2png.wasm (1.83 MB) (692 kB gzip)
18:17:46.106	  └─ dist/yoga.wasm (88.7 kB) (28.3 kB gzip)
18:17:46.106	Σ Total size: 4.52 MB (1.96 MB gzip)
18:17:46.106	[success] [nitro] You can preview this build using `npx wrangler pages dev dist/`
18:17:46.106	[success] [nitro] You can deploy this build using `npx wrangler pages publish dist/`
18:17:46.107	[log] [nitro]   ├─ /__sitemap__/routes.json (0ms)
18:17:46.107	[info] [nitro] Scanning routes for broken links... trailingSlashes: `false`
18:17:46.107	[success] [nitro] Looks good! No broken links found.
18:17:46.235	Done in 48.70s.
18:17:46.257	Finished
18:17:46.258	Found _worker.js in output directory. Uploading.
18:17:47.141	✨ Compiled Worker successfully
18:17:47.188	Found _routes.json in output directory. Uploading.
18:17:47.205	Validating asset output directory
18:17:47.810	Deploying your site to Cloudflare's global network...
18:17:51.122	Uploading... (87/88)
18:17:51.708	Uploading... (88/88)
18:17:51.709	✨ Success! Uploaded 1 files (87 already uploaded) (1.00 sec)
18:17:51.709	
18:17:51.978	✨ Upload complete!
18:17:53.679	Success: Assets published!
18:17:55.023	Error: Failed to publish your Function. Got error: Uncaught ReferenceError: __dirname is not defined
  at functionsWorker-0.9946994914616272.js:5989:18
```

**Comment by danielroe** [comment]
Let's track downstream in https://github.com/nuxt/image/issues/602.

**Comment by duncandejong** [comment]
I have the same issue.
