### ISSUE TITLE
Error with calling graphql api in vercel deployment

### ISSUE THREAD

**Issue by Mnigos** [nuxt/nuxt#20709]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v16.13.1
- Nuxt Version:     3.4.2
- Nitro Version:    2.3.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, components, modules, css, build, runtimeConfig, nitro, graphql-client, vite
- Runtime Modules:  @pinia/nuxt@0.4.2, nuxt-windicss@2.5.5, nuxt-graphql-client@0.2.13
- Build Modules:    -
------------------------------

### Reproduction

This is vercel related error so it won't be so easy to reproduce.
Here is link to [repository](https://github.com/Rigtch/rigtch-music-www) where I'm struggling with this error.

### Describe the bug

In development environment (this one I gave info about above) everything works fine, requests goes thought without any errors, but on vercel deployment there is several errors. I've submitted a ticket in Vercel Support, they answered me, and here is an response.
<img width="1543" alt="Screenshot 2023-05-06 at 20 19 35" src="https://user-images.githubusercontent.com/56691628/236640599-ecfa4576-45fe-4753-be3e-0feabc2701cc.png">

### Vercel errors
<img width="372" alt="Screenshot 2023-04-21 at 12 19 59" src="https://user-images.githubusercontent.com/56691628/236640707-3fc13177-f27e-4c57-b1ff-d0ae1628dfac.png">
<img width="1376" alt="Screenshot 2023-04-21 at 12 20 48" src="https://user-images.githubusercontent.com/56691628/236640708-431f5f28-614a-4bf6-b962-a74924b2cbf1.png">

### My environment (no errors)
<img width="544" alt="Screenshot 2023-04-21 at 12 23 43" src="https://user-images.githubusercontent.com/56691628/236640710-ece2410e-a194-47c3-80bf-f54cd73511dc.png">
<img width="545" alt="Screenshot 2023-04-21 at 12 23 52" src="https://user-images.githubusercontent.com/56691628/236640712-bf25808d-a56c-47bb-8475-67fdee51f81b.png">

### Additional context

related to: https://github.com/unjs/nitro/issues/1084

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
  at (index.mjs:1:52671)  
  at (index.mjs:1:58642)  
  at (index.mjs:1:89318)  
  at (index.mjs:1:91461)  
  at (index.mjs:1:142191)  
  at (index.mjs:1:97937)  
  at (index.mjs:1:99154)  
  at (index.mjs:1:146590)  
  at (index.mjs:1:148383)
```
```
 Error: 
    at (index.mjs:1:743101)
    at (index.mjs:1:751999) {
  type: 4,
  from: {
  fullPath: '/',
  path: '/',
  query: {},
  hash: '',
  name: 'index',
  params: {},
  matched: [
  {
  path: '/',
  redirect: undefined,
  name: 'index',
  meta: { middleware: 'auth' },
  aliasOf: undefined,
  beforeEnter: undefined,
  props: { default: false },
  children: [],
  instances: {},
  leaveGuards: Set(0) {},
  updateGuards: Set(0) {},
  enterCallbacks: {},
  components: {
  default: { __name: 'index', __ssrInlineRender: true, setup: [Function] }
}
}
],
  meta: { middleware: 'auth' },
  redirectedFrom: undefined,
  href: '/'
},
  to: {
  fullPath: '/about',
  hash: '',
  query: {},
  name: 'about',
  path: '/about',
  params: {},
  matched: [
  {
  path: '/about',
  redirect: undefined,
  name: 'about',
  meta: {},
  aliasOf: undefined,
  beforeEnter: undefined,
  props: { default: false },
  children: [],
  instances: {},
  leaveGuards: Set(0) {},
  updateGuards: Set(0) {},
  enterCallbacks: {},
  components: { default: [Function: component] }
}
],
  meta: {},
  redirectedFrom: {
  fullPath: '/',
  hash: '',
  query: {},
  name: 'index',
  path: '/',
  params: {},
  matched: [
  {
  path: '/',
  redirect: undefined,
  name: 'index',
  meta: { middleware: 'auth' },
  aliasOf: undefined,
  beforeEnter: undefined,
  props: { default: false },
  children: [],
  instances: {},
  leaveGuards: Set(0) {},
  updateGuards: Set(0) {},
  enterCallbacks: {},
  components: {
  default: { __name: 'index', __ssrInlineRender: true, setup: [Function] }
}
}
],
  meta: { middleware: 'auth' },
  redirectedFrom: undefined,
  href: '/'
},
  href: '/about'
},
  [Symbol()]: true
}
```
```

**Comment by so1ve** [comment]
related to unjs/h3#381 actually

**Comment by danielroe** [comment]
closing as stale - nuxt-graphql-client and h3 have both moved on substantially since. if you can still reproduce on the latest nuxt, please open a fresh issue with a minimal repro. 🙏
