### ISSUE TITLE
Cannot set properties of undefined (setting 'default')       

### ISSUE THREAD

**Issue by DevArtemNuss** [nuxt/nuxt#20818]
### Environment

Nuxi 3.4.3  Node Version 16.10.0
---- NUXT CONFIG ----
```ts
export default defineNuxtConfig({
  modules: ['@pinia/nuxt', '@nuxt/ui'],
  ssr: false,
  router: {
    middleware: ['layout'],
  },
  layouts: {
    // Specify the default layout for all pages
    default: '~/layouts/default.vue',
  },
  runtimeConfig: {
    // The private keys which are only available within server-side
    apiSecret: '123',
    // Keys within public, will be also exposed to the client-side
    public: {
    },
  },
  pinia: {
    autoImports: [
      // automatically imports `defineStore`
      'defineStore', // import { defineStore } from 'pinia'
      ['defineStore', 'definePiniaStore'], // import { defineStore as definePiniaStore } from 'pinia'
    ],
  },
  components: {
    path: '~/components',
    extensions: ['.vue'],
    pathPrefix: false,
    global: true,
  },
  vite: {
    css: {
      preprocessorOptions: {
        scss: {
          additionalData: '@import "@/assets/styles/main.scss";',
        },
      },
    },
  },
  publicRuntimeConfig: {
    apiURL: process.env.NUXT_API || '',
  },
  buildModules: [
    // Simple usage
    '@nuxtjs/dotenv',
  ],
  plugins: [{ src: './alert.plugin' }]
});
```
---- package.json-----
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/ui": "^0.3.3",
    "nuxt": "^3.2.3",
    "postcss": "^8.4.21",
    "prettier": "2.8.4",
    "sass": "^1.58.3",
    "sass-loader": "^13.2.0",
    "tailwindcss": "^3.2.7"
  },
  "dependencies": {
    "@coinbase/wallet-sdk": "^3.6.4",
    "@gnosis.pm/safe-apps-provider": "^0.15.1",
    "@gnosis.pm/safe-apps-sdk": "^7.8.0",
    "@mobiscroll/javascript": "^5.22.2",
    "@nuxt/kit": "^3.4.3",
    "@nuxtjs/dotenv": "^1.4.1",
    "@pinia/nuxt": "^0.4.7",
    "@vueform/multiselect": "^2.6.1",
    "@vuepic/vue-datepicker": "^5.0.1",
    "@vueup/vue-quill": "^1.1.1",
    "@walletconnect/ethereum-provider": "^2.7.2",
    "@walletconnect/web3-provider": "^1.8.0",
    "axios": "^1.3.4",
    "chart.js": "^3.9.1",
    "element-plus": "^2.3.4",
    "ethers": "^5.6.9",
    "flowbite": "^1.6.3",
    "nuxt3": "^3.5.0-28064087.90ab1b50",
    "pinia": "^2.0.33",
    "quill": "^1.3.7",
    "vee-validate": "^4.7.4",
    "vue": "^3.3.2",
    "vue-chart-3": "^3.1.8",
    "vue-dapp": "^0.7.2",
    "vue-demi": "^0.13.11",
    "vue-icomoon": "^0.6.1"
  }
}
```

### Reproduction

After npm i get this error
> npm i 
> postinstall
> nuxt prepare

Nuxi 3.4.3                                                                                                                                                    7:13:04 PM

 ERROR  Cannot set properties of undefined (setting 'default')                                                                                                7:13:39 PM

  at build (node_modules/nuxt3/dist/index.mjs:3210:21)
  at buildNuxt (node_modules/@nuxt/kit/dist/index.mjs:563:12)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:39:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)

### Describe the bug

After the update, I can't start the procester and reinstall node-modules, started getting an error.

### Logs

```shell-script
> postinstall
> nuxt prepare

Nuxi 3.4.3                                                                                                                                                    7:13:04 PM

 ERROR  Cannot set properties of undefined (setting 'default')                                                                                                7:13:39 PM

  at build (node_modules/nuxt3/dist/index.mjs:3210:21)
  at buildNuxt (node_modules/@nuxt/kit/dist/index.mjs:563:12)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:39:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:48:20)

npm ERR! code 1
npm ERR! path /Users/artem/WebstormProjects/talentum_talents_front_end
npm ERR! command failed
npm ERR! command sh -c nuxt prepare

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/artem/.npm/_logs/2023-05-12T17_13_39_562Z-debug.log
```

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by DevArtemNuss** [comment]
@danielroe https://stackblitz.com/edit/github-58irit?file=package.json

**Comment by DevArtemNuss** [comment]
> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
https://stackblitz.com/edit/github-58irit?file=package.json

**Comment by danielroe** [comment]
I suspect that the issue is that you should not have both `nuxt3` and `nuxt` installed (nuxt3 is an edge channel release - see https://nuxt.com/docs/guide/going-further/edge-channel for more info on how to switch to the edge channel).

Also:

1. `buildModules` is no longer used in Nuxt 3.
2. `@nuxtjs/dotenv` is a Nuxt 2 module
