### ISSUE TITLE
500 named export not found during production

### ISSUE THREAD

**Issue by bitbytebit1** [nuxt/nuxt#21006]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.16.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      runtimeConfig
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-9ukebr-dnchhg

### Describe the bug

Importing a named export works fine during development but breaks when visiting the route directly.

Steps to reproduce:

1. Download the reproduction
2. Build for production
3. Start the server
4. Click "map" (page loads fine)
5. Refresh the page
6. Error!

### Logs

```shell-script
Listening http://[::]:3000
[Vue Router warn]: uncaught error during route navigation:
file:///REDACTED/.output/server/chunks/app/_nuxt/map-73d7f254.mjs:1
import { MarkerClusterer } from '@googlemaps/markerclusterer';
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'MarkerClusterer' not found. The requested module '@googlemaps/markerclusterer' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@googlemaps/markerclusterer';
const { MarkerClusterer } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async Object.setup (file:///REDACTED/.output/server/chunks/app/server.mjs:620:76)
    at async Object.callAsync (file:///REDACTED/.output/server/node_modules/unctx/dist/index.mjs:72:16)
    at async applyPlugin (file:///REDACTED/.output/server/chunks/app/server.mjs:123:33)
    at async applyPlugins (file:///REDACTED/.output/server/chunks/app/server.mjs:139:7)
    at async createNuxtAppServer (file:///REDACTED/.output/server/chunks/app/server.mjs:960:7)
    at async Object.renderToString (file:///REDACTED/.output/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
```

**Comment by danielroe** [comment]
You can try adding it to your `build.transpile` for now, or importing the default export. The issue is that the package doesn't expose a valid ESM export.

**Comment by bitbytebit1** [comment]
Thanks for the quick response @danielroe, I did try importing the default export but that results in a similar error. Transpiling resolved the issue for me. If I understand correctly the fix for the upstream package would be to add type: "module" in their package.json or to set the "module" file to end in ".mjs"?

**Comment by danielroe** [comment]
Yes. But `module` is actually non-standard; ideally they should also have an `exports` field with conditional `import`/`require`/`types` fields.
