### ISSUE TITLE
Netlify build stage fails when using `netlify-edge` preset

### ISSUE THREAD

**Issue by dosstx** [nuxt/nuxt#21049]
### Environment

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v16.19.0
- Nuxt Version:     3.5.1
- Nitro Version:    2.4.1
- Package Manager:  npm@9.6.5
- Builder:          vite
- User Config:      nitro, runtimeConfig, app, modules, content, image
- Runtime Modules:  @nuxt/content@2.6.0, @nuxtjs/tailwindcss@6.7.0, @nuxt/image-edge@1.0.0-28059208.2abef1b, @vueuse/nuxt@10.1.2, @nuxtjs/html-validator@1.3.1    
- Build Modules:    -
----------------------------------
```

### Reproduction

```
export default defineNuxtConfig({
	nitro: {
		preset: 'netlify-edge'
	},
```

### Describe the bug

Followed the Netlify nitro preset doc

### Additional context

**ChatGPT says this about the error (but data cutoff date was September 2021, so not sure anything more recent is known):**

The error message you provided indicates that there's a problem with the use of `__dirname` in your server.js file:

```
11:11:56 AM: ReferenceError: __dirname is not defined
11:11:56 AM:     at file:///opt/build/repo/.netlify/edge-functions/server/server.js:1:1128946
```

The `__dirname` is a global object in Node.js which gives the directory name of the current module. However, when the code is being transpiled for the browser or in some bundling scenarios, `__dirname` may not be available.

The problem is often encountered when building projects for serverless environments, like Netlify Edge Functions. 

Since `__dirname` is specific to Node.js and not a part of JavaScript's standard global objects, it's not defined in the ECMAScript module (ESM) context. Netlify Edge Functions require ESM syntax, and it seems like the Nuxt Nitro preset for Netlify Edge (`netlify-edge`) is trying to use `__dirname` in an ESM context, causing the error.

Here's a workaround you might want to try:

1. Create a `netlify.toml` file in the root of your project if you haven't already. This file is used to configure your Netlify build.

2. Add the following configuration to the file:
    ```
    [functions]
      node_bundler = "esbuild"
      node_sourcemap = "yes"
    ```

**I did the above solution and it did not help.**

### Logs

```shell-script
The following build log is shown during the fail:

11:32:31 AM: Packaging Edge Functions from .netlify/edge-functions directory:
11:32:31 AM:  - server
11:32:33 AM: ReferenceError: __dirname is not defined
11:32:33 AM:     at file:///opt/build/repo/.netlify/edge-functions/server/server.js:1:1128946
11:32:33 AM: ​
11:32:33 AM: Bundling of edge function failed                              
11:32:33 AM: ────────────────────────────────────────────────────────────────
11:32:33 AM: ​
11:32:33 AM:   Error message
11:32:33 AM:   Could not load edge function at '/opt/build/repo/.netlify/edge-functions/server/server.js'. More on the Edge Functions API at https://ntl.fyi/edge-api.
11:32:33 AM: ​
11:32:33 AM:   Error location
11:32:33 AM:   While bundling edge function
11:32:33 AM: ​
11:32:33 AM:   Resolved config
11:32:33 AM:   build:
11:32:33 AM:     command: npm run build
11:32:33 AM:     commandOrigin: ui
11:32:33 AM:     environment:
11:32:33 AM:       - NUXT_OPENAI_API_KEY
11:32:33 AM:     publish: /opt/build/repo/dist
11:32:33 AM:     publishOrigin: ui
11:32:34 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
11:32:34 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:32:34 AM: Failing build: Failed to build site
11:32:34 AM: Finished processing build request in 1m16.367s
```

**Comment by dosstx** [comment]
I made a minimal repro and it worked for that test. I'll have to check and see why it doesnt' with my production version. Thanks for the willingness to look into this, but we can close this for now.
