### ISSUE TITLE
Error when customize vite `manualChunks`

### ISSUE THREAD

**Issue by xtoolkit** [nuxt/nuxt#21354]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.17.1
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://codesandbox.io/p/github/xtoolkit/nuxt-cssModule-problem/manualChunks

### Describe the bug

If we customize vite `manualChunks`, nuxt error!

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] Cannot access '_export_sfc' before initialization
  at ./server/chunks/app/server.mjs:35:46  
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:533:24)  
  at async ./server/chunks/handlers/renderer.mjs:78:24  
  at async ./server/chunks/handlers/renderer.mjs:157:64  
  at async ./server/chunks/handlers/renderer.mjs:33:22  
  at async Object.handler (./server/node_modules/h3/dist/index.mjs:1255:19)  
  at async Server.toNodeHandle (./server/node_modules/h3/dist/index.mjs:1330:7)
[nuxt] [request error] [unhandled] [500] Cannot access '_export_sfc' before initialization
  at ./server/chunks/app/server.mjs:35:46  
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:533:24)  
  at async ./server/chunks/handlers/renderer.mjs:78:24  
  at async ./server/chunks/handlers/renderer.mjs:157:64  
  at async ./server/chunks/handlers/renderer.mjs:33:22  
  at async Object.handler (./server/node_modules/h3/dist/index.mjs:1255:19)  
  at async Server.toNodeHandle (./server/node_modules/h3/dist/index.mjs:1330:7)
```

**Comment by manniL** [comment]
(Can reproduce with latest nuxt version)

**Comment by xtoolkit** [comment]
Hi
New reproduction:
[github](https://github.com/xtoolkit/nuxt-cssModule-problem/tree/manualChunks)
[codesandbox](https://codesandbox.io/p/github/xtoolkit/nuxt-cssModule-problem/manualChunks-latest)

**Comment by codeblockhead** [comment]
<img width="613" alt="image" src="https://github.com/nuxt/nuxt/assets/66559869/fd1820bd-231e-4544-919f-df1c08d182db">



I have also encountered the same problem. I want to optimize my packaging because nuxt packaging generates too many JavaScript files. I want to merge the JavaScript files, but when I configured "manualChunks", I found that the order of introducing JavaScript in the HTML file generated after packaging is incorrect, resulting in an error

The components.js file must be placed after vant.js because there are components that reference vant
![image](https://github.com/nuxt/nuxt/assets/66559869/14b57b75-ef98-45f0-957a-447995e4af95)

**Comment by Joebayld** [comment]
> <img alt="image" width="613" src="https://private-user-images.githubusercontent.com/66559869/331477411-fd1820bd-231e-4544-919f-df1c08d182db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDYzMzAsIm5iZiI6MTcyMjc0NjAzMCwicGF0aCI6Ii82NjU1OTg2OS8zMzE0Nzc0MTEtZmQxODIwYmQtMjMxZS00NTQ0LTkxOWYtZGYxYzA4ZDE4MmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA0MzM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMjc5OTE2YzVmOWNmMTIxMmFlYzkzNThjNmE4MGIwNjMyN2I4MDQ4NDgzOGFmOTgwYWE3YWY0ZjFjODA5YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IGwBosgbhlByjOjPdpHl7k4CwNqyX5gQ-JJfEMEG0Ls">
> I have also encountered the same problem. I want to optimize my packaging because nuxt packaging generates too many JavaScript files. I want to merge the JavaScript files, but when I configured "manualChunks", I found that the order of introducing JavaScript in the HTML file generated after packaging is incorrect, resulting in an error
> 
> The components.js file must be placed after vant.js because there are components that reference vant ![image](https://private-user-images.githubusercontent.com/66559869/331479685-14b57b75-ef98-45f0-957a-447995e4af95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NDYzMzAsIm5iZiI6MTcyMjc0NjAzMCwicGF0aCI6Ii82NjU1OTg2OS8zMzE0Nzk2ODUtMTRiNTdiNzUtZWY5OC00NWYwLTk1N2EtNDQ3OTk1ZTRhZjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA0MzM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZGMyNWU1ZDM0NGE0OTZkMjE5YmE3MGQ3ZmFkMTg5NmVmZjhkMDk0ZWM3OWZlNmFmNWNiNzMzMDJjOWVkOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gdK9_iL1-XyJSxRlCyCZQfgWsJMzEEU-EfJsvLG0iKg)

Have you found any fix for this? I used to use the now deprecated `splitVendorChunkPlugin`. With the plugin, everything worked with custom chunks. Now I have the same error.

**Comment by psy21d** [comment]
How to REDUCE chunks count?!

**Comment by hevans90** [comment]
This is a huge problem that prevents optimising builds, and should get more attention.

**Comment by aiqin-bao** [comment]
me too, unable to merge some expected files

**Comment by alkin** [comment]
This worked for me: https://github.com/nuxt/nuxt/issues/22127#issuecomment-1635925362
