### ISSUE TITLE
SSR fails on `useFetch` while `getServerSession` from `nuxt-auth` is called twice or more

### ISSUE THREAD

**Issue by KitsuneKenshi** [nuxt/nuxt#21362]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.5.1
- Builder:          vite
- User Config:      modules, auth
- Runtime Modules:  @sidebase/nuxt-auth@0.6.0-beta.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-cudppu 
- Go to /fails and refresh page

### Describe the bug

Using two or more `getServerSession` from `nuxt-auth` causes errors 500 with `useFetch`.
While using $fetch or directly going to the endpoint, this error does not occur. 
The issue does not occur on SPA mode, but only on SSR. 
From looking at logs, it looks like there's a problem with usage of `devalue` library.
EDIT:
After some investigation I figured out it's an issue with one of values being Blob.

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] Cannot stringify arbitrary non-POJOs                                                                                                                                        
  at flatten (/<PATH>/node_modules/.pnpm/devalue@4.3.2/node_modules/devalue/src/stringify.js:138:13)
  at flatten (/<PATH>/node_modules/.pnpm/devalue@4.3.2/node_modules/devalue/src/stringify.js:166:43)
  at flatten (/<PATH>/node_modules/.pnpm/devalue@4.3.2/node_modules/devalue/src/stringify.js:166:43)
  at flatten (/<PATH>/node_modules/.pnpm/devalue@4.3.2/node_modules/devalue/src/stringify.js:60:39)
  at stringify (/<PATH>/node_modules/.pnpm/devalue@4.3.2/node_modules/devalue/src/stringify.js:178:16)
  at renderPayloadJsonScript (/<PATH>/.nuxt/dev/index.mjs:4942:32)
  at /<PATH>/.nuxt/dev/index.mjs:4866:29
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async /<PATH>/.nuxt/dev/index.mjs:665:22
  at async Object.handler (/<PATH>/node_modules/.pnpm/h3@1.6.6/node_modules/h3/dist/index.mjs:1255:19)
```

**Comment by danielroe** [comment]
If you want to serialize blobs, you can do this with custom serializer/reviver functions: https://nuxt.com/docs/api/composables/use-nuxt-app#payload. But I would suggest you probably do not want to do this and should not directly return the entire session.
