### ISSUE TITLE
Component "default" in record with path "/" is not a valid component. - Invalid Route Component

### ISSUE THREAD

**Issue by SomethingNew71** [nuxt/nuxt#21366]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.2`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.6.7`
- Builder:          `vite`
- User Config:      `ssr`, `head`, `loading`, `css`, `plugins`, `modules`, `robots`, `serverMiddleware`, `build`, `runtimeConfig`
- Runtime Modules:  `@nuxtjs/robots@3.0.0`
- Build Modules:    `-`

### Reproduction

1. Go to my repo: https://github.com/SomethingNew71/classicminidiy/tree/dev
2. `npm ci` and then try to run the app `npm run dev`
3. After compile attempt to navigate to localhost
4. Observe route error

### Describe the bug

I am in the process of migrating from nuxt-bridge to nuxt3 and working through the bugs I am encountering. I am now at the stage where I am trying to get the code running in any state locally. I have encountered this error with the router and cannot seem to pinpoint why its occuring. Here are screenshots of the error and the folder structure of my app. 

<img width="1128" alt="Screenshot 2023-06-04 at 8 22 36 PM" src="https://github.com/nuxt/nuxt/assets/4572799/cfbaab22-e33c-4482-8c19-4cd825d60032">
<img width="1181" alt="Screenshot 2023-06-04 at 8 22 07 PM" src="https://github.com/nuxt/nuxt/assets/4572799/16f8c506-069f-484e-8c93-0847cf8c5ad8">
<img width="437" alt="Screenshot 2023-06-04 at 8 21 54 PM" src="https://github.com/nuxt/nuxt/assets/4572799/a814a13d-3b4f-41eb-8fac-7bbc41ab573b">

### Additional context

https://github.com/SomethingNew71/classicminidiy/tree/dev

### Logs

```shell-script
✔ Vite server hmr 25 files in 2026.819ms                                                                                                                               8:20:26 PM
[Vue Router warn]: Component "default" in record with path "/" is not a valid component. Received "/Users/colegentry/Development/classicminidiy/pages/index.vue".      8:20:26 PM
[Vue Router warn]: Component "default" in record with path "/" is not a valid component. Received "/Users/colegentry/Development/classicminidiy/pages/index.vue".      8:20:26 PM
[Vue Router warn]: uncaught error during route navigation:                                                                                                             8:20:26 PM
Error: Invalid route component                                                                                                                                         8:20:26 PM
    at extractComponentsGuards (file:///Users/colegentry/Development/classicminidiy/node_modules/vue-router/dist/vue-router.mjs:2065:27)
    at file:///Users/colegentry/Development/classicminidiy/node_modules/vue-router/dist/vue-router.mjs:3303:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.setup (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/pages/runtime/plugins/router.js:94:96)
    at async Object.callAsync (file:///Users/colegentry/Development/classicminidiy/node_modules/unctx/dist/index.mjs:72:16)
    at async applyPlugin (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/nuxt.js:111:23)
    at async Module.applyPlugins (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/nuxt.js:127:7)
    at async createNuxtAppServer (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/entry.js:29:7)
    at async default (file:///Users/colegentry/Development/classicminidiy/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:18)
    at async Object.renderToString (file:///Users/colegentry/Development/classicminidiy/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
[Vue Router warn]: uncaught error during route navigation:                                                                                                             8:20:26 PM
Error: Invalid route component                                                                                                                                         8:20:26 PM
    at extractComponentsGuards (file:///Users/colegentry/Development/classicminidiy/node_modules/vue-router/dist/vue-router.mjs:2065:27)
    at file:///Users/colegentry/Development/classicminidiy/node_modules/vue-router/dist/vue-router.mjs:3303:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.setup (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/pages/runtime/plugins/router.js:94:96)
    at async Object.callAsync (file:///Users/colegentry/Development/classicminidiy/node_modules/unctx/dist/index.mjs:72:16)
    at async applyPlugin (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/nuxt.js:111:23)
    at async Module.applyPlugins (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/nuxt.js:127:7)
    at async createNuxtAppServer (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/entry.js:29:7)
    at async default (file:///Users/colegentry/Development/classicminidiy/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:18)
    at async Object.renderToString (file:///Users/colegentry/Development/classicminidiy/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
[Vue Router warn]: Component "default" in record with path "/" is not a valid component. Received "/Users/colegentry/Development/classicminidiy/pages/index.vue".      8:20:26 PM
[Vue Router warn]: uncaught error during route navigation:                                                                                                             8:20:26 PM
Error: Invalid route component                                                                                                                                         8:20:26 PM
    at extractComponentsGuards (file:///Users/colegentry/Development/classicminidiy/node_modules/vue-router/dist/vue-router.mjs:2065:27)
    at file:///Users/colegentry/Development/classicminidiy/node_modules/vue-router/dist/vue-router.mjs:3303:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.setup (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/pages/runtime/plugins/router.js:94:96)
    at async Object.callAsync (file:///Users/colegentry/Development/classicminidiy/node_modules/unctx/dist/index.mjs:72:16)
    at async applyPlugin (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/nuxt.js:111:23)
    at async Module.applyPlugins (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/nuxt.js:127:7)
    at async createNuxtAppServer (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/entry.js:29:7)
    at async default (file:///Users/colegentry/Development/classicminidiy/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:18)
    at async Object.renderToString (file:///Users/colegentry/Development/classicminidiy/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
[Vue Router warn]: Component "default" in record with path "/" is not a valid component. Received "/Users/colegentry/Development/classicminidiy/pages/index.vue".      8:20:26 PM
[Vue Router warn]: uncaught error during route navigation:                                                                                                             8:20:26 PM
Error: Invalid route component                                                                                                                                         8:20:26 PM
    at extractComponentsGuards (file:///Users/colegentry/Development/classicminidiy/node_modules/vue-router/dist/vue-router.mjs:2065:27)
    at file:///Users/colegentry/Development/classicminidiy/node_modules/vue-router/dist/vue-router.mjs:3303:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.setup (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/pages/runtime/plugins/router.js:94:96)
    at async Object.callAsync (file:///Users/colegentry/Development/classicminidiy/node_modules/unctx/dist/index.mjs:72:16)
    at async applyPlugin (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/nuxt.js:111:23)
    at async Module.applyPlugins (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/nuxt.js:127:7)
    at async createNuxtAppServer (/Users/colegentry/Development/classicminidiy/node_modules/nuxt/dist/app/entry.js:29:7)
    at async default (file:///Users/colegentry/Development/classicminidiy/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:18)
    at async Object.renderToString (file:///Users/colegentry/Development/classicminidiy/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
```
```

**Comment by SomethingNew71** [comment]
This has been resolved. It was a build error related to imports and pathing but it wasnt elevating the error in npm run dev. I found it by running npm run build.
