### ISSUE TITLE
Nuxt 3.5.3  ERROR  "renderJsonPayloads" is not exported

### ISSUE THREAD

**Issue by adnseek** [nuxt/nuxt#21419]
### Environment

Hi Nuxt Team,

I try to deploy Nuxt 3.5.3, but it complains that renderJsonPayloads is not exported by nuxt config.

could you tell me how to fix this ?

Nuxt imported by "node_modules/nuxt/dist/app/composables/payload.js".
file: /home/forge/domain/node_modules/nuxt/dist/app/composables/payload.js:6:9
4: import { getCurrentInstance } from "vue";
5: import { useNuxtApp, useRuntimeConfig } from "../nuxt.js";
6: import { renderJsonPayloads } from "#build/nuxt.config.mjs";
            ^
7: export function loadPayload(url, opts = {}) {
8:   if (process.server) {

[8:12:21 PM]  ERROR  "renderJsonPayloads" is not exported by "virtual:nuxt:/home/forge/domain/.nuxt/nuxt.config.mjs", imported by "node_modules/nuxt/dist/app/composables/payload.js".

Thanks a lot 

Adrian

### Reproduction

upgrade to 3.5.3
yarn build

### Describe the bug

renderJsonPayloads not exported from nuxt.config.ts

### Additional context

none

### Logs

```shell-script
Nuxi 3.5.3                                                                                                                               8:33:26 PM
Nuxt 3.5.3 with Nitro 2.4.1                                                                                                              8:33:26 PM
ℹ Building client...                                                                                                                       20:33:30
ℹ vite v4.1.5 building for production...                                                                                                   20:33:30
ℹ ✓ 858 modules transformed.                                                                                                               20:33:47

 ERROR  "renderJsonPayloads" is not exported by "virtual:nuxt:/home/forge/www.domain.net/.nuxt/nuxt.config.mjs", imported by "node_modules/nuxt/dist/app/composables/payload.js".
file: /home/forge/www.domain.net/node_modules/nuxt/dist/app/composables/payload.js:6:9
4: import { getCurrentInstance } from "vue";
5: import { useNuxtApp, useRuntimeConfig } from "../nuxt.js";
6: import { renderJsonPayloads } from "#build/nuxt.config.mjs";
            ^
7: export function loadPayload(url, opts = {}) {
8:   if (process.server) {


[8:33:47 PM]  ERROR  "renderJsonPayloads" is not exported by "virtual:nuxt:/home/forge/www.domain.net/.nuxt/nuxt.config.mjs", imported by "node_modules/nuxt/dist/app/composables/payload.js".

  at error (/home/forge/node_modules/rollup/dist/es/shared/node-entry.js:2130:30)
  at Module.error (/home/forge/node_modules/rollup/dist/es/shared/node-entry.js:13469:16)
  at Module.traceVariable (/home/forge/node_modules/rollup/dist/es/shared/node-entry.js:13890:29)
  at ModuleScope.findVariable (/home/forge/node_modules/rollup/dist/es/shared/node-entry.js:12435:39)
  at Identifier.bind (/home/forge/node_modules/rollup/dist/es/shared/node-entry.js:8133:40)
  at ConditionalExpression.bind (/home/forge/node_modules/rollup/dist/es/shared/node-entry.js:5744:23)
  at VariableDeclarator.bind (/home/forge/node_modules/rollup/dist/es/shared/node-entry.js:5744:23)
  at VariableDeclaration.bind (/home/forge/node_modules/rollup/dist/es/shared/node-entry.js:5740:28)
  at Program.bind (/home/forge/node_modules/rollup/dist/es/shared/node-entry.js:5740:28)
  at Module.bindReferences (/home/forge/node_modules/rollup/dist/es/shared/node-entry.js:13465:18)
```

**Comment by adnseek** [comment]
my bad. wrong server configuration

**Comment by yulafezmesi** [comment]
wondering, what was the issue? @adnseek

**Comment by oemer-aran** [comment]
I also wonder what the solution for you was. I have the same error with a local yarn workspace package.
I did this in my `nuxt.config.ts`:
```
vite: {
  optimizeDeps: {
      include: ["@workspace/my-custom-package"],
    },
}
```

It fixed the error for development, but it still occurs when I try to build the app.

**Comment by snitovets** [comment]
@oemer-aran Do you managed to found solution?

**Comment by gabrielsantamariab** [comment]
@adnseek What was the problem? Thanks!
