### ISSUE TITLE
npm run generate stopped generating index.html

### ISSUE THREAD

**Issue by Timtendo12** [nuxt/nuxt#21437]
### Environment

------------------------------
- Operating System: `Windows_NT` (11)
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.3.2`
- Nitro Version:    `2.3.2`
- Package Manager:  `npm@6.14.17`
- Builder:          `vite`
- User Config:      `pages`, `ssr`, `debug`, `dev`, `modules`, `pwa`, `app`, `vue`, `ignore`
- Runtime Modules:  `@nuxt/devtools@0.2.5`, `@vite-pwa/nuxt@0.0.5`
- Build Modules:    `-`
------------------------------

### Reproduction

project is pretty big and huge parts of code may not be shared, not sure how to create a reproduction.

### Describe the bug

Since yesterday when running npm run generate, nuxt will no longer generate a index.html. We need this file as we use azure static web apps as our hosting.

### Additional context

iirc. It might have happened after we started using cookies and layouts. However im not sure if this is the main reason of why it wont generate a index.html

### Logs

```shell-script
https://hastebin.com/share/aweyukuser.less

npm run generate logs
```

**Comment by danielroe** [comment]
Is it possible that there is an error or a redirection (for example, from your new cookie approach) when generating this file?

**Comment by Timtendo12** [comment]
> Is it possible that there is an error or a redirection (for example, from your new cookie approach) when generating this file?

I do have a redirection in my middleware back to the login page if 2 cookies are not set

**Comment by Timtendo12** [comment]
but I have that piece of code put in a (if process.client) block

**Comment by Timtendo12** [comment]
I rechecked and I do have an error, I removed and ignore it since I usually get errors when generating. It never broke the site.

The error is:

```
 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'user')                                                                                                                                                                                                 14:15:14  
  at _sfc_ssrRender (C:\path\to\code/.nuxt/prerender/chunks/main-ff398750.mjs:69:16)
  at renderComponentSubTree (C:\path\to\code\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:447:17)
  at renderComponentVNode (C:\path\to\code\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:381:16)
  at renderVNode (C:\path\to\code\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:492:22)
  at renderComponentSubTree (C:\path\to\code\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:456:13)
  at C:\path\to\code\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:378:29
  at async unrollBuffer$1 (C:\path\to\code\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:602:24)
  at async unrollBuffer$1 (C:\path\to\code\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:608:24)
  at async unrollBuffer$1 (C:\path\to\code\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:608:24)
  at async unrollBuffer$1 (C:\path\to\code\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:608:24)
  at async renderToString (C:\path\to\code\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:644:20)
  at async Object.renderToString$1 [as renderToString] (C:\path\to\code/.nuxt/prerender/chunks/renderer.mjs:305:18)
  at async Object.renderToString (C:\path\to\code/node_modules/vue-bundle-renderer/dist/runtime.mjs:177:20)
  at async C:\path\to\code/.nuxt/prerender/chunks/renderer.mjs:379:21
  at async C:\path\to\code/.nuxt/prerender/chunks/renderer.mjs:16:22
  at async Object.handler (C:\path\to\code/node_modules/h3/dist/index.mjs:1247:19)
  at async toNodeHandle (C:\path\to\code/node_modules/h3/dist/index.mjs:1322:7)
  at async ufetch (C:\path\to\code/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async generateRoute (C:\path\to\code/node_modules/nitropack/dist/shared/nitro.43f4f2d5.mjs:4187:17)
  at async prerender (C:\path\to\code/node_modules/nitropack/dist/shared/nitro.43f4f2d5.mjs:4245:22)
  at async C:\path\to\code/node_modules/nuxt/dist/index.mjs:2124:7
  at async build (C:\path\to\code/node_modules/nuxt/dist/index.mjs:2942:5)
  at async Object.invoke (C:\path\to\code/node_modules/nuxt/node_modules/nuxi/dist/chunks/build.mjs:59:5)
  at async Object.invoke (C:\path\to\code/node_modules/nuxt/node_modules/nuxi/dist/chunks/generate.mjs:39:5)
  at async _main (C:\path\to\code/node_modules/nuxt/node_modules/nuxi/dist/cli.mjs:49:20)
```

Not sure what file is giving this error but my guess is the new layout that has a navbar which accesses the user object for the user's name.

However I have included a check that it only tries to retrieve the cookie when in client. Otherwise it should use dummy data

```js
  mounted() {
    if (process.client) {
      if (Cookies.get("user")) this.user = JSON.parse(Cookies.get("user"));
    }

    if (process.server) {
      this.user = {
        fullName: "example"
      }
    }
  },
  ```

**Comment by danielroe** [comment]
mounted only runs on the client so this fallback will never be set

**Comment by Timtendo12** [comment]
> Member
ah I did not know. However, is there a way to figure out exactly where in the codebase it fails to render? Is there some logic behind the chunks so we can identify it?
