### ISSUE TITLE
Cannot use a plugin in the titleTemplate function

### ISSUE THREAD

**Issue by HugeLetters** [nuxt/nuxt#21457]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.1.0
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@9.6.4
- Builder:          vite
- User Config:      modules, app, typescript, vite, experimental
- Runtime Modules:  @pinia/nuxt@0.4.11, @vueuse/nuxt@10.1.2
- Build Modules:    -

### Reproduction

I have a plugin for i18n which uses `"i18next": "^22.5.0","i18next-vue": "^2.1.1",`

```typescript
export default defineNuxtPlugin(({ vueApp }) => {
	vueApp.use(I18NextVue, { i18next });
	i18next.init({ fallbackLng: defaultLocale, resources });

	function translate(key: TranslationKeys) {
		const { t } = useTranslation();
		return t(key);
	}

	return { provide: { i18n: i18next, translate } };
});
```

### Describe the bug

But when I use my plugin like this
```typescript
const { $translate } = useNuxtApp();
useHead({ titleTemplate: (t) => `${t} / ${$translate('meta.home.title')}` });
```
I get the following error.
![image](https://github.com/nuxt/nuxt/assets/119697239/83feb3c3-69ca-4216-bc3e-120353eb0bc3)

This works fine tho
```typescript
const { $translate } = useNuxtApp();
useHead({ titleTemplate: `%s / ${$translate('meta.home.title')}` });
```

### Logs

```shell-script
[frontend] [nuxt] [request error] [unhandled] [500] i18next-vue: No Vue instance in context. Make sure to register the i18next-vue plugin using app.use(...).
[frontend]   at Module.useTranslation (/C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/i18next-vue/dist/index.mjs:118:11)
[frontend]   at translate (C:\Users\ckuka\VS Code Projects\ows-events\frontend\plugins\i18n.ts:23:41)
[frontend]   at titleTemplate (C:\Users\ckuka\VS Code Projects\ows-events\frontend\pages\index.vue:43:39)
[frontend]   at resolveTitleTemplate (/C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/@unhead/shared/dist/index.mjs:79:12)
[frontend]   at tags:resolve (/C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/unhead/dist/index.mjs:59:28)
[frontend]   at /C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/hookable/dist/index.mjs:48:66
[frontend]   at /C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/hookable/dist/index.mjs:48:56
[frontend]   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]   at async Object.resolveTags (/C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/unhead/dist/index.mjs:995:7)
[frontend]   at async Module.renderSSRHead (/C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/@unhead/ssr/dist/index.mjs:77:23)
[frontend] [nuxt] [request error] [unhandled] [500] i18next-vue: No Vue instance in context. Make sure to register the i18next-vue plugin using app.use(...).
[frontend]   at Module.useTranslation (/C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/i18next-vue/dist/index.mjs:118:11)
[frontend]   at translate (C:\Users\ckuka\VS Code Projects\ows-events\frontend\plugins\i18n.ts:23:41)
[frontend]   at titleTemplate (C:\Users\ckuka\VS Code Projects\ows-events\frontend\pages\index.vue:43:39)
[frontend]   at resolveTitleTemplate (/C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/@unhead/shared/dist/index.mjs:79:12)
[frontend]   at tags:resolve (/C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/unhead/dist/index.mjs:59:28)
[frontend]   at /C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/hookable/dist/index.mjs:48:66
[frontend]   at /C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/hookable/dist/index.mjs:48:56
[frontend]   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[frontend]   at async Object.resolveTags (/C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/unhead/dist/index.mjs:995:7)
[frontend]   at async Module.renderSSRHead (/C:/Users/ckuka/VS%20Code%20Projects/ows-events/frontend/node_modules/@unhead/ssr/dist/index.mjs:77:23)
```

**Comment by danielroe** [comment]
The issue here is that we don't have access to the runtime Nuxt context within `renderSSRHead` as it is an async method.

cc: @harlan-zw

**Comment by HugeLetters** [comment]
> 

Would you be so kind to offer a work-around? It's not a deal-breaker, `%s` works fine for now but would be nice to be able to use the function-way.

**Comment by HugeLetters** [comment]
> Hi, I don't really understand the problem if you already have a workaround with `%s`.
> 
> [Template params](https://unhead.harlanzw.com/guide/guides/template-params) are the expanded way to work around this problem.
> 
> If you want to use a function can't you just reference the `$t` function off of the existing i18n instance instead of re-instantiation with `useTranslation()` each time? (my i18n module knowledge is limited). I personally don't really see the value of using a function if the data isn't reactive though.

The data is reactive because it depends on the currently selected language. I'll look into suggested solutions, thanks!
