### ISSUE TITLE
Navigation between simple and query route with blocking async data inside it

### ISSUE THREAD

**Issue by DogmaZh** [nuxt/nuxt#21483]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      devtools, pages
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/DogmaZh/nuxt3-route-query-error

### Describe the bug

When you have navigation with query and default one in same time, like 
Route1 -> Route?test=test
Route2 -> Route2?test=test
and you have async logic inside them, in my case useAsyncData(....)
if you will navigate between default route and query route really fast you will face this error

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (chunk-MNWBZQKJ.js:82:30)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-3Q27KRJ5.js:5823:11)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (chunk-3Q27KRJ5.js:5860:52)
    at updateComponent (chunk-3Q27KRJ5.js:5687:18)
    at processComponent (chunk-3Q27KRJ5.js:5622:7)
    at patch (chunk-3Q27KRJ5.js:5084:11)
    at patchSuspense (chunk-3Q27KRJ5.js:1210:7)
    at Object.process (chunk-3Q27KRJ5.js:1129:7)
    at patch (chunk-3Q27KRJ5.js:5109:16)
    
 "nuxt": "npm:nuxt3@pr-21450"
 Didn`t help me

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/13309. It could also be related to https://github.com/nuxt/nuxt/issues/13350. Both are upstream Vue bugs.
