### ISSUE TITLE
Unable to extend layer to external repo: 403 Forbidden

### ISSUE THREAD

**Issue by saadrhiri** [nuxt/nuxt#21566]
### Environment

- Operating System: `Darwin`
- Node Version:    `v18.16.0`
- Nuxt Version:     `3.5.3`
- Nitro Version:    `2.4.1`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `devtools, extends`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-msvidt?file=nuxt.config.js

### Describe the bug

I'm trying to extend a layer by adding the [extends] property to the nuxt.config.js:
```
export default defineNuxtConfig({
           extends: [  'gitlab:SaadOuadrhiri/test', ], 
 })
```

but i'm encountering this error when i run `npm run dev` :

```
ERROR  Failed to download https://gitlab.com/SaadOuadrhiri/test/-/archive/main.tar.gz: 403 Forbidden

  at download (/Users/Faical/Desktop/sites%20test/b2b2/node_modules/giget/dist/shared/giget.093c29e5.mjs:29:11)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async downloadTemplate (/Users/Faical/Desktop/sites%20test/b2b2/node_modules/giget/dist/shared/giget.093c29e5.mjs:244:5)
  at async resolveConfig (/Users/Faical/Desktop/sites%20test/b2b2/node_modules/c12/dist/index.mjs:250:20)
  at async extendConfig (/Users/Faical/Desktop/sites%20test/b2b2/node_modules/c12/dist/index.mjs:217:21)
  at async loadConfig (/Users/Faical/Desktop/sites%20test/b2b2/node_modules/c12/dist/index.mjs:159:5)
  at async loadNuxtConfig (/Users/Faical/Desktop/sites%20test/b2b2/node_modules/@nuxt/kit/dist/index.mjs:2447:18)
  at async Object.invoke (/Users/Faical/Desktop/sites%20test/b2b2/node_modules/nuxi/dist/chunks/dev.mjs:124:20)
  at async _main (/Users/Faical/Desktop/sites%20test/b2b2/node_modules/nuxi/dist/cli.mjs:48:20)
```

**Comment by baha96** [comment]
see https://gitlab.com/gitlab-org/gitlab-foss/-/issues/54572
