### ISSUE TITLE
Big integer literals are not available in the configured target environment

### ISSUE THREAD

**Issue by fabis94** [nuxt/nuxt#21697]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.5.1
- Package Manager:  yarn@3.2.0
- Builder:          vite
- User Config:      typescript, modules, alias, vite, ssr, build, hooks
- Runtime Modules:  @nuxtjs/tailwindcss@6.7.0
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/specklesystems/speckle-server/pull/1647

### Describe the bug

I'm using @vitejs/plugin-legacy to enable support for older browser versions (chrome65 specifically) and after upgrading to nuxt 3.5.3 I can no longer build the app because of the following error:

```
#31 102.0 ➤ YN0000: Nuxi 3.5.3
#31 102.0 ➤ YN0000: Nuxt 3.5.3 with Nitro 2.5.0
#31 104.1 ➤ YN0000: ℹ Using Tailwind CSS from ~/assets/css/tailwind.css
#31 107.0 ➤ YN0000: ℹ Building client...
#31 107.0 ➤ YN0000: ℹ vite v4.3.9 building for production...
#31 107.3 ➤ YN0000: ℹ transforming...
#31 134.2 ➤ YN0000: ℹ ✓ 5650 modules transformed.
#31 135.3 ➤ YN0000: ℹ rendering chunks...
#31 136.1 ➤ YN0000: 
#31 136.1 ➤ YN0000:  ERROR  [vite:esbuild-transpile] Transform failed with 2 errors:
#31 136.1 ➤ YN0000: _nuxt/entry.!~{001}~.js:10665:80: ERROR: Big integer literals are not available in the configured target environment ("chrome65", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
#31 136.1 ➤ YN0000: _nuxt/entry.!~{001}~.js:10666:66: ERROR: Big integer literals are not available in the configured target environment ("chrome65", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
#31 136.1 ➤ YN0000: 
#31 136.1 ➤ YN0000: Big integer literals are not available in the configured target environment ("chrome65", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
#31 136.1 ➤ YN0000: 10663|  const revivers = {
#31 136.1 ➤ YN0000: 10664|    NuxtError: (data) => createError(data),
#31 136.1 ➤ YN0000: 10665|    EmptyShallowRef: (data) => shallowRef(data === "_" ? void 0 : data === "0n" ? 0n : JSON.parse(data)),
#31 136.1 ➤ YN0000:    |                                                                                  ^
#31 136.1 ➤ YN0000: 10666|    EmptyRef: (data) => ref(data === "_" ? void 0 : data === "0n" ? 0n : JSON.parse(data)),
#31 136.1 ➤ YN0000: 10667|    ShallowRef: (data) => shallowRef(data),
#31 136.1 ➤ YN0000: 
#31 136.1 ➤ YN0000: Big integer literals are not available in the configured target environment ("chrome65", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
#31 136.1 ➤ YN0000: 10664|    NuxtError: (data) => createError(data),
#31 136.1 ➤ YN0000: 10665|    EmptyShallowRef: (data) => shallowRef(data === "_" ? void 0 : data === "0n" ? 0n : JSON.parse(data)),
#31 136.1 ➤ YN0000: 10666|    EmptyRef: (data) => ref(data === "_" ? void 0 : data === "0n" ? 0n : JSON.parse(data)),
#31 136.1 ➤ YN0000:    |                                                                    ^
#31 136.1 ➤ YN0000: 10667|    ShallowRef: (data) => shallowRef(data),
#31 136.1 ➤ YN0000: 10668|    ShallowReactive: (data) => shallowReactive(data),
#31 136.1 ➤ YN0000: 
#31 136.1 ➤ YN0000: 
#31 136.1 ➤ YN0000: ℹ ✓ built in 29.09s
#31 136.1 ➤ YN0000: 
#31 136.1 ➤ YN0000:  ERROR  Transform failed with 2 errors:
#31 136.1 ➤ YN0000: _nuxt/entry.!~{001}~.js:10665:80: ERROR: Big integer literals are not available in the configured target environment ("chrome65", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
#31 136.1 ➤ YN0000: _nuxt/entry.!~{001}~.js:10666:66: ERROR: Big integer literals are not available in the configured target environment ("chrome65", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
#31 136.1 ➤ YN0000: 
#31 136.1 ➤ YN0000:   _nuxt/entry.!~{001}~.js:10665:80: ERROR: Big integer literals are not available in the configured target environment ("chrome65", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
#31 136.1 ➤ YN0000:   _nuxt/entry.!~{001}~.js:10666:66: ERROR: Big integer literals are not available in the configured target environment ("chrome65", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
#31 136.1 ➤ YN0000:   at failureErrorWithLog (node_modules/esbuild/lib/main.js:1636:15)
#31 136.1 ➤ YN0000:   at node_modules/esbuild/lib/main.js:837:29
#31 136.1 ➤ YN0000:   at responseCallbacks.<computed> (node_modules/esbuild/lib/main.js:697:9)
#31 136.1 ➤ YN0000:   at handleIncomingPacket (node_modules/esbuild/lib/main.js:752:9)
#31 136.1 ➤ YN0000:   at Socket.readFromStdout (node_modules/esbuild/lib/main.js:673:7)
#31 136.1 ➤ YN0000:   at Socket.emit (node:events:513:28)
#31 136.1 ➤ YN0000:   at Socket.emit (node:domain:489:12)
#31 136.1 ➤ YN0000:   at addChunk (node:internal/streams/readable:315:12)
#31 136.1 ➤ YN0000:   at readableAddChunk (node:internal/streams/readable:289:9)
#31 136.1 ➤ YN0000:   at Socket.Readable.push (node:internal/streams/readable:228:10)
```

I've tried adjusting the configuration of @vitejs/plugin-legacy, even enabling all polyfills w/ `modernPolyfills: true`, but it doesn't help. Support for chrome65 is a requirement in this case so I can't just target a newer chrome version.

**Comment by danielroe** [comment]
I believe this has been resolved in https://github.com/nuxt/nuxt/pull/21427 - you can try the edge channel to confirm. v3.6.0 should be released later today, including this fix.
