### ISSUE TITLE
Calling a composable inside an async catch block - useNuxtApp not available

### ISSUE THREAD

**Issue by JulianMar** [nuxt/nuxt#21698]
### Environment

Nuxi 3.5.3                                                                                                                                                          12:57:09 PM
                                                                                                                                                                    12:57:10 PM
RootDir: /home/projects/nuxt-starter-rlw14p                                                                                                                         12:57:10 PM
Nuxt project info:                                                                                                                                                  12:57:10 PM

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.3
- Nitro Version:    2.5.0
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      modules, bugsnag
- Runtime Modules:  nuxt-bugsnag@6.5.2
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                         12:57:10 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/github-v4uqpe?file=app.vue

### Describe the bug

When calling use nuxt in an async catch block, the nuxt context is not available anymore.

In the environment, there is enough context to understand the bug.

### Logs

```shell-script
[nitro] [unhandledRejection] Error: [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.
    at Module.useNuxtApp (file:///home/projects/nuxt-starter-rlw14p/node_modules/nuxt/dist/app/nuxt.js:225:13)
    at __vite_ssr_exports__.default (file:///home/projects/nuxt-starter-rlw14p/composables/useApi.ts:12:39)
```

**Comment by danielroe** [comment]
See https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables for more info on why this happens.

You need to obtain `nuxtApp` before your first async operation, and you can then use it later on, including `nuxtApp.runWithContext` to run other composables that require access to the Nuxt context.

**Comment by JulianMar** [comment]
Thanks for the Info! Sorry for the non-issue in that case
