### ISSUE TITLE
@nuxt/kit@3.5.3 -> @nuxt/kit@3.6.0 throws errors when importing css

### ISSUE THREAD

**Issue by VividLemon** [nuxt/nuxt#21752]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  pnpm@8.6.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

A minimal reproduction is a bit difficult. 

You can find my unfinished work https://github.com/VividLemon/bootstrap-vue-next

Don't worry! It's not as big as it looks! The code is at ./packages/nuxt , and the only thing you need to do to see the issue is
 
```bash
pnpm i --ignore-scripts
pnpm build --filter nuxt
```

### Describe the bug

When updating to 3.6 for this package, I started getting `Rollup failed to resolve import "bootstrap-vue-next/dist/bootstrap-vue-next.css" from "C:/Users/Issayah.copsey/Downloads/bootstrap-vue-next/node_modules/.pnpm/nuxt@3.6.0_@types+node@20.3.1_eslint@8.43.0_rollup@3.25.1_typescript@5.1.3/node_modules/nuxt/dist/app/entry.js".`. It's likely something that can be a simple fix on my end. But I'm also simply wondering what necessitated this change to begin with.

### Logs

```shell-script
@bootstrap-vue-next/nuxt:build:  ERROR  [vite]: Rollup failed to resolve import "bootstrap-vue-next/dist/bootstrap-vue-next.css" from "C:/Users/Issayah.copsey/Downloads/bootstrap-vue-next/node_modules/.pnpm/nuxt@3.6.0_@types+node@20.3.1_eslint@8.43.0_rollup@3.25.1_typescript@5.1.3/node_modules/nuxt/dist/app/entry.js".
@bootstrap-vue-next/nuxt:build: This is most likely unintended because it can break your application at runtime.
@bootstrap-vue-next/nuxt:build: If you do want to externalize this module explicitly add it to
@bootstrap-vue-next/nuxt:build: build.rollupOptions.external
@bootstrap-vue-next/nuxt:build: 
@bootstrap-vue-next/nuxt:build: 
@bootstrap-vue-next/nuxt:build:  ERROR  [vite]: Rollup failed to resolve import "bootstrap-vue-next/dist/bootstrap-vue-next.css" from "C:/Users/Issayah.copsey/Downloads/bootstrap-vue-next/node_modules/.pnpm/nuxt@3.6.0_@types+node@20.3.1_eslint@8.43.0_rollup@3.25.1_typescript@5.1.3/node_modules/nuxt/dist/app/entry.js".
@bootstrap-vue-next/nuxt:build: This is most likely unintended because it can break your application at runtime.
@bootstrap-vue-next/nuxt:build: If you do want to externalize this module explicitly add it to
@bootstrap-vue-next/nuxt:build: build.rollupOptions.external
@bootstrap-vue-next/nuxt:build: 
@bootstrap-vue-next/nuxt:build:   This is most likely unintended because it can break your application at runtime.
@bootstrap-vue-next/nuxt:build:   If you do want to externalize this module explicitly add it to
@bootstrap-vue-next/nuxt:build:   build.rollupOptions.external
@bootstrap-vue-next/nuxt:build:   at viteWarn (/C:/Users/Issayah.copsey/Downloads/bootstrap-vue-next/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1_sass@1.63.6/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46597:23)
@bootstrap-vue-next/nuxt:build:   at onRollupWarning (/C:/Users/Issayah.copsey/Downloads/bootstrap-vue-next/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1_sass@1.63.6/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46621:9)
@bootstrap-vue-next/nuxt:build:   at onwarn (/C:/Users/Issayah.copsey/Downloads/bootstrap-vue-next/node_modules/.pnpm/vite@4.3.9_@types+node@20.3.1_sass@1.63.6/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46368:13)
@bootstrap-vue-next/nuxt:build:   at /C:/Users/Issayah.copsey/Downloads/bootstrap-vue-next/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:23639:13
@bootstrap-vue-next/nuxt:build:   at Object.logger [as onLog] (/C:/Users/Issayah.copsey/Downloads/bootstrap-vue-next/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:25305:9)
@bootstrap-vue-next/nuxt:build:   at ModuleLoader.handleInvalidResolvedId (/C:/Users/Issayah.copsey/Downloads/bootstrap-vue-next/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:24221:26)
@bootstrap-vue-next/nuxt:build:   at /C:/Users/Issayah.copsey/Downloads/bootstrap-vue-next/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:24181:26
@bootstrap-vue-next/nuxt:build: 
@bootstrap-vue-next/nuxt:build:  ELIFECYCLE  Command failed with exit code 1.
@bootstrap-vue-next/nuxt:build:  ELIFECYCLE  Command failed with exit code 1.
@bootstrap-vue-next/nuxt:build: ERROR: command finished with error: command (C:\Users\Issayah.copsey\Downloads\bootstrap-vue-next\packages\nuxt) pnpm run build exited (1)
command (C:\Users\Issayah.copsey\Downloads\bootstrap-vue-next\packages\nuxt) pnpm run build exited (1)
```

**Comment by danielroe** [comment]
Are you saying that you receive this error when running this command? `pnpm build --filter nuxt`. I am not getting any errors, and I can also subsequently build and run the playground project.

**Comment by VividLemon** [comment]
> Are you saying that you receive this error when running this command? `pnpm build --filter nuxt`. I am not getting any errors, and I can also subsequently build and run the playground project.

My bad, I recently had reverted the nuxt version on that  branch. If you update the package.json to 3.6, it should have the error

**Comment by VividLemon** [comment]
@danielroe This branch should contain the issue https://github.com/VividLemon/bootstrap-vue-next/tree/nuxt

**Comment by danielroe** [comment]
thank you!

**Comment by VividLemon** [comment]
Yw
