### ISSUE TITLE
Failing on nuxt build

### ISSUE THREAD

**Issue by TusharRoy23** [nuxt/nuxt#21757]
### Environment

- node- 14.20.0
- nuxt - 2.16.3
- @nuxt/bridge - npm:@nuxt/bridge-edge@^3.0.0-27928371.c30fa0f
- @nuxt/bridge-edge - 3.0.0-28071266.dab55db

### Reproduction

application is running on development mode. But failing on build.

### Describe the bug

```
✔ Generated public .output/public                                                                                                                                                         nitro 4:09:34 PM
ℹ Initializing prerenderer                                                                                                                                                                nitro 4:09:34 PM

 FATAL  chunkInfo.moduleIds.at is not a function                                                                                                                                                  16:09:36

  at chunkFileNames (node_modules/@nuxt/bridge/node_modules/nitropack/dist/shared/nitro.28465d4b.mjs:1546:58)
  at Chunk.getPreliminaryFileName (node_modules/@nuxt/bridge/node_modules/rollup/dist/es/shared/node-entry.js:15783:74)
  at Chunk.render (node_modules/@nuxt/bridge/node_modules/rollup/dist/es/shared/node-entry.js:15842:42)
  at node_modules/@nuxt/bridge/node_modules/rollup/dist/es/shared/node-entry.js:17480:72
  at Array.map (<anonymous>)
  at renderChunks (node_modules/@nuxt/bridge/node_modules/rollup/dist/es/shared/node-entry.js:17480:53)
  at Bundle.generate (node_modules/@nuxt/bridge/node_modules/rollup/dist/es/shared/node-entry.js:17702:19)
  at async node_modules/@nuxt/bridge/node_modules/rollup/dist/es/shared/node-entry.js:26543:27
  at async catchUnfinishedHookActions (node_modules/@nuxt/bridge/node_modules/rollup/dist/es/shared/node-entry.js:25676:16)
  at async _build (node_modules/@nuxt/bridge/node_modules/nitropack/dist/shared/nitro.28465d4b.mjs:2313:5)
  at async prerender (node_modules/@nuxt/bridge/node_modules/nitropack/dist/shared/nitro.9ad1b522.mjs:44:3)
  at async node_modules/@nuxt/bridge/dist/shared/bridge-edge.c2605ac0.mjs:403:7
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:959)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:251:5)
  at async Object.invoke (node_modules/@nuxt/bridge-edge/node_modules/nuxi/dist/chunks/build.mjs:56:5)
  at async _main (node_modules/@nuxt/bridge-edge/node_modules/nuxi/dist/cli.mjs:48:20)
```

**Comment by TusharRoy23** [comment]
It was an issue for the node version. Had to move version 14 to 16.

**Comment by VitaliyVorobey** [comment]
> if you want run at node 14 , you can do like this, put this code at head of nuxt.config.js
> 
> ```
> if (!Array.prototype.at) {
>   Array.prototype.at = function (index) {
>     if (index >= 0)
>       return this[index]
> 
>     return this[this.length + index]
>   }
> }
> ```

perfect for me! Thanks
