### ISSUE TITLE
Cannot destructure property 'nuxt' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by floki1250** [nuxt/nuxt#21873]
### Environment

RootDir: C:/Users/ademi/Desktop/Edu/Projets/AgroSense/agrosense_Frontend                                      16:37:06
Nuxt project info:                                                                                            16:37:06

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.14.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, runtimeConfig, build, components, css, dir, experimental, imports, modules, vuefire, mapbox, nitro, srcDir, vite
- Runtime Modules:  @pinia/nuxt@0.4.11, @vueuse/nuxt@9.13.0, ~/modules/primevue, nuxt-icon@0.3.3, nuxt-mapbox@1.3.9, @nuxtjs/device@3.1.0, @nuxt/image-edge@1.0.0-rc.1-28135297.08462d1, nuxt-vuefire@0.1.6, nuxt-pdfeasy@1.4.0
- Build Modules:    -
------------------------------

### Reproduction

....

### Describe the bug

Error after building with yarn, even after trying to update to the latest version of nuxt, the error persists.
![image](https://github.com/nuxt/nuxt/assets/37814393/3b374255-b660-48fb-a0a2-addd54f49141)

### Logs

```shell-script
ERROR  Cannot destructure property 'nuxt' of 'undefined' as it is undefined.                                 16:29:02

  at build:before (C:/Users/ademi/Desktop/Edu/Projets/AgroSense/agrosense_Frontend/src/modules/router.ts:37:33)
  at /C:/Users/ademi/Desktop/Edu/Projets/AgroSense/agrosense_Frontend/node_modules/hookable/dist/index.mjs:48:66
  at Object.run (/C:/Users/ademi/Desktop/Edu/Projets/AgroSense/agrosense_Frontend/node_modules/hookable/dist/index.mjs:41:43)
  at /C:/Users/ademi/Desktop/Edu/Projets/AgroSense/agrosense_Frontend/node_modules/hookable/dist/index.mjs:48:56
  at async build (/C:/Users/ademi/Desktop/Edu/Projets/AgroSense/agrosense_Frontend/node_modules/nuxt/dist/index.mjs:3718:3)
  at async Object.invoke (/C:/Users/ademi/Desktop/Edu/Projets/AgroSense/agrosense_Frontend/node_modules/nuxi/dist/chunks/prepare.mjs:40:5)
  at async _main (/C:/Users/ademi/Desktop/Edu/Projets/AgroSense/agrosense_Frontend/node_modules/nuxi/dist/cli.mjs:48:20)
error Command failed with exit code 1.
```

**Comment by prashantpalikhe** [comment]
Looks like this is coming from your application code? What do you have in `src/modules/router.ts`?
