### ISSUE TITLE
When using nuxt3 to send files exceeding 10k, nuxt3 responds with fetch failed (interface path)

### ISSUE THREAD

**Issue by taishuai110** [nuxt/nuxt#21936]
### Environment

nuxt3 + TS

### Reproduction

Sorry, I may not be able to provide this connection, this error will not be displayed until deployed to the server

### Describe the bug

message
: 
"fetch failed (API)"
stack
: 
""
statusCode
: 
500
statusMessage
: 
""
url
: 
API"

### Logs

```shell-script
I am a new user of nuxt3. Last week, I packaged nuxt3 files and deployed them to the server for testing. I found that nuxt3 could not send files larger than 10KB. At first I thought there was a problem with my backend and the nginx reverse proxy, but after testing, my nginx and backend code did not respond to this request with any error. Later I checked the Internet that nginx limits the size of the uploaded file, I also tried, the limit size is reported 413, but I this is reported 500 error, not limit the size of the file. I tried the development interface again, but I was able to upload files over 10KB and even send 10MB files. After a series of checks, it was discovered that this error was only reported when deployed online. I see that the community has not encountered this problem, I would like to ask you have encountered this problem
```

**Comment by taishuai110** [comment]
Sorry，The is Reproduction [request error] [unhandled] [500] fetch failed ('Api') 
1|NuxtAppName  |   at sendProxy (./node_modules/h3/dist/index.mjs:468:20) 
1|NuxtAppName  |   at Object.handler (./node_modules/h3/dist/index.mjs:1196:19) 
1|NuxtAppName  |   at Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1271:7)
// Sorry, I can't provide my company's api interface

**Comment by taishuai110** [comment]
Sorry, I'm not sure where can I express mine
This is my error content:
   I am a new user of nuxt3. Last week, I packaged nuxt3 files and deployed them to the server for testing. I found that nuxt3 could not send files larger than 10KB. At first I thought there was a problem with my backend and the nginx reverse proxy, but after testing, my nginx and backend code did not respond to this request with any error. Later I checked the Internet that nginx limits the size of the uploaded file, I also tried, the limit size is reported 413, but I this is reported 500 error, not limit the size of the file. I tried the development interface again, but I was able to upload files over 10KB and even send 10MB files. After a series of checks, it was discovered that this error was only reported when deployed online. I see that the community has not encountered this problem, I would like to ask you have encountered this problem

**Comment by taishuai110** [comment]
Sorry，[nuxt] [request error] [unhandled] [500] fetch failed ('API')
1|NuxtAppName  |   at sendProxy (./node_modules/h3/dist/index.mjs:468:20)  
1|NuxtAppName  |   at Object.handler (./node_modules/h3/dist/index.mjs:1196:19)  
1|NuxtAppName  |   at Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1271:7)

**Comment by taishuai110** [comment]
@danielroe  
   I want to ask if nuxt3 will return message, stack, statusCode, statusMessage, url fields to the browser when it reports an error. The error messages returned by the backend and the error messages returned by nginx do not contain these fields, and I now think these fields are returned by nuxt3 itself

**Comment by taishuai110** [comment]
https://github.com/nuxt/nuxt/issues/12461
This is a similar mistake to mine, or I hope you can pay attention to it

**Comment by danielroe** [comment]
I've closed two other issues. Would you provide a [reproduction following these steps](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

That will help us understand the issue you are encountering.

**Comment by taishuai110** [comment]
> 我已经关闭了您创建的另外两个重复问题。[您能按照这些步骤](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)提供复制品吗？🙏
> 
> 这将帮助我们了解您遇到的问题。
this step repeat. I just downloaded the latest version and version 3.6.2 from the official website of nuxt3. In this version, I use Updata component of element-plus plug-in as a tool to upload pictures. nuxt3 can't upload pictures larger than 10kb after build, but there is no such problem when dev is running. Will nuxt3 project limit the size of FromData after npm run build

**Comment by taishuai110** [comment]
> 我已经关闭了您创建的另外两个重复问题。[您能按照这些步骤](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)提供复制品吗？🙏
> 
> 这将帮助我们了解您遇到的问题。

Sorry, I don't know how to use your project to upload the problems I found, but I can make this step repeat. I just downloaded the latest version and version 3.6.2 from the official website of nuxt3. In this version, I use Updata component of element-plus plug-in as a tool to upload pictures. nuxt3 can't upload pictures larger than 10kb after build, but there is no such problem when dev is running. Will nuxt3 project limit the size of FromData after npm run build

**Comment by taishuai110** [comment]
> 我已经关闭了您创建的另外两个重复问题。[您能按照这些步骤](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)提供复制品吗？🙏
> 
> 这将帮助我们了解您遇到的问题。

You can do a simple experiment, download the nuxt3 project package from the nuxt3 website, and then configure element-plus in it (of course you can use other ways to upload pictures, but I think this is the fastest way to upload files), but this is not the point, the point is, Using npm run build to start the index.mjs file (locally) with node will also trigger the bug. After you solve the cross-domain problem, try uploading an image larger than 10kb or a file with a non-TXT suffix. The browser's network will display nuxt] [request error] [unhandled] [500] fetch failed, this error. Or if you change the path to one that doesn't exist, it still reports the error. My progress can only be stuck here, I hope the official staff can try, if not, I directly put the just downloaded nuxt3.6.2 project on my github project, I hope the staff can pay attention to it. thank you

**Comment by danielroe** [comment]
I'm asking you to create the reproduction following the steps in the link I attached above - I'll be very happy to look at it, but the problem is that I don't know exactly what you've done unless I can see some code. Even following steps that you provide isn't good enough most of the time as it is time consuming to do that for every issue someone raises, and I'm never entirely sure that I've done exactly what you've tried.

You can also provide a git repository with the minimal code necessary to cause the issue, if that is easier than using a stackblitz link.

**Comment by danielroe** [comment]
No problem at all! Thank you.

**Comment by taishuai110** [comment]
> 完全没问题！谢谢。
Hello, this is my warehouse address (https://github.com/taishuai110/nuxt3-error/tree/master), if you upload a file to 502 mistakes, this is normal, because the Java quote I didn't open, but this does not affect, You can use npm run build package and then send a more than 10kb non-TXT (preferably this file contains pictures), or you more than 10kb of the picture is also OK, there are errors I said.

**Comment by taishuai110** [comment]
> 完全没问题！谢谢。

Is there a problem? I'm sorry, forgive me for asking, but this is really important to me, and this is the only thing I need to do my job

**Comment by taishuai110** [comment]
> 完全没问题！谢谢。

Sorry, I really have no choice. I have been troubled by this problem for a month. I think, if I don't solve this problem, I will lose this job

**Comment by taishuai110** [comment]
> 没问题！谢谢。
Nirto? In 'development, it will use the FS driver writting to.nitro/cache or.nuxt/cache if using Nuxt.'

'In production, it will use the memory driver by default.'

**Comment by danielroe** [comment]
Have you tried using native fetch with `fetch` rather than `$fetch`?

**Comment by danielroe** [comment]
cc: @pi0 in case this is a limitation you're aware of in ofetch

**Comment by taishuai110** [comment]
![image](https://github.com/nuxt/nuxt/assets/108387355/680cd432-b40b-43ec-b011-2362311228d3)
![QQ图片20230720213730](https://github.com/nuxt/nuxt/assets/108387355/bb963016-29b9-497c-9f27-0748427e3e82)

Sorry, I can only confirm that my red box may be the problem, I really know nothing about Nitro documentation, Nitro in the proxy service, does it limit the size of the requested file in the production environment due to caching issues, if so, that is too bad. I looked at it for 3 hours and couldn't understand the address the `driver` was pointing to in this code

**Comment by taishuai110** [comment]
@danielroe Can you solve this problem

**Comment by taishuai110** [comment]
![image](https://github.com/nuxt/nuxt/assets/108387355/20fac338-4f6b-484f-908b-86a7dbfbd08a)
![image](https://github.com/nuxt/nuxt/assets/108387355/c3d88f75-1b4c-4c31-8fa2-d102d2fc8c75)
![image](https://github.com/nuxt/nuxt/assets/108387355/7f3f03f1-0aa5-4f55-af3c-ea6919708002)

I am really helpless about this bug now, do not know how to solve, the first picture is to send a picture, which corresponds to the third picture, the second picture is to send a txt document format without pictures, which can be successful, but this limitation is too big, I hope I can also upload pictures, but I really do not know where the problem is nuxt. (Note: This is not a `java` problem, because I have been staring at the `java` log, there is nothing wrong with it, this picture is tested locally, so there is no nginx problem.)

**Comment by Hebilicious** [comment]
Looking at your repository here https://github.com/taishuai110/nuxt3-error/tree/master 
It is hard to help you because we do not see the code of your other server, as well as your deployment environment. Therefore we can't reproduce your issue and we can't investigate it. 

However, you can try to upload files to your server without using the nitro proxy settings.

Instead of using the action attribute of your form, try using `new FormData` and `fetch` https://javascript.info/formdata , and directly try sending data to your server URL.

**Comment by taishuai110** [comment]
> @taishuai110 在这里查看您的存储库https://github.com/taishuai110/nuxt3-error/tree/master 很难为您提供帮助，因为我们看不到您其他服务器的代码以及您的部署环境。因此，我们无法覆盖您的问题，也无法由此进行调查。
> 
> 但是，您可以尝试在不使用硝基代理设置的情况下将文件上传到服务器。
> 
> [不要](https://javascript.info/formdata)使用表单的操作属性，而是尝试使用`new FormData`https://javascript.info/formdata ，并直接尝试将数据发送到服务器 URL。`fetch` [](https://javascript.info/formdata)

In fact, this is not a deployment environment and server issues, this is a NItro production environment and development environment issues, server I used `postman` interface, can successfully send back, but using nuxt3 `routeRules` proxy service forward, which can not send, I tried lowering node18 to node16 and the images were ready to be sent, but the images sent were really corrupted. Switching to a proxy service forwarding in development mode, but being able to send it successfully, I now have reason to suspect that Nitro's production and development of two different proxy services are the cause

![image](https://github.com/nuxt/nuxt/assets/108387355/ac8d9e91-e24f-42fd-b413-43a24cd9ed0c)
With a little context, I can make it happen again

**Comment by taishuai110** [comment]
> @taishuai110 在这里查看您的存储库https://github.com/taishuai110/nuxt3-error/tree/master 很难为您提供帮助，因为我们看不到您其他服务器的代码以及您的部署环境。因此，我们无法覆盖您的问题，也无法由此进行调查。
> 
> 但是，您可以尝试在不使用硝基代理设置的情况下将文件上传到服务器。
> 
> [不要](https://javascript.info/formdata)使用表单的操作属性，而是尝试使用`new FormData`https://javascript.info/formdata ，并直接尝试将数据发送到服务器 URL。`fetch` [](https://javascript.info/formdata)

Instead of using forms, I use formData, which is exactly what I want to use, and my github uses forms in order to make it easy for you to download, in fact, I use formData in my project. At the beginning, I also used axios to send requests, but I found that I couldn't get around this error, and both axios and fetch sent requests through the agent service, that is, the agent of nitro. Why did the agent in the development environment and the agent in the production environment have two completely different results

**Comment by taishuai110** [comment]
> @taishuai110 在这里查看您的存储库https://github.com/taishuai110/nuxt3-error/tree/master 很难为您提供帮助，因为我们看不到您其他服务器的代码以及您的部署环境。因此，我们无法覆盖您的问题，也无法由此进行调查。
> 
> 但是，您可以尝试在不使用硝基代理设置的情况下将文件上传到服务器。
> 
> [不要](https://javascript.info/formdata)使用表单的操作属性，而是尝试使用`new FormData`https://javascript.info/formdata ，并直接尝试将数据发送到服务器 URL。`fetch` [](https://javascript.info/formdata)

In fact, you can download it directly, and then install it using npm i, of course, this requires node18, of course node16 environment can be installed, and can also send pictures in production environment, but this does not solve the problem, because in my project, the image sent in the past is a corrupted image. I now have reason to suspect that Nitro's production agent may have mishandled the file file

**Comment by taishuai110** [comment]
@danielroe @Hebilicious @pi0 

(https://github.com/taishuai110/nuxt3-or-node)

This is my newly created github address, and there are two folders in it. One is` NuxT3-error-Master`, which contains the code of `nuxt3` and further verifies my guess on `nitro`. 

After downloading, it is recommended to use` npm i `in this folder for environment download. Then use `npm run build` to test the package. 

The other `node` folder is the `node `interface i created myself, rest assured, this is not big, in this folder also use the` npm i` command to download the environment, and then run the `02` file in this folder, which can be used as a simple interface. 

Whether you use `node18` or `node16` to test` nuxt`3, the results will not be successful. Let me start with the conclusion of my tests. Using `node18`, the program got stuck in the `NuxT3-error-Master` folder and found that the `node` file was not receiving any requests at all. Using `node16` test, found that the file can be sent out, `node` folder can also receive, but you will find that the `public/image` folder received the image can not be opened, although I did not write the image suffix, but you try to modify the image suffix, you will find that the image has been damaged. The situation is the same with `node18` again.

 If you run the project with the "`npm run dev`" command, you will see that the files are sent out again, which undoubtedly confirms that nitro has two different service agents

**Comment by taishuai110** [comment]
@Hebilicious @danielroe @pi0 

Record 2. 
Send pictures to the nodeAPI interface using `node16.15.0.` There are two cases. In the first case, send pictures using n`pm run dev`. 

The second method is to use `npm run build` to send the image after packaging. The result of sending is also successful, but the image can not be opened in the image file of node. 

After the comparison, the development environment to send pictures will not modify the format of the picture, that is, the original ANSI format, the format here refers to the use of notepad to open the picture. 

The production environment will modify the sent image to utf-8 format, which makes me wonder why the production environment will change the format of the image.

**Comment by taishuai110** [comment]
@Hebilicious @danielroe 

Record 2

Send pictures to the nodeAPI interface using node16.15.0. There are two cases. In the first case, send pictures using npm run dev.

The second method is to use npm run build to send the image after packaging. The result of sending is also successful, but the image can not be opened in the image file of node.

After the comparison, the development environment to send pictures will not modify the format of the picture, that is, the original ANSI format, the format here refers to the use of notepad to open the picture

The production environment will modify the sent image to utf-8 format, which makes me wonder why the production environment will change the format of the image.

**Comment by solak147** [comment]
i have the same problems with @taishuai110.
my nuxt3 use   
  routeRules: {
     '/api/**': { proxy: 'http://localhost:8080/**' }
  }
 to upload image in product, but image broken.
but i use postman success.

**Comment by danielroe** [comment]
nuxtathon closed @Norbiros

**Comment by taishuai110** [comment]
New reply to your ticket #11981

Title: Re: [nuxt/nuxt] nuxt3 production environment only supports utf-8 format files, how to modify this to support ANSI format files (Issue #21936)

Message: Hello

**Comment by taishuai110** [comment]
New reply to your ticket #11985

Title: Re: [nuxt/nuxt] nuxt3 production environment only supports utf-8 format files, how to modify this to support ANSI format files (Issue #21936)

Message: Hello

**Comment by taishuai110** [comment]
New reply to your ticket #11989

Title: Re: [nuxt/nuxt] nuxt3 production environment only supports utf-8 format files, how to modify this to support ANSI format files (Issue #21936)

Message: Hello

**Comment by taishuai110** [comment]
New reply to your ticket #11992

Title: Re: [nuxt/nuxt] nuxt3 production environment only supports utf-8 format files, how to modify this to support ANSI format files (Issue #21936)

Message: Hello

**Comment by Norbiros** [comment]
@taishuai110 could you please elaborate? I think this issue is resolved, if not, please consider opening a new issue with a proper reproduction.
