### ISSUE TITLE
Jiti 1.19.0 breaks Nuxt 3.6.1

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#21931]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  pnpm@8.6.5
- Builder:          vite
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Hello,

On Windows (and Linux), start a fresh project and install deps, you will this error

```
Nuxi 3.6.1                                                                                                  2:34:26 PM

[2:34:28 PM]  ERROR  Cannot create property 'C:/Users/esoubiran/dev/barbapapazes/agency/nuxt.config.ts' on string 'C:/Users/ESOUBI~1/AppData/Local/Temp/node-jiti'

  at evalModule (node_modules\.pnpm\jiti@1.19.0\node_modules\jiti\dist\jiti.js:1:254815)
  at Object.jiti (node_modules\.pnpm\jiti@1.19.0\node_modules\jiti\dist\jiti.js:1:253034)
  at resolveConfig (/C:/Users/esoubiran/dev/barbapapazes/agency/node_modules/.pnpm/c12@1.4.2/node_modules/c12/dist/index.mjs:280:24)
  at loadConfig (/C:/Users/esoubiran/dev/barbapapazes/agency/node_modules/.pnpm/c12@1.4.2/node_modules/c12/dist/index.mjs:116:40)
  at async loadNuxtConfig (/C:/Users/esoubiran/dev/barbapapazes/agency/node_modules/.pnpm/@nuxt+kit@3.6.1/node_modules/@nuxt/kit/dist/index.mjs:2483:18)
  at async loadNuxt (/C:/Users/esoubiran/dev/barbapapazes/agency/node_modules/.pnpm/nuxt@3.6.1_@types+node@18.0.0/node_modules/nuxt/dist/index.mjs:3205:19)
  at async loadNuxt (/C:/Users/esoubiran/dev/barbapapazes/agency/node_modules/.pnpm/@nuxt+kit@3.6.1/node_modules/@nuxt/kit/dist/index.mjs:2537:19)
  at async Object.invoke (/C:/Users/esoubiran/dev/barbapapazes/agency/node_modules/.pnpm/nuxi@3.6.1/node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
  at async _main (/C:/Users/esoubiran/dev/barbapapazes/agency/node_modules/.pnpm/nuxi@3.6.1/node_modules/nuxi/dist/cli.mjs:48:20)
```

### Describe the bug

/

**Comment by Barbapapazes** [comment]
What if I use jiti 1.18? I will try

**Comment by casualmatt** [comment]
Same issue. 
![image](https://github.com/nuxt/nuxt/assets/85650530/767e49f0-7478-4415-86ab-06fbc6f88937)

**Comment by bozicstefan** [comment]
I am experiencing the same issue on Linux  Ubuntu 22.04.2 LTS (Jammy Jellyfish), node v18.16.1.
--------------------------------------------------------------------------------------------------------------------------------------
Reproduction steps:
---------------------------
npx init myProject
cd myProject
npm i
--------------------------------------------------------------------------------------------------------------------------------------
![Screenshot from 2023-07-04 15-06-20](https://github.com/nuxt/nuxt/assets/88157789/13cd851e-33be-44aa-96f4-87883ec7ab78)

**Comment by RomainSimonAB** [comment]
I fixed the problem with the following lines in my package.json file :

"overrides": {
    "nuxt": {
      "jiti": "1.18.2"
    }
  }

**Comment by pi0** [comment]
Upstream: https://github.com/unjs/jiti/issues/147

Hotfix added in [`jiti@1.19.1`](https://github.com/unjs/jiti/releases/tag/v1.19.1). Please make sure to upgrade lock file to receive the fix 🙏🏼

**Comment by Barbapapazes** [comment]
> Upstream: [unjs/jiti#147](https://github.com/unjs/jiti/issues/147)
> 
> Hotfix added in [`jiti@1.19.1`](https://github.com/unjs/jiti/releases/tag/v1.19.1). Please make sure to upgrade lock file to receive the fix 🙏🏼

resolved with this version! Thanks @pi0

**Comment by dudunato** [comment]
Overrides didn't work for me, but using `resolutions` did the trick:

```
 "resolutions": {
    "jiti": "1.18.2"
  }
```
