### ISSUE TITLE
Incorrect execution of `definePageMeta` macro

### ISSUE THREAD

**Issue by helltraitor** [nuxt/nuxt#21967]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.1
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Use `definePageMeta` with fields that context depended (tested only layout, probably fails on other fields - if I have correct suspicions)

https://stackblitz.com/edit/nuxt-starter-9reefq?file=pages%2Findex.vue

### Describe the bug

I offend this bug when tries to shortcut layout setting
```ts
definePageMeta({
  layout,  // <-- definitely known and valid
})
```

Then I tries to set different forms of exact same value:
```ts
definePageMeta({
  layout: layout)  // <-- works on my machine
})
```

Then I've started my investigation:
```ts
  // Text that I've wrote before on stackblitz

  // layout, // broken here and for me
  // layout: alias, // fails for both
  // layout: layout, // works for both (floating error - works always for me, but may fail here)
  // layout: 'default', // Works for both
  // layout: computed(() => layout), // cause graphical artifact for both
  // layout: ref(layout), // works for both
  // layout: false, // works for both (dynamic included layout)
```

### Additional context

I assume that problem in the lazy or incorrect implementation of this macro. For my opinion, "linking" setup values occurs in wrong scope (general theory).

## What I suppose you need to check
- [ ] Is this error occurs only for this field, or entire macro affected (as I think, not checked)
- [ ] Is this error affects all provided macro?
- [ ] Is this error can be avoided via wrapping macro in decorator function (*see 1 note)
- [ ] Is this error can be avoided via replacing macro by function
- [ ] Is this error can be avoided via forcing macro execution (may be partially) on setup stage

###  Note 1
What if this error can be avoided via linking values on setup stage and evaluated as usual (instead of defer this action)
```ts
const definePageMeta(options: DefinePageMetaOptions) => {
  // Let assume that we renamed original definePageMeta to definePageMetaMacro
  definePageMetaMacro({
    layout: options.layout,
   ...
  })
}
```

Then, if problem in the stage of macro execution
```html
<script setup lang="ts">

// Will be wrapped and passed to macro
definePageMeta({
  ...
})
</script>
```

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] layout is not defined                                               12:14:50 AM
  at eval (./pages/index.vue:17:7)  
  at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:11)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./virtual:nuxt:/home/projects/nuxt-starter-9reefq/.nuxt/routes.mjs:1:216)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/pages/runtime/plugins/router.js:10:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)

[nuxt] [request error] [unhandled] [500] layout is not defined                                               12:14:50 AM
  at eval (./pages/index.vue:17:7)  
  at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:11)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./virtual:nuxt:/home/projects/nuxt-starter-9reefq/.nuxt/routes.mjs:1:216)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/pages/runtime/plugins/router.js:10:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)

[nuxt] [request error] [unhandled] [500] layout is not defined                                               12:14:50 AM
  at eval (./pages/index.vue:17:7)  
  at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:11)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./virtual:nuxt:/home/projects/nuxt-starter-9reefq/.nuxt/routes.mjs:1:216)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/pages/runtime/plugins/router.js:10:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)

[nuxt] [request error] [unhandled] [500] layout is not defined                                               12:14:50 AM
  at eval (./pages/index.vue:17:7)  
  at ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:11)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./virtual:nuxt:/home/projects/nuxt-starter-9reefq/.nuxt/routes.mjs:1:216)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/pages/runtime/plugins/router.js:10:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)
```

**Comment by danielroe** [comment]
In general, `definePageMeta` is a macro and is not executed in the context of the file it is located in. This is so the metadata can be accessed _without_ running the script setup block.

However, in order to make this possible we can't take variables that are defined _within_ the `setup` function and move them _outside_ the function.

We _can_ however do this with imports, which have implemented.

A PR to the docs would be welcome if it is unclear: see https://nuxt.com/docs/guide/directory-structure/pages/#page-metadata.
