### ISSUE TITLE
vite error: Rollup failed to resolve import "#internal/nitro" from "virtual:nuxt:C:/.../.nuxt/paths.mjs".

### ISSUE THREAD

**Issue by jrutila** [nuxt/nuxt#22046]
### Environment

$ npx nuxi info
Nuxi 3.6.2                                                                                         
                                                                                                   
RootDir: C:/.../nghnuxt3                                   
Nuxt project info:                                                                                

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@9.5.1
- Builder:          vite
- User Config:      ssr, runtimeConfig, modules, css, build, typescript, hooks
- Runtime Modules:  @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

The vite version is vite v4.3.9 and stays the same when runnin nuxt 3.6.1 or nuxt 3.6.2

### Reproduction

I have yet to reproduce this in a minimal reproduction. Fresh nuxt 3.6.2 project does not reproduce this, as is.
I started to reproduce my environment here (https://stackblitz.com/edit/github-djfmny) but has not yet been able to get the error.

Possible culprits causing this from the release notes (my guess): https://github.com/nuxt/nuxt/pull/21922

### Describe the bug

I have a nuxt3 project that runs `generate` just fine with nuxt 3.6.1.

When I upgrade to nuxt 3.6.2, it fails the generate with following output:
```
> generate
> nuxt generate

Nuxi 3.6.2                                                                                                                                                                 7.59.34
Nuxt 3.6.2 with Nitro 2.5.2                                                                                                                                                7.59.34

 WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.                                   7.59.36  

... full log in the logs ...  

 ERROR  [vite]: Rollup failed to resolve import "vue" from "C:/.../libraries/ngh/dist/GuideParser.js".                             8.00.02  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external


 ERROR  [vite]: Rollup failed to resolve import "vue" from "C:/.../libraries/ngh/dist/GuideParser.js".                             8.00.02  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  build.rollupOptions.external
  at viteWarn (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46597:23)
  at onwarn (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.ff002a15.mjs:723:11)
  at onRollupWarning (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46618:9)
  at onwarn (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46368:13)
  at /C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:24066:13
  at Object.logger [as onLog] (/C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:25738:9)
  at ModuleLoader.handleInvalidResolvedId (/C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:24652:26)
  at /C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:24612:26
```

If I add "vue" to `nuxt.config.ts` as it suggestes, I get following error:
```
...
 ERROR  [vite]: Rollup failed to resolve import "#internal/nitro" from "virtual:nuxt:C:/.../nghnuxt3/.nuxt/paths.mjs".             8.12.20  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external


 ERROR  [vite]: Rollup failed to resolve import "#internal/nitro" from "virtual:nuxt:C:/.../nghnuxt3/.nuxt/paths.mjs".             8.12.20  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  build.rollupOptions.external
  at viteWarn (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46597:23)
  at onwarn (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.ff002a15.mjs:723:11)
  at onRollupWarning (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46618:9)
  at onwarn (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46368:13)
  at /C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:24066:13
  at Object.logger [as onLog] (/C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:25738:9)
  at ModuleLoader.handleInvalidResolvedId (/C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:24652:26)
  at /C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:24612:26
```

The workaround is to add to `nuxt.config.ts`:
```
  hooks: {
    "vite:extendConfig": (config, { isClient }) => {
      config.build.rollupOptions.external = ["vue", "#internal/nitro"]
    })
  }
```

If I do the workaround, though, and try to `npx serve .output/public`, I get the following error in the browser console output:
```
Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".
```

The same does not happen when I do not have "vue" in the `rollupOptions.external` config.

### Additional context

It is notable, that I have a project structure like this:
```
-+ dev
 |- libraries/ngh    <--- this is a library that I use in the nuxt project
 |- nghnuxt3   <-- this is the actual nuxt project
```

The first error points to the `libraries/ngh` project that has nothing to do with the vue package. But the second error is for stuff inside `.nuxt` directory and not pointing to `libraries/ngh`

The vite version is vite v4.3.9 and stays the same when generating with nuxt 3.6.1 or nuxt 3.6.2

### Logs

```shell-script
> generate
> nuxt generate

Nuxi 3.6.2                                                                                                                                                                
Nuxt 3.6.2 with Nitro 2.5.2                                                                                                                                                

 WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.                                 

ℹ Building client...                                                                                                                                                      
ℹ vite v4.3.9 building for production...                                                                                                                                  
transforming (749) node_modules\markdown-it-plain-text\index.js
[7.59.49]  WARN  [plugin:vite:resolve] Module "buffer" has been externalized for browser compatibility, imported by "C:/.../libraries/ngh/node_modules/readable-stream/lib/_stream_writable.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[7.59.49]  WARN  [plugin:vite:resolve] Module "events" has been externalized for browser compatibility, imported by "C:/.../libraries/ngh/node_modules/readable-stream/lib/_stream_readable.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[7.59.49]  WARN  [plugin:vite:resolve] Module "buffer" has been externalized for browser compatibility, imported by "C:/.../libraries/ngh/node_modules/readable-stream/lib/_stream_readable.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[7.59.49]  WARN  [plugin:vite:resolve] Module "events" has been externalized for browser compatibility, imported by "C:/.../nghnuxt3/node_modules/readable-stream/lib/_stream_readable.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

transforming (756) ..\libraries\ngh\node_modules\readable-stream\errors-browser.js
[7.59.49]  WARN  [plugin:vite:resolve] Module "events" has been externalized for browser compatibility, imported by "C:/.../libraries/ngh/node_modules/readable-stream/lib/internal/streams/stream-browser.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

[7.59.49]  WARN  [plugin:vite:resolve] Module "buffer" has been externalized for browser compatibility, imported by "C:/.../libraries/ngh/node_modules/readable-stream/lib/internal/streams/buffer_list.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.   


[7.59.49]  WARN  [plugin:vite:resolve] Module "events" has been externalized for browser compatibility, imported by "C:/.../nghnuxt3/node_modules/readable-stream/lib/internal/streams/stream-browser.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.     


[7.59.49]  WARN  [plugin:vite:resolve] Module "buffer" has been externalized for browser compatibility, imported by "C:/.../libraries/ngh/node_modules/safe-buffer/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

ℹ ✓ 845 modules transformed.                                                                                                                                              7.59.50
ℹ .nuxt/dist/client/manifest.json                                         5.57 kB │ gzip:   0.84 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/materialdesignicons-webfont.c1c004a9.woff2    396.73 kB                                                                                         7.59.51   
ℹ .nuxt/dist/client/_nuxt/materialdesignicons-webfont.80bb28b3.woff     576.75 kB                                                                                         7.59.51   
ℹ .nuxt/dist/client/_nuxt/materialdesignicons-webfont.a58ecb54.ttf    1,279.99 kB                                                                                         7.59.51
ℹ .nuxt/dist/client/_nuxt/materialdesignicons-webfont.67d24abe.eot    1,280.21 kB                                                                                         7.59.51   
ℹ .nuxt/dist/client/_nuxt/NHintBody.450a2973.css                          0.30 kB │ gzip:   0.22 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/error-500.aa16ed4d.css                          1.95 kB │ gzip:   0.74 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/error-404.23f2309d.css                          3.63 kB │ gzip:   1.12 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/_...guideId_.e4fb43b5.css                       5.41 kB │ gzip:   1.33 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/VCard.6b2e677e.css                              6.39 kB │ gzip:   1.49 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/VList.140a4b05.css                             16.07 kB │ gzip:   2.85 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/guide.f85c7fd1.css                             19.27 kB │ gzip:   2.99 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/entry.430e05f0.css                             65.12 kB │ gzip:   9.08 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/_plugin-vue_export-helper.c27b6911.js           0.09 kB │ gzip:   0.10 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/default.34a2acec.js                             0.22 kB │ gzip:   0.20 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/index.7a6dc497.js                               0.46 kB │ gzip:   0.34 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/error-500.eb3da340.js                           1.93 kB │ gzip:   1.02 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/error-404.d10d6bbd.js                           2.31 kB │ gzip:   1.19 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/VCard.54d0f15d.js                               4.29 kB │ gzip:   1.61 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/nuxt-link.f3cf3702.js                           4.36 kB │ gzip:   1.87 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/guide.734d49d3.js                              13.49 kB │ gzip:   5.42 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/_...guideId_.0fe66802.js                       19.06 kB │ gzip:   6.90 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/VList.1d23071c.js                              22.92 kB │ gzip:   7.65 kB                                                                       7.59.51
ℹ .nuxt/dist/client/_nuxt/NHintBody.vue.7a35f67a.js                     106.10 kB │ gzip:  33.65 kB                                                                       7.59.51   
ℹ .nuxt/dist/client/_nuxt/entry.90264c4b.js                             546.63 kB │ gzip: 198.41 kB                                                                       7.59.51   

 WARN                                                                                                                                                                      7.59.51  
(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

ℹ ✓ built in 12.33s                                                                                                                                                       7.59.51   
✔ Client built in 12352ms                                                                                                                                                 7.59.51   
ℹ Building server...                                                                                                                                                      7.59.51   
ℹ vite v4.3.9 building SSR bundle for production...                                                                                                                       7.59.51   
ℹ ✓ 570 modules transformed.                                                                                                                                              8.00.02   
ℹ ✓ built in 11.01s                                                                                                                                                       8.00.02   

 ERROR  [vite]: Rollup failed to resolve import "vue" from "C:/.../libraries/ngh/dist/GuideParser.js".                             8.00.02  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external


 ERROR  [vite]: Rollup failed to resolve import "vue" from "C:/.../libraries/ngh/dist/GuideParser.js".                             8.00.02  
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  build.rollupOptions.external
  at viteWarn (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46597:23)
  at onwarn (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.ff002a15.mjs:723:11)
  at onRollupWarning (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46618:9)
  at onwarn (/C:/.../nghnuxt3/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46368:13)
  at /C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:24066:13
  at Object.logger [as onLog] (/C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:25738:9)
  at ModuleLoader.handleInvalidResolvedId (/C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:24652:26)
  at /C:/.../nghnuxt3/node_modules/rollup/dist/es/shared/node-entry.js:24612:26
```

**Comment by danielroe** [comment]
It's possible this is a Windows only issue, if you can't reproduce on stackblitz. In that case, if you can get a minimal repo on GitHub, I can check it out in a Windows VM.

**Comment by jrutila** [comment]
> It's possible this is a Windows only issue, if you can't reproduce on stackblitz. In that case, if you can get a minimal repo on GitHub, I can check it out in a Windows VM.

I think we can rule Windows out as it fails also on my Azure CI pipeline that is running on ubuntu-latest.

```
[error] [vite]: Rollup failed to resolve import "vue" from "/home/vsts/work/1/s/libraries/ngh/dist/GuideParser.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
[error] [vite]: Rollup failed to resolve import "vue" from "/home/vsts/work/1/s/libraries/ngh/dist/GuideParser.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
  This is most likely unintended because it can break your application at runtime.
  If you do want to externalize this module explicitly add it to
  `build.rollupOptions.external`
  at viteWarn (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46597:23)
  at onwarn (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.ff002a15.mjs:723:11)
  at onRollupWarning (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46618:9)
  at onwarn (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46368:13)
  at node_modules/rollup/dist/es/shared/node-entry.js:24066:13
  at Object.logger [as onLog] (node_modules/rollup/dist/es/shared/node-entry.js:25738:9)
  at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:24652:26)
  at node_modules/rollup/dist/es/shared/node-entry.js:24612:26
##[error]Bash exited with code '1'.
Finishing: npm run generate
```

**Comment by jrutila** [comment]
This PR (https://github.com/nuxt/nuxt/pull/21922/files) contains changes that might have something to do with this as the failing imports are `vue` and `#internal/nitro`. Only ones left in the `optimizeDeps` and `external`.

**Comment by jrutila** [comment]
Haven't had time to reproduce this, but this is still happening with nuxt 3.6.3.

**Comment by jrutila** [comment]
I managed to reproduce this problem with nuxt 3.6.2 and 3.6.5.
Check this reproduction: https://stackblitz.com/edit/github-djfmny-nhx8t7?file=nuxt3%2FREADME.md

**Comment by danielroe** [comment]
@jrutila The thing you have reproduced is the same as https://github.com/nuxt/nuxt/issues/19525.

**Comment by danielroe** [comment]
cc: @antfu on this triggering auto import of `h` from `vue`:

```ts
zzz = zzz.map((h) => h.toUpperCase());
```

**Comment by jrutila** [comment]
Alright, I check the dup ticket. One note is that this started happening after 3.6.2. It worked on 3.6.1. But I will follow the other ticket. Thanks!

**Comment by jrutila** [comment]
This workaround fixed the issue for me: https://github.com/nuxt/nuxt/issues/18823#issuecomment-1419704343
