### ISSUE TITLE
App crashes when navigating to the same page while `useAsyncData` is loading

### ISSUE THREAD

**Issue by bombasticseahorse** [nuxt/nuxt#22094]
### Environment

- Operating System: Linux
- Node Version: v16.20.0
- Nuxt Version: 3.6.2
- Nitro Version: 2.5.2
- Package Manager: npm@9.4.2
- Builder: vite
- User Config: -
- Runtime Modules: -
- Build Modules: -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-w3e6kj

Double-click the "Test page" link.

### Describe the bug

App crashes when navigating to the same page while `useAsyncData` is loading.

**Comment by bombasticseahorse** [comment]
This bug was introduced in **v3.6.1**. Can't reproduce it in earlier versions.

**Comment by benjaminrobinet** [comment]
@bombasticseahorse Can't manage to reproduce using your stackblitz. Do you have any stacktrace you can share ?

**Comment by bombasticseahorse** [comment]
@benjaminrobinet 

https://github.com/nuxt/nuxt/assets/136930412/f561d273-c1d9-4d27-9ef8-18e909250a67

Logs:

```
chunk-BVQHDTV7.js:1449 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <RouteProvider key="/test" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/test', path: '/test', query: {…}, hash: '', name: 'test', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <NuxtLayoutProvider layoutProps= {ref: RefImpl} key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>
warn2 @ chunk-BVQHDTV7.js:1449
logError @ chunk-BVQHDTV7.js:1623
handleError @ chunk-BVQHDTV7.js:1615
callWithErrorHandling @ chunk-BVQHDTV7.js:1567
flushJobs @ chunk-BVQHDTV7.js:1763
Promise.then (async)
queueFlush @ chunk-BVQHDTV7.js:1676
queueJob @ chunk-BVQHDTV7.js:1670
(anonymous) @ chunk-BVQHDTV7.js:7208
triggerEffect @ chunk-BVQHDTV7.js:614
triggerEffects @ chunk-BVQHDTV7.js:604
triggerRefValue @ chunk-BVQHDTV7.js:1211
set value @ chunk-BVQHDTV7.js:1255
syncCurrentRoute @ router.js?v=c3cdf4ca:68
(anonymous) @ router.js?v=c3cdf4ca:73
(anonymous) @ vue-router.js:2547
runWithContext @ chunk-BVQHDTV7.js:5256
runWithContext @ vue-router.js:2485
(anonymous) @ vue-router.js:2547
triggerAfterEach @ vue-router.js:2547
(anonymous) @ vue-router.js:2475
Promise.then (async)
pushWithRedirect @ vue-router.js:2441
push @ vue-router.js:2367
navigate @ vue-router.js:1623
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
callWithAsyncErrorHandling @ chunk-BVQHDTV7.js:1573
invoker @ chunk-BVQHDTV7.js:9397
chunk-BVQHDTV7.js:9157 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (chunk-BVQHDTV7.js:9157:30)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-BVQHDTV7.js:7175:11)
    at ReactiveEffect.run (chunk-BVQHDTV7.js:423:19)
    at instance.update (chunk-BVQHDTV7.js:7212:52)
    at updateComponent (chunk-BVQHDTV7.js:7039:18)
    at processComponent (chunk-BVQHDTV7.js:6974:7)
    at patch (chunk-BVQHDTV7.js:6436:11)
    at patchSuspense (chunk-BVQHDTV7.js:2562:7)
    at Object.process (chunk-BVQHDTV7.js:2481:7)
    at patch (chunk-BVQHDTV7.js:6461:16)
parentNode @ chunk-BVQHDTV7.js:9157
componentUpdateFn @ chunk-BVQHDTV7.js:7175
run @ chunk-BVQHDTV7.js:423
instance.update @ chunk-BVQHDTV7.js:7212
updateComponent @ chunk-BVQHDTV7.js:7039
processComponent @ chunk-BVQHDTV7.js:6974
patch @ chunk-BVQHDTV7.js:6436
patchSuspense @ chunk-BVQHDTV7.js:2562
process @ chunk-BVQHDTV7.js:2481
patch @ chunk-BVQHDTV7.js:6461
componentUpdateFn @ chunk-BVQHDTV7.js:7171
run @ chunk-BVQHDTV7.js:423
instance.update @ chunk-BVQHDTV7.js:7212
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
flushJobs @ chunk-BVQHDTV7.js:1763
Promise.then (async)
queueFlush @ chunk-BVQHDTV7.js:1676
queueJob @ chunk-BVQHDTV7.js:1670
(anonymous) @ chunk-BVQHDTV7.js:7208
triggerEffect @ chunk-BVQHDTV7.js:614
triggerEffects @ chunk-BVQHDTV7.js:604
triggerRefValue @ chunk-BVQHDTV7.js:1211
set value @ chunk-BVQHDTV7.js:1255
syncCurrentRoute @ router.js?v=c3cdf4ca:68
(anonymous) @ router.js?v=c3cdf4ca:73
(anonymous) @ vue-router.js:2547
runWithContext @ chunk-BVQHDTV7.js:5256
runWithContext @ vue-router.js:2485
(anonymous) @ vue-router.js:2547
triggerAfterEach @ vue-router.js:2547
(anonymous) @ vue-router.js:2475
Promise.then (async)
pushWithRedirect @ vue-router.js:2441
push @ vue-router.js:2367
navigate @ vue-router.js:1623
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
callWithAsyncErrorHandling @ chunk-BVQHDTV7.js:1573
invoker @ chunk-BVQHDTV7.js:9397
chunk-BVQHDTV7.js:7520 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'subTree')
    at move (chunk-BVQHDTV7.js:7520:28)
    at move (chunk-BVQHDTV7.js:7520:7)
    at Object.resolve (chunk-BVQHDTV7.js:2789:11)
    at chunk-BVQHDTV7.js:2912:20
move @ chunk-BVQHDTV7.js:7520
move @ chunk-BVQHDTV7.js:7520
resolve @ chunk-BVQHDTV7.js:2789
(anonymous) @ chunk-BVQHDTV7.js:2912
Promise.then (async)
registerDep @ chunk-BVQHDTV7.js:2876
mountComponent @ chunk-BVQHDTV7.js:7003
processComponent @ chunk-BVQHDTV7.js:6963
patch @ chunk-BVQHDTV7.js:6436
componentUpdateFn @ chunk-BVQHDTV7.js:7106
run @ chunk-BVQHDTV7.js:423
instance.update @ chunk-BVQHDTV7.js:7212
setupRenderEffect @ chunk-BVQHDTV7.js:7220
mountComponent @ chunk-BVQHDTV7.js:7010
processComponent @ chunk-BVQHDTV7.js:6963
patch @ chunk-BVQHDTV7.js:6436
patchSuspense @ chunk-BVQHDTV7.js:2678
process @ chunk-BVQHDTV7.js:2481
patch @ chunk-BVQHDTV7.js:6461
componentUpdateFn @ chunk-BVQHDTV7.js:7171
run @ chunk-BVQHDTV7.js:423
instance.update @ chunk-BVQHDTV7.js:7212
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
flushJobs @ chunk-BVQHDTV7.js:1763
Promise.then (async)
queueFlush @ chunk-BVQHDTV7.js:1676
queueJob @ chunk-BVQHDTV7.js:1670
(anonymous) @ chunk-BVQHDTV7.js:7208
triggerEffect @ chunk-BVQHDTV7.js:614
triggerEffects @ chunk-BVQHDTV7.js:604
triggerRefValue @ chunk-BVQHDTV7.js:1211
(anonymous) @ chunk-BVQHDTV7.js:1371
triggerEffect @ chunk-BVQHDTV7.js:614
triggerEffects @ chunk-BVQHDTV7.js:599
triggerRefValue @ chunk-BVQHDTV7.js:1211
set value @ chunk-BVQHDTV7.js:1255
finalizeNavigation @ vue-router.js:2563
(anonymous) @ vue-router.js:2473
Promise.then (async)
pushWithRedirect @ vue-router.js:2441
push @ vue-router.js:2367
navigate @ vue-router.js:1623
callWithErrorHandling @ chunk-BVQHDTV7.js:1565
callWithAsyncErrorHandling @ chunk-BVQHDTV7.js:1573
invoker @ chunk-BVQHDTV7.js:9397
nuxt-starter-w3e6kj:1 The resource https://w-credentialless.staticblitz.com/fetch.worker.e809191e.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
content-script.js:1  CastifyDrawComponent   dispose called 
```

**Comment by yukinakato** [comment]
I'm having the same issue. Double clicking the link to the page which has `await` in `script setup` crashes the app.
Even `await new Promise(resolve => setTimeout(resolve, 3000));` can trigger the problem.
[My reproduction repository](https://github.com/yukinakato/nuxt3-await)

**Comment by danielroe** [comment]
This is the same issue as https://github.com/nuxt/nuxt/issues/21841.
