### ISSUE TITLE
Deno Deploy build fails (Nuxt 3.6.2)

### ISSUE THREAD

**Issue by AaronDewes** [nuxt/nuxt#22133]
### Environment

```
- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  yarn@3.6.1
- Builder:          vite
- User Config:      devtools, modules, ui
- Runtime Modules:  @nuxthq/ui@2.5.0, @nuxt/content@2.7.0
- Build Modules:    -
```

### Reproduction

Build any Nuxt project with the Nitro Deno Deploy preset. (This is reproducable with a project created with `nuxi create` with 0 changes)

### Describe the bug

Builds fail with the following error:

```
 ERROR  "https://deno.land/std/http/server.ts" cannot be included in manualChunks because it is resolved as an external module by the "external" option or plugins.   21:33:30

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
  at Bundle.assignManualChunks (node_modules/rollup/dist/es/shared/node-entry.js:17761:28)
  at Bundle.generateChunks (node_modules/rollup/dist/es/shared/node-entry.js:17793:20)
  at Bundle.generate (node_modules/rollup/dist/es/shared/node-entry.js:17707:39)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async node_modules/rollup/dist/es/shared/node-entry.js:26565:27
  at async catchUnfinishedHookActions (node_modules/rollup/dist/es/shared/node-entry.js:25698:16)
  at async _build (node_modules/nitropack/dist/shared/nitro.7a525996.mjs:2316:5)
  at async node_modules/nuxt/dist/index.mjs:2572:7
  at async build (node_modules/nuxt/dist/index.mjs:3721:5)
```

### Additional context

May be related to the issue described in #22127, but this also happens in Nuxt 3.6.1 and 3.6.0 (I didn't check older versions).

**Comment by danielroe** [comment]
I don't believe this is related to Nuxt; it seems to be a purely Nitro issue.

**Comment by AaronDewes** [comment]
The issue seems to be further upstream and seems to be a bug in rollup (It works in older rollup versions), I'll open up a report there.

**Comment by AaronDewes** [comment]
Fixed via https://github.com/rollup/rollup/pull/5068 as part of rollup@3.26.3 and https://github.com/unjs/nitro/pull/1438 as part of nitro@2.6.0.
