### ISSUE TITLE
Error deploying Nuxt 3.6.2 app in Cloudflare Pages

### ISSUE THREAD

**Issue by Fran-AllanSolutions** [nuxt/nuxt#22145]
### Environment

Cloudflare pages

### Reproduction

I follow this tutorial to deploy the project: https://developers.cloudflare.com/pages/framework-guides/deploy-a-nuxt-site/
Repository: https://github.com/Fran-AllanSolutions/my-nuxt-app

### Describe the bug

Hi everyone,
I am trying to deploy a new Nuxt `3.6.2` app without any changes to Cloudflare pages. Locally, it works as expected and generates the `.output/public` directory.

However, when I try to deploy this newly created app to Cloudflare Pages, it doesn’t work and throws an error saying `.output/public` directory not found.

Please take a look at the logs below.

Do you have any idea why is this happening? I appreciate any hints or ideas. 

### Logs

```shell-script
2023-07-13T20:46:32.711517Z	Cloning repository...
2023-07-13T20:46:33.586838Z	From https://github.com/ltroya-as/my-nuxt-app-cloudflare-pages
2023-07-13T20:46:33.587495Z	 * branch            751e832434e3398fc11428435343e897bedafda4 -> FETCH_HEAD
2023-07-13T20:46:33.587682Z	
2023-07-13T20:46:33.629415Z	HEAD is now at 751e832 chore: using npm
2023-07-13T20:46:33.630033Z	
2023-07-13T20:46:33.754409Z	
2023-07-13T20:46:33.785937Z	Success: Finished cloning repository files
2023-07-13T20:46:34.424978Z	Detected the following tools from environment: npm@9.5.1, nodejs@18.16.1
2023-07-13T20:46:34.425972Z	Installing project dependencies: npm clean-install --progress=false
2023-07-13T20:46:46.046897Z	
2023-07-13T20:46:46.047375Z	> postinstall
2023-07-13T20:46:46.047569Z	> nuxt prepare
2023-07-13T20:46:46.047727Z	
2023-07-13T20:46:46.160456Z	[log] Nuxi 3.6.2
2023-07-13T20:46:48.296883Z	[success] Types generated in .nuxt
2023-07-13T20:46:48.346356Z	
2023-07-13T20:46:48.346722Z	added 867 packages, and audited 868 packages in 13s
2023-07-13T20:46:48.346936Z	
2023-07-13T20:46:48.347121Z	138 packages are looking for funding
2023-07-13T20:46:48.347265Z	  run `npm fund` for details
2023-07-13T20:46:48.349005Z	
2023-07-13T20:46:48.349277Z	found 0 vulnerabilities
2023-07-13T20:46:48.369961Z	Executing user command: npm run build
2023-07-13T20:46:49.525171Z	
2023-07-13T20:46:49.525672Z	> build
2023-07-13T20:46:49.525882Z	> nuxt build
2023-07-13T20:46:49.526063Z	
2023-07-13T20:46:49.631568Z	[log] Nuxi 3.6.2
2023-07-13T20:46:49.65576Z	[log] Nuxt 3.6.2 with Nitro 2.5.2
2023-07-13T20:46:52.941572Z	[info] Building client...
2023-07-13T20:46:52.955864Z	[info] [36mvite v4.3.9 [32mbuilding for production...[36m[39m
2023-07-13T20:46:53.002644Z	[info] transforming...
2023-07-13T20:46:54.755641Z	[info] [32m✓[39m 88 modules transformed.
2023-07-13T20:46:54.897251Z	[info] rendering chunks...
2023-07-13T20:46:54.963605Z	[info] computing gzip size...
2023-07-13T20:46:54.991959Z	[info] [2m.nuxt/dist/client/[22m[32mmanifest.json                 [39m[1m[2m  1.59 kB[22m[1m[22m[2m │ gzip:  0.32 kB[22m
2023-07-13T20:46:54.992337Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[35merror-500.aa16ed4d.css  [39m[1m[2m  1.95 kB[22m[1m[22m[2m │ gzip:  0.74 kB[22m
2023-07-13T20:46:54.992521Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[35merror-404.23f2309d.css  [39m[1m[2m  3.63 kB[22m[1m[22m[2m │ gzip:  1.12 kB[22m
2023-07-13T20:46:54.992681Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[35mentry.bbc96c86.css      [39m[1m[2m 12.13 kB[22m[1m[22m[2m │ gzip:  2.49 kB[22m
2023-07-13T20:46:54.99286Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36merror-500.6f50d3fc.js   [39m[1m[2m  1.88 kB[22m[1m[22m[2m │ gzip:  0.99 kB[22m
2023-07-13T20:46:54.993171Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36merror-404.a7f57d62.js   [39m[1m[2m  6.53 kB[22m[1m[22m[2m │ gzip:  2.90 kB[22m
2023-07-13T20:46:54.993418Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36mentry.5e6c6ffa.js       [39m[1m[2m198.18 kB[22m[1m[22m[2m │ gzip: 55.58 kB[22m
2023-07-13T20:46:54.994045Z	[info] [32m✓ built in 2.04s[39m
2023-07-13T20:46:54.994559Z	[success] Client built in 2053ms
2023-07-13T20:46:54.998372Z	[info] Building server...
2023-07-13T20:46:55.0025Z	[info] [36mvite v4.3.9 [32mbuilding SSR bundle for production...[36m[39m
2023-07-13T20:46:55.033142Z	[info] transforming...
2023-07-13T20:46:56.016739Z	[info] [32m✓[39m 45 modules transformed.
2023-07-13T20:46:56.038228Z	[info] rendering chunks...
2023-07-13T20:46:56.077153Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[32mentry-styles.6cce99fb.mjs           [39m[1m[2m  0.08 kB[22m[1m[22m
2023-07-13T20:46:56.07753Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[32merror-404-styles.cf00f4cc.mjs       [39m[1m[2m  0.15 kB[22m[1m[22m
2023-07-13T20:46:56.077836Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[32merror-500-styles.a001b7ed.mjs       [39m[1m[2m  0.15 kB[22m[1m[22m
2023-07-13T20:46:56.078032Z	[info] [2m.nuxt/dist/server/[22m[32mstyles.mjs                                [39m[1m[2m  0.46 kB[22m[1m[22m
2023-07-13T20:46:56.078237Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36misland-renderer-f70c2cce.js         [39m[1m[2m  1.05 kB[22m[1m[22m[2m │ map:   1.39 kB[22m
2023-07-13T20:46:56.078426Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36merror-500-styles-1.mjs-0a86f27a.js  [39m[1m[2m  2.17 kB[22m[1m[22m[2m │ map:   0.12 kB[22m
2023-07-13T20:46:56.078605Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36merror-500-f2715e45.js               [39m[1m[2m  3.02 kB[22m[1m[22m[2m │ map:   3.78 kB[22m
2023-07-13T20:46:56.078768Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36merror-404-styles-1.mjs-6ef6e240.js  [39m[1m[2m  3.86 kB[22m[1m[22m[2m │ map:   0.12 kB[22m
2023-07-13T20:46:56.078912Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36merror-404-a8f489e4.js               [39m[1m[2m  9.67 kB[22m[1m[22m[2m │ map:  18.91 kB[22m
2023-07-13T20:46:56.079048Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36mentry-styles-1.mjs-bfad4fc1.js      [39m[1m[2m 12.38 kB[22m[1m[22m[2m │ map:   0.11 kB[22m
2023-07-13T20:46:56.079184Z	[info] [2m.nuxt/dist/server/[22m[36mserver.mjs                                [39m[1m[2m121.77 kB[22m[1m[22m[2m │ map: 167.83 kB[22m
2023-07-13T20:46:56.079328Z	[info] [32m✓ built in 1.07s[39m
2023-07-13T20:46:56.084138Z	[success] Server built in 1086ms
2023-07-13T20:46:56.100133Z	[success] [nitro] Generated public dist
2023-07-13T20:46:56.15858Z	[info] [nitro] Building Nitro Server (preset: `cloudflare-pages`)
2023-07-13T20:47:07.729681Z	[success] [nitro] Nitro server built
2023-07-13T20:47:07.796313Z	  ├─ dist/_nuxt/entry.5e6c6ffa.js (198 kB) (55.3 kB gzip)
2023-07-13T20:47:07.796829Z	  ├─ dist/_nuxt/entry.bbc96c86.css (12.1 kB) (2.47 kB gzip)
2023-07-13T20:47:07.797167Z	  ├─ dist/_nuxt/error-404.23f2309d.css (3.63 kB) (1.12 kB gzip)
2023-07-13T20:47:07.797433Z	  ├─ dist/_nuxt/error-404.a7f57d62.js (6.53 kB) (2.9 kB gzip)
2023-07-13T20:47:07.797654Z	  ├─ dist/_nuxt/error-500.6f50d3fc.js (1.88 kB) (987 B gzip)
2023-07-13T20:47:07.797837Z	  ├─ dist/_nuxt/error-500.aa16ed4d.css (1.95 kB) (735 B gzip)
2023-07-13T20:47:07.798013Z	  ├─ dist/_worker.js (890 kB) (249 kB gzip)
2023-07-13T20:47:07.798185Z	  ├─ dist/favicon.ico (4.29 kB) (510 B gzip)
2023-07-13T20:47:07.798356Z	  └─ dist/nitro.json (183 B) (150 B gzip)
2023-07-13T20:47:07.79852Z	Σ Total size: 1.12 MB (313 kB gzip)
2023-07-13T20:47:07.799825Z	[success] [nitro] You can preview this build using `npx wrangler pages dev dist/`
2023-07-13T20:47:07.800055Z	[success] [nitro] You can deploy this build using `npx wrangler pages publish dist/`
2023-07-13T20:47:07.878314Z	Finished
2023-07-13T20:47:07.879121Z	Note: No functions dir at /functions found. Skipping.
2023-07-13T20:47:07.879351Z	Validating asset output directory
2023-07-13T20:47:07.879545Z	Error: Output directory ".output/public" not found.
2023-07-13T20:47:08.896628Z	Failed: build output directory not found
```

**Comment by Hebilicious** [comment]
You need to deploy the `dist` directory with cloudflare pages.

<img width="801" alt="image" src="https://github.com/nuxt/nuxt/assets/13395944/99879a91-6c89-4a6b-98e2-deb43e852713">
Here's a working configuration.

**Comment by LTroya** [comment]
Hi @Hebilicious 

A couple of questions:
- Will SSR work deploying the dist folder?
- In 3.0, it used the `.output/public` folder to deploy to Cloudflare Pages. Does that change?
- In 3.6.2, it still generates the `.output/public`  folder. Why?

Also, checking the docs of how to deploy to Cloudflare, it references the `.output/public`

https://nitro.unjs.io/deploy/providers/cloudflare

**Comment by Hebilicious** [comment]
SSR will work. The generated directory depends on the cloudflare preset you use.

**Comment by JerryKusenberger** [comment]
+1 

I rolled back to 3.6.1 for my site deployed to cloudflare. The documentation is confusing. Is the recommendation as of nuxt 3.6.2 to switch to /dist instead of .output/public ... but only on cloudflare?

**Comment by pi0** [comment]
SSR works with the latest Cloudflare module. We generate a special entry for cloudflare in there. Please make sure to use "Nuxt" as preset:

<img width="398" alt="image" src="https://github.com/nuxt/nuxt/assets/5158436/a2a6bbe1-9ee3-459c-a650-5c29d5734a11">

**Comment by ltroya-as** [comment]
Hi @pi0 

I thought that preset was referring to Nuxt 2.

I am fixing an issue in the latest version and the `@rollup/plugin-graphql` library.

But, API will work as usual too, right?

**Comment by Hebilicious** [comment]
> +1
> 
> I rolled back to 3.6.1 for my site deployed to cloudflare. The documentation is confusing. Is the recommendation as of nuxt 3.6.2 to switch to /dist instead of .output/public ... but only on cloudflare?

- `cloudflare` and `cloudflare_module` use `.output/public`
- `cloudflare_pages` use `dist`

You can look at the output of the build command to see what's generated.

If you want to deploy your site on cloudflare pages, you will need to use the`cloudflare_pages` preset and the dist folder.
If you want to deploy your side on cloudflare workers, you will need to use wrangler and either the `cloudflare` or the `cloudflare_module` preset.

**Comment by clopezpro** [comment]
when using cloudflare_pages
```
<html>
<body>
<!--StartFragment-->
17:00:34.031 | [info] [nitro] Building Nuxt Nitro server (preset: `cloudflare-pages`)
-- | --
17:00:51.025 | [error] [nitro] Error: Cannot resolve "@img/sharp-wasm32/versions" from "/opt/buildhome/repo/node_modules/sharp/lib/utility.js" and externals are not allowed!
17:00:51.026 |  
17:00:51.026 |  
17:00:51.026 | undefined
17:00:51.028 | [error] Cannot resolve "@img/sharp-wasm32/versions" from "/opt/buildhome/repo/node_modules/sharp/lib/utility.js" and externals are not allowed!
17:00:51.029 | at Object.resolveId (node_modules/nitropack/dist/nitro.mjs:1970:17)
17:00:51.029 | at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/node-entry.js:19674:28)
17:00:51.029 | at async resolveId (node_modules/rollup/dist/es/shared/node-entry.js:18355:26)
17:00:51.029 | at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/node-entry.js:18758:15)
17:00:51.029 | at async node_modules/@rollup/plugin-commonjs/dist/es/index.js:785:16
17:00:51.029 | at async Promise.all (index 5)
17:00:51.029 | at async node_modules/@rollup/plugin-commonjs/dist/es/index.js:777:32
17:00:51.029 | at async rewriteRequireExpressionsAndGetImportBlock (node_modules/@rollup/plugin-commonjs/dist/es/index.js:1354:28)
17:00:51.030 | at async transformCommonjs (node_modules/@rollup/plugin-commonjs/dist/es/index.js:1933:23)
17:00:51.030 | at async transform (node_modules/rollup/dist/es/shared/node-entry.js:18676:16)
17:00:51.030 |  
17:00:51.030 | [error] Cannot resolve "@img/sharp-wasm32/versions" from "/opt/buildhome/repo/node_modules/sharp/lib/utility.js" and externals are not allowed!
17:00:51.186 | Failed: Error while executing user command. Exited with error code: 1
17:00:51.197 | Failed: build command exited with code: 1
17:00:52.496 | Failed: error occurred while running build command

<!--EndFragment-->
</body>
</html>

**Comment by fabianwohlfart** [comment]
How did you solve the sharp issue @clopezpro?
