### ISSUE TITLE
Prerender errors on navigateTo

### ISSUE THREAD

**Issue by some-user123** [nuxt/nuxt#22159]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rgxtrr?file=pages%2Findex.vue

### Describe the bug

I'm using
```html
<script setup>
navigateTo('/page2')
</script>
```

Rendering fails since 3.6.2 with this error:
```
 ERROR  Exiting due to prerender errors.                                                      10:02:09 PM

  at Module.prerender (node_modules/nitropack/dist/shared/nitro.1db3349c.mjs:204:11)
  at async eval (node_modules/nuxt/dist/index.mjs:2657:7)
  at async build (node_modules/nuxt/dist/index.mjs:3808:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/build.mjs:74:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/generate.mjs:51:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:64:20)
```

**Comment by messiashenrique** [comment]
> [<img alt="Fix this issue in StackBlitz Codeflow" width="117" height="20" src="https://camo.githubusercontent.com/78baa8e11fa39e8c93400da552607ff3a2ddb034a3d36fac19b771e6294c2d9f/68747470733a2f2f646576656c6f7065722e737461636b626c69747a2e636f6d2f696d672f6669785f746869735f69737375655f736d616c6c2e737667">](https://stackblitz.com/~/github.com/nuxt/nuxt/issues/22159?repros=nuxt-starter-rgxtrr) _Start a new pull request in [StackBlitz Codeflow](https://stackblitz.com/~/github.com/nuxt/nuxt/issues/22159?repros=nuxt-starter-rgxtrr)._
> 
> * [**nuxt-starter-rgxtrr** (Open reproduction)](https://stackblitz.com/edit/nuxt-starter-rgxtrr?issueRepo=nuxt/nuxt&issueNumber=22159)

Exactly. I have the same error here. It is important to remember that it occurs in the "generate".

**Comment by danielroe** [comment]
The page can't be prerendered as it immediately navigates to another page. This has always been considered an error. In 3.6.2 we enabled `nitro.prerender.failOnError` by default, which means that now this is failing your build. If you want to ignore that, you can add the page to your `nitro.prerender.ignore` array.

**Comment by some-user123** [comment]
> This has always been considered an error.

In what sense was it wrong? It was working properly...

What's the nuxt solution to redirecting a page to another one?

**Comment by danielroe** [comment]
It's not 'wrong' except that it means that the page wasn't prerendered successfully. We might move redirects out of the error category in future.

**Comment by messiashenrique** [comment]
you can add the page to your `nitro.prerender.ignore` array.

Thanks for answering.
But unfortunately it didn't work. When we add a route to "ignore", it is not generated and then the application fails.

**Comment by danielroe** [comment]
I understand. You should configure your web server to serve `/200.html` or `/404.html` for routes that do not exist in the file system. Or you can set `nitro.prerender.failOnError` to false as a temporary workaround, but that is dangerous as it may conceal real problems with your build.

**Comment by messiashenrique** [comment]
Or you can set `nitro.prerender.failOnError` to false

Strange, but even using "nitro.prerender.failOnError: false", it fails when generating the page that has the redirect (NavigateTo), in this case, the home (index.vue). See in link of StackBlitz.

[https://stackblitz.com/edit/nuxt-starter-gtsqvx?file=nuxt.config.ts](url)

See too the image with a resume of output of nuxi generate:

![stackblitz](https://github.com/nuxt/nuxt/assets/536579/ea079b9a-2d13-4c7c-a40c-f3271c6a83d2)

In advance, thank you once again for your attention.

**Comment by danielroe** [comment]
Yes, it still fails to render because it is redirected within your own code (so there is no HTML to render). This has always been the behaviour. But by setting `failOnError: false`, it won't finish with an error code so your CI will pass.

**Comment by messiashenrique** [comment]
OK. But wasn't it expected to build the page: index.vue, even though it contains the "navigateTo"? It (index.html) is not even generated.

**Comment by danielroe** [comment]
No. Because when you redirect you tell the server - do not render this page, instead render a different page.

**Comment by messiashenrique** [comment]
> No. Because when you redirect you tell the server - do not render this page, instead render a different page.

OK. So I believe there is no way to use Nuxt for the purpose I need. Because it is essential to be able to redirect to the login page, if the user is not logged in.

Anyway, thank you for your attention.

**Comment by danielroe** [comment]
You will be able to do that as long as your server serves up the 200.html file. That will perform the redirect on client side.

**Comment by messiashenrique** [comment]
Now yes! I used "ssr: false" and the generate worked correctly.
Thanks for help!

**Comment by Orillian** [comment]
> Now yes! I used "ssr: false" and the generate worked correctly. Thanks for help!

I found that if you used the following you could still use SSR for the rest of the application. Just in case you still needed to:

`routeRules: {
    '/': {ssr: false}
  }`
