### ISSUE TITLE
Has the official staff tried to download nuxt3 from the official website and use npm run build to package the file and then send pictures or word, ppt and other types of files exceeding 10kb?

### ISSUE THREAD

**Issue by taishuai110** [nuxt/nuxt#22188]
### Environment

node 18.16.0
nuxt  3.6.3
nuxi 3.6.3
nitro 2.5.2

### Reproduction

无

### Describe the bug

Why not try to download an initial project package from nuxt3 official website, and then configure an element-plus plug-in in it, and create a file sending function with plus, and open the project with npm run dev. However, the use of npm run build can not exceed 10kb pictures or non-TXT files, in which many experiments, you can even find that this error will appear before the api request, meaning that any api interface can appear this error, do not need the real api interface. Looking for a long time, finally found the nuxt3 itself left behind the problem, but I think I am not qualified to move the nuxt3 source code, I have not the ability. I wish the people developing the nuxt3 framework would pay attention to this problem

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] fetch failed (url)
  at async sendProxy (/C:/Users/ASUS/Desktop/SRRNuxt/newNuxt3/.output/server/node_modules/h3/dist/index.mjs:521:20)
  at async Object.handler (/C:/Users/ASUS/Desktop/SRRNuxt/newNuxt3/.output/server/node_modules/h3/dist/index.mjs:1284:19)
  at async Server.toNodeHandle (/C:/Users/ASUS/Desktop/SRRNuxt/newNuxt3/.output/server/node_modules/h3/dist/index.mjs:1359:7)
[nuxt] [request error] [unhandled] [500] fetch failed (url)
  at async sendProxy (/C:/Users/ASUS/Desktop/SRRNuxt/newNuxt3/.output/server/node_modules/h3/dist/index.mjs:521:20)
  at async Object.handler (/C:/Users/ASUS/Desktop/SRRNuxt/newNuxt3/.output/server/node_modules/h3/dist/index.mjs:1284:19)
  at async Server.toNodeHandle (/C:/Users/ASUS/Desktop/SRRNuxt/newNuxt3/.output/server/node_modules/h3/dist/index.mjs:1359:7)
```

**Comment by danielroe** [comment]
let's track in your first issue: https://github.com/nuxt/nuxt/issues/21936
