### ISSUE TITLE
Cannot stringify arbitrary non-POJOs Unexpected response type data Blob { size: 2, type: 'application/xhtml+xml' } !!!

### ISSUE THREAD

**Issue by JL-Code** [nuxt/nuxt#22202]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, devServer, nitro
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://github.com/JL-Code/nuxt-workshop

Run the project and you will see the error message

### Describe the bug

API: https://gameusd.com/api/product/categories/navigation
![image](https://github.com/nuxt/nuxt/assets/14163944/5fa597bc-df3d-46a2-8956-1ee939e97627)

In fact, the API return should be an application/JSON, which actually results in a Blob type.
↓↓↓↓↓
data Blob { size: 2, type: 'application/xhtml+xml' }
![image](https://github.com/nuxt/nuxt/assets/14163944/9a73ea76-509b-4fcc-a1bf-5e7a349799d7)

### Logs

```shell-script
Cannot stringify arbitrary non-POJOs

at flatten (/D:/Workspace/nuxt-workshop/node_modules/devalue/src/stringify.js:166:43)
at flatten (/D:/Workspace/nuxt-workshop/node_modules/devalue/src/stringify.js:166:43)
at flatten (/D:/Workspace/nuxt-workshop/node_modules/devalue/src/stringify.js:60:39)
at stringify (/D:/Workspace/nuxt-workshop/node_modules/devalue/src/stringify.js:178:16)
at renderPayloadJsonScript (/D:/Workspace/nuxt-workshop/.nuxt/dev/index.mjs:1060:32)
at /D:/Workspace/nuxt-workshop/.nuxt/dev/index.mjs:984:29
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /D:/Workspace/nuxt-workshop/.nuxt/dev/index.mjs:582:22
at async Object.handler (/D:/Workspace/nuxt-workshop/node_modules/h3/dist/index.mjs:1284:19)
```

**Comment by huang-julien** [comment]
Hi you're reproduction doesn't seems up to date, did you forget to push ?

**Comment by danielroe** [comment]
Try setting `responseType: 'text'` in your useFetch options.

**Comment by JL-Code** [comment]
> Hi you're reproduction doesn't seems up to date, did you forget to push ?

Sorry, I pushed it now. I think I have found the cause of the problem.
<img width="620" alt="image" src="https://github.com/nuxt/nuxt/assets/14163944/2c9bf1b5-9169-4261-86a0-87b87a8169f3">
The application/xHTML response is obtained by accessing the API through a browser, while the application/json response is obtained through Postman I think that's the reason.

Gameusd.com is a nuxt app that is deployed through node. output/server/index.mjs

**Comment by JL-Code** [comment]
> Try setting `responseType: 'text'` in your useFetch options.

This does not solve the problem.
I directly access the API through a browser and receive an application/xHTML response, while through Postman it is an application/JSON response, which is a strange difference. 

<img width="1360" alt="image" src="https://github.com/nuxt/nuxt/assets/14163944/c7415604-86c5-4e1c-b14b-b6629f4493a2">

I proxy my API through routeRules on gameusd.com (Nuxt App)

**Comment by Flexusma** [comment]
I am experiencing a similar problem after upgrading from 3.4.3 to 3.6.5. I have a composable that returns a useState which seems to cause the folowing error:
```
[nuxt] [request error] [unhandled] [500] Cannot stringify arbitrary non-POJOs                                                                                                                                                                                                                                                                                                               5:30:55 PM
  at flatten (./node_modules/devalue/src/stringify.js:138:13)  
  at flatten (./node_modules/devalue/src/stringify.js:166:43)  
  at flatten (./node_modules/devalue/src/stringify.js:166:43)  
  at flatten (./node_modules/devalue/src/stringify.js:60:39)  
  at stringify (./node_modules/devalue/src/stringify.js:178:16)  
  at renderPayloadJsonScript (./.nuxt/dev/index.mjs:2192:32)  
  at ./.nuxt/dev/index.mjs:2116:29  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ./.nuxt/dev/index.mjs:551:22  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1284:19)

```

composable:
```js
export const useAuth = () =>{
...
    let auth = new Auth();
...
    let state = useState('Auth', () => auth);
    watch(state, ()=>{
        ...
    }, {deep:true})
    return state;
}
````

Auth class:
```js
export class Auth{
    token: string | null = null;
    expires:Date = new Date();
    isAuth:boolean = false;

    toJSON () {
        return {...this};
    }
}
```


Setting `experimental.renderJsonPayloads:false` removes the issue :/

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/21832 - we need to document this better, but you basically should provide reviver/reducer functions for your custom auth class.

**Comment by andreasvirkus** [comment]
@danielroe could you consider re-opening this? I'm experiencing a similar issue with `3.7.0` - I have a simple handler in `server/api/connection/index.get.ts`

```js
export default defineEventHandler(async (event) => {
  const session = await getServerSession(event)
  if (!session) throw createError({ statusMessage: 'Unauthenticated', statusCode: 401 })

  const user = await knex<User>('users').where('email', session.user?.email).first()

  return getAccountConnection(user.id)
})
```

The `getAccountConnection` method logs the POJO just fine, it looks something like this
```
'get connection for account ed6107ce-0df6-425b-9a40-b800b3b6daa8' {
  id: 'ed6107ce-0df6-425b-9a40-b800b3b6daa8',
  name: 'Demo',
  subscription: 'TRIAL',
  external: 'slack-.....',
  token: 'xoxb-....'
}
```


And in my `index.vue` I load it with useFetch

```js
const router = useRouter()
const { data: account } = await useFetch('/api/connection')

if (!account.value?.external) router.replace('/app/integrate/slack')
```

Which throws a 500
```js
[nuxt] [request error] [unhandled] [500] Cannot stringify arbitrary non-POJOs
  at flatten (/Users/anc/code/matchbox/monorepo/node_modules/devalue/src/stringify.js:138:13)
  at flatten (/Users/anc/code/matchbox/monorepo/node_modules/devalue/src/stringify.js:166:43)
  at flatten (/Users/anc/code/matchbox/monorepo/node_modules/devalue/src/stringify.js:166:43)
  at flatten (/Users/anc/code/matchbox/monorepo/node_modules/devalue/src/stringify.js:60:39)
  at stringify (/Users/anc/code/matchbox/monorepo/node_modules/devalue/src/stringify.js:178:16)
  at renderPayloadJsonScript (/Users/anc/code/matchbox/monorepo/node_modules/nuxt/dist/core/runtime/nitro/renderer.js:356:32)
  at <anonymous> (/Users/anc/code/matchbox/monorepo/node_modules/nuxt/dist/core/runtime/nitro/renderer.js:229:318)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at <anonymous> (/Users/anc/code/matchbox/monorepo/node_modules/nitropack/dist/runtime/renderer.mjs:20:22)
  at async Object.handler (/Users/anc/code/matchbox/monorepo/node_modules/h3/dist/index.mjs:1630:19)
```

As for others, disabling `experimental.renderJsonPayloads` fixes it...

Or should I post this comment to https://github.com/nuxt/nuxt/issues/21832? I feel plain/simple objects should work out of the box without requiring users to maintain their own plugins that stringify and parse the data 🤔

**Comment by danielroe** [comment]
@andreasvirkus I'm not sure it's linked to the response from that event handler. (We don't use revive/reduce on server responses, and they should come in as pure JSON, as you say.)

Feel free to raise an issue with a reproduction, but I suspect it's coming from a different place.

**Comment by Akgurban** [comment]
> Try setting `responseType: 'text'` in your useFetch options.



> Try setting `responseType: 'text'` in your useFetch options.

thanks very much  it works
