### ISSUE TITLE
upgrade breaks my build in local and in vercel

### ISSUE THREAD

**Issue by CareTiger** [nuxt/nuxt#22237]
### Environment

Nuxt project info:                                                                                                                                      9:36:05 PM

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.8.0
- Builder:          vite
- User Config:      extends, webVitals, typescript, devtools, app, tailwindcss, modules, runtimeConfig
- Runtime Modules:  @nuxthq/ui@2.6.0, @nuxt/content@2.7.1, @nuxtjs/web-vitals@0.2.6, @nuxtjs/fontaine@0.4.0, @nuxtjs/supabase@0.3.8, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1
- Build Modules:    -
------------------------------

### Reproduction

vercel output -
```
Running "npm run build"
21:33:33.574 |  
21:33:33.574 | > build
21:33:33.574 | > nuxt build
21:33:33.574 |  
21:33:33.649 | [log] Nuxi 3.6.5
21:33:33.672 | [log] Nuxt 3.6.5 with Nitro 2.5.2
21:33:34.953 | [info] [nuxt:tailwindcss] Using Tailwind CSS from ~/assets/css/tailwind.css
21:33:36.924 | [error] Cannot find module 'postcss-custom-properties'
21:33:36.924 | Require stack:
21:33:36.924 | - /vercel/path0/app/index.js
21:33:36.924 | Require stack:
21:33:36.925 | - index.js
21:33:36.925 | at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
21:33:36.925 | at Function.resolve (node:internal/modules/cjs/helpers:116:19)
21:33:36.925 | at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:250100)
21:33:36.925 | at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2230:29)
21:33:36.925 | at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2240:24)
21:33:36.925 | at node_modules/@nuxt/vite-builder/dist/shared/vite-builder.9774705b.mjs:851:20
21:33:36.925 | at Array.map (<anonymous>)
21:33:36.925 | at resolveCSSOptions (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.9774705b.mjs:850:167)
21:33:36.925 | at bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.9774705b.mjs:1314:14)
21:33:36.926 | at async build (node_modules/nuxt/dist/index.mjs:3793:5)
```

### Describe the bug

upgrading to latest two versions does not work in dev and hosting.

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

This doesn't seem like a Nuxt issue - perhaps the tailwind module upgraded at the same time? Does it make a difference if you explicitly add `postcss-custom-properties`?

**Comment by CareTiger** [comment]
Not a nuxt issue.
