### ISSUE TITLE
Failed to resolve entry for package "crypto"/"zlib"

### ISSUE THREAD

**Issue by fabis94** [nuxt/nuxt#22250]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@3.2.0`
- Builder:          `vite`
- User Config:      `typescript`, `modules`, `runtimeConfig`, `alias`, `vite`, `app`, `routeRules`, `build`, `hooks`
- Runtime Modules:  `@nuxt/devtools@0.2.5`, `@nuxtjs/tailwindcss@6.3.0`, `~/lib/core/nuxt-modules/apollo/module.ts`, `@speckle/ui-components-nuxt@0.0.1`
- Build Modules:    `-`

### Reproduction

https://github.com/specklesystems/speckle-server/pull/1714

Setup guide: https://speckle.guide/dev/server-local-dev.html#steps
Except skip Step 10 and run `yarn dev` only in the `frontend-2` package, cause we're not interested in anything else.

To run the app properly so that it works in the browser, you'll also have to run the API: Run `yarn dev` in the `packages/server` folder.

### Describe the bug

For some reason Nuxt is trying to bundle `crypto` and `zlib` in when running the dev server. This is the output we get when running the dev server on Win11 w/ WSL2:

```
Nuxi 3.3.1
Nuxt 3.3.1 with Nitro 2.3.1

  > Local:    http://localhost:8081/ 
  > Network:  http://172.26.156.166:8081/

✔ Nuxt Devtools is enabled v0.2.5 (experimental)
ℹ Using Tailwind CSS from ~/assets/css/tailwind.css
ℹ Tailwind Viewer: http://0.0.0.0:8081/_tailwind/
✔ Nitro built in 471 ms
✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:21:
      1365 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22005:11)
    at resolvePackageEntry (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22002:5)
    at tryNodeResolve (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:21737:20)
    at Context.resolveId (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:21488:28)
    at Object.resolveId (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:41612:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:61988:21
    at async file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22323:34
    at async requestCallbacks.on-resolve (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:22)
    at async handleRequest (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:727:13)

  This error came from the "onResolve" callback registered here:

    node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22303:19)
    at handlePlugins (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1287:21)
    at buildOrServeImpl (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:974:5)
    at Object.buildOrServe (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:780:5)
    at /home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:2131:14)
    at build (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1978:51)
    at runOptimizeDeps (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:42966:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/jiti/dist/jiti.js:1:70618:
      1 │ ...ule.exports=require("crypto")},fs:module=>{"use ...
        ╵                        ~~~~~~~~

✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:21:
      1365 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22005:11)
    at resolvePackageEntry (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22002:5)
    at tryNodeResolve (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:21737:20)
    at Context.resolveId (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:21488:28)
    at Object.resolveId (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:41612:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:61988:21
    at async file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22323:34
    at async requestCallbacks.on-resolve (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:22)
    at async handleRequest (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:727:13)

  This error came from the "onResolve" callback registered here:

    node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22303:19)
    at handlePlugins (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1287:21)
    at buildOrServeImpl (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:974:5)
    at Object.buildOrServe (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:780:5)
    at /home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:2131:14)
    at build (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1978:51)
    at runOptimizeDeps (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:42966:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/vite/dist/node/index.js:29:7:
      29 │ import 'crypto';
         ╵        ~~~~~~~~

✘ [ERROR] Could not resolve "./zlib_bindings"

    ../../node_modules/zlib/lib/zlib.js:1:25:
      1 │ module.exports = require('./zlib_bindings');
        ╵                          ~~~~~~~~~~~~~~~~~

✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:21:
      1365 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22005:11)
    at resolvePackageEntry (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22002:5)
    at tryNodeResolve (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:21737:20)
    at Context.resolveId (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:21488:28)
    at Object.resolveId (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:41612:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:61988:21
    at async file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22323:34
    at async requestCallbacks.on-resolve (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:22)
    at async handleRequest (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:727:13)

  This error came from the "onResolve" callback registered here:

    node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22303:19)
    at handlePlugins (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1287:21)
    at buildOrServeImpl (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:974:5)
    at Object.buildOrServe (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:780:5)
    at /home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:2131:14)
    at build (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1978:51)
    at runOptimizeDeps (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:42966:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/esbuild/lib/main.js:1923:21:
      1923 │ var crypto = require("crypto");
           ╵                      ~~~~~~~~

✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:21:
      1365 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22005:11)
    at resolvePackageEntry (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22002:5)
    at tryNodeResolve (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:21737:20)
    at Context.resolveId (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:21488:28)
    at Object.resolveId (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:41612:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:61988:21
    at async file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22323:34
    at async requestCallbacks.on-resolve (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:22)
    at async handleRequest (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:727:13)

  This error came from the "onResolve" callback registered here:

    node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22303:19)
    at handlePlugins (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1287:21)
    at buildOrServeImpl (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:974:5)
    at Object.buildOrServe (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:780:5)
    at /home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:2131:14)
    at build (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1978:51)
    at runOptimizeDeps (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:42966:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/vite/dist/node/chunks/dep-e8f070e8.js:27:25:
      27 │ import require$$5$1 from 'crypto';
         ╵                          ~~~~~~~~

✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:21:
      1365 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22005:11)
    at resolvePackageEntry (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22002:5)
    at tryNodeResolve (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:21737:20)
    at Context.resolveId (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:21488:28)
    at Object.resolveId (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:41612:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:61988:21
    at async file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22323:34
    at async requestCallbacks.on-resolve (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:22)
    at async handleRequest (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:727:13)

  This error came from the "onResolve" callback registered here:

    node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:22303:19)
    at handlePlugins (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1287:21)
    at buildOrServeImpl (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:974:5)
    at Object.buildOrServe (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:780:5)
    at /home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:2131:14)
    at build (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1978:51)
    at runOptimizeDeps (file:///home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-a6e90259.js:42966:26)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/vite/dist/node/chunks/dep-8124a809.js:5:23:
      5 │ import require$$5 from 'crypto';
        ╵                        ~~~~~~~~


 ERROR  error while updating dependencies:
Error: Build failed with 6 errors:
../../node_modules/zlib/lib/zlib.js:1:25: ERROR: Could not resolve "./zlib_bindings"
node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.
node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.
node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.
node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1365:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.
...
    at failureErrorWithLog (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1604:15)
    at /home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1054:7)
    at /home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/home/fabis/Code/speckle/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
```

It doesn't really make sense to me, because the errors come from the build process itself (thrown from esbuild/jiti) not one of our dependencies. 

The workaround we had for now was adding aliases for `crypto` and `zlib` in the nuxt config like so:

```
  alias: {
    crypto: require.resolve('rollup-plugin-node-builtins'),
    zlib: require.resolve('browserify-zlib')
  },
```

You can uncomment these lines in that reproduction PR I shared. But this introduced a new and different error:

```
 ERROR  Failed to resolve import "fsevents" from "node_modules/.vite/deps/chunk-GYCMMED4.js?v=1b5ee208". Does the file exist? (x6)
```

That's on Win11 w/ WSL2. On OSX it looks a bit different, but also relates to `fsevents` being bundled for some reason:

```
✘ [ERROR] No loader is configured for ".node" files: node_modules/fsevents/fsevents.node
[0] 
[0]     node_modules/fsevents/fsevents.js:13:23:
[0]       13 │ const Native = require("./fsevents.node");
[0]          ╵                        ~~~~~~~~~~~~~~~~~
[0] 
[0] 
[0]  ERROR  error while updating dependencies:
[0] Error: Build failed with 1 error:
[0] node_modules/fsevents/fsevents.js:13:23: ERROR: No loader is configured for ".node" files: node_modules/fsevents/fsevents.node
[0]     at failureErrorWithLog (/Users/andrew/Documents/GitHub/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1604:15)
[0]     at /Users/andrew/Documents/GitHub/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1056:28
[0]     at runOnEndCallbacks (/Users/andrew/Documents/GitHub/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1476:61)
[0]     at buildResponseToResult (/Users/andrew/Documents/GitHub/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1054:7)
[0]     at /Users/andrew/Documents/GitHub/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:1166:14
[0]     at responseCallbacks.<computed> (/Users/andrew/Documents/GitHub/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:701:9)
[0]     at handleIncomingPacket (/Users/andrew/Documents/GitHub/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:756:9)
[0]     at Socket.readFromStdout (/Users/andrew/Documents/GitHub/speckle-server/packages/frontend-2/node_modules/@nuxt/vite-builder/node_modules/vite/node_modules/esbuild/lib/main.js:677:7)
[0]     at Socket.emit (node:events:513:28)
[0]     at Socket.emit (node:domain:489:12)
```

We ignored it for a while because everything seemed to work fine, but our devs on OSX have had real app-breaking issues because of this.

For one of our devs the app, when ran, shows the following error in the console: `GET http://127.0.0.1:8081/_nuxt/node_modules/.vite/deps/vue.js?v=4d5b30ef net::ERR_ABORTED 504 (Gateway Timeout)`

And for some reason `node_modules/.vite/` is pretty much empty for them. It only contains a `deps_temp` folder with a nearly empty package.json inside of it, none of the optimized deps.

We think its related to the `fsevents` issue, because after adding `fsevents` to `vite.optimizeDeps.exclude` the app started working (even tho new console errors appeared).

**So as far as I can tell, something is trying to bundle in zlib/crypto/fsevents in our nuxt build and this is breaking everything**

**Comment by fabis94** [comment]
@danielroe I'll try to create one, but that might take a little bit.

In the meanwhile do you maybe have some tips for how I could troubleshoot this further? The error messages don't make sense to me, because the stack traces come from `esbuild` not from within my app, so there doesn't seem to be any way to figure out which dependency is causing the issue from those.

Is there a specific procedure for debugging something like this further?

**Comment by fabis94** [comment]
Also - one thing that makes me skeptical about this being a dependency issue is that there is no problem in the prod build. This only happens when running the dev server

**Comment by fabis94** [comment]
@danielroe I think I figured out the reason. Nuxt is trying to include `./.storybook/main.ts` into the build, which is supposed to only run on node and is not even supposed to be used in any way in the actual Nuxt build. Why is Nuxt trying to include it, if there's nothing in the project trying to import that file?

I can't figure out how to exclude it from the build either - the `ignore` option in the nuxt config doesn't seem to work, maybe it only ignores files in the production/rollup build?

**Comment by danielroe** [comment]
Ah, that makes sense. I think it might be tailwindcss itself though, rather than the Nuxt integration.

Glad you were able to resolve it ❤️

**Comment by wodepig** [comment]
I also encountered the same error today because the parameter of the method name was wrong.
我今天也遇到了同样的报错,原因是方法名的参数错误!!
![image](https://github.com/user-attachments/assets/788b1f06-8445-486d-bf0f-b92b19b95ed4)
