### ISSUE TITLE
Adding async middleware via plugin leads to broken middleware

### ISSUE THREAD

**Issue by Aietes** [nuxt/nuxt#22359]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  npm@9.4.2
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-2ch7rd?file=plugins%2FauthRedirect.ts

### Describe the bug

When I create an async middleware via a plugin, it doesn't work as expected on the server. I need to use an async composable in the middleware. After awaiting the result of the composable, all following composables stop working, and respectively the router breaks, since things like returning navigateTo() are no longer possible. The exact same middleware works fine when not added via a plugin, but I need to add it via plugin for a Nuxt module. The code: `plugins/authRedirect.ts`:

```ts
export default defineNuxtPlugin({
  name: 'auth-redirect',
  setup() {
    addRouteMiddleware(
      'global-auth',
      async (to) => {
        const user = await useAuth()
        if (to.path !== '/login' && !user) {
          console.log('Redirecting to login')
          return navigateTo('/login')
        }
      },
      { global: true }
    )
  },
})
```

The error:

```
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables`.

at useRouter (./node_modules/nuxt/dist/app/composables/router.js:16:32)
at Module.navigateTo (./node_modules/nuxt/dist/app/composables/router.js:98:18)
at __vite_ssr_import_0__.addRouteMiddleware.global (./plugins/authRedirect.ts:14:40)
at async Object.callAsync (./node_modules/unctx/dist/index.mjs:91:16)
at async eval (./node_modules/nuxt/dist/pages/runtime/plugins/router.js:133:26)
```

This error comes from the server, when only running the router on the client with `if(process.client)` it works. But of course, this workaround leads to hydration errors, and I would like to avoid that. Is there something I'm doing wrong in the way I create the middleware via a plugin?

**Comment by danielroe** [comment]
Here's an example of how to handle calling a composable that requires access to the Nuxt context:

```diff
  export default defineNuxtPlugin({
    name: 'auth-redirect',
    setup() {
      addRouteMiddleware(
        'global-auth',
        async (to) => {
+         const nuxtApp = useNuxtApp()
          const user = await useAuth()
          if (to.path !== '/login' && !user) {
            console.log('Redirecting to login')
-           return navigateTo('/login')
+           return nuxtApp.runWithContext(() => navigateTo('/login'))
          }
        },
        { global: true }
      )
    },
  })
```

Alternatively, this should also work:

```diff
  export default defineNuxtPlugin({
    name: 'auth-redirect',
    setup() {
      addRouteMiddleware(
        'global-auth',
-       async (to) => {
+       defineNuxtRouteMiddleware(async (to) => {
          const user = await useAuth()
          if (to.path !== '/login' && !user) {
            console.log('Redirecting to login')
            return navigateTo('/login')
          }
-       },
+       }),
        { global: true }
      )
    },
  })
```

**Comment by Aietes** [comment]
Thank you for your help! 🥇

**Comment by danielroe** [comment]
No problem! 😊
