### ISSUE TITLE
Nuxt welcome page throws error 500 out of box on fresh install

### ISSUE THREAD

**Issue by kid-alan** [nuxt/nuxt#22381]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.5.1`
- Builder:          `vite`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

It also reproduced on another machine with Fedora.

### Reproduction

```
# Nuxi 3.6.5
npx nuxi@latest init project
cd project
npm i
npm run dev
# Go to http://localhost:3000 and observe error 500
```

### Describe the bug

Fresh Nuxt installation using ["Nuxt get started"](https://nuxt.com/docs/getting-started/installation) instruction throws a 500 error out of box.

It shows the following error when running `npm run build`
```
 ERROR  [vite:vue] Element is missing end tag.                                                                     11:37:35 PM
file: /Users/user/whatever/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue:40:11014


 ERROR  Element is missing end tag.                                                                                11:37:35 PM

  at createCompilerError (node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:17:17)
  at emitError (node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1446:5)
  at parseElement (node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1022:5)
  at parseChildren (node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:840:18)
  at parseElement (node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:999:20)
  at parseChildren (node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:840:18)
  at parseElement (node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:999:20)
  at parseChildren (node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:840:18)
  at parseElement (node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:999:20)
  at parseChildren (node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:840:18)
```

It seems like this part is somehow gets recompiled and is being interpreted like it is a component, instead of HTML text.

[This]
```
&lt;NuxtWelcome /&gt;
```
Becomes this in `/Users/user/project/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue`
```
<NuxtWelcome />
```
And it attempts to build it as a component, instead of plain text.

I might be wrong on the details, but I was able easily reproduce this on two different machines just running the commands above.

**Comment by cschweda** [comment]
Same error. Fresh install.

**Comment by danielroe** [comment]
Now resolved - see https://github.com/nuxt/nuxt/issues/22383#issuecomment-1656540496 for how to update.
