### ISSUE TITLE
[Nuxt 3.6.5] `nuxt build`, fail at Nitro step for "undefined"

### ISSUE THREAD

**Issue by djimnz** [nuxt/nuxt#22452]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.8.1`
- Builder:          `vite`
- User Config:      `telemetry`, `app`, `css`, `modules`, `build`, `vite`, `typescript`, `postcss`, `runtimeConfig`, `googleFonts`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.8.0`, `@nuxtjs/google-fonts@3.0.2`, `@formkit/nuxt@0.17.5`
- Build Modules:    `-`

### Reproduction

Difficult to provide a way to reproduce it since my repo is private (sorry), but here is the package.json:
```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/google-fonts": "^3.0.2",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "autoprefixer": "^10.4.13",
    "nuxt": "^3.5.1",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.3.3",
    "vue-gtag-next": "^1.14.0"
  },
  "dependencies": {
    "@bugsnag/js": "^7.20.0",
    "@formkit/nuxt": "^0.17.5",
    "@fortawesome/fontawesome-pro": "^6.4.2",
    "@fortawesome/fontawesome-svg-core": "^6.4.2",
    "@fortawesome/pro-light-svg-icons": "^6.4.2",
    "@fortawesome/pro-regular-svg-icons": "^6.4.2",
    "@fortawesome/pro-solid-svg-icons": "^6.4.2",
    "@fortawesome/vue-fontawesome": "^3.0.3",
    "@headlessui/vue": "^1.7.15",
    "@hotjar/browser": "^1.0.9",
    "@mailchimp/mailchimp_marketing": "^3.0.80",
    "@openreplay/tracker": "^9.0.0",
    "contentful": "^10.4.0",
    "mixpanel-browser": "^2.46.0",
    "preline": "^1.9.0"
  }
}
```

As well as the nuxt config:
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  app: {
    head: {
      script: [
        {
          src: "/preline/preline.js",
          body: true,
          defer: true,
          crossorigin: "anonymous",
          "data-cfasync": false,
        },
        {
          type: "text/javascript",
          innerHTML: `
            window.$crisp = []; window.CRISP_WEBSITE_ID =
            "..."; (function () { d = document; s =
            d.createElement("script"); s.src = "https://client.crisp.chat/l.js";
            s.async = 1; d.getElementsByTagName("head")[0].appendChild(s); })();
          `,
        }, // crips website id obfuscated for the github issue
      ],
    },
  },
  css: [
    "~/assets/css/main.css",
    "@fortawesome/fontawesome-svg-core/styles.css",
  ],
  modules: ["@nuxtjs/tailwindcss", "@nuxtjs/google-fonts", "@formkit/nuxt"],
  build: {
    transpile: ["@fortawesome/vue-fontawesome"],
  },
  vite: {
    build: {
      rollupOptions: {
        output: {
          chunkFileNames: "_nuxt/[hash].js", // can be .mjs or .js
          assetFileNames: "_nuxt/[hash][extname]",
        },
      },
    },
  },
  typescript: {
    tsConfig: {
      compilerOptions: {
        moduleResolution: "bundler",
      },
    },
  },
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  runtimeConfig: {
    mailchimpApiKey: "",
    mailchimpServer: "",
    mailchimpAudienceId: "",
    public: {
      gtagId: "",
      mixpanelToken: "",
      ctfSpaceId: "",
      ctfCdaAccessToken: "",
      bugsnagApiKey: "",
      openreplayProjectKey: "",
    },
  },
  googleFonts: {
    display: "swap",
    download: process.env.NODE_ENV === "production",
    overwriting: false,
    stylePath: "css/fonts.css",
    families: {
      Inter: [100, 200, 300, 400, 500, 600, 700, 800, 900],
      "Noto+Sans+KR": [100, 300, 400, 500, 700, 900],
    },
  },
});
```

### Describe the bug

Running the command `nuxt build` break at Nitro step with an unclear error `undefined`.
I had no issue from my previous Nuxt version 3.5.3.

Is there a way to get a more clear error backtrace, or is anyone already had this issue after upgrading?

Thank you!

### Logs

```shell-script
9:25:10 AM: [info] .nuxt/dist/server/_nuxt/f947eaf0.js   467.79 kB │ map:   0.09 kB
9:25:10 AM: [info] ✓ built in 3.97s
9:25:10 AM: [success] Server built in 3988ms
9:25:10 AM: [success] [nitro] Generated public dist
9:25:10 AM: [nitro] Nitro now uses `isr` option to configure ISR behavior on Netlify. Backwards-compatible support for `static` and `swr` support with Builder Functions will be removed in the future versions. Set `future.nativeSWR: true` nitro config disable this warning.
9:25:10 AM: [info] [nitro] Building Nitro Server (preset: `netlify`)
9:25:19 AM: [error] [nitro] RangeError: Maximum call stack size exceeded
9:25:19 AM: undefined
9:25:19 AM: [error] Maximum call stack size exceeded
9:25:19 AM:   at BinaryExpression.parseNode (node_modules/rollup/dist/es/shared/node-entry.js:5914:14)
9:25:19 AM:   at new NodeBase (node_modules/rollup/dist/es/shared/node-entry.js:5831:14)
9:25:19 AM:   at new BinaryExpression (node_modules/rollup/dist/es/shared/node-entry.js:9294:1)
9:25:19 AM:   at BinaryExpression.parseNode (node_modules/rollup/dist/es/shared/node-entry.js:5945:29)
9:25:19 AM:   at new NodeBase (node_modules/rollup/dist/es/shared/node-entry.js:5831:14)
9:25:19 AM:   at new BinaryExpression (node_modules/rollup/dist/es/shared/node-entry.js:9294:1)
9:25:19 AM:   at BinaryExpression.parseNode (node_modules/rollup/dist/es/shared/node-entry.js:5945:29)
9:25:19 AM:   at new NodeBase (node_modules/rollup/dist/es/shared/node-entry.js:5831:14)
9:25:19 AM:   at new BinaryExpression (node_modules/rollup/dist/es/shared/node-entry.js:9294:1)
9:25:19 AM:   at BinaryExpression.parseNode (node_modules/rollup/dist/es/shared/node-entry.js:5945:29)
```
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/18507.

Rollup is highly memory intensive, and that is likely the issue here. You can try reproducing locally by manually setting `NODE_OPTIONS="--max-old-space-size=6144"` (or some other value) but this will only be a helpful step if you try modifying your app to make it take less memory to build.

**Comment by danielroe** [comment]
You likely want `tagPosition` instead of `body`.

**Comment by danielroe** [comment]
No problem 😊
