### ISSUE TITLE
Nuxt module, application cannot find installed module

### ISSUE THREAD

**Issue by Eugene313** [nuxt/nuxt#22626]
### Environment

Module

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.20.0`
- Nuxt Version:     `^3.6.5`
- Nitro Version:    `-`
- Package Manager:  `pnpm@8.3.1`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/module-builder @nuxt/kit @vueuse/nuxt `
------------------------------

Application

- Operating System: `Windows_NT`
- Node Version:     `v16.20.0`
- Nuxt Version:     `^3.6.5`
- Nitro Version:    `-`
- Package Manager:  `pnpm@8.3.1`
- Builder:          `webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `example module`
------------------------------

### Reproduction

https://github.com/Eugene313/module-error

1.npx nuxi init -t module example
2.pnpm i --shamefully-hoist
3. pnpm i @vueuse/nuxt
4.Install module in module.ts await installModule('@vueuse/nuxt');
5.pnpm run dev:prepare
6.Create new nuxt app "pnpm dlx nuxi@latest init example-app"
7.pnpm i --shamefully-hoist
8.Add example module to example app nuxt.config modules: ['../example/src/module'],
9.pnpm run dev

### Describe the bug

Application cannot find module @vueuse/nuxt

### Logs

```shell-script
Error while requiring module @vueuse/nuxt: Error: Cannot find module 'C:/Users/Eugene/Desktop/module-error-example/example-app/@vueuse/nuxt'                                                                                                            11:30:53  
Require stack:
- C:\Users\Eugene\Desktop\module-error-example\example-app\index.js


 ERROR  Cannot find module 'C:/Users/Eugene/Desktop/module-error-example/example-app/@vueuse/nuxt'                                                                                                                                                              11:30:53  
Require stack:
- C:\Users\Eugene\Desktop\module-error-example\example-app\index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
  at Function.resolve (node:internal/modules/cjs/helpers:114:19)
  at Function._resolve [as resolve] (C:\Users\Eugene\Desktop\module-error-example\example\node_modules\.pnpm\jiti@1.19.1\node_modules\jiti\dist\jiti.js:1:250100)
  at resolveModule (C:/Users/Eugene/Desktop/module-error-example/example/node_modules/.pnpm/@nuxt+kit@3.6.5_rollup@3.28.0/node_modules/@nuxt/kit/dist/index.mjs:2230:41)
  at requireModule (C:/Users/Eugene/Desktop/module-error-example/example/node_modules/.pnpm/@nuxt+kit@3.6.5_rollup@3.28.0/node_modules/@nuxt/kit/dist/index.mjs:2240:24)
  at loadNuxtModuleInstance (C:/Users/Eugene/Desktop/module-error-example/example/node_modules/.pnpm/@nuxt+kit@3.6.5_rollup@3.28.0/node_modules/@nuxt/kit/dist/index.mjs:2435:92)
  at async installModule (C:/Users/Eugene/Desktop/module-error-example/example/node_modules/.pnpm/@nuxt+kit@3.6.5_rollup@3.28.0/node_modules/@nuxt/kit/dist/index.mjs:2408:47)
  at async setup (C:/Users/Eugene/Desktop/module-error-example/example/src/module.ts:18:5)
  at async normalizedModule (C:/Users/Eugene/Desktop/module-error-example/example/node_modules/.pnpm/@nuxt+kit@3.6.5_rollup@3.28.0/node_modules/@nuxt/kit/dist/index.mjs:2140:18)
  at async installModule (/C:/Users/Eugene/Desktop/module-error-example/example-app/node_modules/.pnpm/@nuxt+kit@3.6.5/node_modules/@nuxt/kit/dist/index.mjs:2409:95)
  at async initNuxt (/C:/Users/Eugene/Desktop/module-error-example/example-app/node_modules/.pnpm/nuxt@3.6.5_@types+node@18.17.3/node_modules/nuxt/dist/index.mjs:3238:7)
  at async loadNuxt (/C:/Users/Eugene/Desktop/module-error-example/example-app/node_modules/.pnpm/nuxt@3.6.5_@types+node@18.17.3/node_modules/nuxt/dist/index.mjs:3314:5)
  at async loadNuxt (/C:/Users/Eugene/Desktop/module-error-example/example-app/node_modules/.pnpm/@nuxt+kit@3.6.5/node_modules/@nuxt/kit/dist/index.mjs:2537:19)
  at async Object.invoke (/C:/Users/Eugene/Desktop/module-error-example/example-app/node_modules/.pnpm/nuxi@3.6.5/node_modules/nuxi/dist/chunks/prepare.mjs:31:18)
  at async _main (/C:/Users/Eugene/Desktop/module-error-example/example-app/node_modules/.pnpm/nuxi@3.6.5/node_modules/nuxi/dist/cli.mjs:49:20)


 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by KareemDa** [comment]
updating to `3.6.5` is breaking the whole project! 

structure: 
2 nuxt applications built with pnpm workspaces

folders:
- apps for projects
- package for shared packages

importing a module from a shared package is causing this error in `nuxt prepare`

>  ERROR  Error while requiring module [module name] : Error: Cannot find module [path to module]

**Comment by owl1n** [comment]
any solutions?
bsd/unix working, but on win systems crashings with same error (10/11 windows, yarn workspaces in usage)

**Comment by Eugene313** [comment]
@owl1n I fixed this error, install all package in dependency not in devDependency, its working form me

**Comment by KareemDa** [comment]
nuxt prepare is breaking in pnpm workspaces for nuxt `v3.5.1` and above 
It cannot figure out the local modules

Let's say I have this `package.json`

```
{
  "name": "@anyname",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "^3.7.1",
  },
  "dependencies": {
    "@localpackage": "workspace:^1.0.0",
  }
}
```

and the package `@localpackage` is located in `node_modules` after running `pnpm i`

then when it goes to `nuxt prepare`

It shows the error
>   ERROR  Cannot find module '{{rootDir}}/@localpackage'    

while it should be `'{{rootDir}}/node_modules/@localpackage'`

please, @danielroe "sorry for mentioning" but all of workspace users "pnpm - yarn" are unable to update to above 3.5.0

thank you in advance!

**Comment by danielroe** [comment]
@KareemDa Would you provide a reproduction? :pray:

**Comment by KareemDa** [comment]
sure @danielroe 
here you are: https://stackblitz.com/edit/github-rlzvg4-bemahd

you may ask why I added the module inside a folder called `nuxt` in the package
the answer is: because I'm exporting other things in the package more than the module itself
(pinia store, config, types, etc ...)

**Comment by danielroe** [comment]
@KareemDa In your example you have not provided a subpath export for your module. Add this and you should be good:

```json
  "exports": {
    "./nuxt": "./nuxt/index.ts"
  },
```

**Comment by KareemDa** [comment]
@danielroe 
Wow, this is magic! 
thank you so much

**Comment by danielroe** [comment]
Looking at the original example, if you are not using a monorepo, you need to allow your package manager the info it needs so it can install dependencies. So rather than just passing a path to another unrelated folder, do this:

```diff
  {
    // ...
    "devDependencies": {
      "nuxt": "^3.6.5",
+     "example": "file:../example"
    }
  }
```

Then update your nuxt config:

```ts
  export default defineNuxtConfig({
-   modules: ['../example'],
+   modules: ['example'],
  })
```
