### ISSUE TITLE
Unable to deploy project with nuxt layers on vercel, works locally.

### ISSUE THREAD

**Issue by amandesai01** [nuxt/nuxt#22646]
### Cloud Env: - Doesn't work here
Vercel [Everything default]

### Local Env: - Works Properly Here
- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Create a minimal nuxt application with nuxt config:

Entire repo can be found here:
https://github.com/amandesai01/techlaundry

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  extends: [
    'github:unproducts/magzyne/packages/web-layer'
  ],
})

```

### Describe the bug

I am creating a project where a Nuxt Layer is provided in parent repo (here REPO1: https://github.com/unproducts/magzyne/tree/main/packages/web-layer) and users are supposed to use it in their repo (here REPO2: https://github.com/amandesai01/techlaundry).
It works completely fine on local machine, but doesn't work when REPO2 is deployed on vercel. see attached logs.)

### Additional context

Entire vercel config is default and I havent changed anything. Just connected the repo and clicked on build. That's it.

### Logs

```shell-script
[00:09:13.062] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[00:09:13.113] Cloning github.com/amandesai01/techlaundry (Branch: main, Commit: 32d2486)
[00:09:13.477] Cloning completed: 363.885ms
[00:09:13.508] Previous build cache not available
[00:09:13.819] Running "vercel build"
[00:09:14.357] Vercel CLI 31.3.1
[00:09:14.937] Installing dependencies...
[00:09:15.380] yarn install v1.22.17
[00:09:15.452] [1/4] Resolving packages...
[00:09:15.743] [2/4] Fetching packages...
[00:09:15.762] warning Pattern ["wrap-ansi@^7.0.0"] is trying to unpack in the same destination "/vercel/.cache/yarn/v6/npm-wrap-ansi-cjs-7.0.0-67e145cff510a6a6984bdf1152911d69d2eb9e43-integrity/node_modules/wrap-ansi-cjs" as pattern ["wrap-ansi-cjs@npm:wrap-ansi@^7.0.0"]. This could result in non-deterministic behavior, skipping.
[00:09:27.892] warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
[00:09:27.898] [3/4] Linking dependencies...
[00:09:27.900] warning " > @nuxt/devtools@0.7.6" has unmet peer dependency "vite@*".
[00:09:27.900] warning "@nuxt/devtools > @nuxt/devtools-kit@0.7.6" has unmet peer dependency "vite@*".
[00:09:27.900] warning "@nuxt/devtools > vite-plugin-inspect@0.7.35" has unmet peer dependency "vite@^3.1.0 || ^4.0.0".
[00:09:27.900] warning "@nuxt/devtools > vite-plugin-vue-inspector@3.6.0" has unmet peer dependency "vite@^3.0.0-0 || ^4.0.0-0".
[00:09:27.902] warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > css-loader@5.2.7" has unmet peer dependency "webpack@^4.27.0 || ^5.0.0".
[00:09:27.902] warning "@nuxtjs/tailwindcss > @nuxt/postcss8 > postcss-loader@4.3.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[00:09:31.582] [4/4] Building fresh packages...
[00:09:32.450] $ nuxt prepare
[00:09:32.899] [log] Nuxi 3.6.5
[00:09:36.984] [success] Types generated in .nuxt
[00:09:36.994] Done in 21.62s.
[00:09:37.022] Running "yarn run build"
[00:09:37.212] yarn run v1.22.17
[00:09:37.232] $ nuxt build
[00:09:37.310] [log] Nuxi 3.6.5
[00:09:37.329] [log] Nuxt 3.6.5 with Nitro 2.5.2
[00:09:39.407] [info] Building client...
[00:09:39.416] [info] [36mvite v4.3.9 [32mbuilding for production...[36m[39m
[00:09:39.452] [info] transforming...
[00:09:40.979] [info] [32m✓[39m 105 modules transformed.
[00:09:41.049] [info] rendering chunks...
[00:09:41.106] [info] computing gzip size...
[00:09:41.139] [info] [2m.nuxt/dist/client/[22m[32mmanifest.json                                [39m[1m[2m  1.60 kB[22m[1m[22m[2m │ gzip:  0.33 kB[22m
[00:09:41.140] [info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[35merror-500.c5df6088.css                 [39m[1m[2m  1.95 kB[22m[1m[22m[2m │ gzip:  0.74 kB[22m
[00:09:41.140] [info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[35merror-404.7fc72018.css                 [39m[1m[2m  3.63 kB[22m[1m[22m[2m │ gzip:  1.12 kB[22m
[00:09:41.140] [info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36m_plugin-vue_export-helper.c27b6911.js  [39m[1m[2m  0.09 kB[22m[1m[22m[2m │ gzip:  0.10 kB[22m
[00:09:41.140] [info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36merror-500.975dc4cf.js                  [39m[1m[2m  1.93 kB[22m[1m[22m[2m │ gzip:  1.02 kB[22m
[00:09:41.140] [info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36merror-404.55507f64.js                  [39m[1m[2m  6.58 kB[22m[1m[22m[2m │ gzip:  2.94 kB[22m
[00:09:41.141] [info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36mentry.63350352.js                      [39m[1m[2m117.22 kB[22m[1m[22m[2m │ gzip: 44.31 kB[22m
[00:09:41.141] [info] [32m✓ built in 1.72s[39m
[00:09:41.141] [success] Client built in 1734ms
[00:09:41.144] [info] Building server...
[00:09:41.146] [info] [36mvite v4.3.9 [32mbuilding SSR bundle for production...[36m[39m
[00:09:41.158] [info] transforming...
[00:09:41.409] [info] [32m✓[39m 30 modules transformed.
[00:09:41.410] [info] [32m✓ built in 262ms[39m
[00:09:41.410] [error] [31m[vite]: Rollup failed to resolve import "vue" from "/vercel/.cache/c12/github_unproducts_magzyne/app.vue".
[00:09:41.410] This is most likely unintended because it can break your application at runtime.
[00:09:41.411] If you do want to externalize this module explicitly add it to
[00:09:41.411] `build.rollupOptions.external`[39m
[00:09:41.417] [error] [vite]: Rollup failed to resolve import "vue" from "/vercel/.cache/c12/github_unproducts_magzyne/app.vue".
[00:09:41.417] This is most likely unintended because it can break your application at runtime.
[00:09:41.417] If you do want to externalize this module explicitly add it to
[00:09:41.417] `build.rollupOptions.external`
[00:09:41.417]   This is most likely unintended because it can break your application at runtime.
[00:09:41.418]   If you do want to externalize this module explicitly add it to
[00:09:41.418]   `build.rollupOptions.external`
[00:09:41.418]   at viteWarn (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46597:23)
[00:09:41.418]   at onwarn (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.9774705b.mjs:724:11)
[00:09:41.418]   at onRollupWarning (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46618:9)
[00:09:41.418]   at onwarn (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46368:13)
[00:09:41.418]   at node_modules/rollup/dist/es/shared/node-entry.js:24152:13
[00:09:41.418]   at Object.logger [as onLog] (node_modules/rollup/dist/es/shared/node-entry.js:25825:9)
[00:09:41.418]   at ModuleLoader.handleInvalidResolvedId (node_modules/rollup/dist/es/shared/node-entry.js:24738:26)
[00:09:41.418]   at node_modules/rollup/dist/es/shared/node-entry.js:24698:26
[00:09:41.418]   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[00:09:41.445] error Command failed with exit code 1.
[00:09:41.445] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[00:09:41.469] Error: Command "yarn run build" exited with 1
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/22234.
