### ISSUE TITLE
[request error] [unhandled] [500] fetch failed

### ISSUE THREAD

**Issue by ahoiroman** [nuxt/nuxt#22645]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.5.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `npm@9.8.0`
- Builder:          `vite`
- User Config:      `devtools`, `modules`, `routeRules`, `colorMode`, `runtimeConfig`, `app`, `imports`, `i18n`, `content`, `image`, `veeValidate`, `ui`, `googleFonts`
- Runtime Modules:  `@nuxt/content@2.7.2`, `@nuxtjs/i18n@8.0.0-beta.13`, `@nuxthq/ui@2.7.0`, `@nuxt/image@1.0.0-rc.1`, `@vee-validate/nuxt@4.11.1`, `@nuxtjs/google-fonts@3.0.2`
- Build Modules:    `-`

### Reproduction

Create a routeRule like this:

```
export default defineNuxtConfig({
    routeRules: {
        '/api/v1/**': {
            proxy: `${process.env.NUXT_PUBLIC_BACKEND_URL}/api/${process.env.NUXT_PUBLIC_API_VERSION}/**`,
        },
        '/web/**': {
            proxy: `${process.env.NUXT_PUBLIC_BACKEND_URL}/**`,
        },
        '/csrf': {
            proxy: `${process.env.NUXT_PUBLIC_BACKEND_URL}/sanctum/csrf-cookie`,
        },
    },
```

Now create a POST request against any of those routes

```
curl 'http://web.app.test/web/auth/login' \
-X 'POST' \
-H 'Content-Type: application/json' \
-H 'Accept: application/json' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Accept-Language: de-DE,de;q=0.9' \
-H 'Host: web.app.test' \
-H 'Origin: http://web.app.test' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15' \
-H 'Connection: keep-alive' \
-H 'Referer: http://web.app.test/auth/signin' \
-H 'Content-Length: 48' \
-H 'Cookie: XSRF-TOKEN=...%3D; laravel_session=...%3D; i18n_redirected=en-US' \
-H 'x-xsrf-token: ...=' \
--data-binary '{"email":"test@example.org","password":"secret"}'
```

### Describe the bug

The following error appears:

```
[6:33:00 PM] [nuxt] [request error] [unhandled] [500] fetch failed (http://api.app.test/auth/login)
  at async sendProxy (./node_modules/h3/dist/index.mjs:1017:20)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1683:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1893:7)
[6:34:23 PM] [nuxt] [request error] [unhandled] [500] fetch failed (http://api.app.test/auth/login)
  at async sendProxy (./node_modules/h3/dist/index.mjs:1017:20)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1683:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1893:7)
[6:34:33 PM] [nuxt] [request error] [unhandled] [500] fetch failed (http://api.app.test/auth/login)
  at async sendProxy (./node_modules/h3/dist/index.mjs:1017:20)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1683:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1893:7)
[6:40:43 PM] [nuxt] [request error] [unhandled] [500] fetch failed (http://api.app.test/auth/login)
  at async sendProxy (./node_modules/h3/dist/index.mjs:1017:20)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1683:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1893:7)

```

The curl post request is NOT being handled by the API endpoint. It does not "arrive" there at all.

**Comment by ahoiroman** [comment]
Maybe related to https://github.com/unjs/h3/issues/376 ?

**Comment by ahoiroman** [comment]
I am trying to, but here I get "Socket hang up": https://stackblitz.com/edit/github-a4z167

**Comment by danielroe** [comment]
I think the issue is that you're trying to connect to the wrong URL on stackblitz. You might need to try creating this locally and push to a git repo.

**Comment by ahoiroman** [comment]
What do you mean with "wrong URL"? I added an exposed URL to a laravel app running on a dev machine. Maybe it would be a good idea to use some kind of open API for test purposes?

**Comment by danielroe** [comment]
By wrong URL, I mean you are using the URL to the stackblitz UI, not to your running Nuxt app.

**Comment by ahoiroman** [comment]
Hm alright. I will give it a try.

I also mentioned that this fails only on POST-calls, not on GET-calls.

**Comment by ahoiroman** [comment]
In my local environment, I am getting a bit closer to the issue:

The issue happens always when I am submitting a body to my request. If it's null, the request passes the proxy and is being handled by my backend (which returns 422 of course, because it expects data)

**Comment by ahoiroman** [comment]
Problem is solved when I pin h3 to version 1.7.1. Using 1.8 leads to the error.

**Comment by ahoiroman** [comment]
I am going to close this, as it's not a Nuxt issue, but an h3-problem.

**Comment by bangrobe** [comment]
Sorry for digging up this problem. I updated nuxt to latest version (3.8.0), running on docker with node version 20.8. My installed packages are: 
"devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtseo/module": "2.0.0-beta.15",
    "@vueuse/core": "^10.5.0",
    "@vueuse/nuxt": "^10.5.0",
    "nuxt-simple-sitemap": "^3.4.0"
  },
  "dependencies": {
    "@nuxt/image": "^1.0.0",
    "@nuxt/ui": "^2.9.0",
    "@pinia/nuxt": "^0.5.1",
    "jsdom": "^22.1.0",
    "nuxt": "^3.8.0",
    "pinia": "^2.1.7",
    "vue3-carousel-nuxt": "^1.1.0"
  }
After running few days, the problem appeared (again). Error detail is:
```
[nuxt] [request error] [unhandled] [500] fetch failed
  at Object.fetch (node:internal/deps/undici/undici:11372:11)  
  at async sendProxy (./.output/server/chunks/nitro/node-server.mjs:1850:20)  
  at async Object.handler (./.output/server/chunks/nitro/node-server.mjs:2206:19)  
  at async toNodeHandle (./.output/server/chunks/nitro/node-server.mjs:2395:7)  
  at async ufetch (./.output/server/chunks/nitro/node-server.mjs:2761:17)  
  at async $fetchRaw2 (./.output/server/chunks/nitro/node-server.mjs:2633:26)  
  at async $fetch2 (./.output/server/chunks/nitro/node-server.mjs:2675:15)  
  at async setup (./.output/server/chunks/app/server.mjs:4347:126)  
  at async Object.callAsync (./.output/server/chunks/app/server.mjs:87:16)  
```
My routes settings in nuxt.config.ts is:
```
 routeRules: {
    '/proxy/**': {
      proxy: `${process.env.API_URL}/**`
    }
  },
```
I had changed from Node version 18.x before. The error is always appeared after running for few hours. 
So I'm looking forward to a solution for this.

**Comment by ahoiroman** [comment]
Unfortunately I need to reopen this. I'm not getting this error with POST requests any longer, but DELETE requests are not working.


```
[nuxt] [request error] [unhandled] [500] fetch failed
  at Object.fetch (node:internal/deps/undici/undici:11600:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async sendProxy (./node_modules/h3/dist/index.mjs:1034:20)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)
[nuxt] [request error] [unhandled] [500] fetch failed
  at Object.fetch (node:internal/deps/undici/undici:11600:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async sendProxy (./node_modules/h3/dist/index.mjs:1034:20)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)
```

**Comment by eiriksgata** [comment]
> Unfortunately I need to reopen this. I'm not getting this error with POST requests any longer, but DELETE requests are not working.
> 
> ```
> [nuxt] [request error] [unhandled] [500] fetch failed
>   at Object.fetch (node:internal/deps/undici/undici:11600:11)  
>   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
>   at async sendProxy (./node_modules/h3/dist/index.mjs:1034:20)  
>   at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)  
>   at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)
> [nuxt] [request error] [unhandled] [500] fetch failed
>   at Object.fetch (node:internal/deps/undici/undici:11600:11)  
>   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
>   at async sendProxy (./node_modules/h3/dist/index.mjs:1034:20)  
>   at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)  
>   at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)
> ```

Me too

**Comment by jessielaf** [comment]
I have the same issue on a fresh nuxt 3 install.

**Comment by afrijaldz** [comment]
It's h3 bug for method delete, to handle this problem I use @radyakaze 's temporary way. 

```
  // temporary fix delete method
  if (event.method === 'DELETE') {
    try {
      return $fetch(url, {
        headers: {
          authorization: `Bearer ${token}`,
        },
        method: 'DELETE',
      })
    }
    catch (e) {
      const error = e as FetchError

      setResponseStatus(event, error.statusCode || 500)
      return error.data
    }
  }

```

In server middleware, if the request method is delete I use manual fetch to handle it

**Comment by xupapa** [comment]
Me too

**Comment by danielroe** [comment]
Closing as there is no reproduction and this seems like an upstream issue.
