### ISSUE TITLE
Nuxt 3.7 not working with vue-wrap-balancer

### ISSUE THREAD

**Issue by andrewspy** [nuxt/nuxt#22843]
### Environment

stackblitz nuxt 3.7 starter

### Reproduction

https://stackblitz.com/edit/nuxt-3-7-vue-wrap-balancer-issue?file=app.vue

### Describe the bug

Error as follows:-

require() of ES Module /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/nanoid/index.js from /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/vue-wrap-balancer/dist/index.js not supported. Instead change the require of /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/nanoid/index.js in /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/vue-wrap-balancer/dist/index.js to a dynamic import() which is available in all CommonJS modules.

### Additional context

Used to work in Nuxt 3.6

### Logs

```shell-script
ℹ [nuxt] compiled plugins/server.mjs in 991.82ms                                                               1:54:25 AM
ℹ [nuxt] compiled plugins/client.mjs in 1077.12ms                                                              1:54:25 AM
ℹ Vite client warmed up in 1892ms                                                                              1:54:29 AM
✔ Nitro built in 1343 ms                                                                                 nitro 1:54:30 AM
[nuxt] [request error] [unhandled] [500] require() of ES Module /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/nanoid/index.js from /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/vue-wrap-balancer/dist/index.js not supported.
Instead change the require of /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/nanoid/index.js in /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/vue-wrap-balancer/dist/index.js to a dynamic import() which is available in all CommonJS modules.
  at InternalError.get (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:67:7048)  
  at Module._extensions..js (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14828)  
  at Module.load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13005)  
  at Module._load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:9949)  
  at Module.require (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13323)  
  at i (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:91:2084)  
  at _0x243ee4 (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:154785)  
  at Object.eval (./node_modules/vue-wrap-balancer/dist/index.js:1:597)  
  at Object.function (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:155609)  
  at Module._compile (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14310)  
  at Module._extensions..js (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14989)  
  at Module.load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13005)  
  at Module._load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:9949)  
  at _0x3a95cf.executionFunctionOrLineOffset (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:164:2458)  
  at _0x3a95cf._evaluate (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:318384)  
  at _0x3a95cf.evaluate (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:317451)  
  at ModuleJob.run (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:149:2348)  
  at async ESMLoader.import (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:213:4862)  
  at async ViteNodeRunner.interopedImport (./node_modules/vite-node/dist/client.mjs:377:28)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:268:24)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./app.vue:2:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/app/components/nuxt-root.vue:6:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/app/entry.js:7:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.executeFile (./node_modules/vite-node/dist/client.mjs:186:12)  
  at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:41:89)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:199:19)  
  at async eval (./.nuxt/dev/index.mjs:989:21)  
  at async eval (./.nuxt/dev/index.mjs:549:22)  
  at async Object.eval (./node_modules/h3/dist/index.mjs:1802:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2012:7)
[nuxt] [request error] [unhandled] [500] require() of ES Module /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/nanoid/index.js from /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/vue-wrap-balancer/dist/index.js not supported.
Instead change the require of /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/nanoid/index.js in /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/vue-wrap-balancer/dist/index.js to a dynamic import() which is available in all CommonJS modules.
  at InternalError.get (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:67:7048)  
  at Module._extensions..js (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14828)  
  at Module.load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13005)  
  at Module._load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:9949)  
  at Module.require (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13323)  
  at i (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:91:2084)  
  at _0x243ee4 (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:154785)  
  at Object.eval (./node_modules/vue-wrap-balancer/dist/index.js:1:597)  
  at Object.function (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:155609)  
  at Module._compile (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14310)  
  at Module._extensions..js (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14989)  
  at Module.load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13005)  
  at Module._load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:9949)  
  at _0x3a95cf.executionFunctionOrLineOffset (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:164:2458)  
  at _0x3a95cf._evaluate (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:318384)  
  at _0x3a95cf.evaluate (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:317451)  
  at ModuleJob.run (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:149:2348)  
  at async ESMLoader.import (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:213:4862)  
  at async ViteNodeRunner.interopedImport (./node_modules/vite-node/dist/client.mjs:377:28)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:268:24)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./app.vue:2:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/app/components/nuxt-root.vue:6:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/app/entry.js:7:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.executeFile (./node_modules/vite-node/dist/client.mjs:186:12)  
  at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:41:89)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:199:19)  
  at async eval (./.nuxt/dev/index.mjs:989:21)  
  at async eval (./.nuxt/dev/index.mjs:549:22)  
  at async Object.eval (./node_modules/h3/dist/index.mjs:1802:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2012:7)
[nuxt] [request error] [unhandled] [500] require() of ES Module /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/nanoid/index.js from /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/vue-wrap-balancer/dist/index.js not supported.
Instead change the require of /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/nanoid/index.js in /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/vue-wrap-balancer/dist/index.js to a dynamic import() which is available in all CommonJS modules.
  at InternalError.get (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:67:7048)  
  at Module._extensions..js (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14828)  
  at Module.load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13005)  
  at Module._load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:9949)  
  at Module.require (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13323)  
  at i (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:91:2084)  
  at _0x243ee4 (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:154785)  
  at Object.eval (./node_modules/vue-wrap-balancer/dist/index.js:1:597)  
  at Object.function (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:155609)  
  at Module._compile (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14310)  
  at Module._extensions..js (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14989)  
  at Module.load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13005)  
  at Module._load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:9949)  
  at _0x3a95cf.executionFunctionOrLineOffset (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:164:2458)  
  at _0x3a95cf._evaluate (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:318384)  
  at _0x3a95cf.evaluate (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:317451)  
  at ModuleJob.run (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:149:2348)  
  at async ESMLoader.import (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:213:4862)  
  at async ViteNodeRunner.interopedImport (./node_modules/vite-node/dist/client.mjs:377:28)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:268:24)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./app.vue:2:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/app/components/nuxt-root.vue:6:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/app/entry.js:7:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.executeFile (./node_modules/vite-node/dist/client.mjs:186:12)  
  at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:41:89)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:199:19)  
  at async eval (./.nuxt/dev/index.mjs:989:21)  
  at async eval (./.nuxt/dev/index.mjs:549:22)  
  at async Object.eval (./node_modules/h3/dist/index.mjs:1802:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2012:7)
[nuxt] [request error] [unhandled] [500] require() of ES Module /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/nanoid/index.js from /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/vue-wrap-balancer/dist/index.js not supported.
Instead change the require of /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/nanoid/index.js in /home/projects/nuxt-3-7-vue-wrap-balancer-issue/node_modules/vue-wrap-balancer/dist/index.js to a dynamic import() which is available in all CommonJS modules.
  at InternalError.get (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:67:7048)  
  at Module._extensions..js (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14828)  
  at Module.load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13005)  
  at Module._load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:9949)  
  at Module.require (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13323)  
  at i (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:91:2084)  
  at _0x243ee4 (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:154785)  
  at Object.eval (./node_modules/vue-wrap-balancer/dist/index.js:1:597)  
  at Object.function (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:155609)  
  at Module._compile (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14310)  
  at Module._extensions..js (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:14989)  
  at Module.load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:13005)  
  at Module._load (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:56:9949)  
  at _0x3a95cf.executionFunctionOrLineOffset (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:164:2458)  
  at _0x3a95cf._evaluate (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:318384)  
  at _0x3a95cf.evaluate (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:334:317451)  
  at ModuleJob.run (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:149:2348)  
  at async ESMLoader.import (https://nuxt37vuewrapbalancerissue-uurl.w-credentialless.staticblitz.com/blitz.33975f1d.js:213:4862)  
  at async ViteNodeRunner.interopedImport (./node_modules/vite-node/dist/client.mjs:377:28)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:268:24)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./app.vue:2:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/app/components/nuxt-root.vue:6:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:248:12)  
  at async eval (./node_modules/nuxt/dist/app/entry.js:7:31)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:358:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:214:14)  
  at async ViteNodeRunner.executeFile (./node_modules/vite-node/dist/client.mjs:186:12)  
  at async 𝐝𝐞𝐟𝐚𝐮𝐥𝐭 (./node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:41:89)  
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:199:19)  
  at async eval (./.nuxt/dev/index.mjs:989:21)  
  at async eval (./.nuxt/dev/index.mjs:549:22)  
  at async Object.eval (./node_modules/h3/dist/index.mjs:1802:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2012:7)
```

**Comment by wobsoriano** [comment]
This is fixed in latest vue-wrap-balancer version.

**Comment by manniL** [comment]
Thanks for the info @wobsoriano
