### ISSUE TITLE
vercel_edge preset build fails on new empty projects

### ISSUE THREAD

**Issue by leo91000** [nuxt/nuxt#22875]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.17.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  pnpm@8.6.11
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

You simply have to create an empty project (`npx nuxi init test-edge`) and run `NITRO_PRESET=vercel_edge pnpm run build`.

But in case you prefer a simple git clone, I made the repro available here : https://github.com/leo91000/repro-vercel-edge-bug

### Describe the bug

When running the command `NITRO_PRESET=vercel_edge nuxt build`, the command crash with errors.

### Logs

```shell-script
> nuxt-app@ build C:\Users\maill\Projects\tmp\test-edge
> cross-env NITRO_PRESET=vercel_edge nuxt build

Nuxt 3.7.0 with Nitro 2.6.2                                                                                   23:56:45
ℹ Building client...                                                                                         23:56:48
ℹ vite v4.4.9 building for production...                                                                     23:56:48
ℹ ✓ 97 modules transformed.                                                                                  23:56:49
ℹ .nuxt/dist/client/manifest.json                   2.21 kB │ gzip:  0.34 kB                                 23:56:49
ℹ .nuxt/dist/client/_nuxt/error-500.cbe832a1.css    1.95 kB │ gzip:  0.74 kB                                 23:56:49
ℹ .nuxt/dist/client/_nuxt/error-404.7b8544b4.css    3.63 kB │ gzip:  1.12 kB                                 23:56:49
ℹ .nuxt/dist/client/_nuxt/entry.a08dbdb7.css       12.13 kB │ gzip:  2.49 kB                                 23:56:49
ℹ .nuxt/dist/client/_nuxt/error-500.e0af2f97.js     1.88 kB │ gzip:  0.99 kB                                 23:56:49
ℹ .nuxt/dist/client/_nuxt/error-404.76d61407.js     6.53 kB │ gzip:  2.90 kB                                 23:56:49
ℹ .nuxt/dist/client/_nuxt/entry.07030bdd.js       197.72 kB │ gzip: 55.63 kB                                 23:56:49
ℹ ✓ built in 1.51s                                                                                           23:56:49
✔ Client built in 1519ms                                                                                     23:56:49
ℹ Building server...                                                                                         23:56:49
ℹ vite v4.4.9 building SSR bundle for production...                                                          23:56:49
ℹ ✓ 46 modules transformed.                                                                                  23:56:50
ℹ .nuxt/dist/server/_nuxt/entry-styles.26cb16dd.mjs             0.08 kB                                      23:56:50
ℹ .nuxt/dist/server/_nuxt/error-404-styles.d352c5f6.mjs         0.15 kB                                      23:56:50
ℹ .nuxt/dist/server/_nuxt/error-500-styles.a47c06d2.mjs         0.15 kB                                      23:56:50
ℹ .nuxt/dist/server/styles.mjs                                  0.58 kB                                      23:56:50
ℹ .nuxt/dist/server/_nuxt/island-renderer-9ab8e6f6.js           1.02 kB │ map:   1.43 kB                     23:56:50
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-ad5bc82f.js    2.17 kB │ map:   0.12 kB                     23:56:50
ℹ .nuxt/dist/server/_nuxt/error-500-d8ea4716.js                 3.04 kB │ map:   3.81 kB                     23:56:50
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-712507d9.js    3.86 kB │ map:   0.12 kB                     23:56:50
ℹ .nuxt/dist/server/_nuxt/error-404-8a81d85c.js                 9.72 kB │ map:  19.04 kB                     23:56:50
ℹ .nuxt/dist/server/_nuxt/entry-styles-1.mjs-3e6f63b7.js       12.38 kB │ map:   0.11 kB                     23:56:50
ℹ .nuxt/dist/server/server.mjs                                120.91 kB │ map: 164.51 kB                     23:56:50
ℹ ✓ built in 753ms                                                                                           23:56:50
✔ Server built in 761ms                                                                                      23:56:50
✔ Generated public .vercel/output/static                                                               nitro 23:56:50

 ERROR  Cannot read properties of undefined (reading 'split')                                                 23:56:50

  at /C:/Users/maill/Projects/tmp/test-edge/node_modules/.pnpm/@rollup+plugin-inject@5.0.3_rollup@3.28.1/node_modules/@rollup/plugin-inject/dist/es/index.js:74:74
  at Map.forEach (<anonymous>)
  at inject (/C:/Users/maill/Projects/tmp/test-edge/node_modules/.pnpm/@rollup+plugin-inject@5.0.3_rollup@3.28.1/node_modules/@rollup/plugin-inject/dist/es/index.js:71:16)
  at getRollupConfig (/C:/Users/maill/Projects/tmp/test-edge/node_modules/.pnpm/nitropack@2.6.2/node_modules/nitropack/dist/shared/nitro.daa58dae.mjs:1942:29)
  at build (/C:/Users/maill/Projects/tmp/test-edge/node_modules/.pnpm/nitropack@2.6.2/node_modules/nitropack/dist/shared/nitro.daa58dae.mjs:2230:24)
  at /C:/Users/maill/Projects/tmp/test-edge/node_modules/.pnpm/nuxt@3.7.0/node_modules/nuxt/dist/index.mjs:2854:13
  at async build (/C:/Users/maill/Projects/tmp/test-edge/node_modules/.pnpm/nuxt@3.7.0/node_modules/nuxt/dist/index.mjs:4170:5)
  at async Object.run (/C:/Users/maill/Projects/tmp/test-edge/node_modules/.pnpm/nuxi@3.7.2/node_modules/nuxi/dist/chunks/build.mjs:99:5)
  at async runCommand$1 (/C:/Users/maill/Projects/tmp/test-edge/node_modules/.pnpm/nuxi@3.7.2/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1644:5)
  at async runCommand$1 (/C:/Users/maill/Projects/tmp/test-edge/node_modules/.pnpm/nuxi@3.7.2/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1638:7)



 ERROR  Cannot read properties of undefined (reading 'split')                                                 23:56:50

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by manniL** [comment]
Can you try if it works with plain nitro? Suspecting this is an upstream bug 🤔

**Comment by pi0** [comment]
It is a known issue vercel_edge with tests. (i am not sure we could run edge-runtime on vercel on Windows even!)
