### ISSUE TITLE
Nuxt 3.7 Yarn failed to install

### ISSUE THREAD

**Issue by TheProfanedOne** [nuxt/nuxt#22897]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.17.1`
(I tried `v20.5.1` as well, to the same result)
- Nuxt Version:     `^3.7.0`
- CLI Version:      `3.7.2`
- Nitro Version:    `-`
- Package Manager:  `yarn@3.6.3`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. `yarn dlx nuxi@latest init my-nuxt-app` and select yarn as the package manager (with or without `--no-install`)
     a. if `--no-install` was used, cd into the project directory and `yarn install` (use `--inline-builds` for the same inline error messages)

### Describe the bug

```
❯ yarn install --inline-builds
➤ YN0000: ┌ Resolution step
➤ YN0032: │ fsevents@npm:2.3.3: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ @parcel/watcher@npm:2.3.0: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:7.0.0: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ nuxt-app@workspace:. doesn't provide vite (p278f2), requested by @nuxt/devtools
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 17s 76ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs-parser@npm:21.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.7.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yauzl@npm:2.10.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zhead@npm:2.0.10 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zip-stream@npm:4.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1s 79ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ fast-folder-size@npm:2.2.0 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.19.2 must be built because it never has been before or the last one failed
➤ YN0007: │ nuxt-app@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: │ nuxt-app@workspace:. STDERR 
➤ YN0000: │ nuxt-app@workspace:. STDERR  ERROR  Error: Cannot find module @nuxt/kit imported from file:///home/matthew/coding/web-projects/vue/my-nuxt-app, file:///home/matthew/coding/web-projects/vue/, file:///home/matthew/coding/web-projects/vue/my-nuxt-app/_index.js, file:///home/matthew/coding/web-projects/vue/node_modules
➤ YN0000: │ nuxt-app@workspace:. STDERR 
➤ YN0000: │ nuxt-app@workspace:. STDERR   at resolvePath (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.615ae2d1.mjs:7954:10)
➤ YN0000: │ nuxt-app@workspace:. STDERR   at importModule (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.31a0124f.mjs:11:30)
➤ YN0000: │ nuxt-app@workspace:. STDERR   at loadKit (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.f65c0f6b.mjs:7:18)
➤ YN0000: │ nuxt-app@workspace:. STDERR   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
➤ YN0000: │ nuxt-app@workspace:. STDERR   at async Object.run (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/chunks/prepare.mjs:60:9)
➤ YN0000: │ nuxt-app@workspace:. STDERR   at async runCommand$1 (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1644:5)
➤ YN0000: │ nuxt-app@workspace:. STDERR   at async runCommand$1 (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1638:7)
➤ YN0000: │ nuxt-app@workspace:. STDERR   at async runMain$1 (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1756:7) 
➤ YN0000: │ nuxt-app@workspace:. STDERR 
➤ YN0000: │ nuxt-app@workspace:. STDERR 
➤ YN0000: │ nuxt-app@workspace:. STDERR 
➤ YN0000: │ nuxt-app@workspace:. STDERR  ERROR  Error: Cannot find module @nuxt/kit imported from file:///home/matthew/coding/web-projects/vue/my-nuxt-app, file:///home/matthew/coding/web-projects/vue/, file:///home/matthew/coding/web-projects/vue/my-nuxt-app/_index.js, file:///home/matthew/coding/web-projects/vue/node_modules
➤ YN0000: │ nuxt-app@workspace:. STDERR 
➤ YN0009: │ nuxt-app@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-68480de8/build.log)
➤ YN0000: └ Completed in 1s 399ms
➤ YN0000: Failed with errors in 19s 674ms
```

### Additional context

For reference, the same install worked fine with npm, pnpm, and bun.

### Logs

```shell-script
// This is the logfile from the "Describe the bug" section earlier
// /tmp/xfs-68480de8/build.log

ERROR  Error: Cannot find module @nuxt/kit imported from file:///home/matthew/coding/web-projects/vue/my-nuxt-app, file:///home/matthew/coding/web-projects/vue/, file:///home/matthew/coding/web-projects/vue/my-nuxt-app/_index.js, file:///home/matthew/coding/web-projects/vue/node_modules

  at resolvePath (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.615ae2d1.mjs:7954:10)
  at importModule (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.31a0124f.mjs:11:30)
  at loadKit (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.f65c0f6b.mjs:7:18)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.run (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/chunks/prepare.mjs:60:9)
  at async runCommand$1 (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1644:5)
  at async runCommand$1 (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1638:7)
  at async runMain$1 (.yarn/cache/nuxi-npm-3.7.2-cca0739b6a-139bbbb6d4.zip/node_modules/nuxi/dist/shared/nuxi.c627b411.mjs:1756:7) 



 ERROR  Error: Cannot find module @nuxt/kit imported from file:///home/matthew/coding/web-projects/vue/my-nuxt-app, file:///home/matthew/coding/web-projects/vue/, file:///home/matthew/coding/web-projects/vue/my-nuxt-app/_index.js, file:///home/matthew/coding/web-projects/vue/node_modules
```

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/22861 (workaround provided)

**Comment by danielroe** [comment]
I think we could also look to create this file automatically with nuxi cli if yarn option is selected. (For now, anyway.)

cc: @pi0
