### ISSUE TITLE
3.7.0 – Fresh install: "[request error] [unhandled] [500] entry is not a function"

### ISSUE THREAD

**Issue by superstoffer** [nuxt/nuxt#22899]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.17.0`
- Nuxt Version:     `3.6.5`
- CLI Version:      `3.7.2`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@9.8.1`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

However, my package.json says Nuxt Version: `3.7.0`

### Reproduction

npx nuxi@latest init my-app
cd my-app
npm run dev

### Describe the bug

From a new install, Nuxt is unable to launch. 

The error screen shows:

500
entry is not a function

### Logs

```shell-script
at __vite_ssr_exports__.default (./node_modules/nuxt/dist/app/entry.js:76:41)
at default (/Users/christoffer/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:24)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
at  (./node_modules/nuxt/dist/core/runtime/nitro/renderer.js:171:21)
at  (./node_modules/nitropack/dist/runtime/renderer.mjs:20:22)
at async Object.handler (./node_modules/h3/dist/index.mjs:1630:19)
at async toNodeHandle (./node_modules/h3/dist/index.mjs:1840:7)
at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
at errorhandler (./node_modules/nuxt/dist/core/runtime/nitro/error.js:35:30)
```

**Comment by danielroe** [comment]
It looks like you might have a `node_modules` installation in `/Users/christoffer`, and it seems to have a version of Nuxt installed there. Would you try deleting it?

(The reproduction steps above do not cause an issue for me.)

**Comment by superstoffer** [comment]
That did solve it for me @danielroe .
Thank you very much. I was not aware that my system wide node_modules would affect a specific project.

**Comment by natemate90** [comment]
Is there a flag to make sure the local nuxt version takes precedence before the global one?

**Comment by henrikaskj** [comment]
I'm getting the same error after updating from nuxt 3.6.5 to nuxt 3.7.3 in a monorepo using turbo 1.8.3:
````
[nuxt] [request error] [unhandled] [500] entry is not a function
  at __vite_ssr_exports__.default (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nuxt\dist\app\entry.js:76:41)
  at default (/C:/Users/has022/repos/monorepo/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:24)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.renderToString (/C:/Users/has022/repos/monorepo/apps/nuxt-debug/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
  at <anonymous> (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nuxt\dist\core\runtime\nitro\renderer.js:171:21)
  at <anonymous> (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nitropack\dist\runtime\renderer.mjs:19:22)
  at async Object.handler (/C:/Users/has022/repos/monorepo/node_modules/h3/dist/index.mjs:1630:19)
  at async Server.toNodeHandle (/C:/Users/has022/repos/monorepo/node_modules/h3/dist/index.mjs:1840:7)
[nuxt] [request error] [unhandled] [500] entry is not a function
  at __vite_ssr_exports__.default (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nuxt\dist\app\entry.js:76:41)
  at default (/C:/Users/has022/repos/monorepo/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:24)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.renderToString (/C:/Users/has022/repos/monorepo/apps/nuxt-debug/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
  at <anonymous> (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nuxt\dist\core\runtime\nitro\renderer.js:171:21)
  at <anonymous> (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nitropack\dist\runtime\renderer.mjs:19:22)
  at async Object.handler (/C:/Users/has022/repos/monorepo/node_modules/h3/dist/index.mjs:1630:19)
  at async toNodeHandle (/C:/Users/has022/repos/monorepo/node_modules/h3/dist/index.mjs:1840:7)
  at async ufetch (/C:/Users/has022/repos/monorepo/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at errorhandler (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nuxt\dist\core\runtime\nitro\error.js:35:30)
[nuxt] [request error] [unhandled] [500] entry is not a function
  at __vite_ssr_exports__.default (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nuxt\dist\app\entry.js:76:41)
  at default (/C:/Users/has022/repos/monorepo/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:24)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.renderToString (/C:/Users/has022/repos/monorepo/apps/nuxt-debug/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
  at <anonymous> (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nuxt\dist\core\runtime\nitro\renderer.js:171:21)
  at <anonymous> (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nitropack\dist\runtime\renderer.mjs:19:22)
  at async Object.handler (/C:/Users/has022/repos/monorepo/node_modules/h3/dist/index.mjs:1630:19)
  at async Server.toNodeHandle (/C:/Users/has022/repos/monorepo/node_modules/h3/dist/index.mjs:1840:7)
[nuxt] [request error] [unhandled] [500] entry is not a function
  at __vite_ssr_exports__.default (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nuxt\dist\app\entry.js:76:41)
  at default (/C:/Users/has022/repos/monorepo/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:24)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.renderToString (/C:/Users/has022/repos/monorepo/apps/nuxt-debug/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
  at <anonymous> (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nuxt\dist\core\runtime\nitro\renderer.js:171:21)
  at <anonymous> (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nitropack\dist\runtime\renderer.mjs:19:22)
  at async Object.handler (/C:/Users/has022/repos/monorepo/node_modules/h3/dist/index.mjs:1630:19)
  at async toNodeHandle (/C:/Users/has022/repos/monorepo/node_modules/h3/dist/index.mjs:1840:7)
  at async ufetch (/C:/Users/has022/repos/monorepo/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at errorhandler (C:\Users\has022\repos\monorepo\apps\nuxt-debug\node_modules\nuxt\dist\core\runtime\nitro\error.js:35:30)
````

There is an app in the same repo with nuxt 3.5.1, but that did not interfere with nuxt 3.6:
````
+-- nuxt-debug@ -> .\apps\nuxt-debug
| +-- @nuxt/devtools@0.8.4
| | +-- @nuxt/devtools-kit@0.8.4
| | | `-- nuxt@3.7.3 deduped
| | `-- nuxt@3.7.3 deduped
| `-- nuxt@3.7.3
+-- sps-ordbokene-web@ -> .\apps\sps-ordbokene-web
| `-- nuxt@3.7.3
`-- sps-termportal-web@1.0.0 -> .\apps\sps-termportal-web
  +-- @vueuse/nuxt@9.13.0
  | `-- nuxt@3.2.3
  `-- nuxt@3.5.1
````

**Comment by axe-me** [comment]
I got same issue in a pnpm workspaces.

**Comment by JulianMar** [comment]
Same issue with a nx monorepo.

**Comment by pi0** [comment]
@JulianMar any chance you can make a minimal reproduction repo?

**Comment by JulianMar** [comment]
Okay it's quite hard to replicate it. I will keep on trying. What I can tell is that the `import.meta.server` and `import.meta.client` are both undefined.

They loose their value in the renderToString Method. Did you have something similar somewhere else?
https://github.com/nuxt/nuxt/blob/93ace5548199e4c3fcc4dc07c2e18df8330bb1d8/packages/nuxt/src/core/runtime/nitro/renderer.ts#L288

**Comment by JulianMar** [comment]
Repro: https://github.com/JulianMar/repro
```
pull it
npm ci
npx nx run repro-test:serve
```

**Comment by JulianMar** [comment]
It's not a nuxt issue. It was caused by the @storybook-vue/nuxt package. 
Thanks for your help anyway. I'm on to the next github repo.

**Comment by zinaidagutu** [comment]
> It looks like you might have a `node_modules` installation in `/Users/christoffer`, and it seems to have a version of Nuxt installed there. Would you try deleting it?
> 
> (The reproduction steps above do not cause an issue for me.)

**Comment by zinaidagutu** [comment]
That worked for me. Thanks

**Comment by rakesh-rajwar** [comment]
> It looks like you might have a `node_modules` installation in `/Users/christoffer`, and it seems to have a version of Nuxt installed there. Would you try deleting it?
> 
> (The reproduction steps above do not cause an issue for me.)

Works for me. Thanks
