### ISSUE TITLE
Nuxt Playground is not working in CodeSandbox

### ISSUE THREAD

**Issue by degletnour** [nuxt/nuxt#22934]
### Environment

CodeSandbox / Nuxt ^3.7.0

### Reproduction

You just need to click the "Play with CodeSandbox" button in Nuxt Installation page 

![image](https://github.com/nuxt/nuxt/assets/141123484/c4d944ce-08a7-4a71-8411-c5e06a16e83b)

### Describe the bug

Nuxt playground is not working in codesandbox. It gives the following Error : 

![image](https://github.com/nuxt/nuxt/assets/141123484/6b1b405b-f9c5-4ad8-9c45-806aa885247c)

### Logs

```shell-script
[CODESANDBOX] No container config detected
[CODESANDBOX] Running zsh
[CODESANDBOX] Running command: yarn build
yarn run v1.22.19
$ nuxt build
Nuxt 3.7.0 with Nitro 2.6.1                                         3:05:02 PM

[3:05:04 PM]  ERROR  The requested module '@nuxt/kit' does not provide an export named 'resolveIgnorePatterns'

  import { useNuxt, resolveFiles, defineNuxtModule, addTemplate, addPlugin, addComponent, updateTemplates, addVitePlugin, addWebpackPlugin, addBuildPlugin, findPath, addImportsSources, tryResolveModule, isIgnored, resolveAlias, addPluginTemplate, logger, normalizeModuleTranspilePath, resolveIgnorePatterns, createResolver, nuxtCtx, resolvePath as resolvePath$1, installModule, useNitro, loadNuxtConfig, normalizeTemplate, compileTemplate, normalizePlugin, templateUtils } from '@nuxt/kit';
  ^^^^^^^^^^^^^^^^^^^^^
  SyntaxError: The requested module '@nuxt/kit' does not provide an export named 'resolveIgnorePatterns'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2570:37)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:73:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.51fb54b9.mjs:1644:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.51fb54b9.mjs:1638:7)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.51fb54b9.mjs:1756:7) 



[3:05:04 PM]  ERROR  The requested module '@nuxt/kit' does not provide an export named 'resolveIgnorePatterns'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by manniL** [comment]
The issue mentioned here is resolved, but a new one arised. Tracking in https://github.com/nuxt/starter/issues/599
