### ISSUE TITLE
nuxt 3.7.0 - "getActivePinia()" was called but there was no active Pinia

### ISSUE THREAD

**Issue by CodeDredd** [nuxt/nuxt#22943]
### Environment

- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.0
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/nuxt-starter-h8hokc?file=app.vue

### Describe the bug

Hello,

since 3.7.0 it seems that the pinia instance is initilized in a different order. With nuxt 3.6.5 everything works fine.

### Additional context

There is also an issue on my repository for this topic https://github.com/CodeDredd/pinia-orm/issues/1585

### Logs

```shell-script
[🍍]: "getActivePinia()" was called but there was no active Pinia. Did you forget to install pinia? const pinia = createPinia() app.use(pinia) This will fail in production.

at Query.commit (./node_modules/pinia-orm/dist/index.js:630:91)
at Query.storeFind (./node_modules/pinia-orm/dist/index.js:833:23)
at Query.select (./node_modules/pinia-orm/dist/index.js:897:23)
at Query.internalGet (./node_modules/pinia-orm/dist/index.js:871:25)
at Query.get (./node_modules/pinia-orm/dist/index.js:850:19)
at Repository.all (./node_modules/pinia-orm/dist/index.js:1566:25)
at setup (./app.js:15:28)
at _sfc_main.setup (./app.js:30:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:156:18)
```

**Comment by danielroe** [comment]
Possibly related: https://github.com/nuxt/nuxt/issues/22918

**Comment by vinothkbest** [comment]
Yes. I think below works

```javascript
import { defineStore, createPinia, setActivePinia } from "pinia"
const pinia = createPinia()

export default { store: setActivePinia(pinia) }
export const useMainStore = defineStore("main", {
```

**Comment by CodeDredd** [comment]
> Yes. I think below works
> 
> ```js
> import { defineStore, createPinia, setActivePinia } from "pinia"
> const pinia = createPinia()
> 
> export default { store: setActivePinia(pinia) }
> export const useMainStore = defineStore("main", {
> ```

It's not about a general vue project there i need to create Pinia store by my own. Here `@pinia/nuxt` is used which already creates the pinia instance.
But somehow the pinia instance isn't created before setup is called which was different in nuxt 3.6.5.
The workarounds that work are already mentioned in this ticket: https://github.com/CodeDredd/pinia-orm/issues/1585

**Comment by vinothkbest** [comment]
Yes. Says in nuxt only. In store folder.

**Comment by MateuszStawski** [comment]
> > Yes. I think below works
> > ```js
> > import { defineStore, createPinia, setActivePinia } from "pinia"
> > const pinia = createPinia()
> > 
> > export default { store: setActivePinia(pinia) }
> > export const useMainStore = defineStore("main", {
> > ```
> 
> It's not about a general vue project there i need to create Pinia store by my own. Here `@pinia/nuxt` is used which already creates the pinia instance. But somehow the pinia instance isn't created before setup is called which was different in nuxt 3.6.5. The workarounds that work are already mentioned in this ticket: [CodeDredd/pinia-orm#1585](https://github.com/CodeDredd/pinia-orm/issues/1585)

nuxt 3.11.2, had to use the same workaround, it doesn't seem to be fixed with more current versions

**Comment by jsedanoj** [comment]
> 
> nuxt 3.11.2, had to use the same workaround, it doesn't seem to be fixed with more current versions

Same situation here. It works on 3.10.2 and fails on 3.10.3.

I have created a new bug report here: https://github.com/nuxt/nuxt/issues/27447

**Comment by Maakdev** [comment]
fail on 3.16.0

"getActivePinia()" was called but there was no active Pinia. Are you trying to use a store before calling "app.use(pinia)"?
See https://pinia.vuejs.org/core-concepts/outside-component-usage.html for help.
