### ISSUE TITLE
The Generator Function Cannot be Auto Imported

### ISSUE THREAD

**Issue by otomad** [nuxt/nuxt#22969]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v19.0.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.2
- Nitro Version:    2.6.2
- Package Manager:  npm@8.19.2
- Builder:          -
- User Config:      plugins, modules, alias, css, vite, nitro, vue, i18n, content, piniaPersistedstate, svgSprite, imports, postcss, components
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.3, @nuxt/content@2.7.2, @nuxtjs/svg-sprite@1.0.2, @vueuse/nuxt@9.13.0, nuxt-lodash@2.5.0, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.1, modules/theme/module.ts, modules/noscript/module.ts, modules/unsupported-browsers/module.ts, @nuxtjs/robots@3.0.0, nuxt-simple-sitemap@1.0.11
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-kgd2ro?file=composables%2Ffunctions.ts,app.vue

### Describe the bug

Create a js/ts file in `composables` / `utils` folder, then declare the (async) generator function (function*).

```ts
export function testFunction() { /* ... */ }

export async function testAsyncFunction() { /* ... */ }

export function* testGeneratorFunction() { /* ... */ }

export async function* testAsyncGeneratorFunction() { /* ... */ }
```

In other files, only `testFunction` and `testAsyncFunction` functions can be auto imported, `testGeneratorFunction` and `testAsyncGeneratorFunction` generator functions won't be auto imported unless you explicitly import.

### Logs

```shell-script
500
testGeneratorFunction is not defined

at _sfc_main.setup (./app.js:28:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:156:18)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7190:25)
at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7151:36)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:614:15)
at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:86:10)
at default (./node_modules/nuxt/dist/app/components/nuxt-root.js:79:37)
at Module.ssrRenderSuspense (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:461:5)
at _sfc_ssrRender (./node_modules/nuxt/dist/app/components/nuxt-root.js:70:25)
```

**Comment by danielroe** [comment]
cc: @antfu
