### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_2__.composableNames is not iterable

### ISSUE THREAD

**Issue by mklueh** [nuxt/nuxt#23026]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.3.1
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.5.2
- Package Manager:  yarn@3.6.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Not sure. I've just upgraded nuxt from 3.6.5 to 3.7.1

The @unhead version seems to be the latest 1.5.2

### Describe the bug

Site load produces error after upgrading Nuxt

### Logs

```shell-script
[nitro] ✔ Nitro built in 5506 ms
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_2__.composableNames is not iterable
  at /home/user/workspace/myproject/node_modules/@unhead/vue/dist/index.mjs:63:68
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.directRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:334:5)
  at async ViteNodeRunner.cachedRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:190:14)
  at async ViteNodeRunner.dependencyRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:224:12)
  at async /home/user/workspace/myproject/node_modules/nuxt/dist/app/composables/index.js:1:31
  at async ViteNodeRunner.directRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:334:5)
  at async ViteNodeRunner.cachedRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:190:14)
  at async ViteNodeRunner.dependencyRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:224:12)
  at async /home/user/workspace/myproject/node_modules/nuxt/dist/app/index.js:3:31
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_2__.composableNames is not iterable
  at /home/user/workspace/myproject/node_modules/@unhead/vue/dist/index.mjs:63:68
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ViteNodeRunner.directRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:334:5)
  at async ViteNodeRunner.cachedRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:190:14)
  at async ViteNodeRunner.dependencyRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:224:12)
  at async /home/user/workspace/myproject/node_modules/nuxt/dist/app/composables/index.js:1:31
  at async ViteNodeRunner.directRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:334:5)
  at async ViteNodeRunner.cachedRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:190:14)
  at async ViteNodeRunner.dependencyRequest (/home/user/workspace/myproject/node_modules/vite-node/dist/client.mjs:224:12)
  at async /home/user/workspace/myproject/node_modules/nuxt/dist/app/index.js:3:31
```
```

**Comment by danielroe** [comment]
Would you see if clearing your `.nuxt` and `node_modules/.cache` folder makes a difference here?

**Comment by mklueh** [comment]
@danielroe I've deleted node_modules and yarn.lock but also downgraded to 3.7.0. This works now.

However, going back up to 3.7.1 gives me now

```
[nitro] ✔ Nitro built in 12803 ms
 ERROR  [worker reload] [worker init] The requested module 'file:///home/user/workspace/myproject/node_modules/devalue/dist/devalue.umd.js' does not provide an export named 'stringify'
  import { stringify, uneval } from '/home/user/workspace/myproject/node_modules/devalue/dist/devalue.umd.js';
  ^^^^^^^^^
  SyntaxError: The requested module '/home/user/workspace/myproject/node_modules/devalue/dist/devalue.umd.js' does not provide an export named 'stringify'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)
  at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
  at async loadESM (node:internal/process/esm_loader:40:7)
  at async handleMainPromise (node:internal/modules/run_main:66:12)


```

**Comment by danielroe** [comment]
Can you check the output of `yarn why devalue`?

**Comment by mklueh** [comment]
@danielroe thanks

```
├─ @nuxtjs/i18n@npm:7.3.1
│  └─ devalue@npm:2.0.1 (via npm:^2.0.1)
│
├─ nuxt@npm:3.7.1
│  └─ devalue@npm:4.3.2 (via npm:^4.3.2)
│
├─ nuxt@npm:3.7.1 [41f23]
│  └─ devalue@npm:4.3.2 (via npm:^4.3.2)
│
└─ nuxt@npm:3.7.1 [da0cf]
   └─ devalue@npm:4.3.2 (via npm:^4.3.2)

```

I've removed the i18n package and now it works.

**Comment by danielroe** [comment]
@mklueh I believe the version of the i18n module that's compatible with Nuxt 3 is v8 (rc).

**Comment by eden** [comment]
We experienced this error as well. We have `@unhead/vue` in our dependencies (for other reasons). Installing `@unhead/shared` alongside it seemed to resolve our case. I can't reproduce this with a minimal project of nuxt, however.

**Comment by jordypereira** [comment]
> We experienced this error as well. We have `@unhead/vue` in our dependencies (for other reasons). Installing `@unhead/shared` alongside it seemed to resolve our case. I can't reproduce this with a minimal project of nuxt, however.

Installing `@unhead/shared` solved this issue for us as well. We do not have `@unhead/vue` explicitly in our dependencies, however we do have `@unhead/addons` in our devDependencies.
