### ISSUE TITLE
Builds fail on Netlify

### ISSUE THREAD

**Issue by ijkml** [nuxt/nuxt#23053]
### Environment

- Operating System: `Linux`
- Node Version:     `v20.5.0`
- Nuxt Version:     `3.6.5`
- Nitro Version:    `2.5.2`
- Package Manager:  `pnpm@8.7.1`
- Builder:          `vite`
- User Config:      `extends`, `app`, `alias`, `modules`, `experimental`, `routeRules`, `vite`, `css`, `colorMode`
- Runtime Modules:  `@vueuse/nuxt@9.13.0`, `@unocss/nuxt@0.49.8`, `nuxt-swiper@1.2.0`, `@nuxtjs/color-mode@3.2.0`, `@nuxtjs/critters@0.4.1`, `vite-plugin-vue-type-imports/nuxt`
- Build Modules:    `-`

### Reproduction

Repo: https://github.com/ijkml/PennyPay

### Describe the bug

First of all, I'm not sure if this a Nuxt issue or Netlify issue. All my recent builds are failing. Same projects deployed on Vercel build/deploy without issues. I thought it was a v3.7 issue, but the older versions fail as well. The last commit and deploy for the project (Aug 21) was successful but fails today. Logs :point_down: 

### Logs

```shell-script
11:58:15 PM: build-image version: 73f16e520fdddf409be6f578c8c2c8941bdf32d3 (focal)
11:58:15 PM: buildbot version: 73f16e520fdddf409be6f578c8c2c8941bdf32d3
11:58:15 PM: Fetching cached dependencies
11:58:15 PM: Starting to download cache of 162.4MB
11:58:18 PM: Finished downloading cache in 2.441s
11:58:18 PM: Starting to extract cache
11:58:19 PM: Finished extracting cache in 1.763s
11:58:19 PM: Finished fetching cache in 4.262s
11:58:19 PM: Starting to prepare the repo for build
11:58:20 PM: Preparing Git Reference refs/heads/main
11:58:21 PM: Starting to install dependencies
11:58:21 PM: Python version set to 3.8
11:58:21 PM: Attempting Ruby version 2.7.2, read from environment
11:58:22 PM: Using Ruby version 2.7.2
11:58:22 PM: Started restoring cached go cache
11:58:22 PM: Finished restoring cached go cache
11:58:22 PM: go version go1.19.12 linux/amd64
11:58:23 PM: Using PHP version 8.0
11:58:24 PM: Started restoring cached Node.js version
11:58:25 PM: Finished restoring cached Node.js version
11:58:25 PM: Downloading and installing node v20.6.0...
11:58:25 PM: Downloading https://nodejs.org/dist/v20.6.0/node-v20.6.0-linux-x64.tar.xz...
11:58:25 PM: Computing checksum with sha256sum
11:58:25 PM: Checksums matched!
11:58:28 PM: Now using node v20.6.0 (npm v9.8.1)
11:58:28 PM: Enabling Node.js Corepack
11:58:28 PM: Started restoring cached build plugins
11:58:28 PM: Finished restoring cached build plugins
11:58:28 PM: Started restoring cached corepack dependencies
11:58:28 PM: Finished restoring cached corepack dependencies
11:58:28 PM: No pnpm workspaces detected
11:58:28 PM: Started restoring cached node modules
11:58:28 PM: Finished restoring cached node modules
11:58:29 PM: Installing npm packages using pnpm version 8.6.11
11:58:29 PM: Lockfile is up to date, resolution step is skipped
11:58:29 PM: Already up to date
11:58:30 PM: > @ postinstall /opt/build/repo
11:58:30 PM: > nuxi prepare
11:58:30 PM: [log] Nuxi 3.6.5
11:58:31 PM: Failed during stage 'Install dependencies': dependency_installation script returned non-zero exit code: 1
11:58:31 PM: [error] Cannot redefine property: __internal__deprecationWarning
11:58:31 PM:   at Function.defineProperty (<anonymous>)
11:58:31 PM:   at Object.<anonymous> (node_modules/.pnpm/@babel+types@7.22.10/node_modules/@babel/types/lib/index.js:66:8)
11:58:31 PM:   at Module._compile (node:internal/modules/cjs/loader:1241:14)
11:58:31 PM:   at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
11:58:31 PM:   at Module.load (node:internal/modules/cjs/loader:1091:32)
11:58:31 PM:   at Module._load (node:internal/modules/cjs/loader:938:12)
11:58:31 PM:   at Module.require (node:internal/modules/cjs/loader:1115:19)
11:58:31 PM:   at require (node:internal/modules/helpers:130:18)
11:58:31 PM:   at Object.<anonymous> (node_modules/.pnpm/@babel+types@7.22.10/node_modules/@babel/types/lib/builders/validateNode.js:8:9)
11:58:31 PM:   at Module._compile (node:internal/modules/cjs/loader:1241:14)
11:58:31 PM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
11:58:31 PM: Error during pnpm install
11:58:31 PM: Build was terminated: dependency_installation script returned non-zero exit code: 1
11:58:31 PM: Failing build: Failed to install dependencies
```

**Comment by dargmuesli** [comment]
See https://github.com/nuxt/nuxt/issues/23020. Temporarily downgrade Node to `v20.5.1`.
