### ISSUE TITLE
 ERROR  Cannot start nuxt:  kit.writeTypes is not a function  

### ISSUE THREAD

**Issue by imcm7** [nuxt/nuxt#23079]
### Environment

Nuxt project info:                                                                                                                                        8:15:37 AM

------------------------------
- Operating System: Linux
- Node Version:     v20.5.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.0
- Nitro Version:    2.6.3-28235083.5639f5b
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      alias, app, colorMode, css, dayjs, devtools, experimental, i18n, image, modules, nitro, pwa, runtimeConfig, security, ssr, tailwindcss, viewport, vueEmail
- Runtime Modules:  @hebilicious/authjs-nuxt@0.2.0-beta.8, @nuxt/image@1.0.0-rc.1, @nuxtjs/color-mode@3.3.0, @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @vee-validate/nuxt@4.11.3, @vueuse/nuxt@10.4.1, dayjs-nuxt@1.1.2, nuxt-security@0.14.4, nuxt-viewport@2.0.6, vue3-carousel-nuxt@1.1.0, vue-email/nuxt
- Build Modules:    -
------------------------------

### Reproduction

New instaled nuxt with modules

@hebilicious/authjs-nuxt@0.2.0-beta.8, @nuxt/image@1.0.0-rc.1, @nuxtjs/color-mode@3.3.0, @nuxtjs/i18n@8.0.0-rc.4, @nuxtjs/tailwindcss@6.8.0, @pinia/nuxt@0.4.11, @vee-validate/nuxt@4.11.3, @vueuse/nuxt@10.4.1, dayjs-nuxt@1.1.2, nuxt-security@0.14.4, nuxt-viewport@2.0.6, vue3-carousel-nuxt@1.1.0, vue-email/nuxt

### Describe the bug

-Nuxt 3.7.1 with Nitro 2.6.3-28235083.5639f5b                                                                                                              8:14:07 AM
                                                                                                                                                          8:14:09 AM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Adding @auth/nuxt module... { verifyClientOnEveryRequest: true,                                                                             @auth/nuxt 8:14:12 AM
  guestRedirectTo: '/',
  authenticatedRedirectTo: '/',
  baseUrl: '' }
✔ Added @auth/nuxt module successfully.                                                                                                       @auth/nuxt 8:14:12 AM
ℹ Vue I18n configuration file does not exist at i18n.config. Skipping...                                                                    @nuxtjs/i18n 8:14:13 AM
ℹ Using default Tailwind CSS file                                                                                                       nuxt:tailwindcss 8:14:13 AM
ℹ Using yup with vee-validate                                                                                                                            8:14:14 AM
✔ Nuxt DevTools is enabled v0.8.3 (experimental)                                                                                                         8:14:16 AM
ℹ Tailwind Viewer: http://127.0.0.1:33087/_tailwind/                                                                                    nuxt:tailwindcss 8:14:17 AM

 ERROR  Cannot start nuxt:  kit.writeTypes is not a function                                                                                              8:14:17 AM

  at NuxtDevServer._load (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/chunks/dev.mjs:230:11)
  at async NuxtDevServer.load (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/chunks/dev.mjs:161:7)
  at async NuxtDevServer.init (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/chunks/dev.mjs:156:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/chunks/dev-child.mjs:91:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/shared/nuxi.913ed971.mjs:1645:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/shared/nuxi.913ed971.mjs:1639:7)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.8.0/node_modules/nuxi/dist/shared/nuxi.913ed971.mjs:1757:7)

**Comment by imcm7** [comment]
I think problem appear after instalation of pnpm i @hebilicious/authjs-nuxt @auth/core
and 
```
"resolutions": { // for pnpm and yarn
    "h3": "1.8.0-rc.3",
    "nitropack": "npm:nitropack-edge@latest"
  }
 ```

**Comment by Hebilicious** [comment]
@imcm7 You can remove these resolutions if you are using a recent version of Nuxt. 
@danielroe was there any change related to writeTypes ? The only kit utility related to types I'm using in this module is `addTypeTemplate`
