### ISSUE TITLE
Vite plugin breaks nuxi build

### ISSUE THREAD

**Issue by learntheropes** [nuxt/nuxt#23091]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.17.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/learntheropes/github-anc6tm  
https://stackblitz.com/edit/github-anc6tm
But you need to build it.

### Describe the bug

I have `vite-plugin-node-polyfills` vite plguin as follows
```js
import { nodePolyfills } from 'vite-plugin-node-polyfills';

export default defineNuxtConfig({
  vite: {
    plugins: [
      nodePolyfills({
        include: ['buffer', 'util', 'stream', 'crypto'],
      }),
    ],
  },
});
```
That breaks `nuxi build` as follows :
```bash
(inject plugin) rollup-plugin-inject: failed to parse /home/giovanni/Documents/Dev/github-anc6tm/.nuxt/dist/server/server.mjs. Consider restricting the plugin to particular files via options.include

 ERROR  RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)                                                                                      nitro 7:53:52 PM


229:   }
230:   const head = inject(headSymbol);
231:   if (!head && dist.process.env.NODE_ENV !== "production")
                         ^
232:     console.warn("Unhead is missing Vue context, falling back to shared context. This may have unexpected results.");
233:   return head || getActiveHead();


 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)                                                                                                         7:53:52 PM

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:13726:16)
  at Module.tryParse (node_modules/rollup/dist/es/shared/node-entry.js:14457:25)
  at Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:14058:39)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:24623:20) 



 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript) 
```

**Comment by danielroe** [comment]
This looks like an issue with the plugin, not with Nuxt. I would suggest raising an issue there.
