### ISSUE TITLE
production memory leaks since version 3.6.1

### ISSUE THREAD

**Issue by memic84** [nuxt/nuxt#23193]
### Environment

- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.7.1
- CLI Version:      3.7.3
- Nitro Version:    2.6.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

The problem is that this bug only occurs on our staging / production environment. In our development we cannot reproduce the memory leak. Also recreating this in a minimal environment, is not possible because i cannot share access to our staging. I hope to get some more insights, when more information is provided. I can provide the heap snapshots through a private link, for further debugging.

### Describe the bug

After updating from 3.5 to 3.6 or 3.7. The memory in node keeps leaking, after every user / request, the memory goes up and the garbage collection doesn't seem to work. When running 3.5, everything seems fine.

We have tried the following things:
- Several node versions (16, 18 and 20)
- Disabling several server middleware, and plugins
- Fixed a lot of possible memory leaks in the code
- Bypassing our reverse proxy
- Done a lot of inspection the memory through dev tools, but i am not an expert in node and nuxt internals
- We've used --inspect to analyze the memory via dev tools
- An example, how i tested with apache benchmark. ab -n 100 -c 5 URL, which isn't event that much.. but the memory goes from 50mb to 300mb and stays there.

### Additional context

We are using the SSR mode for Nuxt 3, and the app is loaded in a Docker container, with a reverse proxy before it.

The app does mostly fetch calls, and we use a lot the server/api nitro where the calls is done server to server, en we just call /api on our side.

When a --inspect is detached to our staging, and we profile the memory through allocation sampling, i get the following result.

<img width="719" alt="image" src="https://github.com/nuxt/nuxt/assets/3043840/0f4940ac-46ed-4e78-b63e-a9a3ee9a83a3">

And when i look in more detail, it's something with the vue-router addRoute where a lot of memory stays allocated.

<img width="1030" alt="image" src="https://github.com/nuxt/nuxt/assets/3043840/43015000-644c-4c09-bd4a-53af01062803">

And here is the heapsnapshot with a difference between two intervals (in between are 50 users).

<img width="1028" alt="image" src="https://github.com/nuxt/nuxt/assets/3043840/18ac71cd-6985-4680-bf3c-07e7d42d518a">

Extended view
<img width="1019" alt="image" src="https://github.com/nuxt/nuxt/assets/3043840/795ffa3b-b9c8-436f-ba02-4baafc3eb3c2">

I can deliver the heap snapshots through a private link for debugging purposes. Any insights or help is welcome!

### Logs

```shell-script
<--- Last few GCs --->

[1:0x6e92480]    15641 ms: Scavenge (reduce) 394.1 (405.9) -> 393.7 (406.4) MB, 1.5 / 0.0 ms  (average mu = 0.133, current mu = 0.024) allocation failure; 
[1:0x6e92480]    15666 ms: Scavenge (reduce) 394.5 (406.4) -> 393.9 (406.7) MB, 2.3 / 0.0 ms  (average mu = 0.133, current mu = 0.024) allocation failure; 
[1:0x6e92480]    15686 ms: Scavenge (reduce) 394.7 (406.7) -> 394.1 (406.9) MB, 2.3 / 0.0 ms  (average mu = 0.133, current mu = 0.024) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb83f50 node::Abort() [node]
 2: 0xa94834  [node]
 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf42265  [node]
 6: 0xf43168 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xf53673  [node]
 8: 0xf544e8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf576b5 v8::internal::Heap::HandleGCRequest() [node]
10: 0xed580f v8::internal::StackGuard::HandleInterrupts() [node]
11: 0x12d6065 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x17035b9  [node]
```

**Comment by memic84** [comment]
Some additional information

We do have some errors in the logs, such as

**[nuxt] instance unavailable**
```
Error: [nuxt] instance unavailable
    at useNuxtApp (file:///data/apps/PROJECT/.output/server/chunks/app/server.mjs:1:4687)
    at useApiFetch (file:///data/apps/PROJECT/.output/server/chunks/app/server.mjs:1:141311)
    at Proxy.fetchCart (file:///data/apps/PROJECT/.output/server/chunks/app/server.mjs:1:145814)
    at async Object.setup (file:///data/apps/PROJECT/.output/server/chunks/app/server.mjs:1:149982)
    at async Object.callAsync (file:///data/apps/PROJECT/.output/server/node_modules/unctx/dist/index.mjs:72:16)
    at async applyPlugin (file:///data/apps/PROJECT/.output/server/chunks/app/server.mjs:1:4029)
    at async file:///data/apps/PROJECT/.output/server/chunks/app/server.mjs:1:154639
    at async Da (file:///data/apps/PROJECT/.output/server/chunks/app/server.mjs:1:154479)
    at async Object.renderToString (file:///data/apps/PROJECT/.output/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)
    at async _ (file:///data/apps/PROJECT/.output/server/chunks/handlers/renderer.mjs:1:2423)
```

**[request error] [unhandled] [401**
```
[nuxt] [request error] [unhandled] [401]  (401 Unauthorized (https://URL/api/PROJECT/nl-be/assortment/7c468eac-87dd-497d-aaf9-9080f6031a83/cart))
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ./.output/server/chunks/index.get4.mjs:1:315
  at async Object.handler (./.output/server/node_modules/h3/dist/index.mjs:1255:19)
  at async Server.toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:1330:7)
```

**missing template or render function**
```
[Vue warn]: Component <Anonymous> is missing template or render function.
```

**[request error] [unhandled] [404]**
```
[nuxt] [request error] [unhandled] [404]  (404 Not Found (https://URL/api/PROJECT/en-eu/assortment/ID/cart?cart=CART_ID))
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ./.output/server/chunks/index.get4.mjs:1:315
  at async Object.handler (./.output/server/node_modules/h3/dist/index.mjs:1255:19)
  at async toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:1330:7)
  at async ufetch (./.output/server/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (./.output/server/node_modules/ofetch/dist/shared/ofetch.502a4799.mjs:180:24)
  at async Proxy.fetchCart (./.output/server/chunks/app/server.mjs:1:145568)
  at async Object.setup (./.output/server/chunks/app/server.mjs:1:149982)
  at async Object.callAsync (./.output/server/node_modules/unctx/dist/index.mjs:72:16)
  at async applyPlugin (./.output/server/chunks/app/server.mjs:1:4029)
```

**[request error] [unhandled] [404]**
```
[nuxt] [request error] [unhandled] [404]  (404 Not Found (https://URL/api/PROJECT/nl-be/assortment/ID/product/PRODID/calculate?&variant[ID][quantity]=AMOUNT))
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ./.output/server/chunks/index.get18.mjs:1:482
  at async Object.handler (./.output/server/node_modules/h3/dist/index.mjs:1255:19)
  at async Server.toNodeHandle (./.output/server/node_modules/h3/dist/index.mjs:1330:7)
```

**Comment by heavywar** [comment]
same problem with memory leak

**Comment by manniL** [comment]
Folks, without some code or a reproduction (as mentioned above), it will be nearly impossible to track it down. Most memory leaks are part of userland code, e.g. misusing/abusing composables, forgotten timers/intervals etc. etc.

**Comment by imcm7** [comment]
@manniL that work, but if add to id services with repositories and 10 entities it work ugly. 
But with Bun it rebuild in dev in seconds. With pnpm it took minutes.

**Comment by memic84** [comment]
> Folks, without some code or a reproduction (as mentioned above), it will be nearly impossible to track it down. Most memory leaks are part of userland code, e.g. misusing/abusing composables, forgotten timers/intervals etc. etc.

Yes, i understand that we need a reproduction but the problem is that i can't reproduce it in stackbilitz, and i'll need to reproduce our production environment as close as possible. We are working on the reproduction.

Any insights about the addRoute which creates a lot of Objects? Or something else from the screenshots?

**Comment by memic84** [comment]
Hey @danielroe @manniL 

In our application we had the `NuxtLoadingIndicator` component in our default layout, and I noticed when removing this from my code, that the memory leaks were solved.

Could it be, that we shouldn't use this component in user code?

**Comment by danielroe** [comment]
Ouch. That's really helpful though. If you can get further with a reproduction, I can take a look.

**Comment by memic84** [comment]
I have tried to create reproduction here: https://github.com/memic84/nuxt-memory-leak-loading-indicator 

It still seems it's missing something to be a huge memory leak as in my code. It goes a little bit up.

I'll try to add the layers functionality, just the same way we use it and some other code as well to see if it's more visible.

**Comment by hakan-akgul** [comment]
Hello @memic84 @danielroe 

We have faced with exactly same issue
About 5 days, we try to find root cause of the memory leak

<img width="633" alt="image" src="https://github.com/nuxt/nuxt/assets/64319895/d4dd5807-ec5e-4d44-84a0-483efc085ed0">

**Comment by hakan-akgul** [comment]
Hi @memic84

Our memory leak problem solved completely after uninstall `@nuxtjs/i18n v8.0.0-rc.5`

Hope it helps

**Comment by konradsienkowski** [comment]
We also experienced memory leaks in production, so we stayed with version 3.5.3 for a long time. After an update to 3.8.0, the memory leak was still present. 

I tried out a simple experiment, wrapping the loading indicator component in `<ClientOnly>`. Memory leak doesn't seem to be present after that (according to Grafana metrics).
