### ISSUE TITLE
Issue with nuxi prepare, Cannot find module devtools

### ISSUE THREAD

**Issue by ZainW** [nuxt/nuxt#23245]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.6.1`
- Nuxt Version:     `3.7.3`
- CLI Version:      `3.8.4`
- Nitro Version:    `2.6.3`
- Package Manager:  `pnpm@8.7.5`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I init a new project, i run `pnpm i` and this is my issue. it just fails on `prepare` looking for devtools file that just does not exist

### Describe the bug

I was messing around with node potentially, now now matter what when i run npm i or pnpm i, i just cant get nuxi prepare to work. it just always crashes with the logs below.

I dont even have v18.15.0 installed, im using latest v20 verison and tested on v18.17.1 as well

### Additional context

its probably my fault but idk how else to move foward, i've deleted and removed all of node to the best of my ability and re-installed it using nvm and other node managers, went through the uninstall steps for nvm, asdf, volta, fnm and anything else i could think of

i also ncant reproduce it anywhere else than my local, not on stackblitz or codesandbox, its a me thing

### Logs

```shell-script
[7:14:53 p.m.]  ERROR  Error while requiring module /Users/zain/.nvm/versions/node/v18.15.0/lib/node_modules/@nuxt/devtools/module.cjs: Error: Cannot find module '/Users/zain/.nvm/versions/node/v18.15.0/lib/node_modules/@nuxt/devtools/module.cjs'
Require stack:
- /Users/zain/labs/nuxxx/index.js


 ERROR  Cannot find module '/Users/zain/.nvm/versions/node/v18.15.0/lib/node_modules/@nuxt/devtools/module.cjs'                                                          7:14:53 p.m.
Require stack:
- /Users/zain/labs/nuxxx/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
  at Function.resolve (node:internal/modules/helpers:136:19)
  at Function._resolve [as resolve] (node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:250334)
  at resolveModule (node_modules/.pnpm/@nuxt+kit@3.7.3/node_modules/@nuxt/kit/dist/index.mjs:2239:29)
  at requireModule (node_modules/.pnpm/@nuxt+kit@3.7.3/node_modules/@nuxt/kit/dist/index.mjs:2244:24)
  at loadNuxtModuleInstance (node_modules/.pnpm/@nuxt+kit@3.7.3/node_modules/@nuxt/kit/dist/index.mjs:2459:90)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.7.3/node_modules/@nuxt/kit/dist/index.mjs:2425:47)
  at async initNuxt (node_modules/.pnpm/nuxt@3.7.3/node_modules/nuxt/dist/index.mjs:3563:7)
  at async loadNuxt (node_modules/.pnpm/nuxt@3.7.3/node_modules/nuxt/dist/index.mjs:3646:5)
  at async loadNuxt (node_modules/.pnpm/@nuxt+kit@3.7.3/node_modules/@nuxt/kit/dist/index.mjs:2571:19)
```

**Comment by pi0** [comment]
I think we shall make it a softwarning when devtools (global) is not enabled. Wdyt @antfu @danielroe ?

**Comment by ZainW** [comment]
im sure others would have figured it out faster, but this took away a few hours of time before figuring it out 😆 

if something small could help someone either trace or fix an issue im sure someone ion the future would be appreciative

**Comment by jojomatik** [comment]
> I think we shall make it a softwarning when devtools (global) is not enabled. Wdyt @antfu @danielroe ?

I think this would be a great idea. For some reason some old installation of node was referenced in `.nuxtrc` for me. I wondered how this could even be a problem when I disabled devtools explicitly. 

Also I'm wondering: What is the reason to store that hardcoded path? Similar to @ZainW I'm using nvm and update to a new node version regularly. Apparently that breaks it (at least sometimes?)
