### ISSUE TITLE
Running docs under WSL is not possible

### ISSUE THREAD

**Issue by edimitchel** [nuxt/nuxt#23260]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.2.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.3
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.6.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Under a WSL 2 environment, simply run the command `pnpm build:stub` to build all workspace projects before running any command which need projects finely built.

You'll receive the error I get.

### Describe the bug

Running the docs locally is just not possible under a WSL environment.
The command for building all workspace projects fails on the first step.

### Logs

```shell-script
> nuxt-framework@ build:stub /home/micheledighoffer/DEV/OSS/nuxt
> pnpm --filter './packages/**' prepack --stub

Scope: 6 of 14 workspace projects
packages/schema prepack$ unbuild "--stub"
│ ℹ Stubbing @nuxt/schema
│ Error building /home/micheledighoffer/DEV/OSS/nuxt/packages/schema: Error: TRANSFORM_ERROR: Property body of FunctionDeclaration expected node to be of a type ["Bl
│  /home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/@nuxt+ui-templates@1.3.1/node_modules/@nuxt/ui-templates/dist/templates/error-404.mjs:0:0
│ Error: TRANSFORM_ERROR: Property body of FunctionDeclaration expected node to be of a type ["BlockStatement"] but instead got "CallExpression" 
│  /home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/@nuxt+ui-templates@1.3.1/node_modules/@nuxt/ui-templates/dist/templates/error-404.mjs:0:0
│     at /home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/@nuxt+ui-templates@1.3.1/node_modules/@nuxt/ui-templates/dist/index.mjs:1:826
│     at evalModule (/home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:255614)
│     at jiti (/home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:253542)
│     at /home/micheledighoffer/DEV/OSS/nuxt/packages/schema/src/config/dev.ts:2:20
│     at evalModule (/home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:255614)
│     at jiti (/home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:253542)
│     at /home/micheledighoffer/DEV/OSS/nuxt/packages/schema/src/config/index.ts:5:35
│     at evalModule (/home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:255614)
│     at jiti (/home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/jiti@1.20.0/node_modules/jiti/dist/jiti.js:1:253542)
│     at typesBuild (file:///home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/unbuild@0.8.11/node_modules/unbuild/dist/shared/unbuild.8a8f7183.mjs:629:23)
│     at async build (file:///home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/unbuild@0.8.11/node_modules/unbuild/dist/shared/unbuild.8a8f7183.mjs:794:3)
│     at async main (file:///home/micheledighoffer/DEV/OSS/nuxt/node_modules/.pnpm/unbuild@0.8.11/node_modules/unbuild/dist/cli.mjs:38:3)
└─ Failed in 1.2s at /home/micheledighoffer/DEV/OSS/nuxt/packages/schema
/home/micheledighoffer/DEV/OSS/nuxt/packages/schema:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @nuxt/schema@3.7.3 prepack: `unbuild "--stub"`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Mateleo** [comment]
The codebase is very different (it's now `nuxt prepare`), but under WSL2 W10 it works like a charm (4.4.8)

Can be closed @danielroe

**Comment by danielroe** [comment]
nuxtathon closed @Mateleo
