### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'NUXT_ASYNC_CONTEXT')     at nuxt.js:5:31

### ISSUE THREAD

**Issue by sagardspeed2** [nuxt/nuxt#23272]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.7.0
- Nitro Version:    2.6.3
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

use Nuxt 3.7.0 with nuxi 3.5.0

### Describe the bug

Getting error when I start development server,

Uncaught TypeError: Cannot read properties of undefined (reading 'NUXT_ASYNC_CONTEXT')
    at nuxt.js:5:31
    
   From nuxt.js
 ```
 const nuxtAppCtx = /* @__PURE__ */ getContext("nuxt-app", {
  asyncContext: !!process.env.NUXT_ASYNC_CONTEXT && process.server
});
```

**Comment by sagardspeed2** [comment]
@danielroe 

Here I am attaching my package.json,

when I am using nuxt - 3.7.0 or above, I get error, but when I use nuxt - 3.5.0
working fine

```
{
	"name": "tairo-quickstarter",
	"private": true,
	"type": "module",
	"devDependencies": {
		"@types/js-cookie": "^3.0.3",
		"@types/marked": "^5.0.0",
		"@types/uuid": "^9.0.2",
		"nuxt": "3.7.0",
		"nuxt-simple-robots": "^3.1.3",
		"nuxt-simple-sitemap": "^3.3.2"
	},
	"scripts": {
		"prepare": "nuxi prepare",
		"dev": "nuxi dev",
		"build": "nuxi build",
		"generate": "nuxi generate",
		"clean": "rimraf .nuxt .output node_modules"
	},
	"dependencies": {
		"@pinia/nuxt": "^0.4.11",
		"@splidejs/vue-splide": "^0.6.12",
		"@vueform/slider": "^2.1.7",
		"apexcharts": "^3.41.0",
		"crypto-js": "^4.1.1",
		"firebase": "^10.0.0",
		"highlight.js": "^11.8.0",
		"js-cookie": "^3.0.5",
		"marked": "^5.1.0",
		"mitt": "^3.0.1",
		"moment": "^2.29.4",
		"nuxt-vuefire": "^0.2.1",
		"pdfjs-dist": "^3.8.162",
		"pinia": "^2.1.4",
		"sass": "^1.63.6",
		"sweetalert2": "^11.7.12",
		"uuid": "^9.0.0",
		"v-calendar": "^3.0.1",
		"vue3-apexcharts": "^1.4.1",
		"vue3-carousel": "^0.3.1",
		"vue3-toastify": "^0.1.11",
		"vuefire": "^3.1.2",
		"yup": "^1.2.0"
	}
}
```

**Comment by danielroe** [comment]
Ideally I need a runnable reproduction. See the details in the comment above.
