### ISSUE TITLE
Rollup failed when using custom components and CommonJS dependency

### ISSUE THREAD

**Issue by AnotiaWang** [nuxt/nuxt#23279]
### Environment

Working directory: /home/projects/github-cxu4cp                                                                                 22:20:47
Nuxt project info:                                                                                                              22:20:47

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.3
- CLI Version:      3.8.4
- Nitro Version:    2.6.3
- Package Manager:  pnpm@8.6.10
- Builder:          -
- User Config:      modules, vite
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-cxu4cp?file=pages%2Findex.vue

### Describe the bug

> I'm not very sure if this issue applies to all CommonJS dependencies, I only tested [SheetJS](https://npmjs.com/xlsx)

Based on my tests:
- Seems that the bug exists for all Nuxt 3.x versions, tested 3.0, 3.4, 3.5. 3.6, 3.7
- Binding the function that uses CommonJS dependency to a native element (like `div`) is fine. The bug only appears when the function is binded to custom components.
- The bug exists when `ssr` is set to true in `nuxt.config.ts`. Disabling SSR solves the problem.

### Logs

```shell-script
ℹ Building server...                                                                                                           22:27:36
ℹ vite v4.4.9 building SSR bundle for production...                                                                            22:27:36
ℹ ✓ 75 modules transformed.                                                                                                    22:27:36
ℹ .nuxt/dist/server/_nuxt/entry-styles.5a916124.mjs            0.08 kB                                                         22:27:37
ℹ .nuxt/dist/server/_nuxt/error-404-styles.ba403077.mjs        0.15 kB                                                         22:27:37
ℹ .nuxt/dist/server/_nuxt/error-500-styles.b9dc3876.mjs        0.15 kB                                                         22:27:37
ℹ .nuxt/dist/server/styles.mjs                                 0.59 kB                                                         22:27:37
ℹ .nuxt/dist/server/_nuxt/index-6a088328.js                    0.98 kB │ map:  4.92 kB                                         22:27:37
ℹ .nuxt/dist/server/_nuxt/island-renderer-bdb201ea.js          1.09 kB │ map:  1.43 kB                                         22:27:37
ℹ .nuxt/dist/server/_nuxt/index-3992fda5.js                    2.16 kB │ map:  1.24 kB                                         22:27:37
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-3b8a92b3.js   2.23 kB │ map:  0.12 kB                                         22:27:37
ℹ .nuxt/dist/server/_nuxt/error-500-06965ca9.js                3.15 kB │ map:  3.82 kB                                         22:27:37
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-e9de87b9.js   3.93 kB │ map:  0.12 kB                                         22:27:37
ℹ .nuxt/dist/server/_nuxt/entry-styles-1.mjs-25ef25e9.js       5.30 kB │ map:  0.11 kB                                         22:27:37
ℹ .nuxt/dist/server/_nuxt/error-404-171d7a5d.js                9.82 kB │ map: 19.06 kB                                         22:27:37
ℹ .nuxt/dist/server/server.mjs                                34.22 kB │ map: 79.87 kB                                         22:27:37
ℹ ✓ built in 834ms                                                                                                             22:27:37
✔ Server built in 839ms                                                                                                        22:27:37
✔ Generated public .output/public                                                                                        nitro 22:27:37
ℹ Initializing prerenderer                                                                                               nitro 22:27:37

 ERROR  RollupError: Could not resolve "./dist/cpexcel.js" from "./dist/cpexcel.js?commonjs-external"                     nitro 22:27:38


undefined


 ERROR  Could not resolve "./dist/cpexcel.js" from "./dist/cpexcel.js?commonjs-external"                                        22:27:38

  at error (node_modules/.pnpm/rollup@3.29.2/node_modules/rollup/dist/es/shared/node-entry.js:2312:30)
  at ModuleLoader.handleInvalidResolvedId (node_modules/.pnpm/rollup@3.29.2/node_modules/rollup/dist/es/shared/node-entry.js:24880:24)
  at eval (node_modules/.pnpm/rollup@3.29.2/node_modules/rollup/dist/es/shared/node-entry.js:24842:26) 



 ERROR  Could not resolve "./dist/cpexcel.js" from "./dist/cpexcel.js?commonjs-external"                                        22:27:38

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by AnotiaWang** [comment]
Temporarily resolved this issue by wrapping the related elements with `<ClientOnly>`

**Comment by Flo0806** [comment]
@danielroe We have a workaround + now we using rolldown and with rolldown it is no longer reproducible

**Comment by danielroe** [comment]
nuxtathon closed @Flo0806
