### ISSUE TITLE
nuxt build - vite 4 RollupError

### ISSUE THREAD

**Issue by gr1nch3** [nuxt/nuxt#23517]
### Environment

Nuxt project info:                                                                                                                                                                      2:32:18 PM

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      modules, devtools, css, postcss
- Runtime Modules:  @pinia/nuxt@0.4.11, nuxt-icon@0.5.0
- Build Modules:    -
------------------------------

### Reproduction
```
>  build
> nuxt build

Nuxt 3.7.4 with Nitro 2.6.3                                                                                                                                                             2:33:06 PM
ℹ Building client...                                                                                                                                                                   2:33:09 PM
ℹ vite v4.4.9 building for production...                                                                                                                                               2:33:09 PM
ℹ ✓ 186 modules transformed.                                                                                                                                                           2:33:15 PM
ℹ .nuxt/dist/client/manifest.json                     5.82 kB │ gzip:  0.77 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/Icon.6f5d80f8.css           0.07 kB │ gzip:  0.09 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/IconCSS.fe0874d9.css        0.26 kB │ gzip:  0.17 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/error-500.c5df6088.css      1.95 kB │ gzip:  0.74 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/error-404.7fc72018.css      3.63 kB │ gzip:  1.12 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/config.2a840f4e.js          0.18 kB │ gzip:  0.16 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/vue.f36acd1f.785f231e.js    0.39 kB │ gzip:  0.27 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/IconCSS.c7bfce07.js         0.84 kB │ gzip:  0.54 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/login.313f21a1.js           1.68 kB │ gzip:  0.83 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/error-500.7fcceeb5.js       1.92 kB │ gzip:  1.01 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/error-404.cadf318f.js       2.29 kB │ gzip:  1.18 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/Header.vue.3d07506c.js      2.58 kB │ gzip:  1.08 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/index.828fba2e.js           3.13 kB │ gzip:  1.49 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/signup.4ffdbe0b.js          3.37 kB │ gzip:  1.30 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/_id_.4d31cf73.js            3.51 kB │ gzip:  1.44 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/nuxt-link.65e3f0fc.js       4.06 kB │ gzip:  1.72 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/index.cf2d341d.js           4.39 kB │ gzip:  1.96 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/details.cbcfcd14.js         4.85 kB │ gzip:  1.87 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/index.729d4e1d.js           9.89 kB │ gzip:  3.47 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/Blog.vue.cd6b729d.js       18.83 kB │ gzip:  4.73 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/Icon.8796966b.js           21.70 kB │ gzip:  8.28 kB                                                                                                         2:33:15 PM
ℹ .nuxt/dist/client/_nuxt/entry.27e5354a.js         177.08 kB │ gzip: 65.93 kB                                                                                                         2:33:15 PM
ℹ ✓ built in 5.90s                                                                                                                                                                     2:33:15 PM
✔ Client built in 5918ms                                                                                                                                                               2:33:15 PM
ℹ Building server...                                                                                                                                                                   2:33:15 PM
ℹ vite v4.4.9 building SSR bundle for production...                                                                                                                                    2:33:15 PM
ℹ ✓ 132 modules transformed.                                                                                                                                                           2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/entry-styles.18618fb6.mjs            0.08 kB                                                                                                                 2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/Icon-styles.3c97f940.mjs             0.14 kB                                                                                                                 2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/IconCSS-styles.9ba8332f.mjs          0.15 kB                                                                                                                 2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/error-404-styles.1e0dde27.mjs        0.15 kB                                                                                                                 2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/error-500-styles.cf4b3e80.mjs        0.15 kB                                                                                                                 2:33:19 PM
ℹ .nuxt/dist/server/styles.mjs                                 0.71 kB                                                                                                                 2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/Icon-styles-1.mjs-a085ffd6.js        0.26 kB │ map:   0.11 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/IconCSS-styles-1.mjs-54a74734.js     0.46 kB │ map:   0.11 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/index-6a088328.js                    0.98 kB │ map:   4.83 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/island-renderer-f451278e.js          1.16 kB │ map:   1.41 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/config-f07c7223.js                   1.86 kB │ map:   5.33 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-8fa81fcc.js   2.17 kB │ map:   0.12 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/login-b57c6cac.js                    2.32 kB │ map:   3.04 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/IconCSS-e9995d97.js                  2.45 kB │ map:   2.01 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/error-500-4a054ea0.js                3.17 kB │ map:   3.78 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-e0837f4f.js   3.86 kB │ map:   0.12 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/error-404-239d2913.js                4.06 kB │ map:   5.82 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/signup-782b9feb.js                   4.09 kB │ map:   5.16 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/index-8f48938c.js                    4.16 kB │ map:   4.60 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/_id_-7adf08c8.js                     5.38 kB │ map:   5.80 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/Icon-4fbc22a0.js                     5.44 kB │ map:   5.79 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/nuxt-link-99c863e4.js                6.02 kB │ map:  13.29 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/Header-678c73b1.js                   7.28 kB │ map:   4.04 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/details-85aab0ca.js                  7.32 kB │ map:   8.77 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/index-3f6cbf39.js                    7.38 kB │ map:   9.01 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/index-0a089f2b.js                   13.26 kB │ map:  27.52 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/Blog-b965a041.js                    24.92 kB │ map:  36.40 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/_nuxt/entry-styles-1.mjs-1a47046c.js      64.73 kB │ map:   0.11 kB                                                                                                2:33:19 PM
ℹ .nuxt/dist/server/server.mjs                                88.86 kB │ map: 225.06 kB                                                                                                2:33:19 PM
ℹ ✓ built in 4.13s                                                                                                                                                                     2:33:19 PM
✔ Server built in 4152ms                                                                                                                                                               2:33:19 PM
✔ Generated public .output/public                                                                                                                                                nitro 2:33:19 PM
ℹ Building Nitro Server (preset: node-server)                                                                                                                                    nitro 2:33:19 PM

 ERROR  RollupError: "isScriptProtocol" is not exported by "node_modules/ufo/dist/index.mjs", imported by ".nuxt/dist/server/server.mjs".                                         nitro 2:33:25 PM


12: import { createMemoryHistory, createRouter, START_LOCATION, useRoute as useRoute$1, RouterView } from "vue-router";
13: import { sanitizeStatusCode, createError as createError$1, getRequestHeader, setCookie, getCookie, deleteCookie } fro...
14: import { withQuery, hasProtocol, parseURL, isScriptProtocol, joinURL } from "ufo";
                                               ^
15: import { parse } from "cookie-es";
16: import { hash, isEqual } from "ohash";


 ERROR  "isScriptProtocol" is not exported by "node_modules/ufo/dist/index.mjs", imported by ".nuxt/dist/server/server.mjs".                                                            2:33:25 PM

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
  at Module.traceVariable (node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
  at ReturnValueScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at ChildScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at TrackingScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at BlockScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at Identifier.bind (node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
  at CallExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:5892:23) 



 ERROR  "isScriptProtocol" is not exported by "node_modules/ufo/dist/index.mjs", imported by ".nuxt/dist/server/server.mjs".                                                            2:33:25 PM
```

### Describe the bug

'isScriptProtocol' from ufo leads to `` RollupError: "isScriptProtocol" is not exported by "node_modules/ufo/dist/index.mjs", imported by ".nuxt/dist/server/server.mjs".``  when building the nitro server.

```
 ERROR  RollupError: "isScriptProtocol" is not exported by "node_modules/ufo/dist/index.mjs", imported by ".nuxt/dist/server/server.mjs".                                         nitro 2:33:25 PM


12: import { createMemoryHistory, createRouter, START_LOCATION, useRoute as useRoute$1, RouterView } from "vue-router";
13: import { sanitizeStatusCode, createError as createError$1, getRequestHeader, setCookie, getCookie, deleteCookie } fro...
14: import { withQuery, hasProtocol, parseURL, isScriptProtocol, joinURL } from "ufo";
                                               ^
15: import { parse } from "cookie-es";
16: import { hash, isEqual } from "ohash";


 ERROR  "isScriptProtocol" is not exported by "node_modules/ufo/dist/index.mjs", imported by ".nuxt/dist/server/server.mjs".                                                            2:33:25 PM

  at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
  at Module.traceVariable (node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
  at ReturnValueScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at ChildScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at TrackingScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at BlockScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at Identifier.bind (node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
  at CallExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:5892:23) 



 ERROR  "isScriptProtocol" is not exported by "node_modules/ufo/dist/index.mjs", imported by ".nuxt/dist/server/server.mjs".                                                            2:33:25 PM
```

### Additional context

I am working on a nuxt app that uses a wildcard subdomain to render a page based on the subdomain, using a custom router in ``app/router.options.ts``  and two directories in the pages folder "root-domain" and  "sub-domain".  source: https://stackoverflow.com/a/76719139

the process works in development mode and root-domain/sub-domain are handle accordingly. 

I have tried building similar app without the subdomain routing and it works,

**Comment by joelod** [comment]
I had a similar issue a while ago that I ended up fixing by removing a few devDependencies (that I wasn't even using).

Can you share your devDependencies?

**Comment by gr1nch3** [comment]
Sure!, here's what I got:

```

"devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxt/image": "^0.7.1",
    "@types/node": "^18.16.19",
    "autoprefixer": "^10.4.14",
    "daisyui": "^3.2.1",
    "nuxt": "^3.6.3",
    "nuxt-icon": "^0.5.0",
    "postcss": "^8.4.26",
    "tailwindcss": "^3.3.3"
  },
  "overrides": {
    "vue": "^3.3.4"
  },
  "dependencies": {
    "@pinia/nuxt": "^0.4.11",
    "pinia": "^2.1.4"
  }

```

**Comment by joelod** [comment]
Thanks, we do have a match.

I had **"@nuxt/image": "^0.7.1"** aswel, but I ended up removing it, it was one of the dependencies that I used for a few tests in dev but ended up not using on production. Just tried adding it again and I'm getting the same _"ERROR  "isScriptProtocol" is not exported by "node_modules/ufo/dist/index.mjs", imported by ".nuxt/dist/server/server.mjs"._
when I enable **"@nuxt/image": "^0.7.1"**.

Looks like there's an incompatibility with this dependecy and the UFO version used by Nuxt. I didn't go too deep, but the issue in there.

**Comment by gr1nch3** [comment]
@joelod Thanks so much for this, and I apparently had no use for the **"@nuxt/image"** also.
I removed it from the devdependencies, deleted the **"package.lock.json"** file, the **".nuxt"** and **"node_modules"** directories and did a clean **"npm install"**, and it works!

I'm closing this issue with this, thanks again @joelod

**Comment by joelod** [comment]
@gr1nch3 You're welcome, glad I could help!
