### ISSUE TITLE
Getting an error if clicking NuxtLink routing to an async page twice

### ISSUE THREAD

**Issue by Larsmyrup** [nuxt/nuxt#23636]
### Environment

 Operating System: Darwin
- Node Version:     v20.0.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.6.4
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

Checkout [the repo](https://github.com/Larsmyrup/nuxt-routing-error) or go to [this Stackblitz](https://stackblitz.com/github/Larsmyrup/nuxt-routing-error).

First page has a NuxtLink with the text 'Link', it links to a page called "routed". Routed is an async component, resolving a promise after 10 seconds.

If you click the link once and wait 10 seconds, you get routed (as expected).

However if you click it, and click it again before the 10 seconds, an error is thrown. After the 10 seconds has passed, another error gets thrown and the original page content gets unmounted.

### Describe the bug

Double tapping a NuxtLink, linking to a page with an async component still resolving, breaks the page.

### Additional context

Let me know if there's anything i need to elaborate.

### Logs

```shell-script
chunk-RAKT47ZN.js:2710 <Suspense> is an experimental feature and its API will likely change.
chunk-RAKT47ZN.js:1449 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <RouteProvider key="/routed" vnode= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …} route= {fullPath: '/routed', hash: '', query: {…}, name: 'routed', path: '/routed', …}  ... > 
  at <RouterView name=undefined route=undefined > 
  at <NuxtPage> 
  at <NuxtLayoutProvider layoutProps= {ref: RefImpl} key="default" name="default"  ... > 
  at <NuxtLayout> 
  at <App key=3 > 
  at <NuxtRoot>
warn2 @ chunk-RAKT47ZN.js:1449
logError @ chunk-RAKT47ZN.js:1623
handleError @ chunk-RAKT47ZN.js:1615
callWithErrorHandling @ chunk-RAKT47ZN.js:1567
flushJobs @ chunk-RAKT47ZN.js:1763
Promise.then (async)
queueFlush @ chunk-RAKT47ZN.js:1676
queueJob @ chunk-RAKT47ZN.js:1670
(anonymous) @ chunk-RAKT47ZN.js:7208
triggerEffect @ chunk-RAKT47ZN.js:614
triggerEffects @ chunk-RAKT47ZN.js:604
triggerRefValue @ chunk-RAKT47ZN.js:1211
set value @ chunk-RAKT47ZN.js:1255
syncCurrentRoute @ router.js?v=78c91318:68
(anonymous) @ router.js?v=78c91318:73
(anonymous) @ vue-router.js:2547
runWithContext @ chunk-RAKT47ZN.js:5256
runWithContext @ vue-router.js:2485
(anonymous) @ vue-router.js:2547
triggerAfterEach @ vue-router.js:2547
(anonymous) @ vue-router.js:2475
Promise.then (async)
pushWithRedirect @ vue-router.js:2441
push @ vue-router.js:2367
navigate @ vue-router.js:1621
callWithErrorHandling @ chunk-RAKT47ZN.js:1565
callWithAsyncErrorHandling @ chunk-RAKT47ZN.js:1573
invoker @ chunk-RAKT47ZN.js:9397
chunk-RAKT47ZN.js:9157 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (chunk-RAKT47ZN.js:9157:30)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-RAKT47ZN.js:7175:11)
    at ReactiveEffect.run (chunk-RAKT47ZN.js:423:19)
    at instance.update (chunk-RAKT47ZN.js:7212:52)
    at updateComponent (chunk-RAKT47ZN.js:7039:18)
    at processComponent (chunk-RAKT47ZN.js:6974:7)
    at patch (chunk-RAKT47ZN.js:6436:11)
    at patchSuspense (chunk-RAKT47ZN.js:2562:7)
    at Object.process (chunk-RAKT47ZN.js:2481:7)
    at patch (chunk-RAKT47ZN.js:6461:16)
parentNode @ chunk-RAKT47ZN.js:9157
componentUpdateFn @ chunk-RAKT47ZN.js:7175
run @ chunk-RAKT47ZN.js:423
instance.update @ chunk-RAKT47ZN.js:7212
updateComponent @ chunk-RAKT47ZN.js:7039
processComponent @ chunk-RAKT47ZN.js:6974
patch @ chunk-RAKT47ZN.js:6436
patchSuspense @ chunk-RAKT47ZN.js:2562
process @ chunk-RAKT47ZN.js:2481
patch @ chunk-RAKT47ZN.js:6461
componentUpdateFn @ chunk-RAKT47ZN.js:7171
run @ chunk-RAKT47ZN.js:423
instance.update @ chunk-RAKT47ZN.js:7212
callWithErrorHandling @ chunk-RAKT47ZN.js:1565
flushJobs @ chunk-RAKT47ZN.js:1763
Promise.then (async)
queueFlush @ chunk-RAKT47ZN.js:1676
queueJob @ chunk-RAKT47ZN.js:1670
(anonymous) @ chunk-RAKT47ZN.js:7208
triggerEffect @ chunk-RAKT47ZN.js:614
triggerEffects @ chunk-RAKT47ZN.js:604
triggerRefValue @ chunk-RAKT47ZN.js:1211
set value @ chunk-RAKT47ZN.js:1255
syncCurrentRoute @ router.js?v=78c91318:68
(anonymous) @ router.js?v=78c91318:73
(anonymous) @ vue-router.js:2547
runWithContext @ chunk-RAKT47ZN.js:5256
runWithContext @ vue-router.js:2485
(anonymous) @ vue-router.js:2547
triggerAfterEach @ vue-router.js:2547
(anonymous) @ vue-router.js:2475
Promise.then (async)
pushWithRedirect @ vue-router.js:2441
push @ vue-router.js:2367
navigate @ vue-router.js:1621
callWithErrorHandling @ chunk-RAKT47ZN.js:1565
callWithAsyncErrorHandling @ chunk-RAKT47ZN.js:1573
invoker @ chunk-RAKT47ZN.js:9397
chunk-RAKT47ZN.js:7520 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'subTree')
    at move (chunk-RAKT47ZN.js:7520:28)
    at move (chunk-RAKT47ZN.js:7520:7)
    at Object.resolve (chunk-RAKT47ZN.js:2789:11)
    at chunk-RAKT47ZN.js:2912:20
move @ chunk-RAKT47ZN.js:7520
move @ chunk-RAKT47ZN.js:7520
resolve @ chunk-RAKT47ZN.js:2789
(anonymous) @ chunk-RAKT47ZN.js:2912
Promise.then (async)
registerDep @ chunk-RAKT47ZN.js:2876
mountComponent @ chunk-RAKT47ZN.js:7003
processComponent @ chunk-RAKT47ZN.js:6963
patch @ chunk-RAKT47ZN.js:6436
componentUpdateFn @ chunk-RAKT47ZN.js:7106
run @ chunk-RAKT47ZN.js:423
instance.update @ chunk-RAKT47ZN.js:7212
setupRenderEffect @ chunk-RAKT47ZN.js:7220
mountComponent @ chunk-RAKT47ZN.js:7010
processComponent @ chunk-RAKT47ZN.js:6963
patch @ chunk-RAKT47ZN.js:6436
patchSuspense @ chunk-RAKT47ZN.js:2678
process @ chunk-RAKT47ZN.js:2481
patch @ chunk-RAKT47ZN.js:6461
componentUpdateFn @ chunk-RAKT47ZN.js:7171
run @ chunk-RAKT47ZN.js:423
instance.update @ chunk-RAKT47ZN.js:7212
callWithErrorHandling @ chunk-RAKT47ZN.js:1565
flushJobs @ chunk-RAKT47ZN.js:1763
Promise.then (async)
queueFlush @ chunk-RAKT47ZN.js:1676
queueJob @ chunk-RAKT47ZN.js:1670
(anonymous) @ chunk-RAKT47ZN.js:7208
triggerEffect @ chunk-RAKT47ZN.js:614
triggerEffects @ chunk-RAKT47ZN.js:604
triggerRefValue @ chunk-RAKT47ZN.js:1211
(anonymous) @ chunk-RAKT47ZN.js:1371
triggerEffect @ chunk-RAKT47ZN.js:614
triggerEffects @ chunk-RAKT47ZN.js:599
triggerRefValue @ chunk-RAKT47ZN.js:1211
set value @ chunk-RAKT47ZN.js:1255
finalizeNavigation @ vue-router.js:2563
(anonymous) @ vue-router.js:2473
Promise.then (async)
pushWithRedirect @ vue-router.js:2441
push @ vue-router.js:2367
navigate @ vue-router.js:1621
callWithErrorHandling @ chunk-RAKT47ZN.js:1565
callWithAsyncErrorHandling @ chunk-RAKT47ZN.js:1573
invoker @ chunk-RAKT47ZN.js:9397
```

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/13309
