### ISSUE TITLE
Switched from bun to pnpm and  builder: 'webpack'

### ISSUE THREAD

**Issue by imcm7** [nuxt/nuxt#23644]
### Environment

Nuxt 3.8.0-28284309.b3d3d7f4 with Nitro 2.6.3                                      
                   

### Reproduction

                                                                                                                            
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Adding @auth/nuxt module... { verifyClientOnEveryRequest: true,                                                                              @auth/nuxt 5:49:16 PM
  guestRedirectTo: '/',
  authenticatedRedirectTo: '/',
  baseUrl: '' }
✔ Added @auth/nuxt module successfully.                                                                                                        @auth/nuxt 
ℹ Using default Tailwind CSS file                                                                                                        nuxt:tailwindcss 

 WARN  Nuxt DevTools only supports Vite mode, module is disabled.                                                                                          5:49:19 PM

ℹ Tailwind Viewer: http://localhost:3000/_tailwind/                                                                                      nuxt:tailwindcss  

 ERROR  Cannot start nuxt:  Maximum call stack size exceeded                                                                                               

### Describe the bug

  at deepmerge (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:100:19)
  at cloneUnlessOtherwiseSpecified (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:34:5)
  at node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:94:23
  at Array.forEach (<anonymous>)
  at mergeObject (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:86:18)
  at deepmerge (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:117:10)
  at cloneUnlessOtherwiseSpecified (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:34:5)
  at node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:94:23
  at Array.forEach (<anonymous>)
  at mergeObject (node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js:86:18)

**Comment by imcm7** [comment]
webpack si also with esbuild?

**Comment by imcm7** [comment]
@warflash https://github.com/imcm7/nuxt-db/blob/main/nuxt.config.ts
