### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Cannot find module 'semver'

### ISSUE THREAD

**Issue by Niki2k1** [nuxt/nuxt#23783]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      typescript, nitro, runtimeConfig, css, build, modules, auth, pwa, vite
- Runtime Modules:  @pinia/nuxt@0.5.1, @kevinmarrec/nuxt-pwa@0.17.0, @sidebase/nuxt-auth@0.5.0
- Build Modules:    -

### Reproduction

https://github.com/Niki2k1/nuxt-bug-reproduction

1. `npm install`
2. `npm run dev`
3. go to localhost:3000/ and see the random pw and the hash created with argon2
4. run `npm run build`
5. copy the .output folder to another location
6. run `node .output/server/index.mjs`
7. see errors in console

### Describe the bug

When using bcrypt or argon2 (seems to be any node-pre-gyp library) I get an 500 Error when trying to access my site on a windows build.

### Logs

```shell-script
Listening on http://[::]:3000
[nuxt] [request error] [unhandled] [500] Cannot find module 'nopt'
Require stack:
- C:path\bug-reproduction\.output\server\node_modules\@mapbox\node-pre-gyp\lib\node-pre-gyp.js
- C:path\bug-reproduction\.output\server\node_modules\argon2\argon2.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  at Module._load (node:internal/modules/cjs/loader:922:27)
  at Module.require (node:internal/modules/cjs/loader:1143:19)
  at require (node:internal/modules/cjs/helpers:119:18)
  at Object.<anonymous> (C:path\bug-reproduction\.output\server\node_modules\@mapbox\node-pre-gyp\lib\node-pre-gyp.js:22:14)
  at Module._compile (node:internal/modules/cjs/loader:1256:14)
  at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
  at Module.load (node:internal/modules/cjs/loader:1119:32)
  at Module._load (node:internal/modules/cjs/loader:960:12)
  at Module.require (node:internal/modules/cjs/loader:1143:19)
[nitro] [unhandledRejection] Error: Cannot find module 'nopt'
Require stack:
- C:path\bug-reproduction\.output\server\node_modules\@mapbox\node-pre-gyp\lib\node-pre-gyp.js
- C:path\bug-reproduction\.output\server\node_modules\argon2\argon2.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:path\bug-reproduction\.output\server\node_modules\@mapbox\node-pre-gyp\lib\node-pre-gyp.js:22:14)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\path\\bug-reproduction\\.output\\server\\node_modules\\@mapbox\\node-pre-gyp\\lib\\node-pre-gyp.js',
    'C:\\path\\bug-reproduction\\.output\\server\\node_modules\\argon2\\argon2.js'
  ]
}
```

**Comment by danielroe** [comment]
Would you see if this is reproducible with pure Nitro on Windows? You could try downloading this and running it.

https://stackblitz.com/edit/github-hbkjhc?file=routes/index.ts,package.json

**Comment by Niki2k1** [comment]
Same behaviour, 
- running `npm run dev` works fine
- running `npm run build` and `node .output/server/index.mjs` works fine as well
- copying **.output** to a different folder and running `node .output/server/index.mjs` does not work and I get the semver error.

Is it even correct to only copy the .output folder? or do I need the whole project?

**Comment by danielroe** [comment]
Yes, .output should be sufficient. That indicates the problem is not in Nuxt but in the nitro tracing layer. (This might not be a bug; we allow specifying additional files to include, for edge cases.)

**Comment by danielroe** [comment]
see https://github.com/nuxt/nuxt/issues/22325#issuecomment-1690421926.

**Comment by Niki2k1** [comment]
thank you 🙏🏼

**Comment by Niki2k1** [comment]
Anyone else coming here for argon2 specifically. Adding these entries to the **nuxt.config.ts** fixed my error:
```
nitro: {
  externals: {
    traceInclude: ['node_modules/argon2/argon2.js', 'node_modules/nopt/lib/nopt.js']
  }
}
```
