### ISSUE TITLE
webpack-builder broken in nuxt 3.8.0

### ISSUE THREAD

**Issue by spreadpando** [nuxt/nuxt#23843]
### Environment

- Operating System: Darwin
- Node Version:     v18.18.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@10.1.0
- Builder:          webpack
- User Config:      devtools, builder, webpack
- Runtime Modules:  -
- Build Modules:    -

My package.json:
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxt/webpack-builder": "^3.8.0",
    "nuxt": "^3.8.0",
    "vue": "^3.3.4",
    "vue-router": "^4.2.5"
  }
}

### Reproduction

https://github.com/spreadpando/nuxt-test

Steps to reproduce:

- npx nuxi@latest init <project-name>
- cd <project-name>
- add `builder: 'webpack',` to nuxt.config.ts
- `npm run dev`
- answer "Yes" to ✔ Do you want to install @nuxt/webpack-builder package?
- see error

### Describe the bug

It appears there is an internal bug in the webpack-builder 3.8. I encountered when trying to upgrade nuxt from 3.3. 

### Additional context

Running Nuxt and webapck in production at the moment. We have need to implement several custom webpack loaders, hence the decision to user webpack over vite. Recent updates to the docs look to add some nice/necessary features to the webpack integration, we'd hope to be able to configure the esbuild process a bit, but it seems we won't be able to upgrade at present. Perhaps my config is incorrect, but it was at least working on 3.3, if a bit slow. Perhaps time to move to vue/express/webpack for the sake of simplicity.

`// https://nuxt.com/docs/api/configuration/nuxt-config

export default defineNuxtConfig({
  devtools: { enabled: true },
  builder: '@nuxt/webpack-builder',
  webpack: {
    loaders: {
      vue: {
        hotReload: true,
      }
    }
  }
})
`

### Logs

```shell-script
ERROR  Cannot start nuxt:  "fd" must be a positive integer: undefined                     

  at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
  at new NodeError (node:internal/errors:405:5)
  at new WriteStream (node:tty:88:11)
  at klona (node_modules/klona/dist/index.mjs:8:10)
  at klona (node_modules/klona/dist/index.mjs:25:15)
  at klona (node_modules/klona/dist/index.mjs:11:15)
  at klona (node_modules/klona/dist/index.mjs:25:15)
  at klona (node_modules/klona/dist/index.mjs:25:15)
  at klona (node_modules/klona/dist/index.mjs:25:15)
  at klona (node_modules/klona/dist/index.mjs:11:15)
  at klona (node_modules/klona/dist/index.mjs:35:13)
  at klona (node_modules/klona/dist/index.mjs:25:15)
  at getWebpackConfig (node_modules/@nuxt/webpack-builder/dist/index.mjs:386:10)
  at node_modules/@nuxt/webpack-builder/dist/index.mjs:1241:12
  at Array.map (<anonymous>)
  at bundle (node_modules/@nuxt/webpack-builder/dist/index.mjs:1237:72)
  at bundle (node_modules/nuxt/dist/index.mjs:4453:11)
  at async Promise.all (index 1)
  at async build (node_modules/nuxt/dist/index.mjs:4328:5)
  at async Promise.all (index 1)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:282:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:187:7)
  at async NuxtDevServer.init (node_modules/nuxi/dist/chunks/dev2.mjs:182:5)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-child.mjs:103:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1647:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1638:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1770:7)
```

**Comment by warflash** [comment]
Thanks for the report @spreadpando! While not ideal - reverting to 3.7.4 should "fix" that issue in the meantime.

This seems to be caused by #23692 and the fact that klona does not support circular references https://github.com/lukeed/klona/issues/40. 
rfdc doesn't support esm, structuredClone refuses to work so perhaps it's time for unjs/clonique 😅

**Comment by mohammad-zr** [comment]
@warflash 
How could I downgrade to 3.7.4?
I edit package.json and set nuxt version to 3.7.4, delete node_modules and package-lock.json and run npm install, but when I run npm run dev or build again nuxt 3.8.0 get used!

**Comment by spreadpando** [comment]
@mohammad-zr fwiw, you need to downgrade  "@nuxt/webpack-builder", not the nuxt package itself.  I can confirm this works:
```
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxt/webpack-builder": "3.7.4",
    "nuxt": "^3.8.0",
    "vue": "^3.3.6",
    "vue-router": "^4.2.5"
  }
  ```
