### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by vientorepublic** [nuxt/nuxt#23871]
### Environment

```
System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M1
    Memory: 81.34 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 17.1
  npmPackages:
    nuxt: ^2.15.8 => 2.17.1
```

### Reproduction

https://github.com/vientorepublic/nuxt2-build-error

### Describe the bug

When I run `nuxt build` for a production build I get the error `Cannot read properties of undefined (reading 'indexOf')`

### Logs

```shell-script
FATAL  Cannot read properties of undefined (reading 'indexOf')                                                                                                                            

  at node_modules/sass/sass.dart.js:91335:16
  at Object.applyHooksTransformer (node_modules/sass/sass.dart.js:1854:16)
  at Object.initHooks (node_modules/sass/sass.dart.js:1834:253)
  at Object.initNativeDispatchContinue (node_modules/sass/sass.dart.js:1800:11)
  at Object.initNativeDispatch (node_modules/sass/sass.dart.js:1794:11)
  at Object.getNativeInterceptor (node_modules/sass/sass.dart.js:3662:13)
  at Object.getInterceptor$x (node_modules/sass/sass.dart.js:3912:18)
  at Object.set$render$x (node_modules/sass/sass.dart.js:3949:18)
  at main0 (node_modules/sass/sass.dart.js:21069:11)
  at node_modules/sass/sass.dart.js:92718:5


 FATAL  Cannot read properties of undefined (reading 'indexOf')                                                                                                                            

  at node_modules/sass/sass.dart.js:91335:16
  at Object.applyHooksTransformer (node_modules/sass/sass.dart.js:1854:16)
  at Object.initHooks (node_modules/sass/sass.dart.js:1834:253)
  at Object.initNativeDispatchContinue (node_modules/sass/sass.dart.js:1800:11)
  at Object.initNativeDispatch (node_modules/sass/sass.dart.js:1794:11)
  at Object.getNativeInterceptor (node_modules/sass/sass.dart.js:3662:13)
  at Object.getInterceptor$x (node_modules/sass/sass.dart.js:3912:18)
  at Object.set$render$x (node_modules/sass/sass.dart.js:3949:18)
  at main0 (node_modules/sass/sass.dart.js:21069:11)
  at node_modules/sass/sass.dart.js:92718:5


   ╭────────────────────────────────────────────────────────────────────────╮
   │                                                                        │
   │   ✖ Nuxt Fatal Error                                                   │
   │                                                                        │
   │   TypeError: Cannot read properties of undefined (reading 'indexOf')   │
   │                                                                        │
   ╰────────────────────────────────────────────────────────────────────────╯
```
```

**Comment by vientorepublic** [comment]
I confirmed that this problem occurs in nodejs 21 version. After downgrading to version 20, the problem was resolved.

**Comment by danielroe** [comment]
In that case this sounds like a Node bug with sass. It should probably be opened there rather than in Nuxt's repository.
