### ISSUE TITLE
Cannot find module 'pinia/dist/pinia.mjs'

### ISSUE THREAD

**Issue by brianmhlanga** [nuxt/nuxt#23955]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.0
- Package Manager:  npm@9.5.0
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  @pinia/nuxt@0.5.1
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-7rzxek

### Describe the bug

 ERROR  Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs'                                                                 10:51:50 AM  
Require stack:
- C:\Users\user\Documents\GitHub\property-listing-demo\index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
  at Function.resolve (node:internal/modules/cjs/helpers:116:19)
  at Function._resolve [as resolve] (node_modules\jiti\dist\jiti.js:1:250334)
  at resolveModule (/C:/Users/user/Documents/GitHub/property-listing-demo/node_modules/@nuxt/kit/dist/index.mjs:2239:29)
  at setup (/C:/Users/user/Documents/GitHub/property-listing-demo/node_modules/@pinia/nuxt/dist/module.mjs:26:5)
  at normalizedModule (/C:/Users/user/Documents/GitHub/property-listing-demo/node_modules/@nuxt/kit/dist/index.mjs:2141:37)
  at async installModule (/C:/Users/user/Documents/GitHub/property-listing-demo/node_modules/@nuxt/kit/dist/index.mjs:2439:95)
  at async initNuxt (/C:/Users/user/Documents/GitHub/property-listing-demo/node_modules/nuxt/dist/index.mjs:3655:7)
  at async NuxtDevServer._load (/C:/Users/user/Documents/GitHub/property-listing-demo/node_modules/nuxi/dist/chunks/dev2.mjs:255:5)
  at async NuxtDevServer.load (/C:/Users/user/Documents/GitHub/property-listing-demo/node_modules/nuxi/dist/chunks/dev2.mjs:187:7)

**Comment by madebyfabian** [comment]
Hi there!
As stated in the pinia docs: https://pinia.vuejs.org/ssr/nuxt.html
You have to install both `pinia` and `@pinia/nuxt` as dependencies to make it work.

**Comment by jorgequiteja** [comment]
I got the same error on linux and installing pinia didn't solve it.
