### ISSUE TITLE
Getting error caught during app initialization FetchError after updating to Nuxt 3.8.0 (from 3.7.0)

### ISSUE THREAD

**Issue by skav3n** [nuxt/nuxt#23979]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.12.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.1
- Package Manager:  yarn@1.21.1
- Builder:          -
- User Config:      modules, routeRules, runtimeConfig, vueQuery, i18n, css, devServer, components, nitro
- Runtime Modules:  @hebilicious/vue-query-nuxt@0.2.1, @leanera/nuxt-i18n@0.5.0
- Build Modules:    -

### Reproduction

I cannot provide a reproduction link.
Error message:
[nuxt] error caught during app initialization FetchError: [GET] "/bk-api/_nuxt/builds/meta/test.json": 404 Not Found at async $fetch22 (ofetch.js?v=7f011f6e:529:16)

### Describe the bug

I got an issue after upgrading to Nuxt 3.8.0 from 3.7.0.

I am using nitro devProxy:
`nitro: {
    devProxy: {
      '/bk-api': {
        target: 'http://10.1.0.1:8300/bk-api',
        changeOrigin: true,
        prependPath: true,
      }
    },
  },`

![error](https://github.com/nuxt/nuxt/assets/11429197/ef1e084e-2123-4cfb-86cf-495823fda4da)
![error3](https://github.com/nu
![error4](https://github.com/nuxt/nuxt/assets/11429197/662610f3-7430-4c14-b595-dce309957922)
xt/nuxt/assets/11429197/f7c5976d-2f05-4335-ad1d-43503f357917)

**Comment by alapeta** [comment]
The same error for me. Reverting to 3.7.4 fix this.

**Comment by sawa-ko** [comment]
Same error here....
Nuxt 3.8.0

**Comment by danielroe** [comment]
This should be resolved in the [edge channel](https://nuxt.com/docs/guide/going-further/edge-channel/), or in the next release.

Let me know if not and I'll reopen.

**Comment by justserega** [comment]
Got same error when update from "3.7.4" to "3.8.1". Seems that it is related with my changing apiBase for $fetch

```
import { ofetch } from 'ofetch'

export default defineNuxtPlugin(() => {
  const runtimeConfig = useRuntimeConfig()
  const app = useNuxtApp()

  globalThis.$fetch = ofetch.create({
    baseURL: <string>runtimeConfig.public.apiBase,
  })
})
```
When I comment this line all works fine, except my API is not available. Do you have any suggestion how to fix it?

**Comment by danielroe** [comment]
You definitely should not overwrite `$fetch` with a different baseURL. This is used by Nuxt itself and will break all kinds of things. Instead, you can create your own fetch helper named something different.

**Comment by justserega** [comment]
What is the recommended approach to call the API in nuxt3? There are a lot of discussion in issues how to proxy requests to backend and there is nothing in the documentation... I tried several ways and this was the only one that worked with SSR and dev/prod environments. It "will break all kinds of things” only in 3.8 and was working fine from 3.0 to 3.7 Maybe it is a lack of documentation if there are so many misunderstaing and discussion arount it.

**Comment by justserega** [comment]
https://github.com/nuxt/nuxt/discussions/15930 - solution for my issue

**Comment by akiot-b** [comment]
After updating from v3.8.0 to v3.8.2, the fetch to the backend fails.
The nuxt.conf.ts is here and this is how I was proxying.
```
  vite: {
    server: {
      proxy: {
        '/api': {
          target: process.env.API_URL,
          changeOrigin: true,
        },
      },
      watch: {
        // Settings for WSL
        // https://ja.vitejs.dev/config/server-options.html
        usePolling: true,
      },
    },
    build: {
    },
  },
  ```

error
```
FetchError: [POST] "http://127.0.0.1:3001/api/auth/signin": <no response> Failed to fetch
    at async $fetch22 (ofetch.00501375.mjs:261:15)
    at async signIn (useAuth.mjs:12:20)
    at async signin (signin.vue:110:5)
```

**Comment by zee-shan000** [comment]
@danielroe 
Got this same error in nuxt 3.9.1.

**Comment by anjarupnik** [comment]
And also in 3.9.3

**Comment by jayxuz** [comment]
Got this same error in nuxt 3.9.1.
when use an older chrome version(55, added polyfill) visited the build .output, the fetch request for the _nuxt/build/meta/xxx.json return 400 error
in devtool, the fetch request method was 'undefined'

Reverting to 3.7.4 fix this error

**Comment by dbethel-nib** [comment]
Still having this issue in 3.10.1

Any help?

**Comment by ricricucit** [comment]
I've had a similar issue, coming from a different path. (including nuxt as iframe).

Reading the [`3.8.0` Release notes](https://nuxt.com/blog/v3-8#app-manifest) helped and disabling the `experimental.appManifest` feature did it for me:

```js
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  experimental: {
    appManifest: false,
  },
  ...
})
```

Hope this helps someone. 🙂

**Comment by jim55167** [comment]
@danielroe 
Got this same error in nuxt 3.10.3.
Error 404 /_nuxt/builds/xxxxxxxx.json
![2024-03-06 Error](https://github.com/nuxt/nuxt/assets/67188543/46b0b488-24b9-4781-8ce3-2641377609ad)

**Comment by RomanSkrypnik** [comment]
> @danielroe Got this same error in nuxt 3.10.3. Error 404 /_nuxt/builds/meta/xxxxxxxx.json ![](https://private-user-images.githubusercontent.com/67188543/310457275-46b0b488-24b9-4781-8ce3-2641377609ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NDI4MjQsIm5iZiI6MTcxMTY0MjUyNCwicGF0aCI6Ii82NzE4ODU0My8zMTA0NTcyNzUtNDZiMGI0ODgtMjRiOS00NzgxLThjZTMtMjY0MTM3NzYwOWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDE2MTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2YTQzODJjMTBhMDc2MWVkNzU1MTgwZjNkNGQ3NjVjZDU3MTcwZmUzNjFmNGM2NmM0Y2FiOGY4MDhlN2VjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qngg_9DkuIZopyIlLj--W4vzNCptmmMMdIbk6BdQkgs)

+1

**Comment by danielroe** [comment]
If you're encountering an issue, please raise a new issue with a reproduction 🙏

**Comment by alessioacella** [comment]
+1 @jim55167 did you find a temporary solution to that error? Got the same error here!

**Comment by nasimuddin01** [comment]
> I've had a similar issue, coming from a different path. (including nuxt as iframe).
> 
> Reading the [`3.8.0` Release notes](https://nuxt.com/blog/v3-8#app-manifest) helped and disabling the `experimental.appManifest` feature did it for me:
> 
> ```js
> // https://nuxt.com/docs/api/configuration/nuxt-config
> export default defineNuxtConfig({
>   experimental: {
>     appManifest: false,
>   },
>   ...
> })
> ```
> 
> Hope this helps someone. 🙂

This helped me.

**Comment by COOSONWEI** [comment]
> I've had a similar issue, coming from a different path. (including nuxt as iframe).
> 
> Reading the [`3.8.0` Release notes](https://nuxt.com/blog/v3-8#app-manifest) helped and disabling the `experimental.appManifest` feature did it for me:
> 
> // https://nuxt.com/docs/api/configuration/nuxt-config
> export default defineNuxtConfig({
>   experimental: {
>     appManifest: false,
>   },
>   ...
> })
> Hope this helps someone. 🙂
Thank you！！！
My project can run properly in other browsers, but there was the same problem when I tried to view it in the built-in browsers of WeChat and QQ.
Now, through this method, my website can also be accessed in the built-in browsers of WeChat and QQ!
Up to now, no other new problems have arisen through this method.

**Comment by COOSONWEI** [comment]
> I've had a similar issue, coming from a different path. (including nuxt as iframe).
> 
> Reading the [`3.8.0` Release notes](https://nuxt.com/blog/v3-8#app-manifest) helped and disabling the `experimental.appManifest` feature did it for me:
> 
> // https://nuxt.com/docs/api/configuration/nuxt-config
> export default defineNuxtConfig({
>   experimental: {
>     appManifest: false,
>   },
>   ...
> })
> Hope this helps someone. 🙂

Thank you ！！！
My project can run properly in other browsers, but there was the same problem when I tried to view it in the built-in browsers of WeChat and QQ.
Now, through this method, my website can also be accessed in the built-in browsers of WeChat and QQ!
Up to now, no other new problems have arisen through this method.
