### ISSUE TITLE
nuxt:imports-transform - can't read properties of undefined

### ISSUE THREAD

**Issue by torerik123** [nuxt/nuxt#23988]
### Environment

- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.1
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      telemetry, runtimeConfig, css, build, ssr, vue, components, vite, devServer, meta, modules, imports, i18n, lodash
- Runtime Modules:  (), @nuxtjs/google-fonts@3.0.2, nuxt-icons@3.2.1, @nuxtjs/i18n@8.0.0-rc.5, nuxt-lodash@2.5.3, @pinia/nuxt@0.5.1
- Build Modules:    -

### Reproduction

Not able to recreate issue

### Describe the bug

Recently upgraded to nuxt v.3.8.0.

Running `npm run dev´ gives this error:

```
 ERROR  Internal server error: Cannot read properties of undefined (reading 'includes')
  Plugin: nuxt:imports-transform
  File: /Users/tor/projects/nuxtapp/mixins/module-pinia.js
      at file:///Users/tor/projects/nuxtapp/node_modules/unimport/dist/shared/unimport.0a3f1751.mjs:952:62
      at Array.forEach (<anonymous>)
      at Object.injectImportsWithContext [as injectImports] (file:///Users/tor/projects/nuxtapp/node_modules/unimport/dist/shared/unimport.0a3f1751.mjs:949:22)
      at async TransformContext.transform (file:///Users/tor/projects/nuxtapp/node_modules/nuxt/dist/index.mjs:2014:21)
      at async file:///Users/tor/projects/nuxtapp/node_modules/vite-plugin-inspect/dist/index.mjs:922:19
      at async Object.transform (file:///Users/tor/projects/nuxtapp/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44352:30)
      at async loadAndTransform (file:///Users/tor/projects/nuxtapp/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55026:29)
      at async viteTransformMiddleware (file:///Users/tor/projects/nuxtapp/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:64430:32)
```

### Additional context

If I downgrade to nuxt 3.7.0 it's working.
Not sure if this is a nuxt issue or not. I haven't been able to recreate the problem. 
If I start a new project using nuxt 3.8.0 it works as normal. But in this one I get the error.

Tried removing package-lock.json, delete node_modules with npm cache clear --force and npm install. Still same error.

**Comment by torerik123** [comment]
After some extensive digging I've narrowed down the error to the "toString()"-method from 'nuxt-lodash'. 
Other lodash methods seem to work.

In my store I'm using a mixin:

`import { myMixin } from '~/mixins/myMixin';

export const useCounterStore = defineStore('counter', {
  state: () => ({ count: 0, name: 'Eduardo' }),

  getters: {
    doubleCount: (state) => state.count * 2,
  },

  actions: {
    increment() {
      this.count++;
    },
  },
});`

Mixin causing the issue:
`
let myMixin = {
  state: {
    hello: 'hello from mixin',
  },

  actions: {
    mixinAction() {
      let error = 123459;
      return _toString(error); // < --------- _toString() causing error
    },
  },
};

export { myMixin };

`
