### ISSUE TITLE
After page jump error upgrade to v3.8

### ISSUE THREAD

**Issue by layen520** [nuxt/nuxt#24078]
### Environment

<img width="1028" alt="image" src="https://github.com/nuxt/nuxt/assets/19701056/081d0e54-900a-4318-b967-1929350d86fd">

### Reproduction

none

### Describe the bug

When i upgrade nuxt version from 3.7 to 3.8 , refresh the page is OK but when jump to article content page from home page , got this error:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (chunk-FFKG5BFD.js:9197:30)
    at ReactiveEffect.componentUpdateFn [as fn] (chunk-FFKG5BFD.js:7206:11)
    at ReactiveEffect.run (chunk-FFKG5BFD.js:422:19)
    at instance.update (chunk-FFKG5BFD.js:7243:52)
    at callWithErrorHandling (chunk-FFKG5BFD.js:1552:32)
    at flushJobs (chunk-FFKG5BFD.js:1755:9)
    at flushJobs (chunk-FFKG5BFD.js:1765:7)

<img width="265" alt="image" src="https://github.com/nuxt/nuxt/assets/19701056/6ab27a81-160e-4e1e-9d52-dd59b6830114">

**Comment by danielroe** [comment]
This is probably the same issue as https://github.com/nuxt/nuxt/issues/13309.

**Comment by layen520** [comment]
After updating to v3.8.1, the problem is gone.
