### ISSUE TITLE
Node 20.9.0 and virtual modules

### ISSUE THREAD

**Issue by userquin** [nuxt/nuxt#24103]
### Environment

```shell
Nuxt project info:                                                                                                                                     14:36:07

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.10.1
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  vuetify-nuxt-module@0.6.0
- Build Modules:    -
------------------------------
```

### Reproduction

https://github.com/kingyue737/nuxt-vuetify-error

Check Node warning here: https://github.com/userquin/vuetify-nuxt-module/issues/135

```shell
[14:05:41]  ERROR  (node:8488) [DEP0170] DeprecationWarning: The URL virtual:nuxt:D:/work/issues-repos/nuxt-vuetify-error-issue-135/.nuxt/paths.mjs is invalid. F
uture versions of Node.js will throw an error.
(Use node --trace-deprecation ... to show where the warning was created)
```

When building there is a warning in some transform hook:
```shell
Nuxt 3.8.0 with Nitro 2.7.2                                                                                                                            14:31:10
ℹ Building client...                                                                                                                                  14:31:11
ℹ vite v4.5.0 building for production...                                                                                                              14:31:11
transforming (1) node_modules\.pnpm\nuxt@3.8.0_vite@4.5.0\node_modules\nuxt\dist\app\entry.js(node:19728) [DEP0170] DeprecationWarning: The URL virtual:nuxt:D:/w
ork/issues-repos/nuxt-vuetify-error-issue-135/.nuxt/paths.mjs is invalid. Future versions of Node.js will throw an error.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### Describe the bug

It seems Nuxt is using `pathToFileURL` for virtual modules (https://github.com/nuxt/nuxt/blob/91ee969b1b14d0cad40e4163749dcf8dba2953bd/packages/nuxt/src/core/utils/plugins.ts#L39), with Node 18.16.0 the warning is not there (I guess the problem is using `pathToFileURL` since there are only 3 `new URL` usages):

![imagen](https://github.com/nuxt/nuxt/assets/6311119/4bbf813f-4170-4c7d-9e5e-d7cde63011b5)

![imagen](https://github.com/nuxt/nuxt/assets/6311119/6f5471ad-16cc-48ee-9bc5-ce70226a2596)

**Comment by userquin** [comment]
It seems the problem comes from the Vuetify Vite Plugin: https://github.com/vuetifyjs/vuetify-loader/blob/master/packages/vite-plugin/src/importPlugin.ts#L24

Node 20.9.0 seems to omit the details when running `node --trace-warnings --trace-deprecation node_modules/nuxi/bin/nuxi.mjs dev playground`  I've modified `node_modules/nuxi/bin/nuxi.mjs`:
```ts
process.on('warning', (warning) => {
  console.log(warning.stack);
});

runMain()
```

```shell
[13:49:41]  ERROR  (node:23648) [DEP0170] DeprecationWarning: The URL virtual:nuxt:D:/work/issues-repos/nuxt-fix-parse-id/playground/.nuxt/paths.mjs is invalid. 
Future versions of Node.js will throw an error.
(Use node --trace-deprecation ... to show where the warning was created)

[13:49:41] DeprecationWarning: The URL virtual:nuxt:D:/work/issues-repos/nuxt-fix-parse-id/playground/.nuxt/paths.mjs is invalid. Future versions of Node.js will
 throw an error.
    at getHostname (node:url:516:17)
    at Url.parse (node:url:384:14)
    at urlParse (node:url:141:13)
    at parseId (D:\work\issues-repos\nuxt-fix-parse-id\node_modules\.pnpm\vite-plugin-vuetify@1.0.2_vite@4.5.0_vue@3.3.7_vuetify@3.3.23\node_modules\vite-plugin-vuetify\src\importPlugin.ts:7:39)
    at TransformContext.transform (D:\work\issues-repos\nuxt-fix-parse-id\node_modules\.pnpm\vite-plugin-vuetify@1.0.2_vite@4.5.0_vue@3.3.7_vuetify@3.3.23\node_modules\vite-plugin-vuetify\src\importPlugin.ts:24:31)
    at D:\work\issues-repos\nuxt-fix-parse-id\node_modules\.pnpm\vite-plugin-inspect@0.7.40_@nuxt+kit@packages+kit_rollup@3.29.4_vite@4.5.0\node_modules\vite-plugin-inspect\dist\index.cjs:933:28
    at plugin2.<computed> (D:\work\issues-repos\nuxt-fix-parse-id\node_modules\.pnpm\vite-plugin-inspect@0.7.40_@nuxt+kit@packages+kit_rollup@3.29.4_vite@4.5.0\node_modules\vite-plugin-inspect\dist\index.cjs:920:16)
    at Object.transform (file:///D:/work/issues-repos/nuxt-fix-parse-id/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.9/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44352:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadAndTransform (file:///D:/work/issues-repos/nuxt-fix-parse-id/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.9/node_modules/vite/dist/node/chunks
/dep-bb8a8339.js:55026:29)
```

**Comment by userquin** [comment]
Since Nuxt is not using `import { parse } from 'node:url'` (using `ufo`) I guess this can be closed and maybe the PR.

@danielroe sorry for the noise and the wasted time (I spent almost all day yesterday debugging it) :cry:

**Comment by userquin** [comment]
https://github.com/nodejs/node/issues/50550

**Comment by Justin3go** [comment]
When I upgraded from Node 18 to 20, I encountered the same issue. Is there a way to fix it now?

**Comment by STP5940** [comment]
Update vite-plugin-vuetify v2.0.1 to vite-plugin-vuetify v2.0.2

**Comment by PKief** [comment]
> Update vite-plugin-vuetify v2.0.1 to vite-plugin-vuetify v2.0.2

That actually solved the issue 👍
