### ISSUE TITLE
Error trace only visible during build not in dev mode

### ISSUE THREAD

**Issue by oripka** [nuxt/nuxt#24109]
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v20.8.0`
- Nuxt Version:     `3.8.0`
- CLI Version:      `3.9.1`
- Nitro Version:    `2.7.0`
- Package Manager:  `pnpm@8.7.6`
- Builder:          `-`
- User Config:      `extends`, `devtools`, `routeRules`, `telemetry`, `supabase`, `app`, `content`, `nitro`, `modules`, `colorMode`, `ui`, `fontMetrics`, `googleFonts`, `runtimeConfig`, `hooks`
- Runtime Modules:  `@nuxtjs/supabase@1.1.3`, `@nuxt/content@2.8.5`, `@nuxt/ui@2.9.0`, `@nuxthq/studio@0.14.1`, `@vueuse/nuxt@10.5.0`, `@nuxtjs/fontaine@0.4.1`, `@nuxtjs/google-fonts@3.0.2`, `nuxt-og-image@2.1.3`, `nuxt-icon@0.5.0`, `@morev/vue-transitions/nuxt@2.3.6`
- Build Modules:    `-`
```

### Reproduction

I have a SFC that has this mistake (tags don't match)

```
<MyButton @click.prevent.stop="refreshNames()" type="submit">Refresh</button>
```

In dev mode I get this error which is not helpful (Invalid end tag). It does not give information where the error occurs:

```
npx nuxi dev
Nuxt 3.8.0 with Nitro 2.7.0
[...]

ERROR  Invalid end tag. 
```

Doing a build gives a stack trace and indicates the involved file. Am I missing some kind of configuration. I noted often that errors are easier to debug using a build. It would be more dev-friendly to have a trace during development-time as well.

```
npx nuxi build
[...]

ERROR  [vite:vue] Invalid end tag.
file: /Users/dddd/code/yyyy/components/auth/AuthClaimUser.vue:6:80

  at createCompilerError (node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:17:17)
  at emitError (node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:1446:5)
  at parseChildren (node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:828:13)
  at parseElement (node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:999:20)
  at parseChildren (node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:840:18)
  at parseElement (node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:999:20)
  at parseChildren (node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:840:18)
  at parseElement (node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:999:20)
  at parseChildren (node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:840:18)
  at parseElement (node_modules/.pnpm/@vue+compiler-core@3.3.4/node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js:999:20)
```

### Describe the bug

The dev mode does not show an error trace.

**Comment by OrbisK** [comment]
@danielroe it looks like we provide the correct hint

<img width="756" height="783" alt="Image" src="https://github.com/user-attachments/assets/826bbaaf-16a0-46b6-baea-577b6ef78ff2" />

But not as a stack trace, but as a cause 🤔

<img width="759" height="774" alt="Image" src="https://github.com/user-attachments/assets/b897cc55-6bfd-4ee2-93ed-c6a0aba136e7" />

This is a SSR only issue. Client side shows the correct vue error:

<img width="672" height="608" alt="Image" src="https://github.com/user-attachments/assets/277b87d7-2745-4108-ab47-be7b053bb911" />
