### ISSUE TITLE
vite-builder can't warmup axios deps without error

### ISSUE THREAD

**Issue by MiniDigger** [nuxt/nuxt#24213]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-5yuywh?file=app.vue

### Describe the bug

when you import axios and have the debug env set (to enable your debug logger), you get stampped with warmup errors on startup

### Additional context

I am not sure if this is a proper issue, but since these logs surface if you have the debug env set, its pretty annoying since its shown for like 15 modules.

### Logs

```shell-script
⚙ [nuxt] warmup for node:http failed with: Failed to load url node:http (resolved id: node:http). Does the file exist?                                                                                       14:00:42

  at loadAndTransform (node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55067:21)
  at async warmup (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:861:7)
  at async warmup (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:871:7)
  at async warmup (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:871:7)
  at async warmup (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:871:7)
  at async warmupViteServer (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:876:3)
⚙ [nuxt] warmup for node:https failed with: Failed to load url node:https (resolved id: node:https). Does the file exist?                                                                                    14:00:42

  at loadAndTransform (node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55067:21)
  at async warmup (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:861:7)
  at async warmup (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:871:7)
  at async warmup (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:871:7)
  at async warmup (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:871:7)
  at async warmupViteServer (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:876:3)
```

**Comment by danielroe** [comment]
This was fixed in Nuxt v3.8.2 but the reproduction is on Nuxt v3.8.1.

**Comment by MiniDigger** [comment]
fwiw, I can confirm that both my minimal repro and my actual project don't experience this anymore on 2.8.2, so ill just close this I guess? if @chrisspiegl can provide a repro, that would be a different issue anyways

**Comment by chrisspiegl** [comment]
I rolled back on my own repo and went step by step through updating packages and cleaning/nuking my whole `pnpm store cache` and `node_modules` folder. After that, I was able to slowly upgrade my dependencies and this error did not come back.

Closing this is good.
