### ISSUE TITLE
ERROR  Exiting due to prerender errors. 

### ISSUE THREAD

**Issue by axolo** [nuxt/nuxt#24228]
### Environment

```
Nuxt project info:                                                                                            09:37:53

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.9.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm
- Builder:          -
- User Config:      devtools, modules, runtimeConfig, nitro, app
- Runtime Modules:  @nuxt/ui@2.10.0, nuxt-swiper@1.2.2, dayjs-nuxt@2.1.9
- Build Modules:    -
------------------------------
```

### Reproduction

- run `nuxt build --prerender` 
- only some Error: 404
- throw  prerender error
- run `nuxt preview`
- static files in `_nuxt` not found (http 404)
- dir `_nuxt` is not in `.output/public`

### Describe the bug

throw prerender errors when nuxt generate with crawlLinks

### Additional context

```
> nuxt build --prerender

Nuxt 3.8.1 with Nitro 2.7.2                                                                                   09:15:30
i Using default Tailwind CSS file                                                            nuxt:tailwindcss 09:15:31

i Building client...                                                                                          09:15:33
i vite v4.5.0 building for production...                                                                      09:15:33
i ✓ 392 modules transformed.                                                                                  09:15:42
Inspect report generated at my-project/.nuxt/analyze/.vite-inspect
i .nuxt/dist/client/manifest.json                        11.36 kB │ gzip:  1.33 kB                            09:15:43
i ✓ built in 9.53s                                                                                            09:15:43
√ Client built in 9546ms                                                                                      09:15:43

i Building server...                                                                                          09:15:43
i vite v4.5.0 building SSR bundle for production...                                                           09:15:43
i ✓ 221 modules transformed.                                                                                  09:15:51
Inspect report generated at my-project/.nuxt/analyze/.vite-inspect
i .nuxt/dist/server/_nuxt/_id_-styles.2c4f1d78.mjs              0.14 kB                                       09:15:52
i ✓ built in 9.17s                                                                                            09:15:52
√ Server built in 9191ms                                                                                      09:15:52

i Initializing prerenderer                                                                              nitro 09:15:52
i Prerendering 3 initial routes with crawler                                                            nitro 09:15:55
  ├─ /404.html (127ms)                                                                                  nitro 09:15:55
  ├─ /200.html (123ms)                                                                                  nitro 09:15:55
  ├─ /article/1714465249880489986 (1556ms)                                                              nitro 09:15:58
  ├─ /en/ (159ms)                                                                                       nitro 09:15:59
  │ ├── Error: [404] Page not found: /en/
  │ └── Linked from /
  │ └── Linked from /article/7204
                                                                                                        nitro 09:23:04

 ERROR  Exiting due to prerender errors.                                                                      09:23:04

  at prerender (/my-project/node_modules/nitropack/dist/shared/nitro.3d0a4b01.mjs:214:11)
  at async /my-project/node_modules/nuxt/dist/index.mjs:2986:7
  at async build (/my-project/node_modules/nuxt/dist/index.mjs:4375:5)
  at async Object.run (/my-project/node_modules/nuxi/dist/chunks/build.mjs:92:5)
  at async Object.run (/my-project/node_modules/nuxi/dist/chunks/generate.mjs:61:5)
  at async runCommand$1 (/my-project/node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1647:7)
  at async runCommand$1 (/my-project/node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1638:11)
  at async runMain$1 (/my-project/node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1770:7)

 ERROR  Exiting due to prerender errors.                                                                      09:23:04
```

**Comment by axolo** [comment]
- same errors throw when build on nuxt@3.8.0
- but `_nuxt` output success
- static files in _nuxt can access

**Comment by MinSomai** [comment]
I have similar error when using routeRules. 
I do have manifest.json in public folder.

<img width="503" alt="Screenshot 2023-11-14 at 12 46 11 AM" src="https://github.com/nuxt/nuxt/assets/21338691/972d793c-ea3c-4874-90a6-35d2b0d8ee9c">

**Comment by tomleiter** [comment]
@axolo  Did you find a solution? having the same problem. Same Nuxt Version. etc.

**Comment by axolo** [comment]
> @axolo Did you find a solution? having the same problem. Same Nuxt Version. etc. Thx

locked version nuxt@3.8.0 before fixed.

**Comment by damianof** [comment]
Same here, Nuxt version 3.8.2 with vue 3.3.10 and vue-router 4.2.5

Two simple projects, one of them generates, the other one does not and give this error. I cannot figure out yet why one of them generates successfully though.

**Comment by vgorloff** [comment]
Ended up disabling early exit of pre-render failure in `nuxt.config.js`.

```js
  nitro: {
    prerender: {
      // Workaround for "Error: [404] Page not found: /manifest.json"
      failOnError: false,
    },
  },
```

**Comment by eddiecorrigall** [comment]
To be more selective about the page to disable prerender.

```javascript
  routeRules: {
    // Disable homepage pre-rendered at build time
    '/': { prerender: false },
  }
```

**Comment by XiaoRongwen** [comment]
楼主找到解决方法了吗

**Comment by FatNerdPeng** [comment]
@danielroe Hello, why was this bug `not planned`,is it because it has already been fixed?
I have created a reproduction with `nuxt 3.16.1`:https://stackblitz.com/edit/nuxt-starter-teivqic9
It runs well in the development environment, but reports an error in `nuxt generate`.I don't think this issue is related to GSAP because it runs well in the development environment. Perhaps it has something to do with the build process?
This bug I believe has had a serious impact on because it prevents the project from being deployed to the production environment.I don't know how to solve it,It even took me 2 days to find the problem because it had very few error logs.

**Comment by danielroe** [comment]
@FatNerdPeng that's not related to this issue.

it's not a bug - you should only initialise gsap in `onMounted` as it requires access to the browser window.

**Comment by FatNerdPeng** [comment]
> [@FatNerdPeng](https://github.com/FatNerdPeng) that's not related to this issue.
> 
> it's not a bug - you should only initialise gsap in `onMounted` as it requires access to the browser window.
Oh,I see,thx

**Comment by FatNerdPeng** [comment]
> [@FatNerdPeng](https://github.com/FatNerdPeng) that's not related to this issue.
> 
> it's not a bug - you should only initialise gsap in `onMounted` as it requires access to the browser window.

Oh,I see,thx
