### ISSUE TITLE
defineAppConfig is not defined

### ISSUE THREAD

**Issue by adnseek** [nuxt/nuxt#24346]
### Environment

latest nuxt

### Reproduction

I added a app.config.ts 

export default defineAppConfig({
  NUXT_PUBLIC_API_BASE_URL: 'https://superapi,
  NUXT_PUBLIC_DOMAIN: 'https://www.myshop.com',
  NUXT_PUBLIC_API_SHOP_ID: '14',
  NUXT_PUBLIC_FAVICON: '"public/favicon.png"',
})

to the root of my project folder and tried a build. then it fails with

$ nuxt build
Nuxt 3.8.1 with Nitro 2.7.2                                                                                                         9:00:55 PM

 ERROR  defineAppConfig is not defined                                                                                              9:00:56 PM

  at app.config.ts:1:178
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at nuxt.config.ts:2:35
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at Object.jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at resolveConfig (node_modules/c12/dist/index.mjs:288:24)
  at loadConfig (node_modules/c12/dist/index.mjs:116:40)
  at async loadNuxtConfig (node_modules/@nuxt/kit/dist/index.mjs:2530:18)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:3739:19)
  at async Module.loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2584:19)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:67:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1647:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1638:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1770:7)

### Describe the bug

its not building as it should

### Additional context

everything above

### Logs

```shell-script
everything above
```

**Comment by adnseek** [comment]
https://drive.google.com/file/d/19krbgbw6D1eaXUjLOx7-FOyAer8hRtjH/view

**Comment by manniL** [comment]
A few things:

1. Thanks for the video! This is a good start
2. Reproductions on StackBlitz are free as long as they are public 😋 You just need to log in with your GH account 👍 
3. This looks like you want to set the `runtimeConfig` this way (as the keys look like env variables). Why do you choose an app.config.ts here
4. The error stack hints that it might be related to you nuxt config. Do you import the app config there?

**Comment by adnseek** [comment]
i choose the app config because nuxt does not read the env in prod and i have a lot of variables. so i need to pipe it through pm2 ecoset. and i don't like that. so i was looking for another way

**Comment by adnseek** [comment]
![image](https://github.com/nuxt/nuxt/assets/120753123/5e4ceaac-8c49-4740-bb15-481658dfda7d)

**Comment by manniL** [comment]
That's not how what the app config is thought for at all 🙈
 
Instead, either source your `.env` file in production or pass the variables manually.

You could even create a separate JS/TS file and *import* it in your app.config.ts *and* nuxt.config.ts if you want to.

**Comment by adnseek** [comment]
i managed it with nuxt dotenv
thanks manniL
