### ISSUE TITLE
SSR: Refresh the dynamic route page and navigate to the 404 page

### ISSUE THREAD

**Issue by HuuNghia2807** [nuxt/nuxt#24350]
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v18.17.0`
- Nuxt Version:     `3.2.2`
- Nitro Version:    `2.2.2`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

I refreshed the page and got the error.

 ReferenceError: location is not defined
    at setup (E:\---i\pages\aaa\\[slug].vue:40:18)
    at _sfc_main.setup (E:\----\pages\aaa\\[slug].vue:21647:23)
    at callWithErrorHandling (E:\----\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:171:22)
    at setupStatefulComponent (E:\----\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7194:29)
    at setupComponent (E:\----\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7149:11)
    at renderComponentVNode (E:\----\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:628:17)
    at renderVNode (E:\----\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:755:22)
    at renderComponentSubTree (E:\----\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:719:13)
    at renderComponentVNode (E:\----\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:644:16)
    at renderVNode (E:\----\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:755:22) setup function

### Describe the bug

I have a route: ~/page/aaa/[slug].vue
When I'm on the home page, I redirect to the aaa/slug-1 page with a click action on the client, and it still works, but when I redirect by entering the url or refreshing the aaa/slug-1 page, it redirects to a 404 page.

**Comment by navasfazil1004** [comment]
@HuuNghia2807 , is that solved? How?
