### ISSUE TITLE
Nuxt 3.8 on node 18 fetch on server fails

### ISSUE THREAD

**Issue by alireza2281** [nuxt/nuxt#24368]
### Environment

 Operating System: Linux
- Node Version:     v18.18.2
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.9.0
- Builder:          -
- User Config:      app, css, modern, ssr, components, build, modules, legacy, devtools, runtimeConfig, router, experimental
- Runtime Modules:  @nuxtjs/tailwindcss@6.9.5, @nuxt/image-edge@1.0.0-28336957.57c0f74, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.2.0, @sidebase/nuxt-auth@0.6.1, vue-recaptcha/nuxt, @nuxt/image@1.0.0, nuxt-vite-legacy@1.1.0
- Build Modules:    -

### Reproduction

 <no response> [node-fetch-native] Failed to fetch: `globalThis.fetch` is not available!
85|roklaFrontEnd  |     at onError (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2702:16)
85|roklaFrontEnd  |     ... 6 lines matching cause stack trace ...
85|roklaFrontEnd  |     at Object.asyncData.refresh.asyncData.execute (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/asyncData-3cf5b485.js:49:21)
85|roklaFrontEnd  |     at initialFetch (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/asyncData-3cf5b485.js:92:40)
85|roklaFrontEnd  |     at useAsyncData (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/asyncData-3cf5b485.js:95:21) {
85|roklaFrontEnd  |   cause: Error: [node-fetch-native] Failed to fetch: `globalThis.fetch` is not available!
85|roklaFrontEnd  |       at l (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2546:89)
85|roklaFrontEnd  |       at $fetchRaw2 (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2763:32)
85|roklaFrontEnd  |       at onError (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2702:16)
85|roklaFrontEnd  |       at $fetchRaw2 (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2772:20)
85|roklaFrontEnd  |       at $fetch2 (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2805:21)
85|roklaFrontEnd  |       at $api (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/_api-ef8d63db.js:22:10)
85|roklaFrontEnd  |       at useAsyncData.watch (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/_slug_-d5f38521.js:41:13)
85|roklaFrontEnd  |       at Promise.then.result (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/asyncData-3cf5b485.js:52:19)
85|roklaFrontEnd  |       at new Promise (<anonymous>)
85|roklaFrontEnd  |       at Object.asyncData.refresh.asyncData.execute (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/asyncData-3cf5b485.js:49:21),
85|roklaFrontEnd  |   statusCode: 500,
85|roklaFrontEnd  |   fatal: false,
85|roklaFrontEnd  |   unhandled: false,
85|roklaFrontEnd  |   statusMessage: undefined,
85|roklaFrontEnd  |   data: undefined,
85|roklaFrontEnd  |   __nuxt_error: true
85|roklaFrontEnd  | }

### Describe the bug

when fetching data on server side with useasyncdata composable the fetch fails with error : Failed to fetch: `globalThis.fetch` is not available! on node 18

**Comment by gzf6** [comment]
same issue when using proxyRequest in server/api

**Comment by pi0** [comment]
Is there a chance that your production Node.js version is still v16?

**Comment by gzf6** [comment]
> Is there a chance that your production Node.js version is still v16?

It's v20.9, but I am using Volta to manage Node on Windows. I don’t know if this will cause this issue. I will test it when I have time

**Comment by gzf6** [comment]
> ### Environment
> 
> Operating System: Linux
> 
>     * Node Version:     v18.18.2
> 
>     * Nuxt Version:     3.8.1
> 
>     * CLI Version:      3.9.1
> 
>     * Nitro Version:    2.7.2
> 
>     * Package Manager:  pnpm@8.9.0
> 
>     * Builder:          -
> 
>     * User Config:      app, css, modern, ssr, components, build, modules, legacy, devtools, runtimeConfig, router, experimental
> 
>     * Runtime Modules:  @nuxtjs/tailwindcss@6.9.5, @nuxt/image-edge@1.0.0-28336957.57c0f74, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.2.0, @sidebase/nuxt-auth@0.6.1, vue-recaptcha/nuxt, @nuxt/image@1.0.0, nuxt-vite-legacy@1.1.0
> 
>     * Build Modules:    -
> 
> 
> ### Reproduction
> 
> [node-fetch-native] Failed to fetch: `globalThis.fetch` is not available! 85|roklaFrontEnd | at onError (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2702:16) 85|roklaFrontEnd | ... 6 lines matching cause stack trace ... 85|roklaFrontEnd | at Object.asyncData.refresh.asyncData.execute (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/asyncData-3cf5b485.js:49:21) 85|roklaFrontEnd | at initialFetch (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/asyncData-3cf5b485.js:92:40) 85|roklaFrontEnd | at useAsyncData (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/asyncData-3cf5b485.js:95:21) { 85|roklaFrontEnd | cause: Error: [node-fetch-native] Failed to fetch: `globalThis.fetch` is not available! 85|roklaFrontEnd | at l (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2546:89) 85|roklaFrontEnd | at $fetchRaw2 (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2763:32) 85|roklaFrontEnd | at onError (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2702:16) 85|roklaFrontEnd | at $fetchRaw2 (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2772:20) 85|roklaFrontEnd | at $fetch2 (file:///var/www/html/rokla.ir/html/.output/server/chunks/nitro/node-server.mjs:2805:21) 85|roklaFrontEnd | at $api (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/_api-ef8d63db.js:22:10) 85|roklaFrontEnd | at useAsyncData.watch (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/_slug_-d5f38521.js:41:13) 85|roklaFrontEnd | at Promise.then.result (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/asyncData-3cf5b485.js:52:19) 85|roklaFrontEnd | at new Promise () 85|roklaFrontEnd | at Object.asyncData.refresh.asyncData.execute (file:///var/www/html/rokla.ir/html/.nuxt/dist/server/_nuxt/asyncData-3cf5b485.js:49:21), 85|roklaFrontEnd | statusCode: 500, 85|roklaFrontEnd | fatal: false, 85|roklaFrontEnd | unhandled: false, 85|roklaFrontEnd | statusMessage: undefined, 85|roklaFrontEnd | data: undefined, 85|roklaFrontEnd | __nuxt_error: true 85|roklaFrontEnd | }
> ### Describe the bug
> 
> when fetching data on server side with useasyncdata composable the fetch fails with error : Failed to fetch: `globalThis.fetch` is not available! on node 18
> ### Additional context
> 
> _No response_
> ### Logs
> 
> _No response_

I added `import "node-fetch-native/polyfill` in `node_modules/h3/dist/index.mjs`, but still don’t know what caused it

**Comment by alireza2281** [comment]
> Is there a chance that your production Node.js version is still v16?

I'm getting these problems after using node v18 and above but it's fine working on node v16

**Comment by kreejzak** [comment]
Having the same issue (node 18 and 20), adding `import "node-fetch-native/polyfill"` in `node_modules/h3/dist/index.mjs` helped, but it's not a long term solution.

**Comment by alireza2281** [comment]
After upgrading to nuxt v3.8.2 my problem was fixed
