### ISSUE TITLE
nuxt-vuefire node:fs constants importing error

### ISSUE THREAD

**Issue by luis-amarquez** [nuxt/nuxt#24372]
### Environment

- Operating System: Darwin
- Node Version:     v18.3.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@8.11.0
- Builder:          -
- User Config:      ssr, devtools, modules
- Runtime Modules:  @ant-design-vue/nuxt@1.2.0, nuxt-vuefire@0.4.1
- Build Modules:    -

### Reproduction

cannot start nuxt: Cannot read properties of undefined f_ok

### Describe the bug

`constants` import in `nuxt-vuefire/dist/module.mjs` is being imported from `node:fs/promises` when it should actually be `node:fs`

### Logs

```shell-script
Cannot start nuxt:  Cannot read properties of undefined (reading 'F_OK')                                                                                             8:58:21 PM

  at willUseEmulators (node_modules/nuxt-vuefire/dist/module.mjs:19:73)
  at setup (node_modules/nuxt-vuefire/dist/module.mjs:169:35)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2141:38)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2439:95)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3694:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:255:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:187:7)
  at async NuxtDevServer.init (node_modules/nuxi/dist/chunks/dev2.mjs:182:5)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-child.mjs:103:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1647:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1638:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1770:7)
```

**Comment by luis-amarquez** [comment]
Just realized this was actually posted in the incorrect repo.
