### ISSUE TITLE
ERROR 500 : tag.innerHTML.replace is not a function after upgrading To nuxt 3.8.2

### ISSUE THREAD

**Issue by frederic117** [nuxt/nuxt#24388]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, app, components, modules, speedkit, image, security, snackbar, gtag, pwa, ui, build, runtimeConfig, colorMode, postcss, nitro, vite
- Runtime Modules:  @nuxt/devtools@1.0.3, @nuxt/ui@2.10.0, @vueuse/nuxt@10.6.1, @vueuse/motion/nuxt@2.0.0, @nuxtjs/device@3.1.1, @nuxt/image@1.1.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @vite-pwa/nuxt@0.2.3, nuxt-snackbar@1.0.4, nuxt-gtag@1.1.1, nuxt-security@1.0.0-rc.4, nuxt-speedkit@3.0.0-next.38
- Build Modules:    -

### Reproduction

...

### Describe the bug

500
tag.innerHTML.replace is not a function

at tags:afterResolve (/D:/Dev/maideo/maideo-client-nuxt3/node_modules/unhead/dist/index.mjs:269:43)
at /D:/Dev/maideo/maideo-client-nuxt3/node_modules/hookable/dist/index.mjs:48:66
at Object.run (/D:/Dev/maideo/maideo-client-nuxt3/node_modules/hookable/dist/index.mjs:41:43)
at /D:/Dev/maideo/maideo-client-nuxt3/node_modules/hookable/dist/index.mjs:48:56
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.resolveTags (/D:/Dev/maideo/maideo-client-nuxt3/node_modules/unhead/dist/index.mjs:363:7)
at async renderSSRHead (/D:/Dev/maideo/maideo-client-nuxt3/node_modules/@unhead/ssr/dist/index.mjs:76:23)
at  (D:\Dev\maideo\maideo-client-nuxt3\node_modules\nuxt\dist\core\runtime\nitro\renderer.js:247:70)
at  (D:\Dev\maideo\maideo-client-nuxt3\node_modules\nitropack\dist\runtime\renderer.mjs:19:22)
at async Object.handler (/D:/Dev/maideo/maideo-client-nuxt3/node_modules/h3/dist/index.mjs:1675:19)

**Comment by danielroe** [comment]
This is likely this regression: unjs/unhead#278.

**Comment by harlan-zw** [comment]
Fixed upstream in Unhead 1.8.6. Have gone into detail here: https://github.com/nuxt-modules/fontaine/issues/350

Please delete your lock file + node_modules and re-install.

**Comment by frederic117** [comment]
great thanks a lot :)
