### ISSUE TITLE
ERROR Cannot start nuxt: The requested module 'node:module' does not provide an export named 'isBuiltin'

### ISSUE THREAD

**Issue by afroja-akter** [nuxt/nuxt#24404]
### Environment

 Cannot start nuxt:  The requested module 'node:module' does not provide an export named 'isBuiltin'             12:33:26 PM  

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async bundle (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxt/dist/index.mjs:4512:76)
  at async Promise.all (index 1)
  at async build (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxt/dist/index.mjs:4388:5)
  at async Promise.all (index 1)
  at async NuxtDevServer._load (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxi/dist/chunks/dev2.mjs:280:5)        
  at async NuxtDevServer.load (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxi/dist/chunks/dev2.mjs:185:7)

### Reproduction

 Cannot start nuxt:  The requested module 'node:module' does not provide an export named 'isBuiltin'             12:33:26 PM  

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async bundle (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxt/dist/index.mjs:4512:76)
  at async Promise.all (index 1)
  at async build (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxt/dist/index.mjs:4388:5)
  at async Promise.all (index 1)
  at async NuxtDevServer._load (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxi/dist/chunks/dev2.mjs:280:5)        
  at async NuxtDevServer.load (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxi/dist/chunks/dev2.mjs:185:7)

### Describe the bug

 Cannot start nuxt:  The requested module 'node:module' does not provide an export named 'isBuiltin'             12:33:26 PM  

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async bundle (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxt/dist/index.mjs:4512:76)
  at async Promise.all (index 1)
  at async build (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxt/dist/index.mjs:4388:5)
  at async Promise.all (index 1)
  at async NuxtDevServer._load (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxi/dist/chunks/dev2.mjs:280:5)        
  at async NuxtDevServer.load (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxi/dist/chunks/dev2.mjs:185:7)

### Logs

```shell-script
Cannot start nuxt:  The requested module 'node:module' does not provide an export named 'isBuiltin'             12:33:26 PM  

  at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
  at async bundle (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxt/dist/index.mjs:4512:76)
  at async Promise.all (index 1)
  at async build (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxt/dist/index.mjs:4388:5)
  at async Promise.all (index 1)
  at async NuxtDevServer._load (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxi/dist/chunks/dev2.mjs:280:5)        
  at async NuxtDevServer.load (/C:/Users/MonsterClaw-021/Desktop/Nuxt/nuxt-app/node_modules/nuxi/dist/chunks/dev2.mjs:185:7)
```

**Comment by danielroe** [comment]
what version of node are you using?

You can find out by running `node -v` or running `npx nuxi@latest info`

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/24402.

**Comment by emad313** [comment]
Try to use node v18.18.0 or latest one.

**Comment by ryscript** [comment]
I just upgraded to the latest Nuxt and I got the same when running the app, below are the details on my end

`
------------------------------
- Operating System: Linux
- Node Version:     v18.0.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@8.6.0
- Builder:          -
- User Config:      app, modules, image, devtools, colorMode, sanctum, tailwindcss, googleFonts
- Runtime Modules:  @nuxt/ui@2.10.0, @vueuse/nuxt@10.6.1, @nuxtjs/eslint-module@4.1.0, @nuxt/image@1.1.0, @nuxtjs/fontaine@0.4.1, @nuxtjs/google-fonts@3.0.2, nuxt-auth-sanctum@0.0.10, nuxt-icon@0.6.6
- Build Modules:    -`

Tried the latest node stable (21.2.0) and got the same

Thanks

**Comment by clopezpro** [comment]
> node -v

v18.5.0
