### ISSUE TITLE
Error thrown when opening devtools

### ISSUE THREAD

**Issue by ThatOneCalculator** [nuxt/nuxt#24401]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.7.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  bun@1.0.13
- Builder:          -
- User Config:      devtools, modules, extends, i18n, umami, vite
- Runtime Modules:  `@pinia/nuxt@0.5.1, @formkit/auto-animate/nuxt@0.8.1, @nuxtjs/i18n@8.0.0-rc.5, @nuxt/image@1.1.0, @nuxt/ui@2.10.0-28343426.d39e2de, nuxt-graphql-client@0.2.31, nuxt-og-image@2.2.4, nuxt-icon@0.6.6, @nuxtjs/robots@3.0.0, @unlazy/nuxt@0.10.2, nuxt-plotly@1.0.12`
- Build Modules:    -
------------------------------

### Reproduction

Bun 1.0.13
Linux
Firefox ESR 115
`bun run dev`

### Describe the bug

Opening the devtools with this button 
![image](https://github.com/nuxt/nuxt/assets/44733677/317d628f-95c0-470e-89a2-d5876089bf3d)

shows a white panel

![image](https://github.com/nuxt/nuxt/assets/44733677/f52b6eca-af2f-48a1-94eb-f9c6c985d98f)

and throws this error in the terminal:

```
 ERROR  [h3] [unhandled] parse is not a function                                                                                                                                7:12:00 PM

  at node_modules/sirv/build.js:168:18
  at node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:1357:16
  at call (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50689:7)
  at next (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50633:5)
  at next (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50611:14)
  at next (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50611:14)
  at next (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50611:14)
  at next (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50611:14)
  at call (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50698:3)
  at next (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:50633:5)
```

### Additional context

Vue browser devtools work fine

**Comment by ThatOneCalculator** [comment]
No longer occurs as of bun 1.0.14

**Comment by Pachara** [comment]
I upgrade to bun 1.0.14 and  this error still occur when enable nuxt devtools


[h3] [unhandled] parse is not a function                
  at node_modules/sirv/build.js:168:18
  at node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:1357:16

**Comment by ThatOneCalculator** [comment]
Try upgrading all Nuxt dependencies too.

**Comment by ThahaShahzad** [comment]
Still getting this error with bun 1.0.23 and nuxt 3.9.3
