### ISSUE TITLE
Stack trace for production build with source map

### ISSUE THREAD

**Issue by dhwid** [nuxt/nuxt#24414]
Hi,

I'm struggling with production's build stack trace, I would like to get the trace to the original file (like app.vue) instead of the trace to the `server.mjs`.

I created clean project based on Nuxt 3.8.2. Added `plugins/errorLogger.ts` to handle errors, and added the line to throw error from `app.vue`. 

```
//plugins/errorLogger.ts

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook("vue:error", (err) => {
    throw new Error(err);
  });
});
```

```
//app.vue

<script setup lang="ts">
throw new Error('foo');
</script>

<template>
  <div>
    <NuxtWelcome />
  </div>
</template>
```

After building, creating source maps and executing `node .output/server/index.mjs`, I get an error as expected. But instead of printing track to build's output file `.output/server/chunks/app/server.mjs:872:11` I would like to get a track to the original file (component) `app.vue:2:6`. How to achieve that?

```
[nuxt] Error in `vue:error` hook Error: Error: foo
    at file:///home/dhwid/Projects/nuxt-sourcemap-project/.output/server/chunks/app/server.mjs:872:11
    at file:///home/dhwid/Projects/nuxt-sourcemap-project/.output/server/chunks/app/server.mjs:294:44
    at fn (file:///home/dhwid/Projects/nuxt-sourcemap-project/.output/server/chunks/app/server.mjs:371:44)
    at Object.callAsync (file:///home/dhwid/Projects/nuxt-sourcemap-project/.output/server/chunks/app/server.mjs:80:55)
    at file:///home/dhwid/Projects/nuxt-sourcemap-project/.output/server/chunks/app/server.mjs:373:56
    at Object.runWithContext (/home/dhwid/Projects/nuxt-sourcemap-project/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3863:18)
    at callWithNuxt (file:///home/dhwid/Projects/nuxt-sourcemap-project/.output/server/chunks/app/server.mjs:373:24)
    at file:///home/dhwid/Projects/nuxt-sourcemap-project/.output/server/chunks/app/server.mjs:263:54
    at EffectScope.run (/home/dhwid/Projects/nuxt-sourcemap-project/.output/server/node_modules/@vue/reactivity/dist/reactivity.cjs.js:42:16)
    at Object.runWithContext (file:///home/dhwid/Projects/nuxt-sourcemap-project/.output/server/chunks/app/server.mjs:263:44)
```

**Comment by OrbisK** [comment]
Reproduciton: https://stackblitz.com/edit/github-uxnvwwaa?file=app%2Fapp.vue
