### ISSUE TITLE
builder vite: ERROR  Expecting Unicode escape sequence \uXXXX (1:3) 

### ISSUE THREAD

**Issue by sunnywanggit** [nuxt/nuxt#24459]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.14.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.9.0
- Builder:          vite
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/sunnywanggit/issue

Follow these steps to reproduce：
* pnpm install
* pnpm build:main:dev

### Describe the bug

 Building client...
ℹ vite v4.3.9 building for production...
ℹ transforming...
The file `/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/apps/main/pages/cloud/style/components/create-new-style/domain/create-new-style.domain.ts` is not a valid page as it has no content.
The file `/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/apps/main/pages/cloud/style/components/create-new-style/domain/create-new-style.repo.ts` is not a valid page as it has no content.
The file `/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/apps/main/pages/cloud/style/components/create-video/domain/create-video.domain.ts` is not a valid page as it has no content.
The file `/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/apps/main/pages/cloud/style/components/create-video/domain/create-video.repo.ts` is not a valid page as it has no content.
Unknown type of require argument: "Identifier" in /home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/lt-material-modal@0.0.1-alpha.30_@vue+compiler-sfc@3.3.8_vue@3.3.4/node_modules/lt-material-modal/dist/index.common.js:33362:159
Unknown type of require argument: "Identifier" in /home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/lt-material-modal@0.0.1-alpha.30_@vue+compiler-sfc@3.3.8_vue@3.3.4/node_modules/lt-material-modal/dist/index.common.js:167854:179
ℹ ✓ 435 modules transformed.
ℹ ✓ built in 37.14s

 ERROR  [commonjs--resolver] Expecting Unicode escape sequence \uXXXX (1:3)
file: /home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/lt-material-modal@0.0.1-alpha.30_@vue+compiler-sfc@3.3.8_vue@3.3.4/node_modules/lt-material-modal/dist/index.common.js:1:3

 ERROR  Expecting Unicode escape sequence \uXXXX (1:3)

  at Object.pp$4.raise (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:21621:13)
  at Object.pp.invalidStringToken (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:23770:10)
  at Object.pp.readWord1 (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:23934:16)
  at Object.pp.readWord (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:23953:19)
  at Object.pp.readToken (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:23241:19)
  at Object.readToken (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25991:24)
  at Object.pp.nextToken (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:23234:15)
  at Object.pp.next (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:23195:8)
  at Object.pp$5.parseExprAtom (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20955:10)
  at Object.pp$5.parseExprSubscripts (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20769:19)
  at Object.pp$5.parseMaybeUnary (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20735:17)
  at Object.pp$5.parseExprOps (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20662:19)
  at Object.pp$5.parseMaybeConditional (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20645:19)
  at Object.pp$5.parseMaybeAssign (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20612:19)
  at Object.pp$5.parseParenAndDistinguishExpression (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:21093:28)
  at Object.pp$5.parseExprAtom (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20944:41)
  at Object.pp$5.parseExprSubscripts (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20769:19)
  at Object.pp$5.parseMaybeUnary (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20735:17)
  at Object.pp$5.parseExprOps (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20662:19)
  at Object.pp$5.parseMaybeConditional (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20645:19)
  at Object.pp$5.parseMaybeAssign (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20612:19)
  at Object.pp$5.parseExpression (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:20575:19)
  at Object.pp$8.parseStatement (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:19019:45)
  at Object.pp$8.parseTopLevel (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:18886:21)
  at Object.parse (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:18658:15)
  at Function.parse (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:18708:35)
  at Graph.contextParse (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25754:38)
  at Object.transform (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/@nuxt+vite-builder@3.4.3_@types+node@18.18.13_eslint@8.54.0_sass@1.69.5_stylelint@14.16.1_typ_72y6ve6wdzogwpdd2pjuezynti/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.1d3e962a.mjs:977:17)
  at Object.plugin.transform (/home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/unplugin@1.5.1/node_modules/unplugin/dist/index.mjs:1343:25)
  at /home/jenkins/workspace/Test-front_dragon-cloud-design-dev/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25544:40

### Additional context

lt-material-modal: https://www.npmjs.com/package/lt-material-modal
_No response_

**Comment by sunnywanggit** [comment]
@victortolbert @marr @jaap3 @edwh Can you help me? I have been troubled by this problem for a long time

**Comment by warflash** [comment]
According to the logs you provided this seems like an issue with `lt-material-modal`. I'd recommend checking in with that library first and perhaps try whether removing it solves the issue. If that does not solve it a more minimal reproduction would be great as I can't seem to get your current one to run 🙏

**Comment by sunnywanggit** [comment]
> According to the logs you provided this seems like an issue with `lt-material-modal`. I'd recommend checking in with that library first and perhaps try whether removing it solves the issue. If that does not solve it a more minimal reproduction would be great as I can't seem to get your current one to run 🙏

Introducing lt-material-modal allows for normal packaging in the Vue3 project, but errors may occur when packaging in the Nuxt project, so I am wondering if this is an issue with the Nuxt framework?

**Comment by madebyfabian** [comment]
@sunnywanggit Do you still encounter this issue? Did you try to look into `lt-material-modal`? If you still think this is a Nuxt issue, please provide a working minimal reproduction. Thanks!
