### ISSUE TITLE
Fresh install breaks.

### ISSUE THREAD

**Issue by mateusavila** [nuxt/nuxt#24482]
### Environment

RootDir: /Users/mateus/Projetos/afiliapay/frontend/apps/admin                                                                   12:30:49
Nuxt project info: (copied to clipboard)                                                                                        12:30:49

------------------------------
- Operating System: Darwin
- Node Version:     v20.2.0
- Nuxt Version:     3.8.2
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.0
- Builder:          vite
- User Config:      app, modules, ssr, css, unocss, build, runtimeConfig, sourcemap, vite
- Runtime Modules:  design@1.0.0, @pinia/nuxt@0.5.1, @unocss/nuxt@0.57.7
- Build Modules:    -
------------------------------

### Reproduction

Just make the default instalation.

### Describe the bug

When starting the project with pnpm run dev, the page shows blank (empty), without any error on console if the project is set to ssr: false.

If ssr: true, the following messages appear on terminal:

[nuxt] [request error] [unhandled] [500] entry is not a function
  at __vite_ssr_exports__.default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/app/entry.js:77:41)  
  at default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/@nuxt+vite-builder@3.6.2_@types+node@20.4.1_rollup@2.79.1_sass@1.63.6_vue@3.3.9/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:24)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.renderToString (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/vue-bundle-renderer@1.0.3/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/core/runtime/nitro/renderer.js:171:21)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nitropack@2.8.0/node_modules/nitropack/dist/runtime/renderer.mjs:19:22)  
  at async Object.handler (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1630:19)  
  at async Server.toNodeHandle (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1840:7)
[nuxt] [request error] [unhandled] [500] entry is not a function
  at __vite_ssr_exports__.default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/app/entry.js:77:41)  
  at default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/@nuxt+vite-builder@3.6.2_@types+node@20.4.1_rollup@2.79.1_sass@1.63.6_vue@3.3.9/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:24)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.renderToString (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/vue-bundle-renderer@1.0.3/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/core/runtime/nitro/renderer.js:171:21)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nitropack@2.8.0/node_modules/nitropack/dist/runtime/renderer.mjs:19:22)  
  at async Object.handler (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1630:19)  
  at async Server.toNodeHandle (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1840:7)
[nuxt] [request error] [unhandled] [500] entry is not a function
  at __vite_ssr_exports__.default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/app/entry.js:77:41)  
  at default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/@nuxt+vite-builder@3.6.2_@types+node@20.4.1_rollup@2.79.1_sass@1.63.6_vue@3.3.9/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:24)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.renderToString (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/vue-bundle-renderer@1.0.3/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/core/runtime/nitro/renderer.js:171:21)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nitropack@2.8.0/node_modules/nitropack/dist/runtime/renderer.mjs:19:22)  
  at async Object.handler (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1630:19)  
  at async toNodeHandle (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1840:7)  
  at async ufetch (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/unenv@1.7.4/node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at errorhandler (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/core/runtime/nitro/error.js:35:30)

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] entry is not a function
  at __vite_ssr_exports__.default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/app/entry.js:77:41)  
  at default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/@nuxt+vite-builder@3.6.2_@types+node@20.4.1_rollup@2.79.1_sass@1.63.6_vue@3.3.9/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:24)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.renderToString (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/vue-bundle-renderer@1.0.3/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/core/runtime/nitro/renderer.js:171:21)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nitropack@2.8.0/node_modules/nitropack/dist/runtime/renderer.mjs:19:22)  
  at async Object.handler (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1630:19)  
  at async Server.toNodeHandle (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1840:7)
[nuxt] [request error] [unhandled] [500] entry is not a function
  at __vite_ssr_exports__.default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/app/entry.js:77:41)  
  at default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/@nuxt+vite-builder@3.6.2_@types+node@20.4.1_rollup@2.79.1_sass@1.63.6_vue@3.3.9/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:24)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.renderToString (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/vue-bundle-renderer@1.0.3/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/core/runtime/nitro/renderer.js:171:21)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nitropack@2.8.0/node_modules/nitropack/dist/runtime/renderer.mjs:19:22)  
  at async Object.handler (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1630:19)  
  at async Server.toNodeHandle (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1840:7)
[nuxt] [request error] [unhandled] [500] entry is not a function
  at __vite_ssr_exports__.default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/app/entry.js:77:41)  
  at default (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/@nuxt+vite-builder@3.6.2_@types+node@20.4.1_rollup@2.79.1_sass@1.63.6_vue@3.3.9/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:31:24)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.renderToString (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/vue-bundle-renderer@1.0.3/node_modules/vue-bundle-renderer/dist/runtime.mjs:176:19)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/core/runtime/nitro/renderer.js:171:21)  
  at <anonymous> (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nitropack@2.8.0/node_modules/nitropack/dist/runtime/renderer.mjs:19:22)  
  at async Object.handler (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1630:19)  
  at async toNodeHandle (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/h3@1.8.1/node_modules/h3/dist/index.mjs:1840:7)  
  at async ufetch (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/unenv@1.7.4/node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at errorhandler (/Users/mateus/Projetos/afiliapay/frontend/node_modules/.pnpm/nuxt@3.8.2_@types+node@20.10.0_sass@1.69.5_vite@4.5.0/node_modules/nuxt/dist/core/runtime/nitro/error.js:35:30)
```

**Comment by Triloworld** [comment]
Three step fix that can help you:
- Node 20 isn't supported by all modules at the moment. Try older one. (You use Node Version: v20.2.0) . Node v18.18.0 from starter work fine.
- Try to remove "sourcemap" and "unocss" modules as fresh install don't have it. Re-add and wrote issue on respecting module github repository where it should belong. 
- Align with standards as documentation to get faster help from others too: https://nuxt.com/docs/community/contribution#creating-an-issue

**Comment by mateusavila** [comment]
It worked when downgrade the node version.
