### ISSUE TITLE
Cannot read properties of undefined (reading 'filter')  @nuxt/kit

### ISSUE THREAD

**Issue by Gabrielmoraesp** [nuxt/nuxt#24524]
### Environment

**Local environment**
```
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 AMD FX(tm)-8350 Eight-Core Processor
    Memory: 6.82 GB / 19.96 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.93)
    Internet Explorer: 11.0.19041.3636
``` 

### Reproduction

---

### Describe the bug

I'm trying to deploy the SSR application on Heroku.
I do not know what else to do. I've been trying for 3 days...

The application works perfectly in the local environment.

### Logs

```shell-script
Heroku Logs

-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_VERBOSE=false
       NODE_ENV=development
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  18.x
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  1.x
       
       Resolving node version 18.x...
       Downloading and installing node 18.18.2...
       Using default npm version: 9.8.1
       Resolving yarn version 1.x...
       Downloading and installing yarn (1.22.21)
       Installed yarn 1.22.21
       
-----> Installing dependencies
       Installing node modules (package.json)
       
       added 2793 packages, and audited 2795 packages in 1m
       
       482 packages are looking for funding
         run `npm fund` for details
       
       40 vulnerabilities (1 low, 20 moderate, 17 high, 2 critical)
       
       To address all issues possible (including breaking changes), run:
         npm audit fix --force
       
       Some issues need review, and may require choosing
       a different dependency.
       
       Run `npm audit` for details.
       npm notice 
       npm notice New major version of npm available! 9.8.1 -> 10.2.4
       npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>
       npm notice Run `npm install -g npm@10.2.4` to update!
       npm notice 
       
-----> Build
       Detected both "build" and "heroku-postbuild" scripts
       Running heroku-postbuild
       
       > seducar_nuxt@1.0.0 heroku-postbuild
       > npm run build
       
       
       > seducar_nuxt@1.0.0 build
       > nuxt build
       
 WARN  Changing NODE_ENV from development to production, to avoid unintended behavior.
       Nuxt 2.17.2 with Nitro 2.8.0
 WARN  No .env file found in /tmp/build_334a19c4.
 WARN  Module @nuxt/content is disabled due to incompatibility issues:
 - [nuxt] Nuxt version ^3.0.0-rc.3 is required but currently using 2.17.2
 WARN  Module @nuxtjs/robots is disabled due to incompatibility issues:
 - [bridge] Nuxt bridge is required
 ERROR  Cannot read properties of undefined (reading 'filter')
  at Module.writeTypes (node_modules/@nuxt/kit/dist/index.mjs:2821:36)
  at Object.run (node_modules/nuxi/dist/chunks/build.mjs:93:15)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7) 
 ERROR  Cannot read properties of undefined (reading 'filter')
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by danielroe** [comment]
Reading the error message, it looks like you have versions of the robots and content module that are incompatible with Nuxt 2.

**Comment by yanniznik** [comment]
@Gabrielmoraesp did you eventually find the issue?

**Comment by hashtagnosweat** [comment]
I'm facing this error now, did anyone find a workaround?
