### ISSUE TITLE
SSR error on cloudflare when fetching a prerendered route

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#24523]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.8.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  pnpm@8.10.5
- Builder:          -
- User Config:      extends, modules, ui, nitro, vite, tailwindcss, colorMode, devtools
- Runtime Modules:  @nuxt/ui@2.10.0, @vueuse/nuxt@10.6.1
- Build Modules:    -
------------------------------

### Reproduction

working on it

You can deploy this commit https://github.com/Barbapapazes/relations-unjs/commit/005d39f33f6c5f20e70f56245e5a368c25a59a00 (you will need a UI Pro license)

### Describe the bug

On the server side, I prerender an API route using a route rules.

In the pages/index.vue, I fetch this endpoint. it fail on SSR or even when the page is prerendered on cloudflare. however, it works on client side.

### Additional context

It works fine using netlify or node presets.

**Comment by Barbapapazes** [comment]
I'm not able to reproduce but I do not understand why it happens.

**Comment by Barbapapazes** [comment]
Ok, I got the issue 

 {
      "message": [
        "[nuxt] [request error] [unhandled] [500]",
        "[GET] \"https://unnpm.pages.dev/packages/changelogen\": <no response> Too many subrequests.\n  at async $fetchRaw (chunks/nitro/cloudflare-pages.mjs:1:69382)  \n  at async $fetch (chunks/nitro/cloudflare-pages.mjs:1:70202)  \n  at async Promise.all (index 49)  \n  at async chunks/data.json.mjs:1:295  \n  at async Object.handler (chunks/nitro/cloudflare-pages.mjs:1:62594)  \n  at async chunks/nitro/cloudflare-pages.mjs:1:64963  \n  at async chunks/nitro/cloudflare-pages.mjs:1:103688  \n  at async $fetchRaw (chunks/nitro/cloudflare-pages.mjs:1:69267)  \n  at async $fetch (chunks/nitro/cloudflare-pages.mjs:1:70202)  \n  at async setup (chunks/app/_nuxt/index-6ef0fb7c.mjs:1:4219)"
      ],
      "level": "error",
      "timestamp": 1701260782993
    },
