### ISSUE TITLE
External Props extend broken

### ISSUE THREAD

**Issue by joel-wenzel** [nuxt/nuxt#24533]
### Environment

[6:23:12 PM] Working directory: C:/code/test-app
[6:23:12 PM] Nuxt project info: 

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.8.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-js9bi8-ygsjlv?file=app.vue

### Describe the bug

Extending props from an external file seems to be broken in the latest version (3.8.2). After starting the app you can see the error:
```
[plugin:vite:vue] [@vue/compiler-sfc] Failed to resolve extends base type.
If this previously worked in 3.2, you can instruct the compiler to ignore this extend by adding /* @vue-ignore */ before it, for example:

interface Props extends /* @vue-ignore */ Base {}
```

I created a new vue app (no nuxt) to see if it was a vite or vue issue but it seemed to work ok without nuxt.

### Logs

```shell-script
at ScriptCompileContext.error (C:\code\test-app\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:15670:11)
    at resolveInterfaceMembers (C:\code\test-app\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:17936:13)
    at innerResolveTypeElements (C:\code\test-app\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:17762:14)
    at resolveTypeElements (C:\code\test-app\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:17750:35)
    at innerResolveTypeElements (C:\code\test-app\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:17795:16)
    at resolveTypeElements (C:\code\test-app\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:17750:35)
    at resolveRuntimePropsFromType (C:\code\test-app\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19186:20)
    at genRuntimePropsFromTypes (C:\code\test-app\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19162:17)
    at genRuntimeProps (C:\code\test-app\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:19152:18)
    at Object.compileScript (C:\code\test-app\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:20260:21
```

**Comment by danielroe** [comment]
This is a very bad error message but Vue is trying to tell you that you need to install `typescript` to make this work. (It is required for inferring runtime prop types from pure TS).

Working reproduction: https://stackblitz.com/edit/github-js9bi8-pz6t3q?file=package.json

Ideally we could somehow intercept the error and show it (cc: @antfu).

**Comment by manniL** [comment]
Closing as https://github.com/vuejs/core/pull/8883 is merged and released
