### ISSUE TITLE
RollupError: Entry module "../../node_modules/nuxt/node_modules/nitropack/dist/runtime/entries/nitro-prerenderer" cannot be external. 

### ISSUE THREAD

**Issue by mklueh** [nuxt/nuxt#24551]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.7.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.7.2
- Package Manager:  yarn@4.0.2
- Builder:          -
- User Config:      devtools, dev, debug, modules, typescript, ssr, routeRules, nitro, css, runtimeConfig, sitemap, site, app, build, nuxtIcon, content, experimental
- Runtime Modules:  @unocss/nuxt, @nuxt/content@^2.9.0, @vueuse/nuxt@10.6.1, @nuxtseo/module, nuxt-simple-sitemap, nuxt-link-checker, nuxt-simple-robots, nuxt-icon
- Build Modules:    -

### Reproduction

Not sure, was likely caused by dependency upgrades

### Describe the bug

My build (generate) suddenly fails with the following errors I can't make sense of

```
 ERROR  RollupError: Entry module "../../node_modules/nuxt/node_modules/nitropack/dist/runtime/entries/nitro-prerenderer" cannot be external.                                                                       nitro 09:44:27  


undefined


 ERROR  Entry module "../../node_modules/nuxt/node_modules/nitropack/dist/runtime/entries/nitro-prerenderer" cannot be external.                                                                                          09:44:27  

  at error (/C:/Users/MyUser/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at ModuleLoader.loadEntryModule (/C:/Users/MyUser/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:24887:20)
  at async Promise.all (index 0)



 ERROR  Entry module "../../node_modules/nuxt/node_modules/nitropack/dist/runtime/entries/nitro-prerenderer" cannot be external.      
```

**Comment by mklueh** [comment]
@danielroe I need to extract a reproducer from my monorepo, so it would be nice to know vaguely where such things may be coming from
