### ISSUE TITLE
Nuxt fails to deploy on Cloudflare Pages with `Uncaught TypeError: Object prototype may only be an Object or null: undefined`

### ISSUE THREAD

**Issue by tchin25** [nuxt/nuxt#24573]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.5.0
- Builder:          -
- User Config:      modules, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

[Here's a repo that I hooked up to Cloudflare Pages so you can see when it succeeds/fails deployment.](https://github.com/tchin25/nuxt-jsonwebtoken-bug)

[It fails to deploy when `verify()` is used in server middleware.](https://github.com/tchin25/nuxt-jsonwebtoken-bug/tree/fa0560c99f159c792b0f60dc0c56b01c3002ae8e)

[It deploys successfully when it's commented out.](https://github.com/tchin25/nuxt-jsonwebtoken-bug/tree/5ad5421810c4ba5895c47a63545fc0af26b0ebb3)

### Describe the bug

When using the `jsonwebtoken` package and its `verify()` function in server middleware, Nuxt fails to deploy to Cloudflare Pages with this error *after* everything is built successfully:

```
Error: Failed to publish your Function. Got error: Uncaught TypeError: Object prototype may only be an Object or null: undefined
  at chunks/nitro/cloudflare-pages.mjs:1:147328 in Ut.exports
  at chunks/nitro/cloudflare-pages.mjs:1:158727
```

Everything works locally. When not deploying to Cloudflare Pages it works. When using `jose` instead of `jsonwebtoken` for JWT it works. I don't even know if this is a Nuxt problem.

### Logs

```shell-script
11:44:25.540	[log] Nuxt 3.8.2 with Nitro 2.8.1
11:44:28.985	[info] Building client...
11:44:29.010	[info] vite v4.5.0 building for production...
11:44:29.061	[info] transforming...
11:44:30.776	[info] ✓ 103 modules transformed.
11:44:30.839	Inspect report generated at /opt/buildhome/repo/.nuxt/analyze/.vite-inspect
11:44:30.982	[info] rendering chunks...
11:44:31.046	[info] computing gzip size...
11:44:31.056	[info] .nuxt/dist/client/manifest.json                     1.62 kB │ gzip:  0.33 kB
11:44:31.059	[info] .nuxt/dist/client/_nuxt/error-500.c5df6088.css      1.95 kB │ gzip:  0.74 kB
11:44:31.060	[info] .nuxt/dist/client/_nuxt/error-404.7fc72018.css      3.63 kB │ gzip:  1.12 kB
11:44:31.060	[info] .nuxt/dist/client/_nuxt/vue.f36acd1f.417b85cd.js    0.39 kB │ gzip:  0.27 kB
11:44:31.060	[info] .nuxt/dist/client/_nuxt/error-500.0811a96a.js       1.92 kB │ gzip:  1.01 kB
11:44:31.060	[info] .nuxt/dist/client/_nuxt/error-404.f1c1c3bb.js       6.41 kB │ gzip:  2.83 kB
11:44:31.060	[info] .nuxt/dist/client/_nuxt/entry.043a7343.js         107.37 kB │ gzip: 40.99 kB
11:44:31.061	[info] ✓ built in 2.05s
11:44:31.061	[success] Client built in 2073ms
11:44:31.064	[info] Building server...
11:44:31.068	[info] vite v4.5.0 building SSR bundle for production...
11:44:31.090	[info] transforming...
11:44:31.751	[info] ✓ 48 modules transformed.
11:44:31.831	Inspect report generated at /opt/buildhome/repo/.nuxt/analyze/.vite-inspect
11:44:31.863	[info] rendering chunks...
11:44:31.917	[info] .nuxt/dist/server/_nuxt/error-404-styles.1e0dde27.mjs        0.15 kB
11:44:31.917	[info] .nuxt/dist/server/_nuxt/error-500-styles.cf4b3e80.mjs        0.15 kB
11:44:31.917	[info] .nuxt/dist/server/styles.mjs                                 0.35 kB
11:44:31.917	[info] .nuxt/dist/server/_nuxt/index-6a088328.js                    0.98 kB │ map:  5.93 kB
11:44:31.918	[info] .nuxt/dist/server/_nuxt/island-renderer-4c185c66.js          1.12 kB │ map:  1.53 kB
11:44:31.918	[info] .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-8fa81fcc.js   2.17 kB │ map:  0.12 kB
11:44:31.918	[info] .nuxt/dist/server/_nuxt/error-500-46e8a11f.js                3.07 kB │ map:  3.79 kB
11:44:31.918	[info] .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-e0837f4f.js   3.86 kB │ map:  0.12 kB
11:44:31.921	[info] .nuxt/dist/server/_nuxt/error-404-b0df4638.js               10.08 kB │ map: 21.14 kB
11:44:31.921	[info] .nuxt/dist/server/server.mjs                                26.67 kB │ map: 59.55 kB
11:44:31.921	[info] ✓ built in 852ms
11:44:31.926	[success] Server built in 863ms
11:44:32.020	[success] [nitro] Generated public dist
11:44:32.039	[info] [nitro] Building Nitro Server (preset: `cloudflare-pages`)
11:44:44.181	[success] [nitro] Nitro server built
11:44:44.243	  ├─ dist/_worker.js/chunks/app/_nuxt/error-404-b0df4638.mjs (5.37 kB) (2.29 kB gzip)
11:44:44.243	  ├─ dist/_worker.js/chunks/app/_nuxt/error-404-b0df4638.mjs.map (5.43 kB) (2.38 kB gzip)
11:44:44.244	  ├─ dist/_worker.js/chunks/app/_nuxt/error-404-styles.1e0dde27.mjs (3.75 kB) (1.2 kB gzip)
11:44:44.244	  ├─ dist/_worker.js/chunks/app/_nuxt/error-404-styles.1e0dde27.mjs.map (404 B) (244 B gzip)
11:44:44.244	  ├─ dist/_worker.js/chunks/app/_nuxt/error-500-46e8a11f.mjs (2.21 kB) (1.14 kB gzip)
11:44:44.244	  ├─ dist/_worker.js/chunks/app/_nuxt/error-500-46e8a11f.mjs.map (1.27 kB) (681 B gzip)
11:44:44.244	  ├─ dist/_worker.js/chunks/app/_nuxt/error-500-styles.cf4b3e80.mjs (2.05 kB) (811 B gzip)
11:44:44.244	  ├─ dist/_worker.js/chunks/app/_nuxt/error-500-styles.cf4b3e80.mjs.map (404 B) (243 B gzip)
11:44:44.245	  ├─ dist/_worker.js/chunks/app/_nuxt/index-6a088328.mjs (416 B) (295 B gzip)
11:44:44.245	  ├─ dist/_worker.js/chunks/app/_nuxt/index-6a088328.mjs.map (775 B) (449 B gzip)
11:44:44.245	  ├─ dist/_worker.js/chunks/app/_nuxt/island-renderer-4c185c66.mjs (571 B) (395 B gzip)
11:44:44.245	  ├─ dist/_worker.js/chunks/app/_nuxt/island-renderer-4c185c66.mjs.map (797 B) (471 B gzip)
11:44:44.245	  ├─ dist/_worker.js/chunks/app/client.manifest.mjs (1.81 kB) (410 B gzip)
11:44:44.245	  ├─ dist/_worker.js/chunks/app/client.manifest.mjs.map (1.03 kB) (405 B gzip)
11:44:44.246	  ├─ dist/_worker.js/chunks/app/server.mjs (14.1 kB) (5 kB gzip)
11:44:44.246	  ├─ dist/_worker.js/chunks/app/server.mjs.map (4.38 kB) (1.82 kB gzip)
11:44:44.246	  ├─ dist/_worker.js/chunks/app/styles.mjs (375 B) (225 B gzip)
11:44:44.246	  ├─ dist/_worker.js/chunks/app/styles.mjs.map (318 B) (224 B gzip)
11:44:44.246	  ├─ dist/_worker.js/chunks/error-500.mjs (3.99 kB) (1.76 kB gzip)
11:44:44.246	  ├─ dist/_worker.js/chunks/error-500.mjs.map (311 B) (209 B gzip)
11:44:44.246	  ├─ dist/_worker.js/chunks/handlers/renderer.mjs (632 kB) (186 kB gzip)
11:44:44.247	  ├─ dist/_worker.js/chunks/handlers/renderer.mjs.map (88.8 kB) (27.7 kB gzip)
11:44:44.247	  ├─ dist/_worker.js/chunks/nitro/cloudflare-pages.mjs (236 kB) (67.8 kB gzip)
11:44:44.247	  ├─ dist/_worker.js/chunks/nitro/cloudflare-pages.mjs.map (37.9 kB) (12 kB gzip)
11:44:44.247	  ├─ dist/_worker.js/chunks/rollup/_virtual_spa-template.mjs (85 B) (99 B gzip)
11:44:44.247	  ├─ dist/_worker.js/chunks/rollup/_virtual_spa-template.mjs.map (108 B) (108 B gzip)
11:44:44.247	  ├─ dist/_worker.js/chunks/user.get.mjs (158 B) (153 B gzip)
11:44:44.247	  ├─ dist/_worker.js/chunks/user.get.mjs.map (226 B) (174 B gzip)
11:44:44.247	  └─ dist/_worker.js/index.js (154 B) (155 B gzip)
11:44:44.248	Σ Total size: 1.05 MB (315 kB gzip)
11:44:44.248	[success] [nitro] You can preview this build using `npx wrangler pages dev dist/`
11:44:44.248	[success] [nitro] You can deploy this build using `npx wrangler pages deploy dist/`
11:44:44.394	Finished
11:44:44.395	Found _worker.js in output directory. Uploading.
11:44:45.730	Attaching additional modules:
11:44:45.731	- chunks/app/_nuxt/error-404-b0df4638.mjs (esm)
11:44:45.731	- chunks/app/_nuxt/error-404-styles.1e0dde27.mjs (esm)
11:44:45.731	- chunks/app/_nuxt/error-500-46e8a11f.mjs (esm)
11:44:45.732	- chunks/app/_nuxt/error-500-styles.cf4b3e80.mjs (esm)
11:44:45.732	- chunks/app/_nuxt/index-6a088328.mjs (esm)
11:44:45.732	- chunks/app/_nuxt/island-renderer-4c185c66.mjs (esm)
11:44:45.732	- chunks/app/client.manifest.mjs (esm)
11:44:45.732	- chunks/app/server.mjs (esm)
11:44:45.732	- chunks/app/styles.mjs (esm)
11:44:45.732	- chunks/error-500.mjs (esm)
11:44:45.733	- chunks/handlers/renderer.mjs (esm)
11:44:45.733	- chunks/nitro/cloudflare-pages.mjs (esm)
11:44:45.733	- chunks/rollup/_virtual_spa-template.mjs (esm)
11:44:45.733	- chunks/user.get.mjs (esm)
11:44:45.779	✨ Compiled Worker successfully
11:44:45.883	Found _routes.json in output directory. Uploading.
11:44:45.899	Validating asset output directory
11:44:46.788	Deploying your site to Cloudflare's global network...
11:44:50.207	Uploading... (3/10)
11:44:50.853	Uploading... (5/10)
11:44:50.886	Uploading... (7/10)
11:44:51.075	Uploading... (10/10)
11:44:51.075	✨ Success! Uploaded 7 files (3 already uploaded) (1.17 sec)
11:44:51.075	
11:44:51.327	✨ Upload complete!
11:44:53.572	Success: Assets published!
11:45:00.796	Error: Failed to publish your Function. Got error: Uncaught TypeError: Object prototype may only be an Object or null: undefined
  at chunks/nitro/cloudflare-pages.mjs:1:147328 in Ut.exports
  at chunks/nitro/cloudflare-pages.mjs:1:158727
```

**Comment by danielroe** [comment]
This is likely an upstream library issue. And it's probably replicable in Nitro without Nuxt, as well - would you check? 🙏

**Comment by isramv** [comment]
I have a similar issue:

```
⎔ Starting local server...                                                                
✘ [ERROR] service core:user:tappy-taste: Uncaught TypeError: Object prototype may only be an Object or null: undefined

    at core:user:tappy-taste:44518:45 in V$.exports
    at core:user:tappy-taste:44741:8
    at core:user:tappy-taste:47053:4
    at core:user:tappy-taste:47054:3


✘ [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.  
```

**Comment by Amar-Gill** [comment]
As for `jsonwebtoken` package working locally but not in cloudflare workers ~ that is becuase locally you are running in the NodeJS environment  when you run `npm run dev`

**Comment by tchin25** [comment]
> This is a problem of the `jsonwebtoken` package not being supported in cloudflare workers runtime. Here is an open issue in that repository: [auth0/node-jsonwebtoken#864](https://github.com/auth0/node-jsonwebtoken/issues/864)
> 
> Using `jose` is the recommended package to use json webtokens in the workers runtime.
> 
> I believe we can close this as it's not a nuxt / nitro issue.

Nice catch! I think we can close this then.
