### ISSUE TITLE
Error DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL when use username:password directly on url

### ISSUE THREAD

**Issue by tomosia-hoanguyen** [nuxt/nuxt#24796]
### Environment

- Operating System: Darwin
- Node Version:     v20.6.1
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.0
- Package Manager:  npm@9.8.1

### Reproduction

- Make module basic auth or use any package nuxt basic auth
- Run `npm run build`
- Run `npm run preview`
- Call directly url with username:password same `http://username:password@localhost:3000` on browser
- Check inspect console when appear error for first access, press ASC to stop load page.
- Check console page will be appear error 

### Logs

```shell-script
DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'http://localhost:3000' cannot be created in a document with origin 'http://localhost:3000' and URL 'http://username:password@localhost:3000'.
    at Q (http://localhost:3000/_nuxt/entry.351d726a.js:5:5322)
    at useHistoryStateNavigation (http://localhost:3000/_nuxt/entry.351d726a.js:5:5049)
    at createWebHistory (http://localhost:3000/_nuxt/entry.351d726a.js:5:5876)
    at setup (http://localhost:3000/_nuxt/entry.351d726a.js:94:38070)
    at http://localhost:3000/_nuxt/entry.351d726a.js:1:121516
    at X (http://localhost:3000/_nuxt/entry.351d726a.js:1:121989)
    at Object.runWithContext (http://localhost:3000/_nuxt/entry.351d726a.js:1:54380)
    at callWithNuxt (http://localhost:3000/_nuxt/entry.351d726a.js:1:122027)
    at http://localhost:3000/_nuxt/entry.351d726a.js:1:120510
```
```
entry.351d726a.js:1 [nuxt] error caught during app initialization Error: Context conflict
    at X (VM9 entry.351d726a.js:1:118641)
    at Object.set (VM9 entry.351d726a.js:1:119049)
    at callWithNuxt (entry.351d726a.js:1:122011)
    at entry.351d726a.js:1:120510
    at EffectScope.run (entry.351d726a.js:1:3992)
    at Object.runWithContext (entry.351d726a.js:1:120502)
    at applyPlugin (entry.351d726a.js:1:121497)
    at applyPlugins (entry.351d726a.js:1:121662)
    at entry (entry.351d726a.js:151:15464)
    at entry.351d726a.js:151:15766
```
    
```
entry.351d726a.js:1 Hydration completed but contains mismatches.
```

**Comment by tomosia-hoanguyen** [comment]
In my case, main issue is error `[nuxt] error caught during app initialization Error: Context conflict`. Nuxt throw error `Context conflict`, then error page shown briefly before redirecting again main url without basic authentication.
After many hour research, i try new experimental feature https://nuxt.com/docs/guide/going-further/experimental-features#asynccontext, and luckily everything was resolved 🙇‍♂️
