### ISSUE TITLE
Type issue when using `useFetch` with baseURL

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#24791]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.7.1
- Builder:          -
- User Config:      modules, runtimeConfig, css, site, linkChecker, devtools
- Runtime Modules:  @nuxt/ui@2.11.1, @nuxtseo/module@2.0.0-beta.50
- Build Modules:    -
------------------------------

### Reproduction

```ts
const config = useRuntimeConfig()
const { data: followers } = await useFetch('/repos', {
  baseUrl: config.public.apiBase,
})
```

inside a script tag. In your nuxt.config.ts file, you must define a apiBase.

```
  runtimeConfig: {
    public: {
      apiBase: 'http://localhost:3333',
    },
  },
```

### Describe the bug

This will give you the following type error

```
No overload matches this call.
  Overload 1 of 2, '(request: "/repos" | Ref<"/repos"> | (() => "/repos"), opts?: UseFetchOptions<unknown, unknown, KeysOf<unknown>, null, "/repos", "get"> | undefined): AsyncData<unknown, FetchError<any> | null>', gave the following error.
  Overload 2 of 2, '(request: "/repos" | Ref<"/repos"> | (() => "/repos"), opts?: UseFetchOptions<unknown, unknown, KeysOf<unknown>, unknown, "/repos", "get"> | undefined): AsyncData<unknown, FetchError<any> | null>', gave the following error.
```

![image](https://github.com/nuxt/nuxt/assets/45267552/da17440c-104a-4375-af65-94074ee24a34)

### Logs

using `npx nuxi typecheck`

```
pages/index.vue:4:3 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(request: "/repos" | Ref<"/repos"> | (() => "/repos"), opts?: UseFetchOptions<unknown, unknown, KeysOf<unknown>, null, "/repos", "get"> | undefined): AsyncData<unknown, FetchError<any> | null>', gave the following error.
    Object literal may only specify known properties, but 'baseUrl' does not exist in type 'UseFetchOptions<unknown, unknown, KeysOf<unknown>, null, "/repos", "get">'. Did you mean to write 'baseURL'?
  Overload 2 of 2, '(request: "/repos" | Ref<"/repos"> | (() => "/repos"), opts?: UseFetchOptions<unknown, unknown, KeysOf<unknown>, unknown, "/repos", "get"> | undefined): AsyncData<unknown, FetchError<any> | null>', gave the following error.
    Object literal may only specify known properties, but 'baseUrl' does not exist in type 'UseFetchOptions<unknown, unknown, KeysOf<unknown>, unknown, "/repos", "get">'. Did you mean to write 'baseURL'?

4   baseUrl: config.public.apiBase,
    ~~~~~~~



Found 1 error in pages/index.vue:4


 ERROR  Command failed with exit code 2: npx -p vue-tsc -p typescript vue-tsc --noEmit                                                                                                                                                                       10:42:22 AM

  at makeError (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/index3.mjs:625:11)
  at handlePromise (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/index3.mjs:1821:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/typecheck.mjs:82:7)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7) 



 ERROR  Command failed with exit code 2: npx -p vue-tsc -p typescript vue-tsc --noEmit   
```

**Comment by Barbapapazes** [comment]
It was just a typo. 🫣
