### ISSUE TITLE
Unable to invoke useRuntimeConfig from another composable if this composable was invoked in an API route

### ISSUE THREAD

**Issue by ourique-gus** [nuxt/nuxt#24841]
### Environment

- Operating System: Linux
- Node Version:     v18.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@8.19.1
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. Create a new Nuxt 3 app
2. Create a composable which invokes "useRuntimeConfig"
3. Create an API route which invokes your created composable
4. Invoke this API route

https://stackblitz.com/edit/nuxt-starter-48vrb3?file=server%2Fapi%2Ftest.js

### Describe the bug

If a composable that invokes "useRuntimeConfig" is invoked inside an API route, the following error is returned

```[nuxt] [request error] [unhandled] [500] useRuntimeConfig is not defined```
  
  **Note that this error does not occur if the same composable is invoked inside template/script**

### Additional context

Current workaround: invoke useRuntimeConfig inside API route and send the result as an argument to my composable

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] useRuntimeConfig is not defined
  at useMyComposable (./composables/useMyComposable.js:2:18)  
  at <anonymous> (./server/api/test.js:6:1)  
  at ./node_modules/h3/dist/index.mjs:1610:47  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1675:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1885:7)
```

**Comment by manniL** [comment]
Composables are not meant to run in the `server` folder with exception to a few like `useRuntimeConfig` (and same for app config). 

instead, create e.g. a file in `server/utils` like `server/utils/my-helper-fn.ts`:

```ts
export const myHelperFn = () => {
  return useRuntimeConfig();
};
```

Then in your api endpoint, e.g. `server/api/test.ts`:

```ts
export default defineEventHandler(async (event) => {
  const config = useRuntimeConfig();
  const helper = myHelperFn();

  return helper;
});
```

**Comment by gus-ourique-poatek** [comment]
@manniL for consistency reasons, how me, as an user, should know "which composables should be allowed on server routes"?

**Comment by ourique-gus** [comment]
Hi @manniL 
Just for consistency
how me, as a normal user, should know which composables are allowed in server routes?

I'm trying to do a collection of functions where some should be used on server-side and others in client-side, but both shares several variables

**Comment by manniL** [comment]
@gus-ourique-poatek Fair point. From the top of my head (applying only to the `server/` folder), only [`useRuntimeConfig`](https://nitro.unjs.io/guide/configuration#runtime-configuration) and `useAppConfig`.

You can use any kind of function that is not a composable whereever you like, though `utils` won't be auto import for the files in your `server` folder (for this, use `server/utils`) - and vice versa.

**Comment by ourique-gus** [comment]
Creating utils inside server directory works fine
But if I create utils by side of server directory, I got the same error

I think it is not possible right now to have shared routines in both API layer and "template/script" layer

Am I wrong?

Case of use:
I have 2 functions, one generates a public key and the other one validates the public key using a secret
To generate the public key, you can call it on client-side
To validate the public key, you must invoke an API which validates this key
This should work if I plug everything in a composable and run it only in server-side inside <script setup>
However, this would increase the response time, due to the validation process (that is why I'm trying to move this to an API route)

**Comment by manniL** [comment]
@ourique-gus can you maybe update your stackblitz with a rough idea of it (using `utils` + `server/utils` folder)? Happy to have a look.

**Comment by ourique-gus** [comment]
@manniL For sure
I updated stackblitz

You will notice that I can do what I want if I separate these functions in two files (one utils for pages and other for server)
But for my initial idea was to keep them together to be more readable, since they are associated.

The code is identical, but it will only work if I break it down in two files

**Comment by manniL** [comment]
@ourique-gus Thanks, will have a closer look in a bit! But you might be able to simply re-export the shared utility (see https://www.youtube.com/watch?v=0_hZymmpUHQ)

**Comment by ourique-gus** [comment]
@manniL Thanks! This is exactly what I'm looking for
However, when I tried to do something similar to this, I got an error saying "useRuntimeConfig" is not defined... I will try again soon and tell you if it worked.

**Comment by ourique-gus** [comment]
Hi @manniL 
I followed your suggestion, and I'm getting the same error
```[nuxt] [request error] [unhandled] [500] useRuntimeConfig is not defined```

I'm not sure why, but when I import from "/utils" into "/server/utils" a function that depends on useRuntimeConfig, it just don't find this function anymore

**Comment by manniL** [comment]
Interestingly, it works the other way around: https://stackblitz.com/edit/nuxt-issues-24841-shared?file=server%2Fapi%2Ftest.js,app.vue,utils%2Fshared.js,server%2Futils%2Fshared.js 🤔

**Comment by ourique-gus** [comment]
Well, for me this is kinda unexpected, but good, if it works, it works

Again, thanks @manniL ! I will follow your suggestions 😃

**Comment by manniL** [comment]
@ourique-gus for me too 🙈
