### ISSUE TITLE
Deno preset deploy faild to run 

### ISSUE THREAD

**Issue by aramdata** [nuxt/nuxt#24886]
### Environment

node 18 , Nuxt 3.8.2 with Nitro 2.8.1
ℹ Using Nitro server preset: deno_deploy

### Reproduction

pnpm run build --preset=deno_deploy ==> create index.ts in server folder
deno run -A server\index.ts => raise error , error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'match')
const match = input.match(SEMVER_REGEXP) || [];

### Describe the bug

in my index.ts file there is line for node version
const NODE_VERSION = utils$D.parseSemver(process.versions.node);
that pass process.versions.node to method
function parseSemver(input) { const match = input.match(SEMVER_REGEXP) || []; const major = parseInt(match[1], 10); const minor = parseInt(match[2], 10); const patch = parseInt(match[3], 10); return { buildmetadata: match[5], major: isNaN(major) ? undefined : major, minor: isNaN(minor) ? undefined : minor, patch: isNaN(patch) ? undefined : patch, prerelease: match[4], }; }

input is undefined.
in manual test , i replace const NODE_VERSION to 18 and deno run worked.

### Logs

```shell-script
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'match')
  const match = input.match(SEMVER_REGEXP) || [];
                      ^
    at Object.parseSemver (file:///***/.output/server/index.ts:18750:23)
    at file:///****/.output/server/index.ts:37061:30
```

**Comment by aramdata** [comment]
let's me to create minimal project that reproduce same environment like main project to share here
