### ISSUE TITLE
__NUXT_ASYNC_CONTEXT__ is not defined

### ISSUE THREAD

**Issue by localusercamp** [nuxt/nuxt#24901]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      extends, app, css, components, experimental, typescript, devtools, modules, tailwindcss
- Runtime Modules:  @vueuse/nuxt@10.7.0, @uikit/nuxt@1.0.0
- Build Modules:    -
------------------------------

### Reproduction

Can not reproduce this bug in fresh app.

### Describe the bug

After upgrading to nuxt 3.9.0 app does not running in dev mode and the following error occures:
![image](https://github.com/nuxt/nuxt/assets/45385480/09e9001e-81d7-4767-aa2b-ce83cae0c395)

It might be vite 5 related bug, because it seems like notheing else in 3.9.0 could lead to this...

### Additional context

I use a monorepo with `lerna`.
I use this command to start the server:
```bash
lerna run dev --scope @apps/app
```

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] __NUXT_ASYNC_CONTEXT__ is not defined
  at C:\OpenServer\domains\kidnapper\frontend\node_modules\nuxt\dist\app\nuxt.js:8:19
  at async ViteNodeRunner.directRequest (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:341:5)
  at async ViteNodeRunner.cachedRequest (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:197:14)
  at async ViteNodeRunner.dependencyRequest (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:231:12)
  at async C:\OpenServer\domains\kidnapper\frontend\node_modules\nuxt\dist\app\entry.js:4:31
  at async ViteNodeRunner.directRequest (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:341:5)
  at async ViteNodeRunner.cachedRequest (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:197:14)
  at async ViteNodeRunner.executeFile (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:169:12)
  at async default (/C:/OpenServer/domains/kidnapper/frontend/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:67)
  at async Object.renderToString (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
[nuxt] [request error] [unhandled] [500] __NUXT_ASYNC_CONTEXT__ is not defined
  at C:\OpenServer\domains\kidnapper\frontend\node_modules\nuxt\dist\app\nuxt.js:8:19
  at async ViteNodeRunner.directRequest (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:341:5)
  at async ViteNodeRunner.cachedRequest (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:197:14)
  at async ViteNodeRunner.dependencyRequest (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:231:12)
  at async C:\OpenServer\domains\kidnapper\frontend\node_modules\nuxt\dist\app\entry.js:4:31
  at async ViteNodeRunner.directRequest (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:341:5)
  at async ViteNodeRunner.cachedRequest (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:197:14)
  at async ViteNodeRunner.executeFile (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vite-node/dist/client.mjs:169:12)
  at async default (/C:/OpenServer/domains/kidnapper/frontend/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:67)
  at async Object.renderToString (/C:/OpenServer/domains/kidnapper/frontend/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
```

**Comment by leosin** [comment]
```
 Vite client warmed up in 907ms                                                                                                                                                                             14:41:52
ℹ Vite server warmed up in 1749ms                                                                                                                                                                            14:41:53
✔ Nitro built in 732 ms                                                                                                                                                                                nitro 14:41:53
[nuxt] [request error] [unhandled] [500] __NUXT_ASYNC_CONTEXT__ is not defined
  at /Users//Projects/M&M/node_modules/.pnpm/nuxt@3.9.0_@types+node@20.10.5_eslint@8.56.0_sass@1.69.5_typescript@5.3.3_vite@5.0.10/node_modules/nuxt/dist/app/nuxt.js:8:19  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
  at async ViteNodeRunner.directRequest (/Users//Projects/M&M/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.10.0_sass@1.69.5/node_modules/vite-node/dist/client.mjs:341:5)  
  at async ViteNodeRunner.cachedRequest (/Users//Projects/M&M/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.10.0_sass@1.69.5/node_modules/vite-node/dist/client.mjs:197:14)  
  at async ViteNodeRunner.dependencyRequest (/Users//Projects/M&M/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.10.0_sass@1.69.5/node_modules/vite-node/dist/client.mjs:231:12)  
  at async /Users//Projects/M&M/node_modules/.pnpm/nuxt@3.9.0_@types+node@20.10.5_eslint@8.56.0_sass@1.69.5_typescript@5.3.3_vite@5.0.10/node_modules/nuxt/dist/app/entry.js:4:31  
  at async ViteNodeRunner.directRequest (/Users//Projects/M&M/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.10.0_sass@1.69.5/node_modules/vite-node/dist/client.mjs:341:5)  
  at async ViteNodeRunner.cachedRequest (/Users//Projects/M&M/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.10.0_sass@1.69.5/node_modules/vite-node/dist/client.mjs:197:14)  
  at async ViteNodeRunner.executeFile (/Users//Projects/M&M/node_modules/.pnpm/vite-node@0.33.0_@types+node@20.10.0_sass@1.69.5/node_modules/vite-node/dist/client.mjs:169:12)  
  at async default (/Users//Projects/M&M/node_modules/.pnpm/@nuxt+vite-builder@3.8.2_@types+node@20.10.0_eslint@8.54.0_sass@1.69.5_typescript@5.3.2_vue@3.3.11/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:67)
```

**Comment by localusercamp** [comment]
@leosin 
Could you please run `npx nuxi info` or list modules that you are using?

**Comment by danielroe** [comment]
Would you check that your `@nuxt/vite-builder` version is also 3.9.0?

**Comment by leosin** [comment]
@localusercamp 
------------------------------
- Operating System: Darwin
- Node Version:     v20.9.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.12.1
- Builder:          -
- User Config:      app, build, css, devtools, modules, svgo, runtimeConfig, vite
- Runtime Modules:  @vueuse/nuxt@10.7.0, @unocss/nuxt@0.58.0, nuxt-svgo@3.7.0
- Build Modules:    -
------------------------------

**Comment by localusercamp** [comment]
@danielroe
Yes version the same.
![image](https://github.com/nuxt/nuxt/assets/45385480/849f10c9-5e7c-4285-adf5-613b77936511)

**Comment by danielroe** [comment]
How about your `@nuxt/schema` version?

Workaround will be to set `vite.define.__NUXT_ASYNC_CONTEXT__` to `false`.

**Comment by CernyMatej** [comment]
Hi, I personally wasn't able to replicate this issue, but my friend has been experiencing it on his MacBook. The nuxt schema version is `3.9.0`

Where should I put the workaround?

**Comment by elonsalfati** [comment]
Yep same issue here after upgrading to the latest version.

Running on mac as well.

**Comment by and-ratajski** [comment]
My guess is that you have another Nuxt installation under `/Users/<your-user-name>`. Try deleting `node_modules` and `package.json` with your package manager's lock file from there. 

If that doesn't help you can try downgrading your Nuxt version to `3.8.2` and reinstalling it.

**Comment by localusercamp** [comment]
> My guess is that you have another Nuxt installation under /Users/\u003Cyour-user-name>

In my case I have a monorepo under lerna. I don't think that this is related.
We need more info about what the `__NUXT_ASYNC_CONTEXT__` is, to make guesses about what that could be.
I will try to solve this problem in two weeks.

**Comment by danielroe** [comment]
The likely workaround is:

```ts
export default defineNuxtConfig({
  vite: {
    define: {
      __NUXT_ASYNC_CONTEXT__: false
    }
  }
})
```

**Comment by localusercamp** [comment]
@danielroe 
Yeah, I'll check that as well, and give you feedback.
Still using the workaround is not pleasant =).

**Comment by danielroe** [comment]
I'm pretty sure it's not a Nuxt issue but is triggered by the mismatch of Nuxt/vite versions.

**Comment by CernyMatej** [comment]
> My guess is that you have another Nuxt installation under `/Users/<your-user-name>`. Try deleting `node_modules` and `package.json` with your package manager's lock file from there. 
> 

@and-ratajski 
You're right! Removing `node_modules` from the home folder solved it for the friend of mine. Good catch!

**Comment by and-ratajski** [comment]
> > My guess is that you have another Nuxt installation under `/Users/<your-user-name>`. Try deleting `node_modules` and `package.json` with your package manager's lock file from there.
> 
> @and-ratajski You're right! Removing `node_modules` from the home folder solved it for the friend of mine. Good catch!

Thought so 😎 BTW that's exactly the reason why I prefer using dockerized environment also for development!

**Comment by localusercamp** [comment]
I tried to fix it and it works now.

What have I done:
- Delete monorepo `node_modules` (packages that was shared between all applications).
- Delete every app `node_modules` inside monorepo (local packages for each app).
- Delete `package-lock.json` (since i use monorepo there only one lock file on monorepo level).
- Delete all `.nuxt` folders of all nuxt apps inside monorepo.
- Upgrade to nuxt 3.9.1 via incrementing package version inside `package.json` of every app inside monorepo.
- `npm i`.

After this steps app runs fine.

I think in my case that was old app postinstall files inside `.nuxt` folder. Because i using monorepo with `lerna` (version `8.0.2`) there too musch of a hussle for me to run `nuxi upgrade -f` in every app. So what i regularry do is just incrementing nuxt version manually inside `package.json`. This leads to situation when all dependencies are updated, but `.nuxt` folder is not _"recompiled"_. But these are just my thoughts, I really don't know why it didn't work =D.

As @and-ratajski suggested it could be the `node_modules` folder inside your user directory, but not in my case - there was no any other `node_modules` anywhere else.

@danielroe 
If it makes any sense (since it already closed) the issue could be closed as `closed` instead of `not planned`.

**Comment by fimion** [comment]
Further update:

A reproduction here:

https://stackblitz.com/edit/github-e4atgm?file=app.config.ts

removing `import { defineAppConfig } from '#app/nuxt';` from your `app.config.ts` file seems to also fix this issue.

**Comment by CernyMatej** [comment]
I just experienced it on my personal project as well. Made sure no `node_modules` are in the home folder of my user.

**Comment by datWeazel** [comment]
Got the same issue after trying to upgrade from 3.8.2 to 3.10.0
I got no other `.nuxt` or `node_modules` directories in my home folder.
The vite define workaround also didn't work. 

`@nuxt/schema` and `@nuxt/vite-builder` versions are latest (both 3.10.0)

```
------------------------------
- Operating System: Darwin
- Node Version:     v20.5.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.4.0
- Builder:          -
- User Config:      devtools, css, nitro, runtimeConfig, app, postcss, colorMode, modules, build
- Runtime Modules:  @nuxt/ui@2.13.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0
- Build Modules:    -
------------------------------
```

**Comment by localusercamp** [comment]
@datWeazel did you try to delete the `.nuxt` folder of your project?
If it doesn't work try to delete `node_modules` and `.nuxt` and then reinstall all deps via `npm i`

**Comment by ku-ku** [comment]
This bug is back in the version 3.10.0(1), in 3.9.3 it`s ok

**Comment by FroudeDescartes** [comment]
GTM module was creating this bug on my app. When removed, everything worked fine again

**Comment by Harm-Nullix** [comment]
@MarijnMensinga  https://github.com/nuxt/nuxt/issues/25620
