### ISSUE TITLE
"Nuxt Typed Router" module error on start --  "Cannot start nuxt:  Nuxt module should be a function: nuxt-typed-router"

### ISSUE THREAD

**Issue by wladyslaw-malejew** [nuxt/nuxt#24947]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.9.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      modules
- Runtime Modules:  nuxt-typed-router@3.5.0
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-7e4xvw-s3cqyv

### Describe the bug

Having "Cannot start nuxt:  Nuxt module should be a function: nuxt-typed-router" when trying to start a dev server

### Additional context

Created related issue on "nuxt-typed-router" git:
https://github.com/victorgarciaesgi/nuxt-typed-router/issues/134

### Logs

```shell-script
yarn run v1.22.19
$ HOST=0.0.0.0 nuxt dev
Nuxt 3.9.0 with Nitro 2.8.1                                                                       06:13:29
                                                                                                  06:13:30
 
              █▀▀▀▀▀▀▀██▀██▀█▀▀█▀▀▀▀█▀▀▀▀▀▀▀█
              █ █▀▀▀█ █ ▀▀  █  █▀▄█ █ █▀▀▀█ █
              █ █   █ █▀▄▄▄█▀█ ▄█ ███ █   █ █
              █ ▀▀▀▀▀ █ ▄▀▄▀▄▀▄ █ ▄▀█ ▀▀▀▀▀ █
              █▀▀█▀██▀▀▄▄▀█ ▀▀ ▀▄▄ ▄█▀▀▀█▀▀██
              █ █▀▄█ ▀▄█▀ ▄▀▀ ██▄█▀▄▄ ▀█ ▀▀▄█
              █ ▄ █ ▄▀▄███▄▄ ▄█▀▀██ ▀ ██▀▄ ▀█
              █▄  ▀ ▄▀▀▀▄▄▀▄▀ ██▀▀▄▄▄▀█▀▀▀▀▀█
              █   ▀▄▀▀█ █▄ █▄█▄  ▄█  ▄▄█▄█ ██
              █▀▄ ▄▀█▀ █▀█▄▄ ██ █▄█  ▄▄▀▄█▀ █
              █▀█▄ ▀▄▀▄ █▄ █▀▄  ▄▀ ▀  ▀▀█▀▄▄█
              █▀▀▀▀▀▀▀█ ▀ █▄▀██▄▀██ █▀█ █▄ ▄█
              █ █▀▀▀█ ██ ▄▄▀ █▄▄▀▄█ ▀▀▀ ▄▄▄▀█
              █ █   █ █▄  ▀▄▀▄██▄█▀██▄█   █▀█
              █ ▀▀▀▀▀ █  ███▄  █ ▄█  ▄█ ██ ██
              ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
 
  ➜ Network:  https://stackblitz.com/edit/github-7e4xvw-s3cqyv [QR code]
  ➜ Local:    http://0.0.0.0:3000/
  ➜ Network:  http://192.168.1.104:3000/


 ERROR  Cannot start nuxt:  Nuxt module should be a function: nuxt-typed-router                   06:13:32

  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2582:11)
  at async Module.installModule (node_modules/@nuxt/kit/dist/index.mjs:2521:47)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3839:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:268:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:200:7)
  at async NuxtDevServer.init (node_modules/nuxi/dist/chunks/dev2.mjs:195:5)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-child.mjs:116:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1678:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1669:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1803:7)
```

**Comment by wladyslaw-malejew** [comment]
adding "prettier" solves the issue:

"yarn add prettier"
