### ISSUE TITLE
invalid code is generated if there is a layout named "index"

### ISSUE THREAD

**Issue by hecateball** [nuxt/nuxt#24988]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.5.1`
- Nuxt Version:     `3.9.0`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.1`
- Package Manager:  `npm@9.8.0`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-vjwzyc-btki5e

1. initialize nuxt3 project
2. add layout named "index"
3. modify app.vue to use `<NuxtLayout>` component

### Describe the bug

if a project have layout file named `index.vue`, following error occurs on running dev/build (probably because  'index' is omitted in an unintended way):

### dev mode
`[vite-node] [PARSE_ERROR] virtual:nuxt:./.nuxt/layouts.mjs` on browser

### on build
```
 ERROR  Unexpected token :. Expected identifier, string literal, numeric literal or [ for the computed key (Note that you need plugins to import files that are not JavaScript)         23:56:39
file: virtual:nuxt:/home/projects/github-vjwzyc-btki5e/.nuxt/layouts.mjs:2:2
1: export default {
2:   : () => import("/home/projects/github-vjwzyc-btki5e/layouts/index.vue").then(m => m.default || m)
     ^
3: }


[23:56:39]  ERROR  Nuxt Build Error: Unexpected token :. Expected identifier, string literal, numeric literal or [ for the computed key (Note that you need plugins to import files that are not JavaScript)

  at error (node_modules/rollup/dist/es/shared/parseAst.js:468:30)
  at nodeConverters (node_modules/rollup/dist/es/shared/parseAst.js:2215:9)
  at convertNode (node_modules/rollup/dist/es/shared/parseAst.js:1100:12)
  at convertProgram (node_modules/rollup/dist/es/shared/parseAst.js:1091:48)
  at Module.parseAstAsync (node_modules/rollup/dist/es/shared/parseAst.js:2281:20)
  at async Module.tryParseAsync (node_modules/rollup/dist/es/shared/node-entry.js:13539:21)
  at async Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:13120:35)
  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:17785:13)
```

### Additional context

There were no problem at v3.7.3

**Comment by andiamvinay** [comment]
Just ran into this issue.. Thanks for reporting @hecateball

**Comment by ridge-kimani** [comment]
Could this be an issue with `Rollup`?

**Comment by manniL** [comment]
@ridge-kimani From the error message it seems like they `key` of the object mapping layout components strips the `index` part fully.

**Comment by danielroe** [comment]
It's a very quick fix. The main question is what our desired behaviour should be. For components, we do not allow `index.vue` as a name. I think the value of keeping consistent behaviour between component + layout naming is the important piece.

**Comment by manniL** [comment]
> I think the value of keeping consistent behaviour between component + layout naming is the important piece.

Same for middleware. So instead, maybe a warning would be better?

**Comment by danielroe** [comment]
Agreed. ✅

**Comment by ridge-kimani** [comment]
The name here is dependent on the file's path name. Should the behavior be the same if I give the component a different `name` attribute?
```js
export default {
   name: "different-name"
}
