### ISSUE TITLE
[nuxt.options._layers is not iterable] when creating an empty Nuxt.js project with TailwindCss

### ISSUE THREAD

**Issue by StevenSK-king** [nuxt/nuxt#25068]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.16.0
- Nuxt Version:     2.17.2
- CLI Version:      3.10.0
- Nitro Version:    -
- Package Manager:  npm@9.5.1
- Builder:          webpack
- User Config:      head, css, plugins, components, buildModules, modules, build, devtools, postcss
- Runtime Modules:  -
- Build Modules:    @nuxtjs/tailwindcss@5.3.5
------------------------------

### Reproduction

I create the nuxt project and select the following configurations

run the command:  npx create-nuxt-app <project-name>
Programming language: JavaScript
Package manager: npm
UI framework: Tailwind CSS
Nuxt.js modules: Axios - Promise based HTTP client
Linting tools: ESLint
Testing framework: None
Rendering mode: Universal (SSR / SSG)
Deployment target:  Server (Node.js hosting)
Development tools: jsconfig.json
Continuous integration: None
Version control system: Git

### Describe the bug

Everything is working smoothly when creating the empty nuxt.js project. However when I run the  "npm run dev" it throw the error below:

(base) PS D:\SoftwareDevelopment\freetts\sourcecode\freetts-v2> npm run dev

> freetts-v2@1.0.0 dev
> nuxt

i Using default Tailwind CSS file from runtime/tailwind.css                                                                      nuxt:tailwindcss 20:17:27

 FATAL  nuxt.options._layers is not iterable                                                                                                      20:17:27  

  at installModule (/D:/SoftwareDevelopment/freetts/sourcecode/freetts-v2/node_modules/@nuxt/kit/dist/index.mjs:2439:32)
  at async setup (/D:/SoftwareDevelopment/freetts/sourcecode/freetts-v2/node_modules/@nuxtjs/tailwindcss/dist/module.mjs:186:7)
  at async ModuleContainer.normalizedModule (/D:/SoftwareDevelopment/freetts/sourcecode/freetts-v2/node_modules/@nuxt/kit/dist/index.mjs:2142:17)
  at async ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:167:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:34:7)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:342:5)

 FATAL  nuxt.options._layers is not iterable                                                                                                      20:17:27  

  at installModule (/D:/SoftwareDevelopment/freetts/sourcecode/freetts-v2/node_modules/@nuxt/kit/dist/index.mjs:2439:32)
  at async setup (/D:/SoftwareDevelopment/freetts/sourcecode/freetts-v2/node_modules/@nuxtjs/tailwindcss/dist/module.mjs:186:7)
  at async ModuleContainer.normalizedModule (/D:/SoftwareDevelopment/freetts/sourcecode/freetts-v2/node_modules/@nuxt/kit/dist/index.mjs:2142:17)
  at async ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:167:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:34:7)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:342:5)

   ╭─────────────────────────────────────────────────────╮
   │                                                     │
   │   ✖ Nuxt Fatal Error                                │
   │                                                     │
   │   TypeError: nuxt.options._layers is not iterable   │
   │                                                     │
   ╰─────────────────────────────────────────────────────╯

If I remove the tailwindcss fron nuxt.config.js "buildModules: ['@nuxtjs/tailwindcss'],", it works fine again.

Please help me with that!

![123](https://github.com/nuxt/nuxt/assets/28992096/6fc298ad-fd5e-42de-8201-3274a332268c)

**Comment by manniL** [comment]
You are accidentally using Nuxt 2. `npx nuxi init` will create a new Nuxt 3 project 👍🏻

**Comment by sthiepaan** [comment]
@manniL, is that mean that `v4.2.1` is last version that is supported for _Nuxt_ `v2`?

**Comment by manniL** [comment]
@sthiepaan No, it should work in Nuxt 2. if not open an issue in https://github.com/nuxt-modules/tailwindcss

**Comment by sthiepaan** [comment]
In my _Nuxt_ `v2.15.8` project I tried to update `@nuxtjs/tailwindcss` `v5.0.0` and I got exact error.
If I remember correctly the error was thrown because for some reason `_layers` (`nuxt.options._layers`) is `undefined` 🤔
