### ISSUE TITLE
Nuxi crashes on changes - pointer being freed was not allocated

### ISSUE THREAD

**Issue by SeyyedKhandon** [nuxt/nuxt#25115]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.6.5
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.21
- Builder:          vite
- User Config:      ssr, hooks, css, serverHandlers, runtimeConfig, nitro, vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------
OS:
MACos Sonoma Version 14.1.2 (23B92)

NVM:
0.39.7

### Reproduction

I dont know where is the issue coming from to make the reprex for it( the current project is a very big one)

### Describe the bug

I ran into this issue regularly on nuxt 3 (nuxi), whenever I change some lines of the backend api code to update or change some part of the api, nuxi tries to re-render everything, but sometimes it crashes with errors like below(especially when I am in the middle of  change a piece of code and there is syntax error), and sometimes it just gets closed silently without any errors!

```
node(56577,0x171ba7000) malloc: *** error for object 0x1058e96c8: pointer being freed was not allocated
node(56577,0x171ba7000) malloc: *** set a breakpoint in malloc_error_break to debug
✨  Done in 74.81s.
```

**Comment by SeyyedKhandon** [comment]
> Would you be able to provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏
> 
> More info

It's not possible for me, I mentioned that in the issue, let's see if anyone has any idea on this problem or not,

**Comment by ffixitt** [comment]
I am also experiencing the same problem. Trying to edit the .env file and getting an error.

Nuxt version: 3.10.1
Operating System: Testing on Windows NT & MacOS Sonoma 14.3
Node version: Testing on 18.19.0 & 20.11.0

``` 
From MacOS:

ERROR  [unhandledRejection] connect ECONNREFUSED 127.0.0.1:54689                                                                                          
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
```

```
From Windows

ERROR  [unhandledRejection] kill ENOSYS 

  at ChildProcess.kill (node:internal/child_process:509:13)
  at kill (/C:/Users/user/Documents/Code/website/node_modules/nuxi/dist/chunks/dev.mjs:247:17)
  at restart (/C:/Users/user/Documents/Code/website/node_modules/nuxi/dist/chunks/dev.mjs:252:5)
  at ChildProcess.<anonymous> (/C:/Users/user/Documents/Code/website/node_modules/nuxi/dist/chunks/dev.mjs:281:9)
  at ChildProcess.emit (node:events:518:28)
  at emit (node:internal/child_process:951:14)
  at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by muffe** [comment]
Same for me, regularly crashes when changing "backend" code.

The actual crash changes from time to time, but it's mostly

```
node(89784,0x16d41f000) malloc: *** error for object 0x10a54cb18: pointer being freed was not allocated
node(89784,0x16d41f000) malloc: *** set a breakpoint in malloc_error_break to debug

 ERROR  [unhandledRejection] connect ECONNREFUSED 127.0.0.1:64120                                                                                                                                                                                                                                                                4:12:17 PM

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16)
  ```
  
  
macOS  14.3.1
node 20.11.0

**Comment by geminigeek** [comment]
Having similar issue , any time i modify files in module folder  and save file, here is the error i am getting 

```
 ERROR  [unhandledRejection] kill ENOSYS                                                                                                                   12:39:36 am

  at ChildProcess.kill (node:internal/child_process:509:13)
  at kill (/F:/node-local/nuxt-apps/nuxt-starter/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:246:17)
  at restart (/F:/node-local/nuxt-apps/nuxt-starter/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:251:5)
  at ChildProcess.<anonymous> (/F:/node-local/nuxt-apps/nuxt-starter/node_modules/.pnpm/nuxi@3.10.1/node_modules/nuxi/dist/chunks/dev.mjs:280:9)
  at ChildProcess.emit (node:events:514:28)
  at emit (node:internal/child_process:951:14)
  at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Nuxt 3.10.2 with Nitro 2.8.1
Windows 10
Node v20.10.0

**Comment by danielroe** [comment]
Closing as there is no reproduction and I have not encountered it.
