### ISSUE TITLE
Internal server error: Soft-invalidated module @upstash/redis

### ISSUE THREAD

**Issue by Vap0r1ze** [nuxt/nuxt#25186]
### Environment

```
Operating System: Windows_NT
Node Version:     v18.15.0
Nuxt Version:     3.9.1
CLI Version:      3.10.0
Nitro Version:    2.8.1
Package Manager:  pnpm@8.7.5
Builder:          -
User Config:      devtools, routeRules, build, nitro, imports, modules, svgo
Runtime Modules:  @sidebase/nuxt-auth@0.6.3, nuxt-svgo@4.0.0
Build Modules:    -
```

### Reproduction

https://stackblitz.com/edit/github-cmbjzh

### Describe the bug

When I try to use `@upstash/redis` serverside I get either of these two errors:
```
 ERROR  RollupError: Could not resolve "./chunk-UF7VY2SH.js" from "./chunk-UF7VY2SH.js?commonjs-external"     
```
```
[1:35:27 AM]  ERROR  Internal server error: Internal server error: Soft-invalidated module "/node_modules/.pnpm/nuxt@3.9.1_@planetscale+database@1.13.0_@upstash+redis@1.28.0_sass@1.69.7_typescript@5.3.3_vite@5.0.11/node_modules/nuxt/dist/app/entry.js" should not have existing transform result
      at handleModuleSoftInvalidation (file:///C:/Users/super/GitHub/PlatformerList/node_modules/.pnpm/vite@5.0.11_sass@1.69.7/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49828:15)
      at doTransform (file:///C:/Users/super/GitHub/PlatformerList/node_modules/.pnpm/vite@5.0.11_sass@1.69.7/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49635:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async viteTransformMiddleware (file:///C:/Users/super/GitHub/PlatformerList/node_modules/.pnpm/vite@5.0.11_sass@1.69.7/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:59342:32)
```

### Additional context

Halfway thru writing this I thought about adding `'@upstash/redis'` to `build.transpile[]` in nuxt config. This fixes the issue but I still think the error message is very cryptic

**Comment by ogzhanolguncu** [comment]
We fixed that issue yesterday here: https://github.com/upstash/upstash-redis/pull/825. You can use v1.28.1 safely.

**Comment by leosin** [comment]
![image](https://github.com/nuxt/nuxt/assets/3676670/5be31aa6-d392-4115-b866-f1e2b7144ab8)
I have a hard time catching the moment when he appears, it usually appears when I refresh the page at some point.

**Comment by Vap0r1ze** [comment]
> We fixed that issue yesterday, here: https://github.com/upstash/upstash-redis/pull/825. You can use v1.28.1 safely.

Oh that's so interesting tho know the real cause of the issue, TYSM!

**Comment by manniL** [comment]
Closing here then 👍
