### ISSUE TITLE
How should I add test to my application?

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#25203]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      app, modules, css, ui, nitro, content, colorMode, fontMetrics, googleFonts, ogImage, site, linkChecker, routeRules, devtools
- Runtime Modules:  @nuxtjs/seo@2.0.0-rc.4, @nuxt/content@2.10.0, @nuxt/ui@2.12.0, @vueuse/nuxt@10.7.1, @nuxthq/studio@1.0.6, @nuxtjs/plausible@0.2.4, nuxt-payload-analyzer@0.1.4, @nuxtjs/fontaine@0.4.1, @nuxtjs/google-fonts@3.1.3
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/unjs/website/pull/242

### Describe the bug

Hello,

How should I add tests to my application?

Actually, I don't know if I should use `vitest` or `nuxt test`. Using `nuxt test`, nothing works and the error message is not helping me.

```
esteban@Esteban-PC:~/dev/unjs/website$ nr test

> website@ test /home/esteban/dev/unjs/website
> nuxt test


[10:44:12 PM]  WARN   Vitest  "deps.inline" is deprecated. If you rely on vite-node directly, use "server.deps.inline" instead. Otherwise, consider using "deps.optimizer.ssr.include"

 RUN  v1.2.0 /home/esteban/dev/unjs/website                                                                                                              10:44:12 PM
[warn] Export "useSiteConfig" of module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/useSiteConfig.mjs" was reexported through module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/routes/blog/rss.xml.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
[warn] Export "useSiteConfig" of module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/useSiteConfig.mjs" was reexported through module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/routes/build/rss.xml.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
[warn] Export "useSiteConfig" of module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/useSiteConfig.mjs" was reexported through module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/routes/explore/rss.xml.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
[warn] Export "useSiteConfig" of module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/useSiteConfig.mjs" was reexported through module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/routes/learn/rss.xml.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
[warn] Export "useSiteConfig" of module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/useSiteConfig.mjs" was reexported through module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/routes/rss.xml.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
[warn] [Vue warn]: Component /home/esteban/dev/unjs/website/pages/packages/[...slug].vue is missing template or render function.
[error] [nuxt] [request error] [fatal] [404] Page not found
  at createError (./node_modules/.pnpm/h3@1.10.0/node_modules/h3/dist/index.mjs:78:15)  
  at createError (./.nuxt/test/kekcjg/prerender/chunks/app/server.mjs:886:21)  
  at setup (./.nuxt/test/kekcjg/prerender/chunks/app/_nuxt/_...slug_-4rySAfXW.mjs:95:13)
[warn] [Vue warn]: Component /home/esteban/dev/unjs/website/error.vue is missing template or render function.
[warn] [Vue warn]: Component /home/esteban/dev/unjs/website/pages/packages/[...slug].vue is missing template or render function.
[error] [nuxt] [request error] [fatal] [404] Page not found
  at createError (./node_modules/.pnpm/h3@1.10.0/node_modules/h3/dist/index.mjs:78:15)  
  at createError (./.nuxt/test/kekcjg/prerender/chunks/app/server.mjs:886:21)  
  at setup (./.nuxt/test/kekcjg/prerender/chunks/app/_nuxt/_...slug_-4rySAfXW.mjs:95:13)  
  at runNextTicks (node:internal/process/task_queues:60:5)  
  at process.processImmediate (node:internal/timers:447:9)
[warn] [Vue warn]: Component /home/esteban/dev/unjs/website/error.vue is missing template or render function.
[warn] [Vue warn]: Component /home/esteban/dev/unjs/website/pages/packages/[...slug].vue is missing template or render function.
[error] [nuxt] [request error] [fatal] [404] Page not found
  at createError (./node_modules/.pnpm/h3@1.10.0/node_modules/h3/dist/index.mjs:78:15)  
  at createError (./.nuxt/test/kekcjg/prerender/chunks/app/server.mjs:886:21)  
  at setup (./.nuxt/test/kekcjg/prerender/chunks/app/_nuxt/_...slug_-4rySAfXW.mjs:95:13)  
  at runNextTicks (node:internal/process/task_queues:60:5)  
  at process.processImmediate (node:internal/timers:447:9)
[warn] [Vue warn]: Component /home/esteban/dev/unjs/website/error.vue is missing template or render function.
[warn] Export "useSiteConfig" of module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/useSiteConfig.mjs" was reexported through module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/routes/blog/rss.xml.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
[warn] Export "useSiteConfig" of module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/useSiteConfig.mjs" was reexported through module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/routes/build/rss.xml.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
[warn] Export "useSiteConfig" of module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/useSiteConfig.mjs" was reexported through module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/routes/explore/rss.xml.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
[warn] Export "useSiteConfig" of module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/useSiteConfig.mjs" was reexported through module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/routes/learn/rss.xml.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
[warn] Export "useSiteConfig" of module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/useSiteConfig.mjs" was reexported through module "node_modules/.pnpm/nuxt-site-config@2.2.5_@nuxt+devtools@1.0.6_@vue+compiler-core@3.4.7_nuxt@3.9.1_postcss@8.4.3_hitc3fxvavx46tysjrrowojsza/node_modules/nuxt-site-config/dist/runtime/nitro/composables/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "server/routes/rss.xml.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '/home/esteban/dev/unjs/website/.nuxt/test/kekcjg/output/server/index.mjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.18.0
[error] 
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Error during global setup ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
[error] GetPortError: Timeout waiting for port 43441 after 20 retries with 500ms interval.
[error]  ❯ Module.waitForPort node_modules/.pnpm/get-port-please@3.1.1/node_modules/get-port-please/dist/index.mjs:341:9
[error]  ❯ Module.startServer node_modules/.pnpm/@nuxt+test-utils@3.9.0_@vue+test-utils@2.4.3_h3@1.10.0_happy-dom@13.1.0_vite@5.0.11_vitest@1._ah3pmr6rmvxwhwmgm7yxmrreva/node_modules/@nuxt/test-utils/dist/shared/test-utils.B1uaYm8K.mjs:111:5
[error]     110|     await ctx.serverProcess.kill();
    111|   }
    112| }
       | ^
    113| function fetch(path, options) {
    114|   return fetch$1(url(path), options);
[error]  ❯ Object.setup2 [as setup] node_modules/.pnpm/@nuxt+test-utils@3.9.0_@vue+test-utils@2.4.3_h3@1.10.0_happy-dom@13.1.0_vite@5.0.11_vitest@1._ah3pmr6rmvxwhwmgm7yxmrreva/node_modules/@nuxt/test-utils/dist/e2e.mjs:186:7
[error]  ❯ Object.setup node_modules/.pnpm/@nuxt+test-utils@3.9.0_@vue+test-utils@2.4.3_h3@1.10.0_happy-dom@13.1.0_vite@5.0.11_vitest@1._ah3pmr6rmvxwhwmgm7yxmrreva/node_modules/@nuxt/test-utils/dist/runtime/global-setup.mjs:10:3
[error]  ❯ runTests node_modules/.pnpm/@nuxt+test-utils@3.9.0_@vue+test-utils@2.4.3_h3@1.10.0_happy-dom@13.1.0_vite@5.0.11_vitest@1._ah3pmr6rmvxwhwmgm7yxmrreva/node_modules/@nuxt/test-utils/dist/e2e.mjs:208:21
[error]  ❯ Object.run node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/chunks/test.mjs:34:5
[error]  ❯ runCommand$1 node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1648:16
[error]  ❯ runCommand$1 node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1639:11
[error]  ❯ runMain$1 node_modules/.pnpm/nuxi@3.10.0/node_modules/nuxi/dist/shared/nuxi.4fde776c.mjs:1773:7
[error]
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by Barbapapazes** [comment]
It seems that the module is looking for the server but actually, the app is prerendered using `static: true` in the config.

**Comment by Barbapapazes** [comment]
Evan without the `static: true`, it fails
