### ISSUE TITLE
Deployment on AWS amplify failed

### ISSUE THREAD

**Issue by KingAdeCode** [nuxt/nuxt#25205]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.5.0
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.7.2
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      spaLoadingTemplate, devtools, ssr, runtimeConfig, app, routeRules, modules, build, css, postcss, vite
- Runtime Modules:  @pinia/nuxt@0.4.11
- Build Modules:    -
------------------------------

### Reproduction

This can only be reproduced through AWS amplify deployment, the app works fine when SSR is false, but returns "[500] Cannot read properties of null (reading 'data')" when SSR is true. 

I updated the local development Node.js to v 20.5.0 and the issue was solved, but AWS amplify does not support Node v 20 or new version yet,

### Here is the log from the AWS amplify when the node js version was changed to v 21 in the build settings

``` # Starting phase: preBuild
                                 # Executing command: nvm install 21
2024-01-15T02:28:02.321Z [INFO]: Downloading and installing node v21.5.0...
2024-01-15T02:28:02.472Z [WARNING]: Downloading https://nodejs.org/dist/v21.5.0/node-v21.5.0-linux-x64.tar.gz...
2024-01-15T02:28:02.588Z [WARNING]: ###########################
2024-01-15T02:28:02.589Z [WARNING]: 37.8%
2024-01-15T02:28:02.666Z [WARNING]: ###########################
2024-01-15T02:28:02.666Z [WARNING]: ############################################# 100.0%
2024-01-15T02:28:02.686Z [WARNING]: Computing checksum with sha256sum
2024-01-15T02:28:02.805Z [WARNING]: Checksums matched!
2024-01-15T02:28:04.207Z [INFO]: Now using node v21.5.0 (npm v)
2024-01-15T02:28:04.234Z [INFO]: Installing default global packages from /root/.nvm/default-packages...
2024-01-15T02:28:04.234Z [INFO]: npm install -g --quiet yarn@1.22.0
2024-01-15T02:28:04.236Z [WARNING]: node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
                                    node: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by node)
                                    node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
2024-01-15T02:28:04.237Z [WARNING]: Failed installing default packages. Please check if your default-packages file or a package in it has problems!
2024-01-15T02:28:04.238Z [INFO]: # Executing command: nvm use 21
2024-01-15T02:28:04.706Z [INFO]: Now using node v21.5.0 (npm v)
2024-01-15T02:28:04.707Z [INFO]: # Executing command: corepack enable
2024-01-15T02:28:04.708Z [WARNING]: node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
                                    node: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by node)
                                    node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
2024-01-15T02:28:04.708Z [ERROR]: !!! Build failed
2024-01-15T02:28:04.709Z [INFO]: Please read more about Amplify Hosting's support for SSR frameworks to find if your build failure is related to an unsupported feature: https://docs.aws.amazon.com/amplify/latest/userguide/amplify-ssr-framework-support.html. You may also find this troubleshooting guide useful: https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-ssr-deployment.html
2024-01-15T02:28:04.709Z [ERROR]: !!! Non-Zero Exit Code detected
2024-01-15T02:28:04.709Z [INFO]: # Starting environment caching...
2024-01-15T02:28:04.709Z [INFO]: # Environment caching completed
Terminating logging...```

### Describe the bug

This issue is related to aws amplify deployment, the deployment was successful, but because the homepage depends on the data from a backend app, the "[500] Cannot read properties of null (reading 'data')"  error is causing the page not to load correcly, therefore showing only black screen

### Default build settings is used

```version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm use 18
        - corepack enable
        - npx --yes nypm i
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .amplify-hosting
    files:
      - '**/*'
```

### Log from AWS cloudwatch for the SSR deployment

```INIT_START Runtime Version: nodejs:18.v19	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:5f3775e8514c9422c179089d8c93b55a6d1df5a60e7e37e1e2ae46daf845be72
--
LOGS	Name: bootstrap	State: Subscribed	Types: [Platform, Function]
Listening on http://localhost:3000 (AWS Amplify Hosting)
START RequestId: ffc68552-a445-4508-9f90-aa348f807f80 Version: $LATEST
[nuxt] [request error] [unhandled] [500] Cannot read properties of null (reading 'data')
at ./chunks/app/_nuxt/Index-ce7e9a40.mjs:915:42
at renderFnWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:399:13)
at ssrRenderSlotInner (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:118:17)
at ssrRenderSlot (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:100:3)
at _sfc_ssrRender$5 (./chunks/app/_nuxt/Index-ce7e9a40.mjs:518:3)
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:437:9)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:383:12)
at ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:91:10)
at ./chunks/app/_nuxt/Index-ce7e9a40.mjs:583:15
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:437:9)
file:///var/task/chunks/app/_nuxt/index-3d1b083e.mjs:619
items: unref(homeContent).data.just_landed
^
TypeError: Cannot read properties of null (reading 'data')
at file:///var/task/chunks/app/_nuxt/index-3d1b083e.mjs:619:34
at renderComponentSubTree (/var/task/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:437:9)
at /var/task/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:381:25
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Node.js v18.18.2
RequestId: ffc68552-a445-4508-9f90-aa348f807f80 Error: Runtime exited with error: exit status 1Runtime.ExitError
REPORT RequestId: ffc68552-a445-4508-9f90-aa348f807f80	Duration: 607.82 ms	Billed Duration: 608 ms	Memory Size: 1024 MB	Max Memory Used: 101 MB	Init Duration: 237.06 ms```

### Additional context

_No response_

### Logs

_No response_

**Comment by danielroe** [comment]
This doesn't seem to be a Nuxt issue. Check you have a single version of vue installed in your project. If there's something amplify-specific, see if you can reproduce with just Nitro and raise an issue on https://github.com/unjs/nitro.

**Comment by 1nusah** [comment]
hi, are you using this in your nuxt.config file? 
````
 nitro:{
    preset:'aws-amplify'
  }
````. Which kind of data is being provided by your backend API?
