### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by daniser** [nuxt/nuxt#25261]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.11.0
- Nuxt Version:     3.9.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

I couldn't reproduce this issue in the sandbox so I suppose this problem exists only on Windows platform.
To reproduce you only need fresh Nuxt installation:
```sh
npx nuxi@latest init whatever --packageManager yarn
cd <full path to project using small drive letter>
yarn install
yarn build
```

### Describe the bug

Fresh Nuxt installation fails during build on Windows.

### Logs

```shell-script
Nuxt 3.9.2 with Nitro 2.8.1                                                                                                                           15:51:37
i Building client...                                                                                                                                  15:51:57
i vite v5.0.11 building for production...                                                                                                             15:51:57
i ✓ 31 modules transformed.                                                                                                                           15:51:58
transforming (104) node_modules\nuxt\dist\app\utils.jsInspect report generated at D:/OSPanel/domains/whatever/.nuxt/analyze/.vite-inspect

 ERROR  [nuxt:components:imports] path should be a path.relative()d string, but got "d:/OSPanel/domains/whatever/vite/preload-helper.js"              15:51:59
file: vite/preload-helper.js


 ERROR  Nuxt Build Error: path should be a path.relative()d string, but got "d:/OSPanel/domains/whatever/vite/preload-helper.js"                      15:51:59

  at throwError (node_modules\ignore\index.js:379:9)
  at checkPath (node_modules\ignore\index.js:398:12)
  at Ignore._test (node_modules\ignore\index.js:519:5)
  at Ignore.ignores (node_modules\ignore\index.js:564:17)
  at isIgnored (/d:/OSPanel/domains/whatever/node_modules/@nuxt/kit/dist/index.mjs:2274:42)
  at Object.transformInclude (/d:/OSPanel/domains/whatever/node_modules/nuxt/dist/index.mjs:1770:115)
  at plugin.transform (/d:/OSPanel/domains/whatever/node_modules/unplugin/dist/index.mjs:1408:46)
  at /D:/OSPanel/domains/whatever/node_modules/vite-plugin-inspect/dist/index.mjs:376:26
  at plugin.<computed> (/D:/OSPanel/domains/whatever/node_modules/vite-plugin-inspect/dist/index.mjs:363:14)
  at /D:/OSPanel/domains/whatever/node_modules/rollup/dist/es/shared/node-entry.js:18670:40

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chriscant** [comment]
Hello. Did you make any progress with this?

I've had this on my Windows setup for around the same time. Very very weirdly I can usually clear it by doing "git init" in a new directory elsewhere.  I've tried `npx nuxi cleanup` etc with no joy.  It affects my three nuxt3 developments occasionally. I think things are OK apart from that, but not absolutely sure. Would be good to get to the bottom of this.

As shown above, it's in the vite building client phase. Normally lots of modules are transformed but much fewer are shown when the problem occurs. The error is shown because the pathname received by isIgnored() is just a filename (and also has a \0 character at the start) when I think it is normally a full path.  isIgnored() is called in createUnplugin()

```
    transformInclude(id) {
      id = normalize(id);
      return id.startsWith("virtual:") || id.startsWith("\0virtual:") || id.startsWith(nuxt.options.buildDir) || !isIgnored(id);
    },
```

**Comment by daniser** [comment]
@chriscant downgrading `node-ignore` worked for me. Add this entry into your `package.json`:
```json
"resolutions": {
  "ignore": "4.0.6"
},
```
As alternative, try using case-sensitive current path (including capital drive letter). It makes sense in Unix-like systems, but not in Windows.

**Comment by chriscant** [comment]
Thanks very much. I'm using npm so adding this to package.json seems to fix the problem, although one of the eventual build "You can now deploy" message had an un-normalised path:

```
  "overrides": {
    "ignore": "4.0.6"
  }
```

**Comment by howbizarre** [comment]
I have the same issue, but when disabling nuxt devtools, all goes to normal.

```typescript
//nuxt.config.ts

export default defineNuxtConfig({
  devtools: { enabled: false }
});
```
