### ISSUE TITLE
Error: Cannot find module './shared/untyped.<hash>.cjs' when using custom modules

### ISSUE THREAD

**Issue by mcrapts** [nuxt/nuxt#25343]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      devtools, modules
- Runtime Modules:  ./modules/example
- Build Modules:    -
------------------------------
```

### Reproduction

Stackblitz: https://stackblitz.com/edit/github-rgbq7w?file=nuxt.config.ts,modules%2Fexample%2Findex.ts

1. Create new Nuxt project with Nuxt 3.9.3
2. Create a module with the following contents: `modules/example/index.ts`

```
import { defineNuxtModule, createResolver } from "@nuxt/kit";

export default defineNuxtModule({
  setup() {
    console.log('hi')
  },
});
```
3. Add the module to `nuxt.config.ts`:

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['./modules/example']
})
```
4. Run `npx nuxi prepare` or `npm install` and observe the following error:

```
> npx nuxi prepare

[7:02:43 PM]  ERROR  Error while requiring module ./modules/example: Error: Cannot find module './shared/untyped.a47b2336.cjs'
Require stack:
- /home/marco/projects/nuxt-test-bug/node_modules/untyped/dist/index.d.cts


 ERROR  Cannot find module './shared/untyped.a47b2336.cjs'                                                    7:02:43 PM
Require stack:
- /home/marco/projects/nuxt-test-bug/node_modules/untyped/dist/index.d.cts

  Require stack:
  - node_modules/untyped/dist/index.d.cts
  at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
  at Function.resolve (node:internal/modules/helpers:136:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:251148)
  at jiti (node_modules/jiti/dist/jiti.js:1:253746)
  at node_modules/untyped/dist/index.d.cts:1:1147
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at node_modules/@nuxt/kit/dist/index.mjs:4:16
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371) 



 ERROR  Cannot find module './shared/untyped.a47b2336.cjs'                                                    7:02:43 PM
Require stack:
- /home/marco/projects/nuxt-test-bug/node_modules/untyped/dist/index.d.cts
```

I can consistently reproduce the issue on my local machine and another dev machine (both running Ubuntu Linux). 

### Describe the bug

Unable to run `npm install` or `npx nuxi prepare` without fatal error with Nuxt 3.9.3.

### Additional context

Feels similar to this bug that was previously fixed, though I have no evidence: https://github.com/nuxt/nuxt/issues/20883

**Comment by GMKR** [comment]
Looks like `untyped: 1.4.1` is causing this. 

Adding overrides for pnpm worked for me
```json
"overrides": {
  "untyped": "1.4.0"
},
```

**Comment by mcfarljw** [comment]
https://github.com/unjs/untyped/issues/123 for reference.

**Comment by j4v4d** [comment]
This should work: (add to your package.json)
```json
"resolutions": { "**/untyped": "1.4.0" }
```

**Comment by mcrapts** [comment]
This issue was indeed caused by https://github.com/unjs/untyped/issues/123, which is now resolved. Running `npx nuxi upgrade && npm i` now works without errors, so this issue can be closed.
