### ISSUE TITLE
Add Nuxt Kit helpers for `app.head`

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxt#25469]
### Describe the feature

Hello,

It could help modules authors to have helps for adding things to the head.

https://nuxt.com/docs/api/nuxt-config#head

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://nuxt.com/docs/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/nuxt/discussions) and [issues](https://github.com/nuxt/nuxt/issues).

**Comment by electrolinux** [comment]
Was exactly searching for such help today!

Using `nuxt@3.15.3, @nuxt/kit@3.15.3`

Here is what I want:
````ts
import { defineNuxtModule } from '@nuxt/kit'
import { defu } from 'defu'

// Module options TypeScript interface definition
export interface ModuleOptions {}

export default defineNuxtModule<ModuleOptions>({
  setup(_options, nuxt) {
    const families = [
      "inconsolata:400",
      "arsenal:400,400i,700,700i"
    ]

    const fontServer = "fonts.bunny.net"
    const fontQuery = `family=${families.join("|")}`

    const links = [
      {
        rel: 'preconnect',
        href: `https://${fontServer}`,
        crossorigin: 'true'
      },
      {
        rel: 'stylesheet',
        href: `https://${fontServer}/css?${fontQuery}`
      },
    ]

    nuxt.options.app.head.link = defu(
      links,
      nuxt.options.app.head?.link || []
    )
  },
})
````
I have some more links, all are working well if I comment the first link (with `rel: preconnect` and `crossorigin: true`).
Otherwise, here is what I get:

````bash
src/module.ts(104,5): error TS2322: Type 'Omit<({ rel: string; href: string; crossorigin: boolean; type?: undefined; } | { rel: string; href: string; crossorigin?: undefined; type?: undefined; } | { rel: string; type: string; href: string; crossorigin?: undefined; })[], number | ... 40 more ... | "with"> & Omit<...> & { ...; }' is not assignable to type '{ [x: `data-${string}`]: Stringable; as?: false | "object" | "style" | "script" | "audio" | "document" | "embed" | "fetch" | "font" | "image" | "track" | "video" | "worker" | null | undefined; ... 31 more ...; processTemplateParams?: false | undefined; }[] | undefined'.
  Type 'Omit<({ rel: string; href: string; crossorigin: boolean; type?: undefined; } | { rel: string; href: string; crossorigin?: undefined; type?: undefined; } | { rel: string; type: string; href: string; crossorigin?: undefined; })[], number | ... 40 more ... | "with"> & Omit<...> & { ...; }' is not assignable to type '{ [x: `data-${string}`]: Stringable; as?: false | "object" | "style" | "script" | "audio" | "document" | "embed" | "fetch" | "font" | "image" | "track" | "video" | "worker" | null | undefined; ... 31 more ...; processTemplateParams?: false | undefined; }[]'.
    Types of property 'pop' are incompatible.
      Type '(() => { [x: `data-${string}`]: Stringable; as?: false | "object" | "style" | "script" | "audio" | "document" | "embed" | "fetch" | "font" | "image" | "track" | "video" | "worker" | null | undefined; ... 31 more ...; processTemplateParams?: false | undefined; } | undefined) | (() => { ...; } | ... 2 more ... | undef...' is not assignable to type '() => { [x: `data-${string}`]: Stringable; as?: false | "object" | "style" | "script" | "audio" | "document" | "embed" | "fetch" | "font" | "image" | "track" | "video" | "worker" | null | undefined; ... 31 more ...; processTemplateParams?: false | undefined; } | undefined'.
        Type '() => { rel: string; href: string; crossorigin: boolean; type?: undefined; } | { rel: string; href: string; crossorigin?: undefined; type?: undefined; } | { rel: string; type: string; href: string; crossorigin?: undefined; } | undefined' is not assignable to type '() => { [x: `data-${string}`]: Stringable; as?: false | "object" | "style" | "script" | "audio" | "document" | "embed" | "fetch" | "font" | "image" | "track" | "video" | "worker" | null | undefined; ... 31 more ...; processTemplateParams?: false | undefined; } | undefined'.
          Type '{ rel: string; href: string; crossorigin: boolean; type?: undefined; } | { rel: string; href: string; crossorigin?: undefined; type?: undefined; } | { rel: string; type: string; href: string; crossorigin?: undefined; } | undefined' is not assignable to type '{ [x: `data-${string}`]: Stringable; as?: false | "object" | "style" | "script" | "audio" | "document" | "embed" | "fetch" | "font" | "image" | "track" | "video" | "worker" | null | undefined; ... 31 more ...; processTemplateParams?: false | undefined; } | undefined'.
            Type '{ rel: string; href: string; crossorigin: boolean; type?: undefined; }' is not assignable to type '{ [x: `data-${string}`]: Stringable; as?: false | "object" | "style" | "script" | "audio" | "document" | "embed" | "fetch" | "font" | "image" | "track" | "video" | "worker" | null | undefined; ... 31 more ...; processTemplateParams?: false | undefined; }'.
              Types of property 'crossorigin' are incompatible.
                Type 'boolean' is not assignable to type 'false | "" | "anonymous" | "use-credentials" | null | undefined'.


 ERROR  Failed to compile. Check the logs above.                                                                                                                                    23:40:50

    at error (node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Object.error (node_modules/rollup/dist/es/shared/node-entry.js:25351:20)
    at Object.error (node_modules/rollup/dist/es/shared/node-entry.js:24472:42)
    at generateDtsFromTs (node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1834:30)
    at Object.transform (node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1843:38)
    at node_modules/rollup/dist/es/shared/node-entry.js:25544:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
````

So yes, some help would be really appreciated 👍

**Comment by danielroe** [comment]
I think it would be a nice idea!
