### ISSUE TITLE
cloudflare_pages build error

### ISSUE THREAD

**Issue by saeedkgr** [nuxt/nuxt#25578]
### Environment

cloudflare pages

### Reproduction

nitro_preset='cloudflare-pages' pnpm run build

### Describe the bug

ℹ Building Nitro Server (preset: cloudflare-pages)                                                                                                                            nitro 9:46:51 PM   
(node-resolve plugin) Could not resolve import "unenv/runtime/node/string_decoder/index/" in D:\source\BP\webApps\app\node_modules\.pnpm\readable-stream@2.3.8\node_modules\readable-stream\lib\_stream_readable.js using exports defined in D:\source\BP\webApps\app\node_modules\.pnpm\unenv@1.9.0\node_modules\unenv\package.json.

[nitro 9:46:53 PM]  ERROR  Error: Cannot resolve "unenv/runtime/node/string_decoder/index/" from "D:\\source\\BP\\webApps\\app\\node_modules\\.pnpm\\readable-stream@2.3.8\\node_modules\\readable-stream\\lib\\_stream_readable.js" and externals are not allowed!

undefined

[9:46:53 PM]  ERROR  Cannot resolve "unenv/runtime/node/string_decoder/index/" from "D:\\source\\BP\\webApps\\app\\node_modules\\.pnpm\\readable-stream@2.3.8\\node_modules\\readable-stream\\lib\\_stream_readable.js" and externals are not allowed!

  at Object.resolveId (/D:/source/BP/webApps/app/node_modules/.pnpm/nitropack@2.8.1/node_modules/nitropack/dist/shared/nitro.4ea992bc.mjs:1973:17)
  at async PluginDriver.hookFirstAndGetPlugin (/D:/source/BP/webApps/app/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:18592:28)
  at async resolveId (/D:/source/BP/webApps/app/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:17261:26)
  at async ModuleLoader.resolveId (/D:/source/BP/webApps/app/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:17675:15)
  at async PluginDriver.hookFirstAndGetPlugin (/D:/source/BP/webApps/app/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:18592:28)
  at async resolveId (/D:/source/BP/webApps/app/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:17261:26)
  at async ModuleLoader.resolveId (/D:/source/BP/webApps/app/node_modules/.pnpm/rollup@4.9.6/node_modules/rollup/dist/es/shared/node-entry.js:17675:15)
  at async /D:/source/BP/webApps/app/node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.9.6/node_modules/@rollup/plugin-commonjs/dist/es/index.js:785:16
  at async Promise.all (index 11)
  at async /D:/source/BP/webApps/app/node_modules/.pnpm/@rollup+plugin-commonjs@25.0.7_rollup@4.9.6/node_modules/@rollup/plugin-commonjs/dist/es/index.js:777:32

[9:46:53 PM]  ERROR  Cannot resolve "unenv/runtime/node/string_decoder/index/" from "D:\\source\\BP\\webApps\\app\\node_modules\\.pnpm\\readable-stream@2.3.8\\node_modules\\readable-stream\\lib\\_stream_readable.js" and externals are not allowed!

 ELIFECYCLE  Command failed with exit code 1.

**Comment by saeedkgr** [comment]
- Node Version:     v20.9.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      ssr, imports, generate, nitro, css, extends, app, runtimeConfig, vite, devtools, typescript, experimental
- Runtime Modules:  -

**Comment by pi0** [comment]
Please followup via https://github.com/unjs/nitro/issues/1821
