### ISSUE TITLE
Fatal Error : TypeError: arr.at is not a function while running nuxt build 

### ISSUE THREAD

**Issue by SiddhantSharma575** [nuxt/nuxt#25671]
Node js : 14
nuxt : 2.14.6

 [webpackbar] ℹ Compiling Client

 FATAL  arr.at is not a function
 
   at last (node_modules/webpackbar/dist/index.cjs:29:31)
   at removeBefore (node_modules/webpackbar/dist/index.cjs:45:10)
   at parseRequest (node_modules/webpackbar/dist/index.cjs:100:22)
   at WebpackBarPlugin.updateProgress (node_modules/webpackbar/dist/index.cjs:639:16)
   at WebpackBarPlugin.handler (node_modules/webpackbar/dist/index.cjs:511:12)
   at node_modules/webpack/lib/ProgressPlugin.js:176:5
   at SyncHook.eval [as call] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
   at SyncHook.lazyCompileHook (node_modules/tapable/lib/Hook.js:154:20)
   at Compiler.newCompilation (node_modules/webpack/lib/Compiler.js:631:26)
   at node_modules/webpack/lib/Compiler.js:667:29
   at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
   at AsyncSeriesHook.lazyCompileHook (node_modules/tapable/lib/Hook.js:154:20)
   at Compiler.compile (node_modules/webpack/lib/Compiler.js:662:28)
   at node_modules/webpack/lib/Compiler.js:321:11
   at Compiler.readRecords (node_modules/webpack/lib/Compiler.js:529:11)
   at node_modules/webpack/lib/Compiler.js:318:10
   at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
   at AsyncSeriesHook.lazyCompileHook (node_modules/tapable/lib/Hook.js:154:20)
   at node_modules/webpack/lib/Compiler.js:315:19
   at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
   at AsyncSeriesHook.lazyCompileHook (node_modules/tapable/lib/Hook.js:154:20)
   at Compiler.run (node_modules/webpack/lib/Compiler.js:312:24)
   at node_modules/pify/index.js:33:11
   at new Promise (<anonymous>)
   at Compiler.<anonymous> (node_modules/pify/index.js:6:9)
   at Object.apply (node_modules/pify/index.js:85:19)
   at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:1866:34)
 
 
    ╭─────────────────────────────────────────╮
    │                                         │
    │   ✖ Nuxt Fatal Error                    │
    │                                         │
    │   TypeError: arr.at is not a function   │
    │                                         │
    ╰─────────────────────────────────────────╯
 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the project@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-02-06T13_31_58_705Z-debug.log

**Comment by valenman** [comment]
same error.

**Comment by valenman** [comment]
I solved my problem by updating the node version to 20.11.0
and updating some packages
```
{
"devDependencies": {
"eslint": "^7.32.0",
"eslint-loader": "^4.0.2"
"node-sass": "^9.0.0",
"sass-loader": "^10.1.1"
}
}
```
next left in the current version
`"nuxt": "^2.15.8",`

**Comment by danielroe** [comment]
The issue here is your Node version. The bundler for the latest version of `webpackbar` likely produced this code as it was deemed safe. `Array.at()` should be supported [from Node 16.6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at) which is already EOL.
