### ISSUE TITLE
Vite rejecting node:buffer polyfill 

### ISSUE THREAD

**Issue by mullet627** [nuxt/nuxt#25814]
### Environment

```
------------------------------
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      app, build, colorMode, css, devtools, experimental, modules, nitro, runtimeConfig, typescript, content, image, supabase
- Runtime Modules:  @nuxt/content@2.12.0, @nuxt/image@1.3.0, @nuxt/ui@2.13.0, @nuxtjs/supabase@1.1.6, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, vue-debug-queryparam/nuxt, @samk-dev/nuxt-vcalendar@1.0.2
- Build Modules:    -
```

### Reproduction

https://stackblitz.com/edit/github-w9dwvt?file=app.vue

### Describe the bug

Vite complains when we try to import the node buffer polyfill. Is there some other way that this is supposed to be imported? 

```
__vite-browser-external:node:buffer:3 Uncaught Error: Module "node:buffer" has been externalized for browser compatibility. Cannot access "node:buffer.Buffer" in client code.  See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
    at Object.get (__vite-browser-external:node:buffer:3:11)
    at app.vue:6:38
get @ __vite-browser-external:node:buffer:3
(anonymous) @ app.vue:6
```

**Comment by manniL** [comment]
Try https://nuxt.com/blog/v3-10#client-side-nodejs-support

**Comment by cco3** [comment]
> I don't think it'll work in a Vue component directly

It's the same error if you use it in `utils/myutil.ts`.

**Comment by Jorgagu** [comment]
@danielroe this issue seems fixed by #25028 with this test https://github.com/nuxt/nuxt/blob/5d67c9ed9/test/basic.test.ts#L2721-L2726 and this page https://github.com/nuxt/nuxt/blob/5d67c9ed9/test/fixtures/basic/app/pages/experimental/node-compat.vue

**Comment by danielroe** [comment]
nuxtathon closed @Jorgagu
