### ISSUE TITLE
edge-case: `app.buildAssetsDir` is set to `_` will cause prerendered to fail

### ISSUE THREAD

**Issue by kecrily** [nuxt/nuxt#26179]
### Environment

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.10.3
- CLI Version:      3.10.1
- Nitro Version:    2.9.2
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      app, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

<https://stackblitz.com/edit/github-hgwijm?file=nuxt.config.ts>

### Describe the bug

When `app.buildAssetsDir` is set to `_` it will cause prerendered failures at `nuxi generate`.

### Logs

```shell-script
ℹ Initializing prerenderer                                     nitro 01:19:22
ℹ Prerendering 3 initial routes with crawler                   nitro 01:19:22
  ├─ /200.html (55ms)                                           nitro 01:19:22
  ├─ /404.html (55ms)                                           nitro 01:19:22
  ├─ / (56ms)                                                   nitro 01:19:22
  ├─ /_payload.json (1ms)                                       nitro 01:19:22
  │ ├── Error: [404] Cannot find static asset /_payload.json
  │ └── Linked from /
                                                                nitro 01:19:22
Errors prerendering:
  ├─ /_payload.json (1ms)                                       nitro 01:19:22
  │ ├── Error: [404] Cannot find static asset /_payload.json
  │ └── Linked from /
                                                                nitro 01:19:22

 ERROR  Exiting due to prerender errors.                              01:19:22

  at Module.prerender (node_modules/nitropack/dist/chunks/prerender.mjs:232:11)
  at async eval (node_modules/nuxt/dist/index.mjs:3321:7)
  at async build (node_modules/nuxt/dist/index.mjs:4789:5)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:110:5)
  at async Object.run (node_modules/nuxi/dist/chunks/generate.mjs:71:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.a9f3bca7.mjs:1678:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.a9f3bca7.mjs:1669:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.a9f3bca7.mjs:1807:7) 



 ERROR  Exiting due to prerender errors.                              01:19:22

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by danielroe** [comment]
I suspect this is the same (upstream) issue as https://github.com/nuxt/nuxt/issues/24389. Let's track there.
