### ISSUE TITLE
Getting _import_meta_url_ is not defined error for a Nuxt 3.10.3 and nuxt content project deployed to AWS Lambda

### ISSUE THREAD

**Issue by anjali89r** [nuxt/nuxt#26170]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.10.3`
- CLI Version:      `3.10.1`
- Nitro Version:    `2.9.2`
- Package Manager:  `npm@10.2.4`
- Builder:          `-`
- User Config:      `devtools`, `modules`, `content`, `nitro`
- Runtime Modules:  `@nuxt/content@2.12.1`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-agpzne-qkcpqs?file=pages%2F%5B...slug%5D.vue

### Describe the bug

My project is a SSR application deployed to AWS Lambda. I'm adding a blog section to this app and used Nuxt Content in the document-driven mode. After adding the nuxt content to this project, when I deploy the application, I'm getting an internal server error and below is the error stack in the AWS Cloudwatch,
<img width="1090" alt="image" src="https://github.com/nuxt/nuxt/assets/30242582/9230e94a-06a3-4a9b-bf2a-de3125252f59">

`2024-03-10T04:04:37.099Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "ReferenceError",
    "errorMessage": "_import_meta_url_ is not defined",
    "stack": [
        "ReferenceError: _import_meta_url_ is not defined",
        "    at file:///var/task/index.mjs:1:65",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)",
        "    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)",
        "    at async _tryAwaitImport (file:///var/runtime/index.mjs:1008:16)",
        "    at async _tryRequire (file:///var/runtime/index.mjs:1057:86)",
        "    at async _loadUserApp (file:///var/runtime/index.mjs:1081:16)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
        "    at async start (file:///var/runtime/index.mjs:1282:23)",
        "    at async file:///var/runtime/index.mjs:1288:1"
    ]
}
`
When I remove the nuxt content from the project, it works as expected.  Also when I tried the nitro preset to the default node server, it worked fine.

### Additional context

Nuxt.config.ts,
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@nuxt/content'],
  content: {
    documentDriven: true,
  },
  nitro: {
    preset: 'aws-lambda',
    inlineDynamicImports: true,
  },
});

```

Nuxt build command for Deployment,

NUXT_PUBLIC_API_BASE=https://my-api.com NUXT_APP_CDN_URL=my-static-bucket-url npx nuxt build

**Comment by danielroe** [comment]
This is likely an upstream issue with Nitro.

cc: @pi0

**Comment by cfvargashz** [comment]
@anjali89r Disabling inlineDynamicimports within nuxt.config.js > nitro (`inlineDynamicImports: false`) works for me

**Comment by anjali89r** [comment]
@cfvargashz thanks for that. yes it works after disabling the inline dynamic imports

**Comment by danielroe** [comment]
if you can still hit this on the latest nitro with no workaround, please do open an issue at https://github.com/nitrojs/nitro/issues/new/choose 🙏
