### ISSUE TITLE
Error: [worker reload] [worker init] Context is not available  

### ISSUE THREAD

**Issue by fabianwohlfart** [nuxt/nuxt#26329]
### Environment

 Operating System: Darwin
- Node Version:     v18.19.0
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

To be honest I am not sure how to provide a minimal reproduction as this occurs in a Nitro Plugin that is provided by a layer for Nuxt…

```
export default defineNitroPlugin((nitroApp) => {})
```

### Describe the bug

Upgraded to 3.11 then this `Context is not available` error appeared

### Additional context

I think If I remove the console.logs it works??!!

### Logs

```shell-script
ERROR  [worker reload] [worker init] Context is not available                                                                                     09:27:29

  at Object.use (node_modules/unctx/dist/index.mjs:31:15)
  at <anonymous> (node_modules/nuxt/dist/core/runtime/nitro/dev-server-logs.js:14:30)
  at Object.log (node_modules/nuxt/dist/core/runtime/nitro/dev-server-logs.js:53:7)
  at Consola._log (node_modules/consola/dist/core.mjs:381:16)
  at resolveLog (node_modules/consola/dist/core.mjs:349:14)
  at Consola._logFn (node_modules/consola/dist/core.mjs:377:5)
  at console.log (node_modules/consola/dist/core.mjs:306:19)
  at <anonymous> (/[layer-pwd]/server/plugins/websiteStorage.js:17:1)
  at createNitroApp (node_modules/nitropack/dist/runtime/app.mjs:143:7)
  at <anonymous> (node_modules/nitropack/dist/runtime/app.mjs:151:25)
```

**Comment by morsellif** [comment]
A temporary fix could be using 

`
features: {
  devLogs: false
  // or 'silent' to allow you to handle yourself with `dev:ssr-logs` hook
}
`

as shown in [changelog](https://github.com/nuxt/nuxt/releases/tag/v3.11.0)

**Comment by thijsw** [comment]
This error also occurs when you try to start a Nuxt 3 project on Stackblitz: https://stackblitz.com/github/nuxt/starter/tree/v3

![Screenshot 2024-03-18 at 13 32 35](https://github.com/nuxt/nuxt/assets/28638/eea01178-8dca-45b0-81a0-449d12f98338)

**Comment by HigherOrderLogic** [comment]
This should have been fixed in https://github.com/nuxt/nuxt/commit/b3ced3d694c89344c8e77b804a2dc76434d27668.

**Comment by danielroe** [comment]
This is already fixed; it will be released in a patch release later today.
