### ISSUE TITLE
Nitro Plugin console issue

### ISSUE THREAD

**Issue by indam1** [nuxt/nuxt#26326]
### Environment

- Operating System: Windows_NT
- Node Version:     v20.11.1
- Nuxt Version:     3.11.0
- CLI Version:      3.10.1
- Nitro Version:    2.9.4
- Package Manager:  yarn@1.22.21
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/devbox/pedantic-shtern-y9xvt9

### Describe the bug

Console.log in defineNitroPlugin causes the error "Context is not available". Exists in development, but no errors in production

### Logs

```shell-script
ERROR [worker reload] [worker init] Context is not available                                                                                                                                                            
  at Object.use (/C:/Users/user/WebstormProjects/nuxt-advanced/node_modules/unctx/dist/index.mjs:31:15)
  at <anonymous> (node_modules\nuxt\dist\core\runtime\nitro\dev-server-logs.js:14:30)
  at Object.log (node_modules\nuxt\dist\core\runtime\nitro\dev-server-logs.js:53:7)
  at Consola._log (/C:/Users/user/WebstormProjects/nuxt-advanced/node_modules/consola/dist/core.mjs:381:16)
  at resolveLog (/C:/Users/user/WebstormProjects/nuxt-advanced/node_modules/consola/dist/core.mjs:349:14)
  at Consola._logFn (/C:/Users/user/WebstormProjects/nuxt-advanced/node_modules/consola/dist/core.mjs:377:5)
  at console.warn (/C:/Users/user/WebstormProjects/nuxt-advanced/node_modules/consola/dist/core.mjs:306:19)
  at <anonymous> (server\plugins\sentry.ts:8:1)
  at createNitroApp (node_modules\nitropack\dist\runtime\app.mjs:143:7)
  at <anonymous> (node_modules\nitropack\dist\runtime\app.mjs:151:25)
```

**Comment by danielroe** [comment]
This has been resolved in https://github.com/nuxt/nuxt/commit/b3ced3d694c89344c8e77b804a2dc76434d27668

For now you can work around by setting `features.devLogs` to false
