### ISSUE TITLE
Nuxt 3.11.0 doesn't work on StackBlitz

### ISSUE THREAD

**Issue by luca-smartpricing** [nuxt/nuxt#26347]
### Environment

Any

### Reproduction

https://stackblitz.com/github/nuxt/starter/tree/v3?file=package.json

### Describe the bug

Just click "Open on Stack Blitz" on this [nuxt docu page](https://nuxt.com/docs/getting-started/installation )

### Logs

```shell-script
ERROR  [nuxt] [request error] [unhandled] [500] Context is not available
  at Object.use (./node_modules/unctx/dist/index.mjs:50:15)  
  at eval (./.nuxt/dev/index.mjs:659:171)  
  at eval (./node_modules/hookable/dist/index.mjs:68:66)  
  at Object.run (./node_modules/hookable/dist/index.mjs:61:43)  
  at eval (./node_modules/hookable/dist/index.mjs:68:56)  
  at async eval (./.nuxt/dev/index.mjs:1317:3)  
  at async Object.eval (./.nuxt/dev/index.mjs:736:22)  
  at async eval (./node_modules/h3/dist/index.mjs:2087:19)  
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:91:16)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2374:7)


 ERROR  [h3] [unhandled] connect ECONNREFUSED 127.0.0.1:60261                         16:28:29

  at __node_internal_ (https://owaivommngithub-5k1x.w-credentialless-staticblitz.com/blitz.810981ba.js:36:5406)
  at __node_internal_ (https://owaivommngithub-5k1x.w-credentialless-staticblitz.com/blitz.810981ba.js:36:7078)
  at _0x261a5d.afterConnect [as oncomplete] (https://owaivommngithub-5k1x.w-credentialless-staticblitz.com/blitz.810981ba.js:55:18522)
  at https://owaivommngithub-5k1x.w-credentialless-staticblitz.com/blitz.810981ba.js:371:14070
  at _0x398360 (https://owaivommngithub-5k1x.w-credentialless-staticblitz.com/blitz.810981ba.js:352:154306)
  at https://owaivommngithub-5k1x.w-credentialless-staticblitz.com/blitz.810981ba.js:352:154055
```

**Comment by danielroe** [comment]
Thank you for reporting. This is resolved already and will be fixed in a patch release later today.

**Comment by luca-smartpricing** [comment]
Thank you!
