### ISSUE TITLE
DevTools broken in `3.11.1` - Error: write EPIPE, [500] Cannot read properties of undefined (reading 'on')

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#26418]
### Environment

Tested in 2 environments - **Stackblitz** and **locally** _(broken in both)_

Stackblitz environment:

````
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

Local environment:

````
------------------------------
- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  pnpm@8.1.0
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mgbfcn?file=nuxt.config.ts

### Describe the bug

I initialized a new Nuxt project using the latest version `3.11.1` and when I start the dev server with `pnpm run dev` and open the Nuxt DevTools by clicking on the DevTools button I get this error in my **local environment**:

````
 ERROR  [unhandledRejection] write EPIPE                                                                                                     9:10:51 AM

  at afterWriteDispatched (node:internal/stream_base_commons:160:15)
  at writeGeneric (node:internal/stream_base_commons:151:3)
  at Socket._writeGeneric (node:net:952:11)
  at Socket._write (node:net:964:8)
  at writeOrBuffer (node:internal/streams/writable:564:12)
  at _write (node:internal/streams/writable:493:10)
  at Writable.write (node:internal/streams/writable:502:10)
  at IncomingMessage.ondata (node:internal/streams/readable:1007:22)
  at IncomingMessage.emit (node:events:518:28)
  at addChunk (node:internal/streams/readable:559:12)


 ERROR  [unhandledRejection] read ECONNRESET                                                                                                 9:10:55 AM

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
````

And when running it on **Stackblitz** I get **_this_** error:

````
 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'on')
  at new BroadcastChannel (https://nuxtstartermgbfcn-d1og.w-credentialless-staticblitz.com/blitz.810981ba.js:65:5652)  
  at Module.initAppSeparateWindow (./node_modules/@vue/devtools-core/dist/index.js:711:19)  
  at eval (./node_modules/@nuxt/devtools/dist/runtime/vue-devtools/overlay.mjs:8:23)  
  at async ViteNodeRunner.runModule (./node_modules/vite-node/dist/client.mjs:379:5)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:363:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:206:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:250:12)  
  at async eval (./node_modules/nuxt/dist/app/entry.js:1:216)  
  at async ViteNodeRunner.runModule (./node_modules/vite-node/dist/client.mjs:379:5)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:363:5)
````

This is a completely fresh Nuxt 3.11 installation.

**Comment by martinszeltins** [comment]
It seems to be working for my colleagues on their computers but not  on mine. I have no idea why or even where to begin debugging this. 🤷🏻
