### ISSUE TITLE
Hello World example from doc not working

### ISSUE THREAD

**Issue by guska8** [nuxt/nuxt#26433]
### Environment

```
 Working directory: /home/projects/owaivrkzl.github
[11:24:56] Nuxt project info: 

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
```

### Reproduction

https://nuxt.com/docs/examples/hello-world

https://owaivrkzlgithub-mzhb--3000--810981ba.local.webcontainer.io

### Describe the bug

The project doesn't build.

![image](https://github.com/nuxt/nuxt/assets/25177050/70feebc5-28c4-42ba-9d1c-f84726ac1cb8)

### Additional context

I noticed the nuxt.config its not present

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'on')
  at new BroadcastChannel (https://owaivrkzlgithub-mzhb.w-staticblitz.com/blitz.810981ba.js:65:5652)  
  at Module.initAppSeparateWindow (./node_modules/@vue/devtools-core/dist/index.js:711:19)  
  at eval (./node_modules/@nuxt/devtools/dist/runtime/vue-devtools/overlay.mjs:8:23)  
  at async ViteNodeRunner.runModule (./node_modules/vite-node/dist/client.mjs:379:5)  
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:363:5)  
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:206:14)  
  at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:250:12)  
```
```

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/devtools/issues/629 - it's a devtools issue.
