### ISSUE TITLE
"joinRelativeURL" is not exported by "../../node_modules/ufo/dist/index.mjs", imported by "virtual:nuxt:C:/Users/MyPc/Workspace/my-project/apps/my-app/.nuxt/paths.mjs".

### ISSUE THREAD

**Issue by mklueh** [nuxt/nuxt#26440]
### Environment

Nuxt project info:                                                                                                                         6:51:46

------------------------------
- Operating System: Windows_NT
- Node Version:     v21.4.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.3
- Package Manager:  yarn@4.1.1
- Builder:          -
- User Config:      devtools, ssr, app, modules, turnstile, typescript, routeRules, gtag, nitro, image, runtimeConfig, sitemap, site, nuxtIcon, content, vite, experimental, fonts
- Runtime Modules:  @unocss/nuxt, @nuxt/content, @vueuse/nuxt@10.9.0, @nuxt/fonts, @nuxt/image@1.4.0, @nuxtjs/seo, nuxt-icon, nuxt-gtag, @nuxtjs/turnstile, @hebilicious/form-actions-nuxt

### Reproduction

Appeared after upgrading to 3.11.1

### Describe the bug

Build fails when running generate

### Logs

```shell-script
[6:48:18]  ERROR  Nuxt Build Error: "joinRelativeURL" is not exported by "../../node_modules/ufo/dist/index.mjs", imported by "virtual:nuxt:C:/Users/MyPc/Workspace/my-project/apps/my-app/.nuxt/paths.mjs".

  at error (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Module.error (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
  at Module.traceVariable (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
  at ModuleScope.findVariable (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
  at ReturnValueScope.findVariable (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
  at Identifier.bind (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
  at CallExpression.bind (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
  at CallExpression.bind (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
  at ArrowFunctionExpression.bind (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
  at VariableDeclarator.bind (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
  at VariableDeclaration.bind (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
  at ExportNamedDeclaration.bind (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:10673:27)
  at Program.bind (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
  at Module.bindReferences (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:13741:18)
  at Graph.sortModules (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:25853:20)
  at Graph.build (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:25737:14)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async /C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:26706:13
  at async catchUnfinishedHookActions (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
  at async rollupInternal (/C:/Users/MyPc/Workspace/my-project/node_modules/rollup/dist/es/shared/node-entry.js:26701:5)
  at async Module.build (/C:/Users/MyPc/Workspace/my-project/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-52909643.js:48079:18)
  at async buildClient (/C:/Users/MyPc/Workspace/my-project/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:565:5)
  at async bundle (/C:/Users/MyPc/Workspace/my-project/node_modules/@nuxt/vite-builder/dist/shared/vite-builder.20543d77.mjs:1442:3)
  at async bundle (/C:/Users/MyPc/Workspace/my-project/node_modules/nuxt/dist/index.mjs:5062:5)
  at async Promise.all (index 1)
  at async build (/C:/Users/MyPc/Workspace/my-project/node_modules/nuxt/dist/index.mjs:4937:5)
  at async Object.run (/C:/Users/MyPc/Workspace/my-project/node_modules/nuxi/dist/chunks/build.mjs:95:5)
  at async Object.run (/C:/Users/MyPc/Workspace/my-project/node_modules/nuxi/dist/chunks/generate.mjs:56:5)
  at async runCommand$1 (/C:/Users/MyPc/Workspace/my-project/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1648:16)
  at async runCommand$1 (/C:/Users/MyPc/Workspace/my-project/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1639:11)
  at async runMain$1 (/C:/Users/MyPc/Workspace/my-project/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1777:7)


```
```

**Comment by mklueh** [comment]
Seems to be gone after removing node_modules and yarn.lock and reinstalling the dependencies

**Comment by danielroe** [comment]
Yes, this just requires you have the latest version of ufo installed. It’s a package manager quirk, and is why we recommend refreshing your lockfile when upgrading
