### ISSUE TITLE
Cannot restart nuxt:  Cannot read properties of undefined (reading 'toast') 

### ISSUE THREAD

**Issue by jemdiggity** [nuxt/nuxt#26463]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      devtools, modules, toast
- Runtime Modules:  @nuxtjs/toast@3.3.1
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-7neyu1?file=nuxt.config.ts

### Describe the bug

`npm run dev` and the following error is displayed.

```
 ERROR  Cannot read properties of undefined (reading 'toast')                                                                                              11:31:02 AM

  at nuxtToast (node_modules/@nuxtjs/toast/index.js:4:72)
  at Module.installModule (node_modules/@nuxt/kit/dist/index.mjs:2499:101)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4188:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:4286:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2654:19)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:68:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1678:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1669:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1807:7) 
```

**Comment by Zihan-Hu** [comment]
`@nuxtjs/toast` don't support Nuxt 3 since it has been moved to https://github.com/nuxt-community/legacy-modules/tree/master/packages/toast

**Comment by jemdiggity** [comment]
Thanks.
