### ISSUE TITLE
__vite_ssr_import_0__.xxx is not a function

### ISSUE THREAD

**Issue by baixiaoyu2997** [nuxt/nuxt#26543]
### Environment

stackblitz

### Reproduction

https://stackblitz.com/edit/nuxt-starter-i3vypr?file=composables%2FuseContract.ts

### Describe the bug

can'n start dev server,  according to my tests, this problem is related to the `composables/useContract` function. It should be caused by the fact that useContract has the same name as the parameter in `sdk/util/common.ts`. When I try to delete `default` in `useContract` After that, this error will not occur. This may also be related to the logic of auto-import.

### Logs

```shell-script
500
__vite_ssr_import_0__.commonOwner is not a function

at ./sdk/ethereum/optionFactoryContract.ts:3:37
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ViteNodeRunner.runModule (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/vite-node@1.4.0_@types+node@18.19.17/node_modules/vite-node/dist/client.mjs:362:5)
at async ViteNodeRunner.directRequest (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/vite-node@1.4.0_@types+node@18.19.17/node_modules/vite-node/dist/client.mjs:346:5)
at async ViteNodeRunner.cachedRequest (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/vite-node@1.4.0_@types+node@18.19.17/node_modules/vite-node/dist/client.mjs:189:14)
at async ViteNodeRunner.dependencyRequest (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/vite-node@1.4.0_@types+node@18.19.17/node_modules/vite-node/dist/client.mjs:233:12)
at async ./store/wallet.ts:2:31
at async ViteNodeRunner.runModule (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/vite-node@1.4.0_@types+node@18.19.17/node_modules/vite-node/dist/client.mjs:362:5)
at async ViteNodeRunner.directRequest (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/vite-node@1.4.0_@types+node@18.19.17/node_modules/vite-node/dist/client.mjs:346:5)
at async ViteNodeRunner.cachedRequest (/Users/l.rain/Documents/workspace/deorderbook-monorepo/node_modules/.pnpm/vite-node@1.4.0_@types+node@18.19.17/node_modules/vite-node/dist/client.mjs:189:14)
```
```

**Comment by manniL** [comment]
Most likely https://github.com/unjs/unimport -related as you mentioned.

Could you try reproducing it with "just that library"? 🙏🏻

**Comment by baixiaoyu2997** [comment]
> stackblitz

seems like is bug from `unimport`, i created a issue: https://github.com/unplugin/unplugin-auto-import/issues/481

**Comment by Behaylu-Addisu** [comment]
I can't access my server the log error looks 


 ERROR [nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.gql is not a function
