### ISSUE TITLE
Post installation script fails when using bun for windows

### ISSUE THREAD

**Issue by lucashcl** [nuxt/nuxt#26618]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.7.1
- Nuxt Version:     -
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  unknown
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

When i try to create a new nuxt project with bun for windows, the nuxt post install script throws an error. More specifically "TTY initialization faild"

### Describe the bug

When i try to create a new nuxt project with bun for windows, the nuxt post install script throws an error. More specifically "TTY initialization failed"

### Logs

```shell-script
ERROR  TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)                           17:34:17

  at new WriteStream (node:tty:93:11)
  at sD.prompt (project_folder/node_modules/consola/dist/chunks/prompt.mjs:141:676)
  at confirm (project_folder/node_modules/consola/dist/chunks/prompt.mjs:251:6)
  at Module.prompt (project_folder/node_modules/consola/dist/chunks/prompt.mjs:404:18)
  at project_folder/node_modules/consola/dist/shared/consola.36c0034f.mjs:617:71
  at async ensureUserconsent (project_folder/node_modules/@nuxt/telemetry/dist/shared/telemetry.023ac76b.mjs:26:20)
  at async setup (project_folder/node_modules/@nuxt/telemetry/dist/module.mjs:363:74)
  at async normalizedModule (project_folder/node_modules/@nuxt/kit/dist/index.mjs:2112:17)
  at async installModule (project_folder/node_modules/@nuxt/kit/dist/index.mjs:2415:95)
  at async initNuxt (project_folder/node_modules/nuxt/dist/index.mjs:4171:7)
  at async loadNuxt (project_folder/node_modules/nuxt/dist/index.mjs:4269:5)
  at async loadNuxt (project_folder/node_modules/@nuxt/kit/dist/index.mjs:2570:19)
  at async Object.run (project_folder/node_modules/nuxi/dist/chunks/prepare.mjs:53:18)
  at async runCommand$1 (project_folder/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1648:16)
  at async runCommand$1 (project_folder/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1639:11)
  at async runMain$1 (project_folder/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1777:7)



 ERROR  TTY initialization failed: uv_tty_init returned EBADF (bad file descriptor)                           17:34:17

error: postinstall script from "nuxt-app" exited with 1

 ERROR  Error: Command failed with exit code 1: bun install
```

**Comment by danielroe** [comment]
This seems like a bug in Bun. Have you raised it there?
