### ISSUE TITLE
not found module @nuxt/kit when use yarn Plug'n'play

### ISSUE THREAD

**Issue by little3201** [nuxt/nuxt#26750]
### Environment

- Operating System: Darwin
- Node Version:     v20.10.0
- Nuxt Version:     ^3.11.2
- CLI Version:      3.11.1
- Nitro Version:    -
- Package Manager:  yarn@4.1.1
- Builder:          -
- User Config:      extends, modules, hooks, ui, routeRules, devtools
- Runtime Modules:  @nuxt/content@^2.12.1, @nuxt/ui, @nuxt/image@^1.5.0, @nuxt/fonts@^0.6.1, @vueuse/nuxt@^10.9.0
- Build Modules:    -

### Reproduction

https://codesandbox.io/p/devbox/objective-solomon-m5znvc?file=%2Fpackage.json%3A17%2C33

### Describe the bug

when use yarn install, there are some error:
`➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ esbuild@npm:0.20.2 must be built because it never has been before or the last one failed
➤ YN0007: │ vue-demi@npm:0.14.7 [43011] must be built because it never has been before or the last one failed
➤ YN0007: │ nuxt-app@workspace:. must be built because it never has been before or the last one failed
➤ YN0009: │ nuxt-app@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-7a862d72/build.log)
➤ YN0000: └ Completed in 4s 81ms
➤ YN0000: · Failed with errors in 15s 946ms
`

and after yarn dev , some like:

`
[7:06:12 AM]  ERROR  Cannot find module @nuxt/kit imported from file:///workspace, file:///, file:///workspace/_index.js, file:///node_modules
  at _resolve (/root/.yarn/berry/cache/nuxi-npm-3.11.1-ccaf35a862-10c0.zip/node_modules/nuxi/dist/shared/nuxi.1902c37d.mjs:8003:19)
  at resolveSync (/root/.yarn/berry/cache/nuxi-npm-3.11.1-ccaf35a862-10c0.zip/node_modules/nuxi/dist/shared/nuxi.1902c37d.mjs:8012:10)
  at resolvePathSync (/root/.yarn/berry/cache/nuxi-npm-3.11.1-ccaf35a862-10c0.zip/node_modules/nuxi/dist/shared/nuxi.1902c37d.mjs:8015:24)
  at resolvePath (/root/.yarn/berry/cache/nuxi-npm-3.11.1-ccaf35a862-10c0.zip/node_modules/nuxi/dist/shared/nuxi.1902c37d.mjs:8019:28)
  at importModule (/root/.yarn/berry/cache/nuxi-npm-3.11.1-ccaf35a862-10c0.zip/node_modules/nuxi/dist/shared/nuxi.1902c37d.mjs:8074:30)
  at loadKit (/root/.yarn/berry/cache/nuxi-npm-3.11.1-ccaf35a862-10c0.zip/node_modules/nuxi/dist/shared/nuxi.dc1b30dc.mjs:2410:21)
  at async Object.run (/root/.yarn/berry/cache/nuxi-npm-3.11.1-ccaf35a862-10c0.zip/node_modules/nuxi/dist/chunks/dev.mjs:167:32)
  at async runCommand$1 (/root/.yarn/berry/cache/nuxi-npm-3.11.1-ccaf35a862-10c0.zip/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1648:16)
  at async runCommand$1 (/root/.yarn/berry/cache/nuxi-npm-3.11.1-ccaf35a862-10c0.zip/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1639:11)
  at async runMain$1 (/root/.yarn/berry/cache/nuxi-npm-3.11.1-ccaf35a862-10c0.zip/node_modules/nuxi/dist/shared/nuxi.9edf0930.mjs:1777:7) 
`

**Comment by danielroe** [comment]
Let's track in https://github.com/nuxt/cli/issues/217.

You can see workarounds in https://github.com/nuxt/cli/issues/217#issuecomment-2084624223.

**Comment by carsonbird** [comment]
Same issue experienced here. Can't create any nuxt projects locally via yarn.

**Comment by mklueh** [comment]
Same
