### ISSUE TITLE
TypeError: fetch failed

### ISSUE THREAD

**Issue by ElYaiko** [nuxt/nuxt#26883]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.17.0`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `bun@1.1.4`
- Builder:          `-`
- User Config:      `devtools`, `alias`, `app`, `runtimeConfig`, `css`, `build`, `modules`, `experimental`, `features`, `vite`, `nitro`
- Runtime Modules:  `@pinia/nuxt@0.4.11`
- Build Modules:    `-`

### Reproduction

-

### Describe the bug

I have a $fetch that checks inside an api route a recaptcha response:

````
          const r = await $fetch<{
            success: boolean
            hostname?: string
            'error-codes'?: string[]
          }>('https://www.google.com/recaptcha/api/siteverify', {
            method: 'post',
            headers: {
              'Content-Type': 'application/x-www-form-urlencoded'
            },
            body: new URLSearchParams({
              secret: captchaKey.re,
              response: val
            })
          });
````

For some reason the build in my ssh server gets:

```
Api error: FetchError: [POST] "https://www.google.com/recaptcha/api/siteverify": <no response> fetch failed
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at r (file:///var/www/server/index.mjs:1:59455)
    ... 5 lines matching cause stack trace ...
    at Object.handler (file:///var/www/server/index.mjs:1:51201)
    at Server.<anonymous> (file:///var/www/server/index.mjs:1:54023) {
  [cause]: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11730:11)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at $fetchRaw (file:///var/www/server/index.mjs:1:58493)
      at r (file:///var/www/server/index.mjs:1:59455)
      at Object.refinement (file:///var/www/server/utils/zod.ts:264:1)
      at file:///var/www/server/node_modules/zod-abort-failed/lib/index.mjs:1971:39
      at ZodObject.safeParseAsync (file:///var/www/server/node_modules/zod-abort-failed/lib/index.mjs:655:24)
      at ZodObject.password (file:///var/www/server/node_modules/zod-abort-failed/lib/index.mjs:628:24)
      at Object.handler (file:///var/www/server/api/auth/index.post.ts:17:1)
      at Object.handler (file:///var/www/server/index.mjs:1:51201) {
    cause: ConnectTimeoutError: Connect Timeout Error
        at onConnectTimeout (node:internal/deps/undici/undici:6869:28)
        at node:internal/deps/undici/undici:6825:50
        at Immediate._onImmediate (node:internal/deps/undici/undici:6857:13)
        at processImmediate (node:internal/timers:476:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
} undefined undefined
```
I did the same request with curl and has no problem so I guess is some package issue...

**Comment by manniL** [comment]
I don't think it is a package error. If you can successfully do the request with the plain `fetch` api (not `$fetch`), it might be, but most likely it is either a browser extension blocking the request or some logic error.

**Comment by ElYaiko** [comment]
Sorry, I tried with `fetch` and figured out it was an Ipv6 problem with my server.
Thanks.

**Comment by fatihtkale** [comment]
Did anyone fix this?

**Comment by OrbisK** [comment]
> Did anyone fix this?

There was no issue (see https://github.com/nuxt/nuxt/issues/26883#issuecomment-2084069172)

If you have any issues please open you issue at https://github.com/nuxt/nuxt/issues/new?template=bug-report.yml
