### ISSUE TITLE
node .output/server/index.mjs error

### ISSUE THREAD

**Issue by WooHoo-Wu** [nuxt/nuxt#26954]
### Environment

node 18.18.0
yarn 1.22.21

### Reproduction

"devDependencies": {
    "@awesome-image/image": "^0.0.10",
    "@awesome-image/services": "^0.0.2",
    "@nuxt/kit": "^3.9.1",
    "@nuxtjs/i18n": "^8.3.0",
    "@nuxtjs/sitemap": "^5.1.4",
    "@tailwindcss/aspect-ratio": "^0.4.2",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/line-clamp": "^0.4.2",
    "@tailwindcss/typography": "^0.5.7",
    "@types/aos": "^3.0.4",
    "@types/js-cookie": "^3.0.2",
    "@types/lodash": "^4.14.184",
    "@types/node": "^18.7.18",
    "@types/prettier": "^2.7.0",
    "axios": "^1.4.0",
    "cross-env": "^7.0.3",
    "nuxt": "^3.11.2",
    "prettier": "^2.7.1",
    "prettier-plugin-tailwindcss": "^0.1.13",
    "sass": "^1.54.8",
    "tailwindcss": "^3.2.1",
    "typescript": "*",
    "vite-plugin-svg-icons": "^2.0.1"
  },
  "dependencies": {
    "@nuxt/image": "^1.1.0",
    "aos": "^2.3.4",
    "crypto-js": "^4.1.1",
    "js-cookie": "^3.0.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "node-fetch-native": "^1.0.1",
    "swiper": "^8.3.2"
  }

### Describe the bug

node .output/server/index.mjs
node:internal/modules/cjs/loader:1098
  const err = new Error(`Cannot find module '${request}'`);
              ^

Error: Cannot find module '/Users/woohoo/code/adspower/temp/mix_www_fe/.output/server/node_modules/rollup/dist/rollup.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1098:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1091:15)
    at resolveExports (node:internal/modules/cjs/loader:567:14)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.resolve (node:internal/modules/cjs/helpers:125:19)
    at resolveDependencyVersion (file:///Users/woohoo/code/adspower/temp/mix_www_fe/.output/server/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:12213:47)
    at file:///Users/woohoo/code/adspower/temp/mix_www_fe/.output/server/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:12216:23
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/woohoo/code/adspower/temp/mix_www_fe/.output/server/node_modules/rollup/package.json'
}

Node.js v18.18.0

**Comment by WooHoo-Wu** [comment]
It's my problem, I'm sorry
