### ISSUE TITLE
Nuxt Build Error (RegExp.prototype.exec)

### ISSUE THREAD

**Issue by SossenSystems** [nuxt/nuxt#27012]
### Environment

```
------------------------------
- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.8.1
- Package Manager:  npm@9.6.6
- Builder:          -
- User Config:      devtools, modules, css, app, router, auth, devServer, robots, colorMode, pinia, build, typescript, piniaPersistedstate, hooks, site, sitemap, nitro, runtimeConfig, features
- Runtime Modules:  nuxt-icon@0.6.10, @nuxtjs/google-fonts@3.2.0, @formkit/auto-animate/nuxt@0.8.2, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.0, @nuxt/image@1.6.0, @nuxt/ui@2.15.2, @vueuse/nuxt@10.9.0, v-wave/nuxt, @sidebase/nuxt-auth@0.7.2, @nuxtjs/seo@2.0.0-rc.10, nuxt-aos@1.2.4
- Build Modules:    -
------------------------------
```

### Reproduction

-

### Describe the bug

```
 ERROR  x Build failed in 886ms                                                                                                                            2:08:15 AM


 ERROR  Nuxt Build Error: [vite:css] [postcss] Method RegExp.prototype.exec called on incompatible receiver [object RegExp]                                2:08:15 AM
file: /Users/mynuxtproject/node_modules/tailwindcss/tailwind.css:undefined:NaN

  file: node_modules/tailwindcss/tailwind.css:undefined:NaN
  at Proxy.exec (<anonymous>)
  at Proxy.test (<anonymous>)
  at registerPlugins (node_modules/tailwindcss/lib/lib/setupContextUtils.js:899:38)
  at createContext (node_modules/tailwindcss/lib/lib/setupContextUtils.js:1221:5)
  at getContext (node_modules/tailwindcss/lib/lib/setupContextUtils.js:1278:19)
  at node_modules/tailwindcss/lib/lib/setupTrackingContext.js:118:81
  at node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11
  at plugins (node_modules/tailwindcss/lib/plugin.js:38:69)
  at LazyResult.runOnRoot (node_modules/postcss/lib/lazy-result.js:329:16)
  at LazyResult.runAsync (node_modules/postcss/lib/lazy-result.js:258:26)

```

and

```
 ERROR  x Build failed in 1.95s                                                                                                                                      2:03:45 AM


 ERROR  Nuxt Build Error: [vite:css] [postcss] Method RegExp.prototype.exec called on incompatible receiver [object RegExp]                                          2:03:45 AM
file: /project_live/node_modules/.cache/nuxt-google-fonts/css/nuxt-google-fonts.css:undefined:NaN

  file: node_modules/.cache/nuxt-google-fonts/css/nuxt-google-fonts.css:undefined:NaN
  at Proxy.exec (<anonymous>)
  at Proxy.test (<anonymous>)
  at registerPlugins (node_modules/tailwindcss/lib/lib/setupContextUtils.js:899:38)
  at createContext (node_modules/tailwindcss/lib/lib/setupContextUtils.js:1221:5)
  at getContext (node_modules/tailwindcss/lib/lib/setupContextUtils.js:1278:19)
  at node_modules/tailwindcss/lib/lib/setupTrackingContext.js:118:81
  at node_modules/tailwindcss/lib/processTailwindFeatures.js:46:11
  at plugins (node_modules/tailwindcss/lib/plugin.js:38:69)
  at LazyResult.runOnRoot (node_modules/postcss/lib/lazy-result.js:329:16)
  at LazyResult.runAsync (node_modules/postcss/lib/lazy-result.js:258:26)
  ```

### Additional context

Get this error after "nuxt build"

**Comment by SossenSystems** [comment]
Sure, here is the reproduction: https://stackblitz.com/edit/github-wvkjrt

**Comment by manniL** [comment]
@SossenSystems Posting your whole project is no "minimal" reproduction.

> Please ensure that the reproduction is as minimal as possible. See more details [in our guide](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction).

**Comment by pskclub** [comment]
try this
```
 "resolutions": {
    "@nuxtjs/tailwindcss": "6.11.4"
  },
```

**Comment by danielroe** [comment]
Pinning the tailwind version resolves the issue. Would you raise an issue upstream in `@nuxtjs/tailwindcss`? https://github.com/nuxt-modules/tailwindcss

**Comment by pskclub** [comment]
> "resolutions": {
>     "@nuxtjs/tailwindcss": "6.11.4"
>   },

fixed in https://github.com/nuxt/ui ^v2.16.0

**Comment by pskclub** [comment]
> Pinning the tailwind version resolves the issue. Would you raise an issue upstream in `@nuxtjs/tailwindcss`? https://github.com/nuxt-modules/tailwindcss

fixed in https://github.com/nuxt/ui ^v2.16.0
