### ISSUE TITLE
Problems building Nuxt 3 on electron startup

### ISSUE THREAD

**Issue by sev-b** [nuxt/nuxt#27236]
### Environment

```
- Operating System: Windows_NT
- Node Version:     v20.12.2
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      app, modules, ssr, router, build, vite
- Runtime Modules:  @nuxtjs/eslint-module@4.1.0, @pinia/nuxt@0.5.1, ()
- Build Modules:    -
```

### Reproduction

can't share code due to corporate law
if very necessary I will try to create an electron-fiddle

### Describe the bug

In my electron app I am using Nuxt and have been migrating from v2 to v3 over the last few days.

Now when calling my builder function in main.js I get the error
```
TypeError: Cannot read properties of undefined (reading 'map')
 at initNuxt (nuxt/dist/index.mjs:3928:46)
```
for this
```js
async function readyNuxt() {
  const { createNuxt } = await import('nuxt')
  nuxt = createNuxt(configDev)
  nuxt.hook('build:done', () => {
    const application = express()
    application.use(nuxt.render)
  })
  nuxt.ready()
}
```
and
```
TypeError: Cannot read properties of undefined (reading 'flatMap')
at resolveApp (nuxt/dist/index.mjs:4781:28)
```
for this
```js
async function readyNuxt() {
  const { createNuxt, build } = await import('nuxt')
  nuxt = createNuxt(configDev)
  nuxt.hook('build:done', () => {
    const application = express()
    application.use(nuxt.render)
  })
  build(nuxt)
}
```

In Nuxt 2 this worked perfectly:
```js
async function readyNuxt() {
  const { Nuxt, Builder } = await import('nuxt')
  nuxt = new Nuxt(configDev)
  const builder = new Builder(nuxt)
  builder.build()
  nuxt.hook('build:done', () => {
    const application = express()
    application.use(nuxt.render)
  })
}
```

I know that there are libraries like `nuxt-electron` that take over a lot of the work here but would prefer keeping my own implementation for now.

**Comment by Flo0806** [comment]
Hey! DM Hero is a Nuxt 4 - Electron app. So the important thing to know: `createNuxt` expectes resolved options, not the `NuxtConfig`. To start your app correctly with Electron:

```typescript
const { loadNuxt, buildNuxt } = await import('@nuxt/kit')
const nuxt = await loadNuxt({ cwd, dev: true })
await buildNuxt(nuxt)
```

That's the new way Nuxt >= 3 @danielroe not a bug - only a new way to go. Can be closed

**Comment by danielroe** [comment]
nuxtathon closed @Flo0806
