### ISSUE TITLE
useHead undefined after initiating a regex (since monday)

### ISSUE THREAD

**Issue by hankdetank** [nuxt/nuxt#27392]
### Environment

Linux (this problem doesnt appear to happen on windows).
tested on different node versions. 

### Reproduction

https://stackblitz.com/edit/github-819pq2-4sknkq?file=layouts%2Fdefault.vue

### Describe the bug

"var emailregexx =
  /^[a-zA-Z0-9.!#$%&'+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)$/;
useHead({
  meta: [
    {
      name: 'viewport',
      content:
        'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0',
    },
  ],
});"

This code crashes. And my question is why. It seems to be an upstream bug as it happens since monday(maybe friday or thursday) and this code is already years old.

When you remove the regex line, all works normally again. 

### Additional context

Error that gets thrown:
useHead is not defined

at _sfc_main.setup (./layouts/default.js:42:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:195:19)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7572:25)
at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7533:36)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:15)
at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:755:14)
at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:7)
at eval (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:639:25)
at async unrollBuffer$1 (./node_modules/@vue/s

**Comment by danielroe** [comment]
This is likely an upstream issue with the transform from https://github.com/unjs/unimport and you can probably avoid it by slightly rewriting the regular express.

Would you raise an issue there? 🙏

**Comment by hankdetank** [comment]
> This is likely an upstream issue with the transform from https://github.com/unjs/unimport and you can probably avoid it by slightly rewriting the regular express.
> 
> Would you raise an issue there? 🙏

@danielroe Thank you for your response. I created the ticket.

Also fixed the issue in my project by escaping the / in the regex
/^[a-zA-Z0-9.!#$%&'+\/?`{|}~-]+@[a-zA-Z0-9-]+(?:.[a-zA-Z0-9-]+)$/; (escaped the /)
