### ISSUE TITLE
Error: Cannot find module '@nuxt/ui-templates' 

### ISSUE THREAD

**Issue by yazfield** [nuxt/nuxt#27592]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.12.1`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@9.5.1`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

this is a brand new project I have no code and can't reproduce it in online platform

### Describe the bug

When creating a new nuxt project I get `Error: Cannot find module '@nuxt/ui-templates'` after running npm run dev, i tried different node versions and package managers

**Comment by danielroe** [comment]
We no longer use `@nuxt/ui-templates`. Are you sure you're running the very latest version of Nuxt?

Do you have a globally installed version of `nuxi`?

**Comment by tobiasdiez** [comment]
I also experienced this issue. The reason was that an old version of nuxt-component-meta was used:
```
@nuxt-themes/docus 1.15.0
└─┬ @nuxthq/studio 1.0.13
  └── nuxt-component-meta 0.6.3
```
Overwriting the version of `@nuxthq/studio` to `^1.1.0` solved the issue for me.

**Comment by danielroe** [comment]
Yes, that's a likely cause. A refresh of your lockfile should also hopefully resolve it as https://github.com/nuxtlabs/nuxt-component-meta/pull/66 is included in 0.6.4.

**Comment by securixhk** [comment]
Hello,
Suddenly, I'm facing this issue on Vercel deployments. 
Despite adjusting package.json dependencies versions, nothing improves.
Any suggestion :) ? 
Thanks in advance.

**Here's the output :** 
[08:21:12.726] Running build in Washington, D.C., USA (East) – iad1
[08:21:12.920] Cloning XXXXX
[08:21:13.661] Previous build cache not available
[08:21:14.225] Cloning completed: 1.303s
[08:21:14.825] Running "vercel build"
[08:21:15.668] Vercel CLI 34.3.0
[08:21:16.817] Installing dependencies...
[08:22:06.312] npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[08:22:06.387] npm WARN deprecated paneer@0.1.0: Please migrate to https://github.com/unjs/magicast
[08:22:06.390] npm WARN deprecated are-we-there-yet@2.0.0: This package is no longer supported.
[08:22:06.612] npm WARN deprecated npmlog@5.0.1: This package is no longer supported.
[08:22:06.719] npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[08:22:06.842] npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[08:22:07.195] npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
[08:22:07.225] npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
[08:22:07.306] npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[08:22:07.445] npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[08:22:07.648] npm WARN deprecated gauge@3.0.2: This package is no longer supported.
[08:22:12.449] 
[08:22:12.450] added 990 packages in 55s
[08:22:12.450] 
[08:22:12.450] 290 packages are looking for funding
[08:22:12.450]   run `npm fund` for details
[08:22:12.535] Detected `package-lock.json` generated by npm 7+
[08:22:12.535] Running "npm run build"
[08:22:12.805] 
[08:22:12.805] > alpine-starter@0.1.0 build
[08:22:12.805] > nuxi build
[08:22:12.805] 
[08:22:13.053] [log] Nuxt 3.12.3 with Nitro 2.9.7
[08:22:14.591] [log] Using `2024-04-03` as fallback compatibility date.
[08:22:17.226] [error] Cannot find module '@nuxt/ui-templates'
[08:22:17.227] Require stack:
[08:22:17.227] - /vercel/path0/index.js
[08:22:17.227]   Require stack:
[08:22:17.227]   - index.js
[08:22:17.227]   at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
[08:22:17.227]   at Function.resolve (node:internal/modules/helpers:190:19)
[08:22:17.227]   at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:241814)
[08:22:17.227]   at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2224:29)
[08:22:17.227]   at node_modules/nuxt-component-meta/dist/module.mjs:103:17
[08:22:17.227]   at node_modules/hookable/dist/index.mjs:48:66
[08:22:17.228]   at node_modules/hookable/dist/index.mjs:48:56
[08:22:17.228]   at async node_modules/nuxt/dist/index.mjs:2268:7
[08:22:17.228]   at async resolveApp (node_modules/nuxt/dist/index.mjs:5321:3)
[08:22:17.228]   at async generateApp (node_modules/nuxt/dist/index.mjs:5170:3)
[08:22:17.228]   at async _applyPromised (node_modules/perfect-debounce/dist/index.mjs:54:10) 
[08:22:17.228] 
[08:22:17.228] [error] Cannot find module '@nuxt/ui-templates'
[08:22:17.228] Require stack:
[08:22:17.228] - /vercel/path0/index.js
[08:22:17.250] Error: Command "npm run build" exited with 1
[08:22:17.598]

**Comment by securixhk** [comment]
Fixed : https://github.com/nuxt-themes/alpine/issues/199#issuecomment-2241588271
