### ISSUE TITLE
Cannot find module '@nuxt/cli-edge'

### ISSUE THREAD

**Issue by 343058360** [nuxt/nuxt#27671]
### Environment

docker devops

### Reproduction

package.json
{
  "name": "nuxt-iron",
  "version": "1.0.0",
  "description": "mall",
  "private": true,
  "scripts": {
    "dev": "cross-env NUXT_ENV_ENVIROMENT=dev nuxt-ts",
    "build": "nuxt-ts build",
    "generate": "nuxt-ts generate",
    "start": "nuxt-ts start",
    "lint": "eslint --ext .ts,.js,.vue .",
    "precommit": "npm run lint",
    "docker": "npm install && cross-env NUXT_ENV_ENVIROMENT=prod nuxt-ts build",
    "test": "jest"
  },
  "dependencies": {
    "@babel/preset-env": "^7.12.17",
    "@nuxt/typescript-runtime": "^2.0.1",
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/pwa": "^2.6.0",
    "@types/echarts": "^4.4.1",
    "axios": "^0.18.0",
    "bignumber.js": "^9.0.1",
    "bootstrap": "^4.1.3",
    "bootstrap-vue": "^2.0.4",
    "cookie-universal-nuxt": "^2.1.4",
    "cross-env": "^5.2.0",
    "echarts": "4.5.0",
    "express": "^4.16.4",
    "fork-ts-checker-webpack-plugin": "^6.1.0",
    "nuxt": "^2.14.0",
    "sha1": "^1.1.1",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.2",
    "v-viewer": "^1.6.4",
    "vue-awesome-swiper": "^3.1.3",
    "vue-baidu-map": "^0.21.22",
    "vue-class-component": "^7.1.0",
    "vue-clipboard2": "^0.3.1",
    "vue-json-excel": "^0.3.0",
    "vuex-class": "^0.3.2",
    "xe-utils": "2.2.11"
  },
  "devDependencies": {
    "@nuxt/types": "^2.14.12",
    "@nuxt/typescript-build": "^2.0.4",
    "@nuxt/typescript-runtime": "^2.0.1",
    "@nuxtjs/eslint-config": "1.1.2",
    "@nuxtjs/eslint-config-typescript": "^0.1.3",
    "@types/jquery": "^3.5.6",
    "@typescript-eslint/eslint-plugin": "^2.7.0",
    "@typescript-eslint/parser": "^2.7.0",
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^24.1.0",
    "eslint": "^6.6.0",
    "eslint-config-prettier": "^4.1.0",
    "eslint-config-standard": "14.1.0",
    "eslint-loader": "^2.1.2",
    "eslint-plugin-import": ">=2.16.0",
    "eslint-plugin-jest": ">=22.3.0",
    "eslint-plugin-node": ">=8.0.1",
    "eslint-plugin-nuxt": ">=0.4.2",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-plugin-vue": "^5.2.2",
    "jest": "^24.1.0",
    "nodemon": "^1.18.9",
    "prettier": "^1.16.4",
    "pug": "^2.0.3",
    "pug-plain-loader": "^1.0.0",
    "ts-loader": "^6.2.1",
    "ts-vue-plugin": "^0.1.2",
    "typescript": "^4.1.3",
    "vue-jest": "^3.0.3",
    "vue-property-decorator": "^8.3.0"
  }
}

dockerfile

ADD . mall
WORKDIR /mall
COPY /package.json ./package.json
COPY /package-lock.json ./package-lock.json
RUN npm install
RUN npm install @nuxt/cli
RUN npm install @nuxt/typescript-runtime@2.0.1
RUN npm run dev

### Describe the bug

0.675 > nuxt-iron@1.0.0 dev /shopping-mall
0.675 > cross-env NUXT_ENV_ENVIROMENT=dev nuxt-ts
0.675
0.758 internal/modules/cjs/loader.js:892
0.758   throw err;
0.758   ^
0.758
0.758 Error: Cannot find module '@nuxt/cli-edge'
0.758 Require stack:
0.758 - /shopping-mall/node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js
0.758     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
0.758     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
0.758     at Module.require (internal/modules/cjs/loader.js:961:19)
0.758     at require (internal/modules/cjs/helpers.js:92:18)
0.758     at /shopping-mall/node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js:3:79
0.758     at Object.<anonymous> (/shopping-mall/node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js:3:109)
0.758     at Module._compile (internal/modules/cjs/loader.js:1072:14)
0.758     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
0.758     at Module.load (internal/modules/cjs/loader.js:937:32)
0.758     at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
0.758   code: 'MODULE_NOT_FOUND',
0.758   requireStack: [
0.758     '/shopping-mall/node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js'
0.758   ]
0.758 }
0.765 npm ERR! code ELIFECYCLE
0.765 npm ERR! errno 1
0.768 npm ERR! nuxt-iron@1.0.0 dev: `cross-env NUXT_ENV_ENVIROMENT=dev nuxt-ts`
0.768 npm ERR! Exit status 1
0.768 npm ERR!

 "@nuxt/types": "^2.14.12",
 "@nuxt/typescript-build": "^2.0.4",
 "@nuxt/typescript-runtime": "^2.0.1",
 "nuxt": "^2.14.0",

**Comment by 343058360** [comment]
update node:14.21.3-alpine3.17
