### ISSUE TITLE
v3.12.2: [unhandledRejection] errors with `nuxt dev`

### ISSUE THREAD

**Issue by cossssmin** [nuxt/nuxt#27708]
### Environment

Nuxt project info:                                                              2:58:04 PM

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      css, components, modules, headlessui, ogImage, postcss, spaLoadingTemplate, typescript, site, devtools, nitro
- Runtime Modules:  @vueuse/nuxt@10.11.0, nuxt-og-image@3.0.0-rc.53, @nuxt/content@2.12.1, @nuxtjs/sitemap@5.2.0, nuxt-headlessui@1.2.0, @nuxtjs/google-fonts@3.2.0
- Build Modules:    -
------------------------------

### Reproduction

Run `nuxt dev` to get the error in the first log below.

Run `nuxt dev --host` to see the errors in the second log.

### Describe the bug

`unhandledRejection` errors printed in the terminal.

### Additional context

When using `nuxt dev --host`, the error is printed repeatedly, every few seconds.

### Logs

```shell-script
> nuxt dev

Nuxt 3.12.2 with Nitro 2.9.6                                                2:55:13 PM      
                                                                            2:55:13 PM      
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Alt + D in the browser (v1.3.3)                 2:55:17 PM      

ℹ Vite client warmed up in 6302ms                                          2:55:26 PM       
ℹ Vite server warmed up in 5308ms                                          2:55:26 PM       
✔ Nuxt Nitro server built in 3743 ms                                 nitro 2:55:28 PM       

 ERROR  [unhandledRejection] Must provide a proper URL as target            2:55:29 PM      

  at ProxyServer.ws ([..]/node_modules/httpxy/dist/index.mjs:521:9)
  at Object.upgrade ([..]/node_modules/nitropack/dist/chunks/server.mjs:374:24)
  at Server.<anonymous> ([..]/node_modules/nuxi/dist/chunks/dev2.mjs:6898:29)
  at Server.emit (node:events:526:35)
  at onParserExecuteCommon (node:_http_server:942:14)
  at onParserExecute (node:_http_server:836:3)
```

```
> nuxt dev --host

Nuxt 3.12.2 with Nitro 2.9.6                                                    2:59:22 PM       
                                                                                2:59:22 PM       

              █▀▀▀▀▀▀▀██▀▀▀█▀██▀█▀▀▀▀▀▀▀█
              █ █▀▀▀█ ██▀▀ ▄█▀█▀█ █▀▀▀█ █
              █ █   █ █ █ ▄▀  ▄▄█ █   █ █
              █ ▀▀▀▀▀ █▀▄ █▀▄▀█▀█ ▀▀▀▀▀ █
              █▀▀███▀▀▀█ ▀█ ▀██▀███▀▀████
              ██▄▀▄▀▄▀█▀▀▄▀▀▀█ ▄▄▀▀  ▄ ▀█
              ██▄█▄▄█▀ ▄▀ ▄██ ▀▄▀▀▄█▄██ █
              █ █ ▄▄█▀▄▄▀ █▄█▄ █▀█▀█▀█ ▀█
              █ █  ▄ ▀▀▄▀ █ ▀▄▄▀▀▀▀ █ █▄█
              █▀▀▀▀▀▀▀█ ▄ █▀▀ █ █▀█ ▀▄█▀█
              █ █▀▀▀█ █▄   ▀▀█▀ ▀▀▀ ▀▀█▄█
              █ █   █ ██ ▀█▄██▀ ▀▄▄█▄▀▄ █
              █ ▀▀▀▀▀ █ ▄▄▄▀█▀  ▀▄▄▄▀██ █
              ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

  ➜ Local:    http://localhost:3000/
  ➜ Network:  http://172.28.48.1:3000/ [QR code]
  ➜ Network:  http://192.168.1.190:3000/

  ➜ DevTools: press Shift + Alt + D in the browser (v1.3.3)                     2:59:27 PM

ℹ Vite client warmed up in 6466ms                                              2:59:35 PM
ℹ Vite server warmed up in 5322ms                                              2:59:35 PM
✔ Nuxt Nitro server built in 3746 ms                                     nitro 2:59:37 PM

 ERROR  [unhandledRejection] write ECONNABORTED                                 2:59:41 PM

  at afterWriteDispatched (node:internal/stream_base_commons:160:15)
  at writeGeneric (node:internal/stream_base_commons:151:3)
  at Socket._writeGeneric (node:net:952:11)
  at Socket._write (node:net:964:8)
  at writeOrBuffer (node:internal/streams/writable:556:12)
  at _write (node:internal/streams/writable:490:10)
  at Writable.write (node:internal/streams/writable:494:10)
  at IncomingMessage.ondata (node:internal/streams/readable:985:22)
  at IncomingMessage.emit (node:events:514:28)
  at addChunk (node:internal/streams/readable:545:12)
```
```

**Comment by lustremedia** [comment]
Try if the error is caused by one of the modules. Comment them out one by one and see if the error disappears ...

**Comment by lustremedia** [comment]
Also you should use _npm run dev_ not _nuxt dev_ to run your project, no?

**Comment by cossssmin** [comment]
> Also you should use _**npm run dev -- -o**_ not _**nuxt dev**_ to run your project, no?

I have `npm run dev` set to `nuxt dev --host`.

And as it happens with these weird bugs, I fire up the dev server today and poof, all gone and working fine again. Didn't install/update anything, just came back to it the following day 🫠

Closing it now, will reopen in case it happens again and I have more data, thanks.

**Comment by parzychu** [comment]
I had the similar issue when running when running `yarn dev` after switch from `ssr:true` to `ssr:false`

I removed `dist/`, `/.nuxt` and `/.output` folders and it solved the problem
