### ISSUE TITLE
Nuxt 4 - Internal server error: Failed to resolve import "@vue/devtools-kit"

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/nuxt#27772]
### Environment

````
------------------------------
- Operating System: Ubuntu 22.04.4 LTS
- Node Version:     v18.14.2
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    -
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

### Reproduction

https://stackblitz.com/~/github.com/martinszeltins/nuxt-4-test-app

### Describe the bug

I wanted to test out Nuxt 4 so I created a new project with 

```sh
$ nuxi init -t v4-compat my-nuxt4-app
```

And when I ran `pnpm dev` I got this error _(both locally and on StackBlitz)_:

**Screenshot:**
![image](https://github.com/nuxt/nuxt/assets/34019878/60885f2a-5cf2-46ef-8a93-92f25f8c968a)

**Error:**
````
ERROR  Internal server error: Failed to resolve import "@vue/devtools-kit" from "node_modules/.pnpm/@nuxt+devtools@1.3.5_vite@5.3.1/node_modules/@nuxt/devtools/dist/runtime/vue-devtools/overlay.mjs". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/@nuxt+devtools@1.3.5_vite@5.3.1/node_modules/@nuxt/devtools/dist/runtime/vue-devtools/overlay.mjs:1:27
  1  |  import { devtools } from '@vue/devtools-kit'
     |                            ^
  2  |  import { initAppSeparateWindow } from '@vue/devtools-core'
  3  |  
      at TransformPluginContext._formatError (file:///home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:49752:41)
      at TransformPluginContext.error (file:///home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:49747:16)
      at normalizeUrl (file:///home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:64309:23)
      at async eval (file:///home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:64441:39)
      at async TransformPluginContext.transform (file:///home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:64368:7)
      at async eval (file:///home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/vite-plugin-inspect@0.8.4_@nuxt+kit@3.12.2_vite@5.3.1/node_modules/vite-plugin-inspect/dist/index.mjs:392:17)
      at async PluginContainer.transform (file:///home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:49593:18)
      at async loadAndTransform (file:///home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:52415:27)
      at async viteTransformMiddleware (file:///home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:62151:24)

 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/@nuxt+devtools@1.3.5_vite@5.3.1/node_modules/@nuxt/devtools/dist/runtime/vue-devtools/overlay.mjs"

 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/@nuxt+devtools@1.3.5_vite@5.3.1/node_modules/@nuxt/devtools/dist/runtime/vue-devtools/overlay.mjs"

 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/@nuxt+devtools@1.3.5_vite@5.3.1/node_modules/@nuxt/devtools/dist/runtime/vue-devtools/overlay.mjs"

 WARN  [Vue Router warn]: No match found for location with path "/_nuxt/@fs/home/martinszeltins/nuxt-4-test-app/node_modules/.pnpm/@nuxt+devtools@1.3.5_vite@5.3.1/node_modules/@n
````

**Comment by danielroe** [comment]
this is no longer replicable.
