### ISSUE TITLE
UpdateRuntimeConfig fails in nitro

### ISSUE THREAD

**Issue by max06** [nuxt/nuxt#27847]
### Environment

- Operating System: Linux
- Node Version:     v20.11.0
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  bun@1.1.12
- Builder:          -
- User Config:      alias, devtools, modules, nitro, runtimeConfig, tailwindcss, ui, scalar, future, hooks
- Runtime Modules:  @nuxt/ui@2.17.0-28646542.4d5f250, @nuxtjs/color-mode@3.4.1, @nuxtjs/tailwindcss@6.12.0, @pinia/nuxt@0.5.1, nuxt-monaco-editor@1.2.9, @nuxt/test-utils/module@3.13.1, @scalar/nuxt@0.1.5
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-mtlhhf?file=nuxt.config.ts

### Describe the bug

I'm trying to add values to the nuxt runtime config, that is usually also available in the nitro context using `useRuntimeConfig()`.

Extending the config triggers an hmr reload of nitro, and following error:

```text
 ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'envExpansion')                                                                5:58:54 PM

  at normalizeRuntimeConfig (node_modules/nitropack/dist/nitro.mjs:4997:41)
  at Object.updateConfig (node_modules/nitropack/dist/nitro.mjs:5122:37)
  at updateRuntimeConfig (node_modules/@nuxt/kit/dist/index.mjs:2785:23)
  at eval (nuxt.config.ts:16:38)
  at eval (node_modules/hookable/dist/index.mjs:68:66)
  at Object.run (node_modules/hookable/dist/index.mjs:61:43)
  at eval (node_modules/hookable/dist/index.mjs:68:56)
```

The extended config is available on the client, but not on the server.

**Comment by Teages** [comment]
I think it is is not avaliable in nitro, because it is designed for nuxt module and it visit runtime config by the nuxt runtime context.

for your use case, I suggest to hook `nitro:config`, or just create a nuxt module:

```ts
nuxt.hook('nitro:config', (nitroConfig) => {
  nitroConfig.runtimeConfig = nitroConfig.runtimeConfig ?? {}
  nitroConfig.runtimeConfig.foo = 'bar'
})
```

[Reference](https://github.com/nuxt/nuxt/blob/74e847bd90acec817d6539493d694e9e0fa79912/packages/kit/src/runtime-config.ts#L28)

**Comment by max06** [comment]
Looks like I copy&pasted too much from my code - issue persists even if I just use the nuxt `ready`-hook without any nitro specifics.

I'll try your implementation once I'm awake.

**Comment by danielroe** [comment]
`updateRuntimeConfig` is meant to be called wtihin modules.

In your use case, just use `nitro.updateConfig({ runtimeConfig: { foo: 'bar' }})`

**Comment by max06** [comment]
Looks like something got updated in the meantime - that function no longer crashes. Trying it in the playground linked above now causes nitro to reload over and over again due to the config changes - probably my fault.

Anyways, thanks for taking care of this. My project got cancelled, not sure if that will ever be used ...
