### ISSUE TITLE
Prerender 500 error only in GitHub Actions build & deployment

### ISSUE THREAD

**Issue by iMasoud** [nuxt/nuxt#27862]
### Environment

Environment is Default build & deploy Action that is provided by GitHub for serving static Nuxt output in GitHub Pages.

### Reproduction

You can see the repository here: https://github.com/CODE-CLAN-AUS/clan-uni

### Describe the bug

Generating static output by GitHub Actions fails on prerender with 500 errors for every route. Even though `generate` and `build` as well as `dev` commands all work fine on my local machine with no errors.

Unfortunately, error in the logs is not detailed. You can see the logs [here](https://github.com/CODE-CLAN-AUS/clan-uni/actions/runs/9696396037/job/26758227882#step:8:94).

### Logs

```shell-script
.
.
.
[info] [nitro] Initializing prerenderer
[info] [nitro] Prerendering 5 initial routes with crawler
[log] [nitro]   ├─ /200.html (33ms)
[log] [nitro]   ├─ /404.html (34ms)
[log] [nitro]   ├─ /web-components/what-are-web-components (64ms)
  │ └── Error: [500] 
[log] [nitro]   ├─ /web-components (64ms)
  │ └── Error: [500] 
[log] [nitro]   ├─ / (66ms)
  │ └── Error: [500] 
[log] [nitro] 
Errors prerendering:
[log] [nitro]   ├─ /web-components/what-are-web-components (64ms)
  │ └── Error: [500] 
[log] [nitro]   ├─ /web-components (64ms)
  │ └── Error: [500] 
[log] [nitro]   ├─ / (66ms)
  │ └── Error: [500] 
[log] [nitro]
Error:  Exiting due to prerender errors.
  at prerender (node_modules/nitropack/dist/chunks/prerender.mjs:218:11)
  at async node_modules/nuxt/dist/index.mjs:3540:7
  at async build (node_modules/nuxt/dist/index.mjs:5333:5)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:94:5)
  at async Object.run (node_modules/nuxi/dist/chunks/generate.mjs:55:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1777:7) 

Error:  Exiting due to prerender errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by struthy** [comment]
getting same error

**Comment by danielroe** [comment]
That GitHub Actions workflow looks like a Nuxt 2 setup. Where did you see it recommended?

Please follow [these directions](https://nuxt.com/deploy/github-pages) instead.
