### ISSUE TITLE
Development server keeps trying to reach localhost:24678 which doesn't exist

### ISSUE THREAD

**Issue by therealokoro** [nuxt/nuxt#27907]
### Environment

Nuxt project info:                                                                                                 1:31:40 AM

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     3.11.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      srcDir, serverDir, devtools, css, extends, modules, app, nitro, routeRules, runtimeConfig, image, vue, experimental, fontMetrics, features, vueEmail
- Runtime Modules:  @nuxt/devtools@1.3.6, @vueuse/nuxt@10.11.0, @unocss/nuxt@0.60.4, @nuxt/image@1.7.0, @nuxtjs/fontaine@0.4.3,
 @pinia/nuxt@0.5.1, notivue/nuxt, nuxt-tiptap-editor@1.1.2, @vue-email/nuxt@0.8.19
- Build Modules:    -
------------------------------

### Reproduction

[]( )

### Describe the bug

I keep getting this error and log in the console every single time when running the development server of nuxt and I have absolutely know idea why.

Though it doesn't break the development server as one would think, but it's just so frustrating to see each time

### Additional context

![image](https://github.com/nuxt/nuxt/assets/41494675/92c1bc41-fd30-41b9-9dea-9b41f6e6909e)
![image](https://github.com/nuxt/nuxt/assets/41494675/03802822-b682-4c24-9458-6fca7c81eaf0)

**Comment by martinszeltins** [comment]
I just upgraded to Nuxt 3.12 and getting the same strange port

![image](https://github.com/nuxt/nuxt/assets/34019878/e6e06823-5a2f-4e5f-b5ae-ddd177b75909)

````
------------------------------
- Operating System: Ubuntu 22.04.4 LTS
- Node Version:     v18.14.2
- Nuxt Version:     3.12.0-28587627.2d1ab61b
- CLI Version:      3.12.0
- Nitro Version:    2.10.0-28659787.86930878
- Package Manager:  pnpm@8.6.12
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------
````

**Comment by martinszeltins** [comment]
@danielroe Oh, I just noticed you asked for a reproduction, here it is. Best seen when running locally so I didn't put it on Stackblitz.

https://github.com/martinszeltins/nuxt-port-devtools-issue

There are 2 issues:

1. `client:732 GET http://localhost:24678/_nuxt/ net::ERR_CONNECTION_REFUSED`
2. `Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@vue+devtools-core@7.3.5_vite@5.3.2_vue@3.4.31/node_modules/@vue/devtools-core/dist/index.js?v=98b89a8d' does not provide an export named 'initAppSeparateWindow' (at overlay.mjs:2:10)`

Screenshot:
![image](https://github.com/nuxt/nuxt/assets/34019878/8907ba8a-0cc6-4f85-8671-2dc0a7e8981f)

**Comment by therealokoro** [comment]
Thanks for the reproduction @martinszeltins. I add that. Good to see that i'm not the only one with the issue

**Comment by hermanndettmann** [comment]
I have that issue too since at least 3.12 and I'm also clueless. Would be really happy about a fix!

**Comment by danielroe** [comment]
Make sure you are using `"nuxt": "npm:nuxt-nightly@3x",` instead of `@latest` for now.

Once I upgrade the dependencies in that repo, everything seems to be working fine for me.

**Comment by martinszeltins** [comment]
> Make sure you are using `"nuxt": "npm:nuxt-nightly@3x",` instead of `@latest` for now.
> 
> Once I upgrade the dependencies in that repo, everything seems to be working fine for me.

Yea, I noticed that as well. I had `nuxt-nightly` before nighly switched to version 4 and I had the localhost:24678 issue. But now switching to `nuxt-nightly@3x` the issue is gone. I don't know how to explain this... 🤷🏻‍♂️

**Comment by martinszeltins** [comment]
@danielroe what about the other issue though?

````
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/@vue+devtools-core@7.3.5_vite@5.3.2_vue@3.4.31/node_modules/@vue/devtools-core/dist/index.js?v=98b89a8d' does not provide an export named 'initAppSeparateWindow' (at overlay.mjs:2:10)
````

**Comment by frasza** [comment]
https://github.com/nuxt/cli/issues/432 related possible

**Comment by danielroe** [comment]
@martinszeltins I don't get that either. It seems like a dep is pulling in an old version of that Vue dep. Check your lock file and if necessary force it to update.

**Comment by martinszeltins** [comment]
@danielroe How strange. I deleted both `node_modules` and `pnpm-lock.yaml` file and reinstalled dependencies and still getting this error.

My global `~/.nuxtrc` also doesn't seem to contain anything out of the ordinary:

````
telemetry.consent=1
telemetry.enabled=true
telemetry.seed=d2d790d304909fc0
````

![image](https://github.com/nuxt/nuxt/assets/34019878/c2f63216-63d6-40ca-8661-27793fb7b229)

**Comment by martinszeltins** [comment]
@danielroe I found the issue. Removing `"@nuxt/devtools": "1.1.3",` from dependencies solves the issue for me.

**Comment by isabolic** [comment]
for now this works for me => https://github.com/nuxt/nuxt/discussions/27779#discussioncomment-9952440

**Comment by danielroe** [comment]
Closing as there isn't a reproduction and this seems to be resolved with dependency upgrades.

@isabolic or @therealokoro if you can reproduce, I would be grateful and will happily reopen.

**Comment by marshallswain** [comment]
I updated all layers to `"nuxt": "^3.12.3",` and removed `@nuxt/devtools` as @martinszeltins suggested and it fixed the issue for me.  Thank you, @martinszeltins.

**Comment by Keji-so** [comment]
I'm having this same issue?

**Comment by Keji-so** [comment]
> I updated all layers to `"nuxt": "^3.12.3",` and removed `@nuxt/devtools` as @martinszeltins suggested and it fixed the issue for me. Thank you, @martinszeltins.

I did this and it solved the error for me. Thanks. Hoping this is a final fix.

**Comment by maisoncastro** [comment]
@martinszeltins works for me. Thank you!

**Comment by bsayat** [comment]
Hello, there!
I have the same issue. I just install nuxt globally, and that fixed this issue

**Comment by hybridherbst** [comment]
Since this is still an issue with 3.12.4:
The solution here, explicitly setting the server.hmr.clientPort, worked for me.
https://github.com/nuxt/nuxt/discussions/27779#discussioncomment-9952440

**Comment by aldoprogra** [comment]
On my case the solution was to update NuxtJS.

**Comment by richard-hatslogic** [comment]
i updated the nuxt version from 2.8.0 to ^3.12.3. This solved the issue
