### ISSUE TITLE
V4 - Cannot read properties of undefined (reading 'bind') - @nuxt/kit

### ISSUE THREAD

**Issue by roonie007** [nuxt/nuxt#27956]
### Environment

- Operating System: Linux
- Node Version:     v22.3.0
- Nuxt Version:     4.0.0-28664444.6bb24c14
- CLI Version:      3.13.0-1719571044.bca75ab
- Nitro Version:    -
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, future, compatibilityDate
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

https://stackblitz.com/edit/github-u2t8fv?file=nuxt.config.ts

### Describe the bug

Simply create a new nuxt project and follow the instruction to test the V4.

### Logs

```shell-script
$ nuxt prepare
[11:52:45 PM] ℹ Nuxt now supports pinning the behavior of provider and deployment presets with a compatibility date. We recommend you specify a compatibilityDate in your nuxt.config file.
Using 2024-04-03 as fallback compatibility date.                                                                                                          11:52:45 PM

[11:52:45 PM]  WARN  [nuxt] Expected @nuxt/kit to be at least 4.0.0-28664444.6bb24c14 but got 3.12.2. This might lead to unexpected behavior. Check your package.json or refresh your lockfile.


[11:52:45 PM]  WARN  [nuxt] Expected @nuxt/schema to be at least 4.0.0-28664444.6bb24c14 but got 3.12.2. This might lead to unexpected behavior. Check your package.json or refresh your lockfile.

ℹ Running with compatibility version 4                                                                                                                   11:52:46 PM

 ERROR  Cannot read properties of undefined (reading 'bind')                                                                                              11:52:46 PM

  at loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2749:56)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:76:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi-nightly.618a108a.mjs:1680:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi-nightly.618a108a.mjs:1671:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi-nightly.618a108a.mjs:1809:7) 



 ERROR  Cannot read properties of undefined (reading 'bind')                                                                                              11:52:46 PM

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by danielroe** [comment]
Apologies - it seems the latest changes to the docs haven't been deployed yet.

If you want to use the nightly channel, use `npm:nuxt-nightly@3x`. But in fact you can use nuxt v3.12.2 to test, just as well.
