### ISSUE TITLE
On cloudflare pages, `vue` and `vue-router` must be installed as explicit dependencies

### ISSUE THREAD

**Issue by wtlgo** [nuxt/nuxt#28018]
### Environment

Not sure how it's related, but here it is

```log
pnpm exec nuxi info
Working directory: [Redacted for privacy]/github/wtlgo/Nuxt500ErrorReproduction                                                                                               2:44:56 PM
Nuxt project info:                                                                                                                              2:44:56 PM

------------------------------
- Operating System: Windows_NT
- Node Version:     v22.4.0
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      devtools, compatibilityDate, app
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                     2:44:56 PM  

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

```

### Reproduction

The problem happens in this repo: https://github.com/wtlgo/Nuxt500ErrorReproduction
It is barely different compared to the initial template.

### Describe the bug

When I create `~/pages/index.vue`, add `<NuxtPage/>` to `~/app.vue`, and deploy my project to the CloudFlare Pages, trying to access it from the web results in the "500 - This page is temporarily unavailable." error. In the dev environment, everything works okay.

### Additional context

I use the following environmental variables on Cloudflare Pages:
```log
NODE_VERSION=22.4.0
PNPM_VERSION=9.4.0
```

and the following build settings:
```log
Build command: pnpm run build
Build output directory: /dist
```

### Logs

Real-time Logs when I try to access the index:
```json
{
  "outcome": "ok",
  "scriptName": "pages-worker--3133746-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "[nuxt] [request error] [unhandled] [500]",
        "Cannot access 'default' before initialization\n  at chunks/routes/renderer.mjs:1:112747  \n  at async chunks/routes/renderer.mjs:1:112700  \n  at async chunks/routes/renderer.mjs:1:114880  \n  at async Object.handler (chunks/routes/renderer.mjs:1:113824)  \n  at async Object.handler (chunks/runtime.mjs:1:72221)  \n  at async chunks/runtime.mjs:1:75358  \n  at async chunks/runtime.mjs:1:106817"
      ],
      "level": "error",
      "timestamp": 1720097702082
    },
    {
      "message": [
        "[nuxt] [request error] [unhandled] [500]",
        "Cannot access 'default' before initialization\n  at chunks/routes/renderer.mjs:1:112747  \n  at async chunks/routes/renderer.mjs:1:112700  \n  at async chunks/routes/renderer.mjs:1:114880  \n  at async Object.handler (chunks/routes/renderer.mjs:1:113824)  \n  at async Object.handler (chunks/runtime.mjs:1:72221)  \n  at async chunks/runtime.mjs:1:75358  \n  at async chunks/runtime.mjs:1:106817  \n  at async errorHandler (chunks/runtime.mjs:1:102760)  \n  at async chunks/runtime.mjs:1:75510  \n  at async chunks/runtime.mjs:1:106817"
      ],
      "level": "error",
      "timestamp": 1720097702082
    }
  ],
  "eventTimestamp": 1720097702081,
  "event": {
    "request": {
      "url": "https://nuxt500errorreproduction.pages.dev/",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "accept-encoding": "gzip, br",
        "accept-language": "en-US,en;q=0.9,ru;q=0.8",
        "cache-control": "max-age=0",
        "cf-connecting-ip": "[Redacted for privacy]",
        "cf-ipcountry": "[Redacted for privacy]",
        "cf-ray": "89df446df927b647",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "nuxt500errorreproduction.pages.dev",
        "priority": "u=0, i",
        "sec-ch-ua": "\"Not/A)Brand\";v=\"8\", \"Chromium\";v=\"126\", \"Google Chrome\";v=\"126\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "none",
        "sec-fetch-user": "?1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "[Redacted for privacy]"
      },
      "cf": {
        "clientTcpRtt": 20,
        "longitude": "[Redacted for privacy]",
        "httpProtocol": "HTTP/2",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "[Redacted for privacy]",
        "asn": 12735,
        "clientAcceptEncoding": "gzip, deflate, br, zstd",
        "country": "[Redacted for privacy]",
        "verifiedBotCategory": "",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsClientHelloLength": "1735",
        "tlsExportedAuthenticator": {
          "clientFinished": "14ac1f3362bbfcddb67948b52d9fa1f8421e79253081f669e8a62a81a785127c",
          "clientHandshake": "885bd4ba55c2bf39151d881b88728998a429e5fd0d71af6a980c666a4f85fe9f",
          "serverHandshake": "afd501fca2e1155ea5d7d605e1613b442d96cf7236e4b6747918ed7b25283400",
          "serverFinished": "e37617d752c17b6f8ae6f74e6ed09398ab3c434f7898063c95917f60b0806680"
        },
        "tlsVersion": "TLSv1.3",
        "city": "[Redacted for privacy]",
        "timezone": "[Redacted for privacy]",
        "tlsClientExtensionsSha1": "KiPlZXnmRRe3mY/U2EDRKWxYGFI=",
        "region": "[Redacted for privacy]",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=256;exclusive=1",
        "latitude": "[Redacted for privacy]",
        "postalCode": "[Redacted for privacy]",
        "tlsClientRandom": "HsxAoV17a3U3WE02vmbHCjWI0po/39vQ8GWDtehIe4o=",
        "regionCode": "[Redacted for privacy]",
        "asOrganization": "[Redacted for privacy]",
        "colo": "[Redacted for privacy]",
        "pagesHostName": "nuxt500errorreproduction.pages.dev",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 0
}
```

Build logs:
```log
2024-07-04T12:53:08.339673Z	Cloning repository...
2024-07-04T12:53:08.977281Z	From https://github.com/wtlgo/Nuxt500ErrorReproduction
2024-07-04T12:53:08.977829Z	 * branch            dc13fe04c876a3576003e4db4ff99914b5651b62 -> FETCH_HEAD
2024-07-04T12:53:08.977934Z	
2024-07-04T12:53:09.007541Z	HEAD is now at dc13fe0 Add a single page
2024-07-04T12:53:09.008184Z	
2024-07-04T12:53:09.094861Z	
2024-07-04T12:53:09.095401Z	Using v2 root directory strategy
2024-07-04T12:53:09.120886Z	Success: Finished cloning repository files
2024-07-04T12:53:10.717665Z	Checking for configuration in a wrangler.toml configuration file (BETA)
2024-07-04T12:53:10.718292Z	
2024-07-04T12:53:10.807308Z	No wrangler.toml file found. Continuing.
2024-07-04T12:53:13.556749Z	Detected the following tools from environment: nodejs@22.4.0, pnpm@9.4.0
2024-07-04T12:53:13.557389Z	Installing nodejs 22.4.0
2024-07-04T12:53:14.083936Z	Trying to update node-build... ok
2024-07-04T12:53:14.191006Z	To follow progress, use 'tail -f /tmp/node-build.20240704125314.682.log' or pass --verbose
2024-07-04T12:53:14.313233Z	Downloading node-v22.4.0-linux-x64.tar.gz...
2024-07-04T12:53:14.438265Z	-> https://nodejs.org/dist/v22.4.0/node-v22.4.0-linux-x64.tar.gz
2024-07-04T12:53:16.24433Z	Installing node-v22.4.0-linux-x64...
2024-07-04T12:53:16.643769Z	Installed node-v22.4.0-linux-x64 to /opt/buildhome/.asdf/installs/nodejs/22.4.0
2024-07-04T12:53:16.644235Z	
2024-07-04T12:53:18.107779Z	Preparing pnpm@9.4.0 for immediate activation...
2024-07-04T12:53:20.015164Z	Installing project dependencies: pnpm install
2024-07-04T12:53:20.6886Z	Lockfile is up to date, resolution step is skipped
2024-07-04T12:53:20.740472Z	Progress: resolved 1, reused 0, downloaded 0, added 0
2024-07-04T12:53:20.908253Z	Packages: +659
2024-07-04T12:53:20.908933Z	++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2024-07-04T12:53:21.742026Z	Progress: resolved 659, reused 0, downloaded 130, added 128
2024-07-04T12:53:22.741939Z	Progress: resolved 659, reused 0, downloaded 362, added 356
2024-07-04T12:53:23.741782Z	Progress: resolved 659, reused 0, downloaded 576, added 575
2024-07-04T12:53:24.110878Z	Progress: resolved 659, reused 0, downloaded 659, added 659, done
2024-07-04T12:53:24.372377Z	.../node_modules/protobufjs postinstall$ node scripts/postinstall
2024-07-04T12:53:24.402893Z	.../esbuild@0.23.0/node_modules/esbuild postinstall$ node install.js
2024-07-04T12:53:24.403674Z	.../esbuild@0.21.5/node_modules/esbuild postinstall$ node install.js
2024-07-04T12:53:24.404269Z	.../esbuild@0.20.2/node_modules/esbuild postinstall$ node install.js
2024-07-04T12:53:24.450197Z	.../node_modules/protobufjs postinstall: Done
2024-07-04T12:53:24.50038Z	.../esbuild@0.23.0/node_modules/esbuild postinstall: Done
2024-07-04T12:53:24.508435Z	.../esbuild@0.21.5/node_modules/esbuild postinstall: Done
2024-07-04T12:53:24.524873Z	.../esbuild@0.20.2/node_modules/esbuild postinstall: Done
2024-07-04T12:53:24.643444Z	
2024-07-04T12:53:24.643696Z	dependencies:
2024-07-04T12:53:24.643854Z	+ nuxt 3.12.3
2024-07-04T12:53:24.643963Z	+ vue 3.4.31
2024-07-04T12:53:24.644073Z	
2024-07-04T12:53:24.649525Z	
2024-07-04T12:53:24.649816Z	> nuxt-app@ postinstall /opt/buildhome/repo
2024-07-04T12:53:24.649915Z	> nuxt prepare
2024-07-04T12:53:24.64998Z	
2024-07-04T12:53:26.730308Z	[success] Types generated in .nuxt
2024-07-04T12:53:26.746718Z	Done in 6.3s
2024-07-04T12:53:26.809786Z	Executing user command: pnpm run build
2024-07-04T12:53:27.447633Z	
2024-07-04T12:53:27.447855Z	> nuxt-app@ build /opt/buildhome/repo
2024-07-04T12:53:27.447948Z	> nuxt build
2024-07-04T12:53:27.448061Z	
2024-07-04T12:53:27.694848Z	[log] Nuxt 3.12.3 with Nitro 2.9.7
2024-07-04T12:53:30.218601Z	[info] Building client...
2024-07-04T12:53:30.231079Z	[info] [36mvite v5.3.3 [32mbuilding for production...[36m[39m
2024-07-04T12:53:30.252572Z	[info] transforming...
2024-07-04T12:53:31.359723Z	[info] [32m✓[39m 119 modules transformed.
2024-07-04T12:53:31.435744Z	[info] rendering chunks...
2024-07-04T12:53:31.490361Z	[info] computing gzip size...
2024-07-04T12:53:31.49764Z	[info] [2m.nuxt/dist/client/[22m[32mmanifest.json                 [39m[1m[2m  3.12 kB[22m[1m[22m[2m │ gzip:  0.48 kB[22m
2024-07-04T12:53:31.497894Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[35merror-500.LN8yZVBe.css  [39m[1m[2m  1.88 kB[22m[1m[22m[2m │ gzip:  0.72 kB[22m
2024-07-04T12:53:31.498039Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[35merror-404.HZTjOu-6.css  [39m[1m[2m  3.56 kB[22m[1m[22m[2m │ gzip:  1.10 kB[22m
2024-07-04T12:53:31.498152Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36mDTsAsuJj.js             [39m[1m[2m  0.16 kB[22m[1m[22m[2m │ gzip:  0.16 kB[22m
2024-07-04T12:53:31.498225Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36mBHc3BJTL.js             [39m[1m[2m  0.38 kB[22m[1m[22m[2m │ gzip:  0.27 kB[22m
2024-07-04T12:53:31.498403Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36mkQkyBfnf.js             [39m[1m[2m  2.77 kB[22m[1m[22m[2m │ gzip:  1.24 kB[22m
2024-07-04T12:53:31.498524Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36mCIq9cUhB.js             [39m[1m[2m  8.23 kB[22m[1m[22m[2m │ gzip:  3.35 kB[22m
2024-07-04T12:53:31.498632Z	[info] [2m.nuxt/dist/client/[22m[2m_nuxt/[22m[36mCynDA5h-.js             [39m[1m[2m151.48 kB[22m[1m[22m[2m │ gzip: 57.60 kB[22m
2024-07-04T12:53:31.498736Z	[info] [32m✓ built in 1.27s[39m
2024-07-04T12:53:31.498984Z	[success] Client built in 1280ms
2024-07-04T12:53:31.503263Z	[info] Building server...
2024-07-04T12:53:31.504848Z	[info] [36mvite v5.3.3 [32mbuilding SSR bundle for production...[36m[39m
2024-07-04T12:53:31.511711Z	[info] transforming...
2024-07-04T12:53:32.252427Z	[info] [32m✓[39m 84 modules transformed.
2024-07-04T12:53:32.299706Z	[info] rendering chunks...
2024-07-04T12:53:32.418487Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[32merror-404-styles.CZDg9W6x.mjs       [39m[1m[2m  0.08 kB[22m[1m[22m
2024-07-04T12:53:32.418715Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[32merror-500-styles.DXJajQzp.mjs       [39m[1m[2m  0.08 kB[22m[1m[22m
2024-07-04T12:53:32.418807Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[32merror-404-styles.CNvk8dCs.mjs       [39m[1m[2m  0.15 kB[22m[1m[22m
2024-07-04T12:53:32.419166Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[32merror-500-styles.DdAMz2I4.mjs       [39m[1m[2m  0.15 kB[22m[1m[22m
2024-07-04T12:53:32.419645Z	[info] [2m.nuxt/dist/server/[22m[32mstyles.mjs                                [39m[1m[2m  1.25 kB[22m[1m[22m
2024-07-04T12:53:32.419751Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36mvue.f36acd1f-DvSg21Lc.js            [39m[1m[2m  0.82 kB[22m[1m[22m[2m │ map:   1.81 kB[22m
2024-07-04T12:53:32.419823Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36mindex-DfmZmFnT.js                   [39m[1m[2m  1.04 kB[22m[1m[22m[2m │ map:   0.25 kB[22m
2024-07-04T12:53:32.419889Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36merror-500-styles-1.mjs-CR-8sZoI.js  [39m[1m[2m  2.10 kB[22m[1m[22m[2m │ map:   0.12 kB[22m
2024-07-04T12:53:32.41995Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36merror-404-styles-1.mjs-D2GE5Q_k.js  [39m[1m[2m  3.80 kB[22m[1m[22m[2m │ map:   0.12 kB[22m
2024-07-04T12:53:32.420008Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36merror-500-rFk1U41d.js               [39m[1m[2m  4.14 kB[22m[1m[22m[2m │ map:   4.73 kB[22m
2024-07-04T12:53:32.420075Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36mmultipart-parser-CA9JHtaM.js        [39m[1m[2m  6.91 kB[22m[1m[22m[2m │ map:  10.87 kB[22m
2024-07-04T12:53:32.420133Z	[info] [2m.nuxt/dist/server/[22m[2m_nuxt/[22m[36merror-404-DBLo15W4.js               [39m[1m[2m 13.47 kB[22m[1m[22m[2m │ map:  24.62 kB[22m
2024-07-04T12:53:32.420266Z	[info] [2m.nuxt/dist/server/[22m[36mserver.mjs                                [39m[1m[2m301.42 kB[22m[1m[22m[2m │ map: 602.24 kB[22m
2024-07-04T12:53:32.420376Z	[info] [32m✓ built in 914ms[39m
2024-07-04T12:53:32.421739Z	[success] Server built in 918ms
2024-07-04T12:53:32.481869Z	[success] [nitro] Generated public dist
2024-07-04T12:53:32.500593Z	[info] [nitro] Building Nuxt Nitro server (preset: `cloudflare-pages`)
2024-07-04T12:53:37.992456Z	[success] [nitro] Nuxt Nitro server built
2024-07-04T12:53:38.007943Z	  ├─ dist/_worker.js/chunks/_/error-500.mjs (4.68 kB) (2.01 kB gzip)
2024-07-04T12:53:38.008542Z	  ├─ dist/_worker.js/chunks/_/error-500.mjs.map (426 B) (299 B gzip)
2024-07-04T12:53:38.00873Z	  ├─ dist/_worker.js/chunks/build/client.manifest.mjs (3.2 kB) (534 B gzip)
2024-07-04T12:53:38.00907Z	  ├─ dist/_worker.js/chunks/build/client.manifest.mjs.map (1.06 kB) (405 B gzip)
2024-07-04T12:53:38.009602Z	  ├─ dist/_worker.js/chunks/build/error-404-DBLo15W4.mjs (7.32 kB) (2.91 kB gzip)
2024-07-04T12:53:38.009704Z	  ├─ dist/_worker.js/chunks/build/error-404-DBLo15W4.mjs.map (6.75 kB) (2.88 kB gzip)
2024-07-04T12:53:38.010084Z	  ├─ dist/_worker.js/chunks/build/error-404-styles-1.mjs-D2GE5Q_k.mjs (3.67 kB) (1.18 kB gzip)
2024-07-04T12:53:38.010168Z	  ├─ dist/_worker.js/chunks/build/error-404-styles-1.mjs-D2GE5Q_k.mjs.map (264 B) (200 B gzip)
2024-07-04T12:53:38.010247Z	  ├─ dist/_worker.js/chunks/build/error-404-styles.CNvk8dCs.mjs (149 B) (146 B gzip)
2024-07-04T12:53:38.010396Z	  ├─ dist/_worker.js/chunks/build/error-404-styles.CNvk8dCs.mjs.map (252 B) (180 B gzip)
2024-07-04T12:53:38.010488Z	  ├─ dist/_worker.js/chunks/build/error-404-styles.CZDg9W6x.mjs (147 B) (144 B gzip)
2024-07-04T12:53:38.010585Z	  ├─ dist/_worker.js/chunks/build/error-404-styles.CZDg9W6x.mjs.map (236 B) (175 B gzip)
2024-07-04T12:53:38.010662Z	  ├─ dist/_worker.js/chunks/build/error-500-rFk1U41d.mjs (3.14 kB) (1.45 kB gzip)
2024-07-04T12:53:38.010721Z	  ├─ dist/_worker.js/chunks/build/error-500-rFk1U41d.mjs.map (1.24 kB) (675 B gzip)
2024-07-04T12:53:38.010778Z	  ├─ dist/_worker.js/chunks/build/error-500-styles-1.mjs-CR-8sZoI.mjs (1.98 kB) (794 B gzip)
2024-07-04T12:53:38.010832Z	  ├─ dist/_worker.js/chunks/build/error-500-styles-1.mjs-CR-8sZoI.mjs.map (264 B) (201 B gzip)
2024-07-04T12:53:38.010887Z	  ├─ dist/_worker.js/chunks/build/error-500-styles.DdAMz2I4.mjs (149 B) (146 B gzip)
2024-07-04T12:53:38.010957Z	  ├─ dist/_worker.js/chunks/build/error-500-styles.DdAMz2I4.mjs.map (252 B) (182 B gzip)
2024-07-04T12:53:38.011021Z	  ├─ dist/_worker.js/chunks/build/error-500-styles.DXJajQzp.mjs (147 B) (144 B gzip)
2024-07-04T12:53:38.011105Z	  ├─ dist/_worker.js/chunks/build/error-500-styles.DXJajQzp.mjs.map (236 B) (176 B gzip)
2024-07-04T12:53:38.011166Z	  ├─ dist/_worker.js/chunks/build/index-DfmZmFnT.mjs (390 B) (283 B gzip)
2024-07-04T12:53:38.011229Z	  ├─ dist/_worker.js/chunks/build/index-DfmZmFnT.mjs.map (586 B) (358 B gzip)
2024-07-04T12:53:38.011385Z	  ├─ dist/_worker.js/chunks/build/multipart-parser-CA9JHtaM.mjs (4.66 kB) (2 kB gzip)
2024-07-04T12:53:38.011501Z	  ├─ dist/_worker.js/chunks/build/multipart-parser-CA9JHtaM.mjs.map (6.48 kB) (2.66 kB gzip)
2024-07-04T12:53:38.011641Z	  ├─ dist/_worker.js/chunks/build/server.mjs (177 kB) (52.2 kB gzip)
2024-07-04T12:53:38.011784Z	  ├─ dist/_worker.js/chunks/build/server.mjs.map (24.3 kB) (8.74 kB gzip)
2024-07-04T12:53:38.011885Z	  ├─ dist/_worker.js/chunks/build/styles.mjs (1.24 kB) (396 B gzip)
2024-07-04T12:53:38.011988Z	  ├─ dist/_worker.js/chunks/build/styles.mjs.map (396 B) (232 B gzip)
2024-07-04T12:53:38.012087Z	  ├─ dist/_worker.js/chunks/build/vue.f36acd1f-DvSg21Lc.mjs (387 B) (277 B gzip)
2024-07-04T12:53:38.012276Z	  ├─ dist/_worker.js/chunks/build/vue.f36acd1f-DvSg21Lc.mjs.map (746 B) (433 B gzip)
2024-07-04T12:53:38.012454Z	  ├─ dist/_worker.js/chunks/routes/renderer.mjs (119 kB) (40.2 kB gzip)
2024-07-04T12:53:38.012526Z	  ├─ dist/_worker.js/chunks/routes/renderer.mjs.map (26.1 kB) (8.84 kB gzip)
2024-07-04T12:53:38.012712Z	  ├─ dist/_worker.js/chunks/runtime.mjs (112 kB) (34.2 kB gzip)
2024-07-04T12:53:38.012792Z	  ├─ dist/_worker.js/chunks/runtime.mjs.map (22.1 kB) (7.33 kB gzip)
2024-07-04T12:53:38.012952Z	  ├─ dist/_worker.js/chunks/virtual/_virtual_spa-template.mjs (85 B) (99 B gzip)
2024-07-04T12:53:38.013068Z	  ├─ dist/_worker.js/chunks/virtual/_virtual_spa-template.mjs.map (108 B) (108 B gzip)
2024-07-04T12:53:38.013188Z	  └─ dist/_worker.js/index.js (139 B) (144 B gzip)
2024-07-04T12:53:38.013386Z	Σ Total size: 531 kB (173 kB gzip)
2024-07-04T12:53:38.014624Z	[success] [nitro] You can preview this build using `npx wrangler pages dev dist/`
2024-07-04T12:53:38.01473Z	[success] [nitro] You can deploy this build using `npx wrangler pages deploy dist/`
2024-07-04T12:53:38.11713Z	Finished
2024-07-04T12:53:38.118067Z	Found _worker.js in output directory. Uploading.
2024-07-04T12:53:39.146581Z	Attaching additional modules:
2024-07-04T12:53:39.158146Z	┌──────────────────────────────────────────────────┬──────┬────────────┐
2024-07-04T12:53:39.158439Z	│ Name                                             │ Type │ Size       │
2024-07-04T12:53:39.158654Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.158738Z	│ chunks/_/error-500.mjs                           │ esm  │ 4.57 KiB   │
2024-07-04T12:53:39.158801Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.158875Z	│ chunks/build/client.manifest.mjs                 │ esm  │ 3.13 KiB   │
2024-07-04T12:53:39.158973Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.159067Z	│ chunks/build/error-404-DBLo15W4.mjs              │ esm  │ 7.15 KiB   │
2024-07-04T12:53:39.159234Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.159513Z	│ chunks/build/error-404-styles-1.mjs-D2GE5Q_k.mjs │ esm  │ 3.59 KiB   │
2024-07-04T12:53:39.159664Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.159821Z	│ chunks/build/error-404-styles.CNvk8dCs.mjs       │ esm  │ 0.15 KiB   │
2024-07-04T12:53:39.159993Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.160089Z	│ chunks/build/error-404-styles.CZDg9W6x.mjs       │ esm  │ 0.14 KiB   │
2024-07-04T12:53:39.160191Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.160293Z	│ chunks/build/error-500-rFk1U41d.mjs              │ esm  │ 3.07 KiB   │
2024-07-04T12:53:39.160405Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.160509Z	│ chunks/build/error-500-styles-1.mjs-CR-8sZoI.mjs │ esm  │ 1.93 KiB   │
2024-07-04T12:53:39.16061Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.160711Z	│ chunks/build/error-500-styles.DXJajQzp.mjs       │ esm  │ 0.14 KiB   │
2024-07-04T12:53:39.160813Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.160917Z	│ chunks/build/error-500-styles.DdAMz2I4.mjs       │ esm  │ 0.15 KiB   │
2024-07-04T12:53:39.161011Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.161096Z	│ chunks/build/index-DfmZmFnT.mjs                  │ esm  │ 0.38 KiB   │
2024-07-04T12:53:39.161207Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.161463Z	│ chunks/build/multipart-parser-CA9JHtaM.mjs       │ esm  │ 4.55 KiB   │
2024-07-04T12:53:39.161649Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.161745Z	│ chunks/build/server.mjs                          │ esm  │ 172.68 KiB │
2024-07-04T12:53:39.161962Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.16208Z	│ chunks/build/styles.mjs                          │ esm  │ 1.21 KiB   │
2024-07-04T12:53:39.162196Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.162397Z	│ chunks/build/vue.f36acd1f-DvSg21Lc.mjs           │ esm  │ 0.38 KiB   │
2024-07-04T12:53:39.162476Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.162544Z	│ chunks/routes/renderer.mjs                       │ esm  │ 116.04 KiB │
2024-07-04T12:53:39.162919Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.163168Z	│ chunks/runtime.mjs                               │ esm  │ 109.39 KiB │
2024-07-04T12:53:39.163594Z	├──────────────────────────────────────────────────┼──────┼────────────┤
2024-07-04T12:53:39.164552Z	│ chunks/virtual/_virtual_spa-template.mjs         │ esm  │ 0.08 KiB   │
2024-07-04T12:53:39.16466Z	└──────────────────────────────────────────────────┴──────┴────────────┘
2024-07-04T12:53:39.198168Z	✨ Compiled Worker successfully
2024-07-04T12:53:39.260179Z	Found _routes.json in output directory. Uploading.
2024-07-04T12:53:39.273111Z	Validating asset output directory
2024-07-04T12:53:41.074184Z	Deploying your site to Cloudflare's global network...
2024-07-04T12:53:43.061077Z	Parsed 3 valid header rules.
2024-07-04T12:53:44.583543Z	Uploading... (3/11)
2024-07-04T12:53:45.270777Z	Uploading... (5/11)
2024-07-04T12:53:45.387873Z	Uploading... (8/11)
2024-07-04T12:53:45.551809Z	Uploading... (11/11)
2024-07-04T12:53:45.552081Z	✨ Success! Uploaded 8 files (3 already uploaded) (1.60 sec)
2024-07-04T12:53:45.552216Z	
2024-07-04T12:53:46.089935Z	✨ Upload complete!
2024-07-04T12:53:48.092487Z	Success: Assets published!
2024-07-04T12:53:50.689836Z	Success: Your site was deployed!
```

**Comment by danielroe** [comment]
Is this resolved if you add `vue-router` as a dependency?

**Comment by wtlgo** [comment]
Yes, it did help. Is it written somewhere I should add it tho? I don't remember it being mentioned anywhere

**Comment by danielroe** [comment]
No, it's likely a Nuxt or Nitro bug that we need to investigate.
