### ISSUE TITLE
initNitro - Cannot start nuxt:  Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tankosinn** [nuxt/nuxt#28044]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.11.0`
- Nuxt Version:     `3.12.3`
- CLI Version:      `3.12.0`
- Nitro Version:    `2.9.7`
- Package Manager:  `yarn@4.3.1`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[Reproduction on StackBlitz](https://stackblitz.com/edit/github-x1iob7?file=modules%2Fmask%2Findex.ts)

### Describe the bug

There is an issue when setting the metadata from libphonenumber-js/min/metadata to the default module options in my Nuxt module for input mask generation. Specifically, when the metadata is included in the default options, an error occurs. However, the error is resolved when metadata is not set in the module options.

When i follow the error, error is occurring from initNitro. 

### Logs

```shell-script
ERROR  Cannot start nuxt:  Maximum call stack size exceeded                                                                                                                                   11:42:45 AM

  at Array.hasOwnProperty (<anonymous>)
  at klona (/Users/keremmermer/Playground/livinsoft-plus/node_modules/klona/full/index.mjs:47:30)
  at set (/Users/keremmermer/Playground/livinsoft-plus/node_modules/klona/full/index.mjs:2:49)
  at klona (/Users/keremmermer/Playground/livinsoft-plus/node_modules/klona/full/index.mjs:48:4)
  at set (/Users/keremmermer/Playground/livinsoft-plus/node_modules/klona/full/index.mjs:2:49)
  at klona (/Users/keremmermer/Playground/livinsoft-plus/node_modules/klona/full/index.mjs:48:4)
  at set (/Users/keremmermer/Playground/livinsoft-plus/node_modules/klona/full/index.mjs:2:49)
  at klona (/Users/keremmermer/Playground/livinsoft-plus/node_modules/klona/full/index.mjs:48:4)
  at set (/Users/keremmermer/Playground/livinsoft-plus/node_modules/klona/full/index.mjs:2:49)
  at klona (/Users/keremmermer/Playground/livinsoft-plus/node_modules/klona/full/index.mjs:48:4)
```

**Comment by manniL** [comment]
It seems like `metadata` is simply too much data for `klona` and a recursive deep-clone approach.
