### ISSUE TITLE
Prerendering SSG fails on Cloudflare but not locally

### ISSUE THREAD

**Issue by Atulin** [nuxt/nuxt#28112]
### Environment

- Operating System: Windows_NT
- Node Version:     v21.6.2
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  bun@1.1.18
- Builder:          -
- User Config:      devtools, compatibilityDate, css, modules, plugins, watch, svgo, app
- Runtime Modules:  @nuxt/image@1.7.0, nuxt-svgo-loader@0.4.0, @pinia/nuxt@0.5.1, nuxt-svgo@4.0.1
- Build Modules:    -

### Reproduction

Zod schema

```ts
import dayjs from "dayjs";
import { z } from "zod";

export const changelogSchema = z
	.array(
		z.object({
			date: z.string().transform((d) => dayjs(d).format("YYYY-MM-DD")),
			body: z.string(),
		}),
	)
	.transform((changelogs) => changelogs.toSorted((a, b) => dayjs(b.date).valueOf() - dayjs(a.date).valueOf()));

```

Data to be imported
```json
[
  {
    "body": "-",
    "date": "2024-06-25 03:33:13+0200"
  },
  {
    "body": "<ul>\n<li>Settings menu with filter location selection</li>\n</ul>\n",
    "date": "2024-07-03 21:15:00+0002"
  },
  {
    "body": "-",
    "date": "2024-07-08 20:20:53+02:00"
  },
  {
    "body": "-",
    "date": "2024-07-08 17:41:17+02:00"
  },
  {
    "body": "-",
    "date": "2024-07-11 07:13:37+02:00"
  }
]
```

The page that causes the issue
```vue
<script setup lang="ts">
import changelog from "~/data/changelog.json";
import { changelogSchema } from "~/schemas/changelog-schema";
useSeoMeta({
	title: "About",
});

const { success, data: changelogs, error } = changelogSchema.safeParse(changelog);
</script>

<template>
	<h2>Changelog</h2>
	<div v-if="success" v-for="ch in changelogs" :key="ch.date" class="changelog">
		<h3>{{ ch.date }}</h3>
		<div class="body" v-html="ch.body"></div>
	</div>
	<div v-else>{{ error }}</div>
</template>

<style scoped lang="scss">
h2 {
	margin-bottom: 1rem;
}
.changelog {
	border: 1px solid var(--lighten);
	padding: 1rem;
	margin-bottom: 0.5rem;
	h3 {
		margin-bottom: 0.5rem;
	}
	.body {
		line-height: 1.4rem;
		:deep(ul, ol) {
			padding-left: 1.5rem;
		}

		:deep(table) {
			border-collapse: collapse;
			margin-top: 0.5rem;

			td,
			th {
				padding: 0.25rem 0.5rem;
			}

			th {
				text-transform: capitalize;
				font-variant: small-caps;
				letter-spacing: 0.2rem;
			}

			tbody {
				tr {
					border-bottom: 1px solid var(--lighten);

					&:hover {
						background-color: var(--light-accent);
					}
				}
			}

			thead {
				background-color: var(--lighten);
			}
		}
	}
}
</style>
```

Nuxt config
```ts
export default defineNuxtConfig({
	devtools: { enabled: true },
	compatibilityDate: "2024-07-08",
	css: ["~/assets/global.scss"],
	modules: ["@nuxt/image", "nuxt-svgo-loader", "@pinia/nuxt", "nuxt-svgo"],
	plugins: [],
	watch: ["data"],
	svgo: {
		componentPrefix: "Icon",
	},
	app: {
		head: {
			title: "Tierlist Stars",
			titleTemplate: "%s %separator %siteName",
			templateParams: {
				separator: "—",
				siteName: "My Cool Site",
			},
			htmlAttrs: {
				lang: "en",
			},
			meta: [
				{ charset: "utf-8" },
				{ name: "viewport", content: "width=device-width, initial-scale=1" },
				{ hid: "description", name: "description", content: "My Cool Site" },
				{ name: "msapplication-TileColor", content: "#ffffff" },
				{ name: "msapplication-TileImage", content: "/ms-icon-144x144.png" },
				{ name: "theme-color", content: "#ffffff" },
			],
			link: [
				{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" },
				{ rel: "apple-touch-icon", sizes: "57x57", href: "/apple-icon-57x57.png" },
				{ rel: "apple-touch-icon", sizes: "60x60", href: "/apple-icon-60x60.png" },
				{ rel: "apple-touch-icon", sizes: "72x72", href: "/apple-icon-72x72.png" },
				{ rel: "apple-touch-icon", sizes: "76x76", href: "/apple-icon-76x76.png" },
				{ rel: "apple-touch-icon", sizes: "114x114", href: "/apple-icon-114x114.png" },
				{ rel: "apple-touch-icon", sizes: "120x120", href: "/apple-icon-120x120.png" },
				{ rel: "apple-touch-icon", sizes: "144x144", href: "/apple-icon-144x144.png" },
				{ rel: "apple-touch-icon", sizes: "152x152", href: "/apple-icon-152x152.png" },
				{ rel: "apple-touch-icon", sizes: "180x180", href: "/apple-icon-180x180.png" },
				{ rel: "icon", type: "image/png", sizes: "192x192", href: "/android-icon-192x192.png" },
				{ rel: "icon", type: "image/png", sizes: "32x32", href: "/favicon-32x32.png" },
				{ rel: "icon", type: "image/png", sizes: "96x96", href: "/favicon-96x96.png" },
				{ rel: "icon", type: "image/png", sizes: "16x16", href: "/favicon-16x16.png" },
				// { rel: "manifest", href: "/manifest.json" },
			],
		},
	},
});
```

### Describe the bug

This error is being thrown in the Cloudflare Pages build process:

### Additional context

`nuxt generate` works perfectly well in my local environment. I can build the site locally, and publish it with Wrangler. However, build on Cloudflare **always** fails.

### Logs

```shell-script
> snip <
07:22:15.746 | [log] [nitro]
-- | --
07:22:15.746 | Errors prerendering:
07:22:15.747 | [log] [nitro]   ├─ /about (536ms)
07:22:15.747 | │ ├── Error: [500]
07:22:15.747 | │ └── Linked from /
07:22:15.747 | [log] [nitro]
07:22:15.748 | [error] Exiting due to prerender errors.
07:22:15.748 | at prerender (node_modules/nitropack/dist/chunks/prerender.mjs:220:11)
07:22:15.748 | at async node_modules/nuxt/dist/index.mjs:3605:7
07:22:15.748 | at async build (node_modules/nuxt/dist/index.mjs:5469:5)
07:22:15.748 | at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:94:5)
07:22:15.748 | at async Object.run (node_modules/nuxi/dist/chunks/generate.mjs:55:5)
07:22:15.748 | at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1648:16)
07:22:15.748 | at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1639:11)
07:22:15.749 | at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1777:7)
07:22:15.749 |  
07:22:15.749 | [error] Exiting due to prerender errors.
```

**Comment by danielroe** [comment]
Is this resolved if you add vue/vue-router as explicit dependencies?

**Comment by Atulin** [comment]
It already is added as a dependency:
```json
	"dependencies": {
		"@heroicons/vue": "^2.1.4",
		"@nuxt/image": "^1.7.0",
		"@nuxt/kit": "^3.12.3",
		"@pinia/nuxt": "^0.5.1",
		"marked": "^13.0.2",
		"nuxt": "^3.12.3",
		"nuxt-svgo": "^4.0.1",
		"nuxt-svgo-loader": "^0.4.0",
		"sass": "^1.77.6",
		"vue": "^3.4.31",
		"vue-router": "^4.4.0",
		"zod": "^3.23.8"
	},
	"devDependencies": {
		"@biomejs/biome": "^1.8.3",
		"@types/bun": "^1.1.6",
		"chalk": "^5.3.0",
		"dayjs": "^1.11.11",
		"dedent": "^1.5.3",
		"octokit": "^4.0.2",
		"wrangler": "^3.63.1",
		"yaml": "^2.4.5",
		"zod-to-json-schema": "^3.23.1"
	}
```
