### ISSUE TITLE
Nuxt (ERROR TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function (anonymous)]))

### ISSUE THREAD

**Issue by Arcane6** [nuxt/nuxt#28208]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.16.1
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@9.5.1
- Builder:          -
- User Config:      modules, routeRules, piniaPersistedstate, ui, app, pinia, compatibilityDate
- Runtime Modules:  @nuxt/ui@2.17.0, @pinia/nuxt@0.5.1, @pinia-plugin-persistedstate/nuxt@1.2.1
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/Arcane6/tester

### Describe the bug

When I run the **npm run build** command, it gives me this error. Maybe he's having problems with Pinia's dependencies.

 ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function (anonymous)])                                                                                                          nitro 12:26:55 PM

undefined

 ERROR  The "path" argument must be of type string. Received type function ([Function (anonymous)])                                                                                                                                                  12:26:55 PM

  at new NodeError (node:internal/errors:399:5)
  at validateString (node:internal/validators:163:11)
  at Function.join (node:path:1172:7)
  at Object.mockPath [as then] (node_modules/@vercel/nft/out/analyze.js:174:27) 

 ERROR  The "path" argument must be of type string. Received type function ([Function (anonymous)])   

### Additional context

{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@pinia-plugin-persistedstate/nuxt": "^1.2.1",
    "nuxt": "^3.12.2",
    "vue": "^3.3.4",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@iconify-json/material-symbols": "^1.1.65",
    "@iconify-json/ri": "^1.1.18",
    "@iconify-json/vscode-icons": "^1.1.31",
    "@nuxt/ui": "^2.17.0",
    "@pinia/nuxt": "^0.5.1",
    "nuxt-icon": "^0.6.6",
    "pinia": "^2.1.7",
    "dayjs": "^1.11.11"
  },
  "overrides": {
    "vue": "^3.3.4"
  }
}

### Logs

```shell-script
ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function (anonymous)])                                                                                                          nitro 12:26:55 PM


undefined


 ERROR  The "path" argument must be of type string. Received type function ([Function (anonymous)])                                                                                                                                                  12:26:55 PM

  at new NodeError (node:internal/errors:399:5)
  at validateString (node:internal/validators:163:11)
  at Function.join (node:path:1172:7)
  at Object.mockPath [as then] (node_modules/@vercel/nft/out/analyze.js:174:27) 



 ERROR  The "path" argument must be of type string. Received type function ([Function (anonymous)])
```

**Comment by Arcane6** [comment]
Any idea what it could be?

**Comment by DiasNeto0305** [comment]
I had the same error with my project. Any update?

**Comment by ashraf7hossain** [comment]
@DiasNeto0305 and @Arcane6 
I was facing similar issue in my nuxt project and I figured out I was using 
import { errorMessages } from 'vue/compiler-sfc';
you can check whether you guys are using similar imports that are irrelevant for build.
Also make sure your import paths are correct.

**Comment by aiktb** [comment]
I have the same issue, I get this error when calling parse from `vue/compiler-sfc`, but not from `@vue/compiler-sfc`.

Is anyone following up on this issue? Why can't I do this?

**Comment by aiktb** [comment]
> I have the same issue, I get this error when calling parse from `vue/compiler-sfc`, but not from `@vue/compiler-sfc`.
> 
> Is anyone following up on this issue? Why can't I do this?

[UPDATE]: This solution is not valid and will cause `nuxt preivew` to report an error: "velocityjs" not found.

I didn't find the right way to use vue sfc-compiler in nuxt.

**Comment by israelalagbe** [comment]
> [@DiasNeto0305](https://github.com/DiasNeto0305) and [@Arcane6](https://github.com/Arcane6) I was facing similar issue in my nuxt project and I figured out I was using `import { errorMessages } from 'vue/compiler-sfc'; ` As I removed this from by code the issue resolved. You can check whether you are using similar imports that are irrelevant for build. Also make sure your import paths are correct.

Thank you, I was also having a similar issue and this fixed it
