### ISSUE TITLE
Error cause is not available in error page when using `createError()`

### ISSUE THREAD

**Issue by bgondy** [nuxt/nuxt#28202]
### Environment

```
~/projects/zzmivzgbnw.github
❯ npx nuxi info
Working directory: /home/projects/zzmivzgbnw.github                                                                    14:15:48
Nuxt project info:                                                                                                     14:15:48

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.3
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-v4a5gc?file=app.vue

### Describe the bug

When throwing an error via `createError()`, the optional `cause` option is not forwarded to the error prop in `error.vue`. If I'm not using this function as intended, please let me know.

Given this example in a component : 

```vue
<script setup lang="ts">
try {
  throw new Error('first error', { cause: new Error('first error cause') });
} catch (error) {
  throw createError({
    message: `createError message`,
    statusCode: 500,
    cause: error,
  });
}
</script>
```

There is no `cause` in `error.vue`.

```json
{
  "error": {
    "url": "/",
    "statusCode": 500,
    "statusMessage": "",
    "message": "createError message",
    "stack": "<pre><span class=\"stack internal\">at new H3Error (./node_modules/h3/dist/index.mjs:170:5)</span>\n<span class=\"stack internal\">at Module.createError (./node_modules/h3/dist/index.mjs:203:15)</span>\n<span class=\"stack internal\">at Module.createError (./node_modules/nuxt/dist/app/composables/error.js:43:43)</span>\n<span class=\"stack\">at setup (./app.vue:20:35)</span>\n<span class=\"stack\">at _sfc_main.setup (./app.vue:46:23)</span>\n<span class=\"stack internal\">at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:203:19)</span>\n<span class=\"stack internal\">at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7649:25)</span>\n<span class=\"stack internal\">at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7610:36)</span>\n<span class=\"stack internal\">at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:624:15)</span>\n<span class=\"stack internal\">at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)</span></pre>"
  }
}
```

<details>
<summary>Printed stacktrace without HTML tags</summary>

```text
at new H3Error (./node_modules/h3/dist/index.mjs:170:5)
at Module.createError (./node_modules/h3/dist/index.mjs:203:15)
at Module.createError (./node_modules/nuxt/dist/app/composables/error.js:43:43)
at setup (./app.vue:20:35)
at _sfc_main.setup (./app.vue:46:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:203:19)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7649:25)
at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7610:36)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:624:15)
at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
```

</details>

Moreover, the stacktrace doesn't contain error cause(s). In pure js, given the following file, error causes are nested. Here is an example :

```js
// example.js
try {
  throw new Error('first error', {cause: new Error('first error cause')});
} catch (e) {
  throw new Error('final error', {cause: e});
}
```

I get the following output :

```text
❯ node example.js
/Users/benjamin/projects/sandbox/example.js:4
Error: final error
    at Object.<anonymous> (/Users/benjamin/projects/sandbox/example.js:4:9)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    ... 4 lines matching cause stack trace ...
    at node:internal/main/run_main_module:28:49 {
  [cause]: Error: first error
      at Object.<anonymous> (/Users/benjamin/projects/sandbox/example.js:2:9)
      at Module._compile (node:internal/modules/cjs/loader:1369:14)
      ... 4 lines matching cause stack trace ...
      at node:internal/main/run_main_module:28:49 {
    [cause]: Error: first error cause
        at Object.<anonymous> (/Users/benjamin/projects/sandbox/example.js:2:42)
        at Module._compile (node:internal/modules/cjs/loader:1369:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
        at Module.load (node:internal/modules/cjs/loader:1206:32)
        at Module._load (node:internal/modules/cjs/loader:1022:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
        at node:internal/main/run_main_module:28:49
  }
}

Node.js v20.12.2
```

It makes debugging much easier.

It would be nice to have the error cause available (to display during development) and the full stacktrace, even in the default error page.

**Comment by bgondy** [comment]
Any update on this?

**Comment by TimGonnet** [comment]
It would be really good to have the cause in development actually

**Comment by L422Y** [comment]
This is definitely something that would be nice, at least to be able to see the stack trace in the console or something, not having that is a huge issue when debugging sometimes.
