### ISSUE TITLE
Unable to start server with `inlineDynamicImports` in Nuxt 3.12.4 but works well with 3.12.3

### ISSUE THREAD

**Issue by amandesai01** [nuxt/nuxt#28257]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      nitro, srcDir, modules, googleFonts, css, devtools, runtimeConfig
- Runtime Modules:  @nuxtjs/tailwindcss@6.11.4, nuxt-icon@0.6.10, @vee-validate/nuxt@4.13.2, @nuxtjs/google-fonts@3.2.0
- Build Modules:    -
------------------------------

### Reproduction

Package.json
```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "migration:generate": "drizzle-kit generate",
    "migration:apply": "drizzle-kit migrate",
    "drizzle:update": "drizzle-kit up"
  },
  "dependencies": {
    "@nuxtjs/google-fonts": "^3.2.0",
    "@nuxtjs/tailwindcss": "6.11.4",
    "@tailwindcss/forms": "^0.5.7",
    "@vee-validate/nuxt": "^4.13.1",
    "@vee-validate/zod": "^4.13.1",
    "@vueuse/core": "^10.11.0",
    "drizzle-kit": "^0.22.7",
    "drizzle-orm": "^0.31.2",
    "jsonwebtoken": "^9.0.2",
    "jwks-rsa": "^3.1.0",
    "nuxt": "^3.12.4",
    "nuxt-icon": "^0.6.10",
    "pg": "^8.12.0",
    "uncrypto": "^0.1.3",
    "vue": "^3.4.27",
    "vue-router": "^4.3.2",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@types/pg": "^8.11.6"
  }
}
```

nuxt.config.ts
```js
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  nitro: {
    experimental: {
      tasks: true,
    },
    inlineDynamicImports: true,
  },
  srcDir: 'src/',
  modules: ['@nuxtjs/tailwindcss', 'nuxt-icon', '@vee-validate/nuxt', "@nuxtjs/google-fonts"],
  googleFonts: {
    families: {
      "Noto+Sans": [400, 500, 600, 700],
      "Lato": [400, 500, 600, 700],
    },
    useStylesheet: true,
  },
  css: [
    '~/assets/css/style.css',
    '~/assets/css/additional-styles/utility-patterns.css',
  ],
  devtools: { enabled: true },
);
```

### Describe the bug

When I do `yarn dev` or `yarn build`, following error is displayed. rolling back to `3.12.3` fixes the issue.

```
[1:48:44 PM]  WARN  [nuxt] could not import postcss plugin postcss-custom-properties with ESM. Please report this as a bug.


 ERROR  Nuxt Build Error: Cannot find module 'postcss-custom-properties'              1:48:44 PM
Require stack:
- /Users/amandesai/nirvana-labs/vidurjobs-v2/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
  at Function.resolve (node:internal/modules/cjs/helpers:116:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:241814)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2224:29)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2229:24)
  at resolveCSSOptions (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.BohqozL_.mjs:1093:18)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.BohqozL_.mjs:1579:14)
  at async bundle (node_modules/nuxt/dist/index.mjs:5606:5)
  at async Promise.all (index 1)
  at async build (node_modules/nuxt/dist/index.mjs:5478:5)
```

**Comment by amandesai01** [comment]
Prod server is unable to start for all the 3 versions, `3.12.2`, `3.12.3` and `3.12.4`.
Dev server starts successfully in `3.12.2` and `3.12.3`.

This happens when I use `inlineDynammicImports`.

**Comment by amandesai01** [comment]
Apologies for early commenting, removing `inlineDynamicImports` started the server but got the same issue as soon as I tried to load the page.

**Comment by amandesai01** [comment]
Never mind! I fixed the issue with `npx nuxi upgrade` -> Updated to latest version.
