### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by MHillier98** [nuxt/nuxt#28522]
### Environment

- Operating System: Windows_NT (10)
- Node Version:     v20.15.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.7.0
- Builder:          -
- User Config:      future, compatibilityDate, devtools, modules, app, ui, colorMode, gtag, site, nitro, device
- Runtime Modules:  @formkit/auto-animate/nuxt@0.8.2, @nuxt/content@2.13.2, @nuxt/ui@2.18.4, @nuxtjs/device@3.1.1, @nuxtjs/robots@4.0.2, @nuxtjs/seo@2.0.0-rc.18, @nuxtjs/sitemap@6.0.0-beta.1, nuxt-gtag@2.1.0
- Build Modules:    -

### Reproduction

This seems to be my machine only for some reason, sorry!

### Describe the bug

On running `nuxt dev --open` I get the following result:

```
500
Cannot read properties of undefined (reading 'replace')

at normalizeFilenames (http://localhost:3000/_nuxt/@fs/C:/Users/_____/Documents/Dev/Web/WatchStarWars/node_modules/nuxt/dist/app/plugins/dev-server-logs.js?v=9ffb1c1d:44:32)
at normalizeServerLog (http://localhost:3000/_nuxt/@fs/C:/Users/_____/Documents/Dev/Web/WatchStarWars/node_modules/nuxt/dist/app/plugins/dev-server-logs.js?v=9ffb1c1d:56:20)
at http://localhost:3000/_nuxt/@fs/C:/Users/_____/Documents/Dev/Web/WatchStarWars/node_modules/nuxt/dist/app/plugins/dev-server-logs.js?v=9ffb1c1d:28:20
at http://localhost:3000/_nuxt/@fs/C:/Users/_____/Documents/Dev/Web/WatchStarWars/node_modules/hookable/dist/index.mjs?v=9ffb1c1d:48:66
at http://localhost:3000/_nuxt/@fs/C:/Users/_____/Documents/Dev/Web/WatchStarWars/node_modules/hookable/dist/index.mjs?v=9ffb1c1d:48:56
at async http://localhost:3000/_nuxt/@fs/C:/Users/_____/Documents/Dev/Web/WatchStarWars/node_modules/nuxt/dist/app/plugins/dev-server-logs.js?v=9ffb1c1d:35:93
at async applyPlugin (http://localhost:3000/_nuxt/@fs/C:/Users/_____/Documents/Dev/Web/WatchStarWars/node_modules/nuxt/dist/app/nuxt.js?v=9ffb1c1d:137:25)
at async executePlugin (http://localhost:3000/_nuxt/@fs/C:/Users/_____/Documents/Dev/Web/WatchStarWars/node_modules/nuxt/dist/app/nuxt.js?v=9ffb1c1d:173:9)
at async applyPlugins (http://localhost:3000/_nuxt/@fs/C:/Users/_____/Documents/Dev/Web/WatchStarWars/node_modules/nuxt/dist/app/nuxt.js?v=9ffb1c1d:187:5)
at async initApp (http://localhost:3000/_nuxt/C:/Users/_____/Documents/Dev/Web/WatchStarWars/node_modules/nuxt/dist/app/entry.js:47:7)
```

**Comment by danielroe** [comment]
What is the full path to your project directory?

**Comment by MHillier98** [comment]
The full path is just `C:/Users/matth/Documents/Dev/Web/WatchStarWars/node_modules/nuxt` so nothing special about those characters afaik.

I've tried:
- deleting my package-lock + node_modules + build + .nuxt
- removing packages down to just nuxt
- clearing my npm cache
- updating node/npm

**Comment by luminous8** [comment]
I have the same issue after doing a npm update - was doing just fine before 

`- Operating System: Darwin
- Node Version:     v22.3.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      ssr, devtools, compatibilityDate, site, devServer, modules, robots, css, runtimeConfig, routeRules, vite, app, icon
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.1, nuxt-icon@0.6.10, nuxt-auth-utils@0.3.4, @pinia/nuxt@0.5.3, @vueuse/nuxt@10.11.1, @vee-validate/nuxt@4.13.2, @nuxt/image@1.7.0, @nuxtjs/device@3.1.1, nuxt-jsonld@2.0.8, @nuxt/devtools@1.3.9, @nuxt/icon@1.4.5, @nuxt/content@2.13.2, nuxt-jsonld@2.0.8
- Build Modules:    -`

**Comment by MHillier98** [comment]
Not sure if this really helps but the error has changed after updating to the latest `v3.13.1` release using `npx nuxi@latest upgrade --force` but still doesn't work locally

```
 ERROR  Internal server error: ENOENT: no such file or directory, open 'C:\node_modules\nuxt-icon\dist\runtime\Icon.vue'
      at Object.readFileSync (node:fs:448:20)
      at getDescriptor (file:///C:/Users/matth/Documents/Dev/Web/WatchStarWars/node_modules/@vitejs/plugin-vue/dist/index.mjs:93:18)
      at LoadPluginContext.load (file:///C:/Users/matth/Documents/Dev/Web/WatchStarWars/node_modules/@vitejs/plugin-vue/dist/index.mjs:2911:28)
      at PluginContainer.load (file:///C:/Users/matth/Documents/Dev/Web/WatchStarWars/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:49001:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async loadAndTransform (file:///C:/Users/matth/Documents/Dev/Web/WatchStarWars/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:51796:22)
      at async viteTransformMiddleware (file:///C:/Users/matth/Documents/Dev/Web/WatchStarWars/node_modules/vite/dist/node/chunks/dep-BaOMuo4I.js:61810:24)
```

**Comment by danielroe** [comment]
I do still need a reproduction, please 🙏
