### ISSUE TITLE
type checking error for globally imported vitest globals

### ISSUE THREAD

**Issue by suityou01** [nuxt/nuxt#28608]
### Environment

Working directory: /src                                                                                                                                         6:34:10 AM
Nuxt project info:                                                                                                                                              6:34:10 AM

------------------------------
- Operating System: Linux
- Node Version:     v20.16.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.7.1
- Builder:          -
- User Config:      ignore, modules, typescript, css, $development, $production, compatibilityDate
- Runtime Modules:  @pinia/nuxt@0.5.3, nuxt-build-cache@0.1.1, @nuxt/eslint@0.5.1, @nuxt/test-utils/module@3.14.1
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/suityou01/bpm-core-web-template-repro

### Describe the bug

This in and of itself is a project by itself. The key issue as I see it is there is no decent documentation to be able to help me set up this basic todos project using typescript. I want to chose nuxt as the technology of choice for my new start up venture. I'm not exacly what you would call a noob as I have been developing for over 27 years in IT and have used React and next.js for example.

The repro ain't perfect, but it does showcase the problems I am having so it will have to do. I am using VSCode and devcontainers for my project. 

Please also note that in the process of setting up this template project for my development team I have lost around 3 weeks of work just faffing about with this so I am at the end of my rope with nuxt but don't want to admit it. This is the last call for you kind people at nuxt to help before I just walk away from nuxt completely as not fit for my purposes, which I think it a shame as it shows a lot of promise.

So far the problems I am having are around successfully setting up a basic project for typescript, with 2 testing modes, one for my CI pipeline and one for my local development.

To this end I have configured to vitest configs :

vitest.config.ts and
vitest.dev.config.ts

I was warned to create a vitest.workspace.ts by one of the many helpful and error messages that popped up in vscode so I did.

As you will see in the package.json I have configured two test scripts

```json
    "test": "vitest run",
    "test:dev": "vitest --config ./vitest.dev.config.ts run"
```

This is the output when I run test:dev

```bash
> test:dev
> vitest --config ./vitest.dev.config.ts run

[nuxt] modules:before: 0.272ms
[nuxt] kit:compatibility: 22.91ms
[nuxt] kit:compatibility: 23.039ms
[nuxt] kit:compatibility: 23.048ms
[nuxt] kit:compatibility: 23.053ms
[nuxt] kit:compatibility: 22.926ms
[nuxt] kit:compatibility: 22.893ms
[nuxt] kit:compatibility: 23.07ms
[nuxt] kit:compatibility: 23.098ms
[nuxt] kit:compatibility: 23.204ms
[nuxt] kit:compatibility: 22.929ms
[nuxt] kit:compatibility: 23.027ms
[nuxt] kit:compatibility: 0.062ms
[nuxt] kit:compatibility: 0.14ms
[nuxt] kit:compatibility: 0.312ms
[nuxt] pages:routerOptions: 0.031ms
[nuxt] kit:compatibility: 0.025ms
[nuxt] kit:compatibility: 2.497ms
[nuxt] kit:compatibility: 2.566ms
[nuxt] kit:compatibility: 2.576ms
[nuxt] kit:compatibility: 2.584ms
[nuxt] kit:compatibility: 2.588ms
[nuxt] kit:compatibility: 2.591ms
[nuxt] kit:compatibility: 2.595ms
[nuxt] kit:compatibility: 2.483ms
[nuxt] kit:compatibility: 2.482ms
[nuxt] kit:compatibility: 2.407ms
[nuxt] imports:sources: 0.21ms
[nuxt] imports:context: 0.843ms
[nuxt] imports:dirs: 0.083ms
[nuxt] imports:extend: 0.131ms
[nuxt] builder:generateApp: 0.018ms
[nuxt] schema:extend: 0.022ms
[nuxt] schema:resolved: 0.011ms
[nuxt] modules:done: 11.606ms
[nuxt] kit:compatibility: 5.73ms
[nuxt] nitro:config: 0.19ms
[nuxt] nitro:init: 0.191ms
[nuxt] ready: 0.457ms
[nuxt] components:dirs: 0.016ms
[nuxt] app:resolve: 1.659ms
[nuxt] pages:extend: 0.254ms
[nuxt] components:extend: 0.266ms
[nuxt] app:templates: 11.781ms
[nuxt] eslint:config:addons: 12.043ms
[nuxt] pages:routerOptions: 0.167ms
[nuxt] imports:extend: 0.059ms
[nuxt] builder:generateApp: 0.01ms
[nuxt] app:templatesGenerated: 4.443ms
[nuxt] build:before: 28.215ms
[nuxt] schema:beforeWrite: 0.015ms
[nuxt] schema:written: 0.021ms
[nuxt] nitro:build:before: 0.115ms
[nuxt] prerender:routes: 0.014ms
[nitro] prerender:routes: 0.222ms
[success] [nitro] Generated public .output/public
[nuxt] nitro:build:public-assets: 0.059ms
[nitro] rollup:before: 17.547ms
[nitro] types:extend: 0.021ms
[info] [nitro] Building Nuxt Nitro server (preset: `node-server`)
[error] [nitro] Error: Could not load /src/.nuxt/dist/server/client.manifest.mjs (imported by node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.4.1_eslint@8.57.0_ioredis@5.4.1_magicast@0.3_3466oo4tqv6ryzjrv7s3eehes4/node_modules/nuxt/dist/core/runtime/nitro/renderer.js): ENOENT: no such file or directory, open '/src/.nuxt/dist/server/client.manifest.mjs'


undefined
[nuxt] build:done: 1.943s
[nitro] close: 0.255ms
[nuxt] close: 0.639ms
failed to load config from /src/vitest.dev.config.ts

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Could not load /src/.nuxt/dist/server/client.manifest.mjs (imported by node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.4.1_eslint@8.57.0_ioredis@5.4.1_magicast@0.3_3466oo4tqv6ryzjrv7s3eehes4/node_modules/nuxt/dist/core/runtime/nitro/renderer.js): ENOENT: no such file or directory, open '/src/.nuxt/dist/server/client.manifest.mjs'
    at async open (node:internal/fs/promises:639:25)
    at async readFile (node:internal/fs/promises:1249:14)
    at async file:///src/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:18981:24
    at async Queue.work (file:///src/node_modules/.pnpm/rollup@4.21.0/node_modules/rollup/dist/es/shared/node-entry.js:20023:32) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/src/.nuxt/dist/server/client.manifest.mjs',
  watchFiles: [
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/entries/node-server.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/app.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/shutdown.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/utils.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/index.mjs',
    '/src/node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/mock/empty.mjs',
    '/src/node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs',
    '/src/node_modules/.pnpm/destr@2.0.3/node_modules/destr/dist/index.mjs',
    '/src/node_modules/.pnpm/crossws@0.2.4/node_modules/crossws/dist/adapters/node.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/config.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/cache.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/route-rules.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/context.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/debug.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/static.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/lib/http-graceful-shutdown.mjs',
    '/src/node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/fetch/index.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/plugin.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/task.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/renderer.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/storage.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/error.mjs',
    '/src/node_modules/.pnpm/hookable@5.5.3/node_modules/hookable/dist/index.mjs',
    '/src/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/node.mjs',
    '/src/node_modules/.pnpm/crossws@0.2.4/node_modules/crossws/dist/index.mjs',
    '/src/node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.4.1_eslint@8.57.0_ioredis@5.4.1_magicast@0.3_3466oo4tqv6ryzjrv7s3eehes4/node_modules/nuxt/dist/core/runtime/nitro/error.js',
    '/src/node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.4.1_eslint@8.57.0_ioredis@5.4.1_magicast@0.3_3466oo4tqv6ryzjrv7s3eehes4/node_modules/nuxt/dist/core/runtime/nitro/renderer.js',
    '/src/node_modules/.pnpm/crossws@0.2.4/node_modules/crossws/dist/shared/crossws.a5db571c.mjs',
    '/src/node_modules/.pnpm/crossws@0.2.4/node_modules/crossws/dist/shared/crossws.77e89680.mjs',
    '/src/node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/http/index.mjs',
    '/src/node_modules/.pnpm/nitropack@2.9.7_magicast@0.3.4/node_modules/nitropack/dist/runtime/utils.env.mjs',
    '/src/node_modules/.pnpm/ufo@1.5.4/node_modules/ufo/dist/index.mjs',
    '/src/node_modules/.pnpm/ohash@1.1.3/node_modules/ohash/dist/index.mjs',
    '/src/node_modules/.pnpm/uncrypto@0.1.3/node_modules/uncrypto/dist/crypto.node.mjs',
    '/src/node_modules/.pnpm/radix3@1.1.2/node_modules/radix3/dist/index.mjs',
    '/src/node_modules/.pnpm/cookie-es@1.2.2/node_modules/cookie-es/dist/index.mjs',
    '/src/node_modules/.pnpm/defu@6.1.4/node_modules/defu/dist/defu.mjs',
    '/src/node_modules/.pnpm/iron-webcrypto@1.2.1/node_modules/iron-webcrypto/dist/index.js',
    '/src/node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/fetch/call.mjs',
    '/src/node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs',
    '/src/node_modules/.pnpm/klona@2.0.6/node_modules/klona/dist/index.mjs',
    '/src/node_modules/.pnpm/pathe@1.1.2/node_modules/pathe/dist/index.mjs',
    '/src/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs',
    '/src/node_modules/.pnpm/@unhead+vue@1.9.16_vue@3.4.38_typescript@5.5.4_/node_modules/@unhead/vue/dist/index.mjs',
    '/src/node_modules/.pnpm/unstorage@1.10.2_ioredis@5.4.1/node_modules/unstorage/drivers/fs-lite.mjs',
    '/src/node_modules/.pnpm/unstorage@1.10.2_ioredis@5.4.1/node_modules/unstorage/dist/index.mjs',
    '/src/node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.4.1_eslint@8.57.0_ioredis@5.4.1_magicast@0.3_3466oo4tqv6ryzjrv7s3eehes4/node_modules/nuxt/dist/core/runtime/nitro/error-dev.js',
    '/src/node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.4.1_eslint@8.57.0_ioredis@5.4.1_magicast@0.3_3466oo4tqv6ryzjrv7s3eehes4/node_modules/nuxt/dist/core/runtime/nitro/error-500.js',
    '/src/node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.4.1_eslint@8.57.0_ioredis@5.4.1_magicast@0.3_3466oo4tqv6ryzjrv7s3eehes4/node_modules/nuxt/dist/core/runtime/nitro/paths.js',
    '/src/node_modules/.pnpm/node-fetch-native@1.6.4/node_modules/node-fetch-native/dist/native.mjs',
    '/src/node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/_internal/utils.mjs',
    '/src/node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/mock/proxy.mjs',
    '/src/node_modules/.pnpm/std-env@3.7.0/node_modules/std-env/dist/index.mjs',
    '/src/node_modules/.pnpm/croner@8.1.1/node_modules/croner/dist/croner.min.js',
    '/src/node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/http/_request.mjs',
    '/src/node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/http/_consts.mjs',
    '/src/node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/http/_response.mjs',
    '/src/node_modules/.pnpm/@nuxt+devalue@2.0.2/node_modules/@nuxt/devalue/dist/devalue.mjs',
    '/src/node_modules/.pnpm/scule@1.3.0/node_modules/scule/dist/index.mjs',
    '/src/.nuxt/dist/server/client.manifest.mjs',
    '/src/.nuxt/dist/server/styles.mjs'
  ]
}
```

I have no clue what all this junk means or how to go about fixing it.
Just in case I have to run build before I use the unit tests (I don't think I should have to, but let's try)

```bash
> build
> nuxt build


 WARN  Changing NODE_ENV from development to production, to avoid unintended behavior.                                                                          6:44:43 AM

Nuxt 3.12.4 with Nitro 2.9.7                                                                                                                                    6:44:43 AM
ℹ No build cache found                                                                                                                        nuxt-build-cache 6:44:46 AM
  - in /src/node_modules/.cache/nuxt/builds/3g9gvZu3Ed/nuxt.tar
ℹ Building client...                                                                                                                                           6:44:47 AM
ℹ vite v5.4.1 building for production...                                                                                                                       6:44:47 AM
transforming (14) node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.4.1_eslint@8.57.0_ioredis@5.4.1_magicast@0.3_3466oo4tqv6ryzjrv7s3eehes4/node_modutests/unit/stores/todo.test.ts:6:1 - error TS2593: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha` and then add 'jest' or 'mocha' to the types field in your tsconfig.

6 describe('todo store tests', () => {
  ~~~~~~~~

tests/unit/stores/todo.test.ts:7:5 - error TS2304: Cannot find name 'beforeEach'.

7     beforeEach(() => {
      ~~~~~~~~~~

tests/unit/stores/todo.test.ts:16:5 - error TS2593: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha` and then add 'jest' or 'mocha' to the types field in your tsconfig.

16     it('should create', () => {
       ~~

tests/unit/stores/todo.test.ts:20:5 - error TS2593: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha` and then add 'jest' or 'mocha' to the types field in your tsconfig.

20     it('should fetch todos', async () => {
       ~~


Found 4 errors in the same file, starting at: tests/unit/stores/todo.test.ts:6
```

So the errors here seem to indicate that the vitest types are missing? But why?

All I really wanted was a demo project with a simple todos app with a simple component, plugin, page, store and associated unit tests to act as a template project for my developers to get them started quickly when spinning up new projects. But how can I possibly ask them to do that when I cannot get this working myself from following the documentation and going back to simple first principles?

I am really happy to help contribute to the nuxt documentation to help flesh it out a bit, if only I can get some help with this most basic of tasks. I think it would be a really good win-win for all concerned if you could help me set up this basic basic template project to a working standard and could in turn find out why this is not clicking for me in my head and thus where the gaps are in the documentation and close them up.

**Comment by rayblair06** [comment]
Downgrading `vue` to `^3.3.4` and upgrading `vitest` to `^2.0.5` fixed the tests for me then configuring `tsconfig.json` to work with global apis fixed the build. https://vitest.dev/config/#globals.

**Comment by daniandl** [comment]
This is sadly the outcome of the convoluted dependency hell the JS ecosystem has become. 
I share the same concerns for Nuxt, especially with how the upgrade flow is presented. Almost every update recommends you to regenerate your lockfile, which may work in a new/simple project, but for an existing large codebase this is **guaranteed chaos**.
I've gotten close to just giving up on Nuxt many times because I'm spending more time configuring my project rather than building out my app. Such a shame.... I don't have a solution to it either, just thought I'd share my grief :)

**Comment by danielroe** [comment]
I believe the error you are seeing is coming from using `globals: true`. Nuxt doesn't know about that, and thinks that you are not importing `beforeEach` and `it` into tests/unit/stores/todo.test.ts (see [source](https://github.com/suityou01/bpm-core-web-template-repro/blob/main/tests/unit/stores/todo.test.ts#L3)) when it is running the type check phase.

I would recommend turning off `globals: true` and using explicit imports, but if not, make sure to follow the [vitest docs](https://vitest.dev/config/#globals) and add `vitest/globals` to `typescript.tsConfig.compilerOptions.types` in your `nuxt.config`.

In addition, note that if you configure `exclude` [yourself](https://github.com/suityou01/bpm-core-web-template-repro/blob/main/tsconfig.json#L4C3-L4C27), TypeScript requires you then to add every other field to exclude. That's why we recommend configuring `typescript.tsConfig.exclude` instead in your `nuxt.config` - so it can be merged smartly.

**Comment by danielroe** [comment]
> Stackblitz link for the reproduction: [Stackblitz](https://stackblitz.com/github/suityou01/bpm)

cc: @huang-julien might need to update regexp in the github action

**Comment by suityou01** [comment]
So in summary we have some anecdotes, some context specific suggestions but no strategy for how to come up with better documentation, close down the gaps and make the devx of coming up with a typescript version of nuxt less painful? I think this project will fade into obscurity in which case. For this reason, I'm out. Thanks for helping me to make my mind up.

**Comment by danielroe** [comment]
I'm sorry you feel that way. Best of luck!
