### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'env') 

### ISSUE THREAD

**Issue by WuChenDi** [nuxt/nuxt#28648]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.16.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.7.1
- Builder:          -
- User Config:      compatibilityDate, future, devtools, imports, nitro, runtimeConfig, modules
- Runtime Modules:  nitro-cloudflare-dev@0.1.6, @vueuse/nuxt@11.0.0, @unocss/nuxt@0.62.2, @element-plus/nuxt@1.0.9, nuxt-svgo@4.0.3
- Build Modules:    -
------------------------------

### Reproduction

https://github.com/cdLab996/cf-examples-nuxt

### Describe the bug

Hello everyone, my apologies for the interruption.

I would like to inquire about an issue I encountered while using Nuxt (4). I have been unable to find a solution, yet it is perplexing that there are no errors during the development phase, but problems arise once deployed on Cloudflare. The specific error log is as follows:

- generate

```bash
wudi@cd:~/github/cdlab996/cf-examples-nuxt$ pnpm run generate

> cf-examples-nuxt@ generate /home/wudi/github/cdlab996/cf-examples-nuxt
> nuxt generate

Nuxt 3.12.4 with Nitro 2.9.7                                                                                                                                                    6:32:52 PM
ℹ Using Nitro server preset: static                                                                                                                                            6:32:52 PM
ℹ Running with compatibility version 4                                                                                                                                         6:32:55 PM

 WARN  Components directory not found: /home/wudi/github/cdlab996/cf-examples-nuxt/app/assets/icons/                                                                            6:32:55 PM

ℹ Building client...                                                                                                                                                           6:32:57 PM
ℹ vite v5.4.1 building for production...                                                                                                                                       6:32:57 PM
ℹ ✓ 1572 modules transformed.                                                                                                                                                  6:33:04 PM
ℹ ../.nuxt/dist/client/manifest.json                   3.26 kB │ gzip:  0.50 kB                                                                                                6:33:04 PM
ℹ ../.nuxt/dist/client/_nuxt/error-500.UUkX8yuV.css    1.88 kB │ gzip:  0.72 kB                                                                                                6:33:04 PM
ℹ ../.nuxt/dist/client/_nuxt/error-404.BQ5GNFoe.css    3.56 kB │ gzip:  1.10 kB                                                                                                6:33:04 PM
ℹ ../.nuxt/dist/client/_nuxt/entry.B203oo-1.css        4.66 kB │ gzip:  1.30 kB                                                                                                6:33:04 PM
ℹ ../.nuxt/dist/client/_nuxt/index.sIy8JoaS.css       84.17 kB │ gzip: 12.13 kB                                                                                                6:33:04 PM
ℹ ../.nuxt/dist/client/_nuxt/Cbh1479-.js               0.38 kB │ gzip:  0.27 kB                                                                                                6:33:04 PM
ℹ ../.nuxt/dist/client/_nuxt/CCfBf8Xc.js               2.77 kB │ gzip:  1.24 kB                                                                                                6:33:04 PM
ℹ ../.nuxt/dist/client/_nuxt/C5jzTqX_.js               8.23 kB │ gzip:  3.35 kB                                                                                                6:33:04 PM
ℹ ../.nuxt/dist/client/_nuxt/R8RLRbZE.js             166.11 kB │ gzip: 63.18 kB                                                                                                6:33:04 PM
ℹ ../.nuxt/dist/client/_nuxt/CLrCArce.js             273.03 kB │ gzip: 92.61 kB                                                                                                6:33:04 PM
ℹ ✓ built in 6.98s                                                                                                                                                             6:33:04 PM
✔ Client built in 7565ms                                                                                                                                                       6:33:04 PM
ℹ Building server...                                                                                                                                                           6:33:04 PM
ℹ vite v5.4.1 building SSR bundle for production...                                                                                                                            6:33:04 PM
ℹ ✓ 1524 modules transformed.                                                                                                                                                  6:33:11 PM
ℹ ../.nuxt/dist/server/styles.mjs                            0.07 kB                                                                                                           6:33:11 PM
ℹ ../.nuxt/dist/server/_nuxt/vue.f36acd1f-DvSg21Lc.js        0.82 kB │ map:     1.83 kB                                                                                        6:33:11 PM
ℹ ../.nuxt/dist/server/_nuxt/error-500-C0ftyogV.js           4.16 kB │ map:     4.73 kB                                                                                        6:33:11 PM
ℹ ../.nuxt/dist/server/_nuxt/multipart-parser-WQz-I_2P.js    6.93 kB │ map:    10.87 kB                                                                                        6:33:11 PM
ℹ ../.nuxt/dist/server/_nuxt/error-404-DKbP9LwE.js          13.50 kB │ map:    24.62 kB                                                                                        6:33:11 PM
ℹ ../.nuxt/dist/server/_nuxt/prompt-B5Z8siBC.js             49.83 kB │ map:    78.12 kB                                                                                        6:33:11 PM
ℹ ../.nuxt/dist/server/server.mjs                          249.46 kB │ map:   444.32 kB                                                                                        6:33:11 PM
ℹ ../.nuxt/dist/server/_nuxt/index-CXuMT6OY.js             537.20 kB │ map: 1,834.81 kB                                                                                        6:33:11 PM
ℹ ✓ built in 7.13s                                                                                                                                                             6:33:11 PM
✔ Server built in 7146ms                                                                                                                                                       6:33:11 PM
ℹ Initializing prerenderer                                                                                                                                               nitro 6:33:11 PM
ℹ Prerendering 2 routes                                                                                                                                                  nitro 6:33:15 PM

 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'env')                                                                            6:33:15 PM
  at initializeDrizzle (./.nuxt/prerender/chunks/runtime.mjs:819:47)
  at Object.handler (./.nuxt/prerender/chunks/runtime.mjs:830:17)
  at Object.handler (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:1975:31)
  at runNextTicks (node:internal/process/task_queues:60:5)
  at listOnTimeout (node:internal/timers:545:9)
  at process.processTimers (node:internal/timers:519:7)
  at async toNodeHandle (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2266:7)
  at async ufetch (./node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async generateRoute (./node_modules/.pnpm/nitropack@2.9.7_better-sqlite3@11.2.0_drizzle-orm@0.33.0_@cloudflare+workers-types@4.20240815_744faqxkpe7otzav6jgyqk7jri/node_modules/nitropack/dist/chunks/prerender.mjs:116:17)
  at async Promise.all (index 0)


 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'env')                                                                            6:33:15 PM
  at initializeDrizzle (./.nuxt/prerender/chunks/runtime.mjs:819:47)
  at Object.handler (./.nuxt/prerender/chunks/runtime.mjs:830:17)
  at Object.handler (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:1975:31)
  at runNextTicks (node:internal/process/task_queues:60:5)
  at listOnTimeout (node:internal/timers:545:9)
  at process.processTimers (node:internal/timers:519:7)
  at async toNodeHandle (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2266:7)
  at async ufetch (./node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async errorhandler (./.nuxt/prerender/chunks/runtime.mjs:662:41)
  at async toNodeHandle (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2274:9)


 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'env')                                                                            6:33:15 PM
  at initializeDrizzle (./.nuxt/prerender/chunks/runtime.mjs:819:47)
  at Object.handler (./.nuxt/prerender/chunks/runtime.mjs:830:17)
  at Object.handler (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:1975:31)
  at async toNodeHandle (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2266:7)
  at async ufetch (./node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async generateRoute (./node_modules/.pnpm/nitropack@2.9.7_better-sqlite3@11.2.0_drizzle-orm@0.33.0_@cloudflare+workers-types@4.20240815_744faqxkpe7otzav6jgyqk7jri/node_modules/nitropack/dist/chunks/prerender.mjs:116:17)
  at async Promise.all (index 1)
  at async runParallel (./node_modules/.pnpm/nitropack@2.9.7_better-sqlite3@11.2.0_drizzle-orm@0.33.0_@cloudflare+workers-types@4.20240815_744faqxkpe7otzav6jgyqk7jri/node_modules/nitropack/dist/chunks/prerender.mjs:253:3)
  at async prerender (./node_modules/.pnpm/nitropack@2.9.7_better-sqlite3@11.2.0_drizzle-orm@0.33.0_@cloudflare+workers-types@4.20240815_744faqxkpe7otzav6jgyqk7jri/node_modules/nitropack/dist/chunks/prerender.mjs:202:3)
  at async ./node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.3.0_better-sqlite3@11.2.0_drizzle-orm@0.33.0_5i7qcnj2c63vwiygzeog7q5vqe/node_modules/nuxt/dist/index.mjs:3615:7


 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'env')                                                                            6:33:15 PM
  at initializeDrizzle (./.nuxt/prerender/chunks/runtime.mjs:819:47)
  at Object.handler (./.nuxt/prerender/chunks/runtime.mjs:830:17)
  at Object.handler (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:1975:31)
  at async toNodeHandle (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2266:7)
  at async ufetch (./node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async errorhandler (./.nuxt/prerender/chunks/runtime.mjs:662:41)
  at async toNodeHandle (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2274:9)
  at async ufetch (./node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async generateRoute (./node_modules/.pnpm/nitropack@2.9.7_better-sqlite3@11.2.0_drizzle-orm@0.33.0_@cloudflare+workers-types@4.20240815_744faqxkpe7otzav6jgyqk7jri/node_modules/nitropack/dist/chunks/prerender.mjs:116:17)
  at async Promise.all (index 1)

  ├─ /200.html (15ms)                                                                                                                                                     nitro 6:33:15 PM
  │ └── Error: [500]
  ├─ /404.html (11ms)                                                                                                                                                     nitro 6:33:15 PM
  │ └── Error: [500]
                                                                                                                                                                          nitro 6:33:15 PM
Errors prerendering:
  ├─ /200.html (15ms)                                                                                                                                                     nitro 6:33:15 PM
  │ └── Error: [500]
  ├─ /404.html (11ms)                                                                                                                                                     nitro 6:33:15 PM
  │ └── Error: [500]
                                                                                                                                                                          nitro 6:33:15 PM

 ERROR  Exiting due to prerender errors.                                                                                                                                        6:33:15 PM

  at prerender (node_modules/.pnpm/nitropack@2.9.7_better-sqlite3@11.2.0_drizzle-orm@0.33.0_@cloudflare+workers-types@4.20240815_744faqxkpe7otzav6jgyqk7jri/node_modules/nitropack/dist/chunks/prerender.mjs:220:11)
  at async node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.3.0_better-sqlite3@11.2.0_drizzle-orm@0.33.0_5i7qcnj2c63vwiygzeog7q5vqe/node_modules/nuxt/dist/index.mjs:3615:7
  at async build (node_modules/.pnpm/nuxt@3.12.4_@parcel+watcher@2.4.1_@types+node@22.3.0_better-sqlite3@11.2.0_drizzle-orm@0.33.0_5i7qcnj2c63vwiygzeog7q5vqe/node_modules/nuxt/dist/index.mjs:5479:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/chunks/build.mjs:94:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/chunks/generate.mjs:55:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.12.0/node_modules/nuxi/dist/shared/nuxi.6aad497e.mjs:1777:7)



 ERROR  Exiting due to prerender errors.                                                                                                                                        6:33:15 PM

 ELIFECYCLE  Command failed with exit code 1.
```

- build

```bash
wudi@cd:~/github/cdlab996/cf-examples-nuxt$ pnpm run build

> cf-examples-nuxt@ build /home/wudi/github/cdlab996/cf-examples-nuxt
> nuxt build

Nuxt 3.12.4 with Nitro 2.9.7                                                                                                                                                    7:28:39 PM
ℹ Running with compatibility version 4                                                                                                                                         7:28:42 PM

 WARN  Components directory not found: /home/wudi/github/cdlab996/cf-examples-nuxt/app/assets/icons/                                                                            7:28:42 PM

ℹ Building client...                                                                                                                                                           7:28:43 PM
ℹ vite v5.4.1 building for production...                                                                                                                                       7:28:43 PM
ℹ ✓ 1572 modules transformed.                                                                                                                                                  7:28:50 PM
ℹ ../.nuxt/dist/client/manifest.json                   3.26 kB │ gzip:  0.50 kB                                                                                                7:28:50 PM
ℹ ../.nuxt/dist/client/_nuxt/error-500.UUkX8yuV.css    1.88 kB │ gzip:  0.72 kB                                                                                                7:28:50 PM
ℹ ../.nuxt/dist/client/_nuxt/error-404.BQ5GNFoe.css    3.56 kB │ gzip:  1.10 kB                                                                                                7:28:50 PM
ℹ ../.nuxt/dist/client/_nuxt/entry.B203oo-1.css        4.66 kB │ gzip:  1.30 kB                                                                                                7:28:50 PM
ℹ ../.nuxt/dist/client/_nuxt/index.sIy8JoaS.css       84.17 kB │ gzip: 12.13 kB                                                                                                7:28:50 PM
ℹ ../.nuxt/dist/client/_nuxt/Cbh1479-.js               0.38 kB │ gzip:  0.27 kB                                                                                                7:28:50 PM
ℹ ../.nuxt/dist/client/_nuxt/CCfBf8Xc.js               2.77 kB │ gzip:  1.24 kB                                                                                                7:28:50 PM
ℹ ../.nuxt/dist/client/_nuxt/C5jzTqX_.js               8.23 kB │ gzip:  3.35 kB                                                                                                7:28:50 PM
ℹ ../.nuxt/dist/client/_nuxt/R8RLRbZE.js             166.11 kB │ gzip: 63.18 kB                                                                                                7:28:50 PM
ℹ ../.nuxt/dist/client/_nuxt/CLrCArce.js             273.03 kB │ gzip: 92.61 kB                                                                                                7:28:50 PM
ℹ ✓ built in 7.14s                                                                                                                                                             7:28:50 PM
✔ Client built in 7636ms                                                                                                                                                       7:28:50 PM
ℹ Building server...                                                                                                                                                           7:28:50 PM
ℹ vite v5.4.1 building SSR bundle for production...                                                                                                                            7:28:50 PM
ℹ ✓ 1524 modules transformed.                                                                                                                                                  7:28:56 PM
ℹ ../.nuxt/dist/server/styles.mjs                            0.07 kB                                                                                                           7:28:57 PM
ℹ ../.nuxt/dist/server/_nuxt/vue.f36acd1f-DvSg21Lc.js        0.82 kB │ map:     1.83 kB                                                                                        7:28:57 PM
ℹ ../.nuxt/dist/server/_nuxt/error-500-C0ftyogV.js           4.16 kB │ map:     4.73 kB                                                                                        7:28:57 PM
ℹ ../.nuxt/dist/server/_nuxt/multipart-parser-WQz-I_2P.js    6.93 kB │ map:    10.87 kB                                                                                        7:28:57 PM
ℹ ../.nuxt/dist/server/_nuxt/error-404-DKbP9LwE.js          13.50 kB │ map:    24.62 kB                                                                                        7:28:57 PM
ℹ ../.nuxt/dist/server/_nuxt/prompt-B5Z8siBC.js             49.83 kB │ map:    78.12 kB                                                                                        7:28:57 PM
ℹ ../.nuxt/dist/server/server.mjs                          249.46 kB │ map:   444.32 kB                                                                                        7:28:57 PM
ℹ ../.nuxt/dist/server/_nuxt/index-CXuMT6OY.js             537.20 kB │ map: 1,834.87 kB                                                                                        7:28:57 PM
ℹ ✓ built in 6.32s                                                                                                                                                             7:28:57 PM
✔ Server built in 6323ms                                                                                                                                                       7:28:57 PM
✔ Generated public dist                                                                                                                                                  nitro 7:28:57 PM
ℹ Building Nuxt Nitro server (preset: cloudflare-pages)                                                                                                                  nitro 7:28:57 PM

[nitro 7:29:02 PM]  ERROR  RollupError: .nuxt/dist/server/_nuxt/prompt-B5Z8siBC.js (1:9): "stdin" is not exported by "node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/process/index.mjs", imported by ".nuxt/dist/server/_nuxt/prompt-B5Z8siBC.js".


1: import { stdin, stdout } from "node:process";
            ^
2: import f from "node:readline";
3: import { WriteStream } from "node:tty";


[7:29:02 PM]  ERROR  .nuxt/dist/server/_nuxt/prompt-B5Z8siBC.js (1:9): "stdin" is not exported by "node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/process/index.mjs", imported by ".nuxt/dist/server/_nuxt/prompt-B5Z8siBC.js".

  at getRollupError (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
  at error (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
  at Module.error (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:13958:16)
  at Module.traceVariable (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:14406:29)
  at ModuleScope.findVariable (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:12110:39)
  at ChildScope.findVariable (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:7465:38)
  at ClassBodyScope.findVariable (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:7465:38)
  at ChildScope.findVariable (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:7465:38)
  at ChildScope.findVariable (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:7465:38)
  at FunctionScope.findVariable (node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:7465:38)



[7:29:02 PM]  ERROR  .nuxt/dist/server/_nuxt/prompt-B5Z8siBC.js (1:9): "stdin" is not exported by "node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/process/index.mjs", imported by ".nuxt/dist/server/_nuxt/prompt-B5Z8siBC.js".

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by danielroe** [comment]
Likely the issue is the import from `consola` in your composables which depends on some node APIs. Try to use `import { consola } from 'consola/basic'` instead.

**Comment by WuChenDi** [comment]
Hi @danielroe,

Regarding this issue, I'd like to say that it's probably not due to `consola`.

I tried creating a new empty project and running `npm run generate` and I still get the following error message.

```text

 ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'env')                                                                           11:29:21 AM
  at Object.handler (./.nuxt/prerender/chunks/runtime.mjs:774:43)
  at Object.handler (./node_modules/h3/dist/index.mjs:1975:31)
  at runNextTicks (node:internal/process/task_queues:60:5)
  at listOnTimeout (node:internal/timers:545:9)
  at process.processTimers (node:internal/timers:519:7)
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:2266:7)
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async generateRoute (./node_modules/nitropack/dist/chunks/prerender.mjs:116:17)
  at async Promise.all (index 0)
  at async runParallel (./node_modules/nitropack/dist/chunks/prerender.mjs:253:3)

```

From the perspective of the source code, the issue originates here:

- `server/middleware/db.ts`

```ts
export default defineEventHandler(async (event) => {
  const { DB } = event.context.cloudflare.env
  console.log("🚀 ~ defineEventHandler ~ DB:", DB)
})

```

However, when running `npm run dev`, everything works fine, yet I am uncertain what could be affecting this component.

![image](https://github.com/user-attachments/assets/49785e17-f986-4a20-b192-a38eee1b8cae)


Here is the minimal reproducible issue code address: https://github.com/cdLab996/cf-nuxt-examples

**Comment by danielroe** [comment]
That's a different issue. But it's a nitro one - basically the cloudflare environment doesn't exist when prerendering. Check for  the existence of `event.context.cloudflare.env` first before destructuring it.

Feel free to open an issue on https://github.com/unjs/nitro/issues, but I think @pi0 is already on it.

**Comment by paulius1230** [comment]
I'm having same issue

**Comment by paulius1230** [comment]
I'm having same issue
