### ISSUE TITLE
Nuxt UI (headless-ui) doesn't work wit server components

### ISSUE THREAD

**Issue by wolfgang-hartl** [nuxt/nuxt#28884]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.15.0`
- Nuxt Version:     `3.13.1`
- CLI Version:      `3.13.1`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.8.2`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `srcDir`, `runtimeConfig`, `nitro`, `experimental`, `ignore`, `extends`, `modules`
- Runtime Modules:  `@nuxt/ui@2.18.4`
- Build Modules:    `-`

### Reproduction

I don't have a public repository for that, but it's pretty ease to reproduce

nuxt.config.ts:
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2024-04-03",
  devtools: { enabled: true },
  experimental: {
    componentIslands: {
      selectiveClient: true,
    },
  },
/*
  nitro: {
    serveStatic: true, // it seems that serveStatic is also needed when setting selectiveClient to : 'deep', i didn't manage to make it work without that, for "true" it seems not to be needed.
  },
*/
});
```

You can then either install headless-ui/vue directly or use a component of the nuxt-ui library. In my Case i've used the Combobox example from the docs: https://headlessui.com/v1/vue/combobox on my fresh installation, and in my project I've used the `USelectMenu`from nuxt-ui
```
          <UFormGroup :label="option.label" class="flex-1">
            <USelectMenu
              class="flex-1"
              v-model="model[option.selectOptions!.key]"
              :options="option.selectOptions!.options"
              value-attribute="value"
            />
          </UFormGroup>
```

### Describe the bug

When using the Combobox only (copied from the headlessui docs) I get the following error: 
```
The current component <Combobox /> is rendering a "template".
  However we need to passthrough the following props:
  - data-v-inspector
  
  You can apply a few solutions:
  - Add an as="..." prop, to ensure that we render an actual element instead of a "template".
  - Render a single element as the child so that we can forward the props onto that element.
  at y (node_modules/.pnpm/@headlessui+vue@1.7.22_vue@3.5.3/node_modules/@headlessui/vue/dist/utils/render.js:1:996)
  at A (node_modules/.pnpm/@headlessui+vue@1.7.22_vue@3.5.3/node_modules/@headlessui/vue/dist/utils/render.js:1:403)
  at Proxy.<anonymous> (node_modules/.pnpm/@headlessui+vue@1.7.22_vue@3.5.3/node_modules/@headlessui/vue/dist/components/combobox/combobox.js:1:9272)
  at renderComponentRoot (node_modules/.pnpm/@vue+runtime-core@3.5.3/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6356:16)
  at renderComponentSubTree (node_modules/.pnpm/@vue+server-renderer@3.5.3_vue@3.5.3/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:732:28)
  at renderComponentVNode (node_modules/.pnpm/@vue+server-renderer@3.5.3_vue@3.5.3/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:664:12)
  at Module.ssrRenderComponent (node_modules/.pnpm/@vue+server-renderer@3.5.3_vue@3.5.3/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:86:10)
  at _sfc_ssrRender (components/Button.vue:58:31)
  at renderComponentSubTree (node_modules/.pnpm/@vue+server-renderer@3.5.3_vue@3.5.3/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:715:9)
  at renderComponentVNode (node_modules/.pnpm/@vue+server-renderer@3.5.3_vue@3.5.3/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:664:12)
```

When using the `USelectMenu` Component the error looks like that:
```
Vue warn]: Failed to resolve component: NuxtTeleportSsrSlot
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Notifications data-v-inspector="src/app.vue:6:3" > 
  at <App data-v-inspector="node_modules/nuxt/dist/app/components/nuxt-root.vue:16:5" > 
  at <NuxtRoot>


 WARN  [Vue warn]: Component LayoutLoader is missing template or render function. 
  at <LayoutLoader key="default" layoutProps= { 'data-v-inspector': 'src/app.vue:2:3',
  ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } name="default" > 
  at <NuxtLayoutProvider layoutProps= { 'data-v-inspector': 'src/app.vue:2:3',
  ref:
   RefImpl {
     dep:
      Dep {
        computed: undefined,
        version: 0,
        activeLink: undefined,
        subs: undefined,
        subsHead: undefined },
     __v_isRef: true,
     __v_isShallow: false,
     _rawValue: undefined,
     _value: undefined } } key="default" name="default"  ... > 
  at <NuxtLayout data-v-inspector="src/app.vue:2:3" > 
  at <App data-v-inspector="node_modules/nuxt/dist/app/components/nuxt-root.vue:16:5" > 
  at <NuxtRoot>
```

I'm not quite sure if those errors are really related, but for me it seems to be the following scenario: 

Having a `UserList.server.vue` component and whenever a component (or components nested in those components down the tree) inside of a .server file using nuxt-client which doesn't have a single root element that error seems to occurs. The `HeadlessComboboxExample`-Component is wrapped in a div for example, but it seems that the `Combobox` component from headlessui doesn't have a single root element.
```
<script setup lang="ts">
const users = [
    {
        id: 1,
        name: 'John Doe',
        email: 'john@doe.com',
    },
    {
        id: 2,
        name: 'Jane Doe',
        email: 'jane@doe.com',
    }
];


</script>


<template>


    <div>
        <pre>{{ JSON.stringify(users, null, 2) }}</pre>
        <HeadlessComboboxExample nuxt-client />
    </div>


</template>
```

I hope that makes sense in a way! :-)

**Comment by danielroe** [comment]
This is probably caused by Nuxt Devtools. Would you see if it reproduces if you disable them?

**Comment by wolfgang-hartl** [comment]
> This is probably caused by Nuxt Devtools. Would you see if it reproduces if you disable them?

Hey Daniel, thanks for your fast response!
Unfortunately it's not resolved 100%. In the simple example used with the headless-ui component it works fine and it get's resolved when disabling the devtools. 

In the more complex example i get now the following warning:

**Comment by danielroe** [comment]
No worries! we'll track that other issue in https://github.com/nuxt/nuxt/issues/28879.
