### ISSUE TITLE
Importing .vue file in WebWorker causes error in nuxi generate

### ISSUE THREAD

**Issue by set5u** [nuxt/nuxt#29006]
### Environment

Working directory: C:/Users/vtvsn/Documents/.node_projects/nuxt-worker-custom-renderer                                                                                                              17:54:12
Nuxt project info:                                                                                                                                                                                  17:54:12

------------------------------
- Operating System: Windows_NT
- Node Version:     v21.1.0
- Nuxt Version:     3.13.1
- CLI Version:      3.10.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      compatibilityDate, devtools, vue, ssr
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Here is reproduction repo:
https://github.com/set5u/nuxt-worker-custom-renderer

### Describe the bug

When I try to use Vue's custom renderer API in a WebWorker, it works in dev mode but doesn't work when I generate it.

### Logs

```shell-script
C:\Users\vtvsn\Documents\.node_projects\nuxt-worker-custom-renderer>nuxi generate
Nuxt 3.13.1 with Nitro 2.9.7                                                                                                                                                                        17:52:14
ℹ Using Nitro server preset: static                                                                                                                                                                17:52:14
ℹ Building client...                                                                                                                                                                               17:52:17
ℹ vite v5.4.5 building for production...                                                                                                                                                           17:52:17
ℹ ✓ 107 modules transformed.                                                                                                                                                                       17:52:18   

 ERROR  x Build failed in 789ms                                                                                                                                                                     17:52:18  


[17:52:18]  ERROR  Nuxt Build Error: [vite:worker] [plugin vite:build-import-analysis] utils/SomeComponent.vue (2:51): Failed to parse source for import analysis because the content contains invalid JS syntax. Install @vitejs/plugin-vue to handle .vue files.
file: C:/Users/vtvsn/Documents/.node_projects/nuxt-worker-custom-renderer/utils/Worker.ts?worker:2:51

1: <template>
2: <custom-renderer-element></custom-renderer-element>
                                                      ^
3: </template>
4: <script setup lang="ts">


  file: C:/Users/vtvsn/Documents/.node_projects/nuxt-worker-custom-renderer/utils/Worker.ts?worker:2:51

  1: <template>
  2: <custom-renderer-element></custom-renderer-element>
  ^
  3: </template>
  4: <script setup lang="ts">

  at getRollupError (/C:/Users/vtvsn/Documents/.node_projects/nuxt-worker-custom-renderer/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
  at error (/C:/Users/vtvsn/Documents/.node_projects/nuxt-worker-custom-renderer/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/parseAst.js:388:42)
  at Object.error (/C:/Users/vtvsn/Documents/.node_projects/nuxt-worker-custom-renderer/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/node-entry.js:19734:20)
  at Object.error (/C:/Users/vtvsn/Documents/.node_projects/nuxt-worker-custom-renderer/node_modules/.pnpm/rollup@4.21.3/node_modules/rollup/dist/es/shared/node-entry.js:18854:42)
  at Object.transform (/C:/Users/vtvsn/Documents/.node_projects/nuxt-worker-custom-renderer/node_modules/.pnpm/vite@5.4.5/node_modules/vite/dist/node/chunks/dep-CUvs3bbV.js:64586:14)
```

**Comment by set5u** [comment]
Even without using the Custom Renderer API, importing a Vue file within Worker seems to cause an error in nuxi generate. Reproduction repository has been updated.

**Comment by set5u** [comment]
It seems to be a bug in Vite, so I will reopen the issue in Vite.

**Comment by set5u** [comment]
https://github.com/vitejs/vite/issues/18110
