### ISSUE TITLE
server `.js` files in layers are not transpiled

### ISSUE THREAD

**Issue by geminigeek** [nuxt/nuxt#29120]
### Environment

check reproduction

### Reproduction

https://stackblitz.com/edit/github-om7hsq-ceuyj6?file=packages%2Fnuxt-base%2Fserver%2Froutes%2FtestJs.js

### Describe the bug

clone repo 

pnpm dev  
on index page you will have 2 links pointing to server routes , one built with .ts , another .js the js route throw this error

```
[nuxt] [request error] [unhandled] [500] defineEventHandler is not defined
  at /home/projects/github-om7hsq-1d7k9t/packages/nuxt-base/server/routes/testJs.js  
  at async ModuleLoader.import (https://githubom7hsq1d7k9t-hjuo.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:2688)  
  at async Object.eval [as handler] (/home/projects/github-om7hsq-1d7k9t/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:2087:19)  
  at async Server.toNodeHandle (/home/projects/github-om7hsq-1d7k9t/node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:2374:7)
Global Server Route Middleware
[Vue Router warn]: No match found for location with path "/testJs"
[Vue Router warn]: No match found for location with path "/testJs"
[Vue Router warn]: No match found for location with path "/testJs"
[Vue Router warn]: No match found for location with path "/testJs"
```

**Comment by TimoW75** [comment]
running into the same problem..

Setting up a layer with .js files in the server route works fine if you run a dev server on that layer. The moment you use that layer in a different project defineEventHandler and defineNitroPlugin will throw a 'not defined'. 
When changing the file to .ts instead of .js this error goes away

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by obj63mc** [comment]
Just wanted to note that I am seeing this issue as well.  Referencing issue #27761 - in the stackblitz link - https://stackblitz.com/edit/nuxt-starter-6sjdoj?file=base%2Fserver%2Fserver%2Fmiddleware%2Fsecurity.js if you rename the file to security.ts then it magically works.  It seems that with layers you have to use typescript and will not work with standard .js extensions.

**Comment by danielroe** [comment]
this is a nitro issue that has been resolved in nitro v3 and is not reproducible on our nuxt v5 nightlies 🎉
