### ISSUE TITLE
Empty sourcemap generation of vue files which have the setup directive

### ISSUE THREAD

**Issue by onderceylan** [nuxt/nuxt#29143]
### Environment

Stackblitz environment
```
Working directory: /home/projects/gqairmgblw.github                                                            16:28:02
Nuxt project info:                                                                                             16:28:02

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.13.2
- CLI Version:      3.13.2
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools, sourcemap, nitro, vite
- Runtime Modules:  -
- Build Modules:    -
------------------------------

                                                                                                               16:28:02
👉 Report an issue: https://github.com/nuxt/nuxt/issues/new?template=bug-report.yml
👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new
👉 Read documentation: https://nuxt.com
```

### Reproduction

https://stackblitz.com/edit/github-ucukix?file=components%2FComponent1.vue,pages%2Fpage3.vue,pages%2Fpage4.vue,layouts%2Flayout2.vue,layouts%2Flayout4.vue,validate.cjs,nuxt.config.ts,README.md&view=editor

Manual reproduction on Stackblitz URL - opening the link automatically does the first 2 steps: 

* Run `npm run build` to generate the `dist` public folder.
* Run `npm test` to test the generated sourcemaps.
* Inspect the `xxx.js.map` files under `dist/_nuxt` folder manually.

### Describe the bug

I use setup directive on components, layouts and pages, some of which composes other components with module imports, and I generate builds with sourcemaps enabled.

What I expect is to have client side sourcemaps generated for the components, layouts and pages I use in the project.

What happening is, vite ignores to generate sourcemaps for some SFCs, depending on the content in the script tag with the setup directive. Inside the pages folder of the reproduction URL, there are various examples of single file components failing and succeeding generating sourcemaps.

### Additional context

This issue is linked to a vite issue: https://github.com/vitejs/vite-plugin-vue/issues/447.

- Having only an import statement in the script setup makes sourcemap generation fail.
- Removing the setup directive and using `defineComponent` with setup function in script tag fixes the issue.
- Adding console.log or similar statements in the script setup fixes the issue. See [the quick and dirty workaround doing that](https://stackblitz.com/edit/github-ucukix?file=forceSourcemapPlugin.js,nuxt.config.ts%3AL18) in the repo.

### Logs

```shell-script
❯ npm run build

> build
> nuxt build

Nuxt 3.13.2 with Nitro 2.9.7                                                                                   16:31:31
ℹ Compiled plugins/client.mjs in 520.41ms                                                                     16:31:36
ℹ Compiled types/plugins.d.ts in 526.1ms                                                                      16:31:36
ℹ Building client...                                                                                          16:31:36
ℹ vite v5.4.7 building for production...                                                                      16:31:36
ℹ ✓ 155 modules transformed.                                                                                  16:31:38
ℹ .nuxt/dist/client/manifest.json                    3.68 kB │ gzip:   0.61 kB                                16:31:39
ℹ .nuxt/dist/client/_nuxt/Component1.B73ZVTkA.css    0.04 kB │ gzip:   0.06 kB                                16:31:39
ℹ .nuxt/dist/client/_nuxt/error-500.BQ6EWHSq.css     1.88 kB │ gzip:   0.72 kB                                16:31:39
ℹ .nuxt/dist/client/_nuxt/error-404.zvQlCkGP.css     3.58 kB │ gzip:   1.11 kB                                16:31:39
ℹ .nuxt/dist/client/_nuxt/entry._z4rjWEz.css        12.39 kB │ gzip:   2.56 kB                                16:31:39
ℹ .nuxt/dist/client/_nuxt/B0fXxf3H.js                0.23 kB │ gzip:   0.19 kB │ map:     0.24 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/YceNhqnM.js                0.23 kB │ gzip:   0.19 kB │ map:     0.10 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/CJvId6RL.js                0.28 kB │ gzip:   0.23 kB │ map:     0.20 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/d3_E0v-c.js                0.47 kB │ gzip:   0.32 kB │ map:     0.10 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/Dwtnv5GU.js                0.55 kB │ gzip:   0.35 kB │ map:     0.11 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/Cihgbt3p.js                0.56 kB │ gzip:   0.35 kB │ map:     0.40 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/CavbnZTK.js                0.56 kB │ gzip:   0.35 kB │ map:     0.11 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/r5pRlTus.js                0.56 kB │ gzip:   0.35 kB │ map:     0.43 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/C40vjoMg.js                0.65 kB │ gzip:   0.38 kB │ map:     0.54 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/7IgePr0Y.js                0.75 kB │ gzip:   0.42 kB │ map:     0.40 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/CFhPsCYh.js                0.75 kB │ gzip:   0.42 kB │ map:     0.11 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/D4ueSEWF.js                4.32 kB │ gzip:   1.77 kB │ map:     5.32 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/Byd5qevx.js               18.19 kB │ gzip:   5.29 kB │ map:    30.23 kB             16:31:39
ℹ .nuxt/dist/client/_nuxt/CFR4BDmY.js              494.67 kB │ gzip: 110.63 kB │ map: 1,190.10 kB             16:31:39
ℹ ✓ built in 3.04s                                                                                            16:31:39
✔ Client built in 3049ms                                                                                      16:31:39
ℹ Building server...                                                                                          16:31:39
ℹ vite v5.4.7 building SSR bundle for production...                                                           16:31:39
ℹ ✓ 68 modules transformed.                                                                                   16:31:40
ℹ .nuxt/dist/server/_nuxt/entry-styles.URl_9LWA.mjs              0.08 kB                                      16:31:40
ℹ .nuxt/dist/server/_nuxt/error-404-styles.DRLC0U6S.mjs          0.08 kB                                      16:31:40
ℹ .nuxt/dist/server/_nuxt/error-500-styles.DqmriZ_b.mjs          0.08 kB                                      16:31:40
ℹ .nuxt/dist/server/_nuxt/Component1-styles.D2S_p0P3.mjs         0.09 kB                                      16:31:40
ℹ .nuxt/dist/server/_nuxt/welcome-styles.CyAsta2g.mjs            0.15 kB                                      16:31:40
ℹ .nuxt/dist/server/_nuxt/error-404-styles.BcoFjqgl.mjs          0.15 kB                                      16:31:40
ℹ .nuxt/dist/server/_nuxt/error-500-styles.DPP87-Dp.mjs          0.15 kB                                      16:31:40
ℹ .nuxt/dist/server/_nuxt/Component1-styles.BzxKMCYQ.mjs         0.16 kB                                      16:31:40
ℹ .nuxt/dist/server/styles.mjs                                   1.38 kB                                      16:31:40
ℹ .nuxt/dist/server/_nuxt/Component1-styles-1.mjs-CcdfUQQ_.js    0.25 kB │ map:   0.12 kB                     16:31:40
ℹ .nuxt/dist/server/_nuxt/page2-BhZZt8_r.js                      0.58 kB │ map:   0.25 kB                     16:31:40
ℹ .nuxt/dist/server/_nuxt/page4-B1QocBW7.js                      0.58 kB │ map:   0.11 kB                     16:31:40
ℹ .nuxt/dist/server/_nuxt/page1-DCChe2oN.js                      0.87 kB │ map:   0.25 kB                     16:31:40
ℹ .nuxt/dist/server/_nuxt/page5-wAbmS0WS.js                      1.18 kB │ map:   0.50 kB                     16:31:40
ℹ .nuxt/dist/server/_nuxt/page3-DY_00pby.js                      1.68 kB │ map:   0.15 kB                     16:31:40
ℹ .nuxt/dist/server/_nuxt/error-500-styles-1.mjs-DiWYPNRc.js     2.10 kB │ map:   0.12 kB                     16:31:40
ℹ .nuxt/dist/server/_nuxt/error-404-styles-1.mjs-D8Sw_W7I.js     3.80 kB │ map:   0.12 kB                     16:31:40
ℹ .nuxt/dist/server/_nuxt/error-500-CY3ZbSXA.js                  4.58 kB │ map:   5.35 kB                     16:31:40
ℹ .nuxt/dist/server/_nuxt/entry-styles-1.mjs-Bf3o1wln.js        12.65 kB │ map:   0.11 kB                     16:31:40
ℹ .nuxt/dist/server/_nuxt/error-404-ChCbkRLp.js                 15.37 kB │ map:  28.36 kB                     16:31:40
ℹ .nuxt/dist/server/server.mjs                                 129.44 kB │ map: 194.17 kB                     16:31:40
ℹ ✓ built in 946ms                                                                                            16:31:40
✔ Server built in 994ms                                                                                       16:31:40
✔ Generated public dist                                                                                 nitro 16:31:41
ℹ Building Nuxt Nitro server (preset: node-server)                                                      nitro 16:31:41
✔ Nuxt Nitro server built                                                                               nitro 16:31:45
  ├─ .output/server/chunks/_/error-500.mjs (4.77 kB) (2.02 kB gzip)
  ├─ .output/server/chunks/_/error-500.mjs.map (190 B) (157 B gzip)
  ├─ .output/server/chunks/build/client.manifest.mjs (5.45 kB) (747 B gzip)
  ├─ .output/server/chunks/build/client.manifest.mjs.map (5.17 kB) (510 B gzip)
  ├─ .output/server/chunks/build/Component1-styles-1.mjs-CcdfUQQ_.mjs (246 B) (179 B gzip)
  ├─ .output/server/chunks/build/Component1-styles-1.mjs-CcdfUQQ_.mjs.map (123 B) (123 B gzip)
  ├─ .output/server/chunks/build/Component1-styles.BzxKMCYQ.mjs (385 B) (208 B gzip)
  ├─ .output/server/chunks/build/Component1-styles.BzxKMCYQ.mjs.map (240 B) (177 B gzip)
  ├─ .output/server/chunks/build/Component1-styles.D2S_p0P3.mjs (325 B) (201 B gzip)
  ├─ .output/server/chunks/build/Component1-styles.D2S_p0P3.mjs.map (218 B) (165 B gzip)
  ├─ .output/server/chunks/build/entry-styles-1.mjs-Bf3o1wln.mjs (12.6 kB) (2.64 kB gzip)
  ├─ .output/server/chunks/build/entry-styles-1.mjs-Bf3o1wln.mjs.map (118 B) (116 B gzip)
  ├─ .output/server/chunks/build/entry-styles.URl_9LWA.mjs (299 B) (200 B gzip)
  ├─ .output/server/chunks/build/entry-styles.URl_9LWA.mjs.map (208 B) (163 B gzip)
  ├─ .output/server/chunks/build/error-404-ChCbkRLp.mjs (15.6 kB) (4.71 kB gzip)
  ├─ .output/server/chunks/build/error-404-ChCbkRLp.mjs.map (338 B) (196 B gzip)
  ├─ .output/server/chunks/build/error-404-styles-1.mjs-D8Sw_W7I.mjs (3.79 kB) (1.22 kB gzip)
  ├─ .output/server/chunks/build/error-404-styles-1.mjs-D8Sw_W7I.mjs.map (122 B) (123 B gzip)
  ├─ .output/server/chunks/build/error-404-styles.BcoFjqgl.mjs (373 B) (211 B gzip)
  ├─ .output/server/chunks/build/error-404-styles.BcoFjqgl.mjs.map (238 B) (177 B gzip)
  ├─ .output/server/chunks/build/error-404-styles.DRLC0U6S.mjs (315 B) (205 B gzip)
  ├─ .output/server/chunks/build/error-404-styles.DRLC0U6S.mjs.map (216 B) (168 B gzip)
  ├─ .output/server/chunks/build/error-500-CY3ZbSXA.mjs (4.66 kB) (1.93 kB gzip)
  ├─ .output/server/chunks/build/error-500-CY3ZbSXA.mjs.map (196 B) (167 B gzip)
  ├─ .output/server/chunks/build/error-500-styles-1.mjs-DiWYPNRc.mjs (2.09 kB) (834 B gzip)
  ├─ .output/server/chunks/build/error-500-styles-1.mjs-DiWYPNRc.mjs.map (122 B) (123 B gzip)
  ├─ .output/server/chunks/build/error-500-styles.DPP87-Dp.mjs (371 B) (210 B gzip)
  ├─ .output/server/chunks/build/error-500-styles.DPP87-Dp.mjs.map (238 B) (178 B gzip)
  ├─ .output/server/chunks/build/error-500-styles.DqmriZ_b.mjs (315 B) (203 B gzip)
  ├─ .output/server/chunks/build/error-500-styles.DqmriZ_b.mjs.map (216 B) (165 B gzip)
  ├─ .output/server/chunks/build/page1-DCChe2oN.mjs (941 B) (450 B gzip)
  ├─ .output/server/chunks/build/page1-DCChe2oN.mjs.map (220 B) (152 B gzip)
  ├─ .output/server/chunks/build/page2-BhZZt8_r.mjs (582 B) (354 B gzip)
  ├─ .output/server/chunks/build/page2-BhZZt8_r.mjs.map (190 B) (154 B gzip)
  ├─ .output/server/chunks/build/page3-DY_00pby.mjs (1.76 kB) (641 B gzip)
  ├─ .output/server/chunks/build/page3-DY_00pby.mjs.map (154 B) (109 B gzip)
  ├─ .output/server/chunks/build/page4-B1QocBW7.mjs (583 B) (356 B gzip)
  ├─ .output/server/chunks/build/page4-B1QocBW7.mjs.map (121 B) (109 B gzip)
  ├─ .output/server/chunks/build/page5-wAbmS0WS.mjs (1.25 kB) (554 B gzip)
  ├─ .output/server/chunks/build/page5-wAbmS0WS.mjs.map (422 B) (220 B gzip)
  ├─ .output/server/chunks/build/server.mjs (132 kB) (24.2 kB gzip)
  ├─ .output/server/chunks/build/server.mjs.map (2.66 kB) (687 B gzip)
  ├─ .output/server/chunks/build/styles.mjs (1.39 kB) (416 B gzip)
  ├─ .output/server/chunks/build/styles.mjs.map (849 B) (279 B gzip)
  ├─ .output/server/chunks/build/welcome-styles.CyAsta2g.mjs (362 B) (204 B gzip)
  ├─ .output/server/chunks/build/welcome-styles.CyAsta2g.mjs.map (234 B) (174 B gzip)
  ├─ .output/server/chunks/routes/renderer.mjs (14.4 kB) (4.55 kB gzip)
  ├─ .output/server/chunks/routes/renderer.mjs.map (424 B) (226 B gzip)
  ├─ .output/server/chunks/runtime.mjs (174 kB) (42.1 kB gzip)
  ├─ .output/server/chunks/runtime.mjs.map (2.95 kB) (787 B gzip)
  ├─ .output/server/chunks/virtual/_virtual_spa-template.mjs (94 B) (100 B gzip)
  ├─ .output/server/chunks/virtual/_virtual_spa-template.mjs.map (112 B) (112 B gzip)
  ├─ .output/server/index.mjs (283 B) (186 B gzip)
  └─ .output/server/package.json (635 B) (312 B gzip)
Σ Total size: 1.98 MB (477 kB gzip)
✔ You can preview this build using node .output/server/index.mjs 
```

```
❯ npm test

> test
> node validate.cjs

CFhPsCYh.js validation failed ❌  - There were no sources in the file
    at /home/projects/gqairmgblw.github/dist/_nuxt/CFhPsCYh.js:1:1
    at /home/projects/gqairmgblw.github/dist/_nuxt/CFhPsCYh.js.map:1:1
CavbnZTK.js validation failed ❌  - There were no sources in the file
    at /home/projects/gqairmgblw.github/dist/_nuxt/CavbnZTK.js:1:1
    at /home/projects/gqairmgblw.github/dist/_nuxt/CavbnZTK.js.map:1:1
Dwtnv5GU.js validation failed ❌  - There were no sources in the file
    at /home/projects/gqairmgblw.github/dist/_nuxt/Dwtnv5GU.js:1:1
    at /home/projects/gqairmgblw.github/dist/_nuxt/Dwtnv5GU.js.map:1:1
YceNhqnM.js validation failed ❌  - There were no sources in the file
    at /home/projects/gqairmgblw.github/dist/_nuxt/YceNhqnM.js:1:1
    at /home/projects/gqairmgblw.github/dist/_nuxt/YceNhqnM.js.map:1:1
d3_E0v-c.js validation failed ❌  - There were no sources in the file
    at /home/projects/gqairmgblw.github/dist/_nuxt/d3_E0v-c.js:1:1
    at /home/projects/gqairmgblw.github/dist/_nuxt/d3_E0v-c.js.map:1:1

Sourcemap is empty on 5 files
```

**Comment by danielroe** [comment]
@onderceylan this is an upstream bug, right, and not to be resolved directly in nuxt?

**Comment by onderceylan** [comment]
@danielroe exactly!

**Comment by danielroe** [comment]
let's track there 🙏
