### ISSUE TITLE
Static site generation build process breaks when it encounters 'href' string in content json file

### ISSUE THREAD

**Issue by majoflosa** [nuxt/nuxt#29149]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.0.0`
- Nuxt Version:     `3.13.0`
- CLI Version:      `3.13.1`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@8.6.0`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`, `modules`, `features`, `tiptap`, `ignore`
- Runtime Modules:  `@nuxt/content@2.13.2`, `@nuxt/image@1.8.0`, `nuxt-tiptap-editor@2.0.0`
- Build Modules:    `-`

### Reproduction

https://github.com/majoflosa/nuxt-generate-bug-demo

### Describe the bug

Given a nuxt project using content module with .json files as content, and a page in the app that fetches that content:

If a value in these content files contains the string `href`, the build process will break when generating the  app as a static site by running `npm run generate` or `nuxt generate`.

For example, suppose I have a nuxt page that looks like
```
<script setup>
const { data } = await useAsyncData('test', () => queryContent('test').findOne());
</script>

<template>
  <div>
    <h1>Bug Demo: Nuxt Static Site Generation</h1>
    <pre>{{ data }}</pre>
  </div>
</template>
```

The page will fetch content from a file in `content/test.json`, which looks like:
```
{"normalString":"foobar", "errorCase1": "<a href=\"https://google.com/\">Example Link</a>"}
```

Trying to generate this static site causes an error:
```
  ERROR  [nuxt] [request error] [unhandled] [500] ENAMETOOLONG: name too long, open '/Users/mauricio/dev-experiments/nuxt-generate-bug-demo/.nuxt/cache/nitro/prerender/payload_%22https_google.com_%22%3EExample%20Link%3C_a%3E%22,%20%20%22_id%22_%20%22content_test.json%22,%20%20%22_type%22_%20%22json%22,%20%20%22title%22_%20%22Test%22,%20%20%22_source%22_%20%22content%22,%20%20%22_file%22_%20%22test.json%22,%20%20%22_stem%22_%20%22test%22,%20%20%22_extension%22_%20%22json%22%7D%3C_pre'

/"https://google.com//">Example Link</a>",  "_id": "content:test.json",  "_type": "json",  "title": "Test",  "_source": "content",  "_file": "test.json",  "_stem": "test",  "_extension": "json"}</pre (12ms)
  │ └── Error: [500] Page not found: /%22https://google.com//%22%3EExample%20Link%3C/a%3E%22,%20%20%22_id%22:%20%22content:test.json%22,%20%20%22_type%22:%20%22json%22,%20%20%22title%22:%20%22Test%22,%20%20%22_source%22:%20%22content%22,%20%20%22_file%22:%20%22test.json%22,%20%20%22_stem%22:%20%22test%22,%20%20%22_extension%22:%20%22json%22%7D%3C/pre

Errors prerendering:
[nitro 3:55:40 PM]   ├─ /"https://google.com//">Example Link</a>",  "_id": "content:test.json",  "_type": "json",  "title": "Test",  "_source": "content",  "_file": "test.json",  "_stem": "test",  "_extension": "json"}</pre (12ms)
  │ └── Error: [500] Page not found: /%22https://google.com//%22%3EExample%20Link%3C/a%3E%22,%20%20%22_id%22:%20%22content:test.json%22,%20%20%22_type%22:%20%22json%22,%20%20%22title%22:%20%22Test%22,%20%20%22_source%22:%20%22content%22,%20%20%22_file%22:%20%22test.json%22,%20%20%22_stem%22:%20%22test%22,%20%20%22_extension%22:%20%22json%22%7D%3C/pre

 ERROR  Exiting due to prerender errors.
at prerender (node_modules/nitropack/dist/chunks/prerender.mjs:220:11)
  at async node_modules/nuxt/dist/index.mjs:3628:5
  at async build (node_modules/nuxt/dist/index.mjs:5778:3)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:102:5)
  at async Object.run (node_modules/nuxi/dist/chunks/generate.mjs:60:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1777:7) 

```

### Additional context

The exact cause seems to be somewhat inconsistent. In this minimal reproduction example, the error only occurs if the problematic string (in a /content json file) contains `href=\"[some url here]\"`. In a different project, the error occurs if a string contains any instance of `href`. This issue is written assuming the cause is either the same or similar enough to explain any case.

This error only occurs when trying to generate the static site. The `build` and `dev` commands do not throw errors.

**Comment by danielroe** [comment]
Would you see if you can reproduce this in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose)? 🙏

**Comment by majoflosa** [comment]
Hi @danielroe - thanks for the response. I've made several attempts to reproduce this in a pure Nitro project, trying different prerender settings, and haven't been able to reproduce the error. 

Something that leads me to think it has to do with the Nuxt environment (or maybe Content module?) is the first line of the error output:
```
ERROR  [nuxt] [request error] [unhandled] [500] ENAMETOOLONG: name too long, open '/Users/mauricio/dev-experiments/nuxt-generate-bug-demo/.nuxt/cache/nitro/prerender/payload_%22https_google.com_%22%3EExample%20Link%3C_a%3E%22,%20%20%22_id%22_%20%22content_test.json%22,%20%20%22_type%22_%20%22json%22,%20%20%22title%22_%20%22Test%22,%20%20%22_source%22_%20%22content%22,%20%20%22_file%22_%20%22test.json%22,%20%20%22_stem%22_%20%22test%22,%20%20%22_extension%22_%20%22json%22%7D%3C_pre'
```
It seems the prerender process here is trying to take everything after `href=` and make it part of the file name in `payload_[some suffix here]`. These `payload` files aren't part of the process in a pure Nitro setup (unless there's something I should be doing to prompt building those `payload` files; happy to hear suggestions, if so).

So far, it looks like in Nuxt, nitro interprets `href=` as a signal to start creating a new file with the value of that `href` as the file name, as seen in the next line of the error:
```
/"https://google.com//">Example Link</a>",  "_id": "content:test.json",  "_type": "json",  "title": "Test",  "_source": "content",  "_file": "test.json",  "_stem": "test",  "_extension": "json"}</pre (12ms)
  │ └── Error: [500] Page not found: /%22https://google.com//%22%3EExample%20Link%3C/a%3E%22,%20%20%22_id%22:%20%22content:test.json%22,%20%20%22_type%22:%20%22json%22,%20%20%22title%22:%20%22Test%22,%20%20%22_source%22:%20%22content%22,%20%20%22_file%22:%20%22test.json%22,%20%20%22_stem%22:%20%22test%22,%20%20%22_extension%22:%20%22json%22%7D%3C/pre
```
Where we currently see `/"https://google.com//"...` it would usually show the name of the next file being created, when it's running normal, like `/about/_payload.json` for instance.

I've never tried setting up projects with just Nitro, so happy to try out suggestions to better attempt to replicate this there.

**Comment by danielroe** [comment]
this should now be resolved in the latest nitro as we now parse html to extract links
