### ISSUE TITLE
A link to a `public` `.json` file breaks prerender in `generate` mode

### ISSUE THREAD

**Issue by yannbertrand** [nuxt/nuxt#29202]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

1. Fork [CodeSandbox](https://codesandbox.io/p/devbox/qwts4p) code
2. `npm ci`
3. `npm run dev` -> should work correctly
4. `npm run generate` -> breaks due to 404 `/file.json`

---

Proof that it comes from the .json file only:
5. `rm public/file.json` and the `NuxtLink` from `pages/index.vue`
6. `npm run generate` -> should work correctly

### Describe the bug

`nuxt generate` breaks on the prerender step when a `.json` file is linked in a page.

### Additional context

Weirdly, it does not break the CodePen when the file containing the link is `app.vue`:
5. `mv pages/index.vue app.vue`
6. `npm run generate` -> should work correctly

### Logs

```shell-script
nitro 5:33:19 PM
  │ ├── Error: [404] Page not found: /file.json
  │ └── Linked from /
  ├─ /_payload.json (2ms)                                                                                         nitro 5:33:19 PM
                                                                                                                  nitro 5:33:19 PM
Errors prerendering:
  ├─ /file.json (11ms)                                                                                            nitro 5:33:19 PM
  │ ├── Error: [404] Page not found: /file.json
  │ └── Linked from /
                                                                                                                  nitro 5:33:19 PM

 ERROR  Exiting due to prerender errors.                                                                                5:33:19 PM

  at prerender (node_modules/nitropack/dist/chunks/prerender.mjs:220:11)
  at async node_modules/nuxt/dist/index.mjs:3628:5
  at async build (node_modules/nuxt/dist/index.mjs:5778:3)
  at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:101:5)
  at async Object.run (node_modules/nuxi/dist/chunks/generate.mjs:59:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.3e201632.mjs:1777:7) 



 ERROR  Exiting due to prerender errors.                                                                                5:33:19 PM
```
```

**Comment by adamdehaven** [comment]
I believe you can get around this by telling Nitro about the route:

```ts
  nitro: {
    prerender: {
      crawlLinks: true,
      // Specify routes that the crawler may not be able to discover for prerendering
      routes: [
        '/file.json',
      ],
    },
  },
```

**Comment by danielroe** [comment]
this has been resolved in v3.16.1.
