### ISSUE TITLE
Unable to use `vue/compiler-sfc` or `@vue/compiler-sfc` with nuxt

### ISSUE THREAD

**Issue by aiktb** [nuxt/nuxt#29312]
### Environment

  System:
    OS: Linux 5.15 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (18) x64 Intel(R) Core(TM) Ultra 5 125H
    Memory: 10.04 GB / 15.43 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 22.8.0 - ~/.nvm/versions/node/v22.8.0/bin/node
    pnpm: 9.12.0 - /mnt/c/Program Files/nodejs/pnpm
  npmPackages:
    nuxt: ^3.13.2 => 3.13.2 
    vue: latest => 3.5.11 

### Reproduction

https://stackblitz.com/edit/github-gdblwc?file=app.vue

app.vue:
```vue
<script  setup lang="ts">
// This causes `nuxt build` to report an error
// import {parse} from "vue/compiler-sfc"

// This causes `nuxt generate` to report an error
import {parse} from "@vue/compiler-sfc"

const source= `<template><div>111</div></template>`
</script>

<template>
  <div>
    {{ parse(source) }}
  </div>
</template>

```

### Use "vue/compiler-sfc" and run `nuxt build`

```bash
[nitro 11:58:43 AM]  ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([Function (anonymous)])


undefined


[11:58:43 AM]  ERROR  The "path" argument must be of type string. Received type function ([Function (anonymous)])

  at __node_internal_captureLargerStackTrace2 (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:5335)
  at new NodeError (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:4149)
  at validateString (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:265:1272)
  at Function.join (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:287:7889)
  at Object.mockPath [as then] (node_modules/@vercel/nft/out/analyze.js#cjs:174:27) 



[11:58:43 AM]  ERROR  The "path" argument must be of type string. Received type function ([Function (anonymous)])


~/projects/gqairmgblw.github 36s
```

### Use "@vue/compiler-sfc" and run `nuxt generate`

```bash
[nitro 11:55:11 AM] ℹ Prerendering 3 initial routes with crawler

[11:55:13 AM]  ERROR  [nuxt] [request error] [unhandled] [500] Cannot find package 'velocityjs' imported from /home/projects/gqairmgblw.github/.nuxt/prerender/chunks/build/server.mjs
  at __node_internal_captureLargerStackTrace2 (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:5335)  
  at new NodeError (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:4149)  
  at packageResolve (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:9724)  
  at moduleResolve (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:10188)  
  at defaultResolve (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:12372)  
  at ModuleLoader.defaultResolve (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:3284)  
  at ModuleLoader.resolve (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:2989)  
  at ModuleLoader.getModuleJob (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:1938)  
  at https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:155:1047  
  at _0x24d9dc.link (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:786141)  
  at https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:155:1002


[11:55:13 AM]  ERROR  [nuxt] [request error] [unhandled] [500] Cannot find package 'velocityjs' imported from /home/projects/gqairmgblw.github/.nuxt/prerender/chunks/build/server.mjs
  at __node_internal_captureLargerStackTrace2 (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:5335)  
  at new NodeError (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:4149)  
  at packageResolve (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:9724)  
  at moduleResolve (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:10188)  
  at defaultResolve (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:158:12372)  
  at ModuleLoader.defaultResolve (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:3284)  
  at ModuleLoader.resolve (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:2989)  
  at ModuleLoader.getModuleJob (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:154:1938)  
  at https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:155:1047  
  at _0x24d9dc.link (https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/blitz.134daa3c.js:40:786141)  
  at https://gqairmgblwgithub-c5kt.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:155:1002

[nitro 11:55:13 AM]   ├─ / (1188ms)
  │ └── Error: [500] 
[nitro 11:55:13 AM]   ├─ /200.html (1173ms)
[nitro 11:55:13 AM]   ├─ /404.html (1174ms)
[nitro 11:55:13 AM] 
Errors prerendering:
[nitro 11:55:13 AM]   ├─ / (1188ms)
  │ └── Error: [500] 
[nitro 11:55:13 AM] 

[11:55:13 AM]  ERROR  Exiting due to prerender errors.

  at Module.prerender (node_modules/nitropack/dist/chunks/prerender.mjs:235:11)
  at async eval (node_modules/nuxt/dist/index.mjs:3645:5) 



[11:55:13 AM]  ERROR  Exiting due to prerender errors.

```

### Additional context

This is the same as part #28208, but I didn't think the copy there was small enough, so opened this one.

I don't see `velocityjs` in pnpm-lock.yaml, it's like a module that appeared out of thin air.

And `velocityjs` is not a special case, if you install `velocityjs`, there will be other non-existent dependencies that will give the same error.

**Comment by Arnav12S** [comment]
I'm new here as well, but it think it's the import statement that's causing the errors.

> <script setup lang="ts">
// This causes `nuxt build` to report an error
import { parseComponent } from 'vue/compiler-sfc';

// This causes `nuxt generate` to report an error
// import {parse} from "@vue/compiler-sfc"

const source = '<template><div>111</div></template>';
</script>

<template>
  <div>
    {{ source }}
  </div>
</template>


This works well for me and took the reference from [here](https://github.com/ktsn/vue-sfc-parser)

**Comment by manniL** [comment]
I'm not sure that the SFC compiler should be used at runtime like this.
Instead, you want to enable the **runtime compiler** and generate your templates dynamically via render function or similar.

**Comment by aiktb** [comment]
> > This package contains lower level utilities that you can use if you are writing a plugin / transform for a bundler or module system that compiles Vue Single File Components (SFCs) into JavaScript. It is used in [vue-loader](https://github.com/vuejs/vue-loader) and [@vitejs/plugin-vue](https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue).
> 
> I'm not sure that the SFC compiler should be used at runtime like this. Instead, you want to enable the **runtime compiler** (via `vue.runtimeCompiler`) and generate your templates dynamically via render function or similar.

Thank you for reply.

I don't want to dynamically render components at runtime, but I want to get the AST Tokens corresponding to Vue SFC. I checked the test cases of [vue.runtimeCompiler](https://github.com/nuxt/nuxt/blob/01bee2f0ead9efd88773e5de4ebad5eda4433e67/test/fixtures/runtime-compiler/pages/index.vue#L16) and didn't understand how to get AST. Is this feasible?

My usecase is close to https://ts-ast-viewer.com/
