### ISSUE TITLE
[500] __vite_ssr_import_0__.incrementer is not a function

### ISSUE THREAD

**Issue by Podolchak** [nuxt/nuxt#29529]
### Environment

Nuxt3

- Operating System: Darwin
- Node Version:     v20.14.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  yarn@1.22.22
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Fresh install

### Describe the bug

[1]  ERROR  [nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.incrementer is not a function
[1]   at ./node_modules/vue-i18n/dist/vue-i18n.mjs:33:37  
[1]   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
[1]   at async ViteNodeRunner.runModule (./node_modules/vite-node/dist/client.mjs:399:5)  
[1]   at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:381:5)  
[1]   at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:206:14)  
[1]   at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:259:12)  
[1]   at async ./node_modules/@nuxtjs/i18n/dist/runtime/composables/index.js:21:32  
[1]   at async ViteNodeRunner.runModule (./node_modules/vite-node/dist/client.mjs:399:5)  
[1]   at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:381:5)  
[1]   at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:206:14)

**Comment by raysato** [comment]
I had the same error with vue-i18n.
Upgrading it to the latest version (`^10.0.4`) worked for me.

**Comment by tonori** [comment]
I also encountered the same issue, and I found that @nuxtjs/i18n currently uses vue-i18n@9, but the latest version of vue-i18n@latest on npm is ^10.0.4. After switching from @nuxtjs/i18n to @nuxtjs/i18n@next, @nuxtjs/i18n@next and vue-i18n v10 will work as expected.

### Environment

- "nuxt": "^3.13.2"
- "vue-i18n": "10.0.4"
- "@nuxtjs/i18n": "9.0.0-rc.2"
