### ISSUE TITLE
useAsyncData -  ERROR  Failed to parse URL

### ISSUE THREAD

**Issue by maksimdrosdov** [nuxt/nuxt#29626]
### Environment

```
- Operating System: Darwin
- Node Version:     v21.6.2
- Nuxt Version:     3.13.0
- CLI Version:      3.13.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.3
- Builder:          -
- User Config:      devtools, experimental, runtimeConfig, routeRules, app, css, plugins, modules, proxy, googleFonts, primevue, tailwindcss, compatibilityDate, vite
- Runtime Modules: nuxt-proxy-request@1.10.0
- Build Modules:    -
```

### Reproduction

I get error

```
 ERROR  Failed to parse URL from /api/search?order=price_asc&categories=8

  at node:internal/deps/undici/undici:12443:11
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:222:26)
  at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15)


 ERROR  Failed to parse URL from /api/search?order=price_asc&categories=8

  at node:internal/deps/undici/undici:12443:11
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:222:26)
  at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15)

```

fetch plugin

```
import { ofetch, type FetchContext } from "ofetch";
import { defineNuxtPlugin } from "#app";

export default defineNuxtPlugin(() => {
  const headers = useRequestHeaders(["cookie"]);
  globalThis.$fetch = ofetch.create({
    headers,
    credentials: "include",
    retry: 0,
    onRequestError({ error }) {
      console.error(error);
    },
  });
});
```

```
const { products, totalPages, fetchFilteredProducts } = useProducts();

const { refresh, error } = await useAsyncData(
  "products",
  () => fetchFilteredProducts(queryParams.value),
  {
    server: true,
    lazy: true,
    watch: [queryParams.value],
  }
);

```
composable

```
export const useProducts = () => {
  const $projectServices = useProjectService();

  const state = reactive({
    products: [],
    totalPages: 0,
  });

const fetchFilteredProducts = async (queryParams: any) => {
    try {
      const response = await globalThis.$fetch("/api/search", {
        method: "GET",
        params: queryParams,
      });

      state.products = response.products;
      state.totalPages = response.count;
      return response;
    } catch (err) {
      throw err;
    }
  };

  return {
    ...toRefs(state),
    fetchFilteredProducts,
  };
};
```

### Describe the bug

I get an error when I reload the page using f5.

Via useFetch

```
const {
  data: initialProductsData,
  refresh,
  error,
} = await useFetch(urlGenerator.searchProductsUrl(), {
  lazy: true,
  watch: false,
  params: queryParams.value,
});


```

everything works fine, but I need asyncData to reuse composable

**Comment by maksimdrosdov** [comment]
work

```
const {
  data: initialProductsData,
  refresh,
  error,
} = await useFetch(urlGenerator.searchProductsUrl(), {
  lazy: true,
  watch: false,
  params: queryParams,
});
```

**Comment by maksimdrosdov** [comment]
> Без нашего `$fetch`обработчика вы не сможете выполнить fetch без хоста. Узел не знает, куда отправить сетевой запрос.



> You're overriding the default `$fetch` handler, which is not supported. Instead, create your own fetch with a different name, and use that.
> 
> Without our custom `$fetch` handler, you can't possibly fetch without a host. Node doesn't know where to send the network request.

I don’t quite understand, but how to get your $fetch?

**Comment by maksimdrosdov** [comment]
> You're overriding the default `$fetch` handler, which is not supported. Instead, create your own fetch with a different name, and use that.
> 
> Without our custom `$fetch` handler, you can't possibly fetch without a host. Node doesn't know where to send the network request.
I created my own, but everything is the same

```
import { ofetch } from "ofetch";
import { defineNuxtPlugin } from "#app";

export default defineNuxtPlugin(() => {
  const headers = useRequestHeaders(["cookie"]);
  const fetchApi = ofetch.create({
    headers,
    credentials: "include",
    retry: 0,
    onRequestError({ error }) {
      console.error(error);
    },
  });

  return {
    provide: {
      fetchApi,
    },
  };
});
```
