### ISSUE TITLE
Netlify - pbl with nitro 2.10.2

### ISSUE THREAD

**Issue by cfab** [nuxt/nuxt#29778]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.15.1`
- Nuxt Version:     `3.14.0`
- CLI Version:      `3.15.0`
- Nitro Version:    `2.10.2`
- Package Manager:  `npm@10.7.0`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/cfab/sandbox

### Describe the bug

Build error when deploying to netlify

````
[error] [nitro] RollupError: [plugin impound] This module cannot be imported in server runtime. [importing `node_modules/nitropack/dist/presets/netlify/legacy/runtime/_deno-env-polyfill` from `node_modules/nitropack/dist/presets/netlify/legacy/runtime/netlify.mjs`]
9:52:11 PM: undefined
9:52:11 PM: [error] [plugin impound] This module cannot be imported in server runtime. [importing `node_modules/nitropack/dist/presets/netlify/legacy/runtime/_deno-env-polyfill` from `node_modules/nitropack/dist/presets/netlify/legacy/runtime/netlify.mjs`]
9:52:11 PM:   at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:396:41)
9:52:11 PM:   at error (node_modules/rollup/dist/es/shared/parseAst.js:392:42)
9:52:11 PM:   at Object.error (node_modules/rollup/dist/es/shared/node-entry.js:20604:20)
9:52:11 PM:   at Object.resolveId (node_modules/impound/dist/index.js:29:11)
9:52:11 PM:   at node_modules/rollup/dist/es/shared/node-entry.js:20789:40
9:52:11 PM:   at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/node-entry.js:20689:28)
9:52:11 PM:   at async resolveId (node_modules/rollup/dist/es/shared/node-entry.js:19293:26)
9:52:11 PM:   at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/node-entry.js:19722:15)
9:52:11 PM:   at async Object.resolveId (node_modules/@rollup/plugin-commonjs/dist/es/index.js:600:10)
9:52:11 PM:   at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/node-entry.js:20689:28)
9:52:11 PM: [error] [plugin impound] This module cannot be imported in server runtime. [importing `node_modules/nitropack/dist/presets/netlify/legacy/runtime/_deno-env-polyfill` from `node_modules/nitropack/dist/presets/netlify/legacy/runtime/netlify.mjs`]
9:52:11 PM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
9:52:11 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
9:52:11 PM: ​
9:52:11 PM: "build.command" failed                                        
```

### Additional context

Probably related to same as https://github.com/nitrojs/nitro/issues/2846

### Logs

_No response_

**Comment by aSchaffe** [comment]
same issue

**Comment by dbzx10299** [comment]
Same here

**Comment by manniL** [comment]
Fixed in nightly via https://github.com/nuxt/nuxt/pull/29780
