### ISSUE TITLE
Cloudflare module preset fails after upgrading to Nuxt 3.14.0

### ISSUE THREAD

**Issue by they-cloned-me** [nuxt/nuxt#29784]
### Environment

```
- Operating System: Darwin
- Node Version:     v22.6.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    2.10.2
- Package Manager:  bun@1.1.27
- Builder:          -
- User Config:      default
- Runtime Modules:  `@nuxt/fonts@0.10.2`, `nitro-cloudflare-dev@0.2.1`
- Build Modules:    -
```

### Reproduction

1. Set preset to `cloudflare-modules`
```ts
nitro: {
  preset: "cloudflare-module",
},
```

2. Run the dev command: `bun run dev`

https://github.com/user-attachments/assets/037b876d-d14f-4554-98b4-46d9997d6dce

### Describe the bug

After upgrading to the latest release (Nuxt v3.14.0), running the dev command, 
`bun run dev` fails with

```
RollupError: [plugin impound] This module cannot be imported in server runtime.
[importing node_modules/nitropack/node_modules/unenv/runtime/fetch/index.mjs from node_modules/nitropack/dist/runtime/internal/app.mjs]
```

### Additional context

package.json
```json
{
"dependencies": {
    "drizzle-orm": "^0.36.0",
    "nuxt": "^3.14.0",
    "nuxt-auth-utils": "^0.5.1",
    "vue": "latest",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20241022.0",
    "@nuxt/fonts": "^0.10.2",
    "drizzle-kit": "^0.27.1",
    "nitro-cloudflare-dev": "^0.2.1",
    "typescript": "^5.6.3",
    "wrangler": "^3.84.1"
  }
}
```

**Comment by RynerNO** [comment]
Seems like netlify preset broken too in 3.14.0:
```2:24:17 AM: [log] [@nuxt/fonts]   ├─ https://fonts.gstatic.com/s/poppins/v21/pxiEyp8kv8JHgFVrFJM.woff
2:24:17 AM: [log] [@nuxt/fonts]   ├─ https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLGT9V1g.woff
2:24:17 AM: [log] [@nuxt/fonts]   ├─ https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLEj6V1g.woff
2:24:17 AM: [log] [@nuxt/fonts]   ├─ https://fonts.gstatic.com/s/poppins/v21/pxiByp8kv8JHgFVrLCz7V1g.woff
2:24:17 AM: [success] [@nuxt/fonts] Fonts downloaded and cached.
2:24:17 AM: [success] [nitro] Generated public dist
2:24:17 AM: Duplicated imports "getPathRobotConfig", the one from "/opt/build/repo/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/composables/getPathRobotConfigPolyfill" has been ignored and "/opt/build/repo/node_modules/@nuxtjs/robots/dist/runtime/nitro/composables/getPathRobotConfig.js" is used
2:24:17 AM: [info] [nitro] Building Nuxt Nitro server (preset: `netlify`, compatibility date: `2024-10-10`)
2:24:17 AM: [error] [nitro] RollupError: [plugin impound] This module cannot be imported in server runtime. [importing `node_modules/nitropack/dist/presets/netlify/runtime/_deno-env-polyfill` from `node_modules/nitropack/dist/presets/netlify/runtime/netlify.mjs`]
2:24:17 AM: undefined
2:24:17 AM: [error] [plugin impound] This module cannot be imported in server runtime. [importing `node_modules/nitropack/dist/presets/netlify/runtime/_deno-env-polyfill` from `node_modules/nitropack/dist/presets/netlify/runtime/netlify.mjs`]
2:24:17 AM:   at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:396:41)
2:24:17 AM:   at error (node_modules/rollup/dist/es/shared/parseAst.js:392:42)
2:24:17 AM:   at Object.error (node_modules/rollup/dist/es/shared/node-entry.js:20604:20)
2:24:17 AM:   at Object.resolveId (node_modules/impound/dist/index.js:29:11)
2:24:17 AM:   at node_modules/rollup/dist/es/shared/node-entry.js:20789:40
2:24:17 AM:   at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/node-entry.js:20689:28)
2:24:17 AM:   at async resolveId (node_modules/rollup/dist/es/shared/node-entry.js:19293:26)
2:24:17 AM:   at async ModuleLoader.resolveId (node_modules/rollup/dist/es/shared/node-entry.js:19722:15)
2:24:17 AM:   at async Object.resolveId (node_modules/@rollup/plugin-commonjs/dist/es/index.js:600:10)
2:24:17 AM:   at async PluginDriver.hookFirstAndGetPlugin (node_modules/rollup/dist/es/shared/node-entry.js:20689:28)
2:24:17 AM: [error] [plugin impound] This module cannot be imported in server runtime. [importing `node_modules/nitropack/dist/presets/netlify/runtime/_deno-env-polyfill` from `node_modules/nitropack/dist/presets/netlify/runtime/netlify.mjs`]
2:24:17 AM: ​
2:24:17 AM: "build.command" failed                                        
2:24:17 AM: ────────────────────────────────────────────────────────────────
2:24:17 AM: ​
2:24:17 AM:   Error message
2:24:17 AM:   Command failed with exit code 1: npm run build (https://ntl.fyi/exit-code-1)
```

Downgrade to 3.13.0 fixed the issue

**Comment by they-cloned-me** [comment]
Unfortunately, this issue is not solved, even with the latest updates.

**Comment by franklin-tina** [comment]
I had a similar issue using Bun, but everything worked properly when I switched back to node.
Hope this helps.
cc @danielroe

**Comment by they-cloned-me** [comment]
@danielroe 
I have [this reproduction on codesandbox](https://codesandbox.io/p/devbox/charming-neumann-v45j9g) (uses pnpm) and everything seems to works as expected.

I’m concluding with @franklin-tina [here](https://github.com/nuxt/nuxt/issues/29784#issuecomment-2461054418) that it may be an issue with Bun

**Comment by philipp6690** [comment]
same issue after the update, also using bun as package manager

**Comment by franklin-tina** [comment]
@philipp6690 @they-cloned-me  I reopened at #29884. 
Please add more details/comment if you find it lacking some context 🙏🏿
