### ISSUE TITLE
3.14 vue-class-component

### ISSUE THREAD

**Issue by mak7an** [nuxt/nuxt#29803]
@__vite_ssr_import_0__.Options({ layer: "admin" }) class IndexPage extends Vue {
  ^

Not it not work at all. Thank you for jiti very much

**Comment by mak7an** [comment]
[Vue Router warn]: No match found for location with path "/_nuxt/vendors-node_modules_webpack-hot-middleware_client_js_reload_true_timeout_30000_path_2F__webp-ed025a.js"

**Comment by mak7an** [comment]
All day I try to do something with acorn to work with classes and definepagemeta, remove decorators from string processed by, add ts plugins to acorn :)

**Comment by mak7an** [comment]
```

500
Cannot read properties of undefined (reading 'ids')

at async Promise.all (index 0)
at async setup (./node_modules/nuxt/dist/core/runtime/nitro/renderer.js:525:1)
at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)
at async applyPlugin (./node_modules/nuxt/dist/core/runtime/nitro/renderer.js:525:1)
at async executePlugin (./node_modules/nuxt/dist/core/runtime/nitro/renderer.js:525:1)
at async applyPlugins (./node_modules/nuxt/dist/core/runtime/nitro/renderer.js:525:1)
at async createNuxtAppServer (./node_modules/nuxt/dist/core/runtime/nitro/renderer.js:525:1)
at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19)
at async Object.render (./node_modules/nuxt/dist/core/runtime/nitro/renderer.js:202:21)
```

**Comment by mak7an** [comment]
ERROR  (node:19098) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use node --trace-deprecation ... to show where the warning was created)

**Comment by mak7an** [comment]
[worker reload] [worker init] /home/michael/Desktop/test/xo/.nuxt/dev/index.mjs failed

**Comment by mak7an** [comment]
bun x nuxi@latest init nuxt

[11:31:36 PM]  ERROR  Error: Failed to download template from registry: Failed to download https://raw.githubusercontent.com/nuxt/starter/templates/templates/v3.json: TypeError: fetch failed
