### ISSUE TITLE
Nuxt v3.14.159: ERROR  Nuxt module should be a function: [object Object]

### ISSUE THREAD

**Issue by InvixGG** [nuxt/nuxt#29822]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  pnpm@9.12.3
- Builder:          rspack
- User Config:      default
- Runtime Modules:  @nuxtjs/tailwindcss@6.12.2, @nuxtjs/supabase@1.4.1, @nuxt/image@1.8.1, shadcn-nuxt@0.11.2, @nuxt/icon@1.6.1, @nuxt/fonts@0.10.2, @nuxtjs/color-mode@3.5.2, @nuxt/rspack-builder@3.14.159
- Build Modules:    -
------------------------------

### Reproduction

`package.json`:
```json
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "host": "nuxt dev --host",
    "dev": "nuxt dev",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@dotenvx/dotenvx": "^1.22.0",
    "@nuxt/fonts": "^0.10.2",
    "@nuxt/icon": "^1.6.1",
    "@nuxt/image": "^1.8.1",
    "@nuxt/rspack-builder": "^3.14.159",
    "@nuxtjs/color-mode": "^3.5.2",
    "@nuxtjs/supabase": "^1.4.1",
    "@vee-validate/zod": "^4.14.6",
    "@vueuse/core": "^11.2.0",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "lucide-vue-next": "^0.454.0",
    "nuxt": "^3.14.159",
    "radix-vue": "^1.9.8",
    "shadcn-nuxt": "^0.11.2",
    "tailwind-merge": "^2.5.4",
    "tailwindcss-animate": "^1.0.7",
    "vee-validate": "^4.14.6",
    "vue": "latest",
    "zod": "^3.23.8"
  },
  "packageManager": "pnpm@9.12.3",
  "devDependencies": {
    "@iconify-json/ic": "^1.2.1",
    "@iconify-json/mdi": "^1.2.1",
    "@nuxtjs/tailwindcss": "^6.12.2",
    "typescript": "^5.6.3"
  }
}
```

`nuxt.config.ts`:
```ts
import {defineNuxtConfig} from 'nuxt/config';

export default defineNuxtConfig({
    devtools: {
        enabled: true,

        timeline: {
            enabled: true
        }
    },
    builder: 'rspack',
    compatibilityDate: '2024-10-25',
    modules: [
      '@nuxtjs/tailwindcss',
      '@nuxtjs/supabase',
      '@nuxt/image',
      'shadcn-nuxt',
      '@nuxt/icon',
      '@nuxt/fonts',
      '@nuxtjs/color-mode',
      '@nuxt/rspack-builder'
    ],
});
```

### Describe the bug

This happens when adding @nuxt/rspack-builder.

```
 ERROR  Nuxt module should be a function: [object Object]

  at loadNuxtModuleInstance (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2460:11)
  at async installModule (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_magicast@0.3.5_rollup@4._yvk4y57n46krfngabiv4qthxtq/node_modules/nuxt/dist/index.mjs:4669:5)
  at async loadNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_ioredis@5.4.1_magicast@0.3.5_rollup@4._yvk4y57n46krfngabiv4qthxtq/node_modules/nuxt/dist/index.mjs:4839:5)
  at async loadNuxt (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/@nuxt+kit@3.14.159_magicast@0.3.5_rollup@4.24.4_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2627:19)
  at async Object.run (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:2019:10)
  at async Object.setup (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/add2.mjs:197:5)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1620:5)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runCommand$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (/D:/Documents/Invix%20Digital/Companies/Praetium/Development/app/node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7)

### Additional context

_No response_

### Logs

_No response_

**Comment by danielroe** [comment]
`@nuxt/rspack-builder` is not a module. you set `builder: 'rspack'` to use it.

**Comment by InvixGG** [comment]
> `@nuxt/rspack-builder` is not a module. you set `builder: 'rspack'` to use it.

I see, done that now.

But now I get this?
```
[4:21:45 PM]  ERROR  Cannot start nuxt:  Cannot find package 'D:\Documents\Invix Digital\Companies\Praetium\Development\app\node_modules\.pnpm\@nuxt+rspack-builder@3.14.159_@swc+helpers@0.5.13_magicast@0.3.5_pug@3.0.3_rollup@4.24.4_type_zi
smyuo3sjhbv3u7aspgsmh3au\node_modules\@nuxt\friendly-errors-webpack-plugin\package.json' imported from D:\Documents\Invix Digital\Companies\Praetium\Development\app\node_modules\.pnpm\@nuxt+rspack-builder@3.14.159_@swc+helpers@0.5.13_magicast@0.3.5_pug@3.0.3_rollup@4.24.4_type_zismyuo3sjhbv3u7aspgsmh3au\node_modules\@nuxt\rspack-builder\dist\index.mjs
Did you mean to import "@nuxt/friendly-errors-webpack-plugin/index.js"?

  Did you mean to import "@nuxt/friendly-errors-webpack-plugin/index.js"?
  at legacyMainResolve (node:internal/modules/esm/resolve:215:26)
  at packageResolve (node:internal/modules/esm/resolve:841:14)
  at moduleResolve (node:internal/modules/esm/resolve:927:18)
  at defaultResolve (node:internal/modules/esm/resolve:1157:11)
  at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
  at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
  at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
  at link (node:internal/modules/esm/module_job:86:36)
```
