### ISSUE TITLE
Unable to load module.ts as the entry point of the local module.

### ISSUE THREAD

**Issue by ahas** [nuxt/nuxt#29838]
### Environment

- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.159
- CLI Version:      3.15.0
- Nitro Version:    2.10.3
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  ./modules/my-module
- Build Modules:    -

### Reproduction

[Working reproduction (3.13.0)](https://stackblitz.com/edit/nuxt-starter-8fd3te?file=package.json)
[Not working reproduction (3.14.159)](https://stackblitz.com/edit/nuxt-starter-gy1kco?file=package.json)

### Describe the bug

When the entry point of the local module is module.ts, it works in version 3.13.0 but does not work in 3.14.159. However, if the entry point is index.ts, it works in 3.14.159.

### Logs

❯ npm install && npm run dev

> postinstall
> nuxt prepare

 ERROR  Nuxt module should be a function: ./modules/my-module                                                 오후 3:41:12

  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2549:11)
  at async Module.installModule (node_modules/@nuxt/kit/dist/index.mjs:2478:47)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4686:5)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:4856:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:2716:19)
  at async Object.run (node_modules/nuxi/dist/chunks/prepare.mjs:76:18)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1680:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1671:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1809:7)

**Comment by danielroe** [comment]
for now you can use `./modules/my-module/module` - we'll fix in next patch

**Comment by productdevbook** [comment]
![Image](https://github.com/user-attachments/assets/0502303c-abda-45b1-8fc0-cb67dcb11629)

same error in the new version.

**Comment by IvanWala** [comment]
ERROR  Nuxt module should be a function: @pinia-plugin-persistedstate/nuxt                                   17:19:16

  at loadNuxtModuleInstance (/C:/xvue/htdocs/Rubi/rubi-frontend-2/site/node_modules/@nuxt/kit/dist/index.mjs:2466:11)
  at async installModule (/C:/xvue/htdocs/Rubi/rubi-frontend-2/site/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (/C:/xvue/htdocs/Rubi/rubi-frontend-2/site/node_modules/nuxt/dist/index.mjs:4684:5)
  at async loadNuxt (/C:/xvue/htdocs/Rubi/rubi-frontend-2/site/node_modules/nuxt/dist/index.mjs:4854:5)
  at async loadNuxt (/C:/xvue/htdocs/Rubi/rubi-frontend-2/site/node_modules/@nuxt/kit/dist/index.mjs:2633:19)
  at async Object.run (/C:/xvue/htdocs/Rubi/rubi-frontend-2/site/node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
  at async runCommand$1 (/C:/xvue/htdocs/Rubi/rubi-frontend-2/site/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand (/C:/xvue/htdocs/Rubi/rubi-frontend-2/site/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:2019:10)
  at async Object.setup (/C:/xvue/htdocs/Rubi/rubi-frontend-2/site/node_modules/nuxi/dist/chunks/add2.mjs:197:5)
  at async runCommand$1 (/C:/xvue/htdocs/Rubi/rubi-frontend-2/site/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1620:5)



 ERROR  Nuxt module should be a function: @pinia-plugin-persistedstate/nuxt                                   17:19:16
