### ISSUE TITLE
ERROR  Nuxt module should be a function in Nuxt 3.14.159

### ISSUE THREAD

**Issue by timbenniks** [nuxt/nuxt#29848]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.17.0`
- Nuxt Version:     `3.14.159`
- CLI Version:      `3.15.0`
- Nitro Version:    `2.10.3`
- Package Manager:  `npm@10.8.2`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `./modules/test`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-5vkxur

### Describe the bug

I'm using a local module (not 3rd party) that uses `defineNuxtModule` from `@nuxt/kit` and I get the following error: `[09:20:27]  ERROR  Cannot start nuxt:  Nuxt module should be a function: ./modules/test`

### Additional context

I've seen a few more error reports like this, but none for local modules. Hence this ticket.

### Logs

npm run dev

> dev
> nuxt dev

Nuxt 3.14.159 with Nitro 2.10.3                                                                                                                        9:25:07 AM
                                                                                                                                                       9:25:07 AM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

 ERROR  Cannot start nuxt:  Nuxt module should be a function: ./modules/test                                                          9:25:08 AM

  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2460:11)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:4669:5)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:1894:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:1828:7)
  at async NuxtDevServer.init (node_modules/nuxi/dist/chunks/dev2.mjs:1823:5)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-child.mjs:104:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7)

**Comment by danielroe** [comment]
for now you can use `./modules/test/module`

**Comment by danielroe** [comment]
let's track in https://github.com/nuxt/nuxt/issues/29838.

**Comment by timbenniks** [comment]
Apologies for not referencing: https://github.com/nuxt/nuxt/issues/29838
