### ISSUE TITLE
Can't be fixed! Error: [nuxt] instance unavailable

### ISSUE THREAD

**Issue by VladislavYakonyuk** [nuxt/nuxt#29937]
Either I don't know Nuxt well, or there is some problem. Why my application has recently decided to crash with `Error: [nuxt] instance unavailable`? We were only making edits to the ui part, not touching any other layers and not addressing useNuxtApp and stuff. Now when the page loads, it redirects to en/ (we have i18n module) and gets 500 error. And it is reproduced only in production mode. 

Please help me, I am already in despair 

Full log:
```
node .output/server/index.mjs
Listening on http://[::]:3000
Error: [nuxt] instance unavailable
    at useNuxtApp (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/build/server.mjs:595:13)
    at setup (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/build/server.mjs:10540:37)
    at _sfc_main.setup (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/build/server.mjs:10578:23)
    at callWithErrorHandling (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:82:19)
    at setupStatefulComponent (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:6039:25)
    at setupComponent (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:6026:36)
    at renderComponentVNode (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:358:15)
    at renderToString (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:649:24)
    at Object.renderToString$1 [as renderToString] (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/routes/renderer.mjs:147:24)
    at Object.renderToString (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:174:40)
Error: [nuxt] instance unavailable
    at useNuxtApp (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/build/server.mjs:595:13)
    at setup (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/build/server.mjs:10540:37)
    at _sfc_main.setup (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/build/server.mjs:10578:23)
    at callWithErrorHandling (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:82:19)
    at setupStatefulComponent (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:6039:25)
    at setupComponent (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:6026:36)
    at renderComponentVNode (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:358:15)
    at renderToString (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:649:24)
    at Object.renderToString$1 [as renderToString] (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/routes/renderer.mjs:147:24)
    at Object.renderToString (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:174:40)
Error: [nuxt] instance unavailable
    at useNuxtApp (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/build/server.mjs:595:13)
    at setup (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/build/server.mjs:10540:37)
    at _sfc_main.setup (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/build/server.mjs:10578:23)
    at callWithErrorHandling (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:82:19)
    at setupStatefulComponent (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:6039:25)
    at setupComponent (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:6026:36)
    at renderComponentVNode (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:358:15)
    at renderToString (/Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:649:24)
    at Object.renderToString$1 [as renderToString] (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/chunks/routes/renderer.mjs:147:24)
    at Object.renderToString (file:///Users/vlados/Documents/master-code/Funkcio/funkcio-web-client/.output/server/node_modules/vue-bundle-renderer/dist/runtime.mjs:174:40)
```

**Comment by VladislavYakonyuk** [comment]
I had an app on nuxt that had been running stable for quite some time. The only thing I changed were the edits in vue components. But during recent updates on the server, I noticed the problem I wrote about above.

All this time I tried to find the reasons, helped to create a clean nuxt project, where I first moved all the dependencies and there it began. I tried only specifying `nuxt` and `vue` dependencies with `vue-router` as I had them. On the clean nuxt project everything was crashing (500 error on startup in production mod). It helped to specify latest for `vue` and `vue-router `

```json
"dependencies": {
    "nuxt": "3.10.3",
    "vue": "3.4.20",
    "vue-router": "4.2.5"
}
```

**Comment by AasmundN** [comment]
I am getting the same error message. The situation is similar to yours, an application that has been running fine for a couple years suddenly stopped working. However it still works locally. I will look into it.

**Comment by doobie-droid** [comment]
@AasmundN @VladislavYakonyuk  were either of you able to get a fix to the issue, if so, please can you link it here. The solution I [saw](https://github.com/nuxt/nuxt/issues/14215#issuecomment-1397348345) about removing the import from nuxt/app  does not work for me. I would appreciate any help you can give.

**Comment by AasmundN** [comment]
@doobie-droid we were able to fix it but I don't know what the exact error was. We updated node from version 18 to 20, and Nuxt from version 3.10 to 3.15.1, which solved it.

**Comment by VladislavYakonyuk** [comment]
> [@doobie-droid](https://github.com/doobie-droid) we were able to fix it but I don't know what the exact error was. We updated node from version 18 to 20, and Nuxt from version 3.10 to 3.15.1, which solved it.

Thank you for the reply! Yes, that's exactly how my team and I solved the problem. If you have problems that you can't detect - the first thing I recommend to do is to build a clean application a little bit at a time and move possible trouble spots there. And also play with package versions. I've adopted this

**Comment by doobie-droid** [comment]
@VladislavYakonyuk @AasmundN ... thank you guys so much for your response. This worked for me
