### ISSUE TITLE
Problem with chunkErrorEvent on Nuxt 3.14.159 + nuxt-delay-hydration

### ISSUE THREAD

**Issue by eZ4hUNt** [nuxt/nuxt#29953]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v22.11.0
- Nuxt Version:     3.13.1
- CLI Version:      3.15.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.12.2
- Builder:          -
- User Config:    default
- Runtime Modules:  @vueuse/nuxt@11.2.0, @nuxt/image@1.8.1, nuxt-security@2.0.0-rc.9, @nuxtjs/device@3.2.4, dayjs-nuxt@2.1.11, nuxt-delay-hydration@1.3.8, nuxt-purgecss@2.0.0, @nuxtjs/critters@0.7.2, nuxt-booster@3.1.6, @nuxtjs/tailwindcss@6.12.2, @primevue/nuxt-module@4.2.2, @nuxtjs/robots@3.0.0, @nuxtjs/i18n@8.5.6
- Build Modules:    -
------------------------------

### Reproduction

When using nuxt-delay-hydration and ssr, there is a problem during build due to missing chunkErrorEvent

### Describe the bug

When using nuxt-delay-hydration and srr, there is a problem during build due to missing chunkErrorEvent

### Logs

```shell-script
ERROR  x Build failed in 30.25s                                                                                                    7:07:38 PM


[7:07:38 PM]  ERROR  Nuxt Build Error: node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_eslint@9.15.0_jiti@2.4.0__ioredis@5.4._loqfqi7ds67v7y4grm4aje4ofi/node_modules/nuxt/dist/app/nuxt.js (4:16): "chunkErrorEvent" is not exported by "virtual:nuxt:/project/.nuxt/nuxt.config.mjs", imported by "node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_eslint@9.15.0_jiti@2.4.0__ioredis@5.4._loqfqi7ds67v7y4grm4aje4ofi/node_modules/nuxt/dist/app/nuxt.js".
file: /project/node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_eslint@9.15.0_jiti@2.4.0__ioredis@5.4._loqfqi7ds67v7y4grm4aje4ofi/node_modules/nuxt/dist/app/nuxt.js:4:16

2: import { createHooks } from "hookable";
3: import { getContext } from "unctx";
4: import { appId, chunkErrorEvent, multiApp } from "#build/nuxt.config.mjs";
                   ^
5: 
6: function getNuxtAppCtx(id = appId || "nuxt-app") {


  file: node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_eslint@9.15.0_jiti@2.4.0__ioredis@5.4._loqfqi7ds67v7y4grm4aje4ofi/node_modules/nuxt/dist/app/nuxt.js:4:16
  
  2: import { createHooks } from "hookable";
  3: import { getContext } from "unctx";
  4: import { appId, chunkErrorEvent, multiApp } from "#build/nuxt.config.mjs";
  ^
  5:
  6: function getNuxtAppCtx(id = appId || "nuxt-app") {
  
  at getRollupError (/projectsnode_modules/rollup/dist/es/shared/parseAst.js:392:41)
  at error (/projectsnode_modules/rollup/dist/es/shared/parseAst.js:388:42)
  at Module.error (/projectsnode_modules/rollup/dist/es/shared/node-entry.js:13967:16)
  at Module.traceVariable (/projectsnode_modules/rollup/dist/es/shared/node-entry.js:14414:29)
  at ModuleScope.findVariable (/projectsnode_modules/rollup/dist/es/shared/node-entry.js:12121:39)
  at FunctionScope.findVariable (/projectsnode_modules/rollup/dist/es/shared/node-entry.js:7467:38)
  at FunctionBodyScope.findVariable (/projectsnode_modules/rollup/dist/es/shared/node-entry.js:7467:38)
  at TrackingScope.findVariable (/projectsnode_modules/rollup/dist/es/shared/node-entry.js:7467:38)
  at BlockScope.findVariable (/projectsnode_modules/rollup/dist/es/shared/node-entry.js:7467:38)
  at Identifier.bind (/projectsnode_modules/rollup/dist/es/shared/node-entry.js:6941:40)
```

**Comment by danielroe** [comment]
This is likely an issue with `nuxt-delay-hydration`. Would you raise an issue there? 🙏
