### ISSUE TITLE
work locally with SERVER_PRESET=koyeb pnpm build, not work on koyeb

### ISSUE THREAD

**Issue by mak7an** [nuxt/nuxt#29989]
### Environment

-

### Reproduction

-

### Describe the bug

✔ Server built in 25ms
[nitro] ✔ Generated public .output/public
[nitro] ℹ Building Nuxt Nitro server (preset: koyeb, compatibility date: 2024-04-03)
[nitro]  ERROR  Error: File /layers/heroku_nodejs-pnpm-install/layers/heroku_nodejs-pnpm-install/virtual/store/h3@1.13.0/node_modules/h3/dist/index.mjs does not exist.
undefined
 ERROR  File /layers/heroku_nodejs-pnpm-install/layers/heroku_nodejs-pnpm-install/virtual/store/h3@1.13.0/node_modules/h3/dist/index.mjs does not exist.
  at Job.emitDependency (/layers/heroku_nodejs-pnpm-install/virtual/store/@vercel+nft@0.27.6/node_modules/@vercel/nft/out/node-file-trace.js:310:23)
  at async Job.maybeEmitDep (/layers/heroku_nodejs-pnpm-install/virtual/store/@vercel+nft@0.27.6/node_modules/@vercel/nft/out/node-file-trace.js:110:17)
  at async Promise.all (index 1)
  at async Job.emitDependency (/layers/heroku_nodejs-pnpm-install/virtual/store/@vercel+nft@0.27.6/node_modules/@vercel/nft/out/node-file-trace.js:321:9)
  at async Promise.all (index 1)
  at async nodeFileTrace (/layers/heroku_nodejs-pnpm-install/virtual/store/@vercel+nft@0.27.6/node_modules/@vercel/nft/out/node-file-trace.js:51:5)
  at async Object.buildEnd (/layers/heroku_nodejs-pnpm-install/virtual/store/nitropack@2.10.4_typescript@5.6.3/node_modules/nitropack/dist/rollup/index.mjs:435:26)
  at async Promise.all (index 0)
  at async PluginDriver.hookParallel (/layers/heroku_nodejs-pnpm-install/virtual/store/rollup@4.27.3/node_modules/rollup/dist/es/shared/node-entry.js:20737:9)
  at async /layers/heroku_nodejs-pnpm-install/virtual/store/rollup@4.27.3/node_modules/rollup/dist/es/shared/node-entry.js:21700:9 
 ERROR  File /layers/heroku_nodejs-pnpm-install/layers/heroku_nodejs-pnpm-install/virtual/store/h3@1.13.0/node_modules/h3/dist/index.mjs does not exist.
 ELIFECYCLE  Command failed with exit code 1.
[Error: heroku/nodejs-pnpm build script error]
There was an error while attempting to run a build script
from this project's package.json. The command exited with a non-zero exit code.
Details: Exit code exit status: 1
Timer: Builder ran for 40.939368851s and ended at 2024-11-19T21:46:03Z
ERROR: failed to build: exit status 1
Build failed ❌

### Logs

```shell-script

```

**Comment by manniL** [comment]
Can you check if you can reproduce this with plain Nitro?

**Comment by mak7an** [comment]
empty nuxt app work

**Comment by mak7an** [comment]
always errors like

```
ould not resolve dependency:
npm ERR! pinia@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.2
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.4.0" from pinia@2.2.6
npm ERR!     node_modules/pinia
npm ERR!       pinia@"*" from the root project

```

**Comment by mak7an** [comment]
```
In that case, add the following to your package.json:


"overrides": {
  "vue": "latest"
}
````


> Invalid comparator: latest



It's a shit

**Comment by mak7an** [comment]
Used some old packages what make problem. After make my copy of it and update dependencies in it all work.
