### ISSUE TITLE
Nuxt is not compatible with new version of TypeScript (5.7.2)

### ISSUE THREAD

**Issue by antoinezanardi** [nuxt/nuxt#30026]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  npm@9.8.1
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Here's a minimal reproduction on CodeSandbox. 

https://codesandbox.io/p/devbox/vitest-coverage-4c4d2w

You just need to run `npx nuxi typecheck` to see encounter the error.

### Describe the bug

After upgrading to the last version of TypeScript (5.7.2), Nuxt is not able to typecheck or build normally. 

### Logs

```shell-script
ℹ Running with compatibility version 4                                                                                           10:24:42 AM

/project/workspace/node_modules/vue-tsc/index.js:34
            throw err;
            ^
Search string not found: "/supportedTSExtensions = .*(?=;)/"
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.9.0

 ERROR  Command failed with exit code 1: /project/workspace/node_modules/vue-tsc/bin/vue-tsc.js --noEmit                          10:24:43 AM

  at getFinalError (node_modules/nuxi/dist/chunks/index3.mjs:1134:9)
  at makeError (node_modules/nuxi/dist/chunks/index3.mjs:3614:16)
  at getAsyncResult (node_modules/nuxi/dist/chunks/index3.mjs:7841:4)
  at handlePromise (node_modules/nuxi/dist/chunks/index3.mjs:7824:17)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.run (node_modules/nuxi/dist/chunks/typecheck.mjs:81:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7)
```

**Comment by cernymatej** [comment]
I'm fairly certain this isn't a Nuxt issue but rather that `vue-tsc` doesn't yet support the latest version of TypeScript.

**Comment by sminnee** [comment]
Here's the bug raised on vue-tsc https://github.com/vuejs/language-tools/issues/5018

**Comment by whitersun** [comment]
I am using vue 3.5 not migrate with nuxt, when I run build with typescript ver ^5.7.2. I got the same too.

**Comment by huang-julien** [comment]
Closing this as this is a vue-tsc issue
