### ISSUE TITLE
Module failed to compile

### ISSUE THREAD

**Issue by casualmatt** [nuxt/nuxt#30094]
### Environment

- Operating System: Linux
- Node Version:     v20.17.0
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.10.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

pnpm dlx nuxi init -t module my-module

or [nuxt-user-country module](https://github.com/JAMflow-Cloud/nuxt-user-country)

### Describe the bug

It's impossible to compile, and not even a clean nuxt module was generated by the starter project. 

### Logs

```shell-script
matteo@dev-container:~/git/jamflow/module$ pnpm prepack

> my-module@1.0.0 prepack /home/dev/git/jamflow/module
> nuxt-module-build build

ℹ Building my-module                                                                                                                                                                  5:11:23 PM
ℹ Cleaning dist directory: ./dist                                                                                                                                                     5:11:23 PM
.nuxt/components.plugin.mjs(3,1): error TS2742: The inferred type of 'default' cannot be named without a reference to '~/node_modules/nuxt/dist/app/nuxt.js'. This is likely not portable. A type annotation is necessary.


 ERROR  Failed to compile. Check the logs above.                                                                                                                                       5:11:25 PM

  at error (node_modules/.pnpm/rollup@3.29.5/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Object.error (node_modules/.pnpm/rollup@3.29.5/node_modules/rollup/dist/es/shared/node-entry.js:25351:20)
  at Object.error (node_modules/.pnpm/rollup@3.29.5/node_modules/rollup/dist/es/shared/node-entry.js:24472:42)
  at generateDtsFromTs (node_modules/.pnpm/rollup-plugin-dts@6.1.1_rollup@3.29.5_typescript@5.7.2/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1834:30)
  at Object.transform (node_modules/.pnpm/rollup-plugin-dts@6.1.1_rollup@3.29.5_typescript@5.7.2/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1843:38)
  at node_modules/.pnpm/rollup@3.29.5/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 



 ERROR  Failed to compile. Check the logs above.                                                                                                                                       5:11:25 PM

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by casualmatt** [comment]
Probably a duplicate of https://github.com/nuxt/module-builder/issues/141
