### ISSUE TITLE
@nuxtjs/seo package not installing

### ISSUE THREAD

**Issue by irm4nt45** [nuxt/nuxt#30092]
### Environment

package.json

  "devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/robots": "^5.0.0",
    "@nuxtjs/seo": "^2.0.2",
    "@types/bootstrap": "^5.2.10",
    "nuxt": "^3.14.1592",
    "vue": "^3.3.12",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "bootstrap": "^5.3.2",
    "nuxt-swiper": "^1.2.2",
    "react-nice-select": "^1.0.6",
    "vue3-circle-progress": "^1.0.7",
    "wow.js": "^1.2.2"
  }

  modules: ['nuxt-swiper', "@nuxtjs/seo"],

### Reproduction

Hello,
Following the Nuxt documentation for implementing technical SEO (https://nuxtseo.com/docs/nuxt-seo/getting-started/installation), unfortunately, the installed package is not read correctly as a module.

### Describe the bug

Logs:

Installing @nuxtjs/seo@2.0.2 development dependency                                                                                                                     6:35:08 PM

up to date, audited 758 packages in 2s

178 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
ℹ Adding @nuxtjs/seo to the modules                                                                                                                                       6:35:10 PM

 ERROR  Nuxt module should be a function: [object Object]                                                                                                                  6:35:12 PM

  at loadNuxtModuleInstance (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/@nuxt/kit/dist/index.mjs:2466:11)
  at async installModule (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async installNuxtSiteConfig (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxt-site-config-kit/dist/index.mjs:71:3)
  at async setup (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/@nuxtjs/robots/dist/module.mjs:271:5)
  at async normalizedModule (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/@nuxt/kit/dist/index.mjs:2397:95)
  at async setup (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/@nuxtjs/seo/dist/module.mjs:21:9)
  at async normalizedModule (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/@nuxt/kit/dist/index.mjs:2397:95)
  at async initNuxt (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxt/dist/index.mjs:4684:5)
  at async loadNuxt (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxt/dist/index.mjs:4854:5)
  at async loadNuxt (/Users/irmantastoleikis/node_modules/@nuxt/kit/dist/index.mjs:2633:19)
  at async Object.run (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxi/dist/chunks/prepare.mjs:61:18)
  at async runCommand$1 (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1648:16)
  at async runCommand (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:2019:10)
  at async Object.setup (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxi/dist/chunks/add2.mjs:197:5)
  at async runCommand$1 (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1620:5)
  at async runCommand$1 (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1639:11)
  at async runCommand$1 (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1639:11)
  at async runMain$1 (/Users/irmantastoleikis/Documents/ambimax-webpage/Ygency/VueJs%20Template/light/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1777:7) 

 ERROR  Nuxt module should be a function: [object Object]  

### Additional context

Any help is supported. Thank you in advance.

### Logs

```shell-script

```

**Comment by danielroe** [comment]
Checking, the reproduction provided doesn't show this issue, which is already resolved in the latest version of nuxt kit. Maybe you have an older one?

See https://stackblitz.com/edit/nuxt-starter-kkvhks which was generated by running `npx nuxi module add @nuxtjs/seo` within the stackblitz link you provided - there are no errors.

I'm going to close this, but please feel free to provide a reproduction and I'll happily reopen it.
