### ISSUE TITLE
No error stack trace outside Nuxt context

### ISSUE THREAD

**Issue by sholohov** [nuxt/nuxt#30102]
### Environment

In version 3.14.1592 there is no error stack trace. In version 3.13 it was still there.

![Image](https://github.com/user-attachments/assets/1e07ccfb-7b11-43bc-89ec-8690bd0bb725)

### Reproduction

1. Expand the project
2. Create a file where to create an error
3. Include the file in app.vue

This is reproduced here https://stackblitz.com/edit/github-cqxzt5?file=test.ts

### Describe the bug

There should be an error message and a stack, but in reality there is only a message.

### Logs

```shell-script
ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'document')

ERROR  [nuxt] [request error] [unhandled] [500] [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables.
```

**Comment by danielroe** [comment]
Would you check if this is reproducible with only a Nitro upgrade? (ie. with your v3.13 project, update nitro to v2.10)

**Comment by sholohov** [comment]
> Would you check if this is reproducible with only a Nitro upgrade? (ie. with your v3.13 project, update nitro to v2.10)

I tried installing nitropack 2.10 on project 3.13 - the stack did not disappear, I also tried installing nitropack 2.9 on project 3.14 - the stack did not appear.

**Comment by sholohov** [comment]
I tried to downgrade the Nitro version via "overrides" in package.json - it worked!

**Comment by sholohov** [comment]
@danielroe Tell me, where is the problem, on the Nuxt or Nitropack side? Is this issue enough or do I need to create another one in the Nitro repository to fix it?

**Comment by danielroe** [comment]
it sounds like a nitro issue, indeed 

see if you can reproduce in pure Nitro ([reproduction sandbox](https://stackblitz.com/github/unjs/nitro/tree/main/examples/hello-world)), and if so, raise [there](https://github.com/unjs/nitro/issues/new/choose).🙏

**Comment by sholohov** [comment]
Everything seems to be ok in Nitro...
![Image](https://github.com/user-attachments/assets/cc4128b9-c079-4319-9ce5-6ddb0829fce3)

**Comment by danielroe** [comment]
cc: @pi0 - this was similar to a consola issue you mentioned - do you have any ideas?

**Comment by sholohov** [comment]
Now it's a dilemma, had to update to the latest version of nitropack due to the websockets update and now the stacktrace issue has come up again. Any news on fixing it?

**Comment by foodticket-developer** [comment]
fyi, i ran into this problem while debugging https://github.com/vuejs/pinia/issues/2872

no trace was present, until I did:

```
    "resolutions": {
        "nitropack": "2.9.7"
    }
```

which allowed me to pinpoint the issue to a Pinia update and find the ticket above

**Comment by sholohov** [comment]
> fyi, i ran into this problem on Nuxt 3.15.1 while debugging [vuejs/pinia#2872](https://github.com/vuejs/pinia/issues/2872)
> 
> no trace was present, until I did:
> 
> ```
>     "resolutions": {
>         "nitropack": "2.9.7"
>     }
> ```
> 
> which allowed me to pinpoint the issue to a Pinia update and find the ticket above

This was written above and it is not a panacea, because the new version of nitropack has the updates I need. It is strange that this problem is not solved, because stacktrace is an important tool in debugging

**Comment by danielroe** [comment]
As is solely attributable to the `nitropack` version change, ideally we should reproduce and raise there as it's likely an issue that needs to be solved there.

**Comment by sholohov** [comment]
@danielroe I couldn't reproduce this bug in the `nitorpack`. Could there be a problem in some layer between `nuxt` and `ntropack`?

**Comment by danielroe** [comment]
It might be caused by the fact that `nuxi` forks the dev server process - you can try with `nuxi dev --no-fork` to see if that makes a difference.

**Comment by sholohov** [comment]
> It might be caused by the fact that `nuxi` forks the dev server process - you can try with `nuxi dev --no-fork` to see if that makes a difference.

Nothing has changed, the error stack has not appeared. Maybe there are ideas on how to return it without downgrading the nitropack version?

**Comment by CorrM** [comment]
Same problem
```
 ERROR  [nuxt] [request error] [unhandled] [500] Trying to join 'claim.walletData.wallet.deposits', but 'walletData.wallet.deposits' is not a defined relation on RewardClaimEntity2.
```

**Comment by darklow** [comment]
As a workaround I solved this issue by adding following code to `server/plugins/extend-html.js` file:
```js
export default defineNitroPlugin((nitroApp) => {
  // Since nuxt upgrade stack trace was missing and this helps to get it back
  nitroApp.hooks.hook('error', async (error, { event }) => {
    console.error(`${event?.path} Application error:`, error)
  })
})
```

**Comment by snickell** [comment]
Here's an interesting question: is anyone SEEING server side stack traces in recent nuxt?

**Comment by snickell** [comment]
>     "resolutions": {
>        "nitropack": "2.9.7"
>    }

This works, and to be explicit the next version of nitropack doesn't work (2.10.0).

Here's a [GitHub diff between nitro v2.9.7 and v.2.10.0](https://github.com/nitrojs/nitro/compare/v2.9.7...v2.10.0)

**Comment by snickell** [comment]
Basing off nitro at tag v2.10.0, I've modified normalizeError to log as follows:
```
  console.log(`calling normalizeError: isDev: ${isDev}, Import.meta.prerender: ${import.meta.prerender}, error.unhandled: ${error.unhandled}, error.fatal: ${error.fatal}`);
  console.log(`!isDev && !import.meta.prerender && (error.unhandled || error.fatal) => ${!isDev && !import.meta.prerender && (error.unhandled || error.fatal)}`);

  const stack =
    !isDev && !import.meta.prerender && (error.unhandled || error.fatal)
      ? []
      : ((error.stack as string) || "")
```

Which produces:
```
calling normalizeError: isDev: undefined, Import.meta.prerender: false, error.unhandled: true, error.fatal: false
!isDev && !false && (error.unhandled || error.fatal) => true
```

In other words: it short circuits computing the stack in normalizeError:
- !isDev => true
- !import.meta.prerender => true
- error.unhandled =>

I'm not sure what this is trying to do, but ALL of those seem off to me, almost reversed conditionals.

**Comment by snickell** [comment]
CONFIRMED: if I modify nitropack 1.10.0 to short-circuit the new conditional in normalizeError() ([location in HEAD](https://github.com/nitrojs/nitro/blob/e8d609908e9758094d3639b83fe2956ddf872fa8/src/runtime/internal/error/utils.ts#L39), [location in 1.10.0](https://github.com/nitrojs/nitro/blob/4081e636d3b9de4577107054ffc16c3a225045e9/src/runtime/internal/utils.ts#L64), [location in 1.9.7, no conditional=works!](https://github.com/nitrojs/nitro/blob/46b5a05f7dbfd8a8f6b8673cb934ed7c314bab33/src/runtime/utils.ts#L61), nuxt prints stack traces again:
```
  const stack =
    //!isDev && !import.meta.prerender && (error.unhandled || error.fatal)
    false
```
=>

```
 ERROR  [nuxt] [request error] [unhandled] [500] throwing my special error
  at Object.handler (./server/api/my-error.get.js:2:1)  
  at Object.handler (./node_modules/.pnpm/h3@1.15.1/node_modules/h3/dist/index.mjs:1935:24)  
  at Object.handler (./node_modules/.pnpm/h3@1.15.1/node_modules/h3/dist/index.mjs:2248:34)  
  at ./node_modules/.pnpm/h3@1.15.1/node_modules/h3/dist/index.mjs:2009:31  
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)  
  at async Object.callAsync (./node_modules/.pnpm/unctx@2.4.1/node_modules/unctx/dist/index.mjs:72:16)  
  at async Object.callAsync (./node_modules/.pnpm/unctx@2.4.1/node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.15.1/node_modules/h3/dist/index.mjs:2301:7)
```

**Comment by snickell** [comment]
I believe this is the first / underlying PR that broke nuxt: [fix: hide unhandled error messages in prod](https://github.com/nitrojs/nitro/pull/2591). Perhaps @pi0 can comment on whether this is intended behavior, and suggest what nuxt should be doing different?

I think disabling printing to the server log of stack traces is not a good behavior, even in prod, but not including them in HTML returned to the client is probably a good prod default.

**Comment by snickell** [comment]
I _suspect_, although have not tested, that this is fixed in nuxt HEAD, which uses its own copy of normalizeErrors ([github](https://github.com/nuxt/nuxt/blob/ed22319cd0e3a11e5bb6c9491fcf067ce8f984c3/packages/nuxt/src/core/runtime/nitro/handlers/error.ts#L114).

However, it seems the 3.15.x branch uses nitro's normalizeErrors, which no longer match it ([github](https://github.com/nuxt/nuxt/blob/244da170dd61e9aa790d5e9fdf988aa0a128d55a/packages/nuxt/src/core/runtime/nitro/error.ts/#L10-L11). If a 4.x release is not imminent, perhaps fixing stack traces in 3.15.x is worth backporting a fix for?

**Comment by 749** [comment]
Was this ever fixed for the 3.X branch?
