### ISSUE TITLE
`npx nuxi@latest` won't serve after install

### ISSUE THREAD

**Issue by davestewart** [nuxt/nuxt#30127]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.15.1`
- Nuxt Version:     `3.14.1592`
- CLI Version:      `3.16.0`
- Nitro Version:    `2.10.4`
- Package Manager:  `npm@10.7.0`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Ran this:

```bash
npx nuxi@latest init my-project
```

### Describe the bug

Got this:

```bash
Need to install the following packages:
nuxi@3.16.0
Ok to proceed? (y) 


✔ Which package manager would you like to use?
npm
◐ Installing dependencies...                                                                  09:10:03
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@3.0.2: This package is no longer supported.

> postinstall
> nuxt prepare

✔ Types generated in .nuxt                                                                   09:10:30

added 659 packages, and audited 661 packages in 27s

130 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
✔ Installation completed.                                                                    09:10:31

✔ Initialize git repository?
Yes
ℹ Initializing git repository...                                                             09:10:42

Initialized empty Git repository in /Volumes/Data/Work/Projects/ControlSpace/5_development/repos/other/my-project/.git/
                                                                                              09:10:42
✨ Nuxt project has been created with the v3 template. Next steps:
 › cd my-project                                                                              09:10:42
 › Start development server with npm run dev                                                  09:10:42
npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.9.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.1
npm notice To update run: npm install -g npm@10.9.1
npm notice
dave@ds-m3 other % cd my-project 
dave@ds-m3 my-project % npm i
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: vite-plugin-inspect@0.8.8
npm warn Found: vite@6.0.2
npm warn node_modules/vite
npm warn   peer vite@"*" from @nuxt/devtools@1.6.2
npm warn   node_modules/@nuxt/devtools
npm warn     @nuxt/devtools@"^1.6.0" from nuxt@3.14.1592
npm warn     node_modules/nuxt
npm warn   6 more (@nuxt/devtools-kit, @vitejs/plugin-vue, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer vite@"^3.1.0 || ^4.0.0 || ^5.0.0-0" from vite-plugin-inspect-legacy@0.8.8
npm warn node_modules/@nuxt/devtools/node_modules/vite-plugin-inspect-legacy
npm warn   vite-plugin-inspect-legacy@"npm:vite-plugin-inspect@0.8.8" from @nuxt/devtools@1.6.2
npm warn   node_modules/@nuxt/devtools
npm warn
npm warn Conflicting peer dependency: vite@5.4.11
npm warn node_modules/vite
npm warn   peer vite@"^3.1.0 || ^4.0.0 || ^5.0.0-0" from vite-plugin-inspect-legacy@0.8.8
npm warn   node_modules/@nuxt/devtools/node_modules/vite-plugin-inspect-legacy
npm warn     vite-plugin-inspect-legacy@"npm:vite-plugin-inspect@0.8.8" from @nuxt/devtools@1.6.2
npm warn     node_modules/@nuxt/devtools
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: vite-plugin-vue-inspector@5.1.3
npm warn Found: vite@6.0.2
npm warn node_modules/vite
npm warn   peer vite@"*" from @nuxt/devtools@1.6.2
npm warn   node_modules/@nuxt/devtools
npm warn     @nuxt/devtools@"^1.6.0" from nuxt@3.14.1592
npm warn     node_modules/nuxt
npm warn   6 more (@nuxt/devtools-kit, @vitejs/plugin-vue, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer vite@"^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0" from vite-plugin-vue-inspector@5.1.3
npm warn node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector
npm warn   vite-plugin-vue-inspector@"5.1.3" from @nuxt/devtools@1.6.2
npm warn   node_modules/@nuxt/devtools
npm warn
npm warn Conflicting peer dependency: vite@5.4.11
npm warn node_modules/vite
npm warn   peer vite@"^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0" from vite-plugin-vue-inspector@5.1.3
npm warn   node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector
npm warn     vite-plugin-vue-inspector@"5.1.3" from @nuxt/devtools@1.6.2
npm warn     node_modules/@nuxt/devtools

> postinstall
> nuxt prepare

✔ Types generated in .nuxt                                                                   09:10:52

added 1 package, and audited 662 packages in 2s

130 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
dave@ds-m3 my-project % npm run dev

> dev
> nuxt dev

Nuxt 3.14.1592 with Nitro 2.10.4                                                              09:11:07
                                                                                              09:11:07
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Option + D in the browser (v1.6.2)                                09:11:08


 ERROR  Cannot start nuxt:  Cannot convert undefined or null to object                        09:11:09

  at Function.values (<anonymous>)
  at configureServer (node_modules/vite-plugin-inspect/dist/index.mjs:1410:12)
  at configureServer (node_modules/vite-plugin-inspect/dist/index.mjs:1496:19)
  at _createServer (node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:63080:26)
  at async buildClient (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.B69gK6ir.mjs:733:24)
  at async withLogs (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.B69gK6ir.mjs:1781:3)
  at async bundle (node_modules/@nuxt/vite-builder/dist/shared/vite-builder.B69gK6ir.mjs:1772:3)
  at async bundle (node_modules/nuxt/dist/index.mjs:6091:5)
  at async build (node_modules/nuxt/dist/index.mjs:5966:3)
  at async Promise.all (index 1)
```

### Logs

```shell-script

```

**Comment by DT-Zilo** [comment]
same issue

**Comment by admench** [comment]
Same here

**Comment by admench** [comment]
I have tried using `npm`, `pnpm`, `node 18`, `node 22`. I follow docs exactly.

```
$ npx nuxi@latest init <project-name>
$ cd into project
$ npm run dev -- -o
```

Same as Dave explains above.

**Comment by antoineabbou** [comment]
same issue here : 

node v22.11.0 
nuxt v3.14.1592

**Comment by wenyanlin** [comment]
I just encountered this issue as well. It might be related to the devtools. You can try disabling it for now.

`devtools: { 
    enabled: false,
}`

**Comment by admench** [comment]
> Same here, a workaround is to install Vite 5.4.11

This works for me!

```
# after initial nuxt init
$ npm i -D vite@5.4.11
```

**Comment by danielroe** [comment]
Managed to reproduce and it's caused by vite v6 being installed - it reproduces on npm only (not pnpm) because vite-plugin-inspect now has a peer dep on vite v6.

cc: @antfu

**Comment by horvbalint** [comment]
> Managed to reproduce by running with `npm` and it's caused by vite v6 being installed (with `@nuxt/devtools` v1.6.2 and `vite-plugin-inspect` v0.10.3) - it reproduces on npm only (not pnpm) because vite-plugin-inspect now has a peer dep on vite v6.
> 
> related issues:
> 
> * [feat: support `vite-plugin-inspect` for both Vite 5 and 6 devtools#757](https://github.com/nuxt/devtools/pull/757)
> * [feat!: support Vite 6 antfu-collective/vite-plugin-inspect#113](https://github.com/antfu-collective/vite-plugin-inspect/pull/113)
> 
> cc: [@antfu](https://github.com/antfu)

We have the same issue *with* pnpm, but only in one of our projects, so I don't have a reproduction ready :/

**Comment by davestewart** [comment]
> What version of vite, @nuxt/devtools, and vite-plugin-inspect do you have installed?

```
dave@ds-m3 my-project % npm ls @nuxt/devtools vite vite-plugin-inspect
npm error code ELSPROBLEMS
npm error invalid: vite@6.0.2 /Volumes/Data/Work/Projects/ControlSpace/5_development/repos/other/my-project/node_modules/vite
nuxt-app@ /Volumes/Data/Work/Projects/ControlSpace/5_development/repos/other/my-project
└─┬ nuxt@3.14.1592
  ├─┬ @nuxt/devtools@1.6.2
  │ ├─┬ @nuxt/devtools-kit@1.6.2
  │ │ └── vite@6.0.2 deduped
  │ ├─┬ @vue/devtools-core@7.6.4
  │ │ └─┬ vite-hot-client@0.2.4
  │ │   └── vite@6.0.2 deduped invalid: "^3.1.0 || ^4.0.0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-inspect-legacy, "^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector
  │ ├─┬ vite-plugin-inspect-legacy@npm:vite-plugin-inspect@0.8.8
  │ │ └── vite@6.0.2 deduped invalid: "^3.1.0 || ^4.0.0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-inspect-legacy
  │ ├─┬ vite-plugin-inspect@0.10.3
  │ │ └── vite@6.0.2 deduped invalid: "^3.1.0 || ^4.0.0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-inspect-legacy
  │ ├─┬ vite-plugin-vue-inspector@5.1.3
  │ │ └── vite@6.0.2 deduped invalid: "^3.1.0 || ^4.0.0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-inspect-legacy, "^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector
  │ └── vite@6.0.2 invalid: "^3.1.0 || ^4.0.0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-inspect-legacy, "^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector
  └─┬ @nuxt/vite-builder@3.14.1592
    ├─┬ @vitejs/plugin-vue-jsx@4.1.1
    │ └── vite@6.0.2 deduped invalid: "^3.1.0 || ^4.0.0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-inspect-legacy, "^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector
    ├─┬ @vitejs/plugin-vue@5.2.1
    │ └── vite@6.0.2 deduped invalid: "^3.1.0 || ^4.0.0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-inspect-legacy, "^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector
    ├─┬ vite-node@2.1.8
    │ └── vite@5.4.11
    ├─┬ vite-plugin-checker@0.8.0
    │ └── vite@6.0.2 deduped invalid: "^3.1.0 || ^4.0.0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-inspect-legacy, "^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0" from node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector
    └── vite@5.4.11
```

**Comment by klienjoy** [comment]
I can also confirm `devtools: {  enabled: false, }` solved it

**Comment by antfu** [comment]
Sorry it was my bad. I was trying to figure out a way to have Nuxt DevTools support Vite 5 and 6 seamlessly for future updates, but I wasn't considering well about this case of introducing Vite 6 as peer dep. Reverting the changes, and releasing Nuxt DevTools `v1.6.2` which should fix this.

**Comment by furbierecordsDev** [comment]
> I just encountered this issue as well. It might be related to the devtools. You can try disabling it for now.
> 
> `devtools: { enabled: false, }`

It's worked for me.
