### ISSUE TITLE
Built-in typechecking fails on `nuxt@3.14.1592`

### ISSUE THREAD

**Issue by amostergaard** [nuxt/nuxt#30154]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-qagkk8

### Describe the bug

Hello, 

I'm running into an issue where typechecking is no longer working in `nuxt@3.14.1592`. 

To reproduce the issue: 

1. In the minimal reproduction stackblitz, open the the terminal 
2. Execute `npm install` (to trigger `nuxt prepare`) 
3. Run the command `npm run check-types` (which is just a wrapper for `nuxt typecheck`) 

**Result**: The built-in Nuxt 3 typechecking functionality is broken. When the command from (3) is run, an error is thrown that the search string `"/supportedTSExtensions = .*(?=;)/"` is not found. 

**Desired behaviour**: I'd like to fix the issue so that typechecking works again. We use this in CI, and it's an important alarm bell for us. 

### Logs

```shell-script
'Search string not found: "/supportedTSExtensions = .*(?=;)/"'

 ERROR  Command failed with exit code 1: npx -p vue-tsc -p typescript vue-tsc --noEmit      11:35:21 AM

  at new ExecaError (/home/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index3.mjs:1188:1)
  at getFinalError (/home/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index3.mjs:1158:9)
  at makeError (/home/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index3.mjs:3638:16)
  at getAsyncResult (/home/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index3.mjs:7867:4)
  at handlePromise (/home/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/index3.mjs:7850:17)
  at async Object.run (/home/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/chunks/typecheck.mjs:112:9)
  at async runCommand$1 (/home/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1679:16)
  at async runCommand$1 (/home/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1670:11)
  at async runMain$1 (/home/.npm/_npx/b95349761371180e/node_modules/nuxi/dist/shared/nuxi.f8a4d1b7.mjs:1808:7)
```

**Comment by huang-julien** [comment]
Hello, as @rylanharper mentionned, this is indeed an upstream issue :+1:
