### ISSUE TITLE
Using useSeoMeta in middleware throws internal error

### ISSUE THREAD

**Issue by tratteo** [nuxt/nuxt#30231]
### Environment

```
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.14.1592
- CLI Version:      3.16.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-ksd6ujrj?file=middleware%2Ftest.global.ts

### Describe the bug

I am trying to create a middleware that enables me to automatically map routes to SEO meta and have the middleware setup the actual data automatically. On startup of the dev server and also on page reload, the following error is thrown (seems coming from internal nuxt and `unhead` plugin):
```
ERROR  [nitro] [uncaughtException] [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables.

  at Module.useNuxtApp (node_modules/nuxt/dist/app/nuxt.js:251:13)
  at eval (node_modules/nuxt/dist/head/runtime/plugins/unhead.js:18:35)
  at Module.injectHead (node_modules/@unhead/vue/dist/shared/vue.f49591ad.mjs:76:30)
  at Module.useHead (node_modules/@unhead/vue/dist/shared/vue.8fc199ce.mjs:7:54)
  at Module.useSeoMeta (node_modules/@unhead/vue/dist/index.mjs:101:32)
  at Timeout.eval (middleware/test.global.ts:11:29)
  at <anonymous> (node:internal/timers:246:4692)
```

### Additional context

ℹ Compiled plugins.server.mjs in 641.37ms                                                                                                                   22:36:25
ℹ Compiled plugins.client.mjs in 659.84ms                                                                                                                   22:36:25
ℹ Compiled types/plugins.d.ts in 675.57ms                                                                                                                   22:36:25
✔ Vite client built in 465ms                                                                                                                                22:36:26
✔ Vite server built in 1274ms                                                                                                                               22:36:28
✔ Nuxt Nitro server built in 1767 ms                                                                                                                  nitro 22:36:30
ℹ Vite client warmed up in 1ms                                                                                                                              22:36:30
ℹ Vite server warmed up in 1217ms                                                                                                                           22:36:31
setting meta tags in middleware

 ERROR  [nitro] [uncaughtException] [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables.

  at Module.useNuxtApp (node_modules/nuxt/dist/app/nuxt.js:251:13)
  at eval (node_modules/nuxt/dist/head/runtime/plugins/unhead.js:18:35)
  at Module.injectHead (node_modules/@unhead/vue/dist/shared/vue.f49591ad.mjs:76:30)
  at Module.useHead (node_modules/@unhead/vue/dist/shared/vue.8fc199ce.mjs:7:54)
  at Module.useSeoMeta (node_modules/@unhead/vue/dist/index.mjs:101:32)
  at Timeout.eval (middleware/test.global.ts:11:29)
  at <anonymous> (node:internal/timers:246:4692)

### Logs

```shell-script

```

**Comment by tratteo** [comment]
I found that the problem is the `nextTick` and `setTimeout` function calls inside the middleware. Closing for now sorry for inconvenience.
