### ISSUE TITLE
WARN  'manifest-route-rule' middleware already exists  when copy paste some files (in this case pages)

### ISSUE THREAD

**Issue by Makkalay** [nuxt/nuxt#30267]
### Environment

Nuxt 3

### Reproduction

 WARN  'manifest-route-rule' middleware already exists at '/nuxt/node_modules/nuxt/dist/app/middleware/manifest-route-rule.js'. You can set override: true to replace it.

### Describe the bug

 WARN  'manifest-route-rule' middleware already exists at '/nuxt/node_modules/nuxt/dist/app/middleware/manifest-route-rule.js'. You can set override: true to replace it.

### Logs

```shell-script

```

**Comment by ThomasBerne** [comment]
i get the same error each time I update my code frontend code 
![Image](https://github.com/user-attachments/assets/cb74c870-3e16-4a16-9ac1-9073c0b16939)

**Comment by luger95** [comment]
Hi,

I have the same warning. In addition, the page reloads slowly.

**Comment by SwartZCoding** [comment]
Same issue here. But only for manifest-route-rule

**Comment by Emili-HD** [comment]
Same warn or manifest-route-rule in multiple projects

**Comment by infinity899** [comment]
<img width="553" alt="Image" src="https://github.com/user-attachments/assets/07a6a3a5-3e1f-496a-bcb9-b1094ce5a538" />

**Comment by remihuigen** [comment]
Same. But i'm also encountering the warning for any middleware I've added  with `addRouteMiddleware` from nuxt/kit, for example in modules.

Local middleware in the ./middleware folder does not give a warning


```
// example usage in module
addRouteMiddleware({
  name: 'auth-token',
  path: resolve('./runtime/auth-token'),
  global: true
})
```

Seems to me like these result from the same underlying issue


![Image](https://github.com/user-attachments/assets/1cbd5974-37a5-4137-a042-b8a13c8ff26c)

**Comment by Xaypanya** [comment]
same here 

<img width="535" alt="Image" src="https://github.com/user-attachments/assets/0c190639-0b65-4a7d-a585-39758c1805a8" />

**Comment by egstad** [comment]
+1

**Comment by MhandsomeM** [comment]
+1

**Comment by ludo427** [comment]
+1 any infos on this ?

**Comment by danielroe** [comment]
as I observed above, you can safely ignore, but we're aware that this happens, so no need to add `+1` or equivalent.

does anyone have a reproduction or a way to reproduce this reliably?

**Comment by afflexux** [comment]
> does anyone have a reproduction or a way to reproduce this reliably?

Creating a new post in the content directory whilst the server is running always kicks this error out for me.

I think even saving changes in existing md files does it, but I can't check right now.

**Comment by atonemi** [comment]
> You can ignore this warning but we should certainly look at resolving it.

But，This warning is honestly quite annoying

**Comment by 2DevRuiz** [comment]
Is there a solution?

**Comment by avinmaster** [comment]
So, it's fixed? In which version? v3.17.5?

**Comment by lukasborawski** [comment]
It's not fixed yet, still have it in 3.18 and 4.x. Let's wait. 🤞🏻

**Comment by ciabaros** [comment]
I first noticed this bug when I installed my project from scratch on a new PC. In development mode, it makes [re]loading the page take like 30 seconds with hundreds of these warnings in the console. Anyone know of a temporary workaround of some kind?

Also, it seems to happen when I modify index.vue pages in the Nuxt page folder structure. On a PC where it wasn't happening, I made some index changes, this issue started, and then even when I reverted changes, the problem did not go away, so I believe it has something to do with temp data written by Nuxt (e.g. during build/update?)

**Comment by sugoidesune** [comment]
Fresh nuxt 4 project, and it appears on simple html updates.
But it breaks the server and the page doesn't update and a restart is necessary.
It appears along this message:
```
Failed to parse static properties from plugin node_modules/nuxt/dist/pages/runtime/plugins/prerender.server. ENOENT: no such file or directory, open 'C:\Users\user\code\project\node_modules\nuxt\dist\pages\runtime\plugins\prerender.server'

    at async open (node:internal/fs/promises:640:25)
    at async Object.readFile (node:internal/fs/promises:1277:14)
    at async annotatePlugins (/C:/Users/user/code/project/node_modules/nuxt/dist/index.mjs:6773:68)
    at async Object.getContents (/C:/Users/user/code/project/node_modules/nuxt/dist/index.mjs:6086:26)
    at async processTemplate (/C:/Users/user/code/project/node_modules/nuxt/dist/index.mjs:6625:22)
    at async Promise.allSettled (index 1)
    at async generateApp (/C:/Users/user/code/project/node_modules/nuxt/dist/index.mjs:6651:3)
    at async _applyPromised (/C:/Users/user/code/project/node_modules/perfect-debounce/dist/index.mjs:54:10)
````

**Comment by danielroe** [comment]
@sugoidesune your issue is unrelated. please open a separate issue with a reproduction, please 🙏 

this issue is _purely_ an annoyance (e.g. superfluous console logs), and does not cause any negative consequences or bugs.
