### ISSUE TITLE
Nuxt 2.15.8 (as well as 2.18.1) can't be installed on AMD platforms

### ISSUE THREAD

**Issue by rraagghhu** [nuxt/nuxt#30287]
### Environment

Platform: AMD
Infra: AWS EC2 - India
Node Version: 16.20.2
Yarn Version: 1.22.21

### Reproduction

Run `yarn add nuxt@2.18.1` in AMD machines

### Describe the bug

Nuxt 2 internally uses buffer-xor@1.0.3 which is not getting resolved through npm or yarn. 

yarn add v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
error Error: https://registry.yarnpkg.com/buffer-xor/-/buffer-xor-1.0.3.tgz: Request failed "304 Not Modified"
at ResponseError.ExtendableBuiltin (/home/ec2-user/.nvm/versions/node/v16.20.2/lib/node_modules/yarn/lib/cli.js:696:66)
at new ResponseError (/home/ec2-user/.nvm/versions/node/v16.20.2/lib/node_modules/yarn/lib/cli.js:802:124)
at Request. (/home/ec2-user/.nvm/versions/node/v16.20.2/lib/node_modules/yarn/lib/cli.js:66750:16)
at Request.emit (node:events:513:28)
at Request.module.exports.Request.onRequestResponse (/home/ec2-user/.nvm/versions/node/v16.20.2/lib/node_modules/yarn/lib/cli.js:142287:10)
at ClientRequest.emit (node:events:513:28)
at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
at TLSSocket.socketOnData (node:_http_client:534:22)
at TLSSocket.emit (node:events:513:28)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### Logs

```shell-script

```

**Comment by rraagghhu** [comment]
Seems like the issue from instances from Mumbai region: https://github.com/yarnpkg/yarn/issues/9118
