### ISSUE TITLE
`npx nuxi module add` Fails: `Invalid Module Name Error for “..mjs”`

### ISSUE THREAD

**Issue by 0youri** [nuxt/nuxt#30304]
### Environment

- Operating System: Darwin
- Node Version:     v20.18.1
- Nuxt Version:     3.14.1592
- CLI Version:      3.17.0
- Nitro Version:    2.10.4
- Package Manager:  npm@10.8.2
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

/

### Describe the bug

When using npx nuxi module add to install any module in a Nuxt 3 project, the installation fails with the error:
`[ERROR] Invalid module "..mjs" is not a valid package name imported.`

This issue occurs on a fresh Nuxt project, created using the command `npx nuxi@latest init frontend`. The error happens immediately when running npx nuxi module add without any modifications to the project. This prevents the successful installation and integration of new modules (tried for tailwind, pinia, icon ...).

### Logs

```shell-script

```

**Comment by agenordebriat** [comment]
Occurs since this morning on every module addition. See https://github.com/nuxt/ui/issues/2935.
Everything was fine yesterday. 🫣

**Comment by MontanaDavid** [comment]
Same here (both nuxt UI and tailwind) :
![Image](https://github.com/user-attachments/assets/d9922d6f-3bd1-42af-a333-997f8ccad4d3) ...

**Comment by OpenTextASOWSM** [comment]
I get errors when trying to resolve this package

 ERROR  Invalid module "..mjs" is not a valid package name imported from \Project-Dir\nuxtui-2\nuxtui                           

  at new NodeError (/project-dir/nuxtui-2/nuxtui/node_modules/nuxi/dist/shared/nuxi.BLjynjc6.mjs:6505:5)
  at parsePackageName (/project-dir/nuxtui-2/nuxtui/node_modules/nuxi/dist/shared/nuxi.BLjynjc6.mjs:7876:11)
  at packageResolve (/project-dir/nuxtui-2/nuxtui/node_modules/nuxi/dist/shared/nuxi.BLjynjc6.mjs:7900:51)
  at moduleResolve (/project-dir/nuxtui-2/nuxtui/node_modules/nuxi/dist/shared/nuxi.BLjynjc6.mjs:8046:18)
  at _tryModuleResolve (/project-dir/nuxtui-2/nuxtui/node_modules/nuxi/dist/shared/nuxi.BLjynjc6.mjs:8091:12)
  at _resolve (/project-dir/nuxtui-2/nuxtui/node_modules/nuxi/dist/shared/nuxi.BLjynjc6.mjs:8152:20)
  at resolveSync (/project-dir/nuxtui-2/nuxtui/node_modules/nuxi/dist/shared/nuxi.BLjynjc6.mjs:8179:10)
  at resolvePathSync (/project-dir/nuxtui-2/nuxtui/node_modules/nuxi/dist/shared/nuxi.BLjynjc6.mjs:8182:24)
  at resolvePath (/project-dir/nuxtui-2/nuxtui/node_modules/nuxi/dist/shared/nuxi.BLjynjc6.mjs:8186:28)
  at resolvePackageJSON (/project-dir/nuxtui-2/nuxtui/node_modules/nuxi/dist/shared/nuxi.a6bzaP2S.mjs:85:52)

**Comment by prg-hussam** [comment]
same here

**Comment by jayjake0** [comment]
and same here ;) 

 ERROR  Invalid module "..mjs" is not a valid package name imported from /home/...
