### ISSUE TITLE
Nuxt module should be a function @nuxt/devtools

### ISSUE THREAD

**Issue by howbizarre** [nuxt/nuxt#30329]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.18.1
- Nuxt Version:     3.14.1592
- CLI Version:      3.17.1
- Nitro Version:    2.10.4
- Package Manager:  npm@11.0.0
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

When I tried to start a new project, I received an error:

D:\Kosta\Dev\NUXT>npx nuxi@latest init nxt-est
Need to install the following packages:
nuxi@3.17.1
Ok to proceed? (y)

√ Which package manager would you like to use?
npm
o Installing dependencies...                                                                               14:16:49 ч.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

> postinstall
> nuxt prepare

[14:18:17 ч.]  ERROR  Nuxt module should be a function: C:/Users/howbi/AppData/Roaming/npm/node_modules/@nuxt/devtools/module.cjs

  at loadNuxtModuleInstance (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/@nuxt/kit/dist/index.mjs:2466:11)
  at async installModule (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxt/dist/index.mjs:4684:5)
  at async loadNuxt (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxt/dist/index.mjs:4854:5)
  at async loadNuxt (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/@nuxt/kit/dist/index.mjs:2633:19)
  at async Object.run (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/chunks/prepare.mjs:60:18)
  at async runCommand$1 (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1643:16)
  at async runCommand$1 (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1634:11)
  at async runMain$1 (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1772:7)

[14:18:17 ч.]  ERROR  Nuxt module should be a function: C:/Users/howbi/AppData/Roaming/npm/node_modules/@nuxt/devtools/module.cjs

npm error code 1
npm error path D:\Kosta\Dev\NUXT\nxt-est
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c nuxt prepare
npm error A complete log of this run can be found in: C:\Users\howbi\AppData\Local\npm-cache\_logs\2024-12-22T12_16_49_769Z-debug-0.log
√ Installation completed.                                                                                  14:18:17 ч.

√ Initialize git repository?
No
                                                                                                           14:18:33 ч.
✨ Nuxt project has been created with the v3 template. Next steps:
 › cd nxt-est                                                                                              14:18:33 ч.
 › Start development server with npm run dev                                                               14:18:33 ч.

D:\Kosta\Dev\NUXT>cd nxt-est

D:\Kosta\Dev\NUXT\nxt-est>npm run dev

> dev
> nuxt dev

Nuxt 3.14.1592 with Nitro 2.10.4                                                                           14:18:46 ч.
                                                                                                           14:18:46 ч.
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

[14:18:49 ч.]  ERROR  Cannot start nuxt:  Nuxt module should be a function: C:/Users/howbi/AppData/Roaming/npm/node_modules/@nuxt/devtools/module.cjs

  at loadNuxtModuleInstance (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/@nuxt/kit/dist/index.mjs:2466:11)
  at async installModule (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxt/dist/index.mjs:4684:5)
  at async NuxtDevServer._load (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/chunks/dev2.mjs:1890:5)
  at async NuxtDevServer.load (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/chunks/dev2.mjs:1824:7)
  at async NuxtDevServer.init (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/chunks/dev2.mjs:1819:5)
  at async Object.run (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/chunks/dev-child.mjs:110:5)
  at async runCommand$1 (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1643:16)
  at async runCommand$1 (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1634:11)
  at async runMain$1 (/D:/Kosta/Dev/NUXT/nxt-est/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1772:7)

### Describe the bug

Nuxt cannot start and returns an error.

### Logs

```shell-script
5005 error code 1
5006 error path D:\Kosta\Dev\NUXT\nxt-est
5007 error command failed
5008 error command C:\WINDOWS\system32\cmd.exe /d /s /c nuxt prepare
5009 verbose cwd D:\Kosta\Dev\NUXT\nxt-est
5010 verbose os Windows_NT 10.0.22631
5011 verbose node v20.18.1
5012 verbose npm  v11.0.0
5013 verbose exit 1
5014 verbose code 1
5015 error A complete log of this run can be found in: C:\Users\howbi\AppData\Local\npm-cache\_logs\2024-12-22T12_16_49_769Z-debug-0.log
```

**Comment by howbizarre** [comment]
All the local projects, that I am working on are OK, but when I get one from GitHub and tried to install receive this error:

D:\Kosta\Dev\NUXT\psn-galleries>pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +897
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 897, reused 897, downloaded 0, added 897, done

dependencies:
+ firebase 11.1.0
+ firebase-admin 13.0.2
+ firebase-functions 6.2.0

devDependencies:
+ @nuxt/devtools 1.6.4
+ @nuxt/ui 2.20.0
+ nuxt 3.14.1592
+ vue 3.5.13

> psn-galleries@14.4.71 postinstall D:\Kosta\Dev\NUXT\psn-galleries
> nuxt prepare

i Using default Tailwind CSS file                                                         nuxt:tailwindcss 14:53:41 ч.

[14:53:42 ч.]  ERROR  Nuxt module should be a function: C:/Users/howbi/AppData/Roaming/npm/node_modules/@nuxt/devtools/module.cjs

  at loadNuxtModuleInstance (/D:/Kosta/Dev/NUXT/psn-galleries/node_modules/.pnpm/@nuxt+kit@3.14.1592_magicast@0.3.5_rollup@4.28.1/node_modules/@nuxt/kit/dist/index.mjs:2466:11)
  at async installModule (/D:/Kosta/Dev/NUXT/psn-galleries/node_modules/.pnpm/@nuxt+kit@3.14.1592_magicast@0.3.5_rollup@4.28.1/node_modules/@nuxt/kit/dist/index.mjs:2389:47)
  at async initNuxt (/D:/Kosta/Dev/NUXT/psn-galleries/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_db0@0.2.1_ioredis@5.4.1_magicast@0.3_jh7htkien6eyvbl46okhyqae5q/node_modules/nuxt/dist/index.mjs:4684:5)
  at async loadNuxt (/D:/Kosta/Dev/NUXT/psn-galleries/node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.10.2_db0@0.2.1_ioredis@5.4.1_magicast@0.3_jh7htkien6eyvbl46okhyqae5q/node_modules/nuxt/dist/index.mjs:4854:5)
  at async loadNuxt (/D:/Kosta/Dev/NUXT/psn-galleries/node_modules/.pnpm/@nuxt+kit@3.14.1592_magicast@0.3.5_rollup@4.28.1/node_modules/@nuxt/kit/dist/index.mjs:2633:19)
  at async Object.run (/D:/Kosta/Dev/NUXT/psn-galleries/node_modules/.pnpm/nuxi@3.17.1/node_modules/nuxi/dist/chunks/prepare.mjs:60:18)
  at async runCommand$1 (/D:/Kosta/Dev/NUXT/psn-galleries/node_modules/.pnpm/nuxi@3.17.1/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1643:16)
  at async runCommand$1 (/D:/Kosta/Dev/NUXT/psn-galleries/node_modules/.pnpm/nuxi@3.17.1/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1634:11)
  at async runMain$1 (/D:/Kosta/Dev/NUXT/psn-galleries/node_modules/.pnpm/nuxi@3.17.1/node_modules/nuxi/dist/shared/nuxi.BpXDZ4Tv.mjs:1772:7)



[14:53:42 ч.]  ERROR  Nuxt module should be a function: C:/Users/howbi/AppData/Roaming/npm/node_modules/@nuxt/devtools/module.cjs


 ELIFECYCLE  Command failed with exit code 1.

**Comment by danielroe** [comment]
Looks like you have an old global install of Nuxt Devtools.

Would you remove `C:/Users/howbi/AppData/Roaming/npm/node_modules/@nuxt/devtools`, and update your global `.nuxtrc` to remove it?
