### ISSUE TITLE
renderAndGetWindow and virtualConsole option

### ISSUE THREAD

**Issue by Perlover** [nuxt/nuxt#8262]
### Is your feature request related to a problem? Please describe.

I test a client part code under environment: Jest + Nuxt by using the method `renderAndGetWindow`. My project uses the Vuetify. But when i call:

```
let window = await nuxt.renderAndGetWindow(`${nuxtConfig.env.baseUrl}/`)
```

i got crash test because:

```
    console.log
      [error] Error: Could not parse CSS stylesheet
          at Object.<anonymous>.exports.createStylesheet (/home/perlover/src/my-project/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:34:21)
          at HTMLStyleElementImpl._updateAStyleBlock (/home/perlover/src/my-project/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:68:5)
          at HTMLStyleElementImpl._poppedOffStackOfOpenElements (/home/perlover/src/my-project/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:42:10)
          at OpenElementStack.Object.<anonymous>.OpenElementStack.pop (/home/perlover/src/my-project/node_modules/jsdom/lib/jsdom/browser/parser/html.js:43:12)
          at Object.endTagInText [as END_TAG_TOKEN] (/home/perlover/src/my-project/node_modules/parse5/lib/parser/index.js:2153:20)
          at Parser._processToken (/home/perlover/src/my-project/node_modules/parse5/lib/parser/index.js:657:55)
          at Parser._processInputToken (/home/perlover/src/my-project/node_modules/parse5/lib/parser/index.js:684:18)
          at Parser._runParsingLoop (/home/perlover/src/my-project/node_modules/parse5/lib/parser/index.js:440:18)
          at Parser.parse (/home/perlover/src/my-project/node_modules/parse5/lib/parser/index.js:344:14)
          at Object.parse (/home/perlover/src/my-project/node_modules/parse5/lib/index.js:10:19)
          at parseIntoDocument (/home/perlover/src/my-project/node_modules/jsdom/lib/jsdom/browser/parser/html.js:216:17)
          at parseIntoDocument (/home/perlover/src/my-project/node_modules/jsdom/lib/jsdom/browser/parser/index.js:31:10)
          at new JSDOM (/home/perlover/src/my-project/node_modules/jsdom/lib/api.js:42:5)
          at /home/perlover/src/my-project/node_modules/jsdom/lib/api.js:142:16
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
          at renderAndGetWindow (/home/perlover/src/my-project/node_modules/@nuxt/server/dist/server.js:122:22) .theme--light.v-application {
...
      .v-virtual-scroll__item {
        left: 0;
        position: absolute;
        right: 0;
      }
      /*# sourceMappingURL=vuetify.css.map*/

      at formatLogObj.width (node_modules/consola/dist/consola.js:1:15971)
```

This happens as i understand because the `cssom` module cannot parse CSS from Vuetify. I used a fresh version of `cssom` but it didn't helped to me. So i think `cssom` will not parse the Vueitify's CSS a long time yet.

After researching your code i cannot resolve this problem beause:

1) If i use `virtualConsole` option of `renderAndGetWindow` as `false` i get error from JSDOM that the virtualConsole should be object (it other problem of your doc - i cannot use virtualConsole as `false` but your doc tells to me that i can do it)
2) If i do my own instance of `virtualConsole` with ignoring of (`virtualConsole = new jsdom.VirtualConsole().sendTo(consola, { omitJSDOMErrors: true }) ... await nuxt.renderAndGetWindow(`${nuxtConfig.env.baseUrl}/`, {virtualConsole})` ) i got crash again because your code of `renderAndGetWindow` redefines `jsdomError` event by `on` calling to my instance to your `jsdomErrHandler` in anyway.

https://github.com/nuxt/nuxt.js/blob/dev/packages/server/src/jsdom.js#L45

### Describe the solution you'd like

I think the line https://github.com/nuxt/nuxt.js/blob/dev/packages/server/src/jsdom.js#L45 should be upped in block of `if` before https://github.com/nuxt/nuxt.js/blob/dev/packages/server/src/jsdom.js#L43 line. if you create an instance object of `virtualConsole` yourself, only in this case you should add handler `jsdomError` to it otherwise the developer is not able to fully use the option of `virtualConsole` for own instance.

**Comment by danielroe** [comment]
We are approaching the Nuxt 2 EOL date (June 30, 2024) - see [this article](https://nuxt.com/blog/nuxt2-eol) for more information. I'm closing this issue as it's marked as a _Nuxt 2 related enhancement_ and it's not a critical issue.

That doesn't mean it might not be relevant for Nuxt 3. If it is, please feel free to open a new issue (or just comment, and I can reopen it). 🙏

Thank you for your understanding and for your contribution to Nuxt! 🎉
